/**
 * Real questions for site-11-ui-header / header-capstone.
 * Anchor: remix/app/components/ui/Header.tsx —— 综合：导航 / auth / 主题 / 移动菜单 / a11y 五块的统一审视，以及「加一个新导航项」/「改鉴权」类整体改造练习
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/ui/Header.tsx";
const ROOT = "app/root.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const headerCapstoneQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 Header 总行数",
    prompt: "Header.tsx 总长约 ____ 行（写整数）。",
    options: [],
    blanks: [{ id: "v", placeholder: "数字", acceptedAnswers: ["236", "230"] }],
    correctAnswer: { type: "fill_blank", values: { v: "236" } },
    explanation: { short: "236 行——单一组件，导航 / auth / 移动菜单 / 内联 keyframes 全包；适度复杂度。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 Header 是否拆子组件更好",
    prompt: "Header 包含桌面导航 + 桌面登录态 + 移动汉堡 + 移动抽屉——是否应该拆成 4 个子组件？",
    options: [
      sc("A", "目前不必——四块共享 mobileMenuOpen / hoveredNav / fetcher / session 等多个上下文，拆分需要复杂 prop 传递；当前一文件 236 行可读；超过 400 行再考虑"),
      sc("B", "立刻拆"),
      sc("C", "永远不拆"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "拆分动机 = 文件过大或多处复用——当前没满足。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 桌面与移动版重复 user 卡片",
    prompt: "桌面端用户卡片（横向）vs 移动端用户卡片（纵向 in 抽屉）——两份代码几乎重复，要 DRY 吗？",
    options: [
      sc("A", "暂不——结构相似但布局父容器、间距、文字大小都不同；强抽组件需要复杂 props 切换 layout，反而难读；当前选「重复但直白」"),
      sc("B", "必须 DRY"),
      sc("C", "性能"),
      sc("D", "TypeScript 强制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "DRY 是手段不是目的——清晰胜过强制重用。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 加导航项「博客」全流",
    prompt: "想加一项 { name: '博客', href: '/blog' }。完整改动？",
    options: [
      sc("A", "1) Header.tsx navigation 数组加一项 → 桌面 + 移动菜单 map 自动渲 2) app/routes/blog.tsx 新建 3) 若需 SEO，加 meta；零改 root / Outlet context / 鉴权"),
      sc("B", "改 wrangler"),
      sc("C", "改 D1 schema"),
      sc("D", "改 auth"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "数据驱动 + 文件路由 = 加项 = 改数组 + 加文件。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/blog.tsx"],
  }),
  q({
    type: "single_choice", title: "Q5 加项 + 需要鉴权访问",
    prompt: "新加 /blog 必须登录才能看——改 Header 还是改路由？",
    options: [
      sc("A", "改 app/routes/blog.tsx 的 loader 内 await requireUser(request)；不改 Header——Header 只显示链接，鉴权落点是路由本身；分层各司其职"),
      sc("B", "改 Header"),
      sc("C", "改 root"),
      sc("D", "改 wrangler"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "鉴权 = 路由级 loader——不在 UI 层硬编码。" },
    abilityTags: ["bridge.reactRouter.loader", "backend.auth.required", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/blog.tsx"],
  }),
  q({
    type: "single_choice", title: "Q6 隐藏「未登录用户不该看」的导航项",
    prompt: "进一步：未登录用户不该看到 /blog 链接——逻辑放哪？",
    options: [
      sc("A", "Header 内 navigation 数组改成 (object with optional requiresAuth) + 渲染时 .filter(item => !item.requiresAuth || user)；UI 层根据 session 显隐"),
      sc("B", "改 wrangler"),
      sc("C", "改 root"),
      sc("D", "改 D1"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "可见性 = UI 层根据 session 过滤——结合数据驱动结构。" },
    abilityTags: ["frontend.state.global", "project.modify.fullstack", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 Header 是 client 还是 server",
    prompt: "Header 顶部 import { useState, useEffect } + useFetcher——它在哪运行？",
    options: [
      sc("A", "SSR 时也跑（只跑 render，不跑 effect/事件），客户端 hydrate 后接管；Remix 路由组件默认同构（isomorphic）；浏览器 API 必须在 useEffect 内"),
      sc("B", "只 client"),
      sc("C", "只 server"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix 组件 = 同构；effect/event 仅 client；纯渲染逻辑 SSR 也跑。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 Header 不加 .client 后缀",
    prompt: "Header.tsx 不带 .client 后缀——为什么 OK？",
    options: [
      sc("A", "Header 顶层无浏览器 API（document.body 等都在 useEffect 内，SSR 不跑）+ useState/useEffect 是同构 hook；SSR 安全；不需 .client 隔离"),
      sc("B", "应该加"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".client 后缀针对「文件级浏览器 API 污染」；Header 无此问题。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 useOutletContext 类型来源",
    prompt: "import type { AppOutletContext } from \"~/types/remix\";——为什么要单独一个 types 文件？",
    options: [
      sc("A", "Outlet context 形状由 root 决定但被多个子组件消费；放共享 types 避免循环 import + 让多组件类型一致；types/ 是项目类型 single source"),
      sc("B", "性能"),
      sc("C", "TypeScript 限制"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "共享类型 → 独立 types 文件——避免循环依赖。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/types/remix.ts"],
  }),
  q({
    type: "single_choice", title: "Q10 把 Header 改成 server-only",
    prompt: "假设把 Header 改成 server-rendered（无 hover 动画、无移动菜单 state、纯静态）——影响？",
    options: [
      sc("A", "失去 hover 滑动指示器、移动菜单展开、登录态实时更新等；客户端 JS 体积虽然小，但 UX 退化严重；与项目「现代 SPA 体验」定位不符"),
      sc("B", "更好"),
      sc("C", "无影响"),
      sc("D", "Cloudflare 强制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "纯 SSR Header = 静态导航；丢交互；不适合现代 SPA。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q11 桌面用户登录 + hover + 退出全流",
    prompt: "桌面用户首次访问 → 登录 → hover 'music' → 退出。完整 step？",
    options: [
      sc("s1", "1. SSR：root loader session=null → Header 渲染登录按钮"),
      sc("s2", "2. 用户点击「登录 →」→ openLoginDialog() 触发 root 内 LoginDialog state 变 true → Modal 弹出"),
      sc("s3", "3. 登录成功 → root revalidate → Outlet context.session 更新 → Header 重渲染显示用户卡片"),
      sc("s4", "4. 用户 hover music Link → setHoveredNav('音乐之旅') → m.span 用 layoutId 滑入"),
      sc("s5", "5. 用户点击「退出」→ fetcher.submit(null, ...) → 按钮 disabled 显示「退出中」"),
      sc("s6", "6. /auth/sign-out action 销毁 session + Set-Cookie 清"),
      sc("s7", "7. fetcher 完成 → root revalidate → session=null → Outlet context 更新"),
      sc("s8", "8. Header 重渲染回登录按钮态"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8"] },
    explanation: { short: "Header 完整生命周期 8 步——SSR + 登录 + hover + 退出循环。" },
    abilityTags: ["frontend.event.click", "frontend.state.global", "bridge.reactRouter.action", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, ROOT],
  }),
  q({
    type: "single_choice", title: "Q12 Header 改用 React Server Component",
    prompt: "如果迁到 React 19 RSC（Server Components）——Header 应是 server 还是 client？",
    options: [
      sc("A", "client——Header 含 useState（hover/menu）+ useFetcher + useEffect 副作用；这些都是 client-only hooks；RSC 下必须 \"use client\""),
      sc("B", "server"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "状态 + effect + 事件 = 强制 client component。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 Header 测试策略",
    prompt: "想给 Header 加单元测试——重点测什么？",
    options: [
      sc("A", "1) 未登录态显示「登录」按钮 2) 已登录态显示用户卡片 + 用户名 fallback 链 3) 汉堡点击 → 菜单展开 4) Esc 关菜单 5) 退出 fetcher 调对 action；mock outletContext 与 fetcher"),
      sc("B", "只测样式"),
      sc("C", "无需测"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Header 测试 = 状态分支 + 副作用调用 + 键盘交互；样式不在重点。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 性能瓶颈",
    prompt: "Header 性能潜在瓶颈在哪？",
    options: [
      sc("A", "hoveredNav 频繁 setState（每次进出 Link 都重渲整个 Header），但 React 内部渲染 7 个 Link 成本极低；实际无瓶颈；过早优化是反模式"),
      sc("B", "致命"),
      sc("C", "需 memo 全部"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "小组件高频 setState 实测无问题；profiler 才是判官，不是直觉。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 修复 a11y 缺口的优先级",
    prompt: "a11y 缺口（focus trap / skip-link / sr-only 语言不一致）——哪个最该先修？",
    options: [
      sc("A", "skip-link 最简单且全站受益；focus trap 需要 JS 库且只影响打开抽屉的少数用户；sr-only 文案是字符串改一行——按 ROI 顺序：sr-only 文案 → skip-link → focus trap"),
      sc("B", "全部并发"),
      sc("C", "无需修"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "a11y 改进按 ROI 排序——简单收益大者先行。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 Header 的状态范围",
    prompt: "Header 有 mobileMenuOpen + hoveredNav 两个 useState——为什么这两个一个不上 root？",
    options: [
      sc("A", "都是 Header 局部交互状态——别处无人需要；上提到 root context 会污染全局且无意义；状态作用域 = 谁需要就放谁那；最小作用域原则"),
      sc("B", "全局更好"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "状态最小作用域 = 易维护；不要无意义上提。" },
    abilityTags: ["frontend.state.local", "frontend.state.scope", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 contrast：session 在 root 而不是 Header useState",
    prompt: "对比：session 在 root（context 注入）而非 Header useState——这与 Q16 矛盾吗？",
    options: [
      sc("A", "不矛盾——session 多组件需要（Header + 内容页 + Footer）→ 上提；mobileMenuOpen 仅 Header 需要 → 不上提；准则：「谁用上提到谁的最近共同祖先」"),
      sc("B", "矛盾"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "状态作用域 = 跟随消费者；session 全局 + mobileMenuOpen 局部。" },
    abilityTags: ["frontend.state.scope", "frontend.state.global", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, ROOT],
  }),
  q({
    type: "single_choice", title: "Q18 多语言 i18n",
    prompt: "若做 i18n（中/英），Header 内 「个人简历」 等怎么处理？",
    options: [
      sc("A", "navigation 数组改成 { id: 'cv', href: '/cv' } 等 id；渲染时用 i18n hook t(`nav.${item.id}`)；翻译文件统一管理；UI 文本与代码解耦"),
      sc("B", "复制文件"),
      sc("C", "不支持"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "i18n 设计 = 文本与代码解耦；navigation 用 id 不写文本。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 Header 给 SSR 输出贡献",
    prompt: "Header 在 SSR HTML 里贡献什么？",
    options: [
      sc("A", "完整 nav 结构（链接 a 标签）+ 用户卡片或登录按钮（取决于 session）+ 移动汉堡按钮；不含抽屉（mobileMenuOpen=false）；不含 hover 指示器（hoveredNav=null）"),
      sc("B", "空白"),
      sc("C", "只 nav"),
      sc("D", "全 DOM"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SSR 渲染 useState 初值——隐藏的条件分支不在 HTML。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 客户端 hydrate 失败 fallback",
    prompt: "若 client JS 加载失败（网络中断），Header 还能用吗？",
    options: [
      sc("A", "导航 Link 退化为 <a href> 仍可用；登录按钮变成普通 button 但 onClick 不触发——LoginDialog 没法弹（依赖 root state）；移动菜单不可开；基础导航能用，交互全失"),
      sc("B", "完全 OK"),
      sc("C", "完全废"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "渐进增强：HTML 导航能用 + JS 增强失败丢交互——SSR 优势。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 Header 改造：在 sticky 顶部",
    prompt: "想让 Header sticky 顶部——改 Header 还是 root.tsx Layout？",
    options: [
      sc("A", "Header 的根元素 <header> 加 className=\"sticky top-0 z-40\"；不必动 root；样式作用域属于 Header 自己"),
      sc("B", "改 root"),
      sc("C", "改 wrangler"),
      sc("D", "tailwind 全局"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "样式属于谁就改谁——Header 自治。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 Header 整体设计哲学",
    prompt: "Header.tsx 整体设计哲学（一站式总结）？",
    options: [
      sc("A", "1) 数据驱动 navigation 数组 + Link prefetch=intent 体验 2) framer LazyMotion + 共享 layoutId 高质感 hover 3) session 走 Outlet context 单一全局来源；Header 不复制 4) 退出用 fetcher 不动 history；状态文案 + disabled 5) 移动菜单单 state + cleanup 严格的副作用 6) ARIA modal 三件套 + 键盘等价；缺口已识别 7) 主题不在 Header 由 root + cookie 处理——综合：「轻 Header + 重 root，分层 + 数据驱动 + 渐进增强 + a11y 优先」"),
      sc("B", "纯 UI"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Header 7 原则 = 现代 SPA Header 的标杆范式。" },
    abilityTags: ["ai.review.architecture", "frontend.state.global", "frontend.state.scope", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, ROOT, "app/types/remix.ts"],
  }),
];
