/**
 * Real questions for site-11-ui-header / header-auth.
 * Anchor: remix/app/components/ui/Header.tsx —— useOutletContext<AppOutletContext>() + openLoginDialog + useFetcher 退出 + getUserDisplayName/getUserInitial
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/ui/Header.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const headerAuthQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 useOutletContext 类型",
    prompt: "const { session, openLoginDialog } = useOutletContext<____>();",
    options: [],
    blanks: [{ id: "v", placeholder: "类型名", acceptedAnswers: ["AppOutletContext"] }],
    correctAnswer: { type: "fill_blank", values: { v: "AppOutletContext" } },
    explanation: { short: "AppOutletContext 来自 ~/types/remix——root <Outlet context={...} /> 注入的形状。" },
    abilityTags: ["bridge.reactRouter.loader", "frontend.state.global"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/types/remix.ts"],
  }),
  q({
    type: "single_choice", title: "Q2 useOutletContext 数据来源",
    prompt: "useOutletContext<AppOutletContext>() 返回的 { session, openLoginDialog } 哪来？",
    options: [
      sc("A", "root.tsx 内 <Outlet context={contextValue} /> 注入——contextValue 在 root 组件内组装：session 来自 root loader（cookie 查 Better Auth），openLoginDialog 是 root 内一个 useState 控制的回调"),
      sc("B", "全局变量"),
      sc("C", "props"),
      sc("D", "URL"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Outlet context 是 RR7 标准的「父→子嵌套路由」共享 channel。" },
    abilityTags: ["bridge.reactRouter.loader", "frontend.state.global", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q3 const user = session?.user",
    prompt: "const user = session?.user;——为什么用可选链？",
    options: [
      sc("A", "session 可能为 null（未登录或 Better Auth 查询失败）；不用 ?. 直接 .user 会运行时 TypeError；可选链是 nullable 上层数据的标准防御"),
      sc("B", "性能"),
      sc("C", "TypeScript 限制"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "可选链 = nullable 链路的安全访问；undefined 比 throw 友好。" },
    abilityTags: ["ai.review.architecture", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 三元渲染 !user ? 登录按钮 : 用户卡片",
    prompt: "{!user ? <button>登录</button> : <div>{用户卡片}</div>}——这种渲染分支的好处？",
    options: [
      sc("A", "登录态决定 UI 形状（按钮 vs 卡片差异大）→ 用条件渲染选择整块；两个分支都被 React 知道，不会闪现错误状态；vs CSS hidden 切换会同时渲两份增加 DOM 噪音"),
      sc("B", "性能更差"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "形状差异大用条件渲染——比 CSS hidden 更干净。" },
    abilityTags: ["frontend.state.global", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 openLoginDialog onClick",
    prompt: "<button onClick={() => openLoginDialog()} ...>登录 →</button>——为什么不直接 onClick={openLoginDialog}？",
    options: [
      sc("A", "等价但有 trap：onClick 默认接收 SyntheticEvent 作首参，若 openLoginDialog 签名后续改成 (options?: { redirectTo?: string }) 会被事件对象误传；箭头包一层 = 签名隔离"),
      sc("B", "完全等价无理由"),
      sc("C", "随机"),
      sc("D", "TypeScript 强制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "包一层 = 防止事件对象作为参数误传——抗未来签名变化。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 getUserDisplayName 三级 fallback",
    prompt: "user.name || user.email?.split('@')[0] || 'User'——为什么三级 fallback？",
    options: [
      sc("A", "name 不一定填；email 不一定有；最末 'User' 兜底；OAuth 登录可能只返 email、邮箱登录可能只有用户名前缀；三级让 UI 总有可显示文本"),
      sc("B", "TypeScript 限制"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "auth 字段是 nullable 联合——多级 fallback = 鲁棒 UI。" },
    abilityTags: ["ai.review.architecture", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 getUserInitial",
    prompt: "displayName?.charAt(0).toUpperCase() || 'U'——为什么 toUpperCase？",
    options: [
      sc("A", "头像首字母统一大写——用户输入 'gregor' 与 'Gregor' 视觉一致；UI 一致性细节"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "首字母头像统一大写 = 视觉一致。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 useFetcher 退出登录",
    prompt: "const fetcher = useFetcher(); ... fetcher.submit(null, { method: 'post', action: '/auth/sign-out' })——为什么用 fetcher 不用 <Form>？",
    options: [
      sc("A", "退出登录是「副作用 + 不刷页」——fetcher 不改 navigation 历史栈；<Form> 会进栈，浏览器后退会回到「已退出」前页面但 session 已没——状态不一致"),
      sc("B", "性能更好"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "无导航语义的写 = fetcher；fetcher 不动历史栈。" },
    abilityTags: ["frontend.event.submit", "bridge.reactRouter.action", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 fetcher.submit(null, ...)",
    prompt: "fetcher.submit(null, { method: 'post', action: '/auth/sign-out' })——首参 null 含义？",
    options: [
      sc("A", "不传 form 数据——退出不需要任何 body；服务端只需 session cookie 来识别用户；首参可以是 FormData / 对象 / null；null 显式表示「无 body」"),
      sc("B", "报错"),
      sc("C", "默认"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "fetcher.submit(null) = 无 body 的 POST。" },
    abilityTags: ["frontend.event.submit", "bridge.reactRouter.action"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 fetcher.state",
    prompt: "disabled={fetcher.state !== 'idle'}——fetcher.state 取值？",
    options: [
      sc("A", "'idle' | 'submitting' | 'loading' —— submitting 是发送中、loading 是 action 完成等 revalidate；非 idle 全 disabled = 一次请求期间不可重复点击"),
      sc("B", "boolean"),
      sc("C", "string"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "fetcher.state 三态——非 idle = 进行中。" },
    abilityTags: ["frontend.event.submit", "bridge.reactRouter.action", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 「退出中」按钮文案",
    prompt: "{fetcher.state !== 'idle' ? '退出中' : '退出'}——这种状态文案的好处？",
    options: [
      sc("A", "用户得知请求进行中——避免「点了没反应」错觉再次点击；副作用按钮的「执行中态」+ disabled 是 UI 正确性铁律"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "副作用按钮：disabled + 文案变化 = 用户即时反馈。" },
    abilityTags: ["frontend.event.submit", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 data-auth-target 属性",
    prompt: "<button data-auth-target=\"true\" ...> 与 <div data-auth-target=\"true\" ...>——这个 data-* 属性作用？",
    options: [
      sc("A", "项目自定义钩子——root 内 LoginDialog 关闭时可能用 querySelector('[data-auth-target=\"true\"]') 把焦点还给登录按钮（accessibility focus restore）；DOM 钩子约定"),
      sc("B", "TypeScript 标记"),
      sc("C", "样式"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "data-* = 项目自定义 DOM 钩子；常见于焦点管理 / 测试定位。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q13 用户头像首字母方块",
    prompt: "<div className=\"flex h-8 w-8 ... rounded-full bg-primary-950 ...\">{getUserInitial()}</div>——为什么不用 <img>？",
    options: [
      sc("A", "项目无 OAuth 头像 URL 字段；用首字母 + 主色块作为视觉占位——简单、零网络请求、无 broken image 风险；许多产品 fallback 都用这套"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "首字母色块 = 无图源场景的标配 fallback。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 truncate text-sm",
    prompt: "<p className=\"max-w-36 truncate text-sm font-semibold ...\">{getUserDisplayName()}</p>——max-w-36 + truncate 的意图？",
    options: [
      sc("A", "限制最大宽度 + 文本溢出省略号——防止长邮箱（aaaaaa@example.com）撑破 Header 布局；UI 防御性约束"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "外部数据宽度未知 = max-w + truncate 兜底。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q15 用户点击退出全流",
    prompt: "已登录用户在 Header 点「退出」，步骤？",
    options: [
      sc("s1", "1. 用户点击 button 触发 handleSignOut"),
      sc("s2", "2. fetcher.submit(null, { method: 'post', action: '/auth/sign-out' })"),
      sc("s3", "3. fetcher.state 变 'submitting'，按钮 disabled + 显示「退出中」"),
      sc("s4", "4. Worker 收 POST /auth/sign-out，进对应 action"),
      sc("s5", "5. action 销毁 session（D1 删 session 行 + 返 Set-Cookie 清 auth cookie）"),
      sc("s6", "6. fetcher 收响应——RR7 自动 revalidate root loader"),
      sc("s7", "7. root loader 重读 cookie 没了 → session = null"),
      sc("s8", "8. Outlet context 重新注入 session=null → Header 三元分支切回登录按钮"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8"] },
    explanation: { short: "退出全链：fetcher → action 销毁 → Set-Cookie 清 → revalidate → UI 切换。" },
    abilityTags: ["frontend.event.submit", "bridge.reactRouter.action", "backend.session.cookie", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q16 不在 Header 写 useState 存 session",
    prompt: "Header 不自己 useState 缓存 session——为什么？",
    options: [
      sc("A", "session 是全局共享状态，多组件需要（Header / 内容页 / Footer）；本地 state 会导致退出后某些组件没拿到通知；走 root loader + Outlet context 让所有组件统一刷新"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "全局共享数据 → 全局来源；不要在子组件复制全局状态。" },
    abilityTags: ["frontend.state.global", "frontend.state.scope", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q17 退出按钮 disabled 但不卸载",
    prompt: "为什么退出过程中只 disabled 而不直接消失？",
    options: [
      sc("A", "卸载会触发 layout shift（按钮原位置塌陷）；disabled 保留位置 + 灰显 = 视觉稳定；UI 改变最小化原则"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loading 状态保留布局 = 减少视觉跳动。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 加「我的设置」入口",
    prompt: "想在已登录卡片旁加「设置」链接 → /settings。改动面？",
    options: [
      sc("A", "Header 在 user 分支内多加一个 <Link to=\"/settings\">；前提 app/routes/settings.tsx 已存在；零改 root / loader / context"),
      sc("B", "改 root"),
      sc("C", "改 wrangler"),
      sc("D", "改 D1"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "纯 UI 加链接 = 局部改 Header；Outlet context 已包含所需数据。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 错误处理缺失",
    prompt: "退出按钮逻辑只 fetcher.submit + disabled 没 catch；万一 sign-out action 报 500？",
    options: [
      sc("A", "fetcher.state 会回 idle 但 fetcher.data 携带错误响应；当前代码没显示错误——session 依然有效但 UI 没提示；改进：监听 fetcher.data?.error 显 toast；可观测缺失"),
      sc("B", "永远成功"),
      sc("C", "Cloudflare 处理"),
      sc("D", "无问题"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "fetcher 错误需主动处理——否则用户看不到失败原因。" },
    abilityTags: ["frontend.event.submit", "ai.review.architecture", "bridge.reactRouter.action"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 同时桌面端与移动端两套 user UI",
    prompt: "桌面端用户卡片 + 移动菜单内也有用户卡片——两份代码重复，为什么不抽组件？",
    options: [
      sc("A", "结构相似但样式与父布局完全不同（横向 vs 纵向）；硬抽组件需要复杂 props 控制差异，反而比两份直白代码更难读；项目当前选「重复但清晰」"),
      sc("B", "性能"),
      sc("C", "TypeScript 强制"),
      sc("D", "TypeScript 不允许"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "重复 vs 抽象的取舍——清晰胜于强制 DRY。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 useFetcher 与 useNavigation 区别",
    prompt: "为什么用 useFetcher 而不是 useNavigation 监控退出状态？",
    options: [
      sc("A", "useFetcher 是「这个具体 fetcher」的状态；useNavigation 是「全局当前 navigation」的状态。退出按钮需要按本按钮的请求 disabled，而非全局——fetcher 是细粒度匹配"),
      sc("B", "完全等价"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "fetcher = 本地写操作；navigation = 全局导航——按需选。" },
    abilityTags: ["bridge.reactRouter.action", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 Header auth 部分整体哲学",
    prompt: "Header auth 部分整体哲学？",
    options: [
      sc("A", "1) session 走 root → Outlet context（全局单一来源）2) 三元渲染按登录态切两种 UI 形状 3) 用户名三级 fallback 鲁棒展示 4) 退出用 fetcher 不动 history 5) fetcher.state + 文案 + disabled 给副作用按钮明确反馈 6) 不在 Header 复制 session 状态 7) data-auth-target 留焦点恢复钩子——综合：轻 Header + 重 root 的 auth 分层"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Header auth 7 原则——单一来源 + 形状切换 + 副作用细节体验。" },
    abilityTags: ["frontend.state.global", "bridge.reactRouter.action", "ai.review.architecture", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
];
