/**
 * Real questions for site-11-ui-header / header-nav.
 * Anchor: remix/app/components/ui/Header.tsx —— navigation 数组 + Link prefetch="intent" + LazyMotion m.span layoutId 滑动指示器
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/ui/Header.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const headerNavQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 navigation 数组长度",
    prompt: "Header.tsx 顶部 const navigation = [{name:'个人简历',href:'/cv'}, ...]——一共 ____ 项导航。",
    options: [],
    blanks: [{ id: "v", placeholder: "数字", acceptedAnswers: ["7", "七"] }],
    correctAnswer: { type: "fill_blank", values: { v: "7" } },
    explanation: { short: "7 条：cv / gallery / music / game / chat / anime / updates。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 navigation 为什么写在组件外",
    prompt: "const navigation = [...] 写在 export default function 之外——为什么不放进组件？",
    options: [
      sc("A", "数组是静态常量——放外面只创建一次；放组件内每次 render 都重新构造新数组（虽然内容相同）会让 React.memo / Link 的浅比较失效；性能 + 引用稳定性"),
      sc("B", "TypeScript 强制"),
      sc("C", "随机习惯"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "静态常量提升到模块作用域 = 引用稳定 + 一次构造。" },
    abilityTags: ["frontend.state.scope", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 prefetch='intent'",
    prompt: "<Link to={item.href} prefetch=\"intent\" ...>——prefetch='intent' 的意图？",
    options: [
      sc("A", "Remix 在用户「显出意图」（hover/focus）时预取目标路由的 loader 数据 + JS chunk；点击时几乎瞬时切换；vs prefetch='render' 全量预取浪费带宽"),
      sc("B", "永远预取"),
      sc("C", "只在生产"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "prefetch='intent' = hover/focus 触发预取——延迟与带宽的折中。" },
    abilityTags: ["ai.review.architecture", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 navigation.map 渲染",
    prompt: "{navigation.map((item) => <Link key={item.name} to={item.href} ... />)}——key 用 item.name 而不是 index？",
    options: [
      sc("A", "name 在数组里唯一且稳定——用 index 当 key，将来若数组重排（如管理后台拖拽），React 会复用错节点导致 DOM 状态错位；React 的 key 铁律：稳定唯一标识"),
      sc("B", "随机习惯"),
      sc("C", "TypeScript 要求"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "key 必须是稳定唯一标识——name 比 index 更安全。" },
    abilityTags: ["ai.review.architecture", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 hoveredNav state",
    prompt: "const [hoveredNav, setHoveredNav] = useState<string | null>(null);——state 类型是 string | null 而不是 string？",
    options: [
      sc("A", "null 表示「没有任何项被 hover」——初始状态 + onMouseLeave 时复位；用 string '' 也能但语义弱（空字符串 vs 真空），null 让条件 hoveredNav === item.name 永远准确"),
      sc("B", "TypeScript 限制"),
      sc("C", "性能"),
      sc("D", "习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "null 是「无值」的精确语义——优于空字符串。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 LazyMotion + domAnimation",
    prompt: "<LazyMotion features={domAnimation}>——为什么不直接 import { motion }？",
    options: [
      sc("A", "LazyMotion + domAnimation 让 framer-motion 按需打包——只引入「DOM 动画」的子集（~15kb 而非全包 30kb+）；首屏 JS 体积优化"),
      sc("B", "TypeScript 限制"),
      sc("C", "Cloudflare 强制"),
      sc("D", "习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "LazyMotion = framer-motion 的 tree-shake 友好入口。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 m.span vs motion.span",
    prompt: "<m.span layoutId=\"nav-motion-line\" .../>——m 来自 import { m }；和 motion 的区别？",
    options: [
      sc("A", "m 是 LazyMotion 配套的「轻量 motion 组件」——本身不带动画 features；features 由父 LazyMotion 注入；vs motion 自带全部 features 不能 tree-shake"),
      sc("B", "完全等价"),
      sc("C", "TypeScript"),
      sc("D", "随机命名"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "m + LazyMotion = 体积最优搭配。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 layoutId 共享",
    prompt: "{hoveredNav === item.name && <m.span layoutId=\"nav-motion-line\" ... />}——所有 Link 共用同一 layoutId？",
    options: [
      sc("A", "对——同一 layoutId 让 framer 在不同 Link 间执行 FLIP 动画（指示器从上一个位置「滑到」下一个）；不同 id 会变成淡入淡出而非滑动；这是关键"),
      sc("B", "id 必须唯一"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "共享 layoutId = framer 的 shared-layout transition 机制。" },
    abilityTags: ["ai.review.architecture", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 spring transition 参数",
    prompt: "transition={{ type: \"spring\", stiffness: 520, damping: 42, mass: 0.65 }}——这套参数手感？",
    options: [
      sc("A", "高 stiffness + 中 damping + 较低 mass——动画快、稳、轻；适合导航这种需要「立即反应」的小元素；vs 低 stiffness 拖沓（适合大块内容）"),
      sc("B", "随机数字"),
      sc("C", "默认值"),
      sc("D", "TypeScript 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "spring 三参数的取舍体现在最终手感——快 + 稳 + 轻 = 导航场景。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 onMouseLeave 在父 div",
    prompt: "<div className=\"hidden lg:flex lg:gap-2\" onMouseLeave={() => setHoveredNav(null)}>——为什么在父 div 而不是每个 Link？",
    options: [
      sc("A", "鼠标在 Link 之间移动时，逐个 Link 的 mouseleave 会触发 → null → 下个 mouseenter 又设值；中间一帧空白让指示器闪烁；放父 div 上整体退出才复位，滑动连贯"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "事件域选父级 = 避免子元素切换时的中间空状态。" },
    abilityTags: ["frontend.event.click", "frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 onFocus + onBlur",
    prompt: "Link 绑了 onMouseEnter / onFocus 设值 + onBlur 清；为什么要 focus 也触发？",
    options: [
      sc("A", "键盘用户用 Tab 不发出 mouseenter——只 hover 不绑 focus 会让滑动指示器对键盘用户消失；可访问性铁律：hover 效果同时支持 focus"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "hover + focus 双绑 = 键盘可达性。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 hidden lg:flex",
    prompt: "<div className=\"hidden lg:flex lg:gap-2\">——hidden lg:flex 含义？",
    options: [
      sc("A", "Tailwind 响应式：默认 display:none；lg 断点（≥1024px）改 flex；移动端隐藏整条桌面导航，让位给汉堡按钮——一套 Header 双视图"),
      sc("B", "永远 hidden"),
      sc("C", "永远 flex"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Tailwind 响应式前缀 = 同 DOM 双视图。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 ui-nav-link className",
    prompt: "className=\"ui-nav-link ui-nav-link--motion\"——这是 Tailwind 还是 CSS 类？",
    options: [
      sc("A", "应用层级 utility 类——在 app/styles/ 或 tailwind.config 的 components 层定义；把多个 Tailwind 工具类聚合命名，避免 className 字符串爆炸 + 跨组件复用"),
      sc("B", "纯 Tailwind"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ui-* 前缀 = 项目自定义复合类——抽象常用样式组合。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/styles/"],
  }),
  q({
    type: "branch_trace", title: "Q14 用户 hover 第三个导航项流程",
    prompt: "桌面用户从 cv 移到第 3 个 Link 'music'，步骤？",
    options: [
      sc("s1", "1. 鼠标进入 'music' Link"),
      sc("s2", "2. onMouseEnter 触发 setHoveredNav('音乐之旅')"),
      sc("s3", "3. React 重渲染该 Link 子树——条件 hoveredNav === item.name 真"),
      sc("s4", "4. <m.span layoutId=\"nav-motion-line\" /> 在新位置挂载"),
      sc("s5", "5. framer 检测 layoutId 已存在于 cv Link → 执行 FLIP 动画从旧位置滑入新位置"),
      sc("s6", "6. spring transition 参数控制运动手感（stiffness 520 + damping 42）"),
      sc("s7", "7. 用户视觉上看到指示器横向滑动"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7"] },
    explanation: { short: "FLIP 动画的完整链——React 重渲 + framer layoutId 接管动画。" },
    abilityTags: ["frontend.event.click", "frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 加新导航项",
    prompt: "想新增 '/blog' 导航项。改动？",
    options: [
      sc("A", "仅改 navigation 数组，加 { name: '博客', href: '/blog' }——map 自动渲染；前提：app/routes/blog.tsx 已存在；零改 JSX"),
      sc("B", "改 root.tsx"),
      sc("C", "改 wrangler"),
      sc("D", "新建组件"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "数据驱动渲染的好处——加项 = 改数组。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 prefetch 改 'render'",
    prompt: "把 prefetch='intent' 改成 prefetch='render' 影响？",
    options: [
      sc("A", "首屏挂载就预取所有 7 个导航目标的 loader+chunk——浪费带宽（用户大概率不点全部）；移动端尤其明显；intent 是更优默认"),
      sc("B", "无影响"),
      sc("C", "性能更好"),
      sc("D", "TypeScript 报错"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "prefetch='render' 太激进——intent 是带宽友好的默认。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q17 layoutId 唯一性",
    prompt: "判断：每个 m.span 都应该有不同的 layoutId 才是正确做法。",
    correctAnswer: { value: false },
    explanation: { short: "错——共用同一 layoutId 才能触发 framer 的 shared-layout 滑动；不同 id 退化为淡入淡出。" },
    abilityTags: ["ai.review.architecture", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 删 onMouseLeave 父级",
    prompt: "如果删掉父 div 的 onMouseLeave={() => setHoveredNav(null)}，结果？",
    options: [
      sc("A", "鼠标移出整个导航栏后 hoveredNav 仍保留最后一项的值——指示器留在最后停留的位置不会消失；视觉上「卡住」"),
      sc("B", "无影响"),
      sc("C", "崩溃"),
      sc("D", "TypeScript 报错"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "缺 onMouseLeave = 状态没被复位，指示器留痕。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 从 useState 换 useReducer",
    prompt: "如果用 useReducer 替代 useState 管理 hoveredNav——值得吗？",
    options: [
      sc("A", "不值——只有一个 string|null 状态、一种 set 操作；reducer 增加间接层而无收益；reducer 适合多动作多状态字段同步更新的场景"),
      sc("B", "永远更好"),
      sc("C", "TypeScript 要求"),
      sc("D", "性能更好"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useState vs useReducer 选择 = 状态复杂度匹配。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 Link 而不是 a",
    prompt: "用 <Link to=...> 而不是原生 <a href=...>——为什么？",
    options: [
      sc("A", "Link 触发 client-side 路由切换：不刷新页面、共享 SSR 后 hydrated 的 React 树、配合 prefetch；<a> 触发整页重新加载——丢状态、慢"),
      sc("B", "TypeScript 限制"),
      sc("C", "完全等价"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Link = SPA 路由；<a> = 整页跳转——SPA 体验铁律。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 navigation 数据外提",
    prompt: "若想让 navigation 数组在多处复用（移动端菜单、footer、sitemap）。改动？",
    options: [
      sc("A", "抽到 app/data/navigation.ts 导出 NAVIGATION 常量；Header / footer / sitemap 各自 import；单一来源——加项时一处改"),
      sc("B", "复制三份"),
      sc("C", "用 context"),
      sc("D", "塞 root loader"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "纯静态数据 → 模块常量 import；context 是动态/作用域数据的工具。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/data/navigation.ts"],
  }),
  q({
    type: "single_choice", title: "Q22 导航部分整体哲学",
    prompt: "桌面导航这部分整体哲学？",
    options: [
      sc("A", "1) 数据驱动——navigation 数组定 7 项，map 渲染 2) 模块作用域常量保稳定引用 3) Link + prefetch='intent' 体验与带宽折中 4) hoveredNav 单 state + 共享 layoutId 实现滑动指示器 5) 父级 onMouseLeave 避免闪烁 6) hover/focus 双绑兼顾键盘 7) LazyMotion + m 优化 framer 体积——综合：数据 + 体验 + 性能三方平衡"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "导航 7 原则——数据驱动 + 极致体验 + 体积优化的范式。" },
    abilityTags: ["ai.review.architecture", "frontend.state.local", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
];
