/**
 * Real questions for site-11-ui-header / header-a11y.
 * Anchor: remix/app/components/ui/Header.tsx —— sr-only / aria-* / role="dialog" aria-modal / 键盘可达 / prefers-reduced-motion / button 语义
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/ui/Header.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const headerA11yQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 nav aria-label",
    prompt: "<nav aria-label=\"____\" className=\"...\">",
    options: [],
    blanks: [{ id: "v", placeholder: "label", acceptedAnswers: ["Global"] }],
    correctAnswer: { type: "fill_blank", values: { v: "Global" } },
    explanation: { short: "aria-label=\"Global\" 标识这是站点全局导航——区别于页内局部导航。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 sr-only span",
    prompt: "<span className=\"sr-only\">Open main menu</span>——sr-only 含义？",
    options: [
      sc("A", "Tailwind 工具类——视觉隐藏但屏幕阅读器仍可读；汉堡按钮只显图标 ☰，无文字标签时屏幕阅读器只听到「按钮」无意义；sr-only 文本补充语义"),
      sc("B", "完全隐藏"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "sr-only = 视觉隐藏 + 阅读器可读——图标按钮的标准 a11y 配套。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 aria-hidden 在装饰图标",
    prompt: "<span aria-hidden=\"true\" className=\"...\">☰</span>——aria-hidden 必要？",
    options: [
      sc("A", "图标 ☰ 是装饰性视觉——屏幕阅读器读「汉堡 emoji 字符」无意义且与 sr-only 文本重复；aria-hidden=true 让阅读器跳过这个 span 只读 sr-only 内的「Open main menu」"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "装饰图标 → aria-hidden=true 让阅读器只听有意义的文本。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 role=\"dialog\" aria-modal=\"true\"",
    prompt: "<div className=\"lg:hidden\" role=\"dialog\" aria-modal=\"true\" aria-label=\"移动端导航菜单\">——三个属性意图？",
    options: [
      sc("A", "role=\"dialog\" 告知阅读器「这是对话框」；aria-modal=\"true\" 告知「焦点应被捕获在内部」；aria-label 给对话框命名；三件套是 modal/drawer 的 ARIA 标准"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "modal 三件套——role + aria-modal + aria-label。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 button 而非 div 做遮罩",
    prompt: "<button type=\"button\" className=\"fixed inset-0 ... cursor-default ...\" onClick={...} aria-label=\"关闭菜单\" />——为什么用 button 不用 div？",
    options: [
      sc("A", "可点击元素必须是语义化按钮——键盘用户能 Tab 到 + 回车空格触发 + 屏幕阅读器读为「按钮」；用 div + onClick 没有键盘可达性；button + aria-label 完整语义"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "样式"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "可点击 = button 语义；div onClick 是 a11y 反模式。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 cursor-default 在 button",
    prompt: "<button ... className=\"... cursor-default ...\" />——为什么把 button 的鼠标样式改回 default？",
    options: [
      sc("A", "遮罩本身是「点击关闭」的视觉空白——用默认箭头比 pointer 手势更符合「无明显交互的留白」预期；button 默认 cursor:pointer 在这里多余"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "保留 button 语义但视觉上像普通遮罩 = 兼顾 a11y 与设计意图。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 type=\"button\" 必加",
    prompt: "<button type=\"button\" ...>——type 属性必加？",
    options: [
      sc("A", "在 <form> 内 button 默认 type=\"submit\"——会触发 form 提交；纵使本组件无 form，写明 type=\"button\" 是防御性编程，避免日后被包进 form 时意外触发提交"),
      sc("B", "可省"),
      sc("C", "TypeScript 强制"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "button 不加 type 默认 submit——一律显式写 type=\"button\"。" },
    abilityTags: ["ai.review.architecture", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 onFocus 配 hover",
    prompt: "桌面 Link 同时绑了 onMouseEnter 和 onFocus——前面 nav 课已经讲过；这是哪种 a11y 原则？",
    options: [
      sc("A", "「鼠标交互必须有键盘等价」——hover 触发的视觉反馈，对 Tab 键移动焦点的用户也要有；WCAG 2.1.1 键盘可达性"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "WCAG 键盘等价原则——hover ↔ focus 双绑。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 prefers-reduced-motion 适配",
    prompt: "<style>{` @media (prefers-reduced-motion: reduce) { ... animation: none; } `}</style>——这是 a11y 哪一类？",
    options: [
      sc("A", "「尊重用户设置」类——前庭功能障碍用户在系统设置开「减少动画」时，UI 应自觉关动画；强制全员看动画 = a11y 失败"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "尊重用户系统级偏好 = a11y 高阶要求。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 Esc 关菜单 a11y",
    prompt: "Esc 键关闭菜单——这是 a11y 的哪条？",
    options: [
      sc("A", "ARIA Authoring Practices 的「Modal Dialog」模式：Esc 必须能关；不带 Esc 的 modal 让键盘用户陷入——必须 Tab 找关闭按钮再回车"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ARIA Modal pattern 强制 Esc 关——键盘用户最短退出路径。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 缺失：focus trap",
    prompt: "当前 Header 实现的 ARIA dialog 缺了什么？",
    options: [
      sc("A", "焦点陷阱（focus trap）——aria-modal=\"true\" 暗示焦点应被锁在对话框内，Tab 在最后一项后该回到第一项；当前实现无 trap 实现，键盘可 Tab 到背景；严格符合需要 focus-trap 库"),
      sc("B", "完全合规"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "aria-modal 是声明，不会自动实现 focus trap——需要 JS 配套。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 关闭按钮 X",
    prompt: "<button type=\"button\" onClick={() => setMobileMenuOpen(false)} ...><span className=\"sr-only\">Close menu</span><span aria-hidden=\"true\">✕</span></button>——结构？",
    options: [
      sc("A", "和汉堡按钮一致：sr-only 文本 + aria-hidden 装饰图标 + button 语义；同一项目内一致命名 + 模式增强可维护性"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "图标按钮模式：button + sr-only + aria-hidden 图标——本项目反复使用。" },
    abilityTags: ["ai.review.architecture", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 disabled 状态的可访问性",
    prompt: "退出按钮 disabled={fetcher.state !== 'idle'}——disabled 属性的 a11y 影响？",
    options: [
      sc("A", "disabled 让屏幕阅读器读出「禁用」状态、键盘用户无法激活；视觉 + 听觉 + 键盘三方一致表示「不可用中」；正确语义"),
      sc("B", "只视觉"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "disabled = 跨感官一致的「不可用」语义。" },
    abilityTags: ["frontend.event.submit", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 中文 aria-label",
    prompt: "aria-label=\"移动端导航菜单\" 用中文——OK？",
    options: [
      sc("A", "OK——网站语言是 zh-CN（root <html lang=\"zh-CN\">），屏幕阅读器按 lang 选中文语音读 aria-label；语言一致即可"),
      sc("B", "必须英文"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "aria-label 跟随页面 lang 即可——本站 zh-CN 用中文 label 正确。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q15 但「Open main menu」用英文",
    prompt: "汉堡按钮的 sr-only 是 \"Open main menu\" 英文——这一致吗？",
    options: [
      sc("A", "不一致——根 lang 是 zh-CN 但这里是英文文案；屏幕阅读器中文模式读英文会变成字母拼读或忽略；建议改 \"打开主菜单\"；项目细节瑕疵"),
      sc("B", "完美"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "sr-only 文本应跟随 page lang——这里是细节瑕疵。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 Link 而非 button 做导航",
    prompt: "导航项用 <Link> 不用 <button> 触发 navigate——a11y 角度好处？",
    options: [
      sc("A", "Link 渲染为 <a href> ——屏幕阅读器读「链接」并提示目标 URL；用户可右键打开新标签；button 则不能；语义角色匹配「跳转」=「链接」"),
      sc("B", "只样式"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "导航 = 链接语义；操作 = 按钮语义——选错语义 a11y 会丢信息。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 焦点轮廓",
    prompt: "Header 内多处 className 用 ui-* 类——是否包含 focus-visible 样式？",
    options: [
      sc("A", "应包含——ui-nav-link / ui-icon-button 在 utility 层定义 focus-visible:outline 等样式；键盘用户必须能看到当前焦点位置；浏览器默认轮廓被 reset 后必须显式补回"),
      sc("B", "无所谓"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "去 reset 后必须显式 focus-visible 样式——键盘 a11y 命脉。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/styles/"],
  }),
  q({
    type: "single_choice", title: "Q18 整页跳过到主内容",
    prompt: "Header 当前没有 \"跳到主内容\"（skip-to-content）链接——这是缺陷吗？",
    options: [
      sc("A", "是——WCAG 2.4.1：长导航前应有「跳过」链接让键盘用户直接 Tab 进 main；当前 7 项导航 Tab 一遍才到内容；建议在 root.tsx 加 skip-link"),
      sc("B", "完整"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "WCAG 2.4.1 skip-link = 键盘高阶 a11y。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "true_false", title: "Q19 aria-modal 自动 focus trap",
    prompt: "判断：aria-modal=\"true\" 会让浏览器自动实现焦点陷阱。",
    correctAnswer: { value: false },
    explanation: { short: "错——aria-modal 是「声明」，不是行为；焦点陷阱必须 JS 实现（监听 Tab + 检测边界回正）。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 抽屉打开后焦点应去哪",
    prompt: "完整 a11y 实现：抽屉打开后焦点应该去哪？",
    options: [
      sc("A", "应自动移到抽屉内第一个可聚焦元素（关闭按钮 X 或第一个 Link）；用户键盘体验「触发 → 焦点跟进」连贯；当前实现没做这步——可改 useEffect 内 ref.current?.focus()"),
      sc("B", "保留汉堡按钮"),
      sc("C", "页面顶"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "modal 打开 → 焦点移入；关闭 → 焦点还给触发按钮——这是完整实现。" },
    abilityTags: ["ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 修复 focus 还原",
    prompt: "关菜单后焦点应还给汉堡按钮——怎么实现？",
    options: [
      sc("A", "汉堡按钮加 ref，在 useEffect 监听 mobileMenuOpen 变 false 时 ref.current?.focus()；data-auth-target 类 DOM 钩子或 ref 都可以；显式还原"),
      sc("B", "浏览器自动"),
      sc("C", "无需"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "焦点还原必须显式——React 不自动管。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 Header a11y 整体哲学",
    prompt: "Header a11y 整体哲学（含已实现与缺口）？",
    options: [
      sc("A", "已做：1) sr-only + aria-hidden 图标按钮模式 2) role=dialog + aria-modal + aria-label modal 三件套 3) 鼠标 ↔ 键盘事件等价（hover/focus）4) Esc 关闭支持 5) prefers-reduced-motion 适配 6) Link/button 语义匹配。缺口：focus trap、focus 进出还原、skip-link、sr-only 中英文一致——综合：基础牢固，进阶项可补"),
      sc("B", "完美"),
      sc("C", "无需 a11y"),
      sc("D", "Cloudflare 处理"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "a11y 6 已做 + 4 缺口——清醒认识当前实现的边界。" },
    abilityTags: ["ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
];
