/**
 * Real questions for site-11-ui-header / header-mobile.
 * Anchor: remix/app/components/ui/Header.tsx —— mobileMenuOpen useState + useEffect 锁 body.overflow + Escape 监听 + animate-[mobile-menu-enter_420ms_...]
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/ui/Header.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const headerMobileQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 mobileMenuOpen 初值",
    prompt: "const [mobileMenuOpen, setMobileMenuOpen] = useState(____);",
    options: [],
    blanks: [{ id: "v", placeholder: "初始值", acceptedAnswers: ["false"] }],
    correctAnswer: { type: "fill_blank", values: { v: "false" } },
    explanation: { short: "默认关闭——首屏只显汉堡图标，等用户交互打开。" },
    abilityTags: ["frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 lg:hidden 包汉堡按钮",
    prompt: "<div className=\"flex lg:hidden\"> 包着汉堡按钮——含义？",
    options: [
      sc("A", "默认 flex 显示，lg 断点（≥1024px）改 hidden；移动端显汉堡，桌面端隐藏；与 lg:flex 桌面导航形成「双视图同 DOM」"),
      sc("B", "永远 hidden"),
      sc("C", "永远 flex"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "lg:hidden + lg:flex 反向开关——同 DOM 双视图。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 useEffect 依赖 [mobileMenuOpen]",
    prompt: "useEffect(() => { if (!mobileMenuOpen) return; ... }, [mobileMenuOpen]);——依赖数组只放 mobileMenuOpen？",
    options: [
      sc("A", "正确——effect 只关心菜单开关变化时副作用：开 → 锁 body + 绑 Escape；关 → cleanup 解锁 + 解绑；其他 state 变化不该触发；ESLint react-hooks/exhaustive-deps 也通过"),
      sc("B", "应放空数组"),
      sc("C", "应放所有 state"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "依赖 = effect 内消费的所有外部值——这里只有 mobileMenuOpen。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 if (!mobileMenuOpen) return early",
    prompt: "useEffect 第一行 if (!mobileMenuOpen) return;——这是 cleanup 还是 short-circuit？",
    options: [
      sc("A", "short-circuit——菜单关闭时不需要做任何副作用（既不锁 body 也不绑监听）；React 仍会跑这个 effect（因为依赖变了），early return 跳过；cleanup 是上次开启时挂的副作用解除"),
      sc("B", "cleanup"),
      sc("C", "等价"),
      sc("D", "永远不会跑"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "early return = effect 主体跳过；cleanup 由上次返回函数自动执行。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 锁 body.overflow",
    prompt: "document.body.style.overflow = 'hidden';——意图？",
    options: [
      sc("A", "禁用页面整体滚动——移动端弹出菜单后，避免「菜单内滚动 vs 背景滚动」混淆；用户上下滑时只滚菜单本身，不会让背景跟着动"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "锁滚动 = 移动端 modal/drawer 标准行为——杜绝双重滚动。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 const previousOverflow",
    prompt: "const previousOverflow = document.body.style.overflow; ...; cleanup 内 body.style.overflow = previousOverflow;——为什么不直接还成 ''？",
    options: [
      sc("A", "保存先前值再恢复——若页面其它地方（如视频播放/全屏 modal）也设置过 overflow，直接置 '' 会把它们的设置抹掉；保存 + 恢复是「不破坏其他副作用」的纪律"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "副作用纪律：保存 + 恢复，不假设全局初值。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 Escape 关闭",
    prompt: "useEffect 内 document.addEventListener('keydown', handleKeyDown) handleKeyDown 检 event.key === 'Escape' → setMobileMenuOpen(false)。意图？",
    options: [
      sc("A", "键盘用户用 Esc 关菜单是 modal/drawer 的可访问性铁律；ARIA Authoring Practices 推荐——所有「叠加层」类组件支持 Esc 关闭"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Esc 关 modal = a11y 标准。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 event.preventDefault() in Esc",
    prompt: "if (event.key === 'Escape') { event.preventDefault(); setMobileMenuOpen(false); }——preventDefault 必要？",
    options: [
      sc("A", "防止 Esc 触发浏览器默认行为（部分浏览器/扩展把 Esc 绑定为「停止加载」「退出全屏」等）；UI 自定义快捷键时阻止默认是常规防御"),
      sc("B", "可省"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "自定义快捷键 → preventDefault 阻断默认行为。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 cleanup 函数",
    prompt: "useEffect return () => { body.style.overflow = previousOverflow; document.removeEventListener('keydown', handleKeyDown); };——cleanup 内做什么？",
    options: [
      sc("A", "解锁 body.overflow + 解绑 keydown 监听——effect 重跑（mobileMenuOpen 变 false）或组件卸载时由 React 调用；保证 effect 留下的副作用都能撤销"),
      sc("B", "无意义"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "cleanup = effect 副作用的回收凭证。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 关闭时 cleanup 还是 effect 重跑",
    prompt: "用户开了菜单后再关——React 怎么处理？",
    options: [
      sc("A", "React 调上次 effect 的 cleanup（解锁 + 解绑）→ 然后跑新 effect 主体；新主体内 if (!mobileMenuOpen) return 直接退出；不再挂任何副作用——干净状态"),
      sc("B", "只跑 cleanup"),
      sc("C", "只跑 effect"),
      sc("D", "都不跑"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useEffect 重跑顺序：先 cleanup 再新 effect——React 的 useEffect 契约。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 fixed inset-0 overlay",
    prompt: "<button className=\"fixed inset-0 z-50 cursor-default bg-primary-950/10\" onClick={() => setMobileMenuOpen(false)} aria-label=\"关闭菜单\" />——这是什么？",
    options: [
      sc("A", "全屏点击遮罩——覆盖整个视口（fixed inset-0）半透明色（bg-primary-950/10），用 button 标签让其可被键盘/屏幕阅读器识别为可交互；点击关菜单"),
      sc("B", "装饰"),
      sc("C", "保留位置"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "全屏遮罩 + 点击关 = drawer 标准模式；用 button 而非 div 是 a11y 选择。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 z-50",
    prompt: "z-50——为什么菜单与遮罩都用 z-50？",
    options: [
      sc("A", "Tailwind z-50 是足够大的值，让菜单/遮罩浮在普通页面内容之上；同 z 时后挂的 DOM 在前——抽屉 div 在遮罩 button 之后，自然盖住遮罩；CSS 堆叠规则"),
      sc("B", "随机"),
      sc("C", "Tailwind 必须"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "同 z + DOM 顺序决定堆叠——抽屉在遮罩之后即在上方。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 抽屉 right-0 滑入",
    prompt: "<div className=\"fixed inset-y-0 right-0 z-50 w-full ... sm:max-w-sm ...\">——抽屉位置策略？",
    options: [
      sc("A", "右贴边（right-0）+ 上下满高（inset-y-0）+ 默认宽 100% + sm 断点起最大宽 sm（24rem）——窄屏全宽抽屉、稍宽屏右侧固定宽度抽屉；视觉过渡平滑"),
      sc("B", "永远 24rem"),
      sc("C", "永远 100%"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "响应式抽屉：窄屏全宽 + 较宽屏右贴限宽。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 动画 mobile-menu-enter",
    prompt: "className=\"animate-[mobile-menu-enter_420ms_cubic-bezier(0.16,1,0.3,1)] ...\" + 内联 <style> 定义 keyframes from { transform: translateX(100%) } to { translateX(0) }——为什么不用 framer-motion？",
    options: [
      sc("A", "纯 CSS keyframes 零额外 JS——只用一次的进入动画不值得 framer 体积；cubic-bezier(0.16,1,0.3,1) 是 ease-out 强尾的 spring-like 曲线；够用"),
      sc("B", "TypeScript 限制"),
      sc("C", "Cloudflare"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "单次进入动画 → 纯 CSS 更轻；framer 用在交互复杂场景。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 prefers-reduced-motion",
    prompt: "<style>{` ... @media (prefers-reduced-motion: reduce) { [aria-label=\"移动端导航菜单\"] [class*=\"mobile-menu-enter\"] { animation: none; } } `}</style>——意图？",
    options: [
      sc("A", "尊重用户系统级「减少动画」偏好——前庭功能障碍用户对滑入动画敏感；命中 media query 时 animation: none 跳过；可访问性细节"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "prefers-reduced-motion 适配 = a11y 必须项。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 抽屉内 Link onClick 关菜单",
    prompt: "<Link to={item.href} prefetch=\"intent\" onClick={() => setMobileMenuOpen(false)}>——为什么导航后还要手动关？",
    options: [
      sc("A", "Link 是 client-side 路由切换，组件不卸载（mobileMenuOpen 持续 true）；不手动关菜单会停留覆盖新页面；导航 + 关菜单是两回事，要显式串"),
      sc("B", "自动会关"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "client 路由 = 状态不重置；切页之后必须手动关 menu。" },
    abilityTags: ["frontend.event.click", "frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q17 用户点汉堡 → 选项 → 切页全流",
    prompt: "移动端用户点汉堡，选「音乐」，全流？",
    options: [
      sc("s1", "1. 用户点汉堡按钮 → setMobileMenuOpen(true)"),
      sc("s2", "2. React 重渲染 → mobileMenuOpen 真，抽屉 JSX 被挂载"),
      sc("s3", "3. useEffect 依赖变化 → if (!mobileMenuOpen) return 不命中，主体执行：锁 body.overflow + 绑 keydown"),
      sc("s4", "4. 抽屉用 animate-[mobile-menu-enter_420ms_...] 滑入"),
      sc("s5", "5. 用户点「音乐之旅」Link onClick → setMobileMenuOpen(false)"),
      sc("s6", "6. Link 也触发 client 路由切换 → 跳 /music"),
      sc("s7", "7. mobileMenuOpen 变 false → useEffect cleanup 触发：恢复 body.overflow + 解绑 keydown"),
      sc("s8", "8. 抽屉条件渲染消失（无离场动画——CSS 直接 unmount）"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8"] },
    explanation: { short: "开 → 副作用挂 → 用户操作 → 关 + 路由切 → cleanup 撤副作用——完整 8 步。" },
    abilityTags: ["frontend.state.local", "frontend.effect.useEffect", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 缺 cleanup 后果",
    prompt: "如果 useEffect 不返 cleanup（不解锁 body 也不解绑 keydown）——后果？",
    options: [
      sc("A", "用户关菜单后页面仍无法滚动 + 全局 keydown 仍触发 setState（更糟：组件卸载后还触发，React 警告 + 内存泄漏）；副作用必须能撤回"),
      sc("B", "无问题"),
      sc("C", "性能差"),
      sc("D", "TypeScript 报错"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "无 cleanup = 副作用泄漏 + 卸载后 setState bug。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 SSR 时 useState 初值",
    prompt: "首次 SSR 时 mobileMenuOpen 初值是什么？抽屉会被 SSR 渲出来吗？",
    options: [
      sc("A", "SSR 时 useState(false) → 初值 false → 抽屉条件 mobileMenuOpen ? ... : null 走 null 分支不渲；SSR HTML 不含抽屉——客户端 hydrate 后才会有打开行为"),
      sc("B", "总是渲"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SSR 严格按 useState 初值——抽屉不在 SSR HTML。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 改为始终挂载 + 用 CSS visibility",
    prompt: "若改成抽屉始终挂载、用 CSS visibility/transform 控制可见——好处坏处？",
    options: [
      sc("A", "好处：可加离场动画；坏处：DOM 更重，关闭时 keydown 监听若也常驻会污染键盘事件；当前条件渲染 + 副作用绑定与 mount/unmount 同步是干净取舍"),
      sc("B", "完全等价"),
      sc("C", "永远更好"),
      sc("D", "TypeScript 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "始终挂载 = 离场动画 + DOM 永驻成本；当前实现选「条件渲染 + 进场 CSS」。" },
    abilityTags: ["ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 改加遮罩点击关 + 滑动手势关",
    prompt: "想加「左滑关菜单」手势。落点？",
    options: [
      sc("A", "在抽屉外层 div 加 onTouchStart/Move/End 监听 touchstartX 与 endX 差值，超阈值 setMobileMenuOpen(false)；不必引手势库；纯 React 事件即可"),
      sc("B", "改 framer-motion"),
      sc("C", "改 wrangler"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "简单滑动手势 = 原生 touch 事件 + 状态判断；复杂手势再上库。" },
    abilityTags: ["project.modify.fullstack", "frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 移动菜单整体哲学",
    prompt: "移动菜单整体哲学？",
    options: [
      sc("A", "1) 单 useState 控开关——状态最小 2) useEffect 把 body.overflow 锁与 keydown 监听绑定到状态变化 3) cleanup 严格撤回所有副作用 + 保存先前值不破坏其他副作用 4) Esc 与遮罩点击双途径关 5) 纯 CSS keyframes 滑入 + prefers-reduced-motion 适配 6) Link onClick 显式关菜单 + client 路由——综合：状态 + 副作用 + a11y 三者一体"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "移动菜单 6 原则——单状态 + cleanup 纪律 + a11y 全覆盖。" },
    abilityTags: ["frontend.state.local", "frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
];
