/**
 * Real questions for site-11-ui-header / header-theme.
 * Anchor: remix/app/components/ui/Header.tsx + remix/app/root.tsx
 * 关键事实：Header.tsx 不含主题切换 UI——主题完全在 root.tsx loader/action + cookie 实现
 * 本课考察「为什么不在 Header / 如果加 Header 应怎么接 root action」
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/ui/Header.tsx";
const ROOT = "app/root.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const headerThemeQuestions: RealQ[] = [
  q({
    type: "true_false", title: "Q1 Header 是否含主题切换",
    prompt: "判断：Header.tsx 内有显式的 light/dark 主题切换按钮。",
    correctAnswer: { value: false },
    explanation: { short: "错——Header.tsx 没有主题按钮；主题完全由 root.tsx 的 loader/action + cookie 控制。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 主题状态来源",
    prompt: "当前页面 light/dark 实际 class 在哪设置？",
    options: [
      sc("A", "root.tsx 的 Layout 组件：const theme = data?.theme || 'light'; <html lang=\"zh-CN\" className={theme}> —— 在最外层 html 元素上"),
      sc("B", "Header.tsx"),
      sc("C", "客户端 useEffect"),
      sc("D", "全局 CSS"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "html className={theme} 在 root.tsx 的 Layout 组件——所有页共享。" },
    abilityTags: ["frontend.state.global", "code.position.handler"],
    sourceFilePath: ROOT, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, ROOT],
  }),
  q({
    type: "single_choice", title: "Q3 主题持久化机制",
    prompt: "用户切换主题后，怎么在下次访问保留？",
    options: [
      sc("A", "root.tsx action 收到 theme=light|dark → 调 setTheme(theme, request) 返回 Set-Cookie 头；下次访问 root loader 调 getTheme(request) 从 cookie 读"),
      sc("B", "localStorage"),
      sc("C", "服务端内存"),
      sc("D", "URL query"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "cookie 持久 + 服务端读：SSR 首屏直接套对 className 不闪烁。" },
    abilityTags: ["backend.session.cookie", "bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: ROOT, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [ROOT, "app/utils/theme.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q4 为什么不放 Header",
    prompt: "为什么作者把主题切换放 root.tsx 而不放 Header？",
    options: [
      sc("A", "主题作用全局 html 元素——不属于「导航」概念，逻辑上属于全局 shell；放 Header 会让 Header 同时管「导航 + 主题」两件事，违反单一职责；root 是 shell 的天然位置"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "全局副作用 → 全局 shell 管理；Header 只管导航。" },
    abilityTags: ["ai.review.architecture", "frontend.state.scope"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, ROOT],
  }),
  q({
    type: "single_choice", title: "Q5 root action 校验",
    prompt: "root.tsx action 内 if (theme !== 'light' && theme !== 'dark') return json({ error: 'Invalid theme' }, { status: 400 })——必要？",
    options: [
      sc("A", "必要——前端可能改 form value、或攻击者直接 POST 任意值；不校验会把脏数据写进 cookie，下次 getTheme 返非法字符串挂 className 上挂错样式"),
      sc("B", "可省"),
      sc("C", "TypeScript 限制"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "服务端永远不信前端——枚举字段必须白名单校验。" },
    abilityTags: ["backend.validation.field", "bridge.reactRouter.action"],
    sourceFilePath: ROOT, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [ROOT],
  }),
  q({
    type: "single_choice", title: "Q6 加按钮到 Header 的最小代码",
    prompt: "若想给 Header 加一个主题切换按钮——最少要写什么？",
    options: [
      sc("A", "用 <Form method=\"post\" action=\"/?index\"> 包按钮，<input type=\"hidden\" name=\"theme\" value={nextTheme}>；root.tsx action 已就绪可直接接收"),
      sc("B", "在 Header 写 useState 直接改 cookie"),
      sc("C", "改 wrangler.toml"),
      sc("D", "新建路由"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "已有 root action → 加按钮只是接 Form；不需新后端代码。" },
    abilityTags: ["bridge.reactRouter.action", "frontend.event.submit", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, ROOT],
  }),
  q({
    type: "single_choice", title: "Q7 Form vs fetcher",
    prompt: "用 <Form> 还是 useFetcher.submit() 提交主题切换更合适？",
    options: [
      sc("A", "fetcher.submit——主题切换不应触发整页 navigation（URL 不变 + 不滚到顶 + 不打断当前阅读位置）；<Form> 默认会改路由历史栈"),
      sc("B", "<Form> 更好"),
      sc("C", "完全等价"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "无导航语义的写操作 → fetcher；有导航语义 → Form。" },
    abilityTags: ["frontend.event.submit", "bridge.reactRouter.action", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 root data?.theme 链",
    prompt: "Layout 组件内 const theme = data?.theme || 'light';——data 哪来？",
    options: [
      sc("A", "Layout 组件用 useLoaderData<typeof loader>() 拿 root loader 返回的 { theme, ... };可选链 + || 'light' 应对 loader 抛错时 data 可能为 null 的边界"),
      sc("B", "props"),
      sc("C", "全局变量"),
      sc("D", "context"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Layout 是 root.tsx 的渲染骨架——直接消费 loader data。" },
    abilityTags: ["bridge.reactRouter.loader", "frontend.state.global"],
    sourceFilePath: ROOT, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [ROOT],
  }),
  q({
    type: "single_choice", title: "Q9 inline script 防 FOUC",
    prompt: "root.tsx 内有 <script> 段：const theme = document.cookie.match(/theme=([^;]+)/)?.[1] || 'light'; documentElement.classList.add(theme); ——意图？",
    options: [
      sc("A", "首屏 SSR 已渲染对的 className，但是若 SSR 默认渲 light、cookie 读失败、或客户端 hydration 前异步请求改了 theme，inline script 在 React hydrate 前抢先把 class 同步上——防 FOUC（颜色闪烁）"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "FOUC 防御：在 React 之前用同步脚本对齐 className。" },
    abilityTags: ["ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: ROOT, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [ROOT],
  }),
  q({
    type: "single_choice", title: "Q10 Header 不读 theme",
    prompt: "Header.tsx 内不见任何 useTheme / theme 变量——为什么 Header 不需要知道当前 theme？",
    options: [
      sc("A", "Header 用 Tailwind 工具类（bg-primary-50 text-primary-950 等），primary-* 系列由 tailwind.config 配 dark: 变体；html.dark 父元素一切换，Header 内类名自动级联反向；不需 JS 介入"),
      sc("B", "Header 没主题样式"),
      sc("C", "只走 light"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "CSS 级联 + Tailwind dark: 变体——主题切换零 JS 改色。" },
    abilityTags: ["ai.review.architecture", "frontend.state.scope"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q11 用户点击主题按钮全流（假设已加）",
    prompt: "假设已在 Header 加了主题按钮（fetcher.submit），用户点击「切到 dark」步骤？",
    options: [
      sc("s1", "1. 用户点击 Header 内主题按钮"),
      sc("s2", "2. fetcher.submit({ theme: 'dark' }, { method: 'post', action: '/' })"),
      sc("s3", "3. Worker 收到 POST /，进 root.tsx action"),
      sc("s4", "4. action 校验 theme === 'dark' → setTheme('dark', request) 生成 Set-Cookie"),
      sc("s5", "5. action 返 json({ ok: true }, { headers: { 'Set-Cookie': ... } })"),
      sc("s6", "6. fetcher 收到响应——React Router 自动 revalidate root loader"),
      sc("s7", "7. root loader 重新跑——getTheme(request) 读到 dark"),
      sc("s8", "8. Layout 组件用新 data?.theme = 'dark' 重渲染 <html className=\"dark\">"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8"] },
    explanation: { short: "主题切换全链：fetcher → action → Set-Cookie → revalidate loader → 新 className。" },
    abilityTags: ["frontend.event.submit", "bridge.reactRouter.action", "bridge.reactRouter.loader", "backend.session.cookie"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, ROOT, "app/utils/theme.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q12 直接改 document.documentElement.classList",
    prompt: "「主题切换为什么不直接 onClick={() => documentElement.classList.toggle('dark')}」——错在哪？",
    options: [
      sc("A", "不持久——刷新就丢；不跨标签同步；不被 SSR 知道（下次访问首屏闪一下回 light 再变 dark）；JS 直接操作 DOM 绕过了 React 状态体系"),
      sc("B", "性能"),
      sc("C", "TypeScript 报错"),
      sc("D", "习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "客户端 toggle = 临时玩具；持久化必须走 cookie + 服务端。" },
    abilityTags: ["ai.review.architecture", "backend.session.cookie"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 setTheme(theme, request) 第二参数",
    prompt: "setTheme(theme, request)——为什么要传 request？",
    options: [
      sc("A", "Cookie 库（如 createCookie）通常需要 request 来读现有 cookie 头、合并 secret 解密；写新 cookie 时 sign + 设 path/secure/httpOnly 等属性也要参考请求上下文"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "cookie 工具需要 request 读上下文 + 签名/加密。" },
    abilityTags: ["backend.session.cookie", "ai.review.architecture"],
    sourceFilePath: ROOT, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [ROOT, "app/utils/theme.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q14 anonymous early return",
    prompt: "root.tsx loader 注释：「Anonymous requests often only carry theme/visitor cookies; avoid a Better Auth/D1 read until an auth cookie exists.」——意图？",
    options: [
      sc("A", "未登录请求只带 theme cookie——若每次 root loader 都查 D1 做 auth，访客也吃一次 D1 query；用 cookie 存在性判断 short-circuit 跳过 auth 读，省 D1 调用"),
      sc("B", "性能没差"),
      sc("C", "TypeScript"),
      sc("D", "习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "lazy auth：只在有 auth cookie 时才查 D1——避免访客白嫖 query。" },
    abilityTags: ["backend.session.cookie", "ai.review.architecture", "backend.auth.required"],
    sourceFilePath: ROOT, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [ROOT],
  }),
  q({
    type: "single_choice", title: "Q15 SSR 主题首屏不闪烁",
    prompt: "用户带 cookie theme=dark 再访问。首屏 dark 不闪 light——靠什么？",
    options: [
      sc("A", "SSR 阶段 root loader 已读出 theme=dark，渲染时 <html className=\"dark\"> 直接对；浏览器收到完整 dark HTML——根本没机会显 light；服务端读 cookie 是核心"),
      sc("B", "客户端 useEffect"),
      sc("C", "重定向"),
      sc("D", "Tailwind"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SSR 服务端读 cookie 是首屏不闪的根——客户端方案永远会闪。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture", "backend.session.cookie"],
    sourceFilePath: ROOT, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [ROOT],
  }),
  q({
    type: "single_choice", title: "Q16 加第三个主题 'auto'",
    prompt: "想加一个跟随系统的 'auto' 主题。改动覆盖面？",
    options: [
      sc("A", "1) action 校验白名单加 'auto' 2) Layout 渲染时 className 解析 auto → 加 'auto' 类，CSS 用 @media (prefers-color-scheme: dark) 切色 3) 或写客户端 JS 探测系统偏好后再加 light/dark；3 处都要改"),
      sc("B", "改 Header"),
      sc("C", "改 wrangler"),
      sc("D", "改 D1"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "新枚举 = 校验 + 渲染 + 客户端探测三处共同改。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture"],
    sourceFilePath: ROOT, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [ROOT, "app/utils/theme.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q17 Header 与 root data 的最小耦合",
    prompt: "Header.tsx 通过 useOutletContext 拿 session 但不拿 theme——这种「按需拿数据」的好处？",
    options: [
      sc("A", "Header 不依赖 theme，加新主题时 Header 不动；强耦合 = 改一处影响多处；最小化耦合面 = 维护成本最低"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "组件按需依赖 = 最小耦合面——改动隔离。" },
    abilityTags: ["ai.review.architecture", "frontend.state.scope"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, ROOT],
  }),
  q({
    type: "single_choice", title: "Q18 cookie name 'theme'",
    prompt: "cookie name 写死 'theme' vs 加项目前缀 'lea_theme'——选哪个？",
    options: [
      sc("A", "项目前缀更稳——多项目共享同域名时（如 admin.gregor.com vs gregor.com）避免 cookie name 撞车；线上常见反模式：通用 cookie name 跨项目串味"),
      sc("B", "无差"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "cookie 命名空间隔离 = 多项目同域共存的工程纪律。" },
    abilityTags: ["backend.session.cookie", "ai.review.architecture"],
    sourceFilePath: ROOT, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [ROOT, "app/utils/theme.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q19 主题切换响应慢",
    prompt: "线上反馈：点主题按钮后 500ms 后页面才变色——可能原因？",
    options: [
      sc("A", "fetcher 等 Worker 网络往返 + Set-Cookie 回来 + revalidate root loader + 重渲染——三步串行；优化：客户端先乐观切 className（再服务端持久化）"),
      sc("B", "TypeScript"),
      sc("C", "Cloudflare 限制"),
      sc("D", "习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "网络往返是主因——optimistic update 是经典优化。" },
    abilityTags: ["ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: ROOT, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [ROOT, PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 主题改在 Header 还是 root",
    prompt: "若坚决要把主题切换 UI 加 Header（不放别处），后端逻辑放哪？",
    options: [
      sc("A", "后端逻辑（action / setTheme / cookie）仍放 root.tsx action——UI 在 Header 提交即可；不复制后端代码到新路由——单一来源"),
      sc("B", "Header.server.ts"),
      sc("C", "新路由 /api/theme"),
      sc("D", "客户端处理"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "UI 位置与后端位置解耦——后端单一来源不复制。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.action"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, ROOT],
  }),
  q({
    type: "single_choice", title: "Q21 主题机制可观测",
    prompt: "想监控用户主题分布（多少 light vs dark）。落点？",
    options: [
      sc("A", "root.tsx action 内 setTheme 之后埋一行 console.log 或上报 analytics——单点拦截所有切换；前端埋点会漏掉「服务端默认 light」的访客统计"),
      sc("B", "Header 埋点"),
      sc("C", "tailwind"),
      sc("D", "改 D1"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "可观测性放在最关键的写路径——root action 是单点。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.action"],
    sourceFilePath: ROOT, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [ROOT],
  }),
  q({
    type: "single_choice", title: "Q22 主题哲学整体",
    prompt: "主题机制整体哲学（Header 不参与的反思）？",
    options: [
      sc("A", "1) 主题作用全局 → 放 root shell 而非 Header 2) 持久化用 cookie 不用 localStorage（SSR 友好）3) 服务端校验白名单不信前端 4) html className + Tailwind dark: 变体让 CSS 自管色 5) Header 不依赖 theme = 最小耦合 6) 防 FOUC 用 inline script 同步 className——综合：分层职责让 Header 保持纯导航"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "主题 6 原则——分层 + 持久 + 防闪烁 + 解耦。" },
    abilityTags: ["ai.review.architecture", "frontend.state.scope", "backend.session.cookie"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, ROOT, "app/utils/theme.server.ts"],
  }),
];
