/**
 * Real questions for site-09-gallery-updates / anime-route.
 * Anchor: remix/app/routes/anime.tsx —— cdnUrl + audio modal 三状态 + isMenuActive resize 管理 + 视频 paused 恢复
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/anime.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const animeRouteQuestions: RealQ[] = [
  q({
    type: "single_choice", title: "Q1 cdnUrl vs resolveR2Image",
    prompt: "loader 内 const videoUrl = cdnUrl('you.mp4');——cdnUrl 与 resolveR2Image 区别？",
    options: [
      sc("A", "cdnUrl 把相对路径映射到 CDN 域（cdn.xn--cckl9nsb.com）；不带 token 也不带签名；资源完全公开（视频不需访问控制）；vs resolveR2Image 给图片走 R2 + token 流"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare 强制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "公开内容用 cdnUrl；需要权控的资源走 resolveR2Image——分两路。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/media-cdn.ts", "app/lib/resolve-image.ts"],
  }),
  q({
    type: "fill_blank", title: "Q2 缓存秒数",
    prompt: 'Cache-Control: "public, max-age=____, stale-while-revalidate=600"',
    options: [],
    blanks: [{ id: "v", placeholder: "数字", acceptedAnswers: ["300"] }],
    correctAnswer: { type: "fill_blank", values: { v: "300" } },
    explanation: { short: "300 秒（5 分钟）+ SWR 600s——内容半静态，5 分钟新度足够。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 三态 useState",
    prompt: "useState isMenuActive(false), showAudioModal(true), isLoading(true)——三个独立状态？",
    options: [
      sc("A", "侧栏菜单开关 + 首次访问的音频选择 modal + 整页 loading 三个独立维度——分开 useState 避免单 state 对象更新粒度太粗；React 标准模式"),
      sc("B", "性能差"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "独立 boolean = 多 useState；单 reducer 适合状态相互依赖时。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 audio modal 设计",
    prompt: "showAudioModal 默认 true 在首次进页弹出「播放声音 vs 静音播放」二选一——意图？",
    options: [
      sc("A", "浏览器 autoplay 政策：未交互前不能自动播放有声视频；用 modal 让用户主动点击 = 「用户手势」满足 autoplay；vs 直接 muted 自动播 + 后续手动开声"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "autoplay 政策 = 必须用户手势；modal 是优雅获取交互的方式。" },
    abilityTags: ["ai.review.architecture", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 toggleMenu 用 useCallback",
    prompt: "const toggleMenu = useCallback(() => setIsMenuActive(prev => !prev), []);——为什么 useCallback？",
    options: [
      sc("A", "deps 空数组——handler 引用永久稳定；传给子组件 props 不会因父重渲染而触发子重渲染（搭 React.memo）；prev 函数式更新避免闭包"),
      sc("B", "性能差"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useCallback 空 deps + setX(prev => ...) = 永久稳定 handler。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 useEffect deps=[isMenuActive]",
    prompt: "useEffect(() => { ...video.play().catch(...) }, [isMenuActive]);——deps 选这个？",
    options: [
      sc("A", "侧栏开关导致 transition 期间视频被浏览器自动暂停；effect 在 isMenuActive 切换时延迟 400ms 后调 play()；deps=[isMenuActive] 让 effect 只在切换时跑而非每次重渲染"),
      sc("B", "随机"),
      sc("C", "TypeScript 强制"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "deps 精准控制 effect 触发——只在状态切换时跑。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank", title: "Q7 setTimeout 延迟",
    prompt: "const timer = setTimeout(() => { video.play().catch(...) }, ____);",
    options: [],
    blanks: [{ id: "v", placeholder: "毫秒", acceptedAnswers: ["400"] }],
    correctAnswer: { type: "fill_blank", values: { v: "400" } },
    explanation: { short: "400ms 是 CSS transition (~500ms) 略短一些——动画基本停下时再 play 避免被立即暂停。" },
    abilityTags: ["frontend.effect.useEffect"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 video.play().catch",
    prompt: "video.play().catch(() => { /* 静默处理 */ })——为什么 catch？",
    options: [
      sc("A", "play() 返 Promise；某些浏览器 autoplay 政策或 tab 后台时拒绝；不 catch 会触发 unhandled promise rejection 报错；静默处理是简洁方案"),
      sc("B", "TypeScript 要求"),
      sc("C", "Cloudflare"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "video.play() 永远要 .catch——浏览器随时可能拒绝。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 cleanup return clearTimeout",
    prompt: "useEffect 内 if (video.paused) { ...; return () => clearTimeout(timer); }——cleanup 必要？",
    options: [
      sc("A", "necessary——快速切换 isMenuActive 时上一个 timer 还没跑就有新 timer 排队；clear 防止旧 timer 在新状态下错误调 play；副作用清理铁律"),
      sc("B", "可选"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "setTimeout 在 useEffect 必清——避免回调跑在过期状态。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 AnimePageData type",
    prompt: "AnimePageData = { content, animeList, videoSrc }——为什么这种 shape？",
    options: [
      sc("A", "Remix loader 一次返三段：文案 + 数据列表 + 媒体 URL；前端解构一次拿全；vs 多次 fetch 浪费"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader 一次给齐 = SSR + hydrate 一步到位。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 animeList 静态数据",
    prompt: "animeList: [{ id: 1, name: '从零开始的异世界生活', rating: '10.0', url: null }, ...] 11 条——存哪？",
    options: [
      sc("A", "loader 内硬编码——个人喜好清单，改一次部署；不需 D1；rating 写字符串方便 UI 直接渲染；url:null 占位之后可加跳转"),
      sc("B", "API"),
      sc("C", "D1"),
      sc("D", "用户提交"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "11 条静态数据放 loader = 最简洁。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 useRef 视频 + showcase",
    prompt: "videoRef = useRef<HTMLVideoElement>(null); showcaseRef = useRef<HTMLDivElement>(null);——两个 ref 用途？",
    options: [
      sc("A", "videoRef 控制播放/暂停（命令式 API）；showcaseRef 给 IntersectionObserver/动画用；ref 是 React 与 DOM 命令式交互的桥梁"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useRef 是「命令式 DOM 句柄」——视频播放/动画 trigger 必备。" },
    abilityTags: ["frontend.state.local", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 LazyMotion + AnimatePresence",
    prompt: "import { LazyMotion, domAnimation, m, AnimatePresence } from 'framer-motion';——为什么 AnimatePresence？",
    options: [
      sc("A", "audio modal 进出场动画——AnimatePresence 监听子组件 mount/unmount，给 m.div 加 exit prop 实现淡出；vs 直接卸载子组件就闪掉"),
      sc("B", "TypeScript"),
      sc("C", "Cloudflare"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "AnimatePresence = 卸载动画——modal 退场必备。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 isMenuActive 副作用链",
    prompt: "用户点击菜单按钮 → toggleMenu → setIsMenuActive 切换 → 触发什么？",
    options: [
      sc("A", "1) 组件重渲染（class 切换 CSS transition 推开侧栏） 2) useEffect[isMenuActive] 重跑（400ms 后试播视频） 3) 用户视觉上侧栏滑出 + 视频继续播"),
      sc("B", "只重渲染"),
      sc("C", "什么都不做"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "state 变 = 渲染 + effect 双触发——React 数据流的标准两步。" },
    abilityTags: ["frontend.state.local", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 audio modal 选「播放声音」",
    prompt: "用户点击「播放声音」按钮 → 必须做什么？",
    options: [
      sc("A", "1) videoRef.current.muted = false 2) videoRef.current.play() 3) setShowAudioModal(false)；用户手势已满足 autoplay 政策可以有声播"),
      sc("B", "纯关 modal"),
      sc("C", "刷新"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "muted=false + play() + 关 modal——三步缺一不可。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 isLoading 用途",
    prompt: "isLoading 默认 true——什么时候 setIsLoading(false)？",
    options: [
      sc("A", "video.onLoadedData 或类似事件触发后置 false——给视频元素 onLoadedData={() => setIsLoading(false)}；首次有可播帧才显示主内容"),
      sc("B", "永远 true"),
      sc("C", "永不变"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "video onLoadedData = 视频准备好可播——切换 isLoading 的标准时机。" },
    abilityTags: ["frontend.state.local", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 SSR 视频处理",
    prompt: "SSR 阶段 videoRef.current 是？",
    options: [
      sc("A", "null——SSR 不挂 DOM；effect 也不跑；videoRef 在 client hydrate 后才 .current 可用；这就是为什么 video.play 都放 effect 内"),
      sc("B", "DOM 节点"),
      sc("C", "假元素"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SSR 时 ref.current=null；effect 仅 client 跑——SSR 安全的根本。" },
    abilityTags: ["frontend.effect.useEffect", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 加新动漫落点",
    prompt: "想加 12 号动漫《关于我转生变成史莱姆这档事》。改动？",
    options: [
      sc("A", "loader 内 animeList 数组加 { id: 12, name: '...', rating: '...', url: null }——一处即可，UI 自动 map 渲染"),
      sc("B", "改 wrangler"),
      sc("C", "改 root"),
      sc("D", "改 API"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "数据驱动 UI = 只改数组。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 cdnUrl 路径前缀",
    prompt: "cdnUrl('you.mp4') 内部把 'you.mp4' 拼成什么？",
    options: [
      sc("A", "https://cdn.xn--cckl9nsb.com/you.mp4 —— 把相对路径补全为 CDN 域 + path；逻辑在 media-cdn.ts；改 CDN 域只需改一处"),
      sc("B", "Worker URL"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "cdnUrl = 路径 → 完整 CDN URL 的纯函数转换。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/lib/media-cdn.ts"],
  }),
  q({
    type: "single_choice", title: "Q20 modal 体验改 ClientOnly 包",
    prompt: "「audio modal 在 SSR 闪现一帧再消失」属于 hydration mismatch？",
    options: [
      sc("A", "对——showAudioModal 初始 true 服务端渲染了 modal HTML；client mount 后用户看到一瞬间；可用 ClientOnly 包它（client 才挂）；或 useEffect 切 false 后再渲染"),
      sc("B", "完全无问题"),
      sc("C", "性能"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "client-only UI 应用 ClientOnly/useEffect 守门——避免 SSR 闪现。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 CSS transition 大约时长",
    prompt: "useEffect 注释「与 CSS transition 500ms 保持接近，但略短一些」——这种「软耦合」？",
    options: [
      sc("A", "JS 与 CSS 时长在不同文件——一处改另一处可能漂；可用 CSS 自定义属性（var(--transition-menu) 给 JS 读）解耦；当前是 trade-off：简单 vs 一致性"),
      sc("B", "完美"),
      sc("C", "TypeScript 限制"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "JS/CSS 时长软耦合是技术债——可以但要意识到。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 整体设计哲学",
    prompt: "Anime 页整体哲学？",
    options: [
      sc("A", "1) cdnUrl 公共媒体走 CDN（vs token） 2) loader 一次给齐文案 + 列表 + 视频 URL 3) 多 useState 解耦三个独立 UI 维度 4) audio modal 满足 autoplay 政策 5) useCallback 稳定 handler 6) useEffect[isMenuActive] 处理视频被暂停 7) AnimatePresence 退场动画 8) video.play().catch 静默防 unhandled——综合：媒体页性能 + 浏览器政策应对"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "八条原则——视频内容页的范式。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/lib/media-cdn.ts"],
  }),
];
