/**
 * Real questions for site-09-gallery-updates / content-capstone.
 * Anchor: gallery + updates + cv + anime 综合 —— 新内容栏目落点决策、复用 vs 新建、Header 集成
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/gallery.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const contentCapstoneQuestions: RealQ[] = [
  q({
    type: "single_choice", title: "Q1 加新内容路由 /timeline",
    prompt: "想加 /timeline 时间线页（类似 updates 但内容不同）。第一步落点？",
    options: [
      sc("A", "1) 复制 updates.tsx → timeline.tsx 改文案 + 数据 2) data/ 加 timeline.ts 数据源 3) Header navigation 加项 4) routes-content unit 加 lesson 跟踪——四件套"),
      sc("B", "改 root"),
      sc("C", "改 wrangler"),
      sc("D", "改 _index"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "新路由 = 复制结构 + 数据 + 导航 + 课程跟踪——从 updates 起步是最近模板。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/routes/updates.tsx", "app/data/updates.ts", "app/components/ui/Header.tsx"],
  }),
  q({
    type: "single_choice", title: "Q2 选 gallery 模板还是 updates 模板",
    prompt: "想加图片 + 文字混合的「项目作品集」页——选哪个模板复制？",
    options: [
      sc("A", "gallery 更近——多列瀑布流图片是核心；vs updates 是纯卡片列表；选「视觉结构最像」的模板减少改造成本"),
      sc("B", "永远 updates"),
      sc("C", "永远 cv"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "选模板看视觉结构匹配度——不是复制行数最少。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/updates.tsx", "app/routes/cv.tsx"],
  }),
  q({
    type: "single_choice", title: "Q3 数据应不应该进 D1",
    prompt: "新内容页是「我自己写的项目介绍」——要存 D1 吗？",
    options: [
      sc("A", "不要——内容静态、版本由 git 管、无并发更新；放 data/ 文件最简洁；D1 只在「多人多变内容」（留言、评论）才合适"),
      sc("B", "永远 D1"),
      sc("C", "TypeScript 限制"),
      sc("D", "Cloudflare 强制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "数据形态决定存储——静态文件 vs D1 的分界线。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: "app/data/updates.ts", layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/data/updates.ts"],
  }),
  q({
    type: "single_choice", title: "Q4 缓存策略选哪种",
    prompt: "新内容页 loader 应用哪种 Cache-Control？",
    options: [
      sc("A", "依内容更新频率而定：数月一改 → s-maxage 24h；数天一改 → 1h；图片资源接近 token 寿命；vs 不假思索复制 cv 的 TOKEN_DATA_CACHE_HEADERS"),
      sc("B", "永远 no-store"),
      sc("C", "永远 max-age=10"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "缓存策略由内容更新频率决定——而不是模板默认。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: "app/lib/cache-headers.server.ts", layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q5 新页要不要加 forwardLoaderCacheControl",
    prompt: "新内容页 export const headers 必要？",
    options: [
      sc("A", "如果想让 CDN 缓存 HTML——必要；忘加 = loader Cache-Control 不会传到 document Response；CDN 不缓存；这是 v3_singleFetch 的坑"),
      sc("B", "可省"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "想要 CDN 缓存 HTML 必加 forwardLoaderCacheControl——四个内容页都加了。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: "app/lib/cache-headers.server.ts", layer: "production-debugging",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q6 Header 加导航项落点",
    prompt: "新内容页 /timeline 怎么暴露给用户？",
    options: [
      sc("A", "Header.tsx navigation 数组加 { name: '时间线', href: '/timeline' }——desktop + mobile 都自动 map；vs 不加用户找不到入口"),
      sc("B", "改 _index"),
      sc("C", "改 root"),
      sc("D", "新建 Header"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "新内容页必须挂入口——Header.navigation 是唯一来源。" },
    abilityTags: ["code.position.handler"],
    sourceFilePath: "app/components/ui/Header.tsx", layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/components/ui/Header.tsx"],
  }),
  q({
    type: "single_choice", title: "Q7 SEO meta 落点",
    prompt: "新页的 meta 写哪？",
    options: [
      sc("A", "1) utils/seo.ts 的 pageMeta 加方法 pageMeta.timeline() 2) 路由文件 export const meta = () => pageMeta.timeline()；集中管理避免漂移"),
      sc("B", "硬编码"),
      sc("C", "改 root"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SEO 集中 = utils/seo.ts；新页加方法不硬编码。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: "app/utils/seo.ts", layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/utils/seo.ts"],
  }),
  q({
    type: "single_choice", title: "Q8 GSAP 还是 framer",
    prompt: "新页要进场动画——选哪个？",
    options: [
      sc("A", "依需求：跨元素位置过渡（layoutId）→ framer；scroll-trigger 多元素 → gallery 用了 GSAP；纯 CSS transition + setTimeout 也够（如 updates）；不必都套高级库"),
      sc("B", "永远 GSAP"),
      sc("C", "永远 framer"),
      sc("D", "永远 CSS"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "动画工具选择：scroll → GSAP / 跨组件 → framer / 简单 → CSS。" },
    abilityTags: ["ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY, "app/routes/updates.tsx"],
  }),
  q({
    type: "single_choice", title: "Q9 reduce-motion 守门",
    prompt: "新页有动画——必须加 reduce-motion 守门吗？",
    options: [
      sc("A", "必须——尊重系统级 a11y 偏好；gallery 用 matchMedia 前置 return；updates 用 mediaQuery.addEventListener 实时响应；新页至少做静态检查"),
      sc("B", "可选"),
      sc("C", "纯习惯"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "a11y 不可省——动画必有 reduce-motion fallback。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 图片资源 R2 还是公共 CDN",
    prompt: "新页有 30 张图片——走哪？",
    options: [
      sc("A", "依权控决定：完全公开图（封面、装饰）→ cdnUrl + R2 公开桶；需要时效控制 → resolveR2Image 走 token；混用也常见"),
      sc("B", "永远 cdnUrl"),
      sc("C", "永远 token"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "公开 vs 控权 决定 cdnUrl 还是 resolveR2Image——按需选。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/lib/resolve-image.ts", "app/lib/media-cdn.ts"],
  }),
  q({
    type: "single_choice", title: "Q11 routes-content unit 配置",
    prompt: "新页要加进 site-09 课程吗？",
    options: [
      sc("A", "如果新页延续「内容展示」语义就并入 site-09，加新 lesson 跟踪；如果业务很特殊（如新型互动）开新 unit；判断标准是「与现有 4 页是否同类」"),
      sc("B", "永远新 unit"),
      sc("C", "永远不加"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "课程组织 = 内容相似度；同类合并不分散。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: "app/lib/server/learn/seed-data/units/courseCatalog.ts", layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 客户端动画 vs 纯 SSR",
    prompt: "新页极致追求 SEO/JS-fail 兼容——选哪种动画？",
    options: [
      sc("A", "纯 CSS（transition / @keyframes）——零 JS 依赖；JS 故障也能播；vs framer/GSAP 在 noscript 不工作；updates 的 setTimeout 是折中"),
      sc("B", "GSAP"),
      sc("C", "framer"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "极致兼容 = 纯 CSS；JS 失败仍可看见。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 复用 GsapFillLink/Button",
    prompt: "新页跳转链接用什么？",
    options: [
      sc("A", "GsapFillLink——项目自定义包装；统一交互动画风格；prefetch=intent 自动加；vs 直接用 Remix Link 视觉不一致"),
      sc("B", "原生 a"),
      sc("C", "router-dom"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "项目级 Link 包装 = 视觉一致 + 预取一致。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: "app/components/ui/GsapFillLink.tsx", layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 TypeScript loader 推导",
    prompt: "新页 useLoaderData 怎么写？",
    options: [
      sc("A", "useLoaderData<typeof loader>()——类型从 loader 函数推；改 loader 字段 TS 自动同步前端；vs 手写 interface 双份维护"),
      sc("B", "any"),
      sc("C", "手写 interface"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix typed loader 黄金搭配——单一来源。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q15 完整新页落地 7 步",
    prompt: "/timeline 新内容页全流程？",
    options: [
      sc("s1", "1. data/ 加 timeline.ts 数据源"),
      sc("s2", "2. utils/seo.ts 加 pageMeta.timeline()"),
      sc("s3", "3. routes/timeline.tsx 复制 updates 改 loader/UI"),
      sc("s4", "4. headers = forwardLoaderCacheControl"),
      sc("s5", "5. components/ui/Header.tsx 加 navigation 项"),
      sc("s6", "6. (可选) units/courseCatalog.ts site-09 加 lesson"),
      sc("s7", "7. npm run typecheck → npm run dev 测试 → 部署"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7"] },
    explanation: { short: "7 步完整流——任何新内容页都按这个顺序。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/routes/updates.tsx", "app/data/updates.ts", "app/components/ui/Header.tsx", "app/utils/seo.ts"],
  }),
  q({
    type: "single_choice", title: "Q16 千万别忘的事",
    prompt: "新页最容易被遗忘的环节？",
    options: [
      sc("A", "forwardLoaderCacheControl + Header navigation 项 + reduce-motion 守门——这三个不报错但严重影响生产；TS 检查不出"),
      sc("B", "TypeScript 类型"),
      sc("C", "ESLint 规则"),
      sc("D", "Cloudflare 配置"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "「不报错的疏漏」最致命——清单化检查。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q17 必须改 root.tsx",
    prompt: "判断：加新内容路由必须改 app/root.tsx。",
    correctAnswer: { value: false },
    explanation: { short: "错——root.tsx 已挂 <Outlet />，新路由文件直接放 routes/ 即被 Remix 自动识别；只在新路由要改全局 context 时才动 root。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q18 ImageData 类型复用",
    prompt: "新页有图片需要 ImageData 类型——抽到 types/？",
    options: [
      sc("A", "看用途：仅一两个页用 → 各自本地 type 即可（gallery + cv 都本地）；多页且共享 mapper → 抽到 types/；过早抽象是坏味道"),
      sc("B", "永远抽"),
      sc("C", "永远本地"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "类型抽象的 trade-off——够多复用才抽。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 JS 故障也能用",
    prompt: "新内容页设计原则之一：JS 故障也能阅读内容。落点？",
    options: [
      sc("A", "loader 返完整数据 → SSR 出完整 HTML；动画/交互是 progressive enhancement；用户禁 JS 仍能看图、读字、跳转 Link（默认 a 行为）"),
      sc("B", "强制 JS"),
      sc("C", "TypeScript 限制"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix 的 progressive enhancement 哲学——JS 是增强非必需。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 内容多语言考虑",
    prompt: "新页未来要做中英双语。怎么准备？",
    options: [
      sc("A", "loader 内 content 对象用 key（如 heroTitle: t(lang, 'home.hero')），i18n 工具按 lang 取值；URL 用 /en/timeline 子路径或 cookie 切换；现在不做但保留接口"),
      sc("B", "永远中文"),
      sc("C", "硬编码"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "内容/UI 分层 + i18n key——未来 i18n 的接口铺垫。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 错误处理",
    prompt: "loader 内 throw 错误（如 D1 暂时故障）。新页表现？",
    options: [
      sc("A", "冒泡到最近的 ErrorBoundary——若该路由没自定义就走 root.tsx 的错误页；用户看到友好错误页而非白屏；vs try/catch + 兜底数据让页面仍可用"),
      sc("B", "白屏"),
      sc("C", "200 空"),
      sc("D", "Cloudflare 拦截"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader throw → ErrorBoundary 链——RR 错误处理标准。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 整体决策树",
    prompt: "新内容页落点决策树？",
    options: [
      sc("A", "内容静态/动态？→ 数据放 data/ vs D1；视觉结构？→ 选最近模板复制；图片权控？→ cdnUrl vs resolveR2Image；动画？→ CSS/framer/GSAP 三选一；缓存？→ 按更新频率定 max-age；导航？→ Header.navigation 加项；SEO？→ pageMeta 加方法；课程？→ site-09 加 lesson 跟踪；最后 typecheck + 部署——综合：复用模板 + 数据驱动 + 全链路 checklist"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare 决定"),
      sc("D", "TypeScript 强制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "完整决策树——加新内容页的全套思考。" },
    abilityTags: ["ai.review.architecture", "code.position.handler", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/routes/updates.tsx", "app/routes/cv.tsx", "app/routes/anime.tsx", "app/components/ui/Header.tsx", "app/data/updates.ts", "app/utils/seo.ts", "app/lib/cache-headers.server.ts"],
  }),
];
