/**
 * Real questions for site-09-gallery-updates / cv-route.
 * Anchor: remix/app/routes/cv.tsx —— TOKEN_DATA_CACHE_HEADERS + 嵌套 content 对象 + framer-motion m + emoji 图标
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/cv.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const cvRouteQuestions: RealQ[] = [
  q({
    type: "single_choice", title: "Q1 emoji 替代 heroicons",
    prompt: "const CheckCircleIcon = ({ className }) => (<span role='img' aria-label='check'>✅</span>);——为什么不用 heroicons？",
    options: [
      sc("A", "用 emoji 替代 SVG icon——零 JS 包体积；阅读注释「Icon components replaced with emoji for better performance」；个人站极致优化"),
      sc("B", "TypeScript 限制"),
      sc("C", "Cloudflare 强制"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "emoji icon = 零代码体积；性能驱动的取舍。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 role + aria-label",
    prompt: "<span className role='img' aria-label='check'>✅</span>——为什么需要这两个 ARIA 属性？",
    options: [
      sc("A", "屏幕阅读器把 emoji 当文本读会读出乱码；role='img' 标识为图像 + aria-label 提供文本替代——a11y 正确做法"),
      sc("B", "纯习惯"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "emoji + role/aria-label = 屏幕阅读器友好。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 TOKEN_DATA_CACHE_HEADERS",
    prompt: "return json(data, { headers: TOKEN_DATA_CACHE_HEADERS });——这个常量 vs 内联对象？",
    options: [
      sc("A", "把「token 类数据」常用缓存头集中到 cache-headers.server.ts，多页复用；改一次全更新；vs 每个 loader 各自 'public, max-age=...' 容易不一致"),
      sc("B", "TypeScript 要求"),
      sc("C", "Cloudflare"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "缓存头常量 = 跨路由复用 + 单一来源。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q4 links preload 头像",
    prompt: "links: () => [{ rel: 'preload', as: 'image', href: images.cv_avatar ?? 'https://cdn.xn--cckl9nsb.com/Feedback/person.webp' }];——意图？",
    options: [
      sc("A", "首屏头像图最重要——Remix links 提早注入 <link rel=preload> 让浏览器并行下载；?? 兜底硬编码 URL 防 manifest 缺 key；LCP 优化"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "preload 关键图 = LCP 优化神器。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/generated/image-manifest.ts"],
  }),
  q({
    type: "single_choice", title: "Q5 嵌套 content 对象",
    prompt: "content: { personal: {...}, work_experience: { tencent: {...} }, school_experience: {...}, education: {...}, skills: { list: {...}, levels: {...} }, ... }——为什么所有文案在 loader？",
    options: [
      sc("A", "简历文案是「内容」属于数据层；loader 一次返；前端只渲染——可在不改组件的情况下改文案；i18n 也好替换"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "数据 vs UI 分层——文案放数据层最容易维护。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 艾尔登法环梗",
    prompt: "loader 内 work_experience.tencent.company: '交界地探险者协会'——这种取值方式？",
    options: [
      sc("A", "把简历内容用艾尔登法环风格重写——既是个人趣味又是 NSFW 屏蔽（第三方爬虫看不出真实公司名）；个人站特色 UX"),
      sc("B", "失误"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "趣味化文案 + 隐私保护双赢——个人站特权。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 框架选 framer 全 m",
    prompt: "import { LazyMotion, domAnimation, m } from 'framer-motion'——为什么用 m 而非 motion？",
    options: [
      sc("A", "m 是「轻量版」motion 组件——配合 LazyMotion + domAnimation 只加载必要 features；vs 直接用 motion 触发完整 framer 包；包体积差异显著"),
      sc("B", "性能差"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "framer-motion 性能优化：LazyMotion + m + features 三件套。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 ImageData type 跨页",
    prompt: "interface ImageData { id: string | number; src: string; alt?: string; }——cv 与 gallery 都有 ImageData？",
    options: [
      sc("A", "页内本地 type，未抽到共享 types/——简历只有头像一张图，类型简单且与 gallery 不互通；本地化保持页面自洽"),
      sc("B", "复制粘贴失误"),
      sc("C", "TypeScript 限制"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "局部类型不必共享——保持文件自洽；过早抽象往往是坏味道。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 useLoaderData 解构",
    prompt: "const { avatarImage, content } = useLoaderData<typeof loader>();——typeof loader 用途？",
    options: [
      sc("A", "把 loader 函数返回类型自动推回前端；改 loader 字段（如加新内容块）TS 自动提示前端；类型从函数推 = 单一来源"),
      sc("B", "随机"),
      sc("C", "Cloudflare 强制"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix 类型推导黄金组合：useLoaderData<typeof loader>。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 pageMeta.cv()",
    prompt: "meta: MetaFunction = () => pageMeta.cv();——pageMeta 是？",
    options: [
      sc("A", "项目内 utils/seo.ts 集中所有页面 meta 配置；pageMeta.cv() 返该页 title/description/og 等；一处改全局生效；vs 每页硬编码 meta 字段易漂移"),
      sc("B", "TypeScript"),
      sc("C", "Cloudflare"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SEO 集中管理 = 单一来源，避免 meta 不一致。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/utils/seo.ts"],
  }),
  q({
    type: "single_choice", title: "Q11 forwardLoaderCacheControl",
    prompt: "headers = forwardLoaderCacheControl 与 TOKEN_DATA_CACHE_HEADERS 配套？",
    options: [
      sc("A", "loader 内 headers: TOKEN_DATA_CACHE_HEADERS 设到 loader Response；export const headers = forwardLoaderCacheControl 把它转写到 document Response；缺一不可"),
      sc("B", "可选"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "v3_singleFetch 双层 headers——loader + document 都要设。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q12 LazyMotion features",
    prompt: "<LazyMotion features={domAnimation}>——为什么 domAnimation 而非 domMax？",
    options: [
      sc("A", "domAnimation 只含 animate/initial/whileInView 等基础；domMax 多 layout/drag/gesture 大；本页用不上 = 不必加载；按需选 features"),
      sc("B", "TypeScript"),
      sc("C", "Cloudflare"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "features 按需选——简历页不需 drag/gesture。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 SSR 完整简历",
    prompt: "CV 页 SSR 输出？",
    options: [
      sc("A", "完整简历 HTML——所有文案 + 头像 src + emoji 都已渲染；JS 故障也能阅读；SEO 抓取一手内容；这就是 SSR-first 设计"),
      sc("B", "白屏"),
      sc("C", "占位"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader → SSR 完整内容；JS 故障也能用。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 改简历内容落点",
    prompt: "想改 self_evaluation.content 文案。改动？",
    options: [
      sc("A", "loader 内 content.self_evaluation.content 字符串改一处即可——文案在数据层；不改组件；npm run build 后部署"),
      sc("B", "改组件"),
      sc("C", "改 wrangler"),
      sc("D", "改 root"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "文案在 loader = 不接组件就能改；分层福利。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q15 文案改成 D1",
    prompt: "判断：把 content 从硬编码改到 D1 表里更专业。",
    correctAnswer: { value: false },
    explanation: { short: "错——简历是「我自己写的内容」，不需要并发更新、版本管理；硬编码 + git 即够；D1 只在多人多变内容才合适；过度工程是坏味道。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank", title: "Q16 头像路径 R2 prefix",
    prompt: 'rawAvatarImage.src = "____/person.webp"',
    options: [],
    blanks: [{ id: "v", placeholder: "目录", acceptedAnswers: ["Feedback"] }],
    correctAnswer: { type: "fill_blank", values: { v: "Feedback" } },
    explanation: { short: "Feedback/ 是 R2 内的目录前缀——历史命名延续，不必苛求。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 hobbies.gaming 字符串",
    prompt: "hobbies.gaming: '异世界冒险（总计1546h | 艾尔登法环100h白金 | 只狼无伤义父 | 羊蹄山之魂69小时白金 | 鸣潮214h）'——这种存数据？",
    options: [
      sc("A", "硬编码长字符串——便于一行展示；vs 拆成数组 + 渲染处 join 也行，但本场景一行简洁是优先项；数据形状由 UI 决定"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "数据形状服务 UI——简单字符串是最直接选择。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 长缓存可行性",
    prompt: "TOKEN_DATA_CACHE_HEADERS 通常给「token + data 多分钟」——为什么 CV 也用这个？",
    options: [
      sc("A", "CV 改一次再部署——内容静态，长缓存安全；与「带 token 的图片数据」一起复用同一缓存策略；常量集中"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "静态内容长缓存安全；常量复用降低决策成本。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 改部署后用户看不到新内容",
    prompt: "你改了 self_evaluation 部署，但用户刷新仍看旧——可能原因？",
    options: [
      sc("A", "CDN 缓存还没过期（max-age 长）；本地浏览器 cache 也命中；要等 TTL 或主动 purge CDN；vs 短 max-age 永远看到新（但请求量大）"),
      sc("B", "Worker 故障"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "缓存 vs 新鲜度的经典权衡——长缓存的代价。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 SSR token URL 时效",
    prompt: "resolveR2Image 生成的 URL 有时效（如 30 分钟）；CDN 缓存 29 分钟（接近）——边界？",
    options: [
      sc("A", "缓存期内 URL 仍有效；过期前 1 分钟用户拿到的 URL 即将失效但还能渲染；CDN 自动 revalidate 后拿到新 URL；用「token 寿命减 1 分钟」作 CDN s-maxage 是该模式的精髓"),
      sc("B", "永远新"),
      sc("C", "永远旧"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "缓存与 token 寿命对齐 = 既复用 CDN 又确保不发已死链接。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q21 加新「奖项」段",
    prompt: "想加 awards 段。改动？",
    options: [
      sc("A", "1) CVPageData 接口加 awards: { title, list: {...} } 2) loader 内 content.awards 填值 3) UI 渲染处加段——三处同步；类型先行避免漏"),
      sc("B", "改 wrangler"),
      sc("C", "改 root"),
      sc("D", "新建路由"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "类型 + 数据 + UI 三同步——typed loader 的标准扩展。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 整体设计哲学",
    prompt: "CV 整体哲学？",
    options: [
      sc("A", "1) emoji 替代 SVG icon 极致瘦身 2) loader 集中所有文案（数据/UI 分层）3) 头像 preload 优化 LCP 4) TOKEN_DATA_CACHE_HEADERS 集中缓存策略 5) framer LazyMotion + m + domAnimation 三件套 6) typeof loader 类型推导 7) pageMeta 集中 SEO 8) 趣味化梗文案——综合：极简 + 高性能 + 高可维护"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "八条原则——简历静态页的极致优化范式。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts", "app/utils/seo.ts", "app/generated/image-manifest.ts"],
  }),
];
