/**
 * Real questions for site-09-gallery-updates / gallery-route.
 * Anchor: remix/app/routes/gallery.tsx —— rawColumns 三列 + resolveR2Image + GSAP scrollTrigger 揭示 mask
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/gallery.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const galleryRouteQuestions: RealQ[] = [
  q({
    type: "single_choice", title: "Q1 rawColumns 三列结构",
    prompt: "loader 内 rawColumns: ImageData[][] = [[...],[...],[...]]——为什么按列分组而不是单一数组？",
    options: [
      sc("A", "瀑布流网格——CSS .gallery-grid 把每列单独渲染，每列内 vertical 堆叠 large/small；服务端预分组省客户端 reflow"),
      sc("B", "性能"),
      sc("C", "TypeScript 强制"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三列结构匹配 CSS Grid 多列瀑布流——服务端定布局。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank", title: "Q2 size 字段值域",
    prompt: 'photo.size: "____" | "small"',
    options: [],
    blanks: [{ id: "v", placeholder: "另一个值", acceptedAnswers: ["large"] }],
    correctAnswer: { type: "fill_blank", values: { v: "large" } },
    explanation: { short: "large 与 small 二态——匹配 CSS .gallery-item.large / .small 不同尺寸样式。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 resolveR2Image 转换",
    prompt: "columns.map(column => column.map(img => ({ ...img, src: resolveR2Image(img.src) })))——意图？",
    options: [
      sc("A", "把相对路径 '/photos/photo-1.webp' 转成 R2 CDN 完整 URL；服务端转换可直接 ssr 出最终 src，避免客户端再算"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "服务端转 CDN URL——SSR 最终态，零客户端额外 JS。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/resolve-image.ts"],
  }),
  q({
    type: "fill_blank", title: "Q4 缓存秒数",
    prompt: 'Cache-Control: "public, max-age=____, s-maxage=1740"',
    options: [],
    blanks: [{ id: "v", placeholder: "数字", acceptedAnswers: ["1740"] }],
    correctAnswer: { type: "fill_blank", values: { v: "1740" } },
    explanation: { short: "1740 秒（29 分钟）——R2 token 30 分钟，留 1 分钟 buffer。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 forwardLoaderCacheControl",
    prompt: "export const headers: HeadersFunction = forwardLoaderCacheControl;——必要？",
    options: [
      sc("A", "必要——v3_singleFetch 模式下 loader Cache-Control 默认不 forward 到 document Response；显式 export headers 才把它转写到 HTML 响应；不写则浏览器与 CDN 不缓存页面"),
      sc("B", "可选"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "v3_singleFetch + 缓存的标准做法——常被忘记。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q6 prefers-reduced-motion 守门",
    prompt: "useEffect 内 if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;——意图？",
    options: [
      sc("A", "用户系统层关掉了「减少动效」就跳过 GSAP 注册——尊重 a11y 偏好；前置 return 比加 try/catch 更干净"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "动效组件首条规则：尊重系统偏好。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 dynamic import GSAP",
    prompt: "void Promise.all([import('gsap'), import('gsap/ScrollTrigger')]).then(...)——为什么动态？",
    options: [
      sc("A", "GSAP 是大依赖（~50KB），不进入主 chunk；只有真要播动效的页（gallery）才下载，且 reduce-motion 用户根本不下载"),
      sc("B", "TypeScript 限制"),
      sc("C", "随机"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "动态 import = 按需下载——重依赖只给真正用到的页面。" },
    abilityTags: ["ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 cancelled flag",
    prompt: "let cancelled = false; ... cleanup () => { cancelled = true; ctx?.revert(); }——cancelled 用途？",
    options: [
      sc("A", "import 是异步的，组件可能在 Promise resolve 前已 unmount；then 内 if (cancelled) return; 防止往已卸载组件挂动效；ctx?.revert() 清理已挂的"),
      sc("B", "纯习惯"),
      sc("C", "TypeScript 要求"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "异步 + 卸载 = 经典竞态——cancelled flag 防过期 callback 跑。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 gsap.context",
    prompt: "ctx = gsap.context(() => { ... }, page);——context 的作用？",
    options: [
      sc("A", "把所有 gsap 创建的动画/ScrollTrigger 实例绑到 page DOM 容器；revert() 一次性清理所有；vs 手动 kill 一堆 timeline"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "gsap.context = 作用域 + 一键清理——动画卸载的标准做法。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 transform 而非 clip-path",
    prompt: "代码注释「Keep reveal work on transform/opacity; animating clip-path + blur repaints large photos.」——避免什么？",
    options: [
      sc("A", "transform/opacity 走 GPU 复合层不触发 layout/paint；clip-path/blur 触发整张大图重绘——大照片瀑布流帧率会炸；性能驱动的设计"),
      sc("B", "兼容性"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "动画属性选 GPU 友好的——大图渲染常识。" },
    abilityTags: ["ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 ScrollTrigger start",
    prompt: "scrollTrigger: { trigger: item, start: index === 0 ? 'top 92%' : 'top 86%', once: true }——为什么 index===0 不同？",
    options: [
      sc("A", "首张 hero 元素提早触发（top 92%）让进场更早一点；其他元素 86% 更晚一点等用户滚下来——细节优化"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "首屏 hero 提早触发 = 视觉先动；常见的细节调优。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 once: true",
    prompt: "scrollTrigger: { ..., once: true }——意图？",
    options: [
      sc("A", "动画只播一次——用户滚回页面不重播；省 CPU + 视觉不被打扰；瀑布流场景默认行为"),
      sc("B", "TypeScript 要求"),
      sc("C", "纯习惯"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "once = 只播一次——不重复打扰用户。" },
    abilityTags: ["frontend.effect.useEffect"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 mask scaleX",
    prompt: "gsap.set(mask, { scaleX: 1, transformOrigin: 'right center' }); ... .to(mask, { scaleX: 0, ... })——what is this？",
    options: [
      sc("A", "「擦除式」mask：初始 scaleX=1（铺满），动画 scaleX→0 从右往左收回（origin: right）；视觉效果像幕布拉开露出图片"),
      sc("B", "随机"),
      sc("C", "TypeScript 类型"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "scaleX + transformOrigin = 单方向收幕动画。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 timeline 三条同时",
    prompt: "gsap.timeline().to(item, ..., 0).to(mask, ..., 0.04).to(image, ..., 0.02)——参数 0/0.04/0.02 含义？",
    options: [
      sc("A", "时间线起点偏移（秒）：item 从 0 开始淡入；mask 0.04 秒后开始拉开；image 0.02 秒后开始放大；交错时间制造层次"),
      sc("B", "随机"),
      sc("C", "duration"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "timeline.to(target, vars, position) 第三参是绝对/相对偏移；交错制造质感。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q15 完整 useEffect 流",
    prompt: "Gallery 组件首次挂载步骤？",
    options: [
      sc("s1", "1. useEffect deps=[] 触发"),
      sc("s2", "2. const page = pageRef.current 拿到 DOM 容器"),
      sc("s3", "3. matchMedia 检查——非 reduce-motion 才继续"),
      sc("s4", "4. 创建 cancelled = false 标志"),
      sc("s5", "5. 动态 import GSAP + ScrollTrigger 并发"),
      sc("s6", "6. then 内 if(cancelled) return; gsap.registerPlugin"),
      sc("s7", "7. ctx = gsap.context(...) 注册所有元素的 timeline"),
      sc("s8", "8. cleanup 返回——卸载时 cancelled=true; ctx.revert()"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8"] },
    explanation: { short: "异步动画注册的标准 8 步——每一步都有目的。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 loading=eager vs lazy",
    prompt: "Hero 图 <img loading='eager'>，列表图 <img loading='lazy'>——两种？",
    options: [
      sc("A", "Hero 是 above-the-fold（首屏可见）必须立即加载；列表图视口外用 lazy 浏览器原生延迟加载——LCP + 流量双优化"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loading 属性按视口位置分——首屏 eager，下面 lazy。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 onError",
    prompt: "<img onError={() => console.error('Image failed to load:', photo.src)} />——意图？",
    options: [
      sc("A", "图片加载失败时打日志方便调试 R2 / CDN 问题；不替换为占位图（本项目策略）；生产可改为发到错误监控"),
      sc("B", "Cloudflare 强制"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "onError = 调试钩子；生产可接 Sentry 等。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 LazyMotion features",
    prompt: "<LazyMotion features={domAnimation}>——意图？",
    options: [
      sc("A", "framer-motion 默认全 features 打包大；用 LazyMotion + 只导 domAnimation 子集大幅瘦身；本页用到 m.span 等基础 motion 即够"),
      sc("B", "TypeScript"),
      sc("C", "纯习惯"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "framer 性能优化的标准做法——按需 features。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 GsapFillLink",
    prompt: "<GsapFillLink to='/xiao' prefetch='intent'>——为什么不用普通 Link？",
    options: [
      sc("A", "项目自定义包装：在 Remix Link 之上加 GSAP 填充动画 + prefetch='intent'（hover 即预取）；统一交互风格"),
      sc("B", "TypeScript 强制"),
      sc("C", "Cloudflare"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "封装组件 = 统一动画 + 预取 + 样式——项目级 Link 抽象。" },
    abilityTags: ["bridge.reactRouter.loader", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/ui/GsapFillLink.tsx"],
  }),
  q({
    type: "single_choice", title: "Q20 SSR 输出完整图片网格",
    prompt: "Gallery 页 SSR 输出的 HTML 内容？",
    options: [
      sc("A", "完整图片网格 HTML——所有 26 张图的 src/alt 都在；动效需要 client GSAP 接管，但内容（图、文）SSR 已渲染；SEO 友好"),
      sc("B", "白屏"),
      sc("C", "占位骨架"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix loader = SSR 完整内容；JS 故障也能看图。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 加新照片落点",
    prompt: "想给瀑布流加 6 张新照片。改动？",
    options: [
      sc("A", "loader 内 rawColumns 数组追加 6 条 ImageData；id 续号；size 决定 large/small；resolveR2Image 自动转 URL；client 由 ScrollTrigger 自动接管新 [data-gallery-mask]"),
      sc("B", "改 wrangler"),
      sc("C", "新建路由"),
      sc("D", "改 root"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "数据驱动 = 只改 loader 数组；UI 自动适配。" },
    abilityTags: ["code.position.handler", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 整体设计哲学",
    prompt: "Gallery 整体哲学？",
    options: [
      sc("A", "1) loader 服务端 resolveR2Image 出最终 URL 2) 三列结构匹配 CSS 瀑布流 3) Cache-Control 29 分钟接近 token 寿命 4) reduce-motion 守门 5) 动态 import GSAP 6) gsap.context 一键清理 7) transform/opacity 走 GPU 8) loading=eager/lazy 分场景——综合：性能 + a11y + SEO + 可维护"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare 决定"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "八条原则——内容展示页性能 + 体验范式。" },
    abilityTags: ["ai.review.architecture", "code.position.handler", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/lib/resolve-image.ts", "app/lib/cache-headers.server.ts"],
  }),
];
