/**
 * Real questions for site-09-gallery-updates / shared-layout.
 * Anchor: remix/app/components/ui/Header.tsx —— navigation 数组 + framer m.span layoutId 跟随线 + useOutletContext + fetcher 登出
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/ui/Header.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const sharedLayoutQuestions: RealQ[] = [
  q({
    type: "single_choice", title: "Q1 navigation 数组",
    prompt: "Header 内顶层 const navigation = [{ name: '个人简历', href: '/cv' }, ...] 7 项——存哪？",
    options: [
      sc("A", "组件文件顶层硬编码——导航固定不变；vs 抽到 data/ 仅当多组件复用时；目前只一个 Header 用，就近放最简洁"),
      sc("B", "API"),
      sc("C", "D1"),
      sc("D", "loader"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "导航是 UI 元数据 = 组件内常量；不必过度抽象。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 useOutletContext 取 session",
    prompt: "const { session, openLoginDialog } = useOutletContext<AppOutletContext>();——session 来自哪？",
    options: [
      sc("A", "root 路由 loader 设的 session 通过 <Outlet context={...} /> 传下来；任意子路由的子组件都能 useOutletContext 取到；vs 重复在每路由 loader 取 session"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Outlet context = 路由树共享数据；session 在 root 取一次全树用。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/types/remix.ts", "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q3 useFetcher submit",
    prompt: "const fetcher = useFetcher(); const handleSignOut = () => fetcher.submit(null, { method: 'post', action: '/auth/sign-out' });——为什么用 fetcher 而非 Form？",
    options: [
      sc("A", "fetcher.submit 不导航——登出后由服务端 action 决定是否 redirect；不污染浏览器 history；纯命令式调用 + 等响应；vs <Form> 默认会跳转"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "fetcher = 不导航的 form；登出/点赞类「副作用」操作首选。" },
    abilityTags: ["bridge.reactRouter.loader", "frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 prefetch='intent'",
    prompt: "<Link to={item.href} prefetch='intent'>——'intent' 触发条件？",
    options: [
      sc("A", "用户「打算点击」（hover 或 focus）时预取目标路由的 loader 数据——比 'render' 节流（仅 hover 才取）；点击时 loader 已 ready 几乎瞬间切换"),
      sc("B", "总是预取"),
      sc("C", "永不预取"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "intent = hover/focus 触发预取——节流又即时。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 m.span layoutId",
    prompt: "{hoveredNav === item.name && <m.span layoutId='nav-motion-line' className='ui-nav-motion-line' transition={{ type: 'spring', stiffness: 520, damping: 42, mass: 0.65 }} />}——layoutId 用途？",
    options: [
      sc("A", "framer-motion 跨组件位置共享——同一 layoutId 的 m.* 在不同位置 mount 时自动从旧位置 spring 动画到新位置；视觉上「下划线滑动跟随 hover」"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "layoutId 是 framer 的「跨组件位置过渡」——hover 跟随线效果靠它。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 onMouseLeave 容器",
    prompt: "<div onMouseLeave={() => setHoveredNav(null)}>...</div>——意图？",
    options: [
      sc("A", "鼠标离开整个导航容器才清除 hover——单个 Link 的 onMouseLeave 会在 link 间快速跳跃时打断动画；在容器上监听更稳定"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "在容器层监听 = hover 跟随更顺滑；细节体验。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 useEffect[mobileMenuOpen]",
    prompt: "useEffect 内 if (!mobileMenuOpen) return; document.body.style.overflow = 'hidden'; ... cleanup 还原——意图？",
    options: [
      sc("A", "移动菜单展开时锁住 body 滚动（避免菜单与 body 同时滚动错乱）；卸载或关闭时还原；同时监听 Escape 键关菜单——modal 行为标准实现"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "锁滚动 + Escape 关闭 = modal/抽屉的两条铁律。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 cleanup 还原 previousOverflow",
    prompt: "const previousOverflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; cleanup 内 document.body.style.overflow = previousOverflow;——为什么记录原值而非直接置空？",
    options: [
      sc("A", "如果其他组件已经设了 body.overflow（如 modal 嵌套），直接置 '' 会破坏其他组件的设置；先备份再还原 = 友好叠加"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "全局副作用要先 backup 再还原——避免破坏其他组件。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 getUserDisplayName",
    prompt: "user.name || user.email?.split('@')[0] || 'User'——三层兜底？",
    options: [
      sc("A", "优先 name（用户主动设的）→ 没 name 用 email 前缀（aaa@gmail.com → 'aaa'）→ 都没就 'User'；保证 UI 永远有可显示的字符串"),
      sc("B", "随机"),
      sc("C", "TypeScript 限制"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三层兜底 = UI 永不空字符；细节 UX。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 getUserInitial",
    prompt: "displayName?.charAt(0).toUpperCase() || 'U'——意图？",
    options: [
      sc("A", "头像 fallback：显示用户名首字母大写；name 为「张三」时返「张」（charAt 单字节安全）；没 name 兜底 U；vs 用真实头像图片少一张请求"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "首字母 avatar = 零图轻量替代；常见 fallback。" },
    abilityTags: ["frontend.state.local"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 三态 UI 渲染",
    prompt: "{!user ? <button>登录</button> : <div>头像 + 名字</div>}——session 三态？",
    options: [
      sc("A", "未登录（user=undefined） → 「登录」按钮；已登录 → 头像 + 名字 + 登出；session 加载中 SSR 没明确处理（这里默认走未登录态）"),
      sc("B", "永远登录"),
      sc("C", "永远登出"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "二态简化（loading 同未登录）= UX 友好不闪。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 LazyMotion 包导航",
    prompt: "<LazyMotion features={domAnimation}><div>...nav</div></LazyMotion>——只包导航部分？",
    options: [
      sc("A", "framer features 只在子树内可用；只包 nav（要 m.span）减小作用域；外层用 root.tsx 也包了一层时仍可嵌套但只用最近的；本组件即用即包是清晰做法"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "LazyMotion 局部包 = 作用域清晰；可嵌套但用最近的。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 data-auth-target",
    prompt: "<button data-auth-target='true' onClick={() => openLoginDialog()}>登录</button>——这个 data 属性？",
    options: [
      sc("A", "标记「这是触发登录入口的元素」——可能给登录引导动画/教学引擎扫描用（focus 它来高亮）；vs 用 className 选择器更优雅"),
      sc("B", "TypeScript"),
      sc("C", "Cloudflare"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "data-* 属性 = 自定义元数据钩子；常用于教学引导/测试。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 m.span 弹簧参数",
    prompt: "transition={{ type: 'spring', stiffness: 520, damping: 42, mass: 0.65 }}——三参意图？",
    options: [
      sc("A", "stiffness 520 弹力大快速 + damping 42 阻尼适中防过冲 + mass 0.65 轻 = 「快但不刚」体验；hover 跟随线觉感像橡皮筋——细调好的弹簧"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "spring 三参 = 力 + 阻 + 质——动画手感的核心调参。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 SSR Header 渲染",
    prompt: "Header 在 SSR 时渲染什么？",
    options: [
      sc("A", "完整导航 HTML + 「登录」按钮（默认 user=null）；framer m.span 仅在 client hover 才出现；登录后状态 client hydrate 才更新；SSR 默认匿名态"),
      sc("B", "白屏"),
      sc("C", "永远显示已登录"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SSR 完整导航 + 默认匿名；user 状态 client 接管后切显。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 加新导航项",
    prompt: "想加 /messages 到导航。改动？",
    options: [
      sc("A", "navigation 数组加 { name: '留言板', href: '/messages' } 即可——desktop + mobile 都自动 map 渲染；href 必须是 root 已声明的路由"),
      sc("B", "改 root"),
      sc("C", "改 wrangler"),
      sc("D", "改 routes.ts"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "数据驱动导航 = 加一行；UI 自动适配。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q17 用户登出完整流",
    prompt: "用户点击「登出」按钮 → 内部步骤？",
    options: [
      sc("s1", "1. handleSignOut 触发"),
      sc("s2", "2. fetcher.submit(null, { method: 'post', action: '/auth/sign-out' })"),
      sc("s3", "3. /auth/sign-out 路由 action 执行：清除 session cookie + 任何服务端清理"),
      sc("s4", "4. action 返 redirect('/') 或 json({ success: true })"),
      sc("s5", "5. fetcher 完成，触发整页 revalidation"),
      sc("s6", "6. root loader 重跑，session 现 undefined"),
      sc("s7", "7. Header 重渲染——!user 真，显示「登录」按钮"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7"] },
    explanation: { short: "fetcher 提交 + revalidation + UI 更新——RR 数据流闭环。" },
    abilityTags: ["bridge.reactRouter.loader", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/auth.sign-out.tsx", "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q18 keydown Escape",
    prompt: "useEffect 内 document.addEventListener('keydown', handleKeyDown);——为什么 document 而非元素？",
    options: [
      sc("A", "Escape 全局监听——不管焦点在哪都能关；vs 监听具体元素需要 focus 在它上才生效；modal/抽屉的 Escape 关闭习惯就是全局"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Escape = 全局键 = document 监听；modal 关闭标准做法。" },
    abilityTags: ["frontend.effect.useEffect", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 hoveredNav state 范围",
    prompt: "hoveredNav 是个 string | null state——必须？",
    options: [
      sc("A", "必须——决定 m.span layoutId 出现在哪个 link 内；纯 CSS :hover 不行因为要 layoutId 跨元素；这是 React state 跟 framer 的桥"),
      sc("B", "可省"),
      sc("C", "纯 CSS"),
      sc("D", "TypeScript 强制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "层级 hover 控制 + framer 跨组件动画 = state 必须。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q20 mobile menu 同样支持 Escape",
    prompt: "判断：mobileMenuOpen=true 时按 Escape 也会关菜单。",
    correctAnswer: { value: true },
    explanation: { short: "对——useEffect 内 if (event.key === 'Escape') setMobileMenuOpen(false)；与 modal 行为一致。" },
    abilityTags: ["frontend.effect.useEffect", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 Header 复用全站",
    prompt: "Header 在多少路由出现？",
    options: [
      sc("A", "全站——root.tsx 内一处挂载，所有子路由通过 <Outlet> 共享 Header；改 Header 一处全局生效；这就是 layout 复用的标准做法"),
      sc("B", "首页"),
      sc("C", "每路由各自挂"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Header 在 root 挂 = 全站统一壳；改一处全更新。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q22 整体设计哲学",
    prompt: "Header 整体哲学？",
    options: [
      sc("A", "1) navigation 数组数据驱动 7 项 2) prefetch=intent 节流预取 3) framer m.span layoutId 跟随线 4) useOutletContext 共享 session 5) fetcher.submit 不导航的登出 6) useEffect 锁滚 + Escape 关菜单 7) 三层兜底显示名 8) data-auth-target 教学钩子——综合：流畅交互 + 数据驱动 + a11y + 共享 layout"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "八条原则——全站 Header 的范式。" },
    abilityTags: ["ai.review.architecture", "code.position.handler", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/root.tsx", "app/types/remix.ts", "app/routes/auth.sign-out.tsx"],
  }),
];
