/**
 * Real questions for site-09-gallery-updates / updates-route.
 * Anchor: remix/app/routes/updates.tsx —— getSortedUpdates + IntersectionObserver TOC + UpdateCard 进场动画
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/updates.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const updatesRouteQuestions: RealQ[] = [
  q({
    type: "single_choice", title: "Q1 数据来源 getSortedUpdates",
    prompt: "loader 内 updates: getSortedUpdates() 来自 ~/data/updates——数据存储位置？",
    options: [
      sc("A", "构建时静态数组导入（updates.ts 内的 const updates: UpdateLog[]）；不查 D1；改更新日志要重新部署；个人站典型简化"),
      sc("B", "API 拉"),
      sc("C", "D1"),
      sc("D", "用户提交"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "更新日志 = 静态数组——无需 DB，部署即生效。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/data/updates.ts"],
  }),
  q({
    type: "fill_blank", title: "Q2 缓存秒数",
    prompt: 'Cache-Control: "public, max-age=____, s-maxage=3600"',
    options: [],
    blanks: [{ id: "v", placeholder: "数字", acceptedAnswers: ["3600"] }],
    correctAnswer: { type: "fill_blank", values: { v: "3600" } },
    explanation: { short: "3600 秒（1 小时）——更新日志变化频率低，可激进缓存。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 UpdateType 联合",
    prompt: "type UpdateType = 'feature' | 'fix' | 'improvement' | 'breaking'——四态用途？",
    options: [
      sc("A", "封闭枚举——getTypeStyles 按 type 返不同 bg/text/label；新增类型须改 4 处（type 联合 + getTypeStyles + UI 渲染 + data 文件）"),
      sc("B", "随机"),
      sc("C", "TypeScript 强制"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "封闭联合 = 编译时穷尽——加一项要全链路同步。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/data/updates.ts"],
  }),
  q({
    type: "single_choice", title: "Q4 getReleaseAnchor",
    prompt: "function getReleaseAnchor(update) { return `release-${update.id}`; }——用途？",
    options: [
      sc("A", "把 update.id 转成稳定 DOM id（如 'release-21'）；既给 <article id> 又给 IntersectionObserver target.id 又给 hash router；单一来源"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "纯函数生成 anchor——id 命名一致性的标准做法。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 UpdateCard 进场动画状态",
    prompt: "UpdateCard 内 useState isVisible/prefersReducedMotion + useEffect setTimeout——动画策略？",
    options: [
      sc("A", "不用 GSAP 也不用 framer——纯 CSS transition + setTimeout 触发 isVisible 切到 true（class 切换 opacity-0→100 / translate-y-4→0）；轻量；reduce-motion 直接 isVisible=true"),
      sc("B", "性能差"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "纯 CSS + setState 触发 = 最轻量进场动画；不必每页都 GSAP。" },
    abilityTags: ["frontend.effect.useEffect", "frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank", title: "Q6 delay 计算上限",
    prompt: "const delay = Math.min(index * 45, ____);",
    options: [],
    blanks: [{ id: "v", placeholder: "数字（毫秒）", acceptedAnswers: ["360"] }],
    correctAnswer: { type: "fill_blank", values: { v: "360" } },
    explanation: { short: "360ms 上限——超过 8 项就不再线性递增，避免最后一张要等几秒。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 mediaQuery.addEventListener",
    prompt: "useEffect 内 mediaQuery.addEventListener('change', handleChange)——意图？",
    options: [
      sc("A", "用户在系统设置切换「减少动效」时实时响应；既支持初始检测又支持运行时切换；专业级 a11y"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "matchMedia 不止用 .matches；监听 change 事件才算完整。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 IntersectionObserver TOC",
    prompt: "主组件 useEffect 内 new IntersectionObserver(...) 监听各 release 节点——意图？",
    options: [
      sc("A", "滚动时检测哪个 release 在视口；setActiveId 切换；TOC 中对应项高亮；用户始终知道当前看到哪个版本——锚点导航的标配"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "IntersectionObserver = 当前节高亮；TOC 与正文同步的标准方案。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 rootMargin 偏移",
    prompt: "{ rootMargin: '-22% 0px -58% 0px', threshold: [0.12, 0.28, 0.45] }——参数意图？",
    options: [
      sc("A", "rootMargin 缩小检测视口（-22% 顶部 + -58% 底部）让「中间区段」才算 active；threshold 多档触发——精细化判断进入比例"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "rootMargin 负值 = 缩小检测区——视觉中央区才高亮，避免顶部尾巴。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 visibleEntry 排序",
    prompt: "entries.filter(isIntersecting).sort((a,b) => b.intersectionRatio - a.intersectionRatio)[0]——意图？",
    options: [
      sc("A", "多个 entry 同时可见时挑「占比最大」那个作为 active——避免快速滚动时 active 跳来跳去；视觉稳定"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "占比最大 = 最该高亮的那个——稳定性优化。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 jumpToRelease",
    prompt: "jumpToRelease 内 element.scrollIntoView({ block: 'start', behavior: reduce ? 'auto' : 'smooth' })——意图？",
    options: [
      sc("A", "TOC 点击平滑滚动到 release；reduce-motion 用户用 'auto'（瞬移）尊重偏好；同时 history.replaceState 改 hash 但不入栈，避免污染浏览器返回"),
      sc("B", "原生 scroll"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "scrollIntoView + behavior 切换 + replaceState——锚点跳转专业版。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 useMemo releaseAnchors",
    prompt: "const releaseAnchors = useMemo(() => updates.map(getReleaseAnchor), [updates]);——为什么 useMemo？",
    options: [
      sc("A", "下面 useEffect 把 releaseAnchors 作 deps；不用 useMemo 每次渲染数组引用变 useEffect 频繁重订阅 IntersectionObserver；缓存住引用稳定"),
      sc("B", "性能差"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useMemo 稳定数组引用 = useEffect deps 不抖动——常见技巧。" },
    abilityTags: ["frontend.state.local", "frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 suppressHydrationWarning",
    prompt: "<article suppressHydrationWarning>——必要？",
    options: [
      sc("A", "isVisible 初始 false（SSR）；client mount 后切 true 触发 className 不同；React 警告 hydration mismatch；suppressHydrationWarning 只对该节点忽略"),
      sc("B", "可选"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "client-only 状态导致的 hydration mismatch——精准抑制是正确做法。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 isLatest prop",
    prompt: "<UpdateCard isLatest={index === 0} />——为什么不在 UpdateCard 内部判断？",
    options: [
      sc("A", "组件不应假设自己在数组哪个位置——位置语义应该从外层传入；保持组件纯函数化；可复用到其他「最新」语义不同的场景"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "位置/语义 props 从外注入 = 组件纯化原则。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 SSR 完整内容",
    prompt: "Updates 页 SSR 输出？",
    options: [
      sc("A", "完整 HTML——所有 release 卡片 + TOC 已渲染（虽然 isVisible=false 视觉透明）；SEO 抓取看到全文；JS 故障也能看到（用户可手动 inspect class 切显示）"),
      sc("B", "白屏"),
      sc("C", "占位"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader → SSR 完整内容；动画只是视觉装饰。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q16 滚动到第 3 版完整流",
    prompt: "用户从顶部滚到第 3 版 release 步骤？",
    options: [
      sc("s1", "1. 用户滚动触发 IntersectionObserver"),
      sc("s2", "2. observer callback 收到 entries 数组"),
      sc("s3", "3. filter(isIntersecting) 留下交叉的"),
      sc("s4", "4. sort intersectionRatio 取最大"),
      sc("s5", "5. setActiveId(target.id) 如 'release-19'"),
      sc("s6", "6. UpdatesToc 重渲染——activeId === anchor 的项加 bg-primary-50 高亮"),
      sc("s7", "7. 用户视觉上 TOC 滚动到对应项"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7"] },
    explanation: { short: "Observer + state + 同步 UI——TOC 联动完整链。" },
    abilityTags: ["frontend.effect.useEffect", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 TOC 隐藏交互",
    prompt: "TOC 默认 lg:max-h-0 + lg:opacity-0；group-hover/toc:max-h-[62vh] + opacity-100——意图？",
    options: [
      sc("A", "PC 端 hover 才展开 TOC，平时收起省空间；移动端默认水平滚动可见；纯 Tailwind class 实现，零 JS"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "纯 CSS hover 展开 = 零 JS 开销。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 UpdateLog.items 渲染",
    prompt: "update.items.map((item, itemIndex) => <li key={itemIndex}>...</li>)——key 用 index 是？",
    options: [
      sc("A", "可接受——items 数组是「静态、不会重排、不会插入」的；index 作 key 不会出 React 状态错乱；如果有重排就要换稳定 id"),
      sc("B", "总是错"),
      sc("C", "TypeScript 强制"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "key=index 不是绝对错；只在「不变更」场景下安全。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 latestUpdate 派生",
    prompt: "const latestUpdate = updates[0];——前提？",
    options: [
      sc("A", "前提是 getSortedUpdates 已按日期降序——updates[0] 即最新；这个不变量由数据层保证；UI 直接信任顺序"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "数据排序在 data 层；UI 信任不变量——分层职责。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/data/updates.ts"],
  }),
  q({
    type: "single_choice", title: "Q20 加新版本落点",
    prompt: "想加 v1.21.0 新版本。落点？",
    options: [
      sc("A", "只改 app/data/updates.ts——数组顶部加新条目；id 续号；type 选 feature/fix 等；这页 + 首页 changelog-section 自动展示（首页 .slice(0,4) 取前 4）"),
      sc("B", "改 wrangler"),
      sc("C", "改 root"),
      sc("D", "新建文件"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "单一来源原则——只改一处，多页自动同步。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: "app/data/updates.ts", layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: ["app/data/updates.ts", PRIMARY, "app/components/home/changelog-section.tsx"],
  }),
  q({
    type: "true_false", title: "Q21 IntersectionObserver SSR 安全",
    prompt: "判断：useEffect 内创建 IntersectionObserver 对 SSR 是安全的。",
    correctAnswer: { value: true },
    explanation: { short: "对——useEffect 仅 client 跑；SSR 不执行；浏览器 API 全 client 隔离。" },
    abilityTags: ["frontend.effect.useEffect", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 整体设计哲学",
    prompt: "Updates 整体哲学？",
    options: [
      sc("A", "1) 静态数组数据源（updates.ts）2) 服务端按时间排序 3) Cache 1 小时 4) 纯 CSS + setTimeout 进场动画 5) IntersectionObserver TOC 联动 6) reduce-motion 守门 7) suppressHydrationWarning 抑制 mismatch 8) 单一来源（首页 + 全档双消费）——综合：内容驱动的优雅长内容页"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "八条原则——版本日志页的范式。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/data/updates.ts", "app/components/home/changelog-section.tsx"],
  }),
];
