/**
 * Real questions for site-12-client-boundary / browser-api.
 * Anchor: remix/app/hooks/useNemesisChat.client.ts —— 浏览器 API 在 client 文件中的聚合：localStorage / window / document / navigator.clipboard / requestAnimationFrame / fetch + ReadableStream
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/hooks/useNemesisChat.client.ts";
const sc = (id: string, text: string) => ({ id, text });

export const browserApiQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 hook 文件后缀",
    prompt: "useNemesisChat.____.ts —— 后缀让浏览器 API 永不出现在 SSR bundle。",
    options: [],
    blanks: [{ id: "v", placeholder: "后缀", acceptedAnswers: ["client"] }],
    correctAnswer: { type: "fill_blank", values: { v: "client" } },
    explanation: { short: ".client 后缀 = 浏览器 API 集中地的物理隔离标志。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 hook 内浏览器 API 清单",
    prompt: "useNemesisChat 内用了哪些浏览器 API？",
    options: [
      sc("A", "localStorage（read/saveSessions）+ window.requestAnimationFrame（scrollToBottom）+ document.body / element.scrollTop / scrollHeight + navigator.clipboard.writeText + textareaRef DOM 操作 + fetch + SSE 解析；6+ 类浏览器 API 集中在 hook 内"),
      sc("B", "只 localStorage"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "hook 是浏览器 API 聚合地——多种 API 集中在客户端文件。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 localStorage 通过封装层调",
    prompt: "useEffect 内调 readNemesisChatSessions / saveNemesisChatSessions（来自 ~/lib/nemesis-chat-sessions.client）—— 为什么不直接 localStorage.getItem？",
    options: [
      sc("A", "封装层处理 try/catch（隐私模式抛错）+ JSON parse + 版本兼容 + 上限裁剪；hook 内只关心 'read sessions' / 'write sessions' 语义；持久化策略未来变化只动一处"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "localStorage 经封装 = 错误吸收 + 协议演进隔离。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/lib/nemesis-chat-sessions.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q4 requestAnimationFrame",
    prompt: "scrollToBottom 内 window.requestAnimationFrame(() => { ... });——rAF 是哪类 API？",
    options: [
      sc("A", "浏览器原生 API——告诉浏览器「下一帧绘制前调我」；用于布局/动画相关代码；SSR 无法跑（无浏览器渲染流水线）；必须在客户端文件"),
      sc("B", "Node API"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "rAF = 浏览器渲染时序 API；SSR 无该机制。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 navigator.clipboard",
    prompt: "copyMessage 内 navigator.clipboard.writeText(...)——这是哪类 API？",
    options: [
      sc("A", "浏览器原生 Clipboard API——异步读写剪贴板；返 Promise；SSR 无 navigator；权限 / 安全上下文（HTTPS）要求 + 可被用户拒绝"),
      sc("B", "Node"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "navigator.clipboard = 浏览器异步剪贴板；HTTPS 必需；客户端独有。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 .catch 异步错误处理",
    prompt: "navigator.clipboard.writeText(text).catch(() => { setError('复制失败'); });——为什么需要 catch？",
    options: [
      sc("A", "clipboard API 可能失败：1) 用户拒权限 2) 页面非 HTTPS（HTTP / 非安全上下文 API 不可用）3) 浏览器不支持；不 catch 会抛 unhandled rejection；UI 给反馈"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "异步浏览器 API 必有失败可能 → 必 catch + UI 反馈。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 ref 操作 DOM",
    prompt: "textareaRef.current.style.height = 'auto';——直接改 DOM 是反 React 模式？",
    options: [
      sc("A", "不算反模式——React ref 就是给 imperative DOM 操作的逃生口；测量布局（scrollHeight）要先重置高度才能测；声明式做不到的事用 ref 做；ref 是合法工具"),
      sc("B", "反模式"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ref = imperative DOM 逃生口；测量 + 调整场景合法。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 document 用法",
    prompt: "Header.tsx 的 useEffect 内 document.body.style.overflow = 'hidden';——为什么不用 ref？",
    options: [
      sc("A", "document.body 是文档级元素无法拿 ref；body 不属于 React 树；需要全局 DOM 操作时直接用 document API；effect 内用是安全的（已 hydrate）"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "document.body 等全局 DOM = 直接 API；ref 只对组件内元素。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/ui/Header.tsx"],
  }),
  q({
    type: "single_choice", title: "Q9 浏览器 API 在 useEffect 内",
    prompt: "为什么浏览器 API 通常包 useEffect？",
    options: [
      sc("A", "render 期间访问浏览器 API（document/window）会让组件 SSR 不安全 + 破坏 hydration；effect 在 hydrate 后跑保证 DOM 已就绪 + 不影响首渲一致；纪律性放置"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "浏览器 API → useEffect = SSR 安全 + DOM 就绪——惯例。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 fetch + ReadableStream",
    prompt: "requestNemesisReply 内用 fetch + response.body.getReader() —— 是什么 API？",
    options: [
      sc("A", "Web Streams API——response.body 是 ReadableStream；.getReader() 拿读流接口逐 chunk 读；用于 SSE / streaming 响应；浏览器 + Worker 都有但客户端代码更需关注"),
      sc("B", "Node 专有"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Web Streams = 流式读取响应；SSE 的底层。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/lib/nemesis-chat-api.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q11 hook 不直接 fetch",
    prompt: "useNemesisChat 不直接 fetch，调 requestNemesisReply 封装函数——为什么分层？",
    options: [
      sc("A", "网络层封装 SSE 解析 + 错误规范化 + 进度回调；hook 只关心「调函数 → 拿结果」；分层让网络协议变化（SSE → WebSocket）只改一层；hook 业务稳定"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "网络层封装 = 协议演进面隔离；hook 业务不动。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/lib/nemesis-chat-api.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q12 浏览器 API 封装的好处",
    prompt: "项目把 localStorage / fetch+SSE 都封装成 .client.ts 文件——共同好处？",
    options: [
      sc("A", "1) 错误吸收（隐私模式 / 网络断 / API 不支持）2) 接口契约让 hook 只看语义不看实现 3) 演进面隔离（迁 IndexedDB / WebSocket 时 hook 不动）；分层在浏览器 API 上同样成立"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "浏览器 API 封装 = 错误 + 契约 + 演进三个隔离层。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 BroadcastChannel / EventSource 等",
    prompt: "若想加多标签同步聊天状态——选哪个浏览器 API？",
    options: [
      sc("A", "BroadcastChannel —— 同源多标签广播频道；或 storage 事件监听 localStorage 变化；前者更主动后者被动；都封装 .client 后再调 hook"),
      sc("B", "WebSocket"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "多标签同步 = BroadcastChannel 或 storage 事件——都是浏览器 API。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 浏览器 API 测试",
    prompt: "测试浏览器 API 调用怎么 mock？",
    options: [
      sc("A", "vitest + jsdom 提供基础 DOM；localStorage 用 jsdom 默认实现；clipboard 用 Object.defineProperty 重写 navigator.clipboard；fetch 用 vi.fn() mock；分层 mock"),
      sc("B", "无法测"),
      sc("C", "只 e2e"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "jsdom + 手动 mock navigator/fetch = 浏览器 API 单测方案。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 SSR 不可达浏览器 API 列表",
    prompt: "Worker SSR 时不可用的浏览器 API 类别？",
    options: [
      sc("A", "1) DOM API（document/window/element）2) Storage（localStorage/sessionStorage/IndexedDB）3) navigator API（clipboard/userAgent/geolocation）4) 设备 API（camera/MIDI/USB）5) requestAnimationFrame 6) FileReader 等；都是浏览器特性"),
      sc("B", "全可用"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "浏览器特性 API SSR 都不可用——记住「无 DOM/Storage/Device」三大类。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 Worker SSR 可用的 API",
    prompt: "Worker SSR 可用的标准 Web API？",
    options: [
      sc("A", "1) fetch 2) Request/Response 3) Headers 4) ReadableStream 5) URL/URLSearchParams 6) crypto.subtle 7) TextEncoder/Decoder 8) Web Streams；与浏览器共享一套但无 DOM；网络/编码 API 通用"),
      sc("B", "全无"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Worker = Web 标准 API 子集（无 DOM / 设备）；网络 + 加密 + 流可用。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 错误：在 SSR 误用 window",
    prompt: "useNemesisChat 内顶层 if (typeof window !== 'undefined') { ... } —— 为什么这里不必？",
    options: [
      sc("A", "文件已是 .client 后缀——SSR bundle 内不存在该文件；typeof window 检查多余；如果改成无后缀文件才需要检查 + 用 useEffect 包；后缀让代码更直白"),
      sc("B", "应该加"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".client 后缀让 typeof window 检查冗余——code 更直白。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 错误：useEffect 内仍 typeof window",
    prompt: "useEffect(() => { if (typeof window !== 'undefined') localStorage.set(...); }, []) —— 检查多余？",
    options: [
      sc("A", "对——useEffect 只在客户端跑（SSR 不调 effect）；加 typeof window 检查纯多余；React 文档明示「effect 内必有 window」"),
      sc("B", "必要"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useEffect 内 window 永远存在——typeof window 检查冗余。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 浏览器 API 兼容性",
    prompt: "navigator.clipboard 在某些老浏览器不存在——hook 怎么处理？",
    options: [
      sc("A", "可在 copyMessage 内 if (!navigator.clipboard) return setError('您的浏览器不支持复制功能'); 或用 document.execCommand('copy') 兼容老浏览器；现在主流支持率高，大多项目直接用新 API + .catch 处理"),
      sc("B", "无法处理"),
      sc("C", "永远成功"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "新 API 兼容性 = 检测 + fallback；本项目用 .catch 简化处理。" },
    abilityTags: ["ai.review.architecture", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 浏览器 API 安全",
    prompt: "navigator.clipboard.writeText 与 navigator.clipboard.readText 安全级别差异？",
    options: [
      sc("A", "writeText 较宽松（用户主动操作触发即可）；readText 严格（用户必须显式点击 + 浏览器弹权限对话框）；安全设计——读取剪贴板可能拿到敏感数据"),
      sc("B", "完全等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "writeText 宽 readText 严——浏览器安全模型差异。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 浏览器 API 替代方案",
    prompt: "若项目想完全无浏览器 API（纯服务端渲染）—— 可行吗？",
    options: [
      sc("A", "理论可行但功能受限——无 localStorage 状态不持久（每次刷新清）+ 无 navigator 平台检测 + 无客户端动画；适合「报告/文档类」纯展示站；现代交互式应用必用浏览器 API"),
      sc("B", "可行无代价"),
      sc("C", "永远不行"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "无浏览器 API = 失去交互性；现代 SPA 必用。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 浏览器 API 整体哲学",
    prompt: "本项目浏览器 API 使用整体哲学？",
    options: [
      sc("A", "1) 集中 .client 后缀文件——hooks/useNemesisChat 是聚合地 2) 通过 .client.ts 工具层封装（错误 + 契约 + 演进）3) ref 用作 imperative DOM 逃生口（textareaRef）4) 全局 DOM（document.body）直接调 5) effect 内才安全（不在 render 期）6) 异步 API .catch 防 unhandled 7) 兼容性 + 权限考虑用 try/catch 兜底——综合：「物理隔离 + 封装 + ref 工具 + 异步处理」四件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "浏览器 API 7 原则——SSR 项目客户端 API 纪律。" },
    abilityTags: ["code.position.handler", "frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
];
