/**
 * Real questions for site-12-client-boundary / client-capstone.
 * Anchor: 综合 ClientOnly + .client 后缀 + lazy + Suspense + ViewportLazySection + 浏览器 API + hydration mismatch 七工具
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/common/ClientOnly.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const clientCapstoneQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 客户端边界工具数",
    prompt: "Remix + React 的客户端边界处理工具至少有 ____ 种（写整数）：ClientOnly / .client 后缀 / lazy / Suspense / useEffect / ViewportLazy / suppressHydrationWarning。",
    options: [],
    blanks: [{ id: "v", placeholder: "数字", acceptedAnswers: ["7", "七"] }],
    correctAnswer: { type: "fill_blank", values: { v: "7" } },
    explanation: { short: "7 种工具——客户端边界处理的工具箱。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 工具按职能分类",
    prompt: "客户端边界 7 工具的职能分组？",
    options: [
      sc("A", "时机控制：ClientOnly / useEffect；bundle 隔离：.client 后缀 / lazy；性能延迟：lazy / ViewportLazy / Suspense；hydration 修复：suppressHydrationWarning；按场景选不同工具"),
      sc("B", "全等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "工具按职能分四组——时机/bundle/性能/hydration。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 加新浏览器功能：决策树",
    prompt: "「需要在 /chat 页加 Web Audio 播放回复声音」——选什么工具？",
    options: [
      sc("A", "Web Audio 是浏览器独占——把音频播放代码放进新 hook useReplyAudio.client.ts；NemesisChatPage.client 已是 client 树，调 hook 即可；.client 后缀已隔离 SSR；不需要再加 ClientOnly"),
      sc("B", "ClientOnly"),
      sc("C", "lazy"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".client 后缀文件 = 浏览器 API 的天然栖息地；父级已客户端化无需再包。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 加新浏览器功能：决策树2",
    prompt: "「想在 /cv 页加一个 PDF 预览（用 react-pdf 库，不支持 SSR）」——怎么选？",
    options: [
      sc("A", "/cv 是普通 .tsx 路由（SSR）；用 ClientOnly 包 react-pdf 组件 + lazy 加载库 chunk；不必把整 cv 改 .client 因为 cv 多数内容应 SSR；ClientOnly 是局部包装"),
      sc("B", "改 .client"),
      sc("C", "新路由"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "局部不支持 SSR 的库 = ClientOnly + lazy；不必整页客户端化。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/cv.tsx"],
  }),
  q({
    type: "single_choice", title: "Q5 hydration mismatch vs ClientOnly",
    prompt: "页面出现 hydration mismatch ——加 ClientOnly 是合适的修复吗？",
    options: [
      sc("A", "看场景——若是「无可避免的客户端独有数据」（时间戳、随机数、localStorage）→ ClientOnly 合适；若是逻辑 bug（typeof window 误用）→ 改逻辑；先诊断再选工具"),
      sc("B", "永远合适"),
      sc("C", "永远不合适"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ClientOnly 不是 mismatch 万能药——根据原因选修法。" },
    abilityTags: ["ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 .client + ClientOnly 组合",
    prompt: "_index.tsx 内 <ClientOnly>{() => <ViewportLazySection><Suspense><BubbleMessageBoard.client /></Suspense></ViewportLazySection>}</ClientOnly>——四工具叠加意图？",
    options: [
      sc("A", "ClientOnly：SSR 时绝对不渲（防 mismatch）；ViewportLazy：接近视口才挂；Suspense：处理 .client 文件 lazy chunk 加载；.client：bundle 不进 SSR；四层各司一职极致优化首屏"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ClientOnly+ViewportLazy+Suspense+.client 四层组合 = 首屏极致延迟。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/_index.tsx"],
  }),
  q({
    type: "single_choice", title: "Q7 性能预算视角",
    prompt: "首屏 JS 体积超标——客户端工具如何降？",
    options: [
      sc("A", "1) 把重组件改 .client + lazy → 不进 SSR bundle 也分 client chunk 2) ViewportLazy 让首屏只下载必要 chunk 3) 浏览器 API 重的库改动态 import；逐项压；profile 看具体大块"),
      sc("B", "无法降"),
      sc("C", "永远要"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "首屏体积优化 = .client 隔离 + lazy 分 chunk + viewport 延迟挂载——三件事。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/_index.tsx"],
  }),
  q({
    type: "single_choice", title: "Q8 .client 后缀的 bundle 影响",
    prompt: ".client 后缀对 SSR bundle vs Client bundle 的影响？",
    options: [
      sc("A", "SSR bundle：完全不打入；Client bundle：正常打入（除非配 lazy 才分 chunk）；工具粒度：「文件级」物理隔离；vs ClientOnly 是「实例级」延迟"),
      sc("B", "都打"),
      sc("C", "都不打"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".client 文件级隔离 SSR bundle；客户端正常打。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 SSR 体积 vs Client 体积",
    prompt: "本项目 build 产物：SSR bundle ~903KB，Client worker entry ~262KB——为什么 SSR 反而大？",
    options: [
      sc("A", "SSR bundle 含 Better Auth + D1 客户端 + 业务逻辑 + Remix runtime；客户端 bundle 主要是 React + 路由切换 + UI 组件 + .client 文件；服务端代码层数往往更多"),
      sc("B", "异常"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SSR bundle 含完整业务 + auth + DB；client bundle 是 UI——两者大小相对自然。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q10 用户首次访问 /chat 综合时序",
    prompt: "用户首次访问 /chat 触发七工具综合时序？",
    options: [
      sc("s1", "1. Worker SSR：chat.tsx loader 跑（鉴权、headers）"),
      sc("s2", "2. SSR 渲染 Outlet 内 NemesisChatPage（.client 文件）→ import 被替换 placeholder → 输出空"),
      sc("s3", "3. HTML 返浏览器 + 显示空白聊天区"),
      sc("s4", "4. Client bundle 加载：React + 路由切换 + chat 路由 chunk"),
      sc("s5", "5. NemesisChatPage.client.tsx 通过 import 解析挂载"),
      sc("s6", "6. React hydrate 阶段 → useNemesisChat hook 调用"),
      sc("s7", "7. hook 内 5 useEffect 跑：读 localStorage → 设状态 → focus textarea → 滚到底"),
      sc("s8", "8. 子组件 (Sidebar/Header/MessageList/Composer) 全挂载 + props 透传 hook 数据"),
      sc("s9", "9. 用户看到完整聊天 UI 含历史会话——七工具协奏完成"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8", "s9"] },
    explanation: { short: ".client + hydrate + hook + effect + 子组件——9 步完成首屏到交互。" },
    abilityTags: ["code.position.handler", "frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/chat.tsx", "app/components/nemesis/chat/NemesisChatPage.client.tsx", "app/hooks/useNemesisChat.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q11 客户端边界 vs CDN 缓存",
    prompt: ".client 文件影响 CDN 缓存吗？",
    options: [
      sc("A", "不影响——CDN 缓存的是 HTTP 响应（HTML/JS chunk）；.client 后缀只影响 build 时打包决策；CDN 看 URL + Cache-Control 头；两件不同事"),
      sc("B", "影响"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".client = build 时；CDN = 运行时——不同维度无相互影响。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 React Server Components",
    prompt: "RSC 时代客户端边界还需要这些工具吗？",
    options: [
      sc("A", "RSC 用 \"use client\" 标记替代 .client 后缀 + 边界更明确；ClientOnly 仍可用于「客户端组件内的延迟挂载」；hydration 概念仍在；Suspense 与 RSC 深度集成；工具演进但思路不变"),
      sc("B", "全废"),
      sc("C", "完全相同"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "RSC = 'use client' 替代 .client；其他工具仍适用——演进但思路一致。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 测试客户端边界",
    prompt: "怎么单测 ClientOnly + .client 文件 + lazy 组合？",
    options: [
      sc("A", "1) ClientOnly：jsdom 里 mount 检 fallback → wait → 检 children 内容 2) .client 文件：build 时检产物（grep SSR bundle 不含该文件名）3) lazy + Suspense：用 react-testing-library + waitFor；分层各测各"),
      sc("B", "无法测"),
      sc("C", "只 e2e"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "客户端边界三层各自有合适的测试手段——分层验证。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 删除某个 .client 后缀",
    prompt: "若误把 NemesisChatPage.client.tsx 改名 NemesisChatPage.tsx——后果？",
    options: [
      sc("A", "Remix build 把它打入 SSR bundle；SSR 渲染时调 useNemesisChat → 内部 readNemesisChatSessions 调 localStorage → ReferenceError → SSR 整页失败 500；建议立刻撤回"),
      sc("B", "无影响"),
      sc("C", "只警告"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".client 后缀缺失 = SSR 误打浏览器 API → 运行时 ReferenceError → 500。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 ClientOnly 性能担忧",
    prompt: "ClientOnly 让首屏少渲一部分内容——SEO 影响？",
    options: [
      sc("A", "影响——SEO 爬虫拿到 SSR HTML 看不到 ClientOnly 包内容；如果该内容是 SEO 相关（标题/描述）应避免 ClientOnly；ClientOnly 适合「无 SEO 价值」的交互组件（如聊天/动画）"),
      sc("B", "无影响"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ClientOnly 内容不可被 SEO 爬虫看到——按 SEO 价值选择是否包。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 客户端边界监控",
    prompt: "线上想监控 hydration mismatch 频率——落点？",
    options: [
      sc("A", "拦截 console.warn / window.onerror 抓 'Hydration' / 'mismatch' 关键词；上报 Sentry；React 19 还有专门 onHydrationError 选项；多点监控"),
      sc("B", "无法监"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "拦 console.warn + onHydrationError = mismatch 监控双路径。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 项目客户端边界全景",
    prompt: "本项目客户端边界处理布局是？",
    options: [
      sc("A", "1) ClientOnly 用于 _index.tsx 内的 BubbleMessageBoard 等 2) .client 后缀给整个 nemesis 聊天模块（NemesisChatPage / useNemesisChat / nemesis-chat-api / nemesis-chat-sessions）+ BubbleMessageBoard.client 3) lazy 给首页大量下方组件 4) Suspense 处理 lazy chunk 5) ViewportLazy 视口可见才挂；五者协作"),
      sc("B", "全用 ClientOnly"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "本项目 5 种工具协作——按场景配 .client / ClientOnly / lazy / Suspense / ViewportLazy。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 决策表",
    prompt: "选择客户端边界工具的决策依据？",
    options: [
      sc("A", "1) 全文都浏览器 API → .client 后缀（永久客户端 + bundle 隔离）2) 只这一处 → ClientOnly（局部延迟）3) 大组件 + 概率低被看 → lazy + Suspense 4) 视口外 → ViewportLazy 5) 时间戳类预期 mismatch → suppressHydrationWarning；按场景查表"),
      sc("B", "随机选"),
      sc("C", "全 ClientOnly"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "工具决策表 = 文件级 vs 实例级 vs 资源 vs 视口 vs 预期 mismatch。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 现有架构演进",
    prompt: "若想让 useNemesisChat 在 Worker 服务端也能跑（如 SSR 注水会话）——要变成 .universal.ts？",
    options: [
      sc("A", "重写 hook 让浏览器 API 全包 typeof window 或抽到子文件 *.client.ts；hook 主体 SSR 安全；接收 initialSessions props 让 SSR 能传初值；这是「同构 hook」改造方向"),
      sc("B", "不可改"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "同构 hook = 浏览器 API 抽到 .client 子模块；主体 SSR 安全 + 接 initialProps。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/hooks/useNemesisChat.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q20 客户端边界与 a11y",
    prompt: "首屏 SSR 不渲 ClientOnly 内容（如聊天 UI）——a11y 影响？",
    options: [
      sc("A", "屏幕阅读器读 SSR HTML 时看不到聊天区；用户感知「页面加载中」；hydrate 后 React 触发 DOM 变化阅读器会重新读；如重要内容应考虑 SSR fallback 或避免 ClientOnly"),
      sc("B", "无影响"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ClientOnly 内容初渲不可见 → 屏幕阅读器看不到——影响 a11y 体验。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 滥用 ClientOnly 的代价",
    prompt: "若把所有组件都包 ClientOnly——后果？",
    options: [
      sc("A", "失去 SSR 优势：1) 首屏白屏长 2) SEO 看不到内容 3) hydrate 工作量集中爆发 4) 用户感知慢；ClientOnly 是工具不是默认；「需要 SSR」的内容不要包"),
      sc("B", "性能更好"),
      sc("C", "无影响"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ClientOnly 滥用 = 失 SSR 优势——按场景用。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 客户端边界整体哲学（毕业级）",
    prompt: "site-12 客户端边界综合哲学？",
    options: [
      sc("A", "1) 七工具按场景选：.client 后缀 / ClientOnly / lazy / Suspense / ViewportLazy / useEffect / suppressHydrationWarning 2) 文件级 vs 实例级隔离粒度差异 3) SSR 与客户端首渲一致是 hydration 铁律 4) 浏览器 API 集中到 .client 文件 + 封装层 5) 不滥用 ClientOnly 保 SEO/a11y 6) 三层组合（.client + lazy + ClientOnly + Suspense + Viewport）极致优化首屏 7) RSC 演进但思路不变——综合：「物理隔离 + 时机控制 + 性能延迟 + hydration 一致」四件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "客户端边界 7 原则——SSR 项目工程纪律的中坚。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/_index.tsx", "app/components/nemesis/chat/NemesisChatPage.client.tsx", "app/hooks/useNemesisChat.client.ts"],
  }),
];
