/**
 * Real questions for site-12-client-boundary / client-only.
 * Anchor: remix/app/components/common/ClientOnly.tsx —— 19 行：useState hasMounted + useEffect 设 true + render 期 fallback；防止 SSR 渲染浏览器组件
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/common/ClientOnly.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const clientOnlyQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 ClientOnly 行数",
    prompt: "ClientOnly.tsx 仅 ____ 行（写整数）。",
    options: [],
    blanks: [{ id: "v", placeholder: "数字", acceptedAnswers: ["19", "20"] }],
    correctAnswer: { type: "fill_blank", values: { v: "19" } },
    explanation: { short: "19 行——React 经典「mount 后再渲」组件；极简。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 children 类型",
    prompt: "interface ClientOnlyProps { children: () => ReactNode; fallback?: ReactNode; }——为什么 children 是函数？",
    options: [
      sc("A", "lazy 渲染——挂载前不调用 children() 函数；children 内的浏览器 API（如 window）不会在 SSR 阶段被求值；vs ReactNode 子元素会在 SSR 时构造"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "function as children = render-prop 模式——延迟构造直到 mount。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 hasMounted 初值 false",
    prompt: "const [hasMounted, setHasMounted] = useState(false);——初值 false 含义？",
    options: [
      sc("A", "SSR 阶段 useState 初值 false → 渲染走 fallback 分支；hydrate 时初值仍 false → 客户端首渲 HTML 与 SSR 一致防 hydration mismatch；之后 useEffect 设 true 触发重渲展示真子组件"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "false 初值 = SSR 与 hydrate 一致显 fallback；mount 后才显真组件。" },
    abilityTags: ["frontend.state.local", "frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 useEffect 设 true",
    prompt: "useEffect(() => { setHasMounted(true); }, []);——空依赖含义？",
    options: [
      sc("A", "只在挂载后跑一次——设 hasMounted=true 触发重渲；后续 React 状态变化不再触发；'set once on mount' 模式"),
      sc("B", "永远跑"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "空依赖 + setMounted = 挂载后单次切换状态。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 if (!hasMounted) return fallback",
    prompt: "if (!hasMounted) { return fallback; } return <>{children()}</>;——条件渲染顺序？",
    options: [
      sc("A", "未挂载先返 fallback（默认 null）—— SSR 与首次客户端渲染都是这个分支；挂载后 effect 触发重渲走第二分支调 children() 渲染真组件；时序清晰"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "fallback 优先 + 真组件后置 = 防 SSR 触发浏览器 API。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 fallback 默认 null",
    prompt: "fallback?: ReactNode = null;——默认 null 影响？",
    options: [
      sc("A", "未指定 fallback 时 SSR 不渲任何东西；首屏空白片段 → 挂载后才显内容；如果不希望首屏闪烁应自定义 fallback（如骨架屏/loading）"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "default fallback=null = SSR 留空白；按需自定义 skeleton。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 ClientOnly vs typeof window",
    prompt: "为什么不直接 if (typeof window === 'undefined') return null; 在组件内？",
    options: [
      sc("A", "typeof window 检查会让 SSR 渲 null，hydrate 时客户端却走另一分支渲 children — React 报 hydration mismatch；ClientOnly 用 useState 让 SSR + hydrate 首渲一致再 effect 切——避免 mismatch"),
      sc("B", "等价"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "typeof window 检查破坏 hydration；ClientOnly 用 effect 模式避免 mismatch。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 与 Suspense 区别",
    prompt: "ClientOnly 与 React Suspense 的区别？",
    options: [
      sc("A", "ClientOnly 防「SSR 不该渲的浏览器组件」；Suspense 处理「异步加载中的 chunk/data」；前者是「时机控制」（等 mount），后者是「资源等待」；可叠加使用"),
      sc("B", "完全等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ClientOnly = 时机；Suspense = 资源等待——两件不同事可叠加。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 ClientOnly vs .client 后缀",
    prompt: "ClientOnly 包裹一个普通组件 vs 把组件改 .client 后缀——哪种更好？",
    options: [
      sc("A", "都可，场景不同：1) ClientOnly 适合「这个组件偶尔 SSR、偶尔 client」灵活包装 2) .client 后缀适合「组件全文都是浏览器 API，永远 client 打包」省 SSR bundle；后者还能让 server bundle 更小"),
      sc("B", "完全等价"),
      sc("C", "ClientOnly 永远更好"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ClientOnly = 灵活包装；.client = 永久客户端 + bundle 优化——按需选。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 _index.tsx 用法",
    prompt: "_index.tsx 内 <ClientOnly fallback={<div className=\"...animate-pulse\" />}>{() => <ViewportLazySection><Suspense><BubbleMessageBoard ... /></Suspense></ViewportLazySection>}</ClientOnly>——为什么三层？",
    options: [
      sc("A", "ClientOnly 防 SSR 触发（最外）+ ViewportLazySection 直到接近视口才挂载（中）+ Suspense 处理 lazy chunk 加载（内）；三层处理三类延迟原因；典型组合"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三层延迟堆叠：SSR 时机 + 视口可见 + 资源加载——各管一事。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/routes/_index.tsx"],
  }),
  q({
    type: "branch_trace", title: "Q11 SSR 到 hydrate 流程",
    prompt: "用户首次访问含 ClientOnly 的页面，完整 render 步骤？",
    options: [
      sc("s1", "1. SSR 阶段：ClientOnly 组件渲染时 hasMounted=false（useState 初值）"),
      sc("s2", "2. 走 if (!hasMounted) 分支返 fallback"),
      sc("s3", "3. SSR HTML 输出 fallback 内容"),
      sc("s4", "4. 浏览器收 HTML 并显示 fallback"),
      sc("s5", "5. JS 加载完 → React hydrate 阶段：useState 初值仍 false → 渲染 fallback 与 SSR HTML 一致 → hydrate 成功无 mismatch"),
      sc("s6", "6. hydrate 后 useEffect 跑 → setHasMounted(true)"),
      sc("s7", "7. 状态变化触发重渲 → 走 return <>{children()}</> 分支"),
      sc("s8", "8. children() 函数被调，构造真子组件并渲染"),
      sc("s9", "9. 真子组件挂载，浏览器 API 安全使用"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8", "s9"] },
    explanation: { short: "ClientOnly 完整时序 9 步——SSR + hydrate + effect 切换。" },
    abilityTags: ["frontend.state.local", "frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 fallback 与子组件 layout",
    prompt: "fallback 高度与真子组件高度差异——影响？",
    options: [
      sc("A", "切换瞬间 layout shift（页面其他内容上下跳）；CLS 指标恶化；推荐 fallback 高度匹配真组件（如 skeleton 同尺寸 div）"),
      sc("B", "无影响"),
      sc("C", "性能更好"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "fallback 高度差 = layout shift + 烂 CLS——尺寸应匹配。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 ClientOnly 嵌套",
    prompt: "ClientOnly 内再嵌套 ClientOnly——有意义吗？",
    options: [
      sc("A", "无意义——外层已挂载意味着内层 mount 时也已 mount；嵌套是冗余；删掉内层即可"),
      sc("B", "必要"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ClientOnly 嵌套冗余——外层 mount 推到内层即 mount。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 ClientOnly 内有 useState",
    prompt: "<ClientOnly>{() => <ComponentWithState />}</ClientOnly>——子组件内 useState 行不？",
    options: [
      sc("A", "行——挂载后才构造子组件树，useState 在 mount 阶段才被调用；与正常 React 等价；唯一差别是「首次挂载比无 ClientOnly 晚一帧」"),
      sc("B", "禁止"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ClientOnly 内的子组件正常 React；只是延迟挂载一拍。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 ClientOnly 与服务端渲染数据",
    prompt: "如果想 ClientOnly 内的子组件也用 useLoaderData——可行吗？",
    options: [
      sc("A", "可行——useLoaderData 在客户端也工作（hydrate 后从 window.__remixContext 拿数据）；ClientOnly 不影响 loader 数据获取；只延迟挂载"),
      sc("B", "无法"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ClientOnly 不影响 loader 数据流——loader 已 SSR 获取，hydrate 后挂上即可消费。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 children 函数 vs ReactNode",
    prompt: "若改 children: ReactNode 直接接收子元素——有什么坏处？",
    options: [
      sc("A", "JSX <ClientOnly><Comp /></ClientOnly> 在 SSR 阶段会构造 <Comp /> React 元素（虽不渲染），若 <Comp /> 顶层有 throw new Error('window is undefined') 则 SSR 直接挂；函数 children 让构造也延迟"),
      sc("B", "无差"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "函数 children = 连构造都延迟——比 ReactNode 更安全。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 React Strict Mode 双调",
    prompt: "React 18 Strict Mode 会让 useEffect 双调——hasMounted 设两次会有问题吗？",
    options: [
      sc("A", "无问题——setState 同值（true）React 跳过重渲；幂等操作；Strict Mode 双调测试不影响行为"),
      sc("B", "崩溃"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "setState 幂等 = Strict Mode 安全。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 useSyncExternalStore 替代",
    prompt: "React 18 加了 useSyncExternalStore——能替代 ClientOnly 吗？",
    options: [
      sc("A", "可——useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot) 让 SSR 与客户端可分别返不同值；ClientOnly 是更早的 useState+useEffect 模式；新代码可考虑 useSyncExternalStore；本项目用经典实现"),
      sc("B", "无关"),
      sc("C", "永远不可"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useSyncExternalStore 是新方案；老 ClientOnly 仍能用。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 加 fallback height 参数",
    prompt: "若想给 ClientOnly 内置默认 skeleton（高度可控）——改造？",
    options: [
      sc("A", "扩 props 加 height?: string；fallback 默认改 <div className={`bg-pulse h-${height} ...`} />；调用方简化；但反而强加 UI 决策——保持 fallback?: ReactNode 让调用方完全控更灵活"),
      sc("B", "立刻加"),
      sc("C", "永不加"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ClientOnly 应保持纯——fallback 由调用方决定；通用组件不强加 UI。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 测试 ClientOnly",
    prompt: "怎么测试 ClientOnly？",
    options: [
      sc("A", "1) 单测 SSR：renderToString 应只见 fallback 不见 children 内容 2) 单测 hydrate：mount 后 wait → children 内容出现 3) 双调 useEffect 不出错；分层测保正确性"),
      sc("B", "无法测"),
      sc("C", "只 e2e"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ClientOnly 测试：SSR 看 fallback + mount 看 children——两阶段。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 何时该用 ClientOnly",
    prompt: "什么场景该用 ClientOnly？",
    options: [
      sc("A", "1) 子组件含 window/document/localStorage 等浏览器 API 在顶层 2) 第三方库不支持 SSR（如某些 chart 库）3) 视觉上 SSR 渲不出对的占位的内容（动态 canvas）；这三类用 ClientOnly 适合"),
      sc("B", "永远要"),
      sc("C", "永远不要"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ClientOnly 三场景——按需用，不滥用。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 ClientOnly 整体哲学",
    prompt: "ClientOnly 19 行整体设计哲学？",
    options: [
      sc("A", "1) function as children 延迟构造连 React 元素都不创建 2) useState false 初值 + useEffect 切 true = SSR/hydrate 一致 + mount 后切真组件 3) fallback 默认 null 留空白由调用方自定义 4) 与 .client 后缀互补：灵活包装 vs 永久 client 5) 与 Suspense 互补：时机 vs 资源 6) 不强加 UI 决策保通用——综合：「极简渲染时机控制器」"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ClientOnly 6 原则——19 行解决一类常见 SSR 渲染时机问题。" },
    abilityTags: ["frontend.effect.useEffect", "frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
];
