/**
 * Real questions for site-12-client-boundary / dot-client.
 * Anchor: remix/app/components/nemesis/chat/NemesisChatPage.client.tsx —— 66 行：用 useNemesisChat hook + 4 个子组件组合；.client 后缀让全文件只进客户端 bundle
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/nemesis/chat/NemesisChatPage.client.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const dotClientQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 文件后缀",
    prompt: "NemesisChatPage.____.tsx —— 后缀让 Remix 编译时只把它打到客户端 bundle。",
    options: [],
    blanks: [{ id: "v", placeholder: "后缀", acceptedAnswers: ["client"] }],
    correctAnswer: { type: "fill_blank", values: { v: "client" } },
    explanation: { short: ".client 后缀强制客户端打包；服务端 bundle 内不含此文件。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 .client vs .server 对称",
    prompt: ".client 后缀与 .server 后缀的对称设计？",
    options: [
      sc("A", ".server 让文件只进 Worker bundle（不进浏览器）；.client 让文件只进浏览器 bundle（不进 Worker）；两套机制让代码物理隔离不同 runtime；防止误用"),
      sc("B", "完全等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".server 与 .client 对称分割——按 runtime 物理分隔代码。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 为什么 NemesisChatPage 用 .client",
    prompt: "NemesisChatPage 内调 useNemesisChat() 含浏览器 API（localStorage、SSE、fetch streaming）——为什么必须 .client？",
    options: [
      sc("A", "SSR 阶段无 localStorage / window；如果 NemesisChatPage 进入 SSR bundle，Worker 跑代码时这些 API 引用会抛 ReferenceError；.client 后缀直接禁止它进 SSR；机制隔离"),
      sc("B", "TypeScript"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".client 是「浏览器 API 隔离 SSR」的物理保证。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 chat.tsx 内 import",
    prompt: "chat.tsx 路由文件内 import NemesisChatPage from '~/components/nemesis/chat/NemesisChatPage.client';——服务端能读这个 import 吗？",
    options: [
      sc("A", "服务端 SSR bundle 内 import 被 Remix 替换为占位符——不实际加载该文件；SSR 渲染时该位置渲染 null 或空 placeholder；客户端 hydrate 后真正挂载"),
      sc("B", "崩溃"),
      sc("C", "正常加载"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".client import 在 SSR 时被替换为 null placeholder——hydrate 时挂真组件。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/chat.tsx"],
  }),
  q({
    type: "single_choice", title: "Q5 .client 与 ClientOnly 互补",
    prompt: ".client 后缀与 ClientOnly 组件的关系？",
    options: [
      sc("A", "互补——.client 是「文件级永久客户端打包」（适合本身就是浏览器特性组件），ClientOnly 是「实例级延迟挂载」（适合偶尔需要 SSR 内嵌的组件）；两个工具按场景选"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".client = 文件级；ClientOnly = 实例级——场景不同。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/components/common/ClientOnly.tsx"],
  }),
  q({
    type: "single_choice", title: "Q6 NemesisChatPage 文件结构",
    prompt: "NemesisChatPage.client.tsx 66 行做什么？",
    options: [
      sc("A", "1) import 4 个子组件（Sidebar/Header/MessageList/Composer）+ useNemesisChat hook 2) 调 hook 拿状态控制器 3) 渲染：左 Sidebar + 右主区（Header + MessageList + Composer）+ props 透传 hook 字段；薄壳 + 子组件分工"),
      sc("B", "厚业务"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "NemesisChatPage = ViewModel 适配层——hook 给状态、子组件给 UI 块。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 const chat = useNemesisChat()",
    prompt: "整页只调一次 useNemesisChat()——所有子组件共享同一个 hook 实例数据；为什么集中？",
    options: [
      sc("A", "hook 内 14 useState 是「整页状态机」——若每个子组件各自调 hook 会有 4 份独立状态相互不同步；集中调 + props 透传是 React 共享状态的标准做法（vs Context）"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "状态集中 + props 透传 = 单一来源；多 hook 实例会数据撕裂。" },
    abilityTags: ["frontend.state.scope", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 props drilling 4 层",
    prompt: "NemesisChatPage 把 chat.* 字段几十个透传给 4 子组件——是 props drilling 反模式吗？",
    options: [
      sc("A", "不算反模式——只透 1 层（NemesisChatPage → 直接子组件）；React 文档推荐这种「一层透传」明示数据流；3+ 层才考虑 Context；当前结构直白可读"),
      sc("B", "应改 Context"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "1 层 props 不是 drilling；显式数据流胜于隐式 Context。" },
    abilityTags: ["frontend.state.scope", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 子组件命名空间",
    prompt: "Sidebar/Header/MessageList/Composer 都是 NemesisChat* 前缀——一致性意义？",
    options: [
      sc("A", "命名空间隔离——同项目可能有 Header（全站）和 NemesisChatHeader（聊天页内）；前缀防止文件名 / import 冲突；表达组件归属"),
      sc("B", "随机"),
      sc("C", "TypeScript 限制"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "前缀 = 组件命名空间；区分全站与模块内同名组件。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 子组件未带 .client 后缀",
    prompt: "NemesisChatHeader / NemesisChatComposer 等子组件文件不带 .client——为什么？",
    options: [
      sc("A", "子组件本身没浏览器 API（只是 UI），通过 props 接 hook 数据；只有「文件本身依赖浏览器 API」才需 .client；父 NemesisChatPage.client 已禁 SSR 让整个子树客户端化；子组件不必重复"),
      sc("B", "应该都加"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".client 按文件内容定；纯展示子组件不必加；父级已禁 SSR 子树自然客户端化。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/nemesis/chat/NemesisChatComposer.tsx"],
  }),
  q({
    type: "single_choice", title: "Q11 onSubmitFeedback 包裹 void",
    prompt: "onSubmitFeedback={(message) => void chat.submitFeedback(message)}——为什么用 void？",
    options: [
      sc("A", "submitFeedback 返 Promise；on* 回调签名期望返 void（不期望 Promise）；用 void 显式丢弃返回值满足 TypeScript；vs 不写 void 让 Promise 当返值传出（lint 可能警告）"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript 强制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "void 显式丢弃 Promise 返回值——回调签名匹配。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 onTogglePrivacyPopover 函数式 setter",
    prompt: "onTogglePrivacyPopover={() => chat.setIsPrivacyPopoverOpen((value) => !value)}——为什么传函数 setter？",
    options: [
      sc("A", "函数式 setter setState(prev => !prev) 不依赖外部闭包的当前值——避免快速点击时拿到 stale state；是 React 推荐的「基于上一状态」更新模式"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "函数式 setter = 基于上一状态——抗 stale closure 的标准模式。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 className 布局",
    prompt: "<div className=\"flex h-screen flex-col overflow-hidden bg-primary-50 text-primary-950 md:flex-row\">——布局策略？",
    options: [
      sc("A", "h-screen 全屏 + flex-col 移动端纵叠（Sidebar 在上 main 在下）+ md:flex-row 桌面横排（Sidebar 左 main 右）+ overflow-hidden 阻止整页滚（让内部 MessageList 自管滚）；响应式 + 滚动域控制"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "h-screen + flex 切换 + overflow-hidden = 全屏聊天的布局组合拳。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 main 内 min-h-0 flex-1",
    prompt: "<main className=\"flex min-h-0 flex-1 flex-col bg-primary-50\">——min-h-0 含义？",
    options: [
      sc("A", "flex 容器内子项默认 min-height: auto 阻止 overflow scroll 生效；min-h-0 强制 0 让子项 MessageList 可以滚动；是 flex layout 内常见的滚动域 trick"),
      sc("B", "无意义"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "flex 内 min-h-0 = 让子项可滚——CSS flex 经典坑。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q15 用户访问 /chat 完整渲染流",
    prompt: "用户访问 /chat 完整渲染步骤？",
    options: [
      sc("s1", "1. Worker SSR 阶段：chat.tsx loader 跑完（鉴权 + headers）"),
      sc("s2", "2. 渲染 chat.tsx default 函数 → <NemesisChatPage /> 但 SSR bundle 内 import 被替换 placeholder"),
      sc("s3", "3. Outlet 内 NemesisChatPage 位置 SSR 输出 null/empty"),
      sc("s4", "4. HTML 返浏览器：含 root shell（Header+Outlet 占位）但 Outlet 内是空"),
      sc("s5", "5. 浏览器加载 client bundle（含 NemesisChatPage.client.tsx）"),
      sc("s6", "6. React hydrate：Outlet 处真正构造 NemesisChatPage 组件"),
      sc("s7", "7. NemesisChatPage 调 useNemesisChat() → 14 useState 初始化 + ref 创建"),
      sc("s8", "8. 渲染 4 子组件 + props 透传 hook 状态"),
      sc("s9", "9. useEffect 跑：读 localStorage sessions + 设 hasLoadedSessions=true + focus textarea + scrollToBottom"),
      sc("s10", "10. 用户看到完整聊天 UI 带历史会话"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8", "s9", "s10"] },
    explanation: { short: ".client 文件 SSR 占位 + 客户端 hydrate 真挂载——10 步流程。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/chat.tsx", "app/hooks/useNemesisChat.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q16 首次渲染白屏",
    prompt: "用户访问 /chat 在 client bundle 加载完前看到什么？",
    options: [
      sc("A", "root.tsx 的 shell（Header 等）+ Outlet 内空白（NemesisChatPage 还没挂）；用户感知页面已部分加载但聊天区空白；持续到 JS 加载完 hydrate 才显示真聊天"),
      sc("B", "完整 UI"),
      sc("C", "白屏"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "shell + 空白聊天区——typical Remix 渐进 hydrate 体验。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 加 SSR fallback",
    prompt: "如何让 SSR 时也显示一个聊天 skeleton（不是空白）？",
    options: [
      sc("A", "chat.tsx 在 <NemesisChatPage /> 位置写 SSR fallback：<ChatSkeleton fallback />；hydrate 后 NemesisChatPage 替换；改 chat.tsx 而非 NemesisChatPage"),
      sc("B", "改 hook"),
      sc("C", "改 root"),
      sc("D", "无法"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SSR fallback 在路由文件层加；客户端组件本身无 SSR 渲染权。" },
    abilityTags: ["project.modify.fullstack", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/chat.tsx"],
  }),
  q({
    type: "single_choice", title: "Q18 .client 子组件迁出",
    prompt: "若想把 NemesisChatComposer 也改 .client 后缀——影响？",
    options: [
      sc("A", "无意义改动——子组件已被父 .client 树包；多加 .client 不让它「更客户端」；可能让构建系统多一处特殊处理；保持子组件普通后缀简洁"),
      sc("B", "性能更好"),
      sc("C", "永远要"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".client 不必传染——父级已禁 SSR 子树自然客户端化。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 把 .client 改成 ClientOnly",
    prompt: "如果把 NemesisChatPage.client 改回 NemesisChatPage（无后缀） + 在 chat.tsx 内 <ClientOnly>{() => <NemesisChatPage />}</ClientOnly>——可行吗？",
    options: [
      sc("A", "可行——效果接近但 SSR bundle 会多打 NemesisChatPage 代码（虽然 SSR 不渲染但 chunk 多）；.client 后缀 = bundle 优化 + ClientOnly 是延迟渲染；前者更彻底"),
      sc("B", "完全等价"),
      sc("C", "永远不可"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ClientOnly 不优化 SSR bundle；.client 才物理隔离 bundle。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/chat.tsx"],
  }),
  q({
    type: "single_choice", title: "Q20 SSR 调试 .client",
    prompt: "若想确认 .client 文件没进 SSR bundle——验证方法？",
    options: [
      sc("A", "wrangler dev 启动 + 看 build 产物（build/server/* 不应含 NemesisChatPage 代码）；或运行时打 console.log 在该文件顶部，wrangler dev 控制台不应见日志（只在浏览器 devtools 见）；多手段验证"),
      sc("B", "无法验"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "验证 .client 隔离 = build 产物查 + 运行时日志位置查——多手段。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 .client 与 lazy 组合",
    prompt: "_index.tsx 内 const BubbleMessageBoard = lazy(() => import('~/components/messages/BubbleMessageBoard.client'));——.client + lazy 双重？",
    options: [
      sc("A", "正确——.client 让该文件不进 SSR bundle；lazy 让它进 client bundle 时也按需加载（独立 chunk）；首屏 client bundle 不含此 chunk；二者协奏极致优化"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".client + lazy = SSR 不打 + client 按需加载——双重优化。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/routes/_index.tsx"],
  }),
  q({
    type: "single_choice", title: "Q22 .client 后缀整体哲学",
    prompt: "NemesisChatPage.client.tsx 与 .client 后缀机制整体哲学？",
    options: [
      sc("A", "1) 文件级强制只入客户端 bundle —— SSR 物理隔离 2) 与 .server 对称分割 runtime 3) 适合「文件本身就是浏览器特性」如 hook 调用 + DOM 操作 + 第三方非 SSR 库 4) 子组件不必传染 .client 5) .client + lazy + ClientOnly 三层组合极致优化首屏 6) SSR 期间该位置渲 placeholder hydrate 后挂真组件 7) 父级 .client 树禁 SSR 让所有子组件天然客户端化——综合：「物理 runtime 隔离 + 渐进 hydrate 体验」"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".client 后缀 7 原则——Remix runtime 物理隔离的核心机制。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/chat.tsx", "app/hooks/useNemesisChat.client.ts"],
  }),
];
