/**
 * Real questions for site-12-client-boundary / hydration-mismatch.
 * Anchor: remix/app/components/common/ClientOnly.tsx + hydration 概念配合 SSR 与客户端首渲一致性
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/common/ClientOnly.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const hydrationMismatchQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 React 警告关键词",
    prompt: "SSR 与客户端首渲不一致时 React 控制台警告会含「____ mismatch」。",
    options: [],
    blanks: [{ id: "v", placeholder: "英文词", acceptedAnswers: ["Hydration", "hydration"] }],
    correctAnswer: { type: "fill_blank", values: { v: "Hydration" } },
    explanation: { short: "Hydration mismatch—React 比对 SSR HTML 与客户端首渲 vDOM 不一致时报警。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 hydration 是什么",
    prompt: "React hydration 阶段做什么？",
    options: [
      sc("A", "客户端拿到 SSR 返回的 HTML + 加载 React 后，把 vDOM 与现有 DOM 「绑定」——附事件监听、绑定 state、不重建 DOM；vs render 是从零创建 DOM；hydrate 复用已存在的 HTML"),
      sc("B", "重新渲染"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "hydrate = 把 vDOM 绑到现有 DOM 而非重建——SSR 必备。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 mismatch 触发条件",
    prompt: "什么情况触发 hydration mismatch？",
    options: [
      sc("A", "SSR 渲的 HTML 与客户端首次 render 输出的 vDOM 节点结构/属性/文本不一致——React 无法对齐节点；常见原因：if (typeof window !== 'undefined') 分支、Date.now() / Math.random() / 时区、客户端独有 state 初值不同"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "mismatch = SSR 与首渲 vDOM 不同——常见原因是「服务端/客户端值不一致」。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 mismatch 的代价",
    prompt: "hydration mismatch 的运行时影响？",
    options: [
      sc("A", "React 18 之前会丢弃整棵子树重新 render（性能差 + 视觉闪烁）；React 18+ 部分场景能局部恢复但仍报警告；任何 mismatch 都是 bug 应修；零 mismatch 是目标"),
      sc("B", "无影响"),
      sc("C", "永远崩"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "mismatch = 性能损失 + 视觉闪烁 + 隐藏 bug——必修。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 ClientOnly 用 useState false 防 mismatch",
    prompt: "ClientOnly 用 useState(false) + useEffect 设 true ——为什么这样可以防 mismatch？",
    options: [
      sc("A", "SSR 渲染时 useState 初值 false → 输出 fallback；客户端首次 render（hydrate 阶段）useState 初值仍 false → 输出 fallback；两侧首渲一致 = 无 mismatch；hydrate 后 effect 跑切 true 触发重渲——这是「正常状态变化」非 mismatch"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useState 默认值在 SSR 与首渲都用 = 一致；effect 切换是后续 update 不算 mismatch。" },
    abilityTags: ["frontend.state.local", "frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 反例：直接 typeof window 检查",
    prompt: "若组件内写 const isClient = typeof window !== 'undefined'; 然后 if (isClient) return <ClientUI />;——为什么会 mismatch？",
    options: [
      sc("A", "SSR：typeof window === 'undefined' → return null；客户端首渲：typeof window !== 'undefined' → return <ClientUI />；两侧 vDOM 不同 → mismatch；这是常见反模式"),
      sc("B", "无问题"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "typeof window 在 SSR 与客户端不同 → 首渲不一致 = mismatch。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 反例：Date.now()",
    prompt: "<div>{Date.now()}</div> 直接 SSR——会 mismatch 吗？",
    options: [
      sc("A", "会——SSR 渲染时 Date.now() 返一个值（写入 HTML）；客户端首渲时 Date.now() 返另一个值（毫秒级差）；文本节点内容不同 = mismatch；时间敏感数据要 ClientOnly 包"),
      sc("B", "无问题"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "时间值 SSR ≠ 客户端 → 文本不同 → mismatch；时间渲染要延迟到客户端。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 反例：localStorage 初值",
    prompt: "useState(() => localStorage.getItem('foo') ?? 'default') ——SSR 影响？",
    options: [
      sc("A", "SSR 阶段 localStorage 不存在 → ReferenceError 让 SSR 失败；要包 typeof window 但又破坏 hydration；正确做法：useState('default') + useEffect 内读 localStorage 后 setState"),
      sc("B", "无问题"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "localStorage 初值不能直接用——要 effect 异步读再 setState。" },
    abilityTags: ["frontend.state.local", "frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 时区差异",
    prompt: "Worker SSR 默认 UTC 时区，浏览器是用户本地时区——格式化日期会 mismatch 吗？",
    options: [
      sc("A", "会——服务端 toLocaleString() 用 UTC 格式化；客户端用本地时区；同一时间字符串显示不同；要 ClientOnly 或客户端 effect 内重新格式化"),
      sc("B", "无问题"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "时区差 SSR ≠ 客户端 → 格式化不同 → mismatch；日期渲染要小心。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 user-agent 分支",
    prompt: "if (navigator.userAgent.includes('Mobile')) return <MobileUI />;——SSR 安全？",
    options: [
      sc("A", "不安全——SSR 时 navigator 不存在；要么从服务端 request.headers.get('user-agent') 读传给组件；要么 ClientOnly 包；不能用 navigator API 直接判 SSR"),
      sc("B", "可以"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "navigator API SSR 不可用——服务端从 headers 读 user-agent 传 props。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 mismatch 调试",
    prompt: "出现 hydration mismatch 警告——怎么调试？",
    options: [
      sc("A", "1) React DevTools 查看告警节点 2) 对比 view-source（SSR HTML）与 React 树（客户端首渲）找差异 3) 排查典型原因（typeof window / Date / Math.random / localStorage / navigator / 时区 / 浏览器扩展插入元素）；多管齐下"),
      sc("B", "无法调"),
      sc("C", "重启"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "mismatch 调试 = 对比 HTML 与 vDOM + 排查典型原因——系统方法。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 浏览器扩展插入",
    prompt: "用户装了浏览器扩展（如某些密码管理器）注入了额外 DOM 元素——可能 mismatch 吗？",
    options: [
      sc("A", "会——React 比对发现 SSR HTML 与现有 DOM 多了节点；这种 mismatch 是用户扩展导致非代码 bug；React 18+ 通常能恢复；属于不可控环境噪音"),
      sc("B", "代码 bug"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "浏览器扩展可能注入 DOM 引发 mismatch——线上不可避免的噪音。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 suppressHydrationWarning",
    prompt: "<div suppressHydrationWarning>{Date.now()}</div>——这个属性？",
    options: [
      sc("A", "React 提供的属性——告诉 React 「这一节点的 mismatch 是预期的，不要警告」；用于明知会 mismatch 的特定节点（如时间）；不解决问题但抑制警告；慎用避免掩盖真 bug"),
      sc("B", "禁止 SSR"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "suppressHydrationWarning = 预期 mismatch 的标记；慎用。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 useId hook",
    prompt: "<input id={Math.random()} /> SSR 会 mismatch；React 18 提供什么解决？",
    options: [
      sc("A", "useId() —— 返回稳定唯一 id 字符串，SSR 与客户端首渲一致；专为「需要唯一 id 但不能用 random」设计；如表单 label htmlFor、aria-* 关联"),
      sc("B", "useState"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useId = SSR 安全的稳定唯一 id 生成器。" },
    abilityTags: ["ai.review.architecture", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 useEffect 内 setState",
    prompt: "useEffect(() => { setX(window.innerWidth) }, [])——为什么不会 mismatch？",
    options: [
      sc("A", "useEffect 在 hydrate 完成后才跑——此时 setState 触发的重渲是「正常 update」非「首渲」；首渲已对齐 SSR；只有「首渲」时不一致才叫 mismatch"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useEffect 在 hydrate 后跑——setState 是后续 update，不影响 hydration。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 useLayoutEffect SSR",
    prompt: "useLayoutEffect 在 SSR 时会 React 警告——为什么？",
    options: [
      sc("A", "useLayoutEffect 设计是同步在 DOM 挂载后跑（用于读取布局尺寸/避免闪烁）；SSR 没 DOM 也没 useLayoutEffect 调用机会 → React 警告说「这不会跑」；建议用 useEffect 或 typeof window 包"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useLayoutEffect SSR 不可用 → React 警告；用 useEffect 或 isomorphicLayoutEffect 工具。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q17 ClientOnly 防 mismatch 完整流",
    prompt: "ClientOnly 包裹一个含 localStorage.getItem 的子组件，完整渲染流？",
    options: [
      sc("s1", "1. SSR：ClientOnly useState(false) → 走 fallback 分支返 null"),
      sc("s2", "2. SSR HTML 该位置输出空"),
      sc("s3", "3. 浏览器收 HTML 显示空"),
      sc("s4", "4. JS 加载 → React hydrate"),
      sc("s5", "5. ClientOnly 首渲：useState 仍 false → fallback null → 与 SSR HTML 一致 → hydrate 成功无 mismatch"),
      sc("s6", "6. hydrate 完成后 useEffect 跑 → setHasMounted(true)"),
      sc("s7", "7. ClientOnly 重渲 → return children() → 调用子组件"),
      sc("s8", "8. 子组件首次构造，内部 localStorage.getItem 安全（已在浏览器）"),
      sc("s9", "9. 真子组件挂载 + localStorage 数据可用 + 无 mismatch 警告"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8", "s9"] },
    explanation: { short: "ClientOnly 防 mismatch 9 步——首渲一致 + effect 切真组件。" },
    abilityTags: ["frontend.state.local", "frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 main 项目里的 mismatch 风险",
    prompt: "本 remix 项目内最容易引发 mismatch 的代码是？",
    options: [
      sc("A", "useNemesisChat hook 内 localStorage 读 + Date.now() —— 但已通过 .client 后缀完全隔离 SSR；本项目实测无 mismatch；机制保护到位"),
      sc("B", "Header"),
      sc("C", "root"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "本项目浏览器 API 都在 .client 文件 → SSR 不触及 → 无 mismatch。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/hooks/useNemesisChat.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q19 React 18 vs 19 hydration",
    prompt: "React 19 对 hydration mismatch 的改进？",
    options: [
      sc("A", "React 19 提供更细粒度 mismatch 报告 + 部分场景可自动恢复（如时间戳类已知 mismatch）+ 改进的 streaming SSR；但根本原则不变：避免 mismatch 仍是首选"),
      sc("B", "无变化"),
      sc("C", "完全消除"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "React 19 改善 mismatch 体验；但避免 mismatch 仍是工程纪律。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 mismatch 监控",
    prompt: "想监控线上 mismatch 频率——落点？",
    options: [
      sc("A", "全局 onerror / window.onunhandledrejection 抓 React mismatch 警告（warn 级别需 console.warn 拦截）；上报 Sentry/analytics；mismatch 告警低优先级但有持续监控"),
      sc("B", "无法"),
      sc("C", "随机"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "mismatch 监控 = 拦 console.warn + 上报；线上质量监控。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 防 mismatch 工具箱",
    prompt: "防 hydration mismatch 的工具箱（按场景）？",
    options: [
      sc("A", "1) ClientOnly 包浏览器特性组件 2) useState 初值可序列化 + useEffect 异步初始化 3) useId 替代 random 4) suppressHydrationWarning 标预期 mismatch（慎用）5) .client 后缀文件级隔离 6) 日期/时区从 server props 传入；按场景选"),
      sc("B", "只 ClientOnly"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "六大工具按场景选——hydration 健康的工程纪律。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 hydration 整体哲学",
    prompt: "hydration 与防 mismatch 整体哲学？",
    options: [
      sc("A", "1) hydrate = 把 vDOM 绑到 SSR HTML；首渲必须与 SSR 一致 2) 任何「服务端/客户端值不一致」都是 mismatch 风险（typeof window/Date/Math.random/localStorage/navigator/时区）3) 工具箱：ClientOnly 包 + useState 默认值 + useEffect 异步初始化 + useId + .client 后缀 + suppressHydrationWarning 慎用 4) React 18+ 部分恢复但避免 mismatch 仍是目标 5) 浏览器扩展不可控但通常不致命 6) 监控警告抓持续问题——综合：「SSR 与客户端首渲一致是铁律 + 工具箱按场景选」"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "hydration 6 原则——SSR 项目核心质量纪律。" },
    abilityTags: ["frontend.effect.useEffect", "frontend.state.local", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/components/nemesis/chat/NemesisChatPage.client.tsx", "app/hooks/useNemesisChat.client.ts"],
  }),
];
