/**
 * Real questions for site-04-theme-system / theme-capstone.
 * Anchor: 综合 remix/app/utils/theme.server.ts + remix/app/root.tsx + remix/app/components/ui/Header.tsx
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/utils/theme.server.ts";
const ROOT = "app/root.tsx";
const HEADER = "app/components/ui/Header.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const themeCapstoneQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 主题机制涉及文件数",
    prompt: "完整主题链涉及核心文件 ____ 个：theme.server.ts + root.tsx + (可选) Header.tsx。",
    options: [],
    blanks: [{ id: "v", placeholder: "数字", acceptedAnswers: ["3", "三"] }],
    correctAnswer: { type: "fill_blank", values: { v: "3" } },
    explanation: { short: "三个文件——cookie 工具 + shell + UI；机制极小化。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, ROOT, HEADER],
  }),
  q({
    type: "single_choice", title: "Q2 主题机制最重要的设计原则",
    prompt: "三文件分工怎么定？",
    options: [
      sc("A", "theme.server：cookie I/O 工具；root.tsx：loader 读 + action 写 + Layout 渲染 className + 防 FOUC 脚本；Header（可选）：UI 触发 → 后端复用 root action；分层让每文件做单一事"),
      sc("B", "全在 root"),
      sc("C", "全在 Header"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三层分工：工具 + shell + UI——单一职责。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: ROOT, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, ROOT, HEADER],
  }),
  q({
    type: "single_choice", title: "Q3 SSR 首屏不闪烁的核心",
    prompt: "用户带 cookie theme=dark 访问，首屏直接 dark 不闪——靠什么？",
    options: [
      sc("A", "1) 服务端 root loader getTheme(request) 同步读 cookie 2) Layout 渲染时 <html className=\"dark\"> 已对 3) 浏览器收 HTML 时 dark 已经在 DOM 上——根本没机会显 light——服务端读 cookie 是核心"),
      sc("B", "客户端 useEffect"),
      sc("C", "重定向"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SSR + 服务端读 cookie = 首屏正确——客户端方案永远会闪。" },
    abilityTags: ["bridge.reactRouter.loader", "backend.session.cookie", "ai.review.architecture"],
    sourceFilePath: ROOT, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [ROOT, PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 防 FOUC 内联脚本的作用",
    prompt: "root.tsx 内联 <script> 用 document.cookie 读 theme + documentElement.classList.add——SSR 已经对了为什么还要这步？",
    options: [
      sc("A", "防边界 case：1) cookie parse 失败时 SSR 默认 light 但客户端读 cookie 是 dark——脚本同步对齐 2) cookie 读取时机问题 3) 客户端 hydrate 前的可能不一致；保险措施"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "防 FOUC 脚本 = 服务端 SSR 之后的补丁——边界场景对齐。" },
    abilityTags: ["ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: ROOT, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [ROOT],
  }),
  q({
    type: "single_choice", title: "Q5 httpOnly:false 的代价",
    prompt: "主题 cookie httpOnly:false 让 JS 可读——这与 auth cookie 的 httpOnly:true 矛盾吗？",
    options: [
      sc("A", "不矛盾——httpOnly 是按 cookie 单独配置的；auth 必须 true（防 XSS 偷 token）；theme 必须 false（前端脚本要读防 FOUC）；按敏感度分级配置"),
      sc("B", "矛盾"),
      sc("C", "应该一致"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "cookie 安全级别按内容敏感度配——非敏感数据可放开，敏感必锁。" },
    abilityTags: ["backend.session.cookie", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 主题机制完全无 D1/KV",
    prompt: "整个主题机制不用 D1 也不用 KV——为什么？",
    options: [
      sc("A", "cookie 已是用户级持久存储——浏览器跨会话保留；D1 / KV 是「服务端共享存储」，主题是用户私有偏好不需要服务端 store；用对工具：用户偏好用 cookie，共享数据用 D1"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "用户偏好 = cookie；共享数据 = D1/KV——选对存储层。" },
    abilityTags: ["backend.session.cookie", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 Tailwind dark: 变体",
    prompt: "Header 不写 if (theme==='dark') 切色——靠什么？",
    options: [
      sc("A", "html.dark 父元素 + Tailwind 配 darkMode:'class' + 样式写 'dark:bg-...' —— CSS 级联自动应用；零 JS 改色；性能 + 简洁双赢"),
      sc("B", "JS 切"),
      sc("C", "URL"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "html.dark 父类 + Tailwind dark: = 纯 CSS 主题切换。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: HEADER, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [HEADER, "tailwind.config.ts"],
  }),
  q({
    type: "single_choice", title: "Q8 root action 校验",
    prompt: "root.tsx action 内 if (theme !== 'light' && theme !== 'dark') return json({ error: 'Invalid theme' }, { status: 400 });——白名单意图？",
    options: [
      sc("A", "前端 form 提交可被任意 hack（攻击者直接 POST 任意值）；服务端必须白名单；脏值进 cookie 后 className 会变成奇怪字符串污染样式"),
      sc("B", "可省"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "服务端永远不信前端——白名单是基础防御。" },
    abilityTags: ["backend.validation.field", "bridge.reactRouter.action"],
    sourceFilePath: ROOT, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [ROOT],
  }),
  q({
    type: "branch_trace", title: "Q9 完整跨场景流程",
    prompt: "用户 A 在桌面浏览器切 dark → 关闭 → 在手机访问。手机会跟着 dark 吗？",
    options: [
      sc("s1", "1. 桌面浏览器切 dark → cookie 写在桌面浏览器内"),
      sc("s2", "2. 桌面关闭 cookie 持久化（maxAge 1y）"),
      sc("s3", "3. 用户掏出手机访问——手机浏览器无此 cookie（cookie 按浏览器 + 域名隔离）"),
      sc("s4", "4. 手机首次 GET / —— root loader getTheme 找不到 → fallback light"),
      sc("s5", "5. SSR 渲染 className='light'"),
      sc("s6", "6. 用户在手机看到的是 light 主题"),
      sc("s7", "7. 若用户在手机也切 dark → 手机 cookie 独立存 dark"),
      sc("s8", "8. 桌面 + 手机各自记住自己的偏好；不跨设备同步——cookie 本质设备私有"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8"] },
    explanation: { short: "cookie 设备私有——多设备主题不同步；跨设备同步需登录 + D1。" },
    abilityTags: ["backend.session.cookie", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 跨设备主题同步",
    prompt: "若想跨设备同步主题——改造方向？",
    options: [
      sc("A", "1) 登录用户主题存 D1 用户表 2) root loader：if (user) 从 D1 读用户主题，否则从 cookie 读 3) action 写 D1 + 写 cookie 双轨；登录后跨设备同步，未登录退回 cookie 偏好；分层"),
      sc("B", "改 wrangler"),
      sc("C", "无法"),
      sc("D", "改 KV"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "跨设备同步 = D1 用户偏好；未登录 fallback cookie——分层数据源。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture", "backend.auth.required"],
    sourceFilePath: ROOT, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [ROOT, PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 Header 不依赖 theme",
    prompt: "Header.tsx 不读 theme 不监听 theme——它怎么响应主题切换？",
    options: [
      sc("A", "Tailwind dark: 变体让 Header 内类名自动跟随 html.dark；主题切换时 root 重渲改 className，Header 内的 dark:bg-... 等类自动生效；零 JS 适配"),
      sc("B", "重渲全树"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Header 不依赖 theme = CSS 级联 + Tailwind dark: 变体的零 JS 适配。" },
    abilityTags: ["ai.review.architecture", "frontend.state.scope"],
    sourceFilePath: HEADER, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [HEADER],
  }),
  q({
    type: "single_choice", title: "Q12 加新主题色变量",
    prompt: "想加 'sepia' 主题（米黄柔色）。改动？",
    options: [
      sc("A", "1) Theme 联合加 'sepia' 2) tailwind.config 加 sepia 色板 + sepia: 变体 3) Layout className 支持 sepia；getTheme 收窄三选一；root action 校验白名单加；UI 切换支持三态"),
      sc("B", "改 wrangler"),
      sc("C", "改 D1"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "加新主题 = 类型 + Tailwind 变体 + 校验白名单 + Layout 渲染——TypeScript 推动各处更新。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, ROOT, "tailwind.config.ts"],
  }),
  q({
    type: "single_choice", title: "Q13 fetcher action 与 root action",
    prompt: "为什么 root action 内同时处理 theme 切换和（潜在的）其他 root-level 写？",
    options: [
      sc("A", "root action 是「全 app 默认 action」——多种全局写都汇总到这里；按 form data 内 _action 字段或 theme 字段分发；vs 每个写都建独立 API 路由（爆炸）"),
      sc("B", "应分开"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "root action = 多写聚合 dispatcher；常见 Remix 模式。" },
    abilityTags: ["bridge.reactRouter.action", "ai.review.architecture"],
    sourceFilePath: ROOT, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [ROOT],
  }),
  q({
    type: "single_choice", title: "Q14 主题机制的可观测性",
    prompt: "想监控主题分布（多少 light vs dark）——埋点位置？",
    options: [
      sc("A", "root.tsx action 内 setTheme 之后埋日志或上报——单点拦截所有显式切换；前端埋点会漏掉「服务端默认 light 的访客」；action 是真源"),
      sc("B", "Header"),
      sc("C", "客户端"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "可观测性放在「最关键的写入路径」上——root action 是单点。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.action"],
    sourceFilePath: ROOT, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [ROOT],
  }),
  q({
    type: "single_choice", title: "Q15 主题机制可测",
    prompt: "怎么测试主题机制？",
    options: [
      sc("A", "1) theme.server: 单测 getTheme/setTheme 各种 cookie 输入 2) root loader: integration 测带不带 cookie 返回 theme 正确 3) root action: integration 测合法/非法 theme + 校验 Set-Cookie 头；分层测各自"),
      sc("B", "无法测"),
      sc("C", "只 e2e"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "分层测试 = 单测工具 + integration 测 loader/action；按职责分。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, ROOT],
  }),
  q({
    type: "single_choice", title: "Q16 与 prefers-color-scheme 媒体查询冲突",
    prompt: "若用户系统 dark，但 cookie 是 light——首屏什么样？",
    options: [
      sc("A", "光看 cookie 决定——className='light' 显示亮色；纯 CSS 媒体查询 prefers-color-scheme 不参与；cookie 优先体现「用户在本网站的明确选择」高于系统偏好"),
      sc("B", "随系统"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "用户网站偏好（cookie）高于系统偏好——除非用户选 'auto'。" },
    abilityTags: ["ai.review.architecture", "backend.session.cookie"],
    sourceFilePath: ROOT, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [ROOT],
  }),
  q({
    type: "single_choice", title: "Q17 分层好处之演进面",
    prompt: "若改 cookie 库（@remix-run/cloudflare → 自定义实现），影响多大？",
    options: [
      sc("A", "只改 theme.server.ts 内部实现；导出 API getTheme/setTheme 形状不变 → root.tsx 不动 → Header 不动；分层让演进面收紧"),
      sc("B", "改全栈"),
      sc("C", "无法改"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "薄实用层 = 演进面被锁在内部；上层不变。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 错误恢复",
    prompt: "若 cookie 损坏（被人手动改成无效字符）——下次访问会怎样？",
    options: [
      sc("A", "getTheme 内三元收窄 theme === 'dark' ? 'dark' : 'light' → fallback 'light'；不挂错；自愈式设计；下次切换覆盖坏值"),
      sc("B", "崩溃"),
      sc("C", "白屏"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "白名单收窄 = 自愈防御——脏值 fallback 默认。" },
    abilityTags: ["backend.validation.field", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 主题机制 vs 全局 store",
    prompt: "若用 Zustand 管理 theme（前端全局 store）——还能 SSR 不闪吗？",
    options: [
      sc("A", "不能——store 在客户端 hydrate 后才有值，SSR 阶段 store 默认值（light）；用户带 dark cookie 访问会先看 light 再切 dark = FOUC；SSR 主题必须从服务端读"),
      sc("B", "可以"),
      sc("C", "性能更好"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "客户端 store 永远 SSR 不到——主题用服务端 cookie 是 SSR 兼容的关键。" },
    abilityTags: ["frontend.state.global", "ai.review.architecture"],
    sourceFilePath: ROOT, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [ROOT],
  }),
  q({
    type: "single_choice", title: "Q20 与 React 19 RSC",
    prompt: "迁到 React Server Components——主题机制要改吗？",
    options: [
      sc("A", "几乎不改——getTheme 在 RSC 内仍可用；Layout 仍是 server component；只 Header 切换 UI 必须 \"use client\"；机制底层与 RSC 兼容"),
      sc("B", "全重写"),
      sc("C", "无法迁"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "服务端机制 RSC 兼容；只交互 UI 标 client。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: ROOT, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [ROOT, HEADER],
  }),
  q({
    type: "single_choice", title: "Q21 主题机制何时该用",
    prompt: "什么场景下「不要做主题机制」更合理？",
    options: [
      sc("A", "1) 单一品牌色调强烈的产品（如纯白设计奢侈品）2) 短期项目 / MVP 不必扩主题 3) 全部用户都是同一光线环境（如展厅大屏）；用与不用都是 UX 决策"),
      sc("B", "永远要"),
      sc("C", "永远不要"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "主题机制是 UX 选择——按场景定值不值。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: ROOT, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [ROOT],
  }),
  q({
    type: "single_choice", title: "Q22 主题机制整体哲学（毕业级）",
    prompt: "site-04 主题系统三文件协奏的整体哲学？",
    options: [
      sc("A", "1) cookie 持久化用户私有偏好——不用 D1/KV 2) 服务端 SSR 读 cookie + 渲染 className 防 FOUC 3) 内联同步脚本兜底边界 case 4) httpOnly:false 让脚本能读（非敏感数据松绑）5) 白名单收窄脏值自愈 6) Tailwind dark: 变体让 CSS 自管色 Header 零依赖 7) 切换 UI（如加）走 root action 复用后端 8) 三文件分层让演进面隔离——综合：「服务端权威 + CSS 级联 + 工具薄 + UI 复用」"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "主题机制 8 原则——SSR 友好的全栈主题系统范式。" },
    abilityTags: ["ai.review.architecture", "backend.session.cookie", "bridge.reactRouter.loader", "bridge.reactRouter.action"],
    sourceFilePath: ROOT, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, ROOT, HEADER, "tailwind.config.ts"],
  }),
];
