/**
 * Real questions for site-04-theme-system / theme-server.
 * Anchor: remix/app/utils/theme.server.ts —— createCookie + getTheme + setTheme + getThemeCookie helpers
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/utils/theme.server.ts";
const sc = (id: string, text: string) => ({ id, text });

export const themeServerQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 文件后缀",
    prompt: "theme.____.ts —— 后缀让 Remix 知道只在服务端打包。",
    options: [],
    blanks: [{ id: "v", placeholder: "后缀", acceptedAnswers: ["server"] }],
    correctAnswer: { type: "fill_blank", values: { v: "server" } },
    explanation: { short: ".server 后缀强制只在 Worker 打包——cookie API 与 secret 不进客户端 bundle。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank", title: "Q2 Theme 类型联合",
    prompt: 'export type Theme = "light" | "____";',
    options: [],
    blanks: [{ id: "v", placeholder: "枚举值", acceptedAnswers: ["dark"] }],
    correctAnswer: { type: "fill_blank", values: { v: "dark" } },
    explanation: { short: "封闭联合 Theme = 'light' | 'dark' —— 编译期穷举。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 createCookie 来源",
    prompt: "import { createCookie } from \"@remix-run/cloudflare\";——为什么从 cloudflare 子包不是 react 包？",
    options: [
      sc("A", "@remix-run/cloudflare 包提供 Worker 兼容的 cookie 实现（不依赖 Node.js Buffer 等）；与 @remix-run/node 平行；选对包是 runtime 适配的关键"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "@remix-run/cloudflare = Worker 运行时专用包；与 node 包互斥。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 getThemeCookie 函数",
    prompt: "function getThemeCookie(request?: Request) { const secure = request ? new URL(request.url).protocol === 'https:' : false; return createCookie(...); }——为什么是函数不是常量？",
    options: [
      sc("A", "secure 标志要根据当前请求的协议动态设——HTTPS 才打 secure；常量化会让本地 http 测试时 cookie 永远不写或永远 secure 报错；函数化让运行时决定"),
      sc("B", "性能"),
      sc("C", "TypeScript 限制"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "secure 跟随 request 协议 → cookie 工厂函数；常量解决不了。" },
    abilityTags: ["backend.session.cookie", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 maxAge 31_536_000",
    prompt: "maxAge: 31_536_000 ——这个数字含义？",
    options: [
      sc("A", "365 × 24 × 60 × 60 = 一年（秒）；下划线是 JS 数字字面量分隔符；理论意义：用户主题偏好长期保留"),
      sc("B", "一周"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "31536000 秒 = 1 年；偏好类设定长寿命合理。" },
    abilityTags: ["backend.session.cookie"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 httpOnly: false",
    prompt: "httpOnly: false ——为什么主题 cookie 不设 httpOnly？",
    options: [
      sc("A", "防 FOUC 的内联脚本要用 document.cookie 在 React 加载前同步读 theme；httpOnly:true 会让 JS 读不到；权衡：主题非敏感数据，可以放开"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "httpOnly:false = 客户端 JS 可读；主题非敏感才能这么做（auth cookie 必须 httpOnly:true）。" },
    abilityTags: ["backend.session.cookie", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q7 secure auto-detect",
    prompt: "const secure = request ? new URL(request.url).protocol === 'https:' : false;——为什么动态判断？",
    options: [
      sc("A", "本地开发 http://localhost 必须 secure:false（否则浏览器拒绝写）；线上 https 必须 secure:true（防止 HTTP 中间人嗅探）；自动适配两环境"),
      sc("B", "永远 true"),
      sc("C", "永远 false"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "secure 跟环境走——本地 + 线上都正确。" },
    abilityTags: ["backend.session.cookie", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 sameSite: 'lax'",
    prompt: "sameSite: 'lax' ——含义？",
    options: [
      sc("A", "跨站 GET 时携带（如别站链接到本站，cookie 会带）；跨站 POST/iframe 不带；折中模式：兼顾基础导航与 CSRF 防御；strict 太严会让从外站点链接进来时丢主题；none 太松"),
      sc("B", "永远带"),
      sc("C", "永远不带"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "sameSite=lax = 跨站 GET 带、其他不带——主题偏好的合适松紧度。" },
    abilityTags: ["backend.session.cookie", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 getTheme 实现",
    prompt: "export async function getTheme(request: Request): Promise<Theme> { const themeCookie = getThemeCookie(request); const cookieHeader = request.headers.get('Cookie'); const theme = await themeCookie.parse(cookieHeader); return theme === 'dark' ? 'dark' : 'light'; }——为什么三元而不是 return theme？",
    options: [
      sc("A", "cookieParser.parse 可能返 null/undefined/任意值（曾被篡改/手动写）；强制收窄到联合两值之一；脏数据 fallback light 默认；防御编程"),
      sc("B", "TypeScript 限制"),
      sc("C", "随机"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "返回前白名单收窄 = 防止脏 cookie 让 className 挂奇怪字符串。" },
    abilityTags: ["backend.session.cookie", "backend.validation.field", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 setTheme",
    prompt: "export async function setTheme(theme: Theme, request?: Request) { const themeCookie = getThemeCookie(request); return themeCookie.serialize(theme); }——返回值？",
    options: [
      sc("A", "返回 cookie 的 serialized 字符串（如 'theme=dark; Max-Age=31536000; SameSite=Lax; Path=/'）；调用方放进 Set-Cookie 响应头；这就是 root.tsx action 用 'Set-Cookie' header 的原料"),
      sc("B", "void"),
      sc("C", "Theme"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "setTheme 返字符串而非自己设头——调用方决定怎么用。" },
    abilityTags: ["backend.session.cookie", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q11 同名 cookie name 'theme'",
    prompt: "createCookie(\"theme\", { ... })——cookie 名 'theme' 写死；这与上一题的「项目前缀」建议矛盾？",
    options: [
      sc("A", "短期项目可接受——主题 cookie 是非敏感、纯前端展示偏好；与 auth cookie 不冲突即可；上一节建议是「多项目同域名」更严的场景；当前项目实测 OK"),
      sc("B", "代码错"),
      sc("C", "永不冲突"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "建议是「同域名多项目并存」时严守；单项目可接受简洁名。" },
    abilityTags: ["backend.session.cookie", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 createCookie API 选择",
    prompt: "为什么用 createCookie 而不是直接 request.headers.set('Cookie', ...)？",
    options: [
      sc("A", "createCookie 处理 sign/encrypt（如有 secrets）+ 序列化属性（Max-Age/SameSite/Path）+ 解析；手动拼接易漏属性 + 易遭 cookie injection；用 API 是工程纪律"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "createCookie = 安全 + 完整 cookie 协议处理；不要手拼。" },
    abilityTags: ["backend.session.cookie", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 themeCookie.parse 输入",
    prompt: "themeCookie.parse(cookieHeader) 接收的 cookieHeader 是什么形状？",
    options: [
      sc("A", "完整 Cookie 头字符串（如 'foo=1; bar=2; theme=dark'）；createCookie API 内部按 name 找出对应值；调用方不需手动 split"),
      sc("B", "对象"),
      sc("C", "已 parsed 对象"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "parse(headerString) → cookie 工厂内部按 name 抽值。" },
    abilityTags: ["backend.session.cookie"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q14 用户首次访问→点切换→刷新流程",
    prompt: "用户首次访问 → 点击主题切换为 dark → 关闭浏览器 → 第二天回来。完整步骤？",
    options: [
      sc("s1", "1. 首次访问无 cookie → root loader 调 getTheme(request) → parse 返 null → 三元收窄 'light'"),
      sc("s2", "2. <html className='light'> SSR 输出"),
      sc("s3", "3. 用户点击主题切换提交 form → root action 触发"),
      sc("s4", "4. action 校验 theme === 'dark' 通过 → 调 setTheme('dark', request)"),
      sc("s5", "5. setTheme 内 themeCookie.serialize('dark') 返字符串 'theme=dark; Max-Age=31536000; ...'"),
      sc("s6", "6. action 返 json 含 'Set-Cookie': 上面字符串"),
      sc("s7", "7. 浏览器存 cookie；revalidate root loader → getTheme 这次 parse 拿到 'dark' → 收窄到 'dark'"),
      sc("s8", "8. 关闭浏览器；cookie 持久化在硬盘"),
      sc("s9", "9. 第二天访问 → cookie 仍在 → root loader getTheme 返 'dark' → SSR 直接 className='dark' 不闪烁"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8", "s9"] },
    explanation: { short: "主题持久化全链 9 步——cookie + serialize + Set-Cookie + revalidate + 持久存储。" },
    abilityTags: ["backend.session.cookie", "bridge.reactRouter.action", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q15 setTheme request 可选",
    prompt: "setTheme(theme: Theme, request?: Request)——request 可选意图？",
    options: [
      sc("A", "调用方 root action 一定有 request 可传；可选签名让其他场景（如脚本/测试）省略；request 缺失时 secure 默认 false 也能 serialize 出可用 cookie；签名灵活"),
      sc("B", "TypeScript 限制"),
      sc("C", "随机"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "可选 request = 兼容多调用场景；缺失时 fallback secure=false。" },
    abilityTags: ["backend.session.cookie", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 Path 默认 '/'",
    prompt: "createCookie 没显式设 path——默认 path？",
    options: [
      sc("A", "默认 '/' —— 全站可读；如果设 path:'/admin' 则只 /admin 路径下能读到，loader 在 /home 读不到主题；省略 = 全站默认"),
      sc("B", "无 path"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "省略 path → 默认 '/' 全站可读——主题 cookie 应当全站统一。" },
    abilityTags: ["backend.session.cookie"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 缺乏 secrets 配置",
    prompt: "createCookie(\"theme\", { ... }) 无 secrets——为什么不签名？",
    options: [
      sc("A", "主题 cookie 内容非敏感（仅 'light'/'dark'）+ getTheme 已白名单收窄；签名只能防篡改，但脏值已被白名单吸收；没必要付加密计算成本"),
      sc("B", "应该签"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "签名是「检测篡改」工具；当篡改无意义时不必签——auth cookie 必须签。" },
    abilityTags: ["backend.session.cookie", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 加第三个主题 'auto'",
    prompt: "想加 'auto' 主题（跟随系统）。改动？",
    options: [
      sc("A", "1) Theme 类型联合加 'auto' 2) getTheme 三元加分支 theme === 'auto' ? 'auto' : ... 3) Layout 渲染 className 也要支持 auto；类型先行驱动各处更新；TypeScript 编译会指出未覆盖处"),
      sc("B", "改 wrangler"),
      sc("C", "改 D1"),
      sc("D", "改 Header"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "封闭联合加成员 = TypeScript 推动各处更新；安全演进。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q19 主题 cookie 与 KV 缓存",
    prompt: "若 getTheme 加 KV 缓存（先查 KV 减少 cookie parse）——值得吗？",
    options: [
      sc("A", "不值——cookie parse 是纯字符串解析，纳秒级；KV 是网络读毫秒级反而慢；KV 适合昂贵 D1 / API 结果；过早优化反而劣化性能"),
      sc("B", "立刻加"),
      sc("C", "性能必好"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "缓存原理：缓存比原操作快才有意义；cookie parse 比 KV 快 → 加缓存劣化。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q20 getTheme 异步必要",
    prompt: "判断：getTheme 必须是 async 函数。",
    correctAnswer: { value: true },
    explanation: { short: "对——themeCookie.parse 返 Promise（cookie 工具底层可能涉及加解密）；await 必须 → 函数必须 async。" },
    abilityTags: ["backend.session.cookie", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 类型导出位置",
    prompt: "Theme 类型与函数同 file 导出——好处？",
    options: [
      sc("A", "类型 + 实现一体——消费者只需 import { getTheme, setTheme, type Theme }；不必去找类型定义；模块内聚"),
      sc("B", "应分文件"),
      sc("C", "TypeScript 限制"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "类型与实现同文件 = 内聚；消费者一次 import 拿全。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 theme.server.ts 整体哲学",
    prompt: "theme.server.ts 27 行整体设计哲学？",
    options: [
      sc("A", "1) .server 后缀强制服务端 2) 封闭联合 Theme 让 TypeScript 把守 3) cookie 工厂函数动态 secure 适配本地/线上 4) httpOnly:false 让 FOUC 内联脚本可读 5) sameSite:lax 防 CSRF + 不阻基础导航 6) maxAge 1 年长寿命主题偏好 7) getTheme 白名单收窄非法值 8) setTheme 返 serialized 字符串让调用方决定 Set-Cookie 时机——综合：薄实用层 + 安全 + 适配多环境"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "27 行 8 原则——非敏感 cookie 工具的范本。" },
    abilityTags: ["backend.session.cookie", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
];
