/**
 * Real questions for site-04-theme-system / theme-toggle-ui.
 * Anchor: remix/app/components/ui/Header.tsx + remix/app/root.tsx
 * 关键事实：项目当前 Header.tsx 不含主题切换 UI——本课考察「如果要加，UI 形态、提交方式、与 root action 的衔接」
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/ui/Header.tsx";
const ROOT = "app/root.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const themeToggleUiQuestions: RealQ[] = [
  q({
    type: "true_false", title: "Q1 Header 是否含切换 UI",
    prompt: "判断：当前 Header.tsx 已经有主题切换按钮在 navigation 旁边。",
    correctAnswer: { value: false },
    explanation: { short: "错——Header 当前不含主题切换；本课讨论「如果要加，怎么加」。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 切换 UI 应该是什么形态",
    prompt: "若加主题切换——常见 UI 形态？",
    options: [
      sc("A", "图标按钮（☀️/🌙）+ aria-label='切换主题'；点击切换；空间紧凑符合 Header 布局；Tailwind 的 dark: 变体让两态视觉对比明显"),
      sc("B", "下拉菜单"),
      sc("C", "全屏 modal"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "图标按钮 = Header 主题切换的标准 UI；下拉/modal 成本过重。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 Form vs fetcher 提交",
    prompt: "切换主题用 Remix <Form> 还是 useFetcher？",
    options: [
      sc("A", "fetcher——切主题不改 URL 不进 history；<Form> 默认会 navigate 进 history 栈，浏览器后退会回到「切换前」状态难以理解；fetcher 适合「副作用 + 不导航」"),
      sc("B", "<Form>"),
      sc("C", "无差"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "无导航语义副作用 → fetcher；有导航语义 → Form。" },
    abilityTags: ["frontend.event.submit", "bridge.reactRouter.action", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 fetcher.submit 调用",
    prompt: "用 fetcher.submit({ theme: nextTheme }, { method: 'post', action: '/' });——action: '/' 含义？",
    options: [
      sc("A", "提交到根路由 / 的 action（即 root.tsx 的 action）；root action 已实现 theme 处理逻辑；不需新建 API 路由"),
      sc("B", "新建 /api/theme"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "action='/' = 调用 root.tsx 的 action；复用现有逻辑。" },
    abilityTags: ["bridge.reactRouter.action", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, ROOT],
  }),
  q({
    type: "single_choice", title: "Q5 当前主题来源",
    prompt: "切换按钮怎么知道当前是 light 还是 dark？",
    options: [
      sc("A", "从 useRouteLoaderData('root') 拿 root loader 返回的 { theme } —— Header 内已用 useOutletContext 拿 session，可同样途径拿 theme；或加进 AppOutletContext"),
      sc("B", "useState"),
      sc("C", "URL"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "服务端真值通过 root loader 流到 UI——不要自己 state 复制。" },
    abilityTags: ["frontend.state.global", "bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, ROOT],
  }),
  q({
    type: "single_choice", title: "Q6 nextTheme 计算",
    prompt: "切换按钮 onClick 内 const nextTheme = theme === 'dark' ? 'light' : 'dark';——为什么不用 boolean toggle？",
    options: [
      sc("A", "Theme 类型是 'light' | 'dark' 联合——boolean 表达力不够 + 未来加 'auto' 时只能扩字符串；从一开始用枚举值便于扩展"),
      sc("B", "boolean 更好"),
      sc("C", "TypeScript 限制"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "枚举状态 → 字符串值；boolean 适合纯 on/off。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 按钮 disabled 时机",
    prompt: "fetcher.state !== 'idle' 时按钮要 disabled？",
    options: [
      sc("A", "对——避免连点导致并发提交；submitting 期间锁住按钮 + 视觉变灰；副作用按钮的标准纪律"),
      sc("B", "永远启用"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "fetcher 进行中 = 按钮 disabled；和 Header 退出按钮同款模式。" },
    abilityTags: ["frontend.event.submit", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 optimistic 切换",
    prompt: "若想点击立即变色（不等服务端往返）——optimistic update 怎么做？",
    options: [
      sc("A", "fetcher 提交同时立刻改 documentElement.classList——用户视觉立即响应；服务端 revalidate 回来时 className 已对，无视觉跳变；失败时 fetcher.data 含错误再回滚"),
      sc("B", "等服务端"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "optimistic = 立即改 DOM + 服务端持久；失败回滚。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 SVG 图标 vs emoji",
    prompt: "图标用 ☀️ emoji 还是 SVG？",
    options: [
      sc("A", "SVG 更可控——颜色/大小用 className 调；emoji 在不同操作系统上风格差异大、跨设备不一致；设计系统首选 SVG"),
      sc("B", "emoji 更好"),
      sc("C", "完全等价"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "图标一致性 → SVG > emoji；emoji 是字符跨平台不可控。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 aria-label",
    prompt: "图标按钮加什么 aria-label？",
    options: [
      sc("A", "动态 aria-label：theme === 'dark' ? '切换到亮色主题' : '切换到深色主题' —— 屏幕阅读器读出当前操作意图；图标本身 aria-hidden=true 让阅读器只听 label"),
      sc("B", "固定 'theme'"),
      sc("C", "无需"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "动态 aria-label = 当前状态 + 操作意图——图标按钮 a11y 标配。" },
    abilityTags: ["ai.review.architecture", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 桌面 + 移动端两份",
    prompt: "Header 已有桌面 + 移动菜单两套结构——主题按钮放哪？",
    options: [
      sc("A", "桌面端导航旁加一个；移动端抽屉内底部加一行——两处都要，用户在两布局下都能切；与已有「登录」按钮的双布局做法一致"),
      sc("B", "只桌面"),
      sc("C", "只移动"),
      sc("D", "新组件"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Header 双布局策略 = 主题按钮也双布局；与登录按钮同款模式。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q12 切换全流（含已加按钮假设）",
    prompt: "已加按钮场景：用户点 Header 的主题按钮（dark→light），完整流程？",
    options: [
      sc("s1", "1. 用户点击图标按钮"),
      sc("s2", "2. onClick 内 fetcher.submit({ theme: 'light' }, { method: 'post', action: '/' })"),
      sc("s3", "3. fetcher.state 变 'submitting' → 按钮 disabled"),
      sc("s4", "4. (可选) 立刻 documentElement.classList.replace('dark','light') 视觉立刻变"),
      sc("s5", "5. Worker 收 POST / → root.tsx action"),
      sc("s6", "6. action 校验 'light' 通过 → setTheme('light', request) 生成 Set-Cookie"),
      sc("s7", "7. action 返 json + Set-Cookie 头"),
      sc("s8", "8. fetcher 完成 → revalidate root loader → getTheme 这次返 'light'"),
      sc("s9", "9. Layout 重渲染 className='light' 与 DOM 一致"),
      sc("s10", "10. fetcher.state 回 'idle' → 按钮解禁"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8", "s9", "s10"] },
    explanation: { short: "切换 10 步——客户端立刻响应 + 服务端持久 + revalidate 闭环。" },
    abilityTags: ["frontend.event.click", "frontend.event.submit", "bridge.reactRouter.action", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, ROOT, "app/utils/theme.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q13 与 system prefers-color-scheme",
    prompt: "若实现「auto」模式跟随系统——客户端怎么探测系统偏好？",
    options: [
      sc("A", "window.matchMedia('(prefers-color-scheme: dark)').matches —— 返 boolean；可在 useEffect 内监听变化（addEventListener('change', ...)）；浏览器原生 API"),
      sc("B", "navigator.theme"),
      sc("C", "cookie"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "matchMedia('(prefers-color-scheme: dark)') = 系统偏好探测标准 API。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 三态切换 UI",
    prompt: "auto/light/dark 三态怎么设计 UI？",
    options: [
      sc("A", "下拉/弹窗选择三态；或循环点击按钮（auto → light → dark → auto）；图标也跟随变化（自动用机器图标、light 用太阳、dark 用月亮）；UI 表达三态需要更多空间"),
      sc("B", "单按钮"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三态 UI = 下拉或循环按钮——比双态需要更多视觉空间。" },
    abilityTags: ["ai.review.architecture", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 表单 hidden input 方式",
    prompt: "如果用 <Form method='post'> 提交：<input type='hidden' name='theme' value={nextTheme}> 是否合理？",
    options: [
      sc("A", "合理——非 JS 用户也能切（progressive enhancement）；缺点是会触发整页 navigate；fetcher.submit 是 JS 增强方案，hidden input 是 baseline；两者各有适用场景"),
      sc("B", "永远不可"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "<Form> + hidden input = SSR/无 JS 兼容方案；fetcher = JS 增强。" },
    abilityTags: ["bridge.reactRouter.action", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 持久状态 + 临时状态",
    prompt: "如果用户切了 dark 但只想本次会话有效（不存 cookie）——可行吗？",
    options: [
      sc("A", "可行——加 sessionOnly:true 选项让 fetcher 只调 documentElement.classList 不提交 form；但 Layout 服务端 className 仍 light，与客户端不一致；偏离常规需要权衡"),
      sc("B", "无法"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "「会话内主题」= 客户端独占改 DOM 不持久；与 SSR 不同步是代价。" },
    abilityTags: ["ai.review.architecture", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 与 Header 已有 fetcher 冲突",
    prompt: "Header 已有 退出 用 const fetcher = useFetcher() ——主题按钮再用 useFetcher() 行不？",
    options: [
      sc("A", "行——每次 useFetcher() 返不同 fetcher 实例，互不干扰；Header 内可同时存 const themeFetcher = useFetcher() + const signOutFetcher = useFetcher()；命名清晰"),
      sc("B", "冲突"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useFetcher 多实例互不干扰；用命名区分用途。" },
    abilityTags: ["bridge.reactRouter.action", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 改为 React Server Action",
    prompt: "若用 React 19 Server Action 实现——怎么写？",
    options: [
      sc("A", "服务端导出 async function setThemeAction(formData) { ... }，按钮 form 直接 action={setThemeAction}；React 19 自动序列化 formData；不依赖 fetcher——但 RR7 当前推荐 loader/action 模式"),
      sc("B", "完全不可"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "React 19 Server Action 是新趋势；RR7 仍推 loader/action 范式。" },
    abilityTags: ["bridge.reactRouter.action", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 主题按钮位置 SEO",
    prompt: "主题按钮放 Header 与放 Footer——对 SEO 影响？",
    options: [
      sc("A", "无影响——主题按钮是交互 UI，搜索引擎不进 click；放哪都不计入索引；选位置纯 UX 决策"),
      sc("B", "Header 更好"),
      sc("C", "Footer 更好"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "交互 UI 不影响 SEO；位置选择按 UX。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 测试切换按钮",
    prompt: "想给主题按钮写单元测试——重点测什么？",
    options: [
      sc("A", "1) 显示当前主题对应图标 2) 点击触发 fetcher.submit 入参正确（{theme:'next', method:'post', action:'/'}）3) submitting 时 disabled 4) aria-label 正确变化；mock useFetcher 与 useRouteLoaderData"),
      sc("B", "只样式"),
      sc("C", "无需测"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "测试聚焦：状态分支 + 提交参数 + a11y——不必测样式。" },
    abilityTags: ["ai.review.architecture", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 不加切换 UI 的合理性",
    prompt: "本项目至今未加主题切换 UI——这个决定合理吗？",
    options: [
      sc("A", "合理——主题机制已就绪（cookie + loader/action 全链），但 UI 是 UX 决策；可能选择跟随 OS 偏好不暴露按钮、或留给后续 v2 加；机制 vs UI 解耦的好处"),
      sc("B", "必须加"),
      sc("C", "永不加"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "机制就绪 + UI 推迟 = 渐进交付的合理选择。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, ROOT],
  }),
  q({
    type: "single_choice", title: "Q22 主题切换 UI 整体哲学",
    prompt: "主题切换 UI 设计哲学（如果加）？",
    options: [
      sc("A", "1) 图标按钮 + 动态 aria-label——节省空间 + a11y 好 2) fetcher.submit 不进 history 3) action='/' 复用 root action 4) 当前态从 root loader 拿不本地复制 5) optimistic 改 DOM 立刻视觉响应 6) 桌面 + 移动两布局都加 7) 进行中 disabled 防连点 8) Theme 联合让 TypeScript 把守扩展安全——综合：基础设施已就绪，UI 是「机制 + UX」的薄一层"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "切换 UI 8 原则——从机制到 UI 的薄一层。" },
    abilityTags: ["ai.review.architecture", "frontend.event.click", "bridge.reactRouter.action"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, ROOT, "app/utils/theme.server.ts"],
  }),
];
