/**
 * Real questions for site-18-nemesis-api-chain / api-capstone.
 * Anchor: remix/app/routes/api.nemesis.ts —— 完整 API 链 capstone：route 编排 + service 分层 + SSE 流式 + 守门链 + 审计 + 错误协议；加新功能的影响面分析
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/api.nemesis.ts";
const sc = (id: string, text: string) => ({ id, text });

export const apiCapstoneQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 入口路由",
    prompt: "Nemesis API 入口路由文件 ____ 。",
    options: [],
    blanks: [{ id: "v", placeholder: "文件", acceptedAnswers: ["api.nemesis.ts", "api.nemesis", "routes/api.nemesis.ts"] }],
    correctAnswer: { type: "fill_blank", values: { v: "api.nemesis.ts" } },
    explanation: { short: "api.nemesis.ts = Nemesis API 唯一 HTTP 入口。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 全链文件",
    prompt: "Nemesis API 链涉及的文件总览？",
    options: [
      sc("A", "1) routes/api.nemesis.ts: 编排层 2) services/nemesis-auth.server.ts: 鉴权 3) services/nemesis-guard.server.ts: validation + guard 4) services/nemesis-rate-limit.server.ts: 限流 5) services/nemesis.server.ts: 模型调用 6) services/nemesis-reply.server.ts: 解析模型输出 7) services/nemesis-guard-events.server.ts: audit 8) lib/nemesis-sse.server.ts: SSE 工厂 9) lib/nemesis-ai-gateway.server.ts: AI Gateway 10) lib/nemesis-gemini-classifier.server.ts: Gemini 分类器；10 文件协奏"),
      sc("B", "1 文件"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Nemesis API 全链 = 10 文件协奏——分层架构。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 route 职责",
    prompt: "api.nemesis.ts route 的核心职责？",
    options: [
      sc("A", "编排层（orchestration）—— 不含业务逻辑只调度 services；method 校验 → auth → validation → rate-limit → guard → model → audit 七步顺序；返 SSE Response；薄编排层 + 厚 service 是分层基础"),
      sc("B", "业务实现"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "route = 编排层；business 在 services——分层基础。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 SSE 工厂",
    prompt: "createNemesisSseResponse(async (emit) => { ... }) 的设计？",
    options: [
      sc("A", "工厂函数封装：1) 内部创建 ReadableStream + TextEncoder 2) 给业务侧提供 emit(event, data) 简化 API 3) 业务侧不关心 SSE 协议细节（'event:' / 'data:' / '\\n\\n'） 4) 错误处理统一在工厂层；业务代码看起来像同步逐步 emit；底层流复杂度封装"),
      sc("B", "纯 fetch"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "createNemesisSseResponse = 工厂封装 SSE 协议复杂度；业务侧 emit 即可。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/nemesis-sse.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q5 emit 事件类型",
    prompt: "本 API 的 SSE 事件类型？",
    options: [
      sc("A", "1) status: 阶段进度（guard/route/model running/done） 2) done: 最终回复（含 text + attachments + mode + modelInfo） 3) error: 错误事件（message 字段）；客户端 EventSource 按 event 类型分流处理；三类事件覆盖完整流程"),
      sc("B", "无事件"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SSE 事件三类 = status/done/error——完整流程覆盖。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 客户端协议契约",
    prompt: "客户端 nemesis-sse.client.ts 与 api.nemesis 的协议契约？",
    options: [
      sc("A", "前后端共享事件类型 + payload shape：客户端按 event:'status' / 'done' / 'error' 分支处理；payload 字段（text/attachments/mode/modelInfo 等）必同步；新加事件双面同步；可考虑 .d.ts 共享类型；类型化协议"),
      sc("B", "无契约"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "前后端协议契约 = 事件类型 + payload shape——双面同步。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/lib/nemesis-sse.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q7 完整请求生命周期",
    prompt: "用户在 chat 页输入「你好」点发送的全链路？",
    options: [
      sc("A", "1) useNemesisChat 调 requestNemesisReply → fetch /api/nemesis POST 2) action 入口 method:POST ✓ 3) requireNemesisUser → session DB 查 4) validateRequest → 解析 + 收窄 5) checkRateLimit → DO RPC 6) emit guard running 7) guardMessage → RULE → GEMINI 8) emit guard done 9) modeReply check：PASS_TO_GEMINI → 10) emit route running 11) callNemesisModel → AI Gateway → Gemini API 12) parseReply 13) emit done with text 14) recordAudit (waitUntil) 15) 客户端 onmessage 累加到 messages 状态；15 步全链"),
      sc("B", "纯 fetch"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "完整请求 15 步——客户端 + Worker + service + AI Gateway + DB 协奏。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 错误路径",
    prompt: "上述链路在哪些点可能失败？",
    options: [
      sc("A", "1) auth 失败 → 401 JSON 2) validation 失败 → 422 JSON 3) rate-limit 失败 → 429 JSON 4) guard error → emit error 5) Gemini API 失败 → emit error NemesisModelError 6) parseReply 失败 → emit error 7) 网络中断 → SSE 连接断开 客户端 retry；多失败点 + 多协议（JSON vs SSE）"),
      sc("B", "无失败"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "失败点 7 处 + 双协议（JSON 拒 vs SSE emit error）——错误地图。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 协议双层",
    prompt: "为什么 auth/validation/rate-limit 失败用 JSON status 4xx 但 guard/model 失败用 SSE emit error？",
    options: [
      sc("A", "前置守门链失败时还没开 SSE 流（status 还可设）→ 用 JSON + 4xx；进入 SSE 流后 status 已发（200）不能改 → 错误必走流内 emit；分界点是 createNemesisSseResponse 调用；协议双层"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "协议双层 = 流前 JSON + 流后 SSE emit——createSse 是分界点。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 加新「分析模式」功能",
    prompt: "若加 'analysis_mode' 让用户切换严肃 vs 轻松回复——影响面？",
    options: [
      sc("A", "1) parse-body 加 mode 字段校验（'normal' | 'analysis'） 2) callNemesisModel 接 responseMode 参数（已有路径） 3) Gemini prompt 按 mode 切系统提示 4) audit 表加 mode 列（可观测） 5) 客户端 NemesisChatPage 加 mode 选择 UI 6) 状态管理 useNemesisChat 加 mode state；前后端 + DB 多处协同"),
      sc("B", "改一处"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "加新功能 = 前后端 + DB schema + service + UI 多处协同。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 加新 attachment 类型",
    prompt: "若 LLM 回复可附「图片」附件——改？",
    options: [
      sc("A", "1) parseReply 内识别 image attachment shape（image_url 字段等） 2) emit done payload.attachments 数组加 image 类型 3) 客户端 NemesisChatMessage 渲染 image 类型 attachment 4) 类型加 NemesisAttachment union 加 image 变体；类型驱动协议演进"),
      sc("B", "改一处"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "加 attachment 类型 = parse + emit + 客户端渲染 + 类型 union——多处。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 加 streaming token",
    prompt: "若想客户端实时看到 token 增量（typewriter 效果）——改？",
    options: [
      sc("A", "1) callNemesisModel 内开 streaming 模式（onChunk 回调） 2) 通过 onProgress 透传到 route 3) emit 'token' 事件每次新 chunk 4) 客户端 SSE handler 加 token case 累积到当前消息 5) 现有 emit done 改成 emit done 终止信号 + 完整 text；流式协议增强"),
      sc("B", "无需改"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "streaming token = 模型 streaming + onProgress + 新 token event + 客户端累积。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 性能瓶颈",
    prompt: "Nemesis API 在高并发下可能瓶颈？",
    options: [
      sc("A", "1) Gemini API 限速（主瓶颈）——1000 RPM 等 2) D1 session 查询（hot path 已 cache 缓解） 3) DO 限流 RPC 串行 4) audit 写 D1（已 waitUntil 缓解） 5) Worker CPU（SSE 流连接占用）；Gemini API 是首要瓶颈"),
      sc("B", "无瓶颈"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "性能瓶颈 = Gemini API 主 + DB hot path + DO RPC 次——分层。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 监控指标",
    prompt: "Nemesis API 应监控的指标？",
    options: [
      sc("A", "1) 请求 QPS（按 status 分） 2) 各阶段延迟（auth/validation/rate-limit/guard/model/audit）3) Gemini API 错误率 4) guard category 分布（mode='REFUSE' 比例） 5) rate-limit 触发率 6) audit 写入失败率 7) SSE 连接持续时间；多维度可观测"),
      sc("B", "无监控"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Nemesis API 监控 = QPS + 各阶段延迟 + 错误率 + audit——多维度。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 安全审计要点",
    prompt: "Nemesis API 安全审计要点？",
    options: [
      sc("A", "1) auth 必须（无匿名）2) rate-limit 防滥用 3) input guard 防越界 4) Gemini 通过 AI Gateway 防 API key 暴露 5) audit 不存敏感细节给客户端 6) 错误响应不暴露内部 stack/path 7) NO_STORE 防错缓 8) trustedOrigins 防 CSRF 9) sanitize log 防 secret 进日志；9 项审计"),
      sc("B", "无需审"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Nemesis 安全审计 = 9 项清单——纪律。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 测试 Nemesis API",
    prompt: "Nemesis API 完整测试策略？",
    options: [
      sc("A", "1) service 单测：各 service mock 内部 + 验返回 2) route 单测：mock 所有 services 验编排逻辑 + emit 序列 3) 集成测：真 worker 起 + mock Gemini API + 端到端走流程 4) e2e：浏览器 puppeteer 走真实流程；4 层测试金字塔"),
      sc("B", "只 e2e"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "测试金字塔 = 单测 + route 测 + 集成 + e2e——4 层。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 部署灰度",
    prompt: "Nemesis API 改动如何灰度发布？",
    options: [
      sc("A", "1) Cloudflare Workers Versions 提供蓝绿/分流 2) 新版本先小流量（5%）观察指标 3) 监控错误率 + 延迟 + 用户反馈 4) 没问题逐步扩到 100% 5) 有问题立即 rollback；workers 平台原生支持灰度"),
      sc("B", "全量"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "灰度 = Workers Versions 分流 + 监控指标 + 渐进——平台支持。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 协议版本",
    prompt: "若需要不破坏旧客户端兼容下进化 SSE 协议——策略？",
    options: [
      sc("A", "1) 加新事件类型不删旧（旧客户端忽略未知 event 类型） 2) payload 加可选字段不删必字段 3) 加 protocol_version 字段服务端可识别旧客户端走兼容路径 4) URL path 版本化 /api/nemesis/v2/...；前向兼容设计"),
      sc("B", "强制升"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "协议演进 = 加 + 不删 + 版本字段 + URL 版本化——前向兼容。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 与 feedback API 协奏",
    prompt: "api.nemesis-feedback.ts 是 Nemesis API 链一部分？",
    options: [
      sc("A", "是——用户对 LLM 回复反馈（点赞/拍砖/标记问题）→ 写 D1 反馈表；与 audit 数据关联 → 调优规则；与主 API 是「主调用 + 旁路反馈」关系；分文件保职责单一"),
      sc("B", "无关"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "feedback API = 主调用 + 旁路反馈关系——分文件单一职责。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/routes/api.nemesis-feedback.ts"],
  }),
  q({
    type: "single_choice", title: "Q20 route vs service 切分原则",
    prompt: "什么放 route 什么放 service？",
    options: [
      sc("A", "route：HTTP 协议处理（method/headers/Response）+ 编排（顺序调 services）+ SSE 流管理；service：纯业务（鉴权 / 守卫 / 模型）；route 知道 framework + service 不依赖 framework 可独立测；分层"),
      sc("B", "随便"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "route = HTTP + 编排；service = 纯业务——分层切分。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 演进路径",
    prompt: "Nemesis API 链可能的演进方向？",
    options: [
      sc("A", "1) Streaming token UX 增强 2) 多模型路由（Gemini/Claude/GPT 按场景切） 3) 输出守卫（model 后再 guard） 4) 响应缓存（同问题命中省成本） 5) 用户偏好持久化（语气/长度等） 6) 多语言支持 7) RAG（接知识库） 8) 工具调用（weather/calc 等 function calling）；AI 平台演进方向多元"),
      sc("B", "已完美"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "演进方向 = streaming + 多模型 + 输出守卫 + 缓存 + RAG + tools——多元。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 api-capstone 整体哲学",
    prompt: "Nemesis API 链整体哲学？",
    options: [
      sc("A", "1) route 薄编排 + service 厚业务（分层基础） 2) 五步前置守门链（auth/validation/rate-limit/guard）顺序固定按短路成本 3) SSE 流式响应 + emit 工厂封装协议 4) 协议双层（流前 JSON + 流后 emit）按 createSse 分界 5) 三类事件（status/done/error）覆盖完整流程 6) 前后端类型化协议契约 7) 错误响应状态码精确（401/403/422/429）+ NO_STORE 8) waitUntil 异步审计 + .catch 容错 9) NODE_ENV 条件 log 卫生 10) modeReply 短路省成本 11) onProgress 透传分层进度 12) 测试金字塔（单测 + route + 集成 + e2e） 13) 灰度发布 + 协议版本演进 14) 监控多维度（QPS + 延迟 + 错误） 15) 安全审计 9 项；综合：「分层 + 编排 + 流式 + 协议化 + 可观测 + 演进」六件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Nemesis API 链 15 原则——AI 应用 HTTP 入口的工程纪律。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "bridge.reactRouter.action"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
];
