/**
 * Real questions for site-18-nemesis-api-chain / call-guard.
 * Anchor: remix/app/routes/api.nemesis.ts —— route 内调 guardNemesisMessage(env, message, recentMessages) → GuardDecision；getNemesisModeReply(mode) → 固定文案；guard 短路与放行决策
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/api.nemesis.ts";
const sc = (id: string, text: string) => ({ id, text });

export const callGuardQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 调用",
    prompt: "route action 内 const guard = await ____ (env, message, recentMessages);",
    options: [],
    blanks: [{ id: "v", placeholder: "函数", acceptedAnswers: ["guardNemesisMessage"] }],
    correctAnswer: { type: "fill_blank", values: { v: "guardNemesisMessage" } },
    explanation: { short: "guardNemesisMessage = 守卫主入口。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/services/nemesis-guard.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q2 三参数含义",
    prompt: "guardNemesisMessage(env, message, recentMessages) 三参数？",
    options: [
      sc("A", "env: cloudflare env（含 GEMINI_API_KEY 等给分类器调）；message: 当前用户输入；recentMessages: 上下文最近 ≤10 条；env 让 service 可独立测试（不依赖 process）；message + 上下文给 Gemini 完整决策依据"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三参数 = env 注入 + 当前消息 + 上下文——决策完整依据。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 emit guard 状态",
    prompt: "guard 调用前后 emit('status', { step: 'guard', state: 'running' }) → 'done'——为什么？",
    options: [
      sc("A", "守卫调用 200-500ms（含 Gemini API），客户端必须知道「现在在做什么」否则页面静默；status 事件让 UI 显示 '正在做安全判断…' '安全判断完成'；UX 进度感"),
      sc("B", "调试"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "emit guard 状态 = AI 长流程必备 UX 进度感。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 guard.mode 短路",
    prompt: "const modeReply = getNemesisModeReply(guard.mode); if (modeReply) { recordAudit(...); emit('done', ...); return; }——什么时候短路？",
    options: [
      sc("A", "guard.mode 为 'CLARIFY' / 'REFUSE' / SAFE_BOUNDARY 等时——固定文案直接回复用户不调 Gemini 模型；省 API 成本 + 立即响应；getNemesisModeReply 是「文案查表」函数；快速路径"),
      sc("B", "永远短路"),
      sc("C", "永不"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "modeReply 短路 = 固定文案分支不调模型——快速路径优化。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/nemesis/guard-replies.ts"],
  }),
  q({
    type: "single_choice", title: "Q5 PASS_TO_GEMINI 路径",
    prompt: "guard.mode === 'PASS_TO_GEMINI' 时——继续做什么？",
    options: [
      sc("A", "进入 callNemesisModel 调 Gemini 模型实际生成回复；emit('status', { step: 'route', state: 'running', label: 'Gemini 意图分类中…' }) 让 UI 显示新阶段；走完整模型链；guard 是 gate 不是 endpoint"),
      sc("B", "停止"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "PASS_TO_GEMINI = 守卫放行 → 走完整模型链——gate 不是 endpoint。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 stage detail emit",
    prompt: "emit('status', { step: 'guard', state: 'done', detail: stage === 'GEMINI' ? `Gemini 安全分类器 ... · ${mode}` : 'RULE_GUARD' ? '规则守卫' : undefined });——detail 字段？",
    options: [
      sc("A", "高级 UX——告诉用户「这次决策走了哪个阶段」（规则 vs Gemini）；调试和透明性；用户对 AI 黑盒感更可控；可选字段（undefined 时 UI 不显示）；阶段感知 UX"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "detail = 阶段感知 UX——透明 + 可控感。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 audit 收集",
    prompt: "recordAudit({ assistantMessage, modelResult }) 通过 cloudflare?.ctx?.waitUntil 异步——为什么这种？",
    options: [
      sc("A", "1) audit 写 D1 是非关键路径 2) waitUntil 让响应已发送但任务后台跑 3) 不阻塞 SSE 流 4) 失败 .catch 吞错保主流程；可观测性但不影响用户响应；典型 worker 异步副作用模式"),
      sc("B", "阻塞"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "waitUntil + audit = 可观测但不影响响应——副作用异步。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 guard.shouldAudit",
    prompt: "if (!guard.shouldAudit) { return; } 在 recordAudit 内——什么场景？",
    options: [
      sc("A", "守卫决策 shouldAudit:false 时——通常是「明显正常对话」不需要 audit（避免日志噪声 + D1 写入成本）；只「有风险/拒绝/重要分类」事件审计；选择性"),
      sc("B", "总审计"),
      sc("C", "永不"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "shouldAudit:false = 跳过 audit 写入——日志噪声 vs 完整性平衡。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 dev-only console.log",
    prompt: "if (process.env.NODE_ENV !== 'production') console.log('[NemesisGuard]', { ... });——为什么仅 dev？",
    options: [
      sc("A", "1) 含敏感信息（消息长度 + 决策细节 + classifierReason）prod 滥写日志泄密 2) Cloudflare 日志成本 3) prod 性能影响（每请求 console.log 累积） 4) dev 调试用 + prod 静默；条件 log 平衡"),
      sc("B", "永远 log"),
      sc("C", "永不"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "条件 log = dev 验证 + prod 静默——日志卫生。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 guard 的位置",
    prompt: "为什么 guard 在 rate-limit 之后 model 之前？",
    options: [
      sc("A", "1) rate-limit 在前防恶意刷 → guard 也保护成本（不让一次违规请求消费 guard API）2) guard 之后才调贵的 model（拒了不调省钱）3) 顺序：先认证 → 限流 → guard → model；位置反映「贵在后」原则"),
      sc("B", "无所谓"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "guard 位置 = 限流后 + 模型前——「贵在后」短路成本。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 guard 失败模式",
    prompt: "若 guardNemesisMessage 内部 Gemini 分类器调用失败——怎么办？",
    options: [
      sc("A", "service 内部 fall back 到规则决策（CLASSIFIER_FAILED 时返 PASS_TO_GEMINI 或 CLARIFY 视配置）；不让 guard 整体崩；route 调用方拿到决策正常处理；优雅降级"),
      sc("B", "崩"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "guard 内部容错 fallback = 优雅降级——service 责任。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 guard 输入消毒",
    prompt: "guard 内 normalizeInput(message) 是先做的——什么含义？",
    options: [
      sc("A", "trim + 多空白合一让规则匹配看到「干净」字符串；同一意图（attacker 加空白绕过）规则也能中；输入消毒是守卫第一步；不消毒则规则被 trivial 绕过"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "normalizeInput = 守卫第一步防绕过——消毒标配。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "backend.validation.field"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 guardDecision 信息可见性",
    prompt: "GuardDecision 14 字段哪些回前端 vs 仅内部？",
    options: [
      sc("A", "回前端：mode（决定 UI 走向）、stage 摘要 detail（透明 UX）；仅内部：classifierReason（隐私）、ruleId/ruleName（暴露规则细节给攻击者）、suggestedChange（运维元数据）；选择性暴露"),
      sc("B", "全暴露"),
      sc("C", "全隐藏"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "guard 信息分级暴露 = mode/stage 给前端 + reason/ruleId 仅内部。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 错误：guard 后回退限流计数",
    prompt: "guard 拒后能否回退 rate-limit 计数？",
    options: [
      sc("A", "通常不——rate-limit 在 guard 前已计数 → guard 拒后不回退（防恶意试探守卫规则不付频次代价）；保护守卫不被穷举；位置选择反映这个意图"),
      sc("B", "应回退"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "guard 拒后不回退限流 = 防穷举攻击——位置反映此意图。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "backend.rateLimit"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 错误：直接传原始 body",
    prompt: "若调 guardNemesisMessage(env, body.message, body.recentMessages) 而非用 validation 后的——后果？",
    options: [
      sc("A", "1) body 未校验可能含恶意 type（不是 string） → guard 内 typeof check 失败处理但有崩风险 2) recentMessages 未限长 → guard 内全扫慢 3) 跳 validation 直接 guard 是反模式；validation 必先；project 流程是正确"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "validation 必先 + guard 后 = 防御纪律。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "backend.validation.field"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 错误：忘 emit done",
    prompt: "若 modeReply 短路时漏 emit('done', ...)——后果？",
    options: [
      sc("A", "客户端 SSE 永等不来 done 事件 → 显示 loading 直到超时；用户看到 'Nemesis 思考中…' 永久；UX 故障；done emit 必备 + 可加 finally 保证"),
      sc("B", "正常"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "漏 emit done = 客户端永等——UX 故障。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 测试 call-guard",
    prompt: "怎么测 route 内 guard 调用逻辑？",
    options: [
      sc("A", "1) mock guardNemesisMessage 返不同 GuardDecision 2) 验 modeReply 时 emit('done',...) 走 3) 验 PASS_TO_GEMINI 时进入 model 调用 4) 验 guard error 时 emit('error',...) 5) audit 调用是否带正确 args；对 route 编排逻辑分支测"),
      sc("B", "无法测"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "route 测试 = mock service + 分支验证 emit + 调用——编排测试。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 加新 mode",
    prompt: "若加新 mode 'TYPING_TEST'（专门测试响应速度）—— 需要哪？",
    options: [
      sc("A", "1) NemesisMode union 加 'TYPING_TEST' 2) guard-replies 加对应固定文案（或动态生成） 3) getNemesisModeReply 内 case 处理 4) classifier-prompt 教 Gemini 何时返该 mode 5) audit 表能存（已是 string）；加 mode 多文件协同"),
      sc("B", "改一处"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "加 mode = type + replies + getReply + classifier-prompt + audit 五处协同。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 短路 vs 完整链对比",
    prompt: "短路（modeReply）vs 走完整链（PASS_TO_GEMINI）的延迟差？",
    options: [
      sc("A", "短路：guard ~200-500ms 后 emit done，总 ~500ms；完整链：guard ~200-500ms + Gemini 调用 1-3s + parse + emit ~1.5-3.5s；短路省 1-3 秒；guard 已先 200-500ms 是基本固定成本"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "短路省 1-3s = guard 后跳过 model；可观察延迟差异。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 调试 guard 误判",
    prompt: "用户反馈「我说了正常的话却被拒」—— 怎么调？",
    options: [
      sc("A", "1) 看 [NemesisGuard] log（dev mode）含 mode/category/stage/ruleId 2) D1 audit 表查该用户最近请求 3) 找 stage = RULE_GUARD（规则误中）or GEMINI（分类器问题）4) 复现：用相同输入跑 dev 看决策 5) suggestedChange 字段可能已提示；多线索 + audit 数据"),
      sc("B", "无法调"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "误判调试 = log + audit + 复现 + suggestedChange——数据驱动。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 guard 与 model 解耦",
    prompt: "guard 调用与 model 调用是同一 stream 内吗？",
    options: [
      sc("A", "是——同一 createNemesisSseResponse 流；guard 完成后 emit guard done 状态，再 emit model running 状态，然后 model 流；统一 SSE 流让客户端只接一条连接；分阶段 status 事件区分；流复用"),
      sc("B", "分两连接"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "guard + model 同一 SSE 流 = 客户端单连接 + 分阶段 status——流复用。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 call-guard 整体哲学",
    prompt: "route 内 guard 调用编排整体哲学？",
    options: [
      sc("A", "1) guard 在限流后 + 模型前位置反映「贵在后」原则 2) 调用前后 emit status running/done UX 进度 3) modeReply 短路省 1-3s + API 成本 4) PASS_TO_GEMINI 走完整模型链 5) recordAudit waitUntil 异步不阻塞 6) shouldAudit 选择性记录 7) detail 字段透明 stage 来源 8) guard 信息分级暴露（mode 给前端 + reason 仅内部） 9) dev-only console.log 卫生 10) guard 失败 service 内部 fall back 11) validation 必先 + guard 后纪律 12) 同一 SSE 流复用流；综合：「编排 + 短路 + UX + 异步 + 信息分级」五件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "call-guard 12 原则——route 守卫调用编排纪律。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
];
