/**
 * Real questions for site-18-nemesis-api-chain / parse-body.
 * Anchor: remix/app/services/nemesis-guard.server.ts (validateNemesisRequest) —— request.json 解析 + unknown 类型收窄 + message/recentMessages 字段校验 + role 收窄 + length 限制 + discriminated union 返回
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/services/nemesis-guard.server.ts";
const sc = (id: string, text: string) => ({ id, text });

export const parseBodyQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 解析方法",
    prompt: "validateNemesisRequest 内 const body = await request. ____ ();",
    options: [],
    blanks: [{ id: "v", placeholder: "方法", acceptedAnswers: ["json"] }],
    correctAnswer: { type: "fill_blank", values: { v: "json" } },
    explanation: { short: "request.json() = Web Fetch 标准 body 解析 JSON 方法。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 request.json 默认行为",
    prompt: "request.json() 行为？",
    options: [
      sc("A", "1) 读 body stream 到字符串 2) 调 JSON.parse 解析 3) 返 unknown（TypeScript 严格不返 any） 4) 失败抛 SyntaxError；调用前必 try/catch 防恶意 body 抛错；返回 unknown 强制后续收窄"),
      sc("B", "返 any"),
      sc("C", "纯字符串"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "request.json = stream + parse + unknown——必 try/catch + 收窄。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "backend.validation.field"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 unknown 而不 any",
    prompt: "解析后 body 类型为 unknown 不 any——为什么？",
    options: [
      sc("A", "unknown 强制使用前类型校验（如 typeof body === 'object' && body !== null）；any 绕过类型检查直接 .message 取值（运行时可能 crash）；TypeScript 安全实践推荐 unknown 防漏洞"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "unknown = 强制收窄；any = 类型黑洞——TS 安全推荐 unknown。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 字段收窄链",
    prompt: "校验 body.message 是字符串——典型链？",
    options: [
      sc("A", "if (!body || typeof body !== 'object') return invalid; const message = (body as Record<string, unknown>).message; if (typeof message !== 'string') return invalid; if (!message.trim()) return invalid;——逐级收窄"),
      sc("B", "body.message.trim() 直调"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "字段收窄 = typeof + Record cast + 字符串校验——逐级安全。" },
    abilityTags: ["backend.validation.field", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 长度校验",
    prompt: "if (message.length > MAX_MESSAGE_LENGTH) return { ok: false, status: 422, payload: { error: '消息过长' } };——为什么有上限？",
    options: [
      sc("A", "1) 防 DOS（巨型 body 耗内存） 2) Gemini API 输入 token 限制（成本 + 上下文窗口） 3) UX（超长不合理）4) 配 NEMESIS_MAX_MESSAGE_LENGTH env 可调；多重防护"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "长度上限 = DOS + 成本 + UX——多重防护必备。" },
    abilityTags: ["backend.validation.field", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 recentMessages 数组校验",
    prompt: "recentMessages 是 NemesisRecentMessage[]——校验？",
    options: [
      sc("A", "1) Array.isArray(recentMessages) 2) 限长 ≤ MAX_RECENT_MESSAGES (10) 3) forEach 内 typeof item === 'object' + role/text 各自校验 4) role 必须 'user' | 'model' 闭集；多层校验防恶意 array"),
      sc("B", "as cast"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "数组校验 = isArray + 限长 + 元素逐校 + role 闭集——四层。" },
    abilityTags: ["backend.validation.field", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 role 闭集",
    prompt: "role 必须 'user' | 'model'——为什么严格？",
    options: [
      sc("A", "1) 业务只接受这两个角色 2) Gemini API 输入要求严格格式 3) 攻击者可塞 'system' 试图覆盖系统 prompt 越权——拒绝 4) 闭集 + Set 校验性能 O(1)；安全 + 协议合规"),
      sc("B", "随便"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "role 闭集 = 协议 + 防越权——必严格。" },
    abilityTags: ["backend.validation.field", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 try/catch JSON 解析",
    prompt: "若 body 不是合法 JSON——validateNemesisRequest 怎么处理？",
    options: [
      sc("A", "request.json() 抛 SyntaxError → try/catch 捕获 → 返 { ok:false, status:400, payload: { error: '请求体格式错误' } }；不让错误冒泡到框架（保 API 友好响应）；422 也合理"),
      sc("B", "崩"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "JSON 解析失败 catch + 返 400——API 友好响应。" },
    abilityTags: ["ai.review.architecture", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 discriminated union 返回",
    prompt: "返 { ok: true, message, recentMessages } | { ok: false, status, payload }——这种返回为什么？",
    options: [
      sc("A", "TS discriminated union——调用方 if (result.ok) 编译器自动收窄到成功分支拿数据；ok:false 拿 status/payload；不抛异常降低控制流复杂度；类型驱动分流"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "discriminated union = 编译器自动收窄——零断言 + 不抛错。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "backend.validation.field"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 Content-Type 校验",
    prompt: "应该校验 request.headers.get('Content-Type') === 'application/json' 吗？",
    options: [
      sc("A", "request.json() 内部不强求 Content-Type（基本宽松）；项目可严格校验拒非 application/json（防误调）；项目当前依赖 json 解析失败抛错的隐式校验；可后续严格"),
      sc("B", "强制必"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Content-Type 校验 = 严格防误调；项目用 json 解析隐式校验。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "backend.validation.field"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 zod vs 手动校验",
    prompt: "项目用手动 if/typeof 校验而非 zod schema——为什么？",
    options: [
      sc("A", "1) Worker bundle 大小敏感（zod 加几十 KB） 2) 校验逻辑简单（2-3 字段）手动够用 3) 错误信息可定制 4) 不依赖第三方；手动校验在简单场景仍合理；复杂 schema 才上 zod"),
      sc("B", "应该用 zod"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "手动 vs zod = bundle 大小 + 复杂度权衡；简单选手动。" },
    abilityTags: ["backend.validation.field", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 字段额外属性",
    prompt: "若 body 多了 extra 字段—— 应该怎么处理？",
    options: [
      sc("A", "项目严格收窄只取已知字段（message + recentMessages），extra 自然忽略；不需主动报错（前后兼容性）；攻击者塞 extra 试图越权也无效（不被读）；防御性默认安全"),
      sc("B", "报错"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "extra 字段忽略 = 前后兼容 + 防御性安全。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "backend.validation.field"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 错误：跳过校验",
    prompt: "若直接 const { message } = await request.json() 不校验——后果？",
    options: [
      sc("A", "1) message 类型 any 调 .trim/.length 可能 crash 2) 攻击者塞 message: { malicious: 'object' } → guard 内调 .replace 抛错 3) 大 body 不限长 → 内存爆 4) recentMessages 不校验 → role 'system' 越权；多种漏洞链"),
      sc("B", "无影响"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "跳校验 = 类型崩 + 越权 + DOS 多漏洞——必校验。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "backend.validation.field"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 错误：throw 而非 return",
    prompt: "若 validation 失败 throw new Error 而非 return { ok: false }——后果？",
    options: [
      sc("A", "调用方需 try/catch 处理（控制流复杂） + Error 内部细节可能泄露给客户端；项目 discriminated union return 是更清晰的选择；abort/throw 错误风格在校验场景不推荐"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "validation throw 不推荐 = 控制流复杂 + 信息泄露——return 更好。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 错误信息细节",
    prompt: "validation 失败 payload: { error: '消息不能为空' } vs { error: '请求体格式错误' }——粒度？",
    options: [
      sc("A", "粒度适中——告诉用户「错在哪」便于修但不暴露内部 schema 细节（如「字段 recentMessages[2].role 必须是 user|model」过细给攻击者绘图）；用户视角友好 + 安全模糊"),
      sc("B", "全详细"),
      sc("C", "全模糊"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "错误粒度 = 适中（用户友好 + schema 不暴露）——平衡。" },
    abilityTags: ["ai.review.architecture", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 错误：trim 后空字符",
    prompt: "message.trim() === '' 应当如何？",
    options: [
      sc("A", "返 422 / 400 + '消息不能为空'；trim 是 normalizeInput 的一部分；空消息无意义不浪费 API 成本 + 用户体验提示；多重处理"),
      sc("B", "通过"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "trim 后空 = 拒；防无意义请求。" },
    abilityTags: ["backend.validation.field", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 加新字段流程",
    prompt: "若给 nemesis 加可选 'mode' 字段（'normal' | 'creative'）——改 validation？",
    options: [
      sc("A", "1) NemesisRequestValidationResult 类型加 mode?: string 2) validate 内 if (typeof body.mode === 'string' && ['normal','creative'].includes(body.mode)) message.mode = body.mode; 3) 默认 'normal' 4) 失败合理处理（拒或默认）；类型 + 校验 + 默认值三步"),
      sc("B", "无修改"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "新字段 = 类型 + 校验 + 默认值——三步走。" },
    abilityTags: ["backend.validation.field", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 测试 validation",
    prompt: "validation 单测策略？",
    options: [
      sc("A", "1) 创 mock Request 含各类 body（合法/缺字段/类型错/超长/role 越权/数组超长/非 JSON 等）2) 调 validateNemesisRequest 验返回 ok + 数据 / ok:false + status 3) 边界（length=0 vs 1 vs MAX 等）；分支 + 边界覆盖"),
      sc("B", "e2e only"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "validation 测试 = 各类输入 mock + 分支 + 边界——覆盖完整。" },
    abilityTags: ["backend.validation.field", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 stream body",
    prompt: "request.body 也是 ReadableStream——为什么用 .json() 不直接读 stream？",
    options: [
      sc("A", "request.json 内部已封装 1) 读 stream 到 string 2) JSON.parse 3) 类型转换；手写 stream 读 + parse 复杂 + 易出错；常见用例都用 .json() 快捷方法；高级用例（如逐 chunk 处理）才用 stream"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".json() = 标准简化；stream 仅高级用例。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 body 一次性消费",
    prompt: "request.body / request.json 是一次性消费的—— 二次读会怎样？",
    options: [
      sc("A", "stream 已读完 → 二次 await request.json() 抛 'body already consumed'；项目 validateNemesisRequest 内一次读取完即解决；若需多次读必先 const body = await request.json() 缓存或 request.clone()；流的限制"),
      sc("B", "可重复读"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "body 一次性消费 = stream 流限制；二次读必 clone 或缓存。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 与 form data 区别",
    prompt: "若客户端用 FormData 而非 JSON 提交——怎么办？",
    options: [
      sc("A", "1) request.formData() 接 FormData 对象 2) form.get('field') 取值（默认 string）3) 校验逻辑同 JSON 但 API 不同 4) Remix Form 默认 FormData；项目 nemesis API 用 JSON 因复杂结构（recentMessages 嵌套数组难 form 表达）；选 JSON vs FormData 看 schema 复杂度"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "JSON vs FormData = schema 复杂度差异；嵌套结构选 JSON。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 parse-body 整体哲学",
    prompt: "请求体解析整体哲学？",
    options: [
      sc("A", "1) request.json() 标准解析 + 返 unknown 强制收窄 2) try/catch 防 JSON 错误冒泡到框架 3) typeof + Record cast 逐级收窄字段类型 4) message 长度 + trim 校验 5) recentMessages 数组 + 限长 + 元素 role 闭集校验 6) discriminated union 返 ok:true|ok:false 不抛错降复杂度 7) 错误 payload 粒度适中（用户友好 + schema 不暴露） 8) extra 字段自然忽略防御默认 9) 手动校验非 zod 适简单 schema + bundle 优化 10) JSON vs FormData 按嵌套复杂度选；综合：「解析 + 收窄 + 校验 + 不抛错 + 防御性」五件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "parse-body 10 原则——请求体解析与校验纪律。" },
    abilityTags: ["backend.validation.field", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
];
