/**
 * Real questions for site-17-guards-rate-limit / admin-bypass.
 * Anchor: remix/app/services/nemesis-guard.server.ts + auth.server.ts —— 管理员特权设计：isAdmin(email) 判断 + ADMIN_EMAILS env 列表 + admin role + 跳过限流/守卫的位置选择
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/services/nemesis-guard.server.ts";
const sc = (id: string, text: string) => ({ id, text });

export const adminBypassQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 admin 判断函数",
    prompt: "判断管理员的工具函数 ____ (email)；从 auth.server 导出。",
    options: [],
    blanks: [{ id: "v", placeholder: "函数名", acceptedAnswers: ["isAdmin"] }],
    correctAnswer: { type: "fill_blank", values: { v: "isAdmin" } },
    explanation: { short: "isAdmin(email) = 判断邮箱是否在 ADMIN_EMAILS env 列表内。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/auth.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q2 admin bypass 设计动机",
    prompt: "为什么需要管理员特权（绕过限流/守卫）？",
    options: [
      sc("A", "1) 测试场景（admin 高频测试新规则）2) 紧急运维（故障时不被限流卡死）3) 内容审核（admin 看到守卫拒绝原文以调规则）4) 客户支持（admin 帮用户复现问题）；测试 + 运维 + 审核 + 支持四类需求"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "admin bypass = 测试 + 运维 + 审核 + 支持需求。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 ADMIN_EMAILS env",
    prompt: "ADMIN_EMAILS 是 env var（逗号分隔邮件）—— 为什么不存 DB？",
    options: [
      sc("A", "1) 部署即生效（无需写 DB） 2) 不依赖 DB 可用性（DB 挂时 admin 仍可登录） 3) 部署版本控制（env 改动可 git diff） 4) 灾备应急用；env 是「初始化的根」；DB role 列是运行时动态调（admin plugin 提供）；env + DB 双层保险"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ADMIN_EMAILS env = 部署即生效 + 不依赖 DB——根级配置。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/auth.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q4 isAdmin 实现",
    prompt: "function isAdmin(email) { return getAdminEmails().includes(email); }——细节？",
    options: [
      sc("A", "getAdminEmails 解析 env 切分逗号 + trim + filter falsy；includes 严格相等；email 大小写敏感（注意：实际 email 大小写不敏感但代码层严格）；潜在问题：注册时大写 email 与 env 小写不匹配 → 实际部署需统一小写存配置"),
      sc("B", "正则"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "isAdmin = env list includes 严格匹配——注意大小写一致。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/auth.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q5 双层 admin 判断",
    prompt: "isAdmin(email) 与 user.role === 'admin' 双层——为什么？",
    options: [
      sc("A", "1) ADMIN_EMAILS 是「声明式管理员」（部署配置） 2) user.role 是「DB 持久化状态」（admin plugin API 写） 3) 登录时 promoteConfiguredAdmin 自动同步 env email → DB role 4) 双层冗余但路径互补：env 增删快 + DB 历史可审计；分级"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "env email + DB role 双层 = 部署快增删 + DB 历史可审；分级。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/auth.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q6 admin 在 require 函数中的判断",
    prompt: "requireAdmin 内 if (!isAdmin(email) && role !== 'admin') throw redirect('/');——为什么 OR 而不 AND？",
    options: [
      sc("A", "OR：env 是 admin 或 DB role 是 admin 任一即放行；可处理边界（如 ADMIN_EMAILS 临时移除但 DB role 还在/或反之）；最大化 admin 可达性；安全代价：env 移除一人但 DB 还 admin → 仍有权限（需双手清理）；权衡"),
      sc("B", "应该 AND"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "OR 双层 = 最大可达 + 双源验证；移除需双手清理。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 admin 绕过限流——位置",
    prompt: "若给 admin 加「绕过 nemesis 限流」—— 改哪里？",
    options: [
      sc("A", "checkNemesisRateLimit 内首行 if (isAdmin(user.email)) return { allowed: true };——一行短路；保持调用方代码不变；其他路由 admin 跳限流可同样模式；统一处加防遗漏"),
      sc("B", "route 内 if"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "checkRateLimit 内首行 admin 短路 = 集中处加防漏。" },
    abilityTags: ["backend.rateLimit", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/services/nemesis-rate-limit.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q8 admin 绕过守卫",
    prompt: "admin 应该绕过 guardNemesisMessage 内容守卫吗？",
    options: [
      sc("A", "通常不建议——admin 也应受同样守卫（一致性 + 测试守卫真实行为）；若必绕过应严格场景（如「测试守卫规则」专用入口）；不要全面 bypass 让 admin 看到的与用户不一致；除非用「shadow mode」（守卫报告但不拒）"),
      sc("B", "总是绕"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "guard admin 不绕（一致性）；若必绕用 shadow mode——区别于限流。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 admin 路由独立",
    prompt: "项目可能新增 /admin/test-guard 测试规则用——架构？",
    options: [
      sc("A", "1) /learn/admin/* 路由组（loader 调 requireAdmin） 2) admin route 内可调 raw guardNemesisMessage 看决策细节 3) 不暴露给普通用户； 4) 与正常 /api/nemesis 行为隔离不影响普通流；专用 admin 入口"),
      sc("B", "全用相同 route"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "admin 测试入口独立路由 = 不污染主流 + requireAdmin 守门。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 admin 操作审计",
    prompt: "admin 用特权时该不该记 audit？",
    options: [
      sc("A", "应该 + 必须更详细——admin 有更高权限「滥用」影响大；记 user.id + 操作时间 + 操作内容 + 是否绕过限流/守卫；admin 有权但同时有责——audit 是问责基础；安全合规"),
      sc("B", "不必"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "admin 操作必更详细 audit = 问责基础——合规。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 admin 特权与最小特权原则",
    prompt: "admin 默认绕过 vs 显式开关——哪个更安全？",
    options: [
      sc("A", "显式开关更安全——admin 默认按普通用户行为，登录页或专用 endpoint 显式 'enableAdminMode' 后才特权；防 admin 误操作（点错按钮发恶意请求一样被守住）；最小特权原则"),
      sc("B", "默认特权"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "显式开关 = 最小特权——防 admin 误操作。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 admin token 特殊路径",
    prompt: "若加 'X-Admin-Token: xxx' 跳所有守门——风险？",
    options: [
      sc("A", "1) token 泄露后任何人 admin（极高风险） 2) 头不像 cookie 那样自动带（需手动） 3) 必旋转 token 防泄漏；项目不用 token 模式，用 cookie session + admin role 自然继承所有 cookie 安全；token bypass 通常不推荐"),
      sc("B", "无风险"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "X-Admin-Token = 高风险 + 不继承 cookie 安全——不推荐。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 错误：admin email 大小写不一致",
    prompt: "ADMIN_EMAILS='Admin@Example.COM' 但 user 注册时用 admin@example.com——后果？",
    options: [
      sc("A", "isAdmin 内 includes 严格匹配 → 不识别为 admin → 实际 admin 用户走普通路径；DB role 也不会 promote；故障：'明明在配置但不生效'；修复：env 与 DB email 都统一小写"),
      sc("B", "无影响"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "email 大小写不一致 = isAdmin 失效——必统一小写。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 错误：硬编码 admin",
    prompt: "若代码内 const ADMINS = ['admin@x.com']—— 为什么不可？",
    options: [
      sc("A", "1) 改 admin 列表必发版（部署慢 + 风险）2) 代码 git 历史含 admin 邮箱 → 公开仓库泄露 3) 多环境用同代码但 admin 不同（env 解决） 4) 安全敏感数据不进代码；env 是必备实践"),
      sc("B", "可以"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "硬编码 admin = 发版慢 + git 历史泄露 + 多环境不灵——必 env。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 admin 操作可见性",
    prompt: "admin UI 应该有什么标记？",
    options: [
      sc("A", "Header 显示 'admin mode' 标识 + 不同颜色边框 + admin 按钮区域；让 admin 时刻清楚自己在特权状态防误操作；UX 警示设计"),
      sc("B", "无标识"),
      sc("C", "隐藏"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "admin UI 有警示标识 = 防误操作——UX 设计。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 admin 与 ban",
    prompt: "ban 的 admin 是否还能登录？",
    options: [
      sc("A", "isActiveBan 检查在 admin 检查前 → admin 被 ban 也无法登录（如人为 ban 自己测试）；rare 场景但代码必处理；admin 不豁免基础守门——只是某些场景特权"),
      sc("B", "admin 永豁免"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "admin 不豁免基础守门（ban 仍生效）——分层职责。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 添加 admin 流程",
    prompt: "如何给某用户加管理员权限？",
    options: [
      sc("A", "1) 改 ADMIN_EMAILS env 加该用户邮箱（comma append） 2) wrangler secret put 上 prod 3) 该用户下次登录自动 promote DB role 4) 立即生效；不必 SQL；声明式管理；运维友好"),
      sc("B", "SQL update"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "加 admin = env append + 用户下次登录自动 promote——声明式。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 撤销 admin",
    prompt: "如何撤销某 admin？",
    options: [
      sc("A", "1) 从 ADMIN_EMAILS 移除（自动生效后续登录） 2) DB update user set role='user' where id=X（清残留 DB role） 3) 撤销现存 sessions（admin plugin api）；env 撤 + DB 撤 + session 撤三件事——双层架构需双层清理"),
      sc("B", "改 env 即可"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "撤 admin = env + DB + session 三层清理——必须彻底。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 admin 数量",
    prompt: "项目应该有多少 admin？",
    options: [
      sc("A", "最少够运维（1-3 人）；大型团队按角色细分（content-admin/system-admin/billing-admin）；项目体量小不需要细分；总原则：最小集合需要的人；多 admin = 风险面广"),
      sc("B", "越多越好"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "admin 数最少集 + 角色细分（大团队）——最小特权。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 admin 相关 env 集中",
    prompt: "ADMIN_EMAILS 与 ADMIN_MESSAGES_URL 等同放——为什么？",
    options: [
      sc("A", "命名前缀 ADMIN_ 让运维一眼分类； .env.example 文档化所有 admin 相关 env；wrangler secret list 也分类；命名约定 = 可发现性"),
      sc("B", "随机"),
      sc("C", "无意义"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ADMIN_ 前缀分类 = env 可发现性。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 admin testing in CI",
    prompt: "CI 测试 admin 路径——怎么 mock？",
    options: [
      sc("A", "1) 设置 ADMIN_EMAILS='test@admin.com' 2) 测试时 mock session.user.email='test@admin.com' 3) 调 requireAdmin 应通过 4) 调 isAdmin 返 true；mock env + mock session 双层；不用真实 prod admin"),
      sc("B", "用真 admin"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "admin CI 测试 = mock env + mock session——隔离 prod。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 admin-bypass 整体哲学",
    prompt: "admin bypass 整体哲学？",
    options: [
      sc("A", "1) ADMIN_EMAILS env + admin role 双层（部署快 + DB 历史可审）2) isAdmin 工具函数集中判断 3) requireAdmin OR 双层最大可达 4) bypass 限流可（在 checkRateLimit 内首行短路） 5) 不 bypass 内容守卫（一致性）6) admin 操作必详细 audit（问责）7) 显式 enable admin mode > 默认特权（最小特权）8) admin 不豁免基础守门（ban 仍生效）9) 添加 admin = env append + 自动 promote 10) 撤销 = env 撤 + DB 撤 + session 撤三层 11) admin 数最小集 + 命名前缀分类 + UI 警示标识；综合：「双层 + 显式 + 一致 + 审计 + 最小集」五件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "admin bypass 11 原则——特权设计纪律。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
];
