/**
 * Real questions for site-17-guards-rate-limit / error-responses.
 * Anchor: remix/app/routes/api.nemesis.ts —— 守卫错误码体系: 401 (auth) / 403 (ban) / 405 (method) / 422 (validation) / 429 (rate-limit) / 500 (model) + NO_STORE 头 + 中文 message
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/api.nemesis.ts";
const sc = (id: string, text: string) => ({ id, text });

export const errorResponsesQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 限流码",
    prompt: "rate-limit 拒绝返 status: ____ ;——HTTP 标准限流码。",
    options: [],
    blanks: [{ id: "v", placeholder: "状态码", acceptedAnswers: ["429"] }],
    correctAnswer: { type: "fill_blank", values: { v: "429" } },
    explanation: { short: "429 Too Many Requests = HTTP 标准限流码。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 状态码全集",
    prompt: "api.nemesis 守卫链可能返的状态码与含义？",
    options: [
      sc("A", "401 未登录（auth 失败）；403 已登录但被 ban；405 method 错（非 POST）；422 body 校验失败；429 限流；500/502 模型故障；每个状态码对应不同前置 → 客户端可精确分流处理；HTTP 语义精确"),
      sc("B", "都用 500"),
      sc("C", "都用 400"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "状态码 = 守卫阶段精确化——客户端可分流处理。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 401 vs 403 用法",
    prompt: "未登录 401 vs 已登录但 ban 403——区分原因？",
    options: [
      sc("A", "401 = 重新登录可解决（客户端可引导 /auth?returnTo=...）；403 = 已认证但无权限（账号问题需联系 admin 或自然解禁）；客户端按状态码不同 UI 流程；语义精确触发不同 UX"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "401 引导登录 + 403 提示账号问题——UX 分流。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 405 method not allowed",
    prompt: "method !== 'POST' 返 405——为什么？",
    options: [
      sc("A", "405 = HTTP 标准 Method Not Allowed；通常配 Allow 头列出允许方法（如 'Allow: POST'）；客户端可看到「正确方法」；防误调；如返 404 误以为 endpoint 不存在 → 405 更精确"),
      sc("B", "用 404"),
      sc("C", "用 400"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "405 + Allow 头 = 错误方法精确反馈——HTTP 标准。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 422 vs 400",
    prompt: "body 校验失败（缺字段/类型错）—— 用 422 还是 400？",
    options: [
      sc("A", "400 Bad Request 是宽泛的「请求语法错」；422 Unprocessable Entity 更精确「语法对但语义错（业务规则不符）」；REST 实践偏好 422 表达 validation 失败；本项目 validation 返 422"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "422 = 语义错（validation）；400 = 语法错——精确分。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "backend.validation.field"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 NO_STORE_HEADERS 必备",
    prompt: "所有错误响应都附 NO_STORE_HEADERS——为什么？",
    options: [
      sc("A", "1) 错误响应是临时状态——CDN 缓 401 / 429 给已登录用户会永久错 2) 私密信息（如 user-specific 错误文案）防共享缓存 3) 写响应（4xx/5xx 多是 mutation 拒）必须 no-store；错误响应缓存是 prod 故障常见根因"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "错误响应必 NO_STORE = 防错被永久化——必备。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q7 中文 message",
    prompt: "返 { error: '请先登录后再使用 Nemesis。' }——为什么中文？",
    options: [
      sc("A", "1) 项目主要用户群中文 2) 客户端可直接展示无需翻译 3) 内部系统错误（如 500 内部）才用英文给开发者；UX 优化"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "中文 message = 用户群导向；UX 优化。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 错误响应 shape",
    prompt: "项目错误响应 shape 是？",
    options: [
      sc("A", "{ error: string } 单字段——简单；客户端 const data = await res.json(); if (data.error) showError(data.error);；不必繁琐字段；可选扩展 { error, code, details } 但项目当前简化"),
      sc("B", "复杂"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "{ error: string } 单字段 = 简单 + 通用——项目当前形态。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 4xx vs 5xx",
    prompt: "守卫错误码 4xx，模型/网关失败用 5xx——为什么？",
    options: [
      sc("A", "4xx = 客户端问题（请求格式/权限/限流）—— 客户端可改正后重试；5xx = 服务端问题（DB/Gateway 挂）—— 客户端只能等待；状态码语义反映责任方；客户端可自动 retry 5xx 但不 retry 4xx"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "4xx 客户端责任 + 5xx 服务端责任——重试策略不同。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 SSE 内 emit('error', ...)",
    prompt: "guard 通过 + 模型失败时用 SSE emit('error', ...) 而不返 JSON 5xx——为什么？",
    options: [
      sc("A", "已经开启 SSE 流（HTTP 200）—— 不能中途改 status；emit('error',...) 在流内发错误事件；客户端 nemesis-sse.client 接到后处理；流中错误必走流式协议；状态码已发出无法回头"),
      sc("B", "可以改 status"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SSE 流已开 = 错误必走 emit；status 已发不能改——协议限制。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 客户端处理 429",
    prompt: "客户端收 429——理想处理？",
    options: [
      sc("A", "1) 解析 res.json 拿 message 显示 2) 不自动 retry（限流可能持续多秒/天） 3) 禁用按钮一段时间防误点 4) 给「明天再来」类提示而非红色错误（限流是预期不是 bug）；UX + 限流意识"),
      sc("B", "立即 retry"),
      sc("C", "弹大错"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "429 = 不 retry + 友好提示——预期事件而非 bug。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 Retry-After 头",
    prompt: "429 响应可附 Retry-After 头表「多少秒后可重试」——本项目用了吗？",
    options: [
      sc("A", "未用——项目 message 字段直接含「请稍后再试」「明天再来」自然语言；Retry-After 数值更精确但客户端要解析 header；项目简化用文案；增强可加 Retry-After"),
      sc("B", "已用"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Retry-After 数值精确但项目用文案简化——可后续增强。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 错误：泄露内部信息",
    prompt: "若 catch 内 emit('error', { message: error.message })——风险？",
    options: [
      sc("A", "internal error.message 可能含 stack/path/SQL 错误细节 → 暴露内部架构（攻击者可借此构造攻击）；项目 NemesisModelError 是已知可暴露错误；其他用通用文案 'Nemesis 暂时无法响应' 隐藏内部；安全卫生"),
      sc("B", "无风险"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "暴露 raw error.message = 安全风险；通用文案 + console.error 内部 log 双层。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 错误：所有错误都 200",
    prompt: "若全部错误都返 status 200 + body { error }——后果？",
    options: [
      sc("A", "1) HTTP 语义破坏（200 = 成功） 2) 客户端无法 fetch().then(r => r.ok) 区分成功/失败 → 必须每次解析 body 检查 error 字段（繁琐易漏） 3) CDN/中间代理可能错缓「成功」响应；状态码必精确 = HTTP 协议契约"),
      sc("B", "可接受"),
      sc("C", "无差"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "全 200 = 协议破坏；状态码精确是契约。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 错误：忘 NO_STORE",
    prompt: "若错误响应漏了 NO_STORE_HEADERS——后果？",
    options: [
      sc("A", "CDN 可能缓 401/429 给后续同 URL 请求；用户登录后访问还看到 401；明天访问还看到 429；错误永久化故障；NO_STORE 必备"),
      sc("B", "正常"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "错误响应漏 NO_STORE = 错误永久化 prod 故障——必备。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 错误码与可观测",
    prompt: "怎么按状态码做监控？",
    options: [
      sc("A", "Cloudflare Analytics 按 status 看比例：401 比例高（用户没登录或 cookie 问题）→ 优化登录流；429 比例高 → 配额可能太严或攻击；5xx 比例高 → 服务故障；状态码维度反映系统健康"),
      sc("B", "无法"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Analytics 按 status 看比例 = 系统健康监控维度。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 加新错误类型",
    prompt: "若加「邮箱未验证」错误——选什么状态码？",
    options: [
      sc("A", "403 Forbidden 含义最贴近（已登录但无权限）；或 412 Precondition Failed；项目通用 403 + message 区分；不要每个错误都新发明状态码（HTTP 子集够用）"),
      sc("B", "新建 4xx"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "新错误类型 → 复用 4xx 子集 + message 区分——HTTP 够用。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 客户端通用错误处理",
    prompt: "客户端 fetch 怎么写通用错误 handler？",
    options: [
      sc("A", "1) if (!res.ok) → 解析 body.error 显示 2) if (res.status === 401) → 跳登录 3) if (res.status === 429) → 显示限流 + 禁按钮 4) if (res.status >= 500) → '稍后重试'；分流 status 处理"),
      sc("B", "全部 alert"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "客户端按 status 分流 = 用户体验关键。" },
    abilityTags: ["frontend.event.submit", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 错误日志策略",
    prompt: "什么时候 console.error vs 不打印？",
    options: [
      sc("A", "1) 4xx（业务正常拒）通常不 log（高频会噪日志）2) 5xx（服务故障）必 log 含 stack 3) 已知错误（NemesisModelError）轻 log 4) 未知 throw 必 log 详；按错误性质分级 log"),
      sc("B", "全 log"),
      sc("C", "永不 log"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "4xx 业务静默 + 5xx 必 log = 日志卫生。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 错误码与重试",
    prompt: "客户端 retry 策略按状态码？",
    options: [
      sc("A", "1) 401 → 不 retry 引导登录 2) 403 → 不 retry 提示 3) 429 → 不立即 retry（按文案/Retry-After 等待）4) 4xx 其他 → 不 retry 修请求 5) 5xx → 可 retry 1-3 次（指数退避） 6) 网络错 → 可 retry；状态码语义指导重试"),
      sc("B", "全 retry"),
      sc("C", "永不 retry"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "重试策略 = 按 status 语义；4xx 不 retry / 5xx 退避 retry。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 错误码标准化",
    prompt: "项目错误响应可考虑加 code 字段（机器友好）—— 例？",
    options: [
      sc("A", "{ error: '请先登录...', code: 'AUTH_REQUIRED' }——code 是机器可读的常量串；客户端可按 code switch 不依赖文案；i18n 时 message 翻译但 code 不变；国际化 + 解耦"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "code 字段 = 机器可读 + i18n 友好——可后续增强。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 error-responses 整体哲学",
    prompt: "守卫错误响应整体哲学？",
    options: [
      sc("A", "1) 状态码精确（401/403/405/422/429/5xx 各对应阶段）2) 4xx 客户端责任 / 5xx 服务端责任 → 重试策略指导 3) 所有错误响应附 NO_STORE_HEADERS 防错缓 4) 中文 message 直显客户端 5) SSE 流内错误用 emit 不能改 status 6) 通用文案隐藏内部细节防泄露 7) console.error 仅 5xx + 未知 8) Retry-After 可后续增强 9) code 字段可后续 i18n 解耦 10) 客户端按 status 分流处理 11) 监控按状态码维度反映系统健康；综合：「精确 + 安全 + 不缓 + 中文 + 流式协议」五件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "守卫错误响应 11 原则——HTTP 协议契约纪律。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
];
