/**
 * Real questions for site-17-guards-rate-limit / guards-capstone.
 * Anchor: remix/app/services/nemesis-guard.server.ts + nemesis-rate-limit.server.ts + api.nemesis.ts —— 守卫体系全景: auth → validation → rate-limit → guard → audit；多层职责清晰；配置 env-driven；DO 强一致；audit 可观测
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/services/nemesis-guard.server.ts";
const sc = (id: string, text: string) => ({ id, text });

export const guardsCapstoneQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 守卫链顺序",
    prompt: "守卫链顺序 = auth → validation → ____ → guard → audit。",
    options: [],
    blanks: [{ id: "v", placeholder: "守门", acceptedAnswers: ["rate-limit", "限流", "rateLimit"] }],
    correctAnswer: { type: "fill_blank", values: { v: "rate-limit" } },
    explanation: { short: "auth/validation/rate-limit/guard/audit = 五步守卫流水线。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 五层守卫职责",
    prompt: "守卫五层职责差异？",
    options: [
      sc("A", "1) auth: 「你是谁」（必登录） 2) validation: 「请求格式对吗」（语法层） 3) rate-limit: 「频次合理吗」（数值层） 4) guard: 「内容合规吗」（语义层） 5) audit: 「记录这次决策」（observability）；五层职责单一不重叠"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "auth/validation/rate-limit/guard/audit 五层 = 身份/语法/频次/语义/可观测。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/routes/api.nemesis.ts"],
  }),
  q({
    type: "single_choice", title: "Q3 顺序敏感",
    prompt: "为什么顺序固定不能换？",
    options: [
      sc("A", "1) auth 必先（无法限流匿名）2) validation 在 rate-limit 前防恶意空请求耗额度 3) rate-limit 在 guard 前防额度被守卫拒绝消耗 4) guard 在 model 前防贵 API 浪费 5) audit 在最后记完整决策；每层短路省后续；顺序反映成本/优先级"),
      sc("B", "随便换"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "顺序 = 短路成本 + 优先级——固定不可换。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 守卫层独立可测",
    prompt: "为什么每层抽 service 独立？",
    options: [
      sc("A", "1) 单测可以独立 mock 调用方传 user/message/recentMessages 验输出 2) 复用：feedback 路由可调 requireUser + checkRateLimit 不必整套 3) 修一层不影响其他 4) 框架解耦（可换 Express 不改 service）；分层 + 单一职责"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "service 独立 = 测试 + 复用 + 修隔离 + 框架解耦——分层基础。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 错误响应分流",
    prompt: "守卫各层失败状态码？",
    options: [
      sc("A", "auth 失败 → 401（未登录）/ 403（被 ban）；validation 失败 → 422；rate-limit 失败 → 429；guard 失败 → 200 + emit('done', modeReply)（不算「失败」是合规决策）；五层各自 HTTP 语义"),
      sc("B", "全 500"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "守卫失败状态码 = 各层 HTTP 语义精确——客户端可分流。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 audit 可观测设计",
    prompt: "audit 系统的设计要点？",
    options: [
      sc("A", "1) 含 GuardDecision 全字段（mode/category/reason/version 等） 2) 关联 user.id + 时间戳 3) shouldAudit 标志选择性记（避日志噪声） 4) waitUntil 后台异步不阻塞响应 5) 失败 .catch 吞错保主流程 6) D1 表持久化便于 SQL 分析；可观测但非阻塞"),
      sc("B", "无 audit"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "audit = 全字段 + 选择性 + 异步 + 容错——可观测但非阻塞。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/services/nemesis-guard-events.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q7 配置 env-driven",
    prompt: "项目守卫与限流参数全 env-driven——为什么？",
    options: [
      sc("A", "1) NEMESIS_MAX_PER_MINUTE/DAY 限流配额可调 2) NEMESIS_MAX_MESSAGE_LENGTH 守卫长度可调 3) ADMIN_EMAILS admin 列表可调 4) 部署后调参不必发版 5) 不同环境（staging/prod）可不同 → env 是唯一权威；getPositiveIntegerEnv 校验防异常；运维友好"),
      sc("B", "硬编码"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "守卫参数 env-driven = 运维可调不发版——可观测可控。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 强一致 vs 最终一致",
    prompt: "限流用 DO 强一致；audit 写 D1 最终一致——为什么不同？",
    options: [
      sc("A", "限流必须强一致（防同一秒并发请求都过限）；audit 是事后记录最终一致即可（晚几毫秒到达不影响审计准确性）；按业务的一致性需求选择存储；正确技术选型"),
      sc("B", "都强一致"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "限流强一致防 race；audit 最终一致足够——按需选存储。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 守卫数据流",
    prompt: "守卫五层间数据流？",
    options: [
      sc("A", "1) auth 输出 user 2) validation 输出 message + recentMessages 3) rate-limit 接 user 输出 allowed 4) guard 接 message + recentMessages 输出 GuardDecision 5) audit 接 user + message + decision + modelResult；每层接前层输出 + 自身职责输入；纯函数链"),
      sc("B", "全局变量"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "守卫数据流 = 每层接前层输出 + 自身职责输入——纯函数链。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 守卫与限流交互",
    prompt: "若用户请求被守卫拒（mode='REFUSE'）—— 限流计数应消耗吗？",
    options: [
      sc("A", "通常应消耗——已经在 rate-limit 后才到 guard 阶段；rate-limit 已经 +1；防恶意用户用「试探违规」探测守卫规则不付频次代价；保护守卫不被穷举"),
      sc("B", "回滚"),
      sc("C", "无影响"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "guard 拒后限流不回滚 = 防探测——位置选择反映这个意图。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 错误：守卫层间藕合",
    prompt: "若 guard 函数内调 checkRateLimit——为什么不可？",
    options: [
      sc("A", "1) 职责混乱（guard 应纯内容判断） 2) 测试 guard 必 mock 限流 3) 跨层调用让顺序变模糊 4) 重复检查可能；项目五层独立 + route 编排是清晰模式"),
      sc("B", "正常"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "层间不耦合 = 单一职责；route 编排各层——分层纪律。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 守卫的横向扩展",
    prompt: "feedback 路由也需要 auth + rate-limit——怎么复用？",
    options: [
      sc("A", "1) auth 直接调 requireNemesisUser 2) rate-limit 调 checkRateLimit 但 scope: 'feedback' 隔离配额 3) validation 单独写（不同 body shape） 4) guard 通常不需（feedback 不调模型）；按需挑层；service 独立让横向扩展容易"),
      sc("B", "全部复制"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "横向扩展 = 按需挑层 + scope 隔离配额——service 独立基础。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/routes/api.nemesis-feedback.ts"],
  }),
  q({
    type: "single_choice", title: "Q13 守卫调试",
    prompt: "用户反馈「正常对话被拒」—— 怎么调？",
    options: [
      sc("A", "1) 看 [NemesisGuard] log 含 mode/category/stage/ruleId/classifierReason 2) D1 audit 表查该用户最近请求 3) 找出 stage = RULE_GUARD（规则误中）or GEMINI（分类器问题）4) 按 stage 改规则或调 prompt 5) suggestedChange 字段可能已提示「RULE_TOO_STRICT」；audit 是调优数据基础"),
      sc("B", "无法调"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "audit log + D1 表 + suggestedChange = 守卫调优三件套。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 守卫对正向流程性能影响",
    prompt: "守卫五层对响应延迟影响？",
    options: [
      sc("A", "1) auth: 1-5ms（session 缓存命中后）2) validation: 0-1ms（纯 JS） 3) rate-limit: 5-20ms（DO RPC） 4) guard RULE 阶段: 0-5ms；GEMINI 阶段: 200-500ms（API 调） 5) audit: waitUntil 不阻塞 0ms；总加延迟 10-30ms（不调 Gemini）or 加 200-500ms（调）；guard GEMINI 是主延迟来源"),
      sc("B", "10s"),
      sc("C", "0"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "守卫总延迟 10-500ms；guard GEMINI 是主源——RULE 提前过滤是优化。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 守卫成本",
    prompt: "守卫各层成本？",
    options: [
      sc("A", "auth: D1 read（极低）；validation: 0；rate-limit: DO request（每请求 ~$0.000001）；guard RULE: 0；guard GEMINI: API call ~$0.0001-0.001/次；audit: D1 write ~$0.0000005；guard GEMINI 是主成本——RULE 拦截能省钱"),
      sc("B", "全免费"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "成本主源 = guard GEMINI；RULE 提前拦截能省 5-10x——优化方向。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 加新守卫层",
    prompt: "若加「输出守卫」（LLM 回复也守一遍）—— 改哪？",
    options: [
      sc("A", "1) action 内 callNemesisModel 后调 outputGuard(parsed.text) 2) 实现 outputGuard service（可调 OpenAI Moderation API 或自建规则） 3) 失败时 emit('error', '内容不合规') 不发原 LLM 回复 4) audit 记两次决策（input + output） 5) 顺序：input guard → model → output guard → emit；六层守卫"),
      sc("B", "改 LLM"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "加输出守卫 = action 内 model 后再调 + 双 audit——六层守卫。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 守卫 vs 安全工程",
    prompt: "守卫体系是「安全工程」吗？",
    options: [
      sc("A", "是 + 不只是——守卫是 1) 安全（防滥用/越界）2) 业务（API 体验）3) 成本（防 LLM 滥用） 4) 合规（内容审核）；多目标体系；不只防恶意用户也保系统稳定 + 成本可控；多元目标"),
      sc("B", "纯安全"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "守卫 = 安全 + 业务 + 成本 + 合规多元目标——不只防恶意。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 守卫与产品迭代",
    prompt: "如何根据 audit 数据迭代守卫规则？",
    options: [
      sc("A", "1) D1 SQL 查 mode='REFUSE' 的 category/stage 分布 2) 找 suspectedOverStrict=true 的规则审视 3) 找 suggestedChange 字段的提示 4) 找用户反馈对照 audit 行 5) 调规则或 classifier prompt 后 RULE_VERSION/CLASSIFIER_VERSION +1 6) 监控新版本指标对比；闭环"),
      sc("B", "靠感觉"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "audit → 数据驱动调整 → 版本号 + 监控对比——闭环迭代。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 守卫成熟度",
    prompt: "项目守卫体系处于什么成熟度？",
    options: [
      sc("A", "1) 多层完整守卫（auth/validation/rate-limit/guard/audit）2) 双阶段 RULE + GEMINI 成本优化 3) env-driven 配置 4) audit 完整可观测 5) 类型驱动决策（GuardDecision/14 字段）；初创-中期项目的合理设计；缺：输出守卫、A/B 实验框架、规则可视化；可后续增强"),
      sc("B", "完美"),
      sc("C", "极差"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "成熟度中等：完整核心 + 缺输出守卫/A/B/规则 UI——可增强。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 守卫文件分布",
    prompt: "守卫体系涉及的文件？",
    options: [
      sc("A", "1) services/nemesis-auth.server.ts: requireNemesisUser 2) services/nemesis-guard.server.ts: validate + guardMessage + getReply 3) services/nemesis-rate-limit.server.ts: checkNemesisRateLimit 4) services/nemesis-guard-events.server.ts: audit 写 5) lib/rate-limit.server.ts + rate-limiter-do.ts: DO 限流底层 6) routes/api.nemesis.ts: 编排层 7) nemesis/classifier-prompt.server.ts: Gemini prompt 8) nemesis/guard-replies.ts: 固定文案；8 文件协奏"),
      sc("B", "一文件"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "守卫体系 = 8 文件协奏——分层 + 单一职责架构。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 守卫与认证一致",
    prompt: "守卫体系内 user.id 来自？",
    options: [
      sc("A", "auth 服务 requireNemesisUser → better-auth getSessionCached → cookie + DB session 表查；user.id 是 better-auth 的 user.id 直接传给 rate-limit / audit；身份链路一致；不重复定义身份"),
      sc("B", "新生成"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "user.id 一来源 = better-auth session——身份链路一致。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/services/nemesis-auth.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q22 guards-capstone 整体哲学",
    prompt: "守卫 + 限流系统整体哲学？",
    options: [
      sc("A", "1) 五层流水线（auth/validation/rate-limit/guard/audit）职责单一 2) 顺序固定按短路成本 + 优先级 3) 各层 service 独立可测可复用 4) 限流双窗口 + DO 强一致 5) 守卫双阶段 RULE + GEMINI 成本平衡 6) audit 全字段 + 选择性 + waitUntil 异步 + .catch 容错 7) env-driven 配置 + getPositiveIntegerEnv 校验 8) admin 双层（env + DB role）+ 显式 enable 9) 错误响应状态码精确（401/403/422/429）+ NO_STORE 头 10) 数据流纯函数链每层接前层输出 11) 横向扩展按需挑层 + scope 隔离 12) audit 数据驱动版本迭代闭环；综合：「分层流水线 + 一致存储选型 + 双阶段成本优化 + 全可观测 + 数据驱动迭代」六件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "守卫系统 12 原则——多层守卫工程纪律。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
];
