/**
 * Real questions for site-17-guards-rate-limit / guard-module.
 * Anchor: remix/app/services/nemesis-guard.server.ts —— 351 行守门服务: GuardDecision 类型 + RULE_GUARD/GEMINI 双阶段 + buildDecision 工厂 + normalizeInput + 8 个 NemesisCategory + classifierReason 仅审计不回前端
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/services/nemesis-guard.server.ts";
const sc = (id: string, text: string) => ({ id, text });

export const guardModuleQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 模块名",
    prompt: "守门服务文件 nemesis-____ .server.ts —— 集中所有 guard 逻辑。",
    options: [],
    blanks: [{ id: "v", placeholder: "名字", acceptedAnswers: ["guard"] }],
    correctAnswer: { type: "fill_blank", values: { v: "guard" } },
    explanation: { short: "nemesis-guard.server.ts = 内容守门集中地。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 抽 service 而非 route 内联",
    prompt: "为什么 guard 逻辑放 service 而非 api.nemesis.ts 内联？",
    options: [
      sc("A", "1) 351 行复杂逻辑 inline 让 route 文件读不下去 2) guard 可独立测试（service 是纯函数）3) 多 route 可复用（feedback 路由也需要某些守门）4) 隔离 Remix 框架细节让 service 与运行时无关；分层 + 单一职责"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "guard service = 复杂 + 可测 + 复用 + 框架解耦——分层基础。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 GuardDecision 类型字段",
    prompt: "GuardDecision 含 mode/category/stage/ruleId/classifierLabel/reason/shouldAudit/suspectedOverStrict 等 14 字段——为什么这么细？",
    options: [
      sc("A", "1) mode 决定后续动作（拒绝/澄清/转 Gemini） 2) category 分类原因 3) stage 哪一阶段做的决定（规则 vs 分类器）4) reason 给审计记录 5) shouldAudit 控制是否落 D1 6) suspectedOverStrict 提示运维「这条规则可能太严」7) classifierVersion 追踪分类器版本；丰富信息让审计 + 调优 + 可观测性都齐全"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "GuardDecision 14 字段 = 决策 + 审计 + 调优三合一信息载体。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 双阶段守门",
    prompt: "stage: 'RULE_GUARD' | 'WORKERS_AI' | 'ROUTER' | 'GEMINI'——双阶段含义？",
    options: [
      sc("A", "RULE_GUARD: 字符串规则正则匹配（毫秒级，无 API 成本，覆盖明显违规）；GEMINI: Gemini 分类器（API 调用，成本，但能理解语义）；规则先跑省 API 钱 + 加速明显场景；规则未中再走 Gemini 兜底；分级守门"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "RULE 快速便宜先 + GEMINI 兜底贵但精——双阶段优化。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 NemesisMode 三态",
    prompt: "NemesisMode = 'PASS_TO_GEMINI' | 'CLARIFY' | 'SAFE_BOUNDARY' | 'REFUSE'——含义？",
    options: [
      sc("A", "PASS_TO_GEMINI: 让 Gemini 正常回复；CLARIFY: 要求用户澄清不直接拒；REFUSE: 直接拒绝并固定文案；SAFE_BOUNDARY 仅历史审计读用（守卫不再 emit）；三态决策 + 一历史"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三态决策 PASS/CLARIFY/REFUSE + SAFE_BOUNDARY 历史——清晰分级。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 NemesisCategory 8 类",
    prompt: "PROMPT_EXTRACTION/JAILBREAK/PRIVACY_PROBE/OWNER_BOUNDARY/PUBLIC_AFFAIRS_INFERENCE/NORMAL/UNKNOWN/TOO_LONG——为什么这些？",
    options: [
      sc("A", "覆盖项目主要风险面：1) 提示词攻击 2) 越狱尝试 3) 隐私窥探 4) 越界请求作者私事 5) 公共事务推测 6) 正常对话 7) 未知 8) 超长；闭集精确分类便于审计 + 决策路由 + 后期调优各类比例"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "8 闭集 category = 项目特定风险分类——完整覆盖。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 NemesisGuardLabel 扩展",
    prompt: "NemesisGuardLabel 比 NemesisCategory 多 ALLOW_NEMESIS_RELATED/CSAM_OR_MINOR_SEXUAL/HARD_BLOCKED 等——为什么？",
    options: [
      sc("A", "Label 是 Gemini 分类器的更细输出标签（项目设计的提示词输出空间）；Category 是规范化后存 D1 的简化口径；分类器知道更多但项目按 Category 路由；Label vs Category = 原始 vs 规范"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Label = 分类器原始输出 + Category = 项目规范——两层映射。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/nemesis/classifier-prompt.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q8 normalizeInput",
    prompt: "function normalizeInput(message) { return message.trim().replace(/\\s+/g, ' '); }——为什么先规范化？",
    options: [
      sc("A", "1) trim 去首尾空格 2) /\\s+/g→' ' 多空白合一 3) 后续规则匹配/Gemini 看到的都是同一种「干净」字符串 4) 防绕过（攻击者插大量空白让规则不中）；输入规范化是守门第一步"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "normalizeInput = 守门第一步防绕过——规范化标配。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "backend.validation.field"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 buildDecision 工厂",
    prompt: "function buildDecision(input) { const calledGemini = input.mode === 'PASS_TO_GEMINI'; return { ...input, calledGemini, ruleVersion: RULE_VERSION, classifierVersion: ... }; }——什么模式？",
    options: [
      sc("A", "工厂函数补全样板字段：calledGemini 派生 + 版本号常量；调用方只填业务字段不必每次写版本/派生字段；保证字段完整 + 版本一致；样板剥离"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "buildDecision 工厂 = 样板字段统一补 + 版本一致——DRY。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 RULE_VERSION 常量",
    prompt: "const RULE_VERSION = 'nemesis-guard-v0.3'; const CLASSIFIER_VERSION = 'nemesis-classifier-gemini-v2';——为什么版本号？",
    options: [
      sc("A", "审计记录里带版本号 → 后期分析「v0.3 这条规则的触发率」「v0.2 vs v0.3 误判率对比」；规则迭代时新数据用新版本号 → 历史数据按版本分桶；A/B 验证 + 回归测试基础"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "版本号常量 = 审计可分桶 + A/B 对比基础。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 DEFAULT_MAX_MESSAGE_LENGTH",
    prompt: "DEFAULT_MAX_MESSAGE_LENGTH = 1000 + getMaxMessageLength() 从 env 读——为什么可配？",
    options: [
      sc("A", "1) 默认 1000 字符够日常对话 2) 运维可调 NEMESIS_MAX_MESSAGE_LENGTH env 不重新部署 3) 超长文判 TOO_LONG category 返 REFUSE 防滥用 token；env 配置 + 默认值的常见模式"),
      sc("B", "硬编码"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "默认 + env 覆盖 = 运维可调不必发版——常见配置模式。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 MAX_RECENT_MESSAGES = 10",
    prompt: "MAX_RECENT_MESSAGES = 10——为什么这个数？",
    options: [
      sc("A", "上下文取最近 10 条够 Gemini 理解话题流；超过 10 条会让 prompt 过长 + 成本高 + 早期消息无关性大；裁剪 = token 成本 vs 上下文质量平衡；10 是经验值"),
      sc("B", "随机"),
      sc("C", "无意义"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "10 条 = 上下文 vs token 成本平衡——经验值。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 NemesisRequestValidationResult discriminated union",
    prompt: "type Result = { ok: true; message; recentMessages } | { ok: false; status; payload };——这种 union 的好处？",
    options: [
      sc("A", "TypeScript discriminated union——调用方 if (result.ok) 后编译器自动收窄到成功分支（拿 message/recentMessages）；ok:false 分支拿 status/payload；零类型断言；类型驱动的分流"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "discriminated union = 编译器自动收窄——零断言分流。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 SuggestedChange 字段",
    prompt: "SuggestedChange = 'NO_CHANGE' | 'RULE_TOO_STRICT' | 'CHECK_CLASSIFIER_PROMPT'...——这字段什么用？",
    options: [
      sc("A", "守门记录里给运维「下一步建议」——比如规则中拒了但分类器认为正常 → suggestedChange:'RULE_TOO_STRICT'；运维定期 query 这个字段筛出建议；闭环改进的元数据"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SuggestedChange = 自己给运维的下一步指引——闭环改进。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 SAFE_BOUNDARY 历史兼容",
    prompt: "/** SAFE_BOUNDARY kept only for reading legacy audit rows — guard no longer emits it. */——什么含义？",
    options: [
      sc("A", "v0.x 时期守门会 emit SAFE_BOUNDARY mode；v0.3 不再 emit 但旧 D1 审计行里仍有；类型保留让旧行 deserialize 不出错；新代码不会产生但能读旧；schema 兼容"),
      sc("B", "废"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SAFE_BOUNDARY 仅历史读 = schema 演进时旧数据兼容。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 公开导出函数",
    prompt: "guard 模块对外暴露 validateNemesisRequest / guardNemesisMessage / getNemesisModeReply 三函数——为什么这样划分？",
    options: [
      sc("A", "validateNemesisRequest: 解析 + 校验 body 结构；guardNemesisMessage: 真正守门返 GuardDecision；getNemesisModeReply: 按 mode 返固定文案；三层 API：解析/守门/响应；route 按需调"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三层 API：validate/guard/reply——route 按需调。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 classifierReason 仅审计",
    prompt: "guard.classifierReason 不回前端只进 D1——为什么这样？",
    options: [
      sc("A", "1) 分类器内部推理可能含 prompt 残片暴露提示词（隐私）2) reason 给运维调试不必给用户 3) 用户体验只需「拒绝」结果不必「为什么拒」（反而引导用户改 prompt 绕过）；隐私 + 安全 + UX 三层考虑"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "classifierReason 仅审计 = 隐私 + 安全 + UX 三层考虑。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 守门服务测试",
    prompt: "怎么单测 guard 模块？",
    options: [
      sc("A", "1) mock callGeminiClassifier 控制返回 2) 输入各类 message 调 guardNemesisMessage 验输出 3) 验明显违规规则中（不调 Gemini） 4) 验正常输入走 Gemini 路径 5) 验超长输入返 TOO_LONG 6) 验 shouldAudit 决策；分支覆盖 + mock"),
      sc("B", "无法测"),
      sc("C", "e2e only"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "guard 测试 = mock 分类器 + 各类输入 + 分支覆盖。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 加新 category",
    prompt: "新加 'COPYRIGHT_INFRINGEMENT' 类——改哪里？",
    options: [
      sc("A", "1) NemesisCategory union 加该字面量 2) VALID_CATEGORIES Set 加 3) classifier-prompt.server.ts 教 Gemini 识别该类 4) guard-replies 加对应固定文案 5) buildDecision 流程内可触发该 category 6) 历史审计行查询适配；闭集类型加成员需多处协同"),
      sc("B", "只改 type"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "加 category = 类型 + Set + Gemini prompt + 文案 + 路由——多处。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 守门和 LLM 输出关系",
    prompt: "guardNemesisMessage 是输入守门——LLM 输出还要再守一遍吗？",
    options: [
      sc("A", "可考虑——输入守门不能保证 LLM 不被绕过吐有害内容；输出守门双层防御（如 OpenAI Moderation API 等）；本项目暂未实现但是常见加固方向；生产 AI 应用建议双层"),
      sc("B", "无需"),
      sc("C", "等价"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "输入 + 输出双层守门 = 生产 AI 应用加固方向。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 守门 vs 限流的角色",
    prompt: "guard 与 rate-limit 的区别？",
    options: [
      sc("A", "guard 关心「内容是否合规」（语义层）；rate-limit 关心「频次是否超额」（数值层）；guard 失败 → 内容被拒但允许重试；rate-limit 失败 → 频次抢锁直接 429；两层独立但配合用"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "guard = 内容层；rate-limit = 频次层——独立但配合。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/services/nemesis-rate-limit.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q22 guard-module 整体哲学",
    prompt: "nemesis-guard.server.ts 整体哲学？",
    options: [
      sc("A", "1) 守门集中地（一个文件 351 行）便于审计 2) 双阶段（RULE 快 + GEMINI 兜底）成本与精度平衡 3) GuardDecision 14 字段含决策 + 审计 + 调优三类信息 4) NemesisCategory 8 闭集精确分类 5) Label vs Category 两层映射 6) buildDecision 工厂统一版本号 + 派生字段 7) normalizeInput 防绕过 8) classifierReason 仅审计不回前端 9) discriminated union validateRequest 类型驱动分流 10) suggestedChange 闭环改进元数据 11) SAFE_BOUNDARY 历史兼容 12) RULE_VERSION/CLASSIFIER_VERSION 审计可分桶；综合：「集中 + 分级 + 类型化决策 + 审计完整 + 历史兼容」五件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "guard-module 12 原则——内容守门服务层纪律。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
];
