/**
 * Real questions for site-17-guards-rate-limit / rate-limit.
 * Anchor: remix/app/services/nemesis-rate-limit.server.ts —— 20 行包装：checkRateLimit + 双窗口（minute/day）+ env 可调；底层走 Durable Object（rate-limiter-do.ts）
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/services/nemesis-rate-limit.server.ts";
const sc = (id: string, text: string) => ({ id, text });

export const rateLimitQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 默认每分钟",
    prompt: "DEFAULT_MAX_PER_MINUTE = ____ ;——分钟窗口默认配额。",
    options: [],
    blanks: [{ id: "v", placeholder: "数字", acceptedAnswers: ["5"] }],
    correctAnswer: { type: "fill_blank", values: { v: "5" } },
    explanation: { short: "5 次/分钟 = Nemesis 默认 minute 配额。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 双窗口设计",
    prompt: "为什么同时有 maxPerMinute (5) + maxPerDay (50)？",
    options: [
      sc("A", "1) 分钟窗口防瞬时刷屏（防机器人）2) 日窗口防长期滥用（控总成本）3) 单窗口的不足：仅分钟会让用户全天慢慢刷光成本；仅日会让用户瞬时把日额度用完；双窗口配合"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "双窗口 = 防瞬时刷屏 + 控长期成本——单窗不够。" },
    abilityTags: ["backend.rateLimit", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 key 派生",
    prompt: "const key = user.id || user.email || 'unknown';——为什么这种链式 fallback？",
    options: [
      sc("A", "user.id 是稳定主键（首选）；email 兜底（极端情况下 id 未必有）；'unknown' 防 undefined 防崩；key 用于 DO 内部找配额计数器；身份识别 + 容错"),
      sc("B", "随机"),
      sc("C", "无意义"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "id || email || 'unknown' = 身份链式 fallback——容错。" },
    abilityTags: ["backend.rateLimit", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 scope: 'nemesis'",
    prompt: "checkRateLimit({ key, scope: 'nemesis', ... })——scope 作用？",
    options: [
      sc("A", "scope 命名空间隔离不同业务的配额：nemesis chat 与 magicLink 邮件 + 评论提交各自独立计数；同一 user 在 nemesis scope 用尽不影响 magicLink 还能用；多业务共享 DO 但配额隔离"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "scope = 多业务配额隔离——同 DO 不同 namespace。" },
    abilityTags: ["backend.rateLimit", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/rate-limit.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q5 getPositiveIntegerEnv",
    prompt: "function getPositiveIntegerEnv(name, fallback) { const value = Number(getEnvVar(name)); return Number.isFinite(value) && value > 0 ? value : fallback; }——为什么写这个？",
    options: [
      sc("A", "1) env 可能是空字符串/字母 → Number('') = 0 / Number('abc') = NaN 2) Number.isFinite 排除 NaN/Infinity 3) > 0 排除 0 和负数 4) 都不通过用 fallback；env 输入校验防异常配置"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "env 校验 = isFinite + >0 + fallback——防异常配置。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "backend.validation.field"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 底层走 Durable Object",
    prompt: "checkRateLimit 底层走的是？",
    options: [
      sc("A", "Cloudflare Durable Object（rate-limiter-do.ts）—— sqlite 持久化计数器；DO 单例保证同 key 操作强一致（不会跨节点 race）；分布式限流的标准实现；Workers 上比 KV 强一致"),
      sc("B", "KV"),
      sc("C", "全局变量"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "DO 单例 + sqlite = 强一致分布式限流——Workers 标准。" },
    abilityTags: ["backend.rateLimit", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/rate-limiter-do.ts"],
  }),
  q({
    type: "single_choice", title: "Q7 KV 不能限流",
    prompt: "为什么不用 KV 做限流？",
    options: [
      sc("A", "KV 是最终一致——多节点 read+write 之间有窗口期 race（两次同时读 4 都过限是 5）；DO 强一致单实例处理写入；限流必须强一致防 race；KV 不合适"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "KV 最终一致 → race；DO 强一致 → 限流唯一选——必 DO。" },
    abilityTags: ["backend.rateLimit", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 rate-limit 返回",
    prompt: "checkRateLimit 返 { allowed, reason, ... }——reason 取值？",
    options: [
      sc("A", "reason 区分「为什么拒」：'minute' = 分钟超额（建议短时间重试） 'day' = 日超额（建议明天）；route 内根据 reason 给不同文案 → UX 友好；细化失败原因"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "reason 区分 minute vs day = UX 文案精确化。" },
    abilityTags: ["backend.rateLimit", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/routes/api.nemesis.ts"],
  }),
  q({
    type: "single_choice", title: "Q9 全局 vs 用户限流",
    prompt: "项目同时有 IP 全局限流（magicLink）+ 用户限流（nemesis）——为什么？",
    options: [
      sc("A", "IP 限流防匿名滥用（注册前阶段）；user 限流防已登录用户消耗成本；不同业务对应不同身份层级的限制；多层防御"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "IP + user 限流 = 多身份层级防滥用——分层。" },
    abilityTags: ["backend.rateLimit", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 滑动窗口 vs 固定窗口",
    prompt: "rate-limit 的窗口策略选择？",
    options: [
      sc("A", "固定窗口（minute/day 整点重置）实现简单但有「窗口边界刷流」漏洞（59:59 + 00:01 共发 2N 个）；滑动窗口（rolling 60s）更准确但实现复杂；项目用固定窗口（实现简单 + 5 次/分钟边界影响有限）"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "固定 vs 滑动 = 简单 vs 精确——项目选固定。" },
    abilityTags: ["backend.rateLimit", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 token bucket vs leaky bucket",
    prompt: "限流算法 token bucket 与 leaky bucket 区别？",
    options: [
      sc("A", "token bucket: 桶中累积令牌（突发可消费）；leaky bucket: 固定速率漏水（平滑输出）；token 允许突发 leaky 削峰；项目计数器模式接近 token bucket（窗口内积累配额）"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "token = 允许突发；leaky = 削峰平滑——选择按业务需求。" },
    abilityTags: ["backend.rateLimit", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 user.id || email——可能撞键吗",
    prompt: "若 user.id = 'abc' 而另一 user.email = 'abc'——会同 key 撞限额吗？",
    options: [
      sc("A", "理论可能但实际极端罕见——id 通常是 uuid/hash 长串，email 含 @ 不会撞；项目接受这个低概率风险换实现简单；严苛场景可改 'user:'+id || 'email:'+email 加前缀；命名空间防撞"),
      sc("B", "永不撞"),
      sc("C", "无影响"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "id/email 撞键极罕但理论存在 → 严苛场景加前缀。" },
    abilityTags: ["backend.rateLimit", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 rate-limit 在 action 中的位置",
    prompt: "api.nemesis action 内 rate-limit 在 validation 后 + guard 前——为什么这个位置？",
    options: [
      sc("A", "1) validation 之前会浪费 limit 计数（恶意空请求耗用户额度）2) guard 之后会让明显违规也消耗额度（不合理）3) 在 validation 后 guard 前刚好——确认请求合法 + 在贵的 Gemini 调用前；位置是 「确认 + 拒短路」 平衡"),
      sc("B", "无所谓"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "validation 后 + guard 前 = 确认请求合法但贵调用前——位置敏感。" },
    abilityTags: ["backend.rateLimit", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/routes/api.nemesis.ts"],
  }),
  q({
    type: "single_choice", title: "Q14 限流响应 429 + 文案",
    prompt: "限流失败 reason='minute' 返 '请求过于频繁，请稍后再试'；reason='day' 返 '今天的 Nemesis 使用次数已达上限，明天再来吧'——为什么这种？",
    options: [
      sc("A", "1) minute → 提示「稍后」（用户秒级重试可解）2) day → 提示「明天」（明确时间感更友好）3) 不暴露具体配额数字（防探测） 4) 中文文案符合用户 → UX 友好"),
      sc("B", "暴露配额"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "限流文案 = 时间感 + 不暴露配额——UX + 安全。" },
    abilityTags: ["backend.rateLimit", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 错误：peek vs consume",
    prompt: "若用 peekRateLimit 不 consume—— 后果？",
    options: [
      sc("A", "peek 只看不计数 → 用户可无限请求（每次都「还有额度」）→ 限流失效；checkRateLimit 默认 consume；不要混淆 peek（仅查询） 与 check（查 + 占用）；语义重要"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "peek 只查不计数；check 查 + 占用——必区分。" },
    abilityTags: ["backend.rateLimit", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 错误：DO miss",
    prompt: "如果 DO RPC 偶尔失败——服务该 fail open 还是 fail closed？",
    options: [
      sc("A", "fail open（让通过）——基础设施故障不能让业务全挂；用户访问不应因限流故障被拒；可在 catch 内 log + 允许；fail closed 给极敏感场景才考虑（如付费 API 防超额）"),
      sc("B", "永 fail closed"),
      sc("C", "无所谓"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "限流故障 → fail open 保业务可用——除非超敏感场景。" },
    abilityTags: ["backend.rateLimit", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 监控限流",
    prompt: "怎么观测 rate-limit 触发情况？",
    options: [
      sc("A", "1) console.warn 在限流命中时打 log 含 user/scope/reason 2) recordNemesisGuardEvent 类的审计也可记 3) Cloudflare Analytics 看 429 比例 4) 单独 D1 表存触发记录便于查特定用户；多维度可观测"),
      sc("B", "无监控"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "限流监控 = log + 审计 + Analytics + 表——多维度。" },
    abilityTags: ["backend.rateLimit", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 配额可见",
    prompt: "用户应该看到剩余配额吗？",
    options: [
      sc("A", "可选——展示「今天还剩 X 次」对正常用户友好但给恶意用户精确探测；常见折中：剩余少时（如 < 5）才展示；项目当前不展示（保守）；UX 与安全权衡"),
      sc("B", "永远展示"),
      sc("C", "永不"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "配额展示 = UX vs 探测攻击权衡；保守不展或低剩才展。" },
    abilityTags: ["backend.rateLimit", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 加新限流业务",
    prompt: "新加 /api/comments 评论限流——流程？",
    options: [
      sc("A", "1) 在 services 加 comments-rate-limit.server.ts 类似 nemesis-rate-limit 包装层 2) scope 用 'comments' 隔离 3) 配 COMMENTS_MAX_PER_MINUTE/DAY env vars 4) action 内调 checkRateLimit 拒 429 5) 客户端处理 429；模板化扩展"),
      sc("B", "全局变量"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "新限流业务 = 包装层模板 + scope + env + action 调；模板化。" },
    abilityTags: ["backend.rateLimit", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 IP 还是用户限流",
    prompt: "Nemesis chat 用「user 限流」而非「IP 限流」——动机？",
    options: [
      sc("A", "1) 用户必登录（已有 user.id） 2) IP 限流误伤共享 IP（公司/学校）3) 限流跟着用户而非节点更精准 4) 登录前阶段（如 magic-link）才用 IP 限；按业务身份选限流维度"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "登录后 user 限流；登录前 IP 限流——按身份阶段。" },
    abilityTags: ["backend.rateLimit", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 admin 不限流",
    prompt: "管理员可绕过限流——怎么实现？",
    options: [
      sc("A", "checkNemesisRateLimit 内可加 if (isAdmin(user.email)) return { allowed: true };——admin 不消耗配额；测试 + 应急时方便；本项目可选实现；admin 特权设计"),
      sc("B", "硬不可绕"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "admin 短路绕限流 = 测试 + 应急——常见特权。" },
    abilityTags: ["backend.rateLimit", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 rate-limit 整体哲学",
    prompt: "rate-limit 整体哲学？",
    options: [
      sc("A", "1) 双窗口（minute 防瞬时 + day 控总量）2) DO 单例强一致防 race 3) scope 命名空间隔离不同业务 4) key 链 fallback（id || email || 'unknown'） 5) env getPositiveIntegerEnv 校验防异常配置 6) 位置在 validation 后 + guard 前 7) reason 区分文案精确化 UX 8) 故障 fail open 保业务 9) 配额展示 vs 探测安全权衡 10) IP 限流（登录前）+ user 限流（登录后）按身份分层 11) 监控多维度（log + 审计 + Analytics）；综合：「双窗 + 强一致 + scope 隔离 + 容错 + 分层」五件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "rate-limit 11 原则——限流服务层纪律。" },
    abilityTags: ["backend.rateLimit", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
];
