/**
 * Real questions for site-01-repo-map / app-tree.
 *
 * Anchor: remix/app/ 目录结构。
 *   - components/: auth/ common/ error/ game/ home/ messages/ music/ nemesis/ transitions/ ui/
 *   - services/:   nemesis-*.server.ts (auth / guard / guard-events / query-router / rate-limit / reply / nemesis)
 *   - lib/:        auth.server / db.server / messages.server / rate-limit.server / rate-limiter-do / nemesis-*.server / nemesis-*.client / auth-client.client / theme-server / cache-headers.server …
 *   - utils/:      cloudflare-env.server / theme.server / request.server / seo
 *   - types/, hooks/, data/, generated/, nemesis/, styles/, routes/
 * 学习目标: 给一个职责，能说出它落在哪个子目录；给一个文件名后缀（.server / .client），能说出它的边界含义。
 *
 * 题目数: 22。
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/";

export const appTreeQuestions: RealQ[] = [
  q({
    type: "single_choice",
    title: "Q1 routes 目录的角色",
    prompt: "remix/app/routes/ 目录承担什么职责？",
    options: [
      { id: "A", text: "URL → 处理函数的入口（loader / action / 默认导出 UI）；文件名决定 URL" },
      { id: "B", text: "保存可复用的样式 token" },
      { id: "C", text: "存放 D1 migration SQL" },
      { id: "D", text: "Cloudflare Worker 配置文件" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "routes/ 是 React Router 的真相来源——文件名决定 URL，loader/action/Default 决定行为。",
      detail: "remix/app/routes/ 下的每个 .tsx/.ts 文件对应一条路由：_index.tsx → '/'，gallery.tsx → '/gallery'，api.auth.$.ts → '/api/auth/*' splat。文件名规则与 React Router v2 对齐，点号代表层级、$ 代表动态参数、_index 代表父级 layout 的索引子路由。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/routes/"],
  }),
  q({
    type: "single_choice",
    title: "Q2 services vs lib 的差别",
    prompt: "remix/app/services/ 和 remix/app/lib/ 都装服务端代码，差别在哪？",
    options: [
      { id: "A", text: "services/ 装跨路由复用的业务模块（Nemesis 聊天链路、guard 守门、reply 拼装）；lib/ 装更底层的通用 util（auth / db / cache-headers / messages）" },
      { id: "B", text: "services/ 必须有数据库访问，lib/ 不允许" },
      { id: "C", text: "services/ 是新写的，lib/ 是即将删除的旧代码" },
      { id: "D", text: "完全等价，目录划分纯属习惯" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "services/ = 业务编排层；lib/ = 底层 util 与适配器。改业务规则去 services/，改基础设施去 lib/。",
      detail: "services/ 全是 nemesis-*.server.ts，每个文件是一个业务子能力（auth / guard / guard-events / query-router / rate-limit / reply / nemesis 主入口）。lib/ 里既有 auth.server / db.server / messages.server 这种通用基础，又有 nemesis-ai-gateway.server / nemesis-sse.server 这种已经偏底层的 nemesis util——分层是按「业务厚度」而非「是否访问 DB」。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "server",
    touchedFiles: ["app/services/", "app/lib/"],
  }),
  q({
    type: "multi_choice",
    title: "Q3 components/ 的子分区",
    prompt: "remix/app/components/ 下面真实存在的子目录是？（多选）",
    options: [
      { id: "auth", text: "auth/（登录弹窗、Google one-tap）" },
      { id: "error", text: "error/（NotFound404、RouteErrorBoundary）" },
      { id: "transitions", text: "transitions/（RouteTransition 等过渡动画）" },
      { id: "common", text: "common/（ClientOnly 等无领域包裹器）" },
      { id: "schema", text: "schema/（zod 校验定义）" },
      { id: "hooks", text: "hooks/（useEffect 等自定义 hook）" },
    ],
    correctAnswer: { choiceIds: ["auth", "error", "transitions", "common"] },
    explanation: {
      short: "components/ 真实子目录：auth / common / error / game / home / messages / music / nemesis / transitions / ui。schema 与 hooks 不在这里。",
      detail: "schema/ 在这个项目里不存在；hooks/ 在 app/hooks/ 而不是 components/hooks/。这种「看似合理但其实没有」的目录是 AI 改坏代码的高频出处——它会编出 components/schema/foo.ts 然后 import 失败。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "client",
    touchedFiles: ["app/components/"],
  }),
  q({
    type: "single_choice",
    title: "Q4 .server.ts 后缀含义",
    prompt: "文件名以 `.server.ts` 结尾（如 `app/lib/db.server.ts`）在 React Router 下意味着什么？",
    options: [
      { id: "A", text: "Vite/Remix 编译时只把它放进 server bundle，绝不打包进客户端 JS——里面的 secret / D1 binding 不会泄漏到浏览器" },
      { id: "B", text: "只是命名约定，没有任何编译期作用" },
      { id: "C", text: "编译时被忽略，只用于本地开发" },
      { id: "D", text: "标记此文件需要在 wrangler.toml 单独声明" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: ".server.ts 是 Remix/RR7 的编译器边界标记——保证它不进客户端 bundle。",
      detail: "如果一个 .server.ts 文件被客户端代码 import，构建会直接报错。这是为什么 db.server.ts、auth.server.ts、nemesis.server.ts 一定带 .server——它们持有 D1 binding、API key、session 解码逻辑，泄漏到浏览器就是 RCE 风险。",
    },
    abilityTags: ["code.position.handler", "backend.session.cookie"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "server",
    touchedFiles: ["app/lib/db.server.ts", "app/lib/auth.server.ts"],
  }),
  q({
    type: "single_choice",
    title: "Q5 .client.ts 后缀含义",
    prompt: "文件名以 `.client.ts(x)` 结尾（如 `app/lib/auth-client.client.ts`、`app/components/auth/GoogleOneTap.client.tsx`）意味着？",
    options: [
      { id: "A", text: "强制只在浏览器执行，server bundle 里被替换为空 stub——避免 SSR 阶段调用 window/document 报错" },
      { id: "B", text: "立即在水合前执行" },
      { id: "C", text: "不能 import 任何 React 组件" },
      { id: "D", text: "等同 'use client' 指令" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: ".client 是 Remix/RR7 编译器把客户端专用代码隔离出去的标记。",
      detail: "Google one-tap 与 better-auth 客户端 SDK 都依赖 window/document，SSR 阶段执行就会炸。.client 后缀让它们在 server bundle 里被替换为空，只在浏览器水合后才真正加载——所以 root.tsx 用 lazy(() => import('GoogleOneTap.client')) + Suspense 包它。",
    },
    abilityTags: ["code.position.handler", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "client",
    touchedFiles: ["app/lib/auth-client.client.ts", "app/components/auth/GoogleOneTap.client.tsx"],
  }),
  q({
    type: "true_false",
    title: "Q6 routes 是否可以放纯 util",
    prompt: "把一个共享的格式化函数放进 `app/routes/` 是合理做法，反正 React Router 也会扫这个目录。",
    correctAnswer: { type: "true_false", value: false },
    explanation: {
      short: "false——routes/ 下的文件都被当成路由模块，纯 util 应去 lib/ 或 utils/。",
      detail: "React Router v7 框架模式会把 routes/ 下面每个文件当作路由生成 URL 与代码分裂点。一个不导出 default/loader/action 的 util 文件会污染路由树、可能导致编译期或运行期报错；归处是 app/lib/ 或 app/utils/。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "shared",
    touchedFiles: ["app/routes/", "app/lib/", "app/utils/"],
  }),
  q({
    type: "single_choice",
    title: "Q7 utils vs lib",
    prompt: "remix/app/utils/ 与 remix/app/lib/ 在这个项目里如何区分？",
    options: [
      { id: "A", text: "utils/ 只装 4 个文件（cloudflare-env.server / theme.server / request.server / seo）——都是请求 / 环境 / SEO 元数据这类'框架适配层'；lib/ 装与业务相关的更多东西" },
      { id: "B", text: "utils/ 只能放纯函数；lib/ 只能放 class" },
      { id: "C", text: "两者由不同团队维护，无技术差别" },
      { id: "D", text: "utils/ 是测试脚手架，不会进 production bundle" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "utils/ 是框架适配层（env / theme / request / seo）；lib/ 是业务+基础设施。",
      detail: "实际看 utils/ 只有 4 个文件：cloudflare-env.server.ts（运行时 env 读取）、theme.server.ts（主题 cookie）、request.server.ts（client IP 等）、seo.ts（meta 生成）。它们的共同点是「不携带业务，只是把 framework / runtime 的能力适配成项目可用的 API」。lib/ 则有 auth、db、messages、nemesis-* 等业务相关文件。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "server",
    touchedFiles: ["app/utils/", "app/lib/"],
  }),
  q({
    type: "fill_blank",
    title: "Q8 静态资源目录",
    prompt: "Cloudflare Workers 上的 React Router 项目，构建产物（JS chunk + 静态资产）打包到 ____ 目录后由 [assets] binding 提供。",
    options: [],
    blanks: [{ id: "v", placeholder: "目录名", acceptedAnswers: ["build/client", "./build/client", "build", "build/"] }],
    correctAnswer: { type: "fill_blank", values: { v: "build/client" } },
    explanation: {
      short: "build/client 是默认产物目录，在 wrangler.toml 里以 [assets] directory='./build/client' 暴露。",
      detail: "remix/wrangler.toml 写：[assets] directory='./build/client' binding='ASSETS' run_worker_first=true。Worker 收到请求时先看是否命中静态资产，再交给 entry.server.tsx 渲染。run_worker_first=true 让 Worker 拦截后可以决定是否回退到资产。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "server",
    touchedFiles: ["wrangler.toml", "build/client"],
  }),
  q({
    type: "multi_choice",
    title: "Q9 顶层 Cloudflare bindings",
    prompt: "remix/wrangler.toml 在 production 上配置了哪些真实的 Cloudflare 绑定？（多选）",
    options: [
      { id: "DB", text: "D1 数据库（binding=DB, database_name=app-db）" },
      { id: "RL", text: "Durable Object 限流（binding=RATE_LIMITER, class=RateLimiterDO）" },
      { id: "R2", text: "R2 媒体桶（binding=MEDIA_BUCKET, bucket_name=gregorwang）" },
      { id: "AI", text: "Workers AI 绑定（binding=AI）" },
      { id: "KV", text: "KV namespace（binding=CONFIG_KV）" },
      { id: "Q", text: "Queues 异步队列（binding=JOB_QUEUE）" },
    ],
    correctAnswer: { choiceIds: ["DB", "RL", "R2", "AI"] },
    explanation: {
      short: "DB / RATE_LIMITER / MEDIA_BUCKET / AI 四个绑定真实存在；KV 与 Queue 在本项目没用。",
      detail: "wrangler.toml 顶部 30 行写得清楚。AI 绑定虽然存在但本项目并不用它做推理——真实推理走 Cloudflare AI Gateway（NEMESIS_AI_GATEWAY_ID）做反向代理上游 Gemini / DeepSeek / Grok。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "server",
    touchedFiles: ["wrangler.toml"],
  }),
  q({
    type: "position_judgement",
    title: "Q10 新增「评论 fetch util」应该放哪",
    prompt: "需要新增一个'对当前用户当前页签格式化展示评论'的纯前端函数，最稳妥的落点？",
    options: [
      { id: "lib", text: "app/lib/format-comment.ts（纯 util，可前后端共用）", locationHint: "app/lib/" },
      { id: "components", text: "app/components/comments/format.ts（绑定具体组件）", locationHint: "app/components/comments/" },
      { id: "routes", text: "app/routes/comments.format.ts（让路由扫描接管）", locationHint: "app/routes/" },
      { id: "services", text: "app/services/format-comment.server.ts", locationHint: "app/services/" },
    ],
    correctAnswer: { positionId: "lib" },
    explanation: {
      short: "纯前端 util 归 app/lib/（不带 .server）。",
      detail: "判断顺序：是否触碰 D1 / secret / fs？→ 否 → 不挂 .server。是否仅一个组件用？→ 否 → 不挂 components/。是否是路由？→ 否 → 不挂 routes/。剩下就是 lib/ 或 utils/，业务相关用 lib/、框架适配用 utils/。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "shared",
    touchedFiles: ["app/lib/", "app/components/", "app/routes/"],
  }),
  q({
    type: "position_judgement",
    title: "Q11 新增「用 Stripe SDK 创建 checkout」应该放哪",
    prompt: "需要新增一个走 Stripe 创建 checkout session 的服务端函数（持 secret），最稳妥的落点？",
    options: [
      { id: "services", text: "app/services/stripe.server.ts（业务编排层）", locationHint: "app/services/" },
      { id: "lib", text: "app/lib/stripe.server.ts（基础适配层）", locationHint: "app/lib/" },
      { id: "routes", text: "app/routes/api.stripe-checkout.ts（直接当 API 路由 + 内联逻辑）", locationHint: "app/routes/" },
      { id: "utils", text: "app/utils/stripe.server.ts（运行时适配）", locationHint: "app/utils/" },
    ],
    correctAnswer: { positionId: "lib" },
    explanation: {
      short: "Stripe SDK 是基础适配层，归 lib/——上面再写 services/ 或 routes/ 来编排。",
      detail: "Stripe SDK 没有自身业务规则，只是把 HTTP 包成 TS 类型，归 lib/。如果之后还要拼装「创建 checkout + 写 D1 audit + 推送邮件」这条链，再写 services/billing.server.ts 调 lib/stripe + lib/email + lib/db。routes/ 里只放薄入口（loader/action 100 行以内）。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: ["app/lib/", "app/services/", "app/routes/"],
    realWorldImpact: "把 SDK 直接写在 routes/ 里，下一个用 Stripe 的功能就要再来一遍——重复 secret 引用、重复错误映射，三个月后 secret 轮换要在 5 个 route 里找。",
    aiReviewRisk: "AI 经常把 SDK 调用直接写在 routes/，因为'就一个地方用'，等下一个地方要用时已经是 copy-paste 灾难现场。",
  }),
  q({
    type: "single_choice",
    title: "Q12 hooks/ vs components/",
    prompt: "想写一个'监听 location 变化时触发埋点'的 React hook，应该放哪里？",
    options: [
      { id: "hooks", text: "app/hooks/useLocationTracker.ts" },
      { id: "components", text: "app/components/common/useLocationTracker.tsx" },
      { id: "lib", text: "app/lib/useLocationTracker.ts" },
      { id: "utils", text: "app/utils/use-location-tracker.ts" },
    ],
    correctAnswer: { choiceId: "hooks" },
    explanation: {
      short: "自定义 React hook 归 app/hooks/。",
      detail: "components/ 装组件、hooks/ 装 hook、lib/ 装非 React 的纯 util，分层清晰。混着放就会出现「在 lib 里 import React」这种气味，迟早有人把它打进 server bundle 然后 SSR 报错。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "client",
    touchedFiles: ["app/hooks/", "app/components/"],
  }),
  q({
    type: "single_choice",
    title: "Q13 generated/ 目录用途",
    prompt: "remix/app/generated/ 是什么？应该手改吗？",
    options: [
      { id: "A", text: "由 npm 脚本写出的产物（image manifest、lyrics JSON 等），永远不要手改——改了只是被下次脚本执行覆盖" },
      { id: "B", text: "存放生成的 D1 SQL，可以手改但要小心" },
      { id: "C", text: "废弃目录，删了无影响" },
      { id: "D", text: "TypeScript 编译产物" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "generated/ 是脚本产物——手改会被 npm run images:process / lyrics:build 覆盖。",
      detail: "图片清单从 fetch→process→upload 三步生成；歌词从 assets/lyrics/*.lrc 编译成 app/data/lyrics/*.json。CLAUDE.md 里写得很清楚：「不要手改 image-manifest.ts」。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "shared",
    touchedFiles: ["app/generated/", "app/data/lyrics/"],
  }),
  q({
    type: "true_false",
    title: "Q14 是否所有路由都要 default 导出",
    prompt: "remix/app/routes/ 下每个文件都必须 default 导出一个 React 组件。",
    correctAnswer: { type: "true_false", value: false },
    explanation: {
      short: "false——api.* 与 sitemap[.]xml.tsx 这种「资源路由」只导出 loader/action，不需要 default。",
      detail: "remix/app/routes/api.nemesis.ts 只 export action（没有 UI）；sitemap[.]xml.tsx 只 export loader 返回 XML。React Router 允许只 export loader/action 不 export default——这条路由就不在 UI 树里。",
    },
    abilityTags: ["code.position.handler", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/api.nemesis.ts", "app/routes/sitemap[.]xml.tsx"],
  }),
  q({
    type: "multi_choice",
    title: "Q15 services/ 的 7 个真实文件",
    prompt: "remix/app/services/ 下面真实存在的服务端文件包括？（多选）",
    options: [
      { id: "auth", text: "nemesis-auth.server.ts" },
      { id: "guard", text: "nemesis-guard.server.ts" },
      { id: "router", text: "nemesis-query-router.server.ts" },
      { id: "rate", text: "nemesis-rate-limit.server.ts" },
      { id: "email", text: "nemesis-email.server.ts" },
      { id: "stripe", text: "nemesis-stripe.server.ts" },
    ],
    correctAnswer: { choiceIds: ["auth", "guard", "router", "rate"] },
    explanation: {
      short: "auth / guard / guard-events / query-router / rate-limit / reply / nemesis 七个都是真的；email 与 stripe 不存在。",
      detail: "services/ 是按「Nemesis 聊天链路上的子能力」切分的，每个文件覆盖一个职责：auth=拿登录态、guard=守门、guard-events=审计、query-router=多模型路由、rate-limit=限流、reply=回复拼装、nemesis=主入口。在这里编出「nemesis-email.server」会让 import 报错。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: ["app/services/"],
  }),
  q({
    type: "sort",
    title: "Q16 一次新功能落地的目录顺序",
    prompt: "添加一个新功能（比如「打卡签到」）从底向上需要触碰的目录顺序：",
    sortItems: [
      { id: "s1", text: "migrations/ 新建 SQL，给 D1 加 checkin 表", title: "DB schema", category: "backend" },
      { id: "s2", text: "app/lib/checkin.server.ts，写读写 D1 的基础函数", title: "lib 层", category: "backend" },
      { id: "s3", text: "app/services/checkin.server.ts，写「打卡 + 写审计 + 派事件」业务编排", title: "service 层", category: "backend" },
      { id: "s4", text: "app/routes/api.checkin.ts，loader/action 调 service", title: "route 层", category: "backend" },
      { id: "s5", text: "app/components/checkin/CheckinButton.tsx，UI 组件", title: "组件层", category: "frontend" },
    ],
    correctAnswer: { type: "sort", itemIds: ["s1", "s2", "s3", "s4", "s5"] },
    explanation: {
      short: "数据 → 基础函数 → 业务编排 → 路由入口 → UI。",
      detail: "这条顺序保证每一层只依赖下层、能独立测试。AI 改坏代码常见反模式：先写 UI（s5）再倒着补 service / lib / migration——结果 UI 用了一组想象的字段，等真要写到 D1 时发现 schema 兜不住，又回去改前面所有层。",
    },
    abilityTags: ["code.position.handler", "project.modify.fullstack"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: ["migrations/", "app/lib/", "app/services/", "app/routes/", "app/components/"],
    realWorldImpact: "顺序错 = 倒着重做。",
  }),
  q({
    type: "single_choice",
    title: "Q17 路由参数 $",
    prompt: "remix/app/routes/game.$platform.tsx 里 `$platform` 是什么？",
    options: [
      { id: "A", text: "路由动态段——访问 /game/switch 时 params.platform === 'switch'" },
      { id: "B", text: "TypeScript 模板字面量" },
      { id: "C", text: "shell 环境变量替换" },
      { id: "D", text: "loader 内部的私有标识符" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "$ 前缀 = 动态路由段，loader/action 里通过 params.platform 取值。",
      detail: "React Router v7 框架模式约定：文件名里 $name 表示动态段，对应 URL /game/<任意值>，在 loader/action 里 params.<name> 拿到值。本项目用 $platform 区分 PS5 / Switch / PC 等不同游戏平台。",
    },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/game.$platform.tsx"],
  }),
  q({
    type: "single_choice",
    title: "Q18 splat 路由 $",
    prompt: "remix/app/routes/api.auth.$.ts 文件名里裸 `$` 没有名字，意思是？",
    options: [
      { id: "A", text: "splat 路由——匹配 /api/auth/* 之后的整段路径，全部塞进 params['*']" },
      { id: "B", text: "未命名变量，编译会报错" },
      { id: "C", text: "Better Auth 占位符" },
      { id: "D", text: "等价于 _index" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "裸 $ = catch-all（splat），整段路径 → params['*']。",
      detail: "Better Auth 的 OAuth 回调 URL 是不固定的（/api/auth/google/callback、/api/auth/sign-out…），用 splat 路由统一接进来，再交给 Better Auth handler 自己派发。这种'我代理一段路径'的接入方式在 OAuth、Stripe webhook、第三方代理这类场景常见。",
    },
    abilityTags: ["code.position.handler", "backend.session.cookie"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/api.auth.$.ts"],
  }),
  q({
    type: "true_false",
    title: "Q19 .css?url import",
    prompt: "remix/app/root.tsx 顶部 `import tailwindStyles from './tailwind.css?url'` 的 `?url` 后缀让 Vite 把 CSS 路径作为字符串导入而不是把样式直接注入。",
    correctAnswer: { type: "true_false", value: true },
    explanation: {
      short: "true——?url 让 import 拿到的是构建后的资源 URL，root.tsx 把它写到 <link rel='stylesheet'> 里。",
      detail: "Vite 的 ?url query 是显式资产引用——绕过默认的'CSS 自动注入'，让你手动控制何时如何加载这份样式。这里和 links() 函数配合：把 URL 放进 LinksFunction 返回值，由 React Router 在 <head> 里输出 <link>。",
    },
    abilityTags: ["frontend.state.global", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: ["app/root.tsx", "app/tailwind.css"],
  }),
  q({
    type: "multi_choice",
    title: "Q20 路由文件名特殊字符",
    prompt: "remix/app/routes/sitemap[.]xml.tsx 里方括号 [.] 是？（多选）",
    options: [
      { id: "escape", text: "字面量转义——告诉路由编译器，文件名里这部分是真的点号，不是层级分隔符" },
      { id: "url", text: "结果是 URL /sitemap.xml（点号成了 URL 的一部分）" },
      { id: "regex", text: "正则字符类（与字符串.匹配的简写）" },
      { id: "unicode", text: "Unicode 标点占位" },
    ],
    correctAnswer: { choiceIds: ["escape", "url"] },
    explanation: {
      short: "[.] = 转义，让 URL 出现真正的点号；不是正则。",
      detail: "React Router v2/v7 文件名约定里，点号默认是层级分隔（game.tsx → game/Outlet）。要在 URL 里保留字面量点号（如 /sitemap.xml），就用 [.] 转义。同样的语法也能转义其它特殊字符。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/sitemap[.]xml.tsx"],
  }),
  q({
    type: "single_choice",
    title: "Q21 nemesis/ 顶层目录与 components/nemesis/ 的差别",
    prompt: "remix/app/nemesis/ 与 remix/app/components/nemesis/ 同时存在。它们的差别？",
    options: [
      { id: "A", text: "app/nemesis/ 是 Nemesis 服务端「领域模块」（数据形状、prompt 目录、查询路由配置等纯逻辑），不依赖 React；app/components/nemesis/ 是 Nemesis 的 UI 组件" },
      { id: "B", text: "完全等价，历史遗留" },
      { id: "C", text: "app/nemesis/ 是文档" },
      { id: "D", text: "components/nemesis/ 已废弃" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "app/nemesis/ = 领域核心（无 React），components/nemesis/ = UI；分层让领域逻辑可被 routes、services、components 三方复用。",
      detail: "把「领域核心」独立成顶层目录是这个项目的有意设计：services/ 编排时引用它的纯类型与配置，components/ 渲染时引用它生成的数据形状，没有任何一边能拥有它。这种分层让 Nemesis 的扩展（加新模型、新分类）只动 app/nemesis/ 即可。",
    },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: ["app/nemesis/", "app/components/nemesis/", "app/services/"],
    realWorldImpact: "如果把领域配置塞到 components/nemesis 里，service 层就要倒着 import UI——一旦 UI 重写，领域配置全跟着搬家。",
    aiReviewRisk: "AI 看到'与 Nemesis 相关'就会一股脑塞到 components/nemesis 或 services/，破坏'领域 / UI / 编排'三层分工。",
  }),
  q({
    type: "single_choice",
    title: "Q22 给 capstone 题: routes vs components 的判断",
    prompt: "新功能「在每个页面右下角弹一个'今日金句'卡片，数据从 D1 拉」。这条改动按职责切，至少要落在哪几个目录？",
    options: [
      { id: "A", text: "lib/quote.server.ts（D1 读）+ root loader 拉数据 + components/QuoteCard.tsx 渲染 + 在 root.tsx 的 Layout 里挂卡片" },
      { id: "B", text: "只在 components/QuoteCard.tsx 里 fetch '/api/quote' 即可" },
      { id: "C", text: "只在 routes/_index.tsx loader 里返回数据，再在 _index 渲染" },
      { id: "D", text: "全部塞进 root.tsx 一文件" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "全站浮动卡 = 走 root loader 注入 + 全站组件挂在 Layout，不要绑定到具体页面。",
      detail: "B 错：组件里直接 fetch 会导致每个页面单独打一次 API，且 SSR 无法预填——首屏一定空。C 错：只挂到 _index 意味着除首页外都看不到。D 错：root.tsx 应该薄，业务读写写到 lib/。正确解法是 lib/ 拿数据 → root loader 调用 → Layout 通过 useLoaderData 渲染 QuoteCard，这样任何子路由都能看到，且 SSR 一次性出。",
    },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: ["app/lib/", "app/components/", "app/root.tsx"],
    realWorldImpact: "落点选错，全站功能就退化成「只在某些页面工作」或「性能糟」，且后续维护要满项目找。",
    aiReviewRisk: "AI 倾向把全局 UI 塞到首页路由，导致除首页外都没卡片，用户感受是'功能好像坏了'。",
  }),
];
