/**
 * Real questions for site-01-repo-map / cloudflare-env.
 *
 * Anchor: remix/app/utils/cloudflare-env.server.ts (109 行).
 *   - interface RuntimeEnv { DB?, RATE_LIMITER?, MEDIA_BUCKET?, AI?, AUTH_KEY_SECRET?, …, [key: string]: unknown }
 *   - setRuntimeEnv(env): 写到模块级 runtimeEnv 与 globalThis.__REMIX_RUNTIME_ENV__
 *   - getRuntimeEnv(): 三层 fallback —— globalThis.__REMIX_RUNTIME_ENV__ → 模块 runtimeEnv → process.env → {}
 *   - getEnvVar(name): string | undefined
 *   - getRequiredEnv(name): string，缺失时 throw `${name} environment variable is required`
 *   - getDatabaseBinding(): D1Database，缺 binding 时 throw "Cloudflare D1 binding 'DB' is required"
 *   - getRateLimiterBinding(): DurableObjectNamespace，同样 throw 模板
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/utils/cloudflare-env.server.ts";

export const cloudflareEnvQuestions: RealQ[] = [
  q({
    type: "single_choice",
    title: "Q1 文件目的",
    prompt: "cloudflare-env.server.ts 在这个项目里扮演什么角色？",
    options: [
      { id: "A", text: "Cloudflare 注入的 env（DB/AI/secrets）的统一入口——其它 .server 文件不直接读 globalThis 或 process.env，而是调它的 getEnvVar / getDatabaseBinding 等" },
      { id: "B", text: "环境变量验证工具" },
      { id: "C", text: "Cloudflare Workers 的官方 SDK 二次封装" },
      { id: "D", text: "类型声明文件，不含运行时" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "项目层的 env 单一入口——把'env 从哪拿到'集中管理，剩下文件只调 helper。",
      detail: "好处：(1) 测试时只需 mock 这一文件；(2) 加新 binding 只改一个地方；(3) 把'缺失就抛错'的 fail-fast 集中——比每个调用方各自判断 undefined 强得多。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "multi_choice",
    title: "Q2 RuntimeEnv 接口包含的字段",
    prompt: "RuntimeEnv interface 里真实声明的 binding（不是普通 string env var）有？（多选）",
    options: [
      { id: "DB", text: "DB?: D1Database" },
      { id: "RL", text: "RATE_LIMITER?: DurableObjectNamespace" },
      { id: "R2", text: "MEDIA_BUCKET?: R2Bucket" },
      { id: "AI", text: "AI?: Ai" },
      { id: "Q", text: "QUEUE?: Queue" },
      { id: "KV", text: "KV?: KVNamespace" },
    ],
    correctAnswer: { choiceIds: ["DB", "RL", "R2", "AI"] },
    explanation: {
      short: "DB / RATE_LIMITER / MEDIA_BUCKET / AI 四个 binding；KV / Queue 不在本项目。",
      detail: "RuntimeEnv 对应 wrangler.toml 里的实际绑定。新加 binding 的流程：(1) wrangler.toml 加；(2) RuntimeEnv 加字段；(3) 再加一个 getXxxBinding helper 兜底缺失。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "wrangler.toml"],
  }),
  q({
    type: "single_choice",
    title: "Q3 [key: string]: unknown 的目的",
    prompt: "RuntimeEnv 末尾 `[key: string]: unknown;` 索引签名是？",
    options: [
      { id: "A", text: "兜底字段——任何未在 interface 里显式列出的 env key 都能被读到（类型是 unknown，使用前需收窄）" },
      { id: "B", text: "占位符，编译期会被去掉" },
      { id: "C", text: "强制 readonly" },
      { id: "D", text: "把 RuntimeEnv 标成 dynamic 类" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "索引签名 = 兜底——支持 ad-hoc env 而不破坏已声明字段的类型。",
      detail: "因为本项目大量临时 env（NEMESIS_FORCE_ROUTE 等开发开关），不希望每加一个就改 interface。索引签名让 getEnvVar('SOME_TEMP_FLAG') 不报错，但类型是 unknown，迫使使用方显式收窄——这比 any 安全得多。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "typescript-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "sort",
    title: "Q4 getRuntimeEnv 三层 fallback 顺序",
    prompt: "getRuntimeEnv() 内部按下列哪个顺序探测 env：",
    sortItems: [
      { id: "s1", text: "(globalThis as RuntimeGlobal).__REMIX_RUNTIME_ENV__", title: "1. globalThis", category: "backend" },
      { id: "s2", text: "模块级 runtimeEnv（最近一次 setRuntimeEnv 写入）", title: "2. 模块作用域", category: "backend" },
      { id: "s3", text: "typeof process !== 'undefined' ? process.env : {}", title: "3. process.env (本地 dev)", category: "backend" },
    ],
    correctAnswer: { type: "sort", itemIds: ["s1", "s2", "s3"] },
    explanation: {
      short: "globalThis → 模块变量 → process.env。",
      detail: "globalThis 优先是因为 entry.server.tsx 每个请求都 setRuntimeEnv 写到 globalThis，最新最准；模块变量是同一个 isolate 内的副本（极端情况下 globalThis 被擦除时兜底）；process.env 只在 Node 本地脚本（如 seed-local.ts）调用 getEnvVar 时生效。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q5 getEnvVar 的返回类型",
    prompt: "getEnvVar(name) 的返回类型是？",
    options: [
      { id: "A", text: "string | undefined（值不是 string 或缺失时返回 undefined）" },
      { id: "B", text: "string（缺失时返回空字符串）" },
      { id: "C", text: "any" },
      { id: "D", text: "string | null | undefined" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "string | undefined——拿不到就 undefined，不会硬塞空串。",
      detail: "实现里如果 value === undefined || null 就直接 return undefined；否则强制 String(value) 兜成字符串。这种'undefined 表示缺失'的做法比'空串表示缺失'好——空串容易和合法的'空配置'混淆。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "typescript-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank",
    title: "Q6 getRequiredEnv 抛错文案",
    prompt: "getRequiredEnv 找不到时 throw 的错误信息模板是 `${name} ____` ?",
    options: [],
    blanks: [{ id: "v", placeholder: "后半句", acceptedAnswers: ["environment variable is required", "environment variable is required.", "is required"] }],
    correctAnswer: { type: "fill_blank", values: { v: "environment variable is required" } },
    explanation: {
      short: "`${name} environment variable is required`。",
      detail: "用 name 拼出明确的错误能在生产排障时省一万倍时间——一眼看出「哪个 env 没注入」，对比「undefined is not a function」。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q7 getDatabaseBinding 抛错信息",
    prompt: "getDatabaseBinding 在 env.DB 缺失时 throw 的具体文案？",
    options: [
      { id: "A", text: "Cloudflare D1 binding 'DB' is required" },
      { id: "B", text: "DB not found" },
      { id: "C", text: "undefined" },
      { id: "D", text: "Database connection failed" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "Cloudflare D1 binding 'DB' is required——明确指出'是 binding 不是连接字符串'。",
      detail: "排障时这条信息能让人立刻去看 wrangler.toml 的 [[d1_databases]] 段，而不是去检查 url、密码——D1 用 binding 注入而非连接串，新人不熟悉会找错方向。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false",
    title: "Q8 getRateLimiterBinding 同样的 fail-fast 模式",
    prompt: "getRateLimiterBinding 在 env.RATE_LIMITER 缺失时也 throw（不是返回 undefined）。",
    correctAnswer: { type: "true_false", value: true },
    explanation: {
      short: "true——所有 getXxxBinding 都 fail-fast：缺 binding 立即抛，不允许后续代码继续跑出空指针。",
      detail: "fail-fast 的好处：错误信息明确（一眼看出哪个 binding 没配），且阻止 bug 被推到下游。如果返回 undefined 让调用方自己判断，会出现「binding 没注入但服务还在跑、所有写入都静默失败」的可怕场景。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "position_judgement",
    title: "Q9 新加 KV binding 应该改哪",
    prompt: "项目要加 KV namespace 来做轻量缓存。新增的 helper（如 getKvBinding）放哪？",
    options: [
      { id: "envFile", text: "remix/app/utils/cloudflare-env.server.ts（同 getDatabaseBinding 一起）", locationHint: PRIMARY },
      { id: "lib", text: "remix/app/lib/kv.server.ts", locationHint: "app/lib/" },
      { id: "service", text: "remix/app/services/kv.server.ts", locationHint: "app/services/" },
      { id: "wrangler", text: "remix/wrangler.toml 即可", locationHint: "wrangler.toml" },
    ],
    correctAnswer: { positionId: "envFile" },
    explanation: {
      short: "binding helper 一律落在 cloudflare-env.server.ts——保持单一来源。",
      detail: "KV 业务逻辑（写、读、TTL）会去 lib/kv.server.ts；但取 binding 的'是不是 undefined / fail-fast'统一在 cloudflare-env。这样下次加新 binding 时也只改一处。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/lib/", "wrangler.toml"],
  }),
  q({
    type: "single_choice",
    title: "Q10 setRuntimeEnv 同时写两个地方",
    prompt: "setRuntimeEnv(env) 把 env 写到 (1) 模块级 runtimeEnv 变量，(2) (globalThis as RuntimeGlobal).__REMIX_RUNTIME_ENV__。两个都写的原因？",
    options: [
      { id: "A", text: "isolate 复用 + ESM 模块缓存的边界——globalThis 是请求间最稳的写入点，模块变量做 backup；两个都有，命中率最高" },
      { id: "B", text: "为了线程安全" },
      { id: "C", text: "TypeScript 类型要求" },
      { id: "D", text: "Cloudflare Worker 强制要求" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "双写——globalThis 优先（最稳），模块变量兜底（极端情况下 globalThis 被改写）。",
      detail: "Cloudflare Worker isolate 在某些情况下会「重置」globalThis 字段或者由不同 entry 覆盖；同时同一个 ESM 模块在跨 entry 复用时模块变量也未必被重新初始化。两个都写 = 三层 fallback 中前两层都覆盖。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false",
    title: "Q11 getEnvVar 在 Node 脚本里能用吗",
    prompt: "在 scripts/seed-local.ts 里 import { getEnvVar } from '~/utils/cloudflare-env.server'，调它能拿到 .env 的值吗？",
    correctAnswer: { type: "true_false", value: true },
    explanation: {
      short: "true——三层 fallback 的最后一层是 process.env，所以 Node 脚本里调用也能工作。",
      detail: "这是这套 helper 设计的妙处：runtime env 与 build-time env 的差异被 getRuntimeEnv 内部抹平。Worker 上读 globalThis 注入；Node 脚本上读 process.env。调用方代码完全相同。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "scripts/seed-local.ts"],
  }),
  q({
    type: "multi_choice",
    title: "Q12 RuntimeEnv 里的 secret 字段",
    prompt: "RuntimeEnv 里下面哪些字段属于 secret（不能进客户端 bundle）？（多选）",
    options: [
      { id: "auth", text: "AUTH_KEY_SECRET / BETTER_AUTH_SECRET" },
      { id: "ai", text: "GOOGLE_AI_API_KEY / GEMINI_API_KEY / DEEPSEEK_API_KEY / XAI_API_KEY" },
      { id: "oauth", text: "GOOGLE_CLIENT_SECRET" },
      { id: "resend", text: "RESEND_API_KEY" },
      { id: "appname", text: "APP_NAME" },
      { id: "appurl", text: "APP_URL" },
    ],
    correctAnswer: { choiceIds: ["auth", "ai", "oauth", "resend"] },
    explanation: {
      short: "*_SECRET / *_KEY / *_API_KEY 都是 secret；APP_NAME / APP_URL 是公开配置。",
      detail: "区分 secret 与 public：secret 只能在 .server.ts 里读（保证不进 client bundle）；public 可以打到 root 的 window.ENV 让客户端用——本项目就是这么做（root.tsx 把 GOOGLE_CLIENT_ID + APP_URL 写到 window.ENV）。",
    },
    abilityTags: ["backend.session.cookie", "backend.auth.required"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "ai_review",
    title: "Q13 AI 写 export const env = getRuntimeEnv()",
    prompt: 'AI 想"少写一点"，把 helper 改成 `export const env = getRuntimeEnv();` 然后到处 import { env }。这个改法合格吗？',
    options: [
      { id: "bad", text: "不合格：模块顶部执行时 env 还没被注入（Cloudflare 在请求阶段才 setRuntimeEnv），import { env } 拿到的是空对象" },
      { id: "ok", text: "合格：少写代码就好" },
      { id: "ok2", text: "合格：TypeScript 不会报错" },
      { id: "ok3", text: "合格：getRuntimeEnv 是纯函数" },
    ],
    correctAnswer: { choiceId: "bad", riskIds: ["loader_action_mix"] },
    aiReviewMeta: { riskTypeOptions: [{ id: "loader_action_mix", label: "loader/action 职责混淆（这里是 模块加载时机错误）" }] },
    explanation: {
      short: "在模块顶部 const env = getRuntimeEnv() 是经典生命周期错误——env 还没注入。",
      detail: "Cloudflare Worker 加载模块时 setRuntimeEnv 还没被调用（要到 handleRequest 才调）。const 在那一刻就 freeze 了空对象。后面再 setRuntimeEnv 也不会反向改这个 const。一定要每次需要 env 时都调 getRuntimeEnv() / getEnvVar()——不要试图缓存。",
    },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
    realWorldImpact: "上线后所有依赖 env 的 .server 文件都拿到 undefined——D1/AI/secrets 全废。",
    aiReviewRisk: "AI 经常忽略 Worker 的请求生命周期，把 setup 放到模块顶部跑。",
  }),
  q({
    type: "debug",
    title: "Q14 排障 NEMESIS_AI_GATEWAY_ID is required",
    prompt: "线上偶发抛 'NEMESIS_AI_GATEWAY_ID environment variable is required'。第一个排查方向？",
    code: "// remix/app/utils/cloudflare-env.server.ts\n// getRequiredEnv 抛错",
    options: [
      { id: "wrangler", text: "Cloudflare 控制台 / wrangler.toml [vars] 与 secrets 看 NEMESIS_AI_GATEWAY_ID 是否真的注入了 production env（dev 环境通过 .env 注入与 prod 不同）" },
      { id: "css", text: "先调 Tailwind class" },
      { id: "css2", text: "先重启浏览器" },
      { id: "loader", text: "先改 loader 缓存策略" },
    ],
    correctAnswer: { issueId: "wrangler" },
    explanation: {
      short: "getRequiredEnv 抛 = env 没注入；先看 Cloudflare 是否真有这个变量。",
      detail: "误以为 .dev.vars 也能在 production 生效是常见错——dev/prod 两边 secrets 是分开的。区分方式：本地用 wrangler dev 走 .dev.vars；线上 secrets 通过 wrangler secret put 或 Cloudflare 控制台。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "wrangler.toml"],
    realWorldImpact: "依赖此 env 的功能（Nemesis 聊天）在生产 100% 失败。",
  }),
  q({
    type: "code_fix",
    title: "Q15 让 getEnvVar 防御 null",
    prompt: "已知某个 env 偶发返回 null（不是 undefined）。补一行让 getEnvVar 处理这种情况。",
    codeFixBaseline: "export function getEnvVar(name) {\n  const value = getRuntimeEnv()[name];\n  if (typeof value === 'string') return value;\n  // TODO: handle null\n  return String(value);\n}",
    correctAnswer: {
      type: "code_fix",
      patchedCode: "export function getEnvVar(name) {\n  const value = getRuntimeEnv()[name];\n  if (typeof value === 'string') return value;\n  if (value === undefined || value === null) return undefined;\n  return String(value);\n}",
    },
    expectedFixScope: "one-line",
    serverClientBoundary: "server",
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    touchedFiles: [PRIMARY],
    explanation: {
      short: "if (value === undefined || value === null) return undefined; 这一行让 null/undefined 都退化为「缺失」。",
      detail: "原文件就是这么写的。null 和 undefined 在 JS 里 == 等价但 === 不等价；不显式处理会让 String(null) 输出「null」字符串——这种「字符串看起来有但语义无效」是最糟的情况。",
    },
    realWorldImpact: "缺这行 → null 变成字符串 「null」 → 后续判断 if (envVar) 都误判为「有值」。",
  }),
  q({
    type: "single_choice",
    title: "Q16 getRuntimeEnv 在测试中如何 mock",
    prompt: "测试一个依赖 env 的函数，最干净的 mock 方式？",
    options: [
      { id: "A", text: "在 setup 里 setRuntimeEnv({ DB: mockDb, AUTH_KEY_SECRET: 'test' }) 注入测试 env，断言期再清空" },
      { id: "B", text: "改源码加 if (process.env.NODE_ENV === 'test')" },
      { id: "C", text: "全局 mock process.env" },
      { id: "D", text: "vitest.spy(getRuntimeEnv).mockReturnValue(...)" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "用 setRuntimeEnv 注入测试 env——这正是它存在的目的之一。",
      detail: "测试场景里 setRuntimeEnv 把测试 env 写进 globalThis，被测代码调 getEnvVar/getDatabaseBinding 时正常拿到。这种'测试可注入'的设计是 helper 价值的一部分——不依赖框架，写测试便宜。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false",
    title: "Q17 getRequiredEnv 与守门",
    prompt: "在 loader 顶部用 getRequiredEnv('SOME_KEY') 等于给这条路由加了一个隐式的'缺 env 就 500'守门。",
    correctAnswer: { type: "true_false", value: true },
    explanation: {
      short: "true——getRequiredEnv 一旦抛，handler 没跑完，React Router 把它转成 500。",
      detail: "fail-fast 设计的副作用：在调用栈最深处缺 env，最浅处的 React Router ErrorBoundary 把它当成 500 处理。这是 desired behavior——env 缺失是配置错误，不该让请求「半成功」。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q18 NODE_ENV 字段",
    prompt: "RuntimeEnv 里有 NODE_ENV?: string，但 Cloudflare Worker 上没有真实的 NODE_ENV——这个字段为什么还在？",
    options: [
      { id: "A", text: "兼容 Node 脚本（如 seed-local.ts）调用时通过 process.env.NODE_ENV 拿到 development/production" },
      { id: "B", text: "废弃字段，应删除" },
      { id: "C", text: "Cloudflare 在某些 region 注入" },
      { id: "D", text: "TypeScript 编译产物用" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "NODE_ENV 走 Node 脚本路径——Worker 上虽然没有，但用 [key: string]: unknown 兜底让 TS 不报错。",
      detail: "这里又用了一次「双层兼容」的设计：Node 脚本拿到真实 NODE_ENV；Worker 上拿到 undefined。调用方做 `getEnvVar('NODE_ENV') === 'development'` 判定开发模式（在 Worker 上这个条件永远 false——因为生产 Worker 没注入）。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "multi_choice",
    title: "Q19 RuntimeGlobal 类型设计",
    prompt: "type RuntimeGlobal = typeof globalThis & { __REMIX_RUNTIME_ENV__?: RuntimeEnv }; 这个类型的目的？（多选）",
    options: [
      { id: "extend", text: "在保持 globalThis 既有所有方法的同时，加一个项目自己的 __REMIX_RUNTIME_ENV__ 字段" },
      { id: "type", text: "让 (globalThis as RuntimeGlobal).__REMIX_RUNTIME_ENV__ 不需要 as any" },
      { id: "isolate", text: "把这个字段标成 ?: 表示 isolate 启动时它可能还不存在（首次请求前）" },
      { id: "lock", text: "锁定 globalThis 不让别人修改" },
    ],
    correctAnswer: { choiceIds: ["extend", "type", "isolate"] },
    explanation: {
      short: "扩展 globalThis 类型 + 标可选——既保留类型安全又表达运行时事实。",
      detail: "类型扩展是常见 TS 技巧：`type Custom = typeof base & { extra?: T }`，比 declare global 更局部、更可控。? 反映「启动时为空、setRuntimeEnv 后才有值」的真相，强迫调用方判空。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "typescript-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "ai_review",
    title: "Q20 AI 把 .server 改成 .ts",
    prompt: "AI 看到 cloudflare-env.server.ts 不知道为什么有 .server，'重构'时把它改名成 cloudflare-env.ts。会发生什么？",
    options: [
      { id: "bad", text: "不合格：失去编译期边界保护，下次有人在客户端 import 这个文件时不会报错——secrets 与 D1 binding 类型可能进客户端 bundle" },
      { id: "ok", text: "合格：文件名简化、import 更短" },
      { id: "ok2", text: "合格：编译期等价" },
      { id: "ok3", text: "合格：现代项目都不用 .server 了" },
    ],
    correctAnswer: { choiceId: "bad", riskIds: ["client_server_mix"] },
    aiReviewMeta: { riskTypeOptions: [{ id: "client_server_mix", label: "客户端/服务端边界混淆" }] },
    explanation: {
      short: ".server 后缀是 React Router 编译器的硬约束——删了就丢边界。",
      detail: "丢 .server 后，理论上只是「约定不在了」，但实际后果链很长：(1) 别人在客户端组件里 import 它编译能过；(2) D1 binding 类型出现在客户端代码里，最坏情况触发 worker.ts 的 binding 引用泄漏；(3) 即使没真正泄漏 secret，也让 client bundle 变大。",
    },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
    realWorldImpact: "失去 server-only 保护 = 给后续所有 PR 留了 secret 泄漏的口子。",
    aiReviewRisk: "AI 在 'naming consistency' 名义下抹掉编译器约束是经典反模式。",
  }),
  q({
    type: "true_false",
    title: "Q21 getRuntimeEnv() 返回 {} 时怎么处理",
    prompt: "如果三层 fallback 都拿不到 env，getRuntimeEnv 返回 `{}`（空对象），调用方的 getEnvVar(name) 会返回 undefined。",
    correctAnswer: { type: "true_false", value: true },
    explanation: {
      short: "true——空对象是合法的 RuntimeEnv，所有字段读出 undefined。",
      detail: "返回 `{}` 比 throw 好的地方在于：(1) 模块顶部还没注入 env 时调用不直接炸；(2) 区分'没注入'与'缺某条字段'：前者 getRuntimeEnv() === {}，后者 getRuntimeEnv()[name] === undefined。getRequiredEnv 才负责'必须有的硬抛'。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "free_explain",
    title: "Q22 自由复述 cloudflare-env 设计",
    prompt: "用自己的话讲一下 cloudflare-env.server.ts 在 Worker 请求生命周期里扮演的角色，以及'三层 fallback'的存在意义。",
    code: "// 关键代码（删节）：\n// let runtimeEnv: RuntimeEnv = {};\n// export function setRuntimeEnv(env) {\n//   runtimeEnv = env;\n//   (globalThis as RuntimeGlobal).__REMIX_RUNTIME_ENV__ = env;\n// }\n// export function getRuntimeEnv() {\n//   return globalThis.__REMIX_RUNTIME_ENV__\n//     ?? (Object.keys(runtimeEnv).length > 0 ? runtimeEnv : (process?.env ?? {}));\n// }",
    correctAnswer: { type: "free_explain", text: "no correct answer — AI grades" },
    explanation: {
      short: "好答案应该提到：请求生命周期、isolate 复用、Worker vs Node 脚本两套消费场景。",
      detail: "完整答案至少包含：(1) entry.server.tsx 在 handleRequest 头部 setRuntimeEnv 把 Cloudflare 注入的 env 写进来；(2) 模块作用域作为 isolate 内的副本；(3) process.env 用来支持 Node 脚本（seed/curriculum 等）；(4) 三层 fallback 让同一份代码在 Worker 与脚本两种环境跑都能拿到正确 env。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "free-response",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
];
