/**
 * Real questions for site-01-repo-map / components-folder.
 *
 * Anchor: remix/app/components/ 下的真实子目录。
 *   auth/ (LoginDialog, GoogleOneTap.client, LoginSuccessVeil)
 *   common/ (ClientOnly)
 *   error/ (NotFound404, RouteErrorBoundary)
 *   game/, home/, messages/, music/, nemesis/
 *   transitions/ (RouteTransition)
 *   ui/ (Header, GsapFillLink, GsapGlassCard, MotionMusicGateway, question)
 * 学习目标: 看到一个 UI 想法时能说出它落在 components/ 的哪个子目录；理解 .client 后缀。
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/";

export const componentsFolderQuestions: RealQ[] = [
  q({
    type: "multi_choice",
    title: "Q1 components/ 真实子目录",
    prompt: "remix/app/components/ 下面真实存在的子目录是？（多选）",
    options: [
      { id: "auth", text: "auth/（登录弹窗与 OAuth UI）" },
      { id: "error", text: "error/（NotFound404 / RouteErrorBoundary）" },
      { id: "transitions", text: "transitions/（RouteTransition 路由过渡）" },
      { id: "ui", text: "ui/（Header / GsapGlassCard 等通用 UI）" },
      { id: "auth-pages", text: "auth-pages/" },
      { id: "shared", text: "shared/" },
    ],
    correctAnswer: { choiceIds: ["auth", "error", "transitions", "ui"] },
    explanation: {
      short: "auth / common / error / game / home / messages / music / nemesis / transitions / ui 这十个真实存在；auth-pages / shared 不在。",
      detail: "目录划分按「领域」切：auth = 登录认证 UI、error = 错误页、game/home/music/messages = 各业务区块、ui = 跨领域基础组件、common = 跨业务包裹器（ClientOnly）、transitions = 路由过渡、nemesis = 聊天领域 UI。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q2 ClientOnly 在哪",
    prompt: "ClientOnly 这个'强制只在浏览器渲染'的包裹器在哪个目录？",
    options: [
      { id: "common", text: "remix/app/components/common/ClientOnly.tsx" },
      { id: "ui", text: "remix/app/components/ui/ClientOnly.tsx" },
      { id: "lib", text: "remix/app/lib/ClientOnly.tsx" },
      { id: "hooks", text: "remix/app/hooks/ClientOnly.tsx" },
    ],
    correctAnswer: { choiceId: "common" },
    explanation: {
      short: "common/ClientOnly——'通用包裹器'放 components/common，UI 装饰才放 components/ui。",
      detail: "common/ 与 ui/ 的差别：ui/ 装能直接呈现样式的组件（Header、Button、Card）；common/ 装无视觉、只做行为包裹的 helper（ClientOnly、ErrorBoundary、Suspense 等）。",
    },
    abilityTags: ["code.position.handler", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "client",
    touchedFiles: ["app/components/common/ClientOnly.tsx"],
  }),
  q({
    type: "single_choice",
    title: "Q3 RouteErrorBoundary 在哪",
    prompt: "项目级别的 RouteErrorBoundary（路由报错时的兜底 UI）放在？",
    options: [
      { id: "error", text: "remix/app/components/error/RouteErrorBoundary.tsx" },
      { id: "common", text: "remix/app/components/common/RouteErrorBoundary.tsx" },
      { id: "ui", text: "remix/app/components/ui/RouteErrorBoundary.tsx" },
      { id: "root", text: "remix/app/root.tsx 内部" },
    ],
    correctAnswer: { choiceId: "error" },
    explanation: {
      short: "components/error/RouteErrorBoundary.tsx——错误页归 error/ 子目录。",
      detail: "error/ 子目录里同时还有 NotFound404.tsx。这种'按 UX 关注点分文件夹'的方式让排查问题时知道该去哪——404 / 500 / 路由级错误都在 error/。root.tsx 只是导出一个外壳指向这些。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "client",
    touchedFiles: ["app/components/error/RouteErrorBoundary.tsx", "app/components/error/NotFound404.tsx"],
  }),
  q({
    type: "single_choice",
    title: "Q4 GoogleOneTap.client.tsx 后缀含义",
    prompt: "remix/app/components/auth/GoogleOneTap.client.tsx 的 .client 后缀是？",
    options: [
      { id: "A", text: "强制只在浏览器执行——server bundle 把这个文件替换成空 stub，避免 SSR 阶段调用 window/document 报错" },
      { id: "B", text: "等同 'use client' 指令" },
      { id: "C", text: "Vite 插件配置标记" },
      { id: "D", text: "和 SSR 无关，纯命名约定" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: ".client 是 Remix/RR 编译器把客户端专用代码隔离的标记。",
      detail: "Google one-tap SDK 直接读取 window.google，SSR 阶段执行就崩。.client 后缀让构建链在 server bundle 里把它替换为空，只在浏览器水合后由 lazy import 加载。root.tsx 用 lazy(() => import('GoogleOneTap.client')) + Suspense 是配套写法。",
    },
    abilityTags: ["code.position.handler", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "client",
    touchedFiles: ["app/components/auth/GoogleOneTap.client.tsx"],
  }),
  q({
    type: "true_false",
    title: "Q5 components/ui 必须保持纯展示",
    prompt: "components/ui/ 里的组件不应该 import 任何 .server 文件。",
    correctAnswer: { type: "true_false", value: true },
    explanation: {
      short: "true——components/ui 是 client 组件，import .server 会编译报错（也不该 import）。",
      detail: "Header.tsx / GsapGlassCard.tsx 等组件最终都进客户端 bundle，那里没有 D1 binding 也没有 secret。如果 Header 想显示登录用户，正确路径是：root loader 拿 session → 通过 useLoaderData 传到 Header（props 注入）→ Header 不直接访问 server。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q6 Header.tsx 在哪",
    prompt: "全站 Header 组件在哪个文件？",
    options: [
      { id: "ui", text: "remix/app/components/ui/Header.tsx" },
      { id: "common", text: "remix/app/components/common/Header.tsx" },
      { id: "layout", text: "remix/app/components/layout/Header.tsx" },
      { id: "app", text: "remix/app/Header.tsx" },
    ],
    correctAnswer: { choiceId: "ui" },
    explanation: {
      short: "components/ui/Header.tsx——Header 属于通用 UI。",
      detail: "项目里没有 components/layout/ 这个目录。'布局'职责由 Header（这里）+ root.tsx 的 Layout 组件共同承担——Header 是组件，Layout 是路由树根。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "client",
    touchedFiles: ["app/components/ui/Header.tsx"],
  }),
  q({
    type: "multi_choice",
    title: "Q7 components/ui/ 真实文件",
    prompt: "remix/app/components/ui/ 下面真实存在的文件有？（多选）",
    options: [
      { id: "header", text: "Header.tsx" },
      { id: "gsapfill", text: "GsapFillLink.tsx" },
      { id: "gsapglass", text: "GsapGlassCard.tsx" },
      { id: "music", text: "MotionMusicGateway.tsx" },
      { id: "question", text: "question.tsx" },
      { id: "button", text: "Button.tsx" },
      { id: "card", text: "Card.tsx" },
    ],
    correctAnswer: { choiceIds: ["header", "gsapfill", "gsapglass", "music", "question"] },
    explanation: {
      short: "Header / GsapFillLink / GsapGlassCard / MotionMusicGateway / question 真实存在；Button / Card 没有。",
      detail: "这是个有'强动画审美'的项目（GSAP / Framer Motion），UI 文件夹里都是带动效的组件而不是常规的 Button/Card 库。AI 默认假设的'设计系统组件'在这里不存在——别编。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "client",
    touchedFiles: ["app/components/ui/"],
  }),
  q({
    type: "position_judgement",
    title: "Q8 添加'登录弹窗的关闭按钮'",
    prompt: "登录弹窗（LoginDialog）需要新增一个关闭 X 按钮组件。这个组件放哪？",
    options: [
      { id: "auth", text: "remix/app/components/auth/CloseButton.tsx", locationHint: "app/components/auth/" },
      { id: "ui", text: "remix/app/components/ui/CloseButton.tsx", locationHint: "app/components/ui/" },
      { id: "common", text: "remix/app/components/common/CloseButton.tsx", locationHint: "app/components/common/" },
      { id: "lib", text: "remix/app/lib/CloseButton.tsx", locationHint: "app/lib/" },
    ],
    correctAnswer: { positionId: "ui" },
    explanation: {
      short: "通用 X 按钮 → ui/。它会被多个领域复用（messages 弹窗、settings 弹窗也都用得到），别绑死在 auth/。",
      detail: "判断顺序：(1) 是否纯通用 UI 装饰？是 → ui/；(2) 是否有领域特定行为（如 LoginDialog 内部的 close 逻辑）？有 → auth/；(3) 是否无视觉只做行为？是 → common/。这条 X 只是按钮，归 ui/。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: ["app/components/ui/", "app/components/auth/"],
  }),
  q({
    type: "single_choice",
    title: "Q9 lazy import 与 .client",
    prompt: "remix/app/root.tsx 顶部 const LoginDialog = lazy(() => import('~/components/auth/LoginDialog'));，为什么 LoginDialog 不带 .client 后缀也能 lazy 加载？",
    options: [
      { id: "A", text: "lazy() 让代码分裂 + 延迟加载，但本身不强制只在客户端运行；LoginDialog 内部可以 SSR 渲染（只是被 lazy 包了一层不在首屏 bundle 里）" },
      { id: "B", text: "因为 lazy 自动加 .client" },
      { id: "C", text: "编译期会自动改名" },
      { id: "D", text: "其实不能加载，是个 bug" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "lazy = 代码分裂 + 延迟；.client = 强制只在浏览器执行。两件事独立。",
      detail: "LoginDialog 没有 window/document 强依赖，可以 SSR；但首屏不需要它（用户没点登录按钮前），所以用 lazy 把它分到独立 chunk。GoogleOneTap 不一样——它真的依赖 window，必须 .client。",
    },
    abilityTags: ["frontend.state.local", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "client",
    touchedFiles: ["app/root.tsx", "app/components/auth/LoginDialog.tsx", "app/components/auth/GoogleOneTap.client.tsx"],
  }),
  q({
    type: "single_choice",
    title: "Q10 components/nemesis 与 services/nemesis",
    prompt: "components/nemesis/ 下面装的是什么？与 services/nemesis*.server.ts 区别？",
    options: [
      { id: "A", text: "components/nemesis/ = Nemesis 聊天的 UI（Chat 输入框、Message 气泡、StreamRenderer）；services/nemesis*.server.ts = 服务端逻辑（守门、限流、模型路由）" },
      { id: "B", text: "完全相同的两份代码" },
      { id: "C", text: "components 是测试，services 是生产" },
      { id: "D", text: "只有 services 有意义，components 已废弃" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "components/nemesis = UI；services/nemesis = server 逻辑——同一领域两个面。",
      detail: "Nemesis 这条业务横跨前后端，分两层：UI 层在 components/nemesis/，服务端逻辑在 services/nemesis*.server.ts，再加上 app/nemesis/ 这个不依赖 React 的领域核心三层。改 UI 不影响 server，改 server 也不动 UI。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "shared",
    touchedFiles: ["app/components/nemesis/", "app/services/", "app/nemesis/"],
  }),
  q({
    type: "true_false",
    title: "Q11 transitions/ 是过渡动画",
    prompt: "components/transitions/ 装的是 React 路由切换时的过渡动画组件（如 RouteTransition）。",
    correctAnswer: { type: "true_false", value: true },
    explanation: {
      short: "true——RouteTransition 监听 location 变化触发 GSAP/Framer Motion 过渡。",
      detail: "把过渡动画独立成子目录是因为它们都依赖 useLocation + 时间序列控制——和'静态展示组件'在生命周期上完全不一样。集中管理也方便统一关掉（如 prefers-reduced-motion）。",
    },
    abilityTags: ["frontend.effect.useEffect", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "client",
    touchedFiles: ["app/components/transitions/RouteTransition.tsx"],
  }),
  q({
    type: "ai_review",
    title: "Q12 AI 把 'global header state' 写到 Header 组件里",
    prompt: "AI 想'让 Header 知道当前用户是否登录'，于是在 Header.tsx 内部 useEffect + fetch('/api/me')。这个改法合格吗？",
    options: [
      { id: "bad", text: '不合格：Header 是 components/ui/ 的纯展示组件，不应该自己拉数据；session 应该来自 root loader 通过 props 注入' },
      { id: "ok", text: "合格：Header 自己负责自己的数据" },
      { id: "ok2", text: "合格：useEffect + fetch 是经典 React 写法" },
      { id: "ok3", text: "合格：少传一层 props 更省事" },
    ],
    correctAnswer: { choiceId: "bad", riskIds: ["client_server_mix"] },
    aiReviewMeta: { riskTypeOptions: [{ id: "client_server_mix", label: "客户端/服务端状态混淆" }] },
    explanation: {
      short: "Header.tsx 应当是纯展示组件——session 来自 root loader 注入，不要自己 fetch。",
      detail: "(1) useEffect+fetch 让首屏空一段时间（SSR 时还没数据），用户先看到无登录态再闪到有登录态；(2) 每次进页面都打一次 /api/me；(3) 写法分散：5 个组件都各自要自己的 session 时就 5 份重复请求。正确做法：root loader 一次拉，全树通过 useLoaderData / useRouteLoaderData('root') 共享。",
    },
    abilityTags: ["ai.review.architecture", "frontend.state.global"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: ["app/components/ui/Header.tsx", "app/root.tsx"],
    realWorldImpact: "全站 Header 闪烁、N 倍 /api/me 请求、Header 内部状态散落。",
    aiReviewRisk: "AI 把'让组件自治'优先级置于'框架推荐的数据流'之上，是 SSR 项目里的高频反模式。",
  }),
  q({
    type: "single_choice",
    title: "Q13 components/auth 子目录列表",
    prompt: "remix/app/components/auth/ 下面真实有的文件？（仅一个对的）",
    options: [
      { id: "A", text: "LoginDialog（弹窗）+ GoogleOneTap.client（OAuth 一触登录）+ LoginSuccessVeil（登录成功后的过渡蒙层）" },
      { id: "B", text: "只有 LoginDialog 一个文件" },
      { id: "C", text: "没有这个目录" },
      { id: "D", text: "只有 OAuth 配置 JSON" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "三件套：LoginDialog（容器）+ GoogleOneTap.client（外部 SDK 桥接）+ LoginSuccessVeil（动效）。",
      detail: "看到这个组合就大体知道登录 UX：用户进来 GoogleOneTap 自动弹（如果支持）→ 不行就显式 LoginDialog → 登录成功后 LoginSuccessVeil 给一个过渡。把不同关注点拆成三个文件比一个 LoginPanel.tsx 长 800 行清楚得多。",
    },
    abilityTags: ["code.position.handler", "backend.session.cookie"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "client",
    touchedFiles: ["app/components/auth/"],
  }),
  q({
    type: "position_judgement",
    title: "Q14 添加'游戏分数排行榜'",
    prompt: "新增一个'游戏分数排行榜'组件，主要被 game.$platform.tsx 使用，但首页 Hero 也想内嵌。该放哪？",
    options: [
      { id: "game", text: "remix/app/components/game/Leaderboard.tsx", locationHint: "app/components/game/" },
      { id: "ui", text: "remix/app/components/ui/Leaderboard.tsx", locationHint: "app/components/ui/" },
      { id: "home", text: "remix/app/components/home/Leaderboard.tsx", locationHint: "app/components/home/" },
      { id: "common", text: "remix/app/components/common/Leaderboard.tsx", locationHint: "app/components/common/" },
    ],
    correctAnswer: { positionId: "game" },
    explanation: {
      short: "组件主属域 = 'game'（数据语义、业务逻辑都属游戏）；首页只是'用户'。归 game/。",
      detail: "判断按'数据所有权'优先于'调用频率'：Leaderboard 的数据形状、API 都是游戏域定义的；首页只是把它嵌进来。如果归到 ui/ 就跨了领域；归到 home/ 让首页拥有了不属于它的代码。组件可以被 import 得很广，归处仍然按数据所有权。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: ["app/components/game/", "app/components/ui/", "app/components/home/"],
  }),
  q({
    type: "true_false",
    title: "Q15 components/ 子目录里能放 .server 文件吗",
    prompt: "在 components/messages/ 里写一个 messages.server.ts 文件（让消息组件直接读 D1）是合理的。",
    correctAnswer: { type: "true_false", value: false },
    explanation: {
      short: "false——components/ 都是 client；.server 文件应该挪到 lib/ 或 services/。",
      detail: "components/ 整个目录的语义是'客户端 React 组件'。.server 文件出现在这里会被 import 链拉进客户端 bundle 编译——RR 框架会直接报错，让你修。这是有意识的设计：边界清晰才不会泄漏 secret。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: ["app/components/", "app/lib/messages.server.ts"],
  }),
  q({
    type: "fill_blank",
    title: "Q16 home 子目录的核心组件",
    prompt: "首页 _index.tsx 主要由 components/home/ 下的 ____ 组件拼装。",
    options: [],
    blanks: [{ id: "v", placeholder: "组件名（一个就行）", acceptedAnswers: ["HomeHero", "video-showcase", "cyber-terminal", "Hero"] }],
    correctAnswer: { type: "fill_blank", values: { v: "HomeHero" } },
    explanation: {
      short: "HomeHero / video-showcase / cyber-terminal 等都在 components/home/。",
      detail: "首页是组件拼装出来的（很多区块都重）：Hero（GSAP 主视觉）+ 视频展示 + 歌词 / 终端 + 更新列表。这种'页面薄、组件厚'的结构方便每个区块单独迭代。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "client",
    touchedFiles: ["app/components/home/", "app/routes/_index.tsx"],
  }),
  q({
    type: "debug",
    title: "Q17 排障 hydration mismatch",
    prompt: '某个 components/home/ 的子组件在线上偶发 "Hydration failed because the initial UI does not match"。第一个排查方向？',
    code: "// remix/app/components/home/...\n// 大概率有 useEffect 或读取 window/document",
    options: [
      { id: "client", text: "看组件是否在初次渲染就读 window/document/Date.now()——这种值在 server 与 client 不一致，应该用 ClientOnly 包裹或者放进 useEffect 里" },
      { id: "ssl", text: "先重发 SSL 证书" },
      { id: "css", text: "先改 Tailwind class" },
      { id: "wait", text: "先等流量过去" },
    ],
    correctAnswer: { issueId: "client" },
    explanation: {
      short: "Hydration mismatch = SSR 与 client 第一次渲染输出不同 → 99% 是组件在初次 render 就用了仅 client 才有的值。",
      detail: "ClientOnly 包裹是直接修法（让组件第一次 render 输出 fallback，浏览器水合后才真正渲染）。useEffect 也行（effect 在 client 才跑）。常见错源：Date.now() / Math.random() / window.matchMedia / navigator.userAgent。",
    },
    abilityTags: ["frontend.effect.useEffect", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "client",
    touchedFiles: ["app/components/home/", "app/components/common/ClientOnly.tsx"],
    realWorldImpact: "Hydration 失败让整个组件树退化成 client-only render，性能与 SEO 都受损。",
  }),
  q({
    type: "single_choice",
    title: "Q18 messages 组件域",
    prompt: "remix/app/components/messages/ 装的是？",
    options: [
      { id: "A", text: "留言板的 UI 组件（BubbleMessageBoard、消息卡片、表单等）" },
      { id: "B", text: "邮件模板" },
      { id: "C", text: "Telegram bot 接入" },
      { id: "D", text: "空目录" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "留言板域：BubbleMessageBoard 等。messages.tsx 路由把它们组装起来。",
      detail: "看 components/messages/ 与 routes/messages.tsx + lib/messages.server.ts 是同一业务的三层：UI / 路由 / 服务端读写——这是这个项目的标准三层。学会识别这种模式，加新功能时知道怎么对齐。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "client",
    touchedFiles: ["app/components/messages/", "app/routes/messages.tsx", "app/lib/messages.server.ts"],
  }),
  q({
    type: "single_choice",
    title: "Q19 一个组件依赖 GSAP，应该 .client 吗",
    prompt: "GsapGlassCard.tsx 大量调用 GSAP（依赖 window）。它有没有 .client 后缀？为什么？",
    options: [
      { id: "A", text: "没有 .client——因为 GSAP 调用都被放到 useEffect 里，SSR 时不执行；首屏 SSR 是静态版，水合后 effect 跑起来才动" },
      { id: "B", text: "有 .client，否则 SSR 报错" },
      { id: "C", text: "应该改成 .client" },
      { id: "D", text: "和 SSR 没关系" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "GSAP 在 useEffect 里调，SSR 不执行——不需要 .client。",
      detail: "什么时候真需要 .client：SDK 在模块顶部初始化就读 window（如 Google one-tap）、或组件返回值依赖 navigator.userAgent / matchMedia。如果 effect 内部读 window，普通组件 + useEffect 就够。",
    },
    abilityTags: ["frontend.effect.useEffect", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "client",
    touchedFiles: ["app/components/ui/GsapGlassCard.tsx"],
  }),
  q({
    type: "multi_choice",
    title: "Q20 .client 后缀适用场景",
    prompt: "下列哪些场景适合给一个组件加 .client 后缀？（多选）",
    options: [
      { id: "sdk", text: "组件 import 的 SDK 在模块加载时就 new XxxClient(window)，SSR 时会炸" },
      { id: "topwindow", text: "组件函数体最顶部就 const w = window，SSR 报错" },
      { id: "navigator", text: "组件初次返回值依赖 navigator.userAgent" },
      { id: "useEffect", text: "组件只在 useEffect 内部调用 window.matchMedia" },
      { id: "tailwind", text: "组件用了 Tailwind class" },
    ],
    correctAnswer: { choiceIds: ["sdk", "topwindow", "navigator"] },
    explanation: {
      short: "凡是'初次同步渲染就读 window'的都该 .client；effect 内部读 window 不需要。",
      detail: "Tailwind class 与 .client 完全无关；useEffect 因为本身就只在浏览器跑也不需要。判断标准只一条：'第一次 render 同步执行的代码里是否依赖 client-only API'。",
    },
    abilityTags: ["frontend.effect.useEffect", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "client",
    touchedFiles: ["app/components/"],
  }),
  q({
    type: "ai_review",
    title: "Q21 AI 把所有组件都标 .client",
    prompt: 'AI 觉得"反正都是 React 组件，全标 .client 最安全"，把所有 components/ 文件改名加 .client 后缀。这个改法合格吗？',
    options: [
      { id: "bad", text: "不合格：失去 SSR 后所有 UI 在 server 都是空白，首屏白屏 + SEO 失效；这是把所有组件降级成 client-only render" },
      { id: "ok", text: "合格：100% 不会出 hydration 错误" },
      { id: "ok2", text: "合格：客户端渲染更快" },
      { id: "ok3", text: "合格：与 'use client' 等价" },
    ],
    correctAnswer: { choiceId: "bad", riskIds: ["client_server_mix"] },
    aiReviewMeta: { riskTypeOptions: [{ id: "client_server_mix", label: "客户端/服务端边界混淆" }] },
    explanation: {
      short: "全 .client = 全站退化为 SPA，首屏白屏 + SEO 0 分。SSR 是核心价值。",
      detail: "Cloudflare Workers SSR + React Router 框架模式的优势就是首屏服务端渲染、流式输出。让所有组件 .client 等于把这优势全砍掉——和直接用 Vite + React SPA 没区别。.client 是定点武器，不是普适开关。",
    },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: ["app/components/"],
    realWorldImpact: "全站首屏空白 → 用户感受是站炸了；SEO 抓不到内容。",
    aiReviewRisk: "AI 用'最保守'盖过'最合理'是高频反模式；越保守的设置反而经常带来更糟的副作用。",
  }),
  q({
    type: "free_explain",
    title: "Q22 自由复述 components/ 子目录划分",
    prompt: "用自己的话讲一下 components/ 下的 10 个子目录（auth/common/error/game/home/messages/music/nemesis/transitions/ui）的分工逻辑——按什么维度切？",
    code: "// 真实子目录：auth/ common/ error/ game/ home/ messages/ music/ nemesis/ transitions/ ui/",
    correctAnswer: { type: "free_explain", text: "no correct answer — AI grades" },
    explanation: {
      short: "好答案要点：业务领域（auth/game/messages/music/nemesis/home）、UX 关注点（error/transitions）、跨域共用（ui/common）三类切分。",
      detail: "完整答案至少包含：(1) 多数子目录是按业务领域切（auth/game/messages/music/nemesis/home）；(2) error/ 与 transitions/ 是按 UX 关注点切（错误处理、过渡动画）——这两件事横跨所有领域；(3) ui/ 是无领域的设计基础（Header、Card、Link）；(4) common/ 是行为包裹器（ClientOnly），无视觉。三种切分维度并存，让组件归处明确——'按领域 / 按关注点 / 按通用度'。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "free-response",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
];
