/**
 * Real questions for site-01-repo-map / entry-server-intro.
 *
 * Anchor: remix/app/entry.server.tsx (整个文件 65 行).
 *   - default export handleRequest(request, status, headers, remixContext, loadContext)
 *   - ABORT_DELAY = 5_000
 *   - renderToReadableStream from "react-dom/server.browser"
 *   - isbot from "isbot"
 *   - setRuntimeEnv(cloudflareEnv) on each request
 *   - /.well-known/* short-circuits to {} JSON with public,max-age=3600
 *   - AbortSignal.timeout(ABORT_DELAY) feeds renderToReadableStream
 *   - 如果 isbot → await body.allReady; 否则流式
 *   - responseHeaders.set("Content-Type", "text/html")
 *   - 错误 → status 500
 *
 * 学习目标: 看到 entry.server.tsx 时能说清"它在 SSR 链路里是哪一站"，遇到 SSR 行为异常知道改这里还是别处。
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/entry.server.tsx";

export const entryServerIntroQuestions: RealQ[] = [
  q({
    type: "single_choice",
    title: "Q1 default export 是什么",
    prompt: "remix/app/entry.server.tsx 的 default export 函数名 + 作用？",
    options: [
      { id: "A", text: "handleRequest——Worker 收到的每个请求都会调用它，把 React 树渲染成 HTML response" },
      { id: "B", text: "main——服务启动入口" },
      { id: "C", text: "Layout——根组件" },
      { id: "D", text: "fetch——Cloudflare Worker fetch handler" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "default = handleRequest，Remix/RR7 约定的 SSR hook 名。",
      detail: "签名是 handleRequest(request, responseStatusCode, responseHeaders, remixContext, loadContext)。Worker 入口 worker.ts → React Router 服务端运行 → 调 entry.server 的 default。这是你能拿到所有路由 loader 跑完结果之后、HTML 输出之前的「最后一关」。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank",
    title: "Q2 ABORT_DELAY 值",
    prompt: "entry.server.tsx 里 const ABORT_DELAY = ____ ;（毫秒）",
    options: [],
    blanks: [{ id: "v", placeholder: "毫秒数", acceptedAnswers: ["5000", "5_000", "5 000"] }],
    correctAnswer: { type: "fill_blank", values: { v: "5000" } },
    explanation: {
      short: "ABORT_DELAY = 5_000 (5 秒)。",
      detail: "这个值喂给 AbortSignal.timeout(ABORT_DELAY) 给 renderToReadableStream 设上限——loader 加 SSR 渲染最多花 5 秒，超时 abort。如果你的 loader 比较慢，把数字调大要权衡：客户端要等更久才能看到首屏。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q3 renderToReadableStream 来源",
    prompt: "entry.server.tsx 顶部 import 中 renderToReadableStream 来自？",
    options: [
      { id: "A", text: "react-dom/server.browser（带 // @ts-expect-error 注释，因为 React 18 没发布该入口的类型）" },
      { id: "B", text: "react-dom/server" },
      { id: "C", text: "@remix-run/cloudflare" },
      { id: "D", text: "react/server" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "react-dom/server.browser——Cloudflare Worker 上要用 browser 版本，不是 node 版本。",
      detail: "Cloudflare Worker 的运行时用 V8 ish 不是 Node，react-dom/server (Node 版) 会引入 stream 等 Node API。.browser 子路径是 Web Streams 实现，配 Worker 才不爆。文件顶部那行 // @ts-expect-error 是因为 react-dom 18 的 package.json 没暴露这个 subpath 的 types——升 React 19 后这行可能可以删。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q4 setRuntimeEnv 的目的",
    prompt: "handleRequest 一开始就 setRuntimeEnv(cloudflareEnv)，目的是？",
    options: [
      { id: "A", text: "把 Cloudflare 注入的 env（DB / AI / R2 / secrets）写到 globalThis 与模块级变量，让 .server 模块通过 getEnvVar/getRuntimeEnv 拿到" },
      { id: "B", text: "重启 Worker" },
      { id: "C", text: "缓存请求" },
      { id: "D", text: "重置请求计数器" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "把 env 写到 globalThis，让 .server 文件里 getEnvVar() 不用每次都 prop drilling 拿 context。",
      detail: "Cloudflare 把 env 通过 loadContext.cloudflare.env 传进来。每次请求都重新 setRuntimeEnv，因为同一个 Worker isolate 会被多个请求复用——上一次的 env 不能假定还对。这是为什么很多 lib/auth.server / db.server 不需要把 env 从每个 loader 一路传进来。",
    },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/utils/cloudflare-env.server.ts"],
  }),
  q({
    type: "single_choice",
    title: "Q5 .well-known 短路",
    prompt: "entry.server.tsx 对 url.pathname.startsWith('/.well-known/') 的请求做了什么？",
    options: [
      { id: "A", text: '直接返回 { } 空 JSON，状态 200，Cache-Control: public, max-age=3600——绕过整个 React 渲染' },
      { id: "B", text: "重定向到 /404" },
      { id: "C", text: "调 Better Auth 处理" },
      { id: "D", text: "直接 throw" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "对 /.well-known/* 直接返回空 JSON + 1h 缓存——避开浏览器 / Apple 设备的探测请求拖累 SSR。",
      detail: "Apple Pay、Mac 的 .well-known/apple-app-site-association、TLS-ALPN 验证等等会大量打 /.well-known/*。如果让它们走完 React Router 渲染就是浪费——直接短路到空 JSON，缓存一小时，把 CPU 留给真实请求。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false",
    title: "Q6 isbot 与流式",
    prompt: "entry.server.tsx 对爬虫（isbot 判定）会等 body.allReady 后再返回 HTML，而对真实用户走流式输出。",
    correctAnswer: { type: "true_false", value: true },
    explanation: {
      short: "true——爬虫拿不到流式，给一次性 HTML；用户走流式让首屏更快。",
      detail: "搜索引擎抓取器对 chunked / streaming HTML 解析参差不齐，等 body.allReady 把全部内容打齐再返回更稳。真实用户的浏览器都支持流式，让 Suspense / loader 慢的部分边渲染边出，首屏更快。这是 SSR 的经典分流。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank",
    title: "Q7 Content-Type 设置",
    prompt: "entry.server.tsx 末段 responseHeaders.set('Content-Type', '____');",
    options: [],
    blanks: [{ id: "v", placeholder: "MIME", acceptedAnswers: ["text/html", "text/html; charset=utf-8"] }],
    correctAnswer: { type: "fill_blank", values: { v: "text/html" } },
    explanation: {
      short: "text/html。",
      detail: "因为这条 SSR 路径产出的就是 HTML 文档；entry.server 不负责 JSON / XML——sitemap[.]xml.tsx 自己 loader 里 set 'application/xml' 覆盖。Set 而不是 append，一定确保唯一 Content-Type。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q8 didError = true 时返回什么",
    prompt: "renderToReadableStream 的 onError 回调把 didError 置为 true 后，最终响应的 status 是？",
    options: [
      { id: "A", text: "500（return new Response(body, { status: didError ? 500 : responseStatusCode }))" },
      { id: "B", text: "200（流式不能改 status）" },
      { id: "C", text: "404" },
      { id: "D", text: "504" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "didError ? 500 : responseStatusCode——SSR 渲染过程中抛错就返 500。",
      detail: "注意：onError 只是把标志位 didError 置 true 并 console.error，不会中断流。流式输出已经在飞了，所以最终状态码会在所有 chunk 写完后由这一行决定。loader 里 throw 的是另一回事——那时还没进 renderToReadableStream，会被 React Router 自身的 ErrorBoundary 捕获走另一条路径。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace",
    title: "Q9 一个 GET / 的处理路径",
    prompt: "用户用浏览器打开 https://站点/，handleRequest 的执行路径：",
    branchScenario: "正常浏览器 GET /",
    options: [
      { id: "env", text: "setRuntimeEnv(cloudflareEnv) 把 env 写到 globalThis" },
      { id: "wellknown", text: "判断 url.pathname 不是 /.well-known/，跳过短路" },
      { id: "render", text: "renderToReadableStream(<RemixServer .../>) 启动流式 SSR" },
      { id: "bot", text: "isbot('Mozilla/...') === false，不等 allReady" },
      { id: "out", text: "set Content-Type: text/html，return Response(body, status=200)" },
    ],
    correctAnswer: { type: "branch_trace", pathIds: ["env", "wellknown", "render", "bot", "out"] },
    explanation: {
      short: "env → 短路检查 → 渲染 → bot 判定 → 输出。",
      detail: "理解这个顺序对排障有用：在 env 写入之前 throw 表示 Cloudflare 没注入 env（wrangler 配置问题），在短路前 throw 但路径是 /.well-known 表示短路逻辑被改坏，渲染时 throw 走 onError 标志位，等等。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q10 RemixServerContext 类型",
    prompt: "entry.server.tsx 顶部 type RemixServerContext = ComponentProps<typeof RemixServer>['context']; 这个写法的目的？",
    options: [
      { id: "A", text: "从 <RemixServer> 组件的 props 类型里萃取 context 属性的类型——避免硬编码 entry context 形状，未来 React Router 升级也能跟着更新" },
      { id: "B", text: "运行时反射拿组件 props" },
      { id: "C", text: "强制 TypeScript 重新检查 RemixServer" },
      { id: "D", text: "和 TypeScript 没关系" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: '从组件 props 萃取类型——把"应该传给 <RemixServer> 的 context"这个事实当类型来源，不重复定义。',
      detail: "ComponentProps<typeof X> 是常见 TS 模式：从一个 React 组件里反推它的 props 形状。这里加 ['context'] 取出 context 子字段。好处：React Router 升级 RemixServer.context 类型时，这里跟着改、不用手动同步两份定义。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "typescript-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q11 CloudflareLoadContext 形状",
    prompt: "entry.server.tsx 里 type CloudflareLoadContext = AppLoadContext & { cloudflare?: { env?: RuntimeEnv } };，从 loadContext 取 env 的安全写法？",
    options: [
      { id: "A", text: "(loadContext as CloudflareLoadContext).cloudflare?.env" },
      { id: "B", text: "loadContext.cloudflare.env（直接断言）" },
      { id: "C", text: "loadContext as any" },
      { id: "D", text: "JSON.parse(JSON.stringify(loadContext))" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "用类型交叉 + 可选链——既保留原 AppLoadContext 类型，又加上 Cloudflare 特有字段，访问时 ?. 防 undefined。",
      detail: "AppLoadContext 是 Remix 框架级别的类型，不知道 Cloudflare 在它上面挂了什么。本项目用 & { cloudflare?: { env?: RuntimeEnv } } 显式声明扩展，再用 ?. 兜底——Local dev / 测试环境可能没注入 cloudflare 字段。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "typescript-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false",
    title: "Q12 entry.server 是否每次请求都重新执行",
    prompt: "entry.server.tsx 顶部的 import 与 const ABORT_DELAY = 5_000 在每次请求时都会重新执行一次。",
    correctAnswer: { type: "true_false", value: false },
    explanation: {
      short: "false——模块作用域代码只在 isolate 启动时执行一次，handleRequest 才是每个请求执行。",
      detail: "Cloudflare Worker isolate 的复用模型：同一个 isolate 处理多个请求时，模块顶部初始化代码（import、const）只跑一次。每次请求只重新进入 handleRequest。这意味着模块级别的 const、缓存对象等会被请求间共用——可以利用，但要小心跨请求污染。",
    },
    abilityTags: ["frontend.state.global", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "multi_choice",
    title: "Q13 entry.server 与 root.tsx 的分工",
    prompt: "对比 entry.server.tsx 与 root.tsx，下列哪些说法对？（多选）",
    options: [
      { id: "A", text: "entry.server.tsx 处理 Worker 级别的请求生命周期（短路 / 流式 / Content-Type）" },
      { id: "B", text: "root.tsx 处理路由树根组件（HTML shell、Outlet、theme cookie 读取）" },
      { id: "C", text: "改 entry.server 影响所有 SSR 请求；改 root.tsx 影响所有页面渲染" },
      { id: "D", text: "两个文件功能等价，可任选其一" },
    ],
    correctAnswer: { choiceIds: ["A", "B", "C"] },
    explanation: {
      short: "entry.server = 请求入口；root = 路由根。改 entry 影响所有 SSR；改 root 影响所有 UI。",
      detail: "排障时这条分工很重要：用户拿不到 HTML（白屏 / 503）应去看 entry.server；HTML 有但 React 树渲染异常应去看 root.tsx 或具体路由。entry 写错（比如忘了 set Content-Type）会让浏览器收到原文却不渲染，看起来像 root 错了。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "position_judgement",
    title: "Q14 改 SSR 超时应该改哪",
    prompt: "loader 偶发超过 5s，需要把 SSR 超时改大到 8s，最稳妥的位置？",
    options: [
      { id: "entry", text: "remix/app/entry.server.tsx 的 ABORT_DELAY 常量", locationHint: PRIMARY },
      { id: "wrangler", text: "wrangler.toml 增加超时配置", locationHint: "wrangler.toml" },
      { id: "loader", text: "在每个慢的 loader 里加 setTimeout", locationHint: "loader" },
      { id: "client", text: "客户端 fetch 加 AbortController", locationHint: "client" },
    ],
    correctAnswer: { positionId: "entry" },
    explanation: {
      short: "ABORT_DELAY 是 SSR 超时的唯一来源——改这里就行。",
      detail: "ABORT_DELAY 喂给 AbortSignal.timeout，传给 renderToReadableStream。改 wrangler.toml 是改 Worker 整体执行时间上限（CPU time），是不同的概念；客户端 AbortController 是另一个方向；在 loader 里 setTimeout 也不会影响 SSR 总超时。",
    },
    abilityTags: ["code.position.handler", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "debug",
    title: "Q15 排障 1 SSR 白屏",
    prompt: "线上某条路由打开就白屏，HTML 拿到但浏览器不渲染。第一个排查方向？",
    code: "// remix/app/entry.server.tsx\n// responseHeaders.set('Content-Type', 'text/html');",
    options: [
      { id: "ct", text: "看 Network 面板里这条响应的 Content-Type——是不是被某处覆盖成了 application/json 或丢了" },
      { id: "rebuild", text: "先重启 Worker" },
      { id: "css", text: "先改 Tailwind class" },
      { id: "loader", text: "先改 loader 缓存策略" },
    ],
    correctAnswer: { issueId: "ct" },
    explanation: {
      short: "白屏 + HTML 在 = 浏览器不当 HTML 解析；Content-Type 是头号嫌疑。",
      detail: "entry.server.tsx 这一行是 Content-Type 的唯一来源；如果 loader/route 里 throw 了一个非 HTML 响应（比如直接 new Response(JSON.stringify(...))），Content-Type 就跑偏了。Network 面板看一眼就清楚，比改代码快。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
    realWorldImpact: "Content-Type 失误会让全站某条路由所有用户白屏；时间久了会被搜索引擎降权。",
  }),
  q({
    type: "debug",
    title: "Q16 排障 2 流式中断",
    prompt: "用户反馈某些页面「加载了一半就停了」，HTML 看到一半。最可能的原因？",
    code: "// renderToReadableStream(..., { signal: AbortSignal.timeout(ABORT_DELAY), onError(err) { didError = true } })",
    options: [
      { id: "abort", text: "AbortSignal.timeout(5_000) 触发，loader 中某条慢链路超时；onError 写了 didError=true 但没向用户层暴露" },
      { id: "css", text: "CSS 有 display:none" },
      { id: "css2", text: "字体文件 404" },
      { id: "wrong", text: "browser cache 命中" },
    ],
    correctAnswer: { issueId: "abort" },
    explanation: {
      short: "5s 超时——loader 慢，流式中断。",
      detail: '现象就是 ABORT_DELAY 触发的标准表现：HTML 先出一部分（已经渲染好的），后面的 Suspense 边界被 abort，浏览器拿不到结尾。修法：(1) 找慢的 loader 把它从 SSR 里挪走，改成客户端 fetch；(2) 提高 ABORT_DELAY；(3) 给慢的部分套 React Suspense + 客户端水合。',
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
    realWorldImpact: "5s 超时 = SEO 权重下降 + 用户感觉站点卡——比单页 500 损伤更大。",
  }),
  q({
    type: "ai_review",
    title: "Q17 AI 改 ABORT_DELAY 到 0",
    prompt: "AI 看到'用户抱怨慢'就把 ABORT_DELAY 改成 0（'强制立即返回'）。这个改法合格吗？",
    options: [
      { id: "bad", text: "不合格：0 让 SSR 立即 abort，所有请求都拿到一半的 HTML，问题更严重" },
      { id: "ok", text: "合格：0 = 立刻返回，最快" },
      { id: "ok2", text: "合格：JS 里 0 等同 false，行为不变" },
      { id: "ok3", text: "合格：用户感受是变快了" },
    ],
    correctAnswer: { choiceId: "bad", riskIds: ["local_patch"] },
    aiReviewMeta: { riskTypeOptions: [{ id: "local_patch", label: "局部补丁冒充全局方案" }] },
    explanation: {
      short: "把 timeout 调到 0 是把「慢」换成「什么都没有」——更糟。",
      detail: "AI 经常这种'看到值就调到极端'的反模式。真问题是某条 loader 或上游调用慢，应该解决慢的那一环（缓存、并行化、改成客户端 fetch），而不是把上限去掉。",
    },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
    realWorldImpact: "ABORT_DELAY=0 上线 = 全站 SSR 拿不到完整 HTML。",
    aiReviewRisk: "AI 把时间常量调极端是高频错改——根因是不理解上下文。",
  }),
  q({
    type: "code_fix",
    title: "Q18 一行修复忘记 setRuntimeEnv",
    prompt: "假设 entry.server.tsx 把 setRuntimeEnv 那两行删了。补一行最小修复。",
    codeFixBaseline: "  const cloudflareEnv = (loadContext as CloudflareLoadContext).cloudflare?.env;\n  // TODO: 守门缺失",
    correctAnswer: {
      type: "code_fix",
      patchedCode: "  const cloudflareEnv = (loadContext as CloudflareLoadContext).cloudflare?.env;\n  if (cloudflareEnv) setRuntimeEnv(cloudflareEnv);",
    },
    expectedFixScope: "one-line",
    serverClientBoundary: "server",
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    touchedFiles: [PRIMARY],
    explanation: {
      short: "if (cloudflareEnv) setRuntimeEnv(cloudflareEnv); 一行还原。",
      detail: "本地 dev 环境 loadContext.cloudflare 可能是 undefined，所以 if 守一下；实际生产 Cloudflare 一定注入。原文件就是这么写的。",
    },
    realWorldImpact: "缺这行 → 任何 .server 文件 getEnvVar 都拿不到 env → D1 / AI / secrets 全炸。",
  }),
  q({
    type: "single_choice",
    title: "Q19 entry.server 与 worker.ts 的关系",
    prompt: "remix/worker.ts 与 entry.server.tsx 的调用顺序？",
    options: [
      { id: "A", text: "请求先到 worker.ts（Cloudflare Worker fetch handler）→ React Router 服务端 handler → entry.server.tsx 的 handleRequest" },
      { id: "B", text: "顺序相反" },
      { id: "C", text: "并行" },
      { id: "D", text: "没有关系" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "worker.ts 是 Cloudflare 入口；React Router 内部把 handleRequest 调起。",
      detail: "理解这条链对排障很关键：纯静态资产 / .well-known 在 worker.ts 层就被处理掉，不会进 entry.server；某些 middleware（CORS、IP 解析）写在 worker.ts 比写在 entry.server 更合适。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "worker.ts"],
  }),
  q({
    type: "true_false",
    title: "Q20 entry.server 是否能写业务",
    prompt: "把「用户登录后写一行 D1 audit」的逻辑写在 entry.server.tsx 里是合理选择，因为它每个请求都执行。",
    correctAnswer: { type: "true_false", value: false },
    explanation: {
      short: "false——entry.server 只管 SSR 渲染，写业务会污染所有请求且很难加守门。",
      detail: "audit 应该写在产生事件的那一层（services/ 或 routes/ 的 action）。塞到 entry.server 等于「每个请求都尝试 audit」——不仅成本高（D1 写每次请求都触发），还很难判断是不是该 audit 这个请求。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q21 React 19 升级影响",
    prompt: "把项目升级到 React 19，entry.server.tsx 哪一行最可能要动？",
    options: [
      { id: "A", text: "顶部的 // @ts-expect-error 注释——React 19 修了 server.browser 的类型，注释变成多余会被 ts-expect-error 自身报错" },
      { id: "B", text: "ABORT_DELAY 必须改为 ms 单位" },
      { id: "C", text: "整个文件需要重写" },
      { id: "D", text: "不需要任何改动" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "@ts-expect-error 在不再需要时会自己报错，必须删除。",
      detail: "@ts-expect-error 的语义是「下面这行有错，没错时报错给我」。React 19 修了类型后下面这行不会再有错，注释自己变错。这是有意识的工程设计：让 hack 在不再需要时主动通知你。",
    },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "typescript-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "review_comment",
    title: "Q22 PR Review · 把流式去掉",
    prompt: '同事的 PR 把 entry.server.tsx 里 await body.allReady 改成无条件等所有内容都准备好再返回（"觉得流式有点不稳"）。写一段 PR Review 评语指出问题。',
    diffSnippet: "--- a/app/entry.server.tsx\n+++ b/app/entry.server.tsx\n@@\n-  if (isbot(request.headers.get('user-agent') || '')) {\n-    await body.allReady;\n-  }\n+  await body.allReady;\n",
    correctAnswer: { type: "review_comment", comment: "no correct answer — AI grades" },
    expectedFixScope: "single-function",
    serverClientBoundary: "server",
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "free-response",
    touchedFiles: [PRIMARY],
    explanation: {
      short: "评语应当点出：失去流式 = TTFB 变长、首屏慢；爬虫与用户的体验权衡是分流的初衷。",
      detail: "好的 review 至少包含：(1) 这个改动让真实用户也走 await，TTFB 变长；(2) 流式只是给爬虫不可靠，不是普遍不稳；(3) 如果担心稳定性，应该写测试或 metrics 监控，而不是一刀切删流式。",
    },
    realWorldImpact: "全站 TTFB 直接增长（loader 慢→首屏慢），核心 web vitals 退化。",
  }),
];
