/**
 * Real questions for site-01-repo-map / repo-capstone.
 *
 * Anchor: 整个 remix/app/ 的"职责落点决策树"。
 *   每题给一个具体的需求场景，选最稳的落点。
 * 学习目标: 接到一个 ticket，能判断"这要放在哪几个目录"，避免把所有逻辑都堆到一个文件。
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/";

export const repoCapstoneQuestions: RealQ[] = [
  q({
    type: "position_judgement",
    title: "Q1 给消息板加敏感词过滤",
    prompt: "给留言板加一道'写消息前过滤敏感词'的守门——能拦下违规内容也能审计。最佳落点？",
    options: [
      { id: "lib", text: "remix/app/lib/sensitive-word.server.ts（纯 util，输入字符串返回是否合规）+ services/messages.server.ts 调用它", locationHint: "app/lib/" },
      { id: "route", text: "remix/app/routes/messages.tsx 的 action 内联 if(/badword/.test(text)) return 400", locationHint: "app/routes/" },
      { id: "client", text: "remix/app/components/messages/MessageForm.tsx 客户端 disabled", locationHint: "app/components/" },
      { id: "css", text: "Tailwind 隐藏不合规消息", locationHint: "css" },
    ],
    correctAnswer: { positionId: "lib" },
    explanation: {
      short: "守门基础放 lib/.server，业务编排在 services/，路由薄、客户端不能兜底。",
      detail: "客户端 disabled 任何攻击者都能绕过；路由内联让多个入口要重复一遍；纯 util 在 lib/ 让规则可单元测试、可被多个 route/service 复用。这条'守门下沉到 lib，编排在 services'是项目里最常用的分层模板。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture", "backend.validation.field"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: ["app/lib/", "app/services/", "app/routes/"],
  }),
  q({
    type: "position_judgement",
    title: "Q2 加'获取当前用户消息列表'API",
    prompt: "为前端 Header 添加'红点'功能：需要一个 API 返回未读消息数。最佳落点？",
    options: [
      { id: "api", text: "remix/app/routes/api.unread-count.ts（resource route，loader 调 lib/messages.server.countUnread）", locationHint: "app/routes/" },
      { id: "lib", text: "把整个端点逻辑写在 remix/app/lib/unread.server.ts 里 export default", locationHint: "app/lib/" },
      { id: "header", text: "在 Header.tsx useEffect fetch '/messages' 然后 client 端数", locationHint: "app/components/" },
      { id: "root", text: "塞到 root loader 里", locationHint: "app/root.tsx" },
    ],
    correctAnswer: { positionId: "api" },
    explanation: {
      short: "API 端点 = api.* resource route；Header 通过 fetch（或 root loader 注入）拿数据。",
      detail: "正经 API 应该有自己的 URL 与缓存策略；放 lib/ 不是 URL 入口；让 Header 自己 fetch 是 client/server 状态分裂；塞 root loader 让全站都读一次（即使在 messages 页面也读，重复）。判断标准：是否需要独立 URL + 独立缓存策略 → 是 → routes/api.*。",
    },
    abilityTags: ["code.position.handler", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/api.unread-count.ts", "app/lib/messages.server.ts"],
  }),
  q({
    type: "position_judgement",
    title: "Q3 加'用户登录后弹一个欢迎条'",
    prompt: "用户首次登录后弹一个 toast '欢迎回来'。该写在哪？",
    options: [
      { id: "client", text: "remix/app/components/auth/LoginSuccessVeil.tsx（已有）扩展，或新增 LoginSuccessToast.tsx——纯 client 行为", locationHint: "app/components/auth/" },
      { id: "root", text: "root loader 检测 session 后返回 flag，root 层用 useEffect 弹", locationHint: "app/root.tsx" },
      { id: "server", text: "lib/auth.server.ts 的 sign-in 后 set 一个 'show-welcome' cookie", locationHint: "app/lib/auth.server.ts" },
      { id: "cdn", text: "Cloudflare 边缘 Worker 注入", locationHint: "edge" },
    ],
    correctAnswer: { positionId: "client" },
    explanation: {
      short: "登录后欢迎是纯 client 体验——已经有 LoginSuccessVeil 在那条路径上扩展即可。",
      detail: "把'是否首次'放 cookie 是过度设计——登录的瞬间客户端已经知道；root loader + useEffect 也行但污染了根 loader 数据形状。最便宜：在登录成功的客户端代码（LoginSuccessVeil 内）触发 toast。",
    },
    abilityTags: ["frontend.event.click", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: ["app/components/auth/"],
  }),
  q({
    type: "position_judgement",
    title: "Q4 加'每条消息出/进时记 D1 audit'",
    prompt: "需要每条消息发出/接收时往 D1 写一行审计。落点？",
    options: [
      { id: "service", text: "remix/app/services/messages.server.ts 在 createMessage 函数体里调 lib/audit.server.ts.write({...}) ——业务编排层", locationHint: "app/services/" },
      { id: "do", text: "RateLimiterDO 内部插入审计", locationHint: "DO" },
      { id: "client", text: "客户端 fetch 完之后再 fetch '/api/audit'", locationHint: "client" },
      { id: "entry", text: "entry.server.tsx 拦所有请求", locationHint: PRIMARY },
    ],
    correctAnswer: { positionId: "service" },
    explanation: {
      short: "audit = 业务事件，归 services 编排；lib/audit.server.ts 是写入 util。",
      detail: "DO 已经被限流占用、加业务逻辑会让 DO 边界混乱；客户端二次请求让审计不可信（用户可以跳过）；entry.server 全局拦截会审计无关请求。services 是业务编排层，写 audit 的天然位置。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: ["app/services/", "app/lib/"],
  }),
  q({
    type: "single_choice",
    title: "Q5 路由薄 vs 厚的判断",
    prompt: "什么情况下 route 文件应该长（>200 行），什么情况下应该薄？",
    options: [
      { id: "A", text: "route 应该薄——loader/action 调 services/，导出 default 渲染 components/ 里的组件。route 自己持有的逻辑越少越好" },
      { id: "B", text: "route 应该厚——所有逻辑都集中在一个 route 里方便查" },
      { id: "C", text: "看心情" },
      { id: "D", text: "和 layer 嵌套深度成正比" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "route 薄 = 只做 URL 入口与编排；逻辑沉到 services/lib/，UI 沉到 components/。",
      detail: "薄路由的好处：(1) 测试友好——核心逻辑在 services/lib，测试它们就够；(2) 复用——多个 route 可以共用同一个 service；(3) 演化灵活——逻辑迁移不动 URL 结构。看 remix/app/routes/messages.tsx 与 lib/messages.server.ts、components/messages/* 的分布，正是这种模式。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: ["app/routes/", "app/services/", "app/lib/", "app/components/"],
  }),
  q({
    type: "ai_review",
    title: "Q6 AI 把守门 + 限流 + 业务全塞到 route",
    prompt: 'AI 觉得"分散到三层不直观"，于是把守门 + 限流 + D1 写入 + audit 全部塞进 routes/api.feedback.ts 一个文件。这个改法合格吗？',
    options: [
      { id: "bad", text: "不合格：复用变成复制粘贴；测试要 mock 整个 Worker；下一条 API 再写一遍。这是把分层架构的好处全部抹掉" },
      { id: "ok", text: "合格：集中代码方便阅读" },
      { id: "ok2", text: "合格：少一层 import" },
      { id: "ok3", text: "合格：等等再分层" },
    ],
    correctAnswer: { choiceId: "bad", riskIds: ["architecture_boundary"] },
    aiReviewMeta: { riskTypeOptions: [{ id: "architecture_boundary", label: "破坏分层架构边界" }] },
    explanation: {
      short: "把守门 / 限流 / 业务 / audit 都塞 route = 复用全砍，下一条 API 全再写一遍。",
      detail: "分层不是为了'优雅'——是为了'下一次需要时只改一个地方'。守门写在 services/guard.server，下一条 API 直接调；写在 route 内联，每条 API 都要 copy-paste，也最容易在某条上忘记。",
    },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/", "app/services/", "app/lib/"],
    realWorldImpact: "下次有新 API 要复用守门时，发现得手动复制——时间一长，规则不同步，安全漏洞。",
    aiReviewRisk: "AI 把'代码集中'当成'代码组织好'是高频反模式；前者是表象，后者要求按职责分层。",
  }),
  q({
    type: "sort",
    title: "Q7 加'用户头像上传'功能的目录顺序",
    prompt: "增加'用户上传头像存 R2、URL 写 D1'的功能，从底向上的目录顺序：",
    sortItems: [
      { id: "s1", text: "migrations/ 加 SQL，给 user 表加 avatar_url 列", title: "DB schema", category: "backend" },
      { id: "s2", text: "lib/r2-upload.server.ts，封装 PUT 到 R2 的基础函数", title: "lib 层", category: "backend" },
      { id: "s3", text: "services/avatar.server.ts，验证 + 存 R2 + 写 D1 + audit 一条龙", title: "service 层", category: "backend" },
      { id: "s4", text: "routes/api.avatar-upload.ts，action 接收 multipart 调 service", title: "route 层", category: "backend" },
      { id: "s5", text: "components/auth/AvatarUploader.tsx，UI 组件 + 客户端预览", title: "组件层", category: "frontend" },
    ],
    correctAnswer: { type: "sort", itemIds: ["s1", "s2", "s3", "s4", "s5"] },
    explanation: {
      short: "数据 → 基础函数 → 业务编排 → 路由入口 → UI——这是项目的标准 5 层结构。",
      detail: "每一步都依赖下一层：service 调 lib，route 调 service，UI 通过 fetch 调 route。倒着写就是 AI 经典反模式（先 UI 再补后端），等真要 D1 写入时发现 schema 不够，回头改。",
    },
    abilityTags: ["code.position.handler", "project.modify.fullstack"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: ["migrations/", "app/lib/", "app/services/", "app/routes/", "app/components/"],
  }),
  q({
    type: "single_choice",
    title: "Q8 services 与 lib 的判断",
    prompt: "新加一个'把 markdown 转 HTML'的函数，应该放？",
    options: [
      { id: "lib", text: "remix/app/lib/markdown.ts（无领域、纯函数，可前后端共用——服务端 SSR 渲染、客户端预览都用得到）" },
      { id: "services", text: "remix/app/services/markdown.server.ts" },
      { id: "components", text: "remix/app/components/common/markdown.tsx" },
      { id: "utils", text: "remix/app/utils/markdown.ts" },
    ],
    correctAnswer: { choiceId: "lib" },
    explanation: {
      short: "纯函数、无领域、可前后端共用 → lib/。.server 后缀别加（要让 client 也用）。",
      detail: "services/ 是业务编排（'渲染消息时把 md 转 html 再过滤敏感词再写 D1'这种），里面会 import 多个 lib。markdown 转换本身是孤立函数，归 lib/。utils/ 是框架适配层（env、theme），不放业务相关。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "shared",
    touchedFiles: ["app/lib/", "app/services/", "app/utils/"],
  }),
  q({
    type: "true_false",
    title: "Q9 测试归处",
    prompt: "测试文件应该放在被测代码相邻位置，比如 lib/auth.server.test.ts 与 lib/auth.server.ts 同目录。",
    correctAnswer: { type: "true_false", value: false },
    explanation: {
      short: "false——本项目惯例是放 tests/ 顶层（与 lea/ Code Coach 项目相同模式），不和源文件同目录。",
      detail: "Cloudflare Worker 项目里 tests/ 顶层有几个好处：(1) Vite 容易排除测试文件不打进 bundle；(2) 一眼能看出'测试是否齐'；(3) 多个被测文件可以共享 setup。但这是项目选择，不是绝对——某些项目（如 Vite 默认）确实推荐相邻摆放。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "shared",
    touchedFiles: ["tests/"],
  }),
  q({
    type: "multi_choice",
    title: "Q10 一次正确的 PR 涉及哪些文件",
    prompt: "为消息板加'匿名留言'功能（通过 cookie 传匿名 id 不需登录）。一次合格的 PR 至少涉及哪些目录的改动？（多选）",
    options: [
      { id: "lib", text: "lib/messages.server.ts 或 lib/anon.server.ts（基础读写）" },
      { id: "service", text: "services/ 中的留言编排代码（如果有，否则在 route 里）" },
      { id: "route", text: "routes/messages.tsx（接收 form 提交）" },
      { id: "components", text: "components/messages/* （UI 调整）" },
      { id: "migrations", text: "migrations/* （加 anon_id 列）" },
      { id: "wrangler", text: "wrangler.toml 加新 binding" },
    ],
    correctAnswer: { choiceIds: ["lib", "route", "components", "migrations"] },
    explanation: {
      short: "lib（读写）+ route（接受 form）+ components（UI）+ migration（schema）。services 视项目当前结构定，wrangler 不需要改（cookie 不用新 binding）。",
      detail: "判断'每个 PR 该动多少层'：(1) 改了 D1 schema → 必有 migration；(2) 改了 server 行为 → 必动 lib/services/route 中至少一层；(3) 用户能看到效果 → 必动 components/* 或 routes/* 的 UI 部分。这条 PR 走 4 层，正常。",
    },
    abilityTags: ["project.modify.fullstack", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: ["app/lib/", "app/routes/", "app/components/", "migrations/"],
  }),
  q({
    type: "position_judgement",
    title: "Q11 Better Auth 钩子放哪",
    prompt: "Better Auth 在 sign-in 成功后想触发一个'写一行 D1 audit'。具体代码该写在哪？",
    options: [
      { id: "auth", text: "remix/app/lib/auth.server.ts 的 Better Auth 配置 events.signIn.after 回调里调 lib/audit.server.write({...})", locationHint: "app/lib/auth.server.ts" },
      { id: "route", text: "在 api.auth.$.ts 内联", locationHint: "app/routes/api.auth.$.ts" },
      { id: "client", text: "客户端登录成功后再 fetch '/api/audit'", locationHint: "client" },
      { id: "do", text: "RateLimiterDO 写一份", locationHint: "DO" },
    ],
    correctAnswer: { positionId: "auth" },
    explanation: {
      short: "Better Auth 配置在 lib/auth.server.ts，事件钩子也在那里——就近 hook。",
      detail: "Better Auth 提供生命周期钩子（events.signIn / events.signOut），在配置文件里挂上去最干净。route 内联会在每条 OAuth 回调路径都要重复；client 兜底不可靠（用户禁 JS）；DO 不该接业务事件。",
    },
    abilityTags: ["code.position.handler", "backend.session.cookie"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: ["app/lib/auth.server.ts", "app/lib/audit.server.ts"],
  }),
  q({
    type: "single_choice",
    title: "Q12 何时写新 service vs 复用旧 lib",
    prompt: '什么情况下应该新建 services/foo.server.ts，而不是把逻辑塞到现有 lib/foo.server.ts？',
    options: [
      { id: "A", text: "当一个操作横跨多个领域（例如：写消息 = 校验 + audit + 通知 + 邮件），且会被多个 route 复用——这是业务编排，归 services" },
      { id: "B", text: "代码超过 500 行就该新建 service" },
      { id: "C", text: "需要异步就新建" },
      { id: "D", text: "永远塞进 lib/" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "service = 多 lib 的编排器；单一职责的纯函数留在 lib/。",
      detail: "判断标准：(1) 这个函数只做一件事吗？是 → lib；(2) 这个函数把 N 个 lib 的能力组合成业务流程吗？是 → service；(3) 还会被多个 route 共用吗？是 → 加强 service 的必要。两种文件不冲突，分工清楚。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: ["app/lib/", "app/services/"],
  }),
  q({
    type: "true_false",
    title: "Q13 components 里能 import services",
    prompt: "在 components/messages/MessageForm.tsx 里 import services/messages.server.ts，编译会过。",
    correctAnswer: { type: "true_false", value: false },
    explanation: {
      short: "false——components 是 client，import .server 会被 React Router 编译器拒绝。",
      detail: ".server 文件的存在意义就是不进 client bundle。当 components 想要 server 数据时，正确路径是 route loader 拿 → 通过 props/Outlet 上下文注入。这是为什么很多项目没法'懒得想'地直接跨边界——边界保护是有意识的。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "shared",
    touchedFiles: ["app/components/", "app/services/"],
  }),
  q({
    type: "ai_review",
    title: "Q14 AI 把 .server.ts 删掉",
    prompt: "AI 看到 lib/messages.server.ts 不能 import 进 client，'重构'时把 .server 删掉变成 lib/messages.ts，又把 D1 binding 引用去掉换成 fetch('/api/messages')。这个改法？",
    options: [
      { id: "bad", text: "不合格：把 server 逻辑改成客户端 fetch = 失去类型契约 + 多一次 HTTP + SSR 不能用；本质是把分层往后退" },
      { id: "ok", text: "合格：客户端 fetch 通用" },
      { id: "ok2", text: "合格：少一层抽象" },
      { id: "ok3", text: "合格：能 import 到客户端就行" },
    ],
    correctAnswer: { choiceId: "bad", riskIds: ["client_server_mix", "loader_action_mix"] },
    aiReviewMeta: { riskTypeOptions: [
      { id: "client_server_mix", label: "客户端/服务端边界混淆" },
      { id: "loader_action_mix", label: "loader/action 职责混淆" },
    ]},
    explanation: {
      short: "把 server util 退化成 client fetch = 失去 SSR、失去类型、失去事务保证。",
      detail: "正确做法：组件需要数据 → route loader 拿 → 通过 useLoaderData 注入。SSR 一次性返回完整 HTML，客户端水合接管，零额外 fetch。AI 这种'退化分层让事情变简单'是高频反模式——简单是表象，代价是性能与类型安全。",
    },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: ["app/lib/", "app/components/"],
    realWorldImpact: "全站首屏多一次请求 + 首屏空白 + 类型契约丢失。",
    aiReviewRisk: "AI 不理解 SSR 时常做这种重构。",
  }),
  q({
    type: "single_choice",
    title: "Q15 Cloudflare 限流 + 业务限流",
    prompt: "Cloudflare 的 RATE_LIMITER Durable Object 在 wrangler.toml 已配置，但业务层（lib/rate-limit.server.ts）里也有限流逻辑。两层关系？",
    options: [
      { id: "A", text: "DO 提供「持久计数与窗口化」原语；lib/rate-limit.server.ts 在其上封装业务规则（哪条 API 限多少、命中后返回什么错误）" },
      { id: "B", text: "重复实现，应删一个" },
      { id: "C", text: "DO 是 fallback，lib 是主路径" },
      { id: "D", text: "完全无关" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "DO = 计数原语；lib = 业务规则封装。两层各司其职。",
      detail: "Cloudflare DO 提供的是'强一致计数器'这种基础能力——不能直接给业务用，因为业务还要决定窗口大小、key 怎么算（按 IP 还是按用户）、超限后该 429 还是 silently drop。这些规则属于业务，归 lib/。",
    },
    abilityTags: ["code.position.handler", "backend.rateLimit", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: ["app/lib/rate-limit.server.ts", "app/lib/rate-limiter-do.ts", "wrangler.toml"],
  }),
  q({
    type: "position_judgement",
    title: "Q16 给 nemesis 增加'某模型每用户每天上限'",
    prompt: "Nemesis 聊天里 grok 模型成本最高，需要限'每用户每天最多 5 次'。代码该写在？",
    options: [
      { id: "service", text: "remix/app/services/nemesis-rate-limit.server.ts（已存在）扩展 +'按用户 + 按模型'计数", locationHint: "app/services/nemesis-rate-limit.server.ts" },
      { id: "route", text: "routes/api.nemesis.ts 入口加 if(model === 'grok')", locationHint: "app/routes/api.nemesis.ts" },
      { id: "client", text: "前端按钮 disabled 防止超限", locationHint: "client" },
      { id: "wrangler", text: "wrangler.toml 配置", locationHint: "wrangler.toml" },
    ],
    correctAnswer: { positionId: "service" },
    explanation: {
      short: "Nemesis 已有 services/nemesis-rate-limit.server.ts——业务规则归这里。",
      detail: "已存在的服务文件就是为了'集中限流业务规则'而生。不在那里加规则、反而把判断散到 route，是给未来留坑。services/nemesis-rate-limit.server.ts 又会调 lib/rate-limit.server.ts（基础设施层），再去找 DO。",
    },
    abilityTags: ["code.position.handler", "backend.rateLimit"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: ["app/services/nemesis-rate-limit.server.ts"],
  }),
  q({
    type: "single_choice",
    title: "Q17 Worker 入口 vs entry.server",
    prompt: "remix/worker.ts 与 entry.server.tsx 哪个先执行？什么逻辑该放 worker.ts？",
    options: [
      { id: "A", text: "worker.ts 先（Cloudflare 收到请求第一站）；entry.server 再（React Router 内部调用）。worker.ts 适合：纯静态资产命中、CORS 头、IP 解析；entry.server 适合 SSR 渲染" },
      { id: "B", text: "顺序相反" },
      { id: "C", text: "并发执行" },
      { id: "D", text: "等价" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "worker.ts → React Router → entry.server。worker 层适合中间件（CORS、IP、static-asset 短路）。",
      detail: "理解这条链对扩展中间件很重要。比如想'非 prod 环境拒绝所有请求'，写 worker.ts 比 entry.server 早一拍——entry 处理时已经走完了一些 RR 解析。worker.ts 是更早的入口。",
    },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: ["worker.ts", "app/entry.server.tsx"],
  }),
  q({
    type: "true_false",
    title: "Q18 generated/ 与 data/ 区别",
    prompt: "generated/ 和 data/ 都是脚本产物目录，可以混用。",
    correctAnswer: { type: "true_false", value: false },
    explanation: {
      short: "false——generated/ 是临时产物（image-manifest 等），data/ 是稳定产物（lyrics/*.json 是从 .lrc 编译的）。",
      detail: "细微但重要的区分：generated/ 里的内容会经常重写，git 看到大量 diff；data/ 里的更稳定。两者放一起会让'什么时候 git diff 是预期的'变模糊。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: ["app/generated/", "app/data/"],
  }),
  q({
    type: "ai_review",
    title: "Q19 AI 把 nemesis 的 prompt config 移到 client",
    prompt: 'AI 觉得"prompt 文本是给用户看的"，把 app/nemesis/prompts/ 整个目录改名 components/nemesis/prompts/ 并加上 .client。这个改法？',
    options: [
      { id: "bad", text: "不合格：prompt config 是服务端模型路由的输入，是领域模块；改成 client 后服务端拿不到 prompt 调模型" },
      { id: "ok", text: "合格：prompt 是给用户看的" },
      { id: "ok2", text: "合格：和 UI 接近" },
      { id: "ok3", text: "合格：缩短调用距离" },
    ],
    correctAnswer: { choiceId: "bad", riskIds: ["architecture_boundary", "client_server_mix"] },
    aiReviewMeta: { riskTypeOptions: [
      { id: "architecture_boundary", label: "破坏架构边界" },
      { id: "client_server_mix", label: "客户端/服务端边界混淆" },
    ]},
    explanation: {
      short: "prompt config 是 server 编排的输入，不是 UI 文案——把它移到 client 等于让 server 拿不到 prompt。",
      detail: "AI 容易把'用户最终看到的字符串'和'生成它的逻辑'混淆。Prompt config 只在服务端被读，组装成最终 prompt 调上游模型。client 拿到的是模型 response（不是 prompt）。",
    },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: ["app/nemesis/", "app/components/nemesis/"],
    realWorldImpact: "Nemesis 服务端拿不到 prompt 配置 → 模型路由整段崩。",
    aiReviewRisk: "AI 把 server-only 的领域配置当 UI 资源是高频反模式。",
  }),
  q({
    type: "review_comment",
    title: "Q20 PR Review 同事一文件 800 行",
    prompt: "同事的 PR：在 routes/api.checkin.ts 写了 800 行代码，包含守门 + 限流 + D1 写入 + 邮件通知 + audit。写一段 PR Review 评语指出问题与重构方向。",
    diffSnippet: "--- a/app/routes/api.checkin.ts\n+++ b/app/routes/api.checkin.ts\n@@ +1,800 @@\n+ // 800 行代码\n+ // 守门 / 限流 / D1 / 邮件 / audit 都在 action 内联\n",
    correctAnswer: { type: "review_comment", comment: "no correct answer — AI grades" },
    expectedFixScope: "single-function",
    serverClientBoundary: "server",
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "free-response",
    touchedFiles: ["app/routes/", "app/services/", "app/lib/"],
    explanation: {
      short: "好评语应当：(1) 指出 route 应该薄；(2) 建议拆分到 lib/services；(3) 给重构步骤；(4) 说明长期收益（可测试、可复用）。",
      detail: "完整答案至少包含：(1) 「route 应保持薄，800 行不可维护」；(2) 「建议把守门拆到 services/guard, 限流到 services/rate-limit, D1 写入到 lib/checkin.server, 邮件到 lib/email」；(3) 「拆完 route 应该 < 50 行」；(4) 「拆分让下一个『打卡奖励 API』能直接复用守门与限流，不用 copy-paste」。",
    },
    realWorldImpact: "800 行 route 上线后下次有人改'打卡规则'要在一坨里找；测试要 mock 整个 Worker；下一条相似 API 重写一遍。",
  }),
  q({
    type: "single_choice",
    title: "Q21 monorepo 与 remix 边界",
    prompt: "Code Coach 项目（lea/）与 remix/ 子项目同 repo，Code Coach 的代码是否能 import remix/ 的代码？",
    options: [
      { id: "A", text: "不能。tsconfig.json 里 exclude remix/**，且生产时 Code Coach 的 build 不知道 remix/ 存在；只能通过 dev-only 的 /__remix-assets/* HTTP 端点读 remix 文件" },
      { id: "B", text: "能，直接 import" },
      { id: "C", text: "需要 npm link" },
      { id: "D", text: "靠 monorepo workspace" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "Code Coach 与 remix/ 物理隔离——只能 dev-only HTTP 读取，不能直接 import。",
      detail: "这是有意设计：让 Code Coach 把 remix 当成'被学习的目标项目'，不依赖它的代码。生产 Worker 里没有 remix/ 文件夹；scripts/remix-assets.ts 只在 Node 脚本（seed-local 等）里能 fs.readFileSync remix 路径，且 Vite 插件 vite-remix-assets-plugin 只在 dev 暴露 /__remix-assets/list 与 /read 这两个端点。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: ["tsconfig.json", "scripts/remix-assets.ts", "scripts/vite-remix-assets-plugin.ts"],
  }),
  q({
    type: "free_explain",
    title: "Q22 自由复述 这次学到的'落点判断'",
    prompt: "用自己的话写一份'我接到一个 ticket 后该怎么决定每段代码落在哪'的简短指南——按你这一章学到的来。",
    code: "// 5 层结构提示：\n// 1. migrations/ (D1 schema)\n// 2. app/lib/*.server.ts (基础读写、纯 util)\n// 3. app/services/*.server.ts (业务编排，调多个 lib)\n// 4. app/routes/*.tsx (URL 入口，薄)\n// 5. app/components/*.tsx (UI)\n// 边界标记：.server / .client",
    correctAnswer: { type: "free_explain", text: "no correct answer — AI grades" },
    explanation: {
      short: "好答案应该覆盖：自底向上写代码、route 保持薄、组件按领域分、.server / .client 是硬边界、避免 AI 反模式。",
      detail: "完整答案应当包含：(1) 5 层结构（migrations/lib/services/route/components）；(2) 自底向上 vs 自顶向下的对比；(3) .server 与 .client 的硬约束；(4) services 与 lib 的差别（编排 vs 基础）；(5) 看到 route 文件 > 200 行 = 警报；(6) AI 高频反模式（混分层、删 .server、退化为 fetch）；(7) 写代码前 30 秒先想：这个职责属于哪一层、哪个领域。",
    },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "free-response",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY],
  }),
];
