/**
 * Real questions for site-01-repo-map / routes-folder.
 *
 * Anchor: remix/app/routes/ 下的真实文件名。
 *   _index.tsx, anime.tsx, api.auth.$.ts, api.claim-token.tsx, api.nemesis-feedback.ts,
 *   api.nemesis.ts, auth.sign-out.tsx, auth.tsx, chat.tsx, cv.tsx, gallery.tsx,
 *   game.$platform.tsx, game._index.tsx, game.tsx, messages.tsx, music.tsx,
 *   rapid-layers-preview.tsx, sitemap[.]xml.tsx, updates.tsx, xiao.tsx
 * 学习目标: 文件名 ↔ URL 一一对应；动态段、splat、index、转义字符各自的语义。
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/";

export const routesFolderQuestions: RealQ[] = [
  q({
    type: "single_choice",
    title: "Q1 _index.tsx 对应的 URL",
    prompt: "remix/app/routes/_index.tsx 对应的 URL？",
    options: [
      { id: "A", text: "/（站点根路径）" },
      { id: "B", text: "/index" },
      { id: "C", text: "/_index" },
      { id: "D", text: "动态决定" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "_index = 父级 layout 的索引子路由；顶层 _index.tsx 就是 /。",
      detail: "下划线开头的 _index 不会成为 URL 段——它表示'当前 layout 的默认子路由'。在 routes/ 顶层，它就是站点首页 /。在 routes/game._index.tsx 那种位置，它表示 /game 的默认内容。",
    },
    abilityTags: ["code.position.handler", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/_index.tsx"],
  }),
  q({
    type: "single_choice",
    title: "Q2 文件名点号 vs 嵌套",
    prompt: "remix/app/routes/game.$platform.tsx 与 game._index.tsx 与 game.tsx 三者关系？",
    options: [
      { id: "A", text: "game.tsx 是父 layout（提供 Outlet）；game._index.tsx 是 /game 的默认子页；game.$platform.tsx 是 /game/<动态段> 的子页" },
      { id: "B", text: "三者无关，平级路由" },
      { id: "C", text: "game._index 与 game.tsx 等价" },
      { id: "D", text: "$platform 必须放在子目录" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "game.tsx = 父；game._index.tsx = /game 的默认；game.$platform.tsx = /game/:platform。",
      detail: "扁平文件名约定：`game` 部分共享，`.` 后是子段、`._index` 是默认、`.$xxx` 是动态。这种'文件名即路由树'的设计让目录和路由结构 1:1 对齐，看一眼文件夹就知道 URL 形状。",
    },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/game.tsx", "app/routes/game._index.tsx", "app/routes/game.$platform.tsx"],
  }),
  q({
    type: "single_choice",
    title: "Q3 splat 路由 api.auth.$.ts",
    prompt: "remix/app/routes/api.auth.$.ts 匹配的 URL 集合？",
    options: [
      { id: "A", text: "/api/auth 之后的所有路径（/api/auth/google/callback、/api/auth/sign-out 等），splat 段落进 params['*']" },
      { id: "B", text: "只匹配 /api/auth" },
      { id: "C", text: "只匹配 /api/auth/$" },
      { id: "D", text: "整个 / 站点的请求" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "裸 $ = catch-all，匹配 /api/auth 之下任意路径。",
      detail: "Better Auth 的 OAuth 回调 URL 形式各异（/api/auth/google/callback、/api/auth/sign-out、/api/auth/sign-in 等），用单个 splat 路由统一接进来再交给 Better Auth handler 派发——避免为每条 OAuth 路由各写一个文件。",
    },
    abilityTags: ["code.position.handler", "backend.session.cookie"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/api.auth.$.ts"],
  }),
  q({
    type: "single_choice",
    title: "Q4 sitemap 文件名转义",
    prompt: "remix/app/routes/sitemap[.]xml.tsx 的 URL 是？",
    options: [
      { id: "A", text: "/sitemap.xml（[.] 转义把'.'变成 URL 字面量而不是文件名分隔符）" },
      { id: "B", text: "/sitemap/xml" },
      { id: "C", text: "/sitemap%5B.%5Dxml" },
      { id: "D", text: "/sitemap[.]xml" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "[.] 转义点号——URL 是 /sitemap.xml。",
      detail: "因为 . 默认表示路由层级。要在 URL 里出现真正的点号（如 .xml 后缀让爬虫识别），就要在文件名里写 [.]。Wikipedia.json、cv.pdf 这类 URL 同理。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/sitemap[.]xml.tsx"],
  }),
  q({
    type: "multi_choice",
    title: "Q5 真实存在的资源路由",
    prompt: "remix/app/routes/ 下面真实存在的 'API/资源路由'（不渲染 UI 只 export loader/action）有？（多选）",
    options: [
      { id: "auth", text: "api.auth.$.ts" },
      { id: "claim", text: "api.claim-token.tsx" },
      { id: "nemesis", text: "api.nemesis.ts" },
      { id: "feedback", text: "api.nemesis-feedback.ts" },
      { id: "graphql", text: "api.graphql.ts" },
      { id: "ws", text: "api.websocket.ts" },
    ],
    correctAnswer: { choiceIds: ["auth", "claim", "nemesis", "feedback"] },
    explanation: {
      short: "auth / claim-token / nemesis / nemesis-feedback 真实存在；graphql / websocket 不在此项目。",
      detail: "记住前缀约定：api.* 一般是 server-only 资源路由。注意 api.claim-token.tsx 用 .tsx 后缀但不渲染——只是项目沿用约定，里面只 export loader/action。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/api.auth.$.ts", "app/routes/api.claim-token.tsx", "app/routes/api.nemesis.ts", "app/routes/api.nemesis-feedback.ts"],
  }),
  q({
    type: "fill_blank",
    title: "Q6 chat 路由的 URL",
    prompt: "remix/app/routes/chat.tsx 对应的 URL 是 ____ 。",
    options: [],
    blanks: [{ id: "v", placeholder: "URL", acceptedAnswers: ["/chat", "chat"] }],
    correctAnswer: { type: "fill_blank", values: { v: "/chat" } },
    explanation: {
      short: "/chat。",
      detail: "扁平路由文件名直接对应 URL：chat.tsx → /chat、cv.tsx → /cv、gallery.tsx → /gallery。无嵌套、无动态段时一一对应。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/chat.tsx"],
  }),
  q({
    type: "single_choice",
    title: "Q7 auth.sign-out 是否独立路由",
    prompt: "remix/app/routes/auth.sign-out.tsx 这个文件名表达的语义？",
    options: [
      { id: "A", text: "/auth/sign-out 是 /auth 父路由下的子页（点号代表层级）" },
      { id: "B", text: "和 auth.tsx 等价" },
      { id: "C", text: "永远 redirect 到 /auth" },
      { id: "D", text: "Better Auth 的内部签名" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "auth.sign-out.tsx = /auth/sign-out 子路由。点号是层级，连字符不是。",
      detail: "注意区分点号（路由层级分隔符）与连字符（普通 URL 字符）：sign-out 里的 - 是字符串本身，会出现在 URL 里。/auth/sign-out 是常规 React Router 路径。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/auth.sign-out.tsx", "app/routes/auth.tsx"],
  }),
  q({
    type: "true_false",
    title: "Q8 game.$platform 必须导出 default",
    prompt: "remix/app/routes/game.$platform.tsx 必须 export default 一个 React 组件，否则编译报错。",
    correctAnswer: { type: "true_false", value: false },
    explanation: {
      short: "false——只 export loader/action 也合法（资源路由模式）；编译不会强制 default。",
      detail: "React Router 不要求每条路由都有 default。游戏平台页确实导出 default，但'技术上不是必须'——api.* 路由就是反例，只 export action 不 export default。",
    },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/game.$platform.tsx", "app/routes/api.nemesis.ts"],
  }),
  q({
    type: "single_choice",
    title: "Q9 routes/_index 与 root.tsx",
    prompt: "remix/app/_index.tsx（不存在）与 remix/app/routes/_index.tsx（存在）的关系？",
    options: [
      { id: "A", text: "root.tsx 是整个路由树的根（HTML shell + Outlet）；routes/_index.tsx 是 / 的具体页面，被 root.tsx 的 Outlet 渲染" },
      { id: "B", text: "两者重复，必须删一个" },
      { id: "C", text: "_index.tsx 应该挪到 app/_index.tsx" },
      { id: "D", text: "完全无关" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "root.tsx = HTML shell；routes/_index.tsx = / 页面。Outlet 把后者塞进前者。",
      detail: "层级关系：root.tsx 提供 <html><body>{children}</body></html>，children 就是 Outlet。访问 / 时，Outlet 拿到 routes/_index.tsx 渲染结果。这是为什么所有页面共享 root 的 head meta、theme 与 session。",
    },
    abilityTags: ["bridge.reactRouter.loader", "frontend.state.global"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: ["app/root.tsx", "app/routes/_index.tsx"],
  }),
  q({
    type: "position_judgement",
    title: "Q10 添加 /blog/:slug 路由放哪",
    prompt: "新增 'blog 详情页 /blog/:slug'，文件名应该写成什么？",
    options: [
      { id: "right", text: "remix/app/routes/blog.$slug.tsx", locationHint: "app/routes/blog.$slug.tsx" },
      { id: "wrong1", text: "remix/app/routes/blog/[slug].tsx", locationHint: "app/routes/blog/" },
      { id: "wrong2", text: "remix/app/routes/blog.{slug}.tsx", locationHint: "app/routes/" },
      { id: "wrong3", text: "remix/app/routes/blog/:slug.tsx", locationHint: "app/routes/blog/" },
    ],
    correctAnswer: { positionId: "right" },
    explanation: {
      short: "$slug 是动态段约定；blog.tsx 不存在时 blog 是字面量段、$slug 跟着是动态。",
      detail: "[xxx]、{xxx}、:xxx 都不是 React Router v7 的约定（Next.js / Vite Router / Express 各有自己的写法）。本项目的扁平文件名约定就是 $name 表示动态段。",
    },
    abilityTags: ["code.position.handler", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/"],
  }),
  q({
    type: "single_choice",
    title: "Q11 动态段值在 loader 怎么取",
    prompt: "在 remix/app/routes/game.$platform.tsx 的 loader 里，取动态段 platform 的值的写法？",
    options: [
      { id: "A", text: "loader({ params }) { const platform = params.platform; ... }" },
      { id: "B", text: "loader({ request }) { const platform = request.url.split('/')[3]; ... }" },
      { id: "C", text: "loader() { return process.env.platform; }" },
      { id: "D", text: "loader({ context }) { const platform = context.platform; ... }" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "loader/action 第一参数解构 params，按文件名 $name 一一对应。",
      detail: "params 是类型化的——typegen 会读 routes.ts，自动生成 Route.LoaderArgs，其中 params.platform 类型已知是 string。手动 split URL 是反模式：脆且没类型。",
    },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/game.$platform.tsx"],
  }),
  q({
    type: "fill_blank",
    title: "Q12 splat 段在 params 里的 key",
    prompt: "splat 路由（如 api.auth.$.ts）匹配的 URL 段最终在 params 字典里以 ____ 为 key。",
    options: [],
    blanks: [{ id: "v", placeholder: "key 名称", acceptedAnswers: ["*", "'*'"] }],
    correctAnswer: { type: "fill_blank", values: { v: "*" } },
    explanation: {
      short: "params['*']——按 React Router v7 约定。",
      detail: "/api/auth/google/callback 触发 api.auth.$.ts 时 params['*'] === 'google/callback'。它是个特殊 key，因为 * 不是合法的 JS identifier，只能括号访问。",
    },
    abilityTags: ["code.position.handler", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/api.auth.$.ts"],
  }),
  q({
    type: "ai_review",
    title: "Q13 AI 把 routes/ 改成嵌套目录",
    prompt: "AI 看到扁平文件名（auth.sign-out.tsx 这种），'觉得不优雅'，提议改成嵌套目录 routes/auth/sign-out.tsx。这个改法合格吗？",
    options: [
      { id: "bad", text: '不合格：本项目用的是 React Router v7 框架模式的」扁平文件名"约定，目录嵌套与扁平文件名是两套等价但互斥的方案——混用会破坏路由扫描' },
      { id: "ok", text: "合格：嵌套目录更可读" },
      { id: "ok2", text: "合格：和别的框架一致" },
      { id: "ok3", text: "合格：编译会自动适配" },
    ],
    correctAnswer: { choiceId: "bad", riskIds: ["architecture_boundary"] },
    aiReviewMeta: { riskTypeOptions: [{ id: "architecture_boundary", label: "破坏架构边界" }] },
    explanation: {
      short: '扁平文件名 ↔ 嵌套目录是路由扫描的两种模式，混用会让其中一边失效。',
      detail: "React Router v7 框架模式默认开启扁平 (flat) 文件名解析；要嵌套目录得显式打开。AI 自作主张改一个文件名，剩下文件不动 = 路由树支离破碎。改路由组织方式必须整个项目一次性做，且要修改 routes.ts 配置。",
    },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/", "app/routes.ts"],
    realWorldImpact: "改对一个、剩下文件不改，等于让某些路由突然 404，且 typegen 输出全错。",
    aiReviewRisk: "AI 把'美感'优先级置于'框架约束'之上是高频反模式。",
  }),
  q({
    type: "true_false",
    title: "Q14 routes 文件能否相互 import",
    prompt: "在 remix/app/routes/chat.tsx 里 import 另一个 route 文件 routes/_index.tsx 的导出，编译能过。",
    correctAnswer: { type: "true_false", value: true },
    explanation: {
      short: "true——技术上能，但是反模式。",
      detail: "TypeScript / 框架不阻止 route 之间互相 import，但语义上 route 是 URL 入口而不是模块；互相 import 会让代码组织退化。共用逻辑应抽到 lib/ 或 services/，不应该在 route 文件里互相依赖。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/", "app/lib/"],
  }),
  q({
    type: "multi_choice",
    title: "Q15 routes/ 下的 'UI 路由'",
    prompt: "remix/app/routes/ 下面真实存在、用来渲染 UI（带 default export）的页面路由有？（多选）",
    options: [
      { id: "anime", text: "anime.tsx" },
      { id: "cv", text: "cv.tsx" },
      { id: "gallery", text: "gallery.tsx" },
      { id: "music", text: "music.tsx" },
      { id: "messages", text: "messages.tsx" },
      { id: "blog", text: "blog.tsx" },
    ],
    correctAnswer: { choiceIds: ["anime", "cv", "gallery", "music", "messages"] },
    explanation: {
      short: "anime / cv / gallery / music / messages 都是真页面；blog 不存在。",
      detail: "记住一点：编出'像是合理'但其实不存在的路由是 AI 高频反模式。这种文件 import 不到、URL 也访问不到。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/"],
  }),
  q({
    type: "single_choice",
    title: "Q16 rapid-layers-preview 看上去奇怪",
    prompt: "remix/app/routes/rapid-layers-preview.tsx 是？",
    options: [
      { id: "A", text: "项目里的一个'实验/预览'页面，URL = /rapid-layers-preview——存在因为有人需要它" },
      { id: "B", text: "废弃文件应删除" },
      { id: "C", text: "Vite 的内部产物" },
      { id: "D", text: "TypeScript 编译占位" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "/rapid-layers-preview——一个 dev-only 风格的预览页面。",
      detail: "看到陌生路由文件第一反应不应该是'删了吧'——可能是某个 demo / 调研页。处理方法：(1) git log 看新增动机；(2) 如果真没用了再 PR 删。AI 经常因为'不认识'就建议删除。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/rapid-layers-preview.tsx"],
  }),
  q({
    type: "branch_trace",
    title: "Q17 访问 /game/switch 的路由匹配链",
    prompt: "用户访问 /game/switch，React Router 按以下顺序匹配并渲染：",
    branchScenario: "GET /game/switch",
    options: [
      { id: "root", text: "root.tsx（顶层 HTML shell + Outlet）" },
      { id: "game", text: "routes/game.tsx（游戏区父 layout，提供子级 Outlet）" },
      { id: "platform", text: "routes/game.$platform.tsx（params.platform === 'switch'，渲染具体平台内容）" },
      { id: "respond", text: "返回 HTML 流 / 完整 HTML（取决于 isbot）" },
    ],
    correctAnswer: { type: "branch_trace", pathIds: ["root", "game", "platform", "respond"] },
    explanation: {
      short: "root → game (layout) → game.$platform (动态段) → 输出。",
      detail: "理解嵌套渲染对排障关键：游戏页样式异常先看 game.tsx 的 Outlet 容器，数据异常先看 game.$platform 的 loader，主题异常追到 root。一层一层找最小可复现位置。",
    },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: ["app/root.tsx", "app/routes/game.tsx", "app/routes/game.$platform.tsx"],
  }),
  q({
    type: "single_choice",
    title: "Q18 game._index 与 game.$platform 互斥",
    prompt: "用户访问 /game（无后缀），渲染哪个文件的 default？",
    options: [
      { id: "A", text: "routes/game._index.tsx（_index 是 /game 的默认子）" },
      { id: "B", text: "routes/game.tsx 的 default" },
      { id: "C", text: "routes/game.$platform.tsx" },
      { id: "D", text: "返回 404" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "/game → game.tsx 父 + game._index.tsx 默认子。",
      detail: "嵌套规则：访问 /game/<segment> → game.tsx + game.$platform.tsx；访问 /game（光秃秃）→ game.tsx + game._index.tsx。这就是 _index 存在的意义——给 layout 路由一个默认子。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/game._index.tsx", "app/routes/game.$platform.tsx", "app/routes/game.tsx"],
  }),
  q({
    type: "code_fix",
    title: "Q19 修改 splat 让 catch 段必须存在",
    prompt: "想把 api.auth.$.ts 改成只匹配 /api/auth/<至少一段>（不允许光秃秃 /api/auth）。最小改法？",
    codeFixBaseline: "// remix/app/routes/api.auth.$.ts\nexport async function loader({ params }) {\n  // params['*'] 可能是空字符串\n  return Response.json({ tail: params['*'] });\n}",
    correctAnswer: {
      type: "code_fix",
      patchedCode: "// remix/app/routes/api.auth.$.ts\nexport async function loader({ params }) {\n  if (!params['*']) throw new Response(null, { status: 404 });\n  return Response.json({ tail: params['*'] });\n}",
    },
    expectedFixScope: "one-line",
    serverClientBoundary: "server",
    abilityTags: ["code.position.handler", "backend.validation.field"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    touchedFiles: ["app/routes/api.auth.$.ts"],
    explanation: {
      short: "在 loader 里检查 params['*']，空就 throw 404。",
      detail: "splat 路由会匹配空 tail（/api/auth 直接命中，params['*'] === ''）。如果业务上要求至少一段，loader 顶部加守门是最便宜的修法。比改路由配置更直接。",
    },
    realWorldImpact: "不守门会导致 /api/auth 这种秃路径打到 Better Auth handler，可能 500 也可能错误处理某些路径。",
  }),
  q({
    type: "true_false",
    title: "Q20 routes 文件命名会影响代码分裂",
    prompt: "在 routes/ 文件夹添加新文件，React Router 编译期会自动给它生成独立的 JS chunk。",
    correctAnswer: { type: "true_false", value: true },
    explanation: {
      short: "true——每个 route 文件 = 一个 lazy chunk，URL 命中才下载。",
      detail: "这是 React Router 的核心优化：全站 100 条路由不会让首页下载所有代码，因为编译期已经按文件分裂。这也意味着把 util 塞到 routes/ 会让 util 进入路由 chunk——bundle 形状不可控。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/"],
  }),
  q({
    type: "single_choice",
    title: "Q21 routes/ 与 routes.ts",
    prompt: "Code Coach 项目（与 remix 项目同 repo）的 app/routes.ts 和 routes/ 文件夹的关系？",
    options: [
      { id: "A", text: "Code Coach 用 config-based 路由（每条路由在 routes.ts 显式声明）；remix 用 file-based 路由——两个项目用了不同模式" },
      { id: "B", text: "两者等价" },
      { id: "C", text: "都用 file-based 但 remix 多一层" },
      { id: "D", text: "都用 config-based" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "Code Coach (RR7 framework mode) → routes.ts 显式；remix → 文件名约定。",
      detail: "你正在学习的 Code Coach 项目（lea/）走 React Router 7 框架模式的 config-based 路由——所有路由在 app/routes.ts 用 route()/prefix()/layout() 写。被学习的 remix 子项目（remix/）走的是 Remix v2 的 file-based 路由。两者并存于同一个 repo 是有意为之：用一个项目教你读另一个项目。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/"],
  }),
  q({
    type: "free_explain",
    title: "Q22 自由复述 routes/ 的扁平文件名约定",
    prompt: "用自己的话解释 remix 项目 routes/ 的扁平文件名约定：'.'、'$'、'_index'、'[.]' 各自的作用。",
    code: "// 真实文件示例：\n// _index.tsx\n// game.tsx\n// game._index.tsx\n// game.$platform.tsx\n// api.auth.$.ts\n// sitemap[.]xml.tsx",
    correctAnswer: { type: "free_explain", text: "no correct answer — AI grades" },
    explanation: {
      short: "好答案应当覆盖：'.'=层级、$name=动态段、裸 $=splat catch-all、_index=父级默认子、[x]=字面量转义。",
      detail: "完整答案至少包括：(1) 文件名映射 URL 的核心规则；(2) 每个特殊符号的语义；(3) 各自的实际项目用途（game.$platform 接收 :platform，api.auth.$ 接收 OAuth 回调，sitemap[.]xml 输出 .xml URL）；(4) 为什么这套约定能让一个文件夹一眼看出全站 URL 形状。",
    },
    abilityTags: ["code.position.handler", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "free-response",
    serverClientBoundary: "server",
    touchedFiles: ["app/routes/"],
  }),
];
