/**
 * Real questions for site-13-frontend-state / error-state.
 * Anchor: remix/app/hooks/useNemesisChat.client.ts —— error state + DEFAULT_ERROR_MESSAGE + try/catch in sendMessage/regenerateResponse/submitFeedback + regenerate 回滚
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/hooks/useNemesisChat.client.ts";
const sc = (id: string, text: string) => ({ id, text });

export const errorStateQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 默认错误文案常量",
    prompt: "const DEFAULT_ERROR_MESSAGE = \"上游模型服务____繁忙，稍后重试通常可以恢复。\";",
    options: [],
    blanks: [{ id: "v", placeholder: "字", acceptedAnswers: ["暂时"] }],
    correctAnswer: { type: "fill_blank", values: { v: "暂时" } },
    explanation: { short: "DEFAULT_ERROR_MESSAGE 在 catch 块用——非 Error 类型 throw 时兜底文案。" },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 error state 类型",
    prompt: "const [error, setError] = useState<string | null>(null);——为什么 string | null？",
    options: [
      sc("A", "string 携带可读错误文案（直接显示给用户）；null 表示「无错误」；不存原始 Error 对象——UI 不需要 stack trace、只要文案"),
      sc("B", "Error 对象"),
      sc("C", "boolean"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "UI 错误 state 存「展示文案」即可——结构最小化。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 catch 内 instanceof Error",
    prompt: "} catch (err) { setError(err instanceof Error ? err.message : DEFAULT_ERROR_MESSAGE); }——三处 sendMessage / regenerateResponse / submitFeedback 都用此模式？",
    options: [
      sc("A", "对——三处都用同款 catch；统一处理 unknown→string 收窄；项目内一致的错误处理范式"),
      sc("B", "三种不同"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三处统一 catch 模式 = 错误处理纪律一致。" },
    abilityTags: ["frontend.event.submit", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 setError 在 sendMessage / startNewSession",
    prompt: "startNewSession / selectSession / deleteSession 内都有 setError(null);——为什么操作时清错误？",
    options: [
      sc("A", "用户主动改变上下文（切会话/新建/删）时之前的错误已不相关——清掉避免错误信息留在新会话上下文里造成困惑；状态切换隐含「重置错误展示」"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "切上下文 → 清残留错误——状态边界清理纪律。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 regenerateResponse 失败回滚",
    prompt: "regenerateResponse catch 内：commitMessages([...messagesBeforeRegenerate, previousAssistantMessage, ...followingMessages]);——为什么这样？",
    options: [
      sc("A", "regenerate 是「替换旧助手消息」操作——成功前先 commitMessages 把旧消息暂时移除；失败时 catch 把 previousAssistantMessage 放回原位置；恢复用户视角的连续性"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "regenerate 失败 = 把旧消息放回——维持 UI 连续性。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 sendMessage 失败不回滚 user 消息",
    prompt: "sendMessage 失败时 catch 内只 setError 没回滚 userMessage——为什么？",
    options: [
      sc("A", "用户消息留下让用户能看到「我说了什么」+ 错误提示让用户决定重试或编辑；如果回滚用户消息会让用户困惑「我说的话哪去了」；UX 选择"),
      sc("B", "应该回滚"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "用户消息保留 = 错误时上下文可见；UX 友好。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 regenerateResponse 顶部 guard",
    prompt: "if (!activeSessionId || isTypingReply) { return; }——双 guard 含义？",
    options: [
      sc("A", "无活跃会话不可重生成（无目标）；正在打字机播放时不可重生成（避免与 typing 渲染冲突）；前置守门保证操作合法"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "regenerate 双 guard：会话 + 非 typing——防错调。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 messageIndex 边界",
    prompt: "if (messageIndex <= 0) { return; }——为什么 <= 0？",
    options: [
      sc("A", "messageIndex 应至少 1（前面有用户消息才能重生成助手回复）；0 = 自身就是第一个无法回溯；-1 = 没找到；两种情况合一拒绝；防御边界"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "messageIndex <=0 涵盖「找不到」与「无前置 user 消息」两边界。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 previousUserMessage 类型校验",
    prompt: "const previousUserMessage = messages[messageIndex - 1]; if (previousUserMessage.role !== 'user') { return; }——为什么校验 role？",
    options: [
      sc("A", "数据形状未必符合假设——可能是 system 消息或顺序异常；不校验直接用 .content 可能不存在；防御性校验是处理外部数据/历史数据的纪律"),
      sc("B", "TypeScript"),
      sc("C", "随机"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "结构假设要校验——历史数据/外部数据不可假定。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 submitFeedback 双校验",
    prompt: "submitFeedback 内 if (!activeSessionId || assistantMessage.role !== 'assistant' || feedbackSubmittingId) { return; }——三 guard 含义？",
    options: [
      sc("A", "1) 无活跃会话 2) 提交目标不是助手消息（数据异常）3) 已经在提交另一条 → 防止并发反馈；三 guard 各管一种异常"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三 guard 三种异常——分别防御。" },
    abilityTags: ["frontend.event.submit", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 setError 'submitFeedback' 中两次",
    prompt: "submitFeedback 内若找不到对应 user 消息：setError(\"找不到这条回复对应的用户问题，无法提交反馈。\");——为什么写具体文案不用 DEFAULT？",
    options: [
      sc("A", "这是「业务错误」（数据异常）非「网络错误」；具体文案让用户理解原因（数据问题不是重试能解决的）；DEFAULT_ERROR_MESSAGE 表「重试可恢复」语义不符"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "业务错误用具体文案；DEFAULT 是「重试可解」类网络错误的兜底。" },
    abilityTags: ["frontend.event.submit", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 copyMessage catch",
    prompt: "navigator.clipboard.writeText(...).catch(() => { setError('复制失败，请手动选择文本。'); });——为什么链式 catch 不 try/catch？",
    options: [
      sc("A", "clipboard.writeText 返 Promise——链式 catch 是 Promise API 的标准写法；try/catch 同步代码只能配 await；不 await 时只能链式"),
      sc("B", "应该 await"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Promise 不 await → 链式 .catch；await + try/catch 等价但风格不同。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 没全局错误边界",
    prompt: "Hook 内 try/catch 都被三处 sendMessage / regenerate / submitFeedback 各自管 — 没有「兜底全局 error boundary」？",
    options: [
      sc("A", "对——hook 内只处理「业务可预期错误」（网络失败 / 数据异常）；编程 bug 抛出会冒泡到 React Error Boundary（root.tsx 的 ErrorBoundary）；分层各管各"),
      sc("B", "兜底所有"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "业务错误 hook 内 catch；运行时错误冒泡 ErrorBoundary——分层。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "branch_trace", title: "Q14 网络断时发消息全流",
    prompt: "用户发消息时网络突然断 → requestNemesisReply throw NetworkError，步骤？",
    options: [
      sc("s1", "1. sendMessage 顶部 guard 通过"),
      sc("s2", "2. optimistic：setMessages 加 user 消息 + upsertActiveSession 持久化"),
      sc("s3", "3. setIsLoading(true) + setRequestStage(initial) + scrollToBottom"),
      sc("s4", "4. await requestNemesisReply 抛 NetworkError（一个 Error 实例）"),
      sc("s5", "5. catch 入参 err instanceof Error → setError(err.message)"),
      sc("s6", "6. finally：setIsLoading(false) + setRequestStage(null)"),
      sc("s7", "7. UI 状态：messages 含 user 消息无助手回复 + error 字符串显示 + isLoading=false 解禁按钮"),
      sc("s8", "8. 用户阅读错误后可点重试或修改后重新发"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8"] },
    explanation: { short: "网络失败完整 8 步——optimistic 留消息 + error 显示 + loading 解禁。" },
    abilityTags: ["frontend.event.submit", "frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 错误后再发同一消息",
    prompt: "用户失败后想重发同一消息——怎么操作？",
    options: [
      sc("A", "Hook 暴露 sendMessage(content?) 接受参数 → 消费者从最后一条 user 消息拿 content 调；自然支持重试；不必新增 retry API"),
      sc("B", "新加 retry"),
      sc("C", "改 server"),
      sc("D", "无法重发"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "已有 sendMessage(string?) 直接支持重发——API 设计的灵活性体现。" },
    abilityTags: ["frontend.event.submit", "ai.review.architecture", "project.modify.fullstack"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 错误显示位置",
    prompt: "error state 在 UI 哪里展示？",
    options: [
      sc("A", "消费者组件（如 NemesisChatErrorBanner 或 Composer 上方）从 hook 拿 error 显示——hook 不规定位置；UI 决定布局；error 暴露为 hook 公共 API"),
      sc("B", "Header"),
      sc("C", "root"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "hook 暴露 error 让消费者决定展示位置——hook 不耦合 UI。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/nemesis/chat/"],
  }),
  q({
    type: "single_choice", title: "Q17 错误自动消失",
    prompt: "想让 error 5s 后自动消失。落点？",
    options: [
      sc("A", "消费者 useEffect 监听 error + setTimeout 5s 后调 setError(null)（hook 暴露 setError 或封装一个 clearError）；hook 不内置定时——UX 决策"),
      sc("B", "改 hook"),
      sc("C", "改 server"),
      sc("D", "无法实现"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "auto-dismiss 是 UX 选择 → 消费者层 useEffect 实现。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/nemesis/chat/"],
  }),
  q({
    type: "single_choice", title: "Q18 多语言错误文案",
    prompt: "做 i18n 后错误文案怎么处理？",
    options: [
      sc("A", "DEFAULT_ERROR_MESSAGE 改成 i18n key 'errors.upstream_busy'，hook 不直接持中文文案；调 t(key) 在消费者层；或 hook 接 errorMessages prop 注入"),
      sc("B", "硬编码"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "i18n = 文案与代码解耦；hook 持 key 不持文案。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 错误监控埋点",
    prompt: "想把错误上报到监控（Sentry 等）——落点？",
    options: [
      sc("A", "catch 内 setError 之前加 reportError(err)；网络层包装层（requestNemesisReply 内）也可埋点；两层埋点：业务错误 + 网络错误一并上报"),
      sc("B", "改 root"),
      sc("C", "无法埋"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "错误监控 = catch 块 + 网络封装层都埋——双层覆盖。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/lib/nemesis-chat-api.client.ts"],
  }),
  q({
    type: "true_false", title: "Q20 error state 是否会持久化到 localStorage",
    prompt: "判断：error state 会被 saveNemesisChatSessions 持久化到 localStorage。",
    correctAnswer: { value: false },
    explanation: { short: "错——只有 sessions（会话+消息）持久化；error 是临时 UI 状态不进 localStorage。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 缺 AbortController 引发的错误模式",
    prompt: "用户切会话时上一个请求仍在跑 → 后续 setError 影响新会话——可能问题？",
    options: [
      sc("A", "旧请求失败后调 setError 时 activeSessionId 已变 → 错误看似属于新会话；用户疑惑；改进：AbortController + 在 selectSession 中 abort 上一个请求"),
      sc("B", "无问题"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "无 abort = 旧请求结果污染新上下文——错误显示位置错乱。" },
    abilityTags: ["frontend.event.submit", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 错误处理整体哲学",
    prompt: "useNemesisChat 错误处理整体哲学？",
    options: [
      sc("A", "1) error: string|null 最小存储「展示文案」2) catch 三处统一 instanceof Error 收窄 3) DEFAULT_ERROR_MESSAGE 兜底非 Error throw 4) 业务错误用具体文案区分网络错误 5) regenerate 失败回滚保连续性 6) sendMessage 失败保留 user 消息保上下文 7) 切上下文（startNew/select/delete）清错误避免污染 8) hook 暴露 error 不耦合 UI 位置——综合：错误是状态机一员，与 loading/messages 同等管理"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "错误处理 8 原则——前端错误 state 的纪律范本。" },
    abilityTags: ["frontend.state.local", "frontend.event.submit", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
];
