/**
 * Real questions for site-13-frontend-state / loading-ui.
 * Anchor: remix/app/hooks/useNemesisChat.client.ts —— isLoading / requestStage / typingMessageId 三态派生 + adjustTextareaHeight + scrollToBottom + activeSession 派生
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/hooks/useNemesisChat.client.ts";
const sc = (id: string, text: string) => ({ id, text });

export const loadingUiQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 isTypingReply 派生",
    prompt: "const isTypingReply = ____(typingMessageId);",
    options: [],
    blanks: [{ id: "v", placeholder: "函数", acceptedAnswers: ["Boolean"] }],
    correctAnswer: { type: "fill_blank", values: { v: "Boolean" } },
    explanation: { short: "Boolean(string|null) = 把 string|null 转布尔——typingMessageId 有值即 true。" },
    abilityTags: ["frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 isLoading 控按钮 disabled",
    prompt: "isLoading 主要被消费者用作什么？",
    options: [
      sc("A", "禁用发送按钮 + 输入框（禁连发）+ 显示 loading 指示器；消费者 NemesisChatComposer 等组件根据 isLoading 控制 UI 状态"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "isLoading = 简单二值开关——禁交互 + 显加载态。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/nemesis/chat/"],
  }),
  q({
    type: "single_choice", title: "Q3 requestStage 是数组",
    prompt: "const [requestStage, setRequestStage] = useState<NemesisProgressStep[] | null>(null);——为什么是数组？",
    options: [
      sc("A", "SSE 进度是「逐步累积的步骤序列」——例如 [{step:'auth', state:'done'}, {step:'rate', state:'done'}, {step:'model', state:'inflight'}]；数组让 UI 显示带顺序的进度条；null 表示无请求"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "进度多步累积 → 数组结构；null = 无活跃请求。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 requestStatusLabel 三元",
    prompt: "const requestStatusLabel = requestStage ? 'Nemesis 正在处理' : isTypingReply ? 'Nemesis 正在显示完整回复' : '就绪';——为什么这种顺序？",
    options: [
      sc("A", "时序优先：requestStage（处理中）→ isTypingReply（已收到、播打字机）→ 就绪；判断从最早状态开始一路降级；能精确表达「现在到哪一步」"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三元从「最进行中」到「最闲」——状态机时序映射文案。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 activeSession 派生",
    prompt: "const activeSession = sessions.find((session) => session.id === activeSessionId) ?? null;——为什么不存 state？",
    options: [
      sc("A", "派生值——sessions 与 activeSessionId 是源；存 state 会有同步问题（sessions 变了 activeSession 没更新）；每次渲染派生反而最简单准确"),
      sc("B", "性能差"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "派生值不入 state——React 数据建模铁律。" },
    abilityTags: ["frontend.state.local", "frontend.state.scope", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 useMemo 不上",
    prompt: "activeSession = sessions.find(...) 没用 useMemo——为什么？",
    options: [
      sc("A", "find 在小数组（最多 MAX_NEMESIS_CHAT_SESSIONS 项）上是常数级；useMemo 引入依赖追踪 + 缓存比较反而更慢；有数千项才考虑 memo"),
      sc("B", "应该 memo"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useMemo 只对昂贵计算或引用稳定有用——小数组 find 不必。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 adjustTextareaHeight",
    prompt: "useEffect(() => { adjustTextareaHeight(); }, [adjustTextareaHeight, inputMessage]);——依赖 inputMessage 含义？",
    options: [
      sc("A", "用户每次按键改 inputMessage → effect 跑 → 重算 textarea 高度（auto-resize）；adjustTextareaHeight 是 useCallback 引用稳定，加它进依赖只是 lint 要求"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "input 变化 → 高度重算；callback 自身进依赖是 exhaustive-deps 规范。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 adjustTextareaHeight 实现",
    prompt: "textareaRef.current.style.height = 'auto'; textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 180)}px`;——两步顺序意图？",
    options: [
      sc("A", "先 'auto' 让浏览器按内容算 scrollHeight；如果不重置直接读 scrollHeight 会被旧的 height 锁住值缩不下去；Math.min 限上限 180 防止 textarea 过高"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "auto-resize 模板：先 auto 再读 scrollHeight 再设新 height + max 上限。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 focus textarea on session change",
    prompt: "useEffect(() => { textareaRef.current?.focus(); }, [activeSessionId]);——意图？",
    options: [
      sc("A", "用户切会话后焦点自动回输入框——可立即继续打字；切会话是「场景切换」，按经验需要重新聚焦输入区"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "切会话 → 自动聚焦输入 = 用户即时连续打字。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 scrollToBottom effect",
    prompt: "useEffect(() => { scrollToBottom(); }, [isLoading, messages.length, scrollToBottom]);——三个依赖含义？",
    options: [
      sc("A", "isLoading 切换：开始/结束请求时滚；messages.length 变：新消息加入时滚；scrollToBottom 进依赖是 lint；三个共同覆盖「需要滚到底」的所有时机"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "依赖列出所有「触发滚动」事件——精确驱动 effect 重跑。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 scrollToBottom 用 rAF",
    prompt: "scrollToBottom 内 window.requestAnimationFrame(() => { ... chatWindowRef.current.scrollTop = scrollHeight });——为什么 rAF？",
    options: [
      sc("A", "messages 变化触发 effect → effect 同步执行时 DOM 还没真正反映新消息（React commit 已发生但浏览器布局未刷新）；rAF 等下一帧布局完成读取 scrollHeight 才正确滚到新底"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "rAF = 等浏览器下一帧布局完——这时 scrollHeight 才准。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 isLoading + scroll",
    prompt: "为什么 isLoading 也作 scroll 依赖？",
    options: [
      sc("A", "loading 开始时（isLoading 由 false→true）触发滚一次让用户看到「我已发送、正在等」；loading 结束时（true→false，新消息已 setMessages 但 length 已 +1 早触发了）也触发；保险滚一次"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loading 状态切换是滚动的额外触发点——保用户视觉跟得上。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 typingMessageId 与 finishTypingMessage",
    prompt: "const finishTypingMessage = useCallback(() => { setTypingMessageId(null); scrollToBottom(); }, [scrollToBottom]);——谁调它？",
    options: [
      sc("A", "消费者组件（NemesisChatTypewriter 等）在打字机播放完一句话时调用——告诉 hook「这条已展示完」清状态；hook 通过返回这个 callback 让 UI 控制时机"),
      sc("B", "hook 内部"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "hook 暴露 callback 让 UI 控制状态结束 = 渲染 ↔ 状态机的协作。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/nemesis/chat/"],
  }),
  q({
    type: "single_choice", title: "Q14 isPrivacyPopoverOpen / showPrivacyNotice 双 state",
    prompt: "isPrivacyPopoverOpen vs showPrivacyNotice——两个像但不一样？",
    options: [
      sc("A", "showPrivacyNotice：首次访问横幅是否还要显（是否已 accepted），单向降级；isPrivacyPopoverOpen：用户主动开关详情 popover；两件事各管各，不可合一"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "看似相似实则不同生命周期 = 不可合一；命名要精确。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 acceptPrivacyNotice",
    prompt: "const acceptPrivacyNotice = useCallback(() => { saveNemesisPrivacyNoticeAccepted(); setShowPrivacyNotice(false); }, []);——同步两步？",
    options: [
      sc("A", "持久化用户接受到 localStorage（下次访问不再显）+ 当下立刻关横幅；分立功能但同事件触发——一个 callback 内做完"),
      sc("B", "应该拆"),
      sc("C", "随机"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "同事件多副作用 = 一个 callback 内组合，依赖空数组保稳定。" },
    abilityTags: ["frontend.event.click", "frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q16 用户发消息 UI 状态全流",
    prompt: "用户发消息，UI 各状态变化？",
    options: [
      sc("s1", "1. 初始：isLoading=false, requestStage=null, typingMessageId=null → label='就绪'"),
      sc("s2", "2. sendMessage 第一阶段：setIsLoading(true) + setRequestStage(initial)"),
      sc("s3", "3. label 变 'Nemesis 正在处理'；按钮 disabled；请求阶段进度条挂"),
      sc("s4", "4. SSE 进度回调触发多次 setRequestStage 更新阶段"),
      sc("s5", "5. await requestNemesisReply 完成 → setMessages 加助手消息 + setTypingMessageId(id)"),
      sc("s6", "6. finally：setIsLoading(false) + setRequestStage(null)"),
      sc("s7", "7. label 变 'Nemesis 正在显示完整回复'；isLoading=false 解禁按钮"),
      sc("s8", "8. 打字机播完调 finishTypingMessage → setTypingMessageId(null)"),
      sc("s9", "9. label 回 '就绪'，新一轮可发"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8", "s9"] },
    explanation: { short: "loading UI 完整状态机：就绪 → 处理 → 显示 → 就绪 9 步。" },
    abilityTags: ["frontend.state.local", "frontend.event.submit", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 isLoading 在 finally 设 false",
    prompt: "为什么 setIsLoading(false) 放 finally 而不是各分支？",
    options: [
      sc("A", "成功失败都要解禁；finally 是「必跑」语义；放 try 里失败时 isLoading 永远 true，按钮永远 disabled——卡死 UI"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loading 解禁是 try/catch 都要做的事 → finally 就位。" },
    abilityTags: ["frontend.event.submit", "frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 没 typingMessageId 后果",
    prompt: "若移除 typingMessageId 状态——丢失什么？",
    options: [
      sc("A", "消费者无法知道哪条消息正在打字机播放——所有助手消息一并瞬现，没有渐进出现的视觉过渡；体验降级；状态用于「区分一条消息正打 vs 已完整」"),
      sc("B", "无影响"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "typingMessageId 是「打字机精确指针」——丢了就没渐进体验。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 加「停止生成」按钮",
    prompt: "想加一个「停止生成」按钮（在 isLoading 时显示，点击中断响应）。改动？",
    options: [
      sc("A", "1) hook 内 useRef<AbortController | null>(null) 2) sendMessage 内 new AbortController() 存 ref + 传给 requestNemesisReply 3) 新 callback stopGeneration → controller.abort() + setIsLoading(false) 4) 暴露 stopGeneration 给消费者；体系扩展"),
      sc("B", "改 root"),
      sc("C", "改 wrangler"),
      sc("D", "无法实现"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "AbortController + ref + 暴露 stop callback = 中断功能完整路径。" },
    abilityTags: ["project.modify.fullstack", "frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/lib/nemesis-chat-api.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q20 多个状态对应同一个 button disabled",
    prompt: "若发送按钮要根据「isLoading || isTypingReply || !inputMessage」三条件 disable——逻辑放哪？",
    options: [
      sc("A", "放在 NemesisChatComposer 等消费者组件——hook 暴露三个原子值，组件按 UX 自行组合 disabled 条件；hook 不预设 UX 决策，给消费者灵活性"),
      sc("B", "hook 内"),
      sc("C", "改 root"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "原子状态在 hook，组合规则在消费者——分层让 UI 灵活。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/nemesis/chat/"],
  }),
  q({
    type: "single_choice", title: "Q21 加超时显示「响应慢」提示",
    prompt: "想在 isLoading 超过 10s 时显示「响应较慢，请耐心等」提示。落点？",
    options: [
      sc("A", "消费者组件内 useEffect 监听 isLoading + setTimeout 10s 后置 showSlowHint=true；isLoading 变 false 时清；hook 仍不变；属于「派生 UI 状态」"),
      sc("B", "改 hook 加 state"),
      sc("C", "改 server"),
      sc("D", "改 wrangler"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "超时提示是消费者层 UX；不必扩 hook——保 hook 简洁。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/nemesis/chat/"],
  }),
  q({
    type: "single_choice", title: "Q22 loading UI 整体哲学",
    prompt: "isLoading / requestStage / typingMessageId 三态整体哲学？",
    options: [
      sc("A", "1) 三态时序错开（请求 → 收到 → 播放）—不重叠不冲突 2) 派生组合得 requestStatusLabel 精准描述 3) finally 必清避免卡死 4) hook 暴露原子状态 + callback 让消费者灵活组合 UX 5) finishTypingMessage 让 UI 控制状态结束时机 6) scroll/focus/textarea 高度等副作用按依赖驱动各 effect——综合：状态机精准 + 副作用解耦 + 消费者主导 UX"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loading UI 6 原则——多态状态机的精准范式。" },
    abilityTags: ["frontend.state.local", "frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
];
