/**
 * Real questions for site-13-frontend-state / nemesis-hook.
 * Anchor: remix/app/hooks/useNemesisChat.client.ts —— 14 useState + 3 useRef + 5 useEffect + 各 callback；总览级
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/hooks/useNemesisChat.client.ts";
const sc = (id: string, text: string) => ({ id, text });

export const nemesisHookQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 文件后缀",
    prompt: "useNemesisChat.____.ts —— 后缀强制只在浏览器打包。",
    options: [],
    blanks: [{ id: "v", placeholder: "后缀", acceptedAnswers: ["client"] }],
    correctAnswer: { type: "fill_blank", values: { v: "client" } },
    explanation: { short: ".client 后缀让 Remix 把文件只打包到浏览器 bundle，避免 SSR 误访问 localStorage 等浏览器 API。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 useState 数量",
    prompt: "useNemesisChat 顶部连续 14 行 useState——为什么这么多 state 而不是合一个对象？",
    options: [
      sc("A", "每个 state 独立更新——React setState 一次只动一个；合并对象会让每次小改动写完整新对象，且 useState 不浅合并；分开更精确、性能更稳"),
      sc("B", "TypeScript 限制"),
      sc("C", "性能更差"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useState 不合并；分散 state = 精确更新；useReducer 才适合「联动多字段」。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 sessions 与 messages 双 state",
    prompt: "同时有 sessions（多会话列表）和 messages（当前会话消息）两个 state——为什么不只用 sessions？",
    options: [
      sc("A", "messages 是当前活跃会话消息的「快速访问视图」——避免每次渲染要 sessions.find(s=>s.id===activeSessionId).messages 再读；同时让用户切会话时 messages 一次性替换、UI 平滑；冗余但有意"),
      sc("B", "TypeScript 限制"),
      sc("C", "性能更差"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "messages 是 sessions 的派生但缓存——可读性 + 平滑切换的取舍。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 activeSessionId vs activeSession",
    prompt: "state 是 activeSessionId（id 字符串），但暴露的 activeSession 是对象——怎么算的？",
    options: [
      sc("A", "const activeSession = sessions.find((s) => s.id === activeSessionId) ?? null;——派生值，每次渲染重新计算；id 是真源 + 对象是派生；这样的好处：状态最小化"),
      sc("B", "用 useMemo"),
      sc("C", "另存 state"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "派生值不入 state——sessions + id 是源，对象 derive；最小状态原则。" },
    abilityTags: ["frontend.state.local", "frontend.state.scope", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 isLoading vs requestStage vs typingMessageId",
    prompt: "isLoading（请求中）+ requestStage（SSE 阶段进度）+ typingMessageId（打字机动画）——为什么三个 state 不合一个？",
    options: [
      sc("A", "三种状态时序不同：请求开始 → isLoading=true & requestStage=init；服务端流回来 → isLoading=false & typingMessageId 设为新消息；打字机播完 → typingMessageId=null；不重叠不冲突"),
      sc("B", "TypeScript 限制"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三种「进行中状态」时序错开 → 分别 state 表达精确语义。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 useRef 三个",
    prompt: "useRef 三个：chatWindowRef / textareaRef / hasLoadedSessions——为什么用 ref 不是 state？",
    options: [
      sc("A", "前两个引用 DOM 元素（滚动/聚焦操作）—ref 是 React 给 DOM 的句柄；hasLoadedSessions 是「初次挂载已 loaded」的标志，不该触发渲染——ref 不引发 re-render，state 会"),
      sc("B", "TypeScript 限制"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ref = DOM 句柄 + 不触发渲染的可变值；state = 触发渲染的值。" },
    abilityTags: ["frontend.state.local", "frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 hasLoadedSessions ref",
    prompt: "const hasLoadedSessions = useRef(false);——具体作用？",
    options: [
      sc("A", "防止「初始化加载 → setSessions」自动触发 saveNemesisChatSessions 回写 localStorage——挂载时第一个 useEffect 读完 localStorage 设 hasLoadedSessions=true，后面写 effect 才生效；避免回声写入"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "hasLoadedSessions = 「初始化阶段忽略写入」标记——避免读-写循环。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 useCallback 数量",
    prompt: "Hook 内大量 const xxx = useCallback(..., [deps])——为什么不是普通函数？",
    options: [
      sc("A", "返回值给消费者（NemesisChatPage 等组件），消费者把这些函数当 props 传给子组件；useCallback 让引用稳定→子组件 React.memo 不被无意义打破"),
      sc("B", "TypeScript 限制"),
      sc("C", "性能更差"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useCallback = 引用稳定，配合 memo / 子组件 props 比较。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 useEffect 数量",
    prompt: "Hook 内 5 个 useEffect——分别做什么？",
    options: [
      sc("A", "1) 初始化加载 sessions 2) sessions 变化回写 localStorage 3) inputMessage 变化调整 textarea 高度 4) activeSessionId 变化聚焦 textarea 5) isLoading/messages.length 变化滚到底部；每个 effect 单一职责"),
      sc("B", "全部一个 effect"),
      sc("C", "随机数"),
      sc("D", "TypeScript 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "5 effect 各管一事——单一职责让依赖清晰、cleanup 不混。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 isTypingReply 派生",
    prompt: "const isTypingReply = Boolean(typingMessageId);——直接用就行，为什么不上 useMemo？",
    options: [
      sc("A", "Boolean 转换是常数级；用 useMemo 反而引入依赖追踪开销和心智负担；只有「重计算昂贵」才上 useMemo——本身轻量值不必要"),
      sc("B", "性能更差"),
      sc("C", "TypeScript 限制"),
      sc("D", "习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useMemo 仅用于昂贵计算或引用稳定需求；轻量值直接派生。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 requestStatusLabel 三元",
    prompt: "const requestStatusLabel = requestStage ? '处理' : isTypingReply ? '显示完整回复' : '就绪';——为什么放 hook 内？",
    options: [
      sc("A", "状态派生集中在 hook——消费者直接拿 label 字符串，不必自己重写三元；hook 是「业务状态机」+「派生展示」一体的封装"),
      sc("B", "组件内"),
      sc("C", "随机"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "hook 把「状态 + 派生 + 操作」打包给 UI——降低消费者复杂度。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 NemesisChatController 类型导出",
    prompt: "export type NemesisChatController = ReturnType<typeof useNemesisChat>;——这个类型给谁用？",
    options: [
      sc("A", "其他组件用 NemesisChatController 类型作 props 类型——不必手动列字段；ReturnType 自动跟随 hook 返回结构变化；类型与实现一处真源"),
      sc("B", "TypeScript 强制"),
      sc("C", "随机"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ReturnType<typeof fn> = 实现驱动类型——少一处同步负担。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 hook 返回对象的字段量",
    prompt: "return { sessions, activeSession, messages, inputMessage, setInputMessage, ..., handleEnter, finishTypingMessage };——返回 30+ 字段——是否过宽？",
    options: [
      sc("A", "对一个聊天「视图模型」而言合理——消费者 NemesisChatPage 几乎用全部字段；拆多个小 hook 会让消费者要并发 hook 调用更乱；视图模型一体化"),
      sc("B", "应拆"),
      sc("C", "TypeScript 限制"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ViewModel hook 把整个 UI 业务一站式打包——返回多字段是必然。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 setInputMessage 直接暴露",
    prompt: "返回里有 inputMessage + setInputMessage——直接暴露 setter？",
    options: [
      sc("A", "对受控 input 标准——textarea onChange={(e) => setInputMessage(e.target.value)}；不暴露 setter 就要再造一个 changeInput 包装函数无意义；直接 setter 简洁"),
      sc("B", "应封装"),
      sc("C", "TypeScript 限制"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "受控组件 setter 直接暴露——纯包装无价值。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 hook 内不直接调 fetch",
    prompt: "sendMessage 内 await requestNemesisReply(message, history, setRequestStage) ——hook 不直接 fetch？",
    options: [
      sc("A", "正确——网络层封装在 ~/lib/nemesis-chat-api.client.ts 内的 requestNemesisReply；hook 只调用，不关心 SSE 解析细节；分层让 hook 聚焦「状态管理」"),
      sc("B", "应直接 fetch"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "hook = 状态层；网络 = API 层；分层让两边各自演进。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/lib/nemesis-chat-api.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q16 hook 内不直接 localStorage",
    prompt: "useEffect 用 readNemesisChatSessions / saveNemesisChatSessions 而非直接 localStorage.getItem——为什么封装一层？",
    options: [
      sc("A", "封装层处理：try/catch（隐私模式可能抛错）、JSON parse、版本兼容、最大数量裁剪；hook 内只关心「读 sessions / 写 sessions」语义；持久化策略未来变 IndexedDB 也只改一处"),
      sc("B", "TypeScript"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "持久化封装 = 错误处理 + 协议演进的隔离层。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/lib/nemesis-chat-sessions.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q17 useCallback 依赖错列",
    prompt: "若把 sendMessage 的 useCallback 依赖只写 [activeSessionId]——后果？",
    options: [
      sc("A", "捕获到 stale 闭包：messages、inputMessage 等变化时 sendMessage 不重新生成，调用时读到的是旧 messages 数组——发出消息时 history 错乱；exhaustive-deps lint 会警告"),
      sc("B", "无影响"),
      sc("C", "TypeScript 报错"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "依赖漏列 = 闭包陷阱——React Strict 与 lint 是第一道防线。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 hook 不带 props",
    prompt: "useNemesisChat() 不接任何参数——若想传初始 sessions（如 SSR 注水）？",
    options: [
      sc("A", "改签名 useNemesisChat(initialSessions?: NemesisChatSession[])；初始化 useState(initialSessions ?? [])；之后第一个 useEffect 在 ref 没标记时加载本地；二选一注水机制"),
      sc("B", "改 root"),
      sc("C", "无需"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "扩 hook 接初始数据 = 加可选参数 + 初始化路径分支。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q19 hook 是否可在 SSR 跑",
    prompt: "判断：useNemesisChat 这个 hook 可以在 Cloudflare Worker SSR 阶段调用。",
    correctAnswer: { value: false },
    explanation: { short: "错——文件 .client 后缀禁止 SSR；且内部依赖 localStorage / window 等浏览器 API；只能在 hydrate 后客户端跑。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 hook 可被多组件实例化",
    prompt: "若 NemesisChatPage 之外另一个组件也 useNemesisChat()——结果？",
    options: [
      sc("A", "两个独立实例——各自的 useState，各自的 effect；两份 sessions state；持久化都写同一 localStorage 键会冲突；通常只在一个 root 组件用，不要重复"),
      sc("B", "共享"),
      sc("C", "报错"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "hook 实例独立——共享需要 context lift up 到上层。" },
    abilityTags: ["frontend.state.scope", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 hook 拆为多个",
    prompt: "若想把 useNemesisChat 拆成 useNemesisSessions + useNemesisMessages + useNemesisFeedback——动机与代价？",
    options: [
      sc("A", "动机：单一职责更清晰；代价：跨子 hook 共享 activeSessionId、commitMessages 等需要中间层（context 或 hook 组合 hook）；419 行边界一旦超过 500-700 应考虑；当前文件复杂度可承受"),
      sc("B", "立刻拆"),
      sc("C", "永不拆"),
      sc("D", "TypeScript 强制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "拆 hook 是文件膨胀的应对；拆带来跨 hook 协调成本。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 hook 整体哲学",
    prompt: "useNemesisChat 整体设计哲学？",
    options: [
      sc("A", "1) 状态分散 14 个 useState 精确更新 2) ref 区分 DOM 句柄与「不触发渲染的标记」3) 派生值不入 state（activeSession / isTypingReply）4) useCallback 让函数引用稳定 5) 5 个 useEffect 各司一职 6) 网络/存储分层封装到 client lib 7) 返回打包整套 ViewModel + ReturnType 暴露类型——综合：状态机 + ViewModel + 分层 + 引用纪律"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "hook 7 原则——大型聊天状态机的范式实现。" },
    abilityTags: ["frontend.state.local", "frontend.effect.useEffect", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
];
