/**
 * Real questions for site-13-frontend-state / session-storage.
 * Anchor: remix/app/hooks/useNemesisChat.client.ts —— sessions ↔ localStorage 双向同步：第一个 useEffect 加载 + hasLoadedSessions ref + 第二个 useEffect 持久化 + MAX_NEMESIS_CHAT_SESSIONS slice
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/hooks/useNemesisChat.client.ts";
const sc = (id: string, text: string) => ({ id, text });

export const sessionStorageQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 多会话上限常量",
    prompt: "import { ____ } from \"~/nemesis/chat-ui-config\";",
    options: [],
    blanks: [{ id: "v", placeholder: "常量名", acceptedAnswers: ["MAX_NEMESIS_CHAT_SESSIONS"] }],
    correctAnswer: { type: "fill_blank", values: { v: "MAX_NEMESIS_CHAT_SESSIONS" } },
    explanation: { short: "MAX_NEMESIS_CHAT_SESSIONS 用于 sessions.slice(0, max) 上限裁剪。" },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/nemesis/chat-ui-config.ts"],
  }),
  q({
    type: "single_choice", title: "Q2 第一个 useEffect 初始化",
    prompt: "useEffect(() => { const localSessions = readNemesisChatSessions(); ... hasLoadedSessions.current = true; }, []);——空依赖 [] 含义？",
    options: [
      sc("A", "只在首次挂载跑一次——读 localStorage 初始化 sessions 是「单次副作用」；空依赖让 React 不重跑；标记 hasLoadedSessions=true 让后续写 effect 才生效"),
      sc("B", "永远跑"),
      sc("C", "只 SSR"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "空依赖 = 只在 mount 跑一次——典型「初始化」effect 模式。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 initialSessions fallback",
    prompt: "const initialSessions = localSessions.length > 0 ? localSessions : [createNemesisChatSession()];——意图？",
    options: [
      sc("A", "本地有就用，没有就建一个新会话——确保 hook 启动后 sessions 一定非空；activeSessionId 有目标可设；UI 不出现「无会话可选」尴尬态"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "fallback 创建空会话 = 保证 hook 启动后总有可用会话。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 setSessions + setActiveSessionId + setMessages 三连",
    prompt: "setSessions(initialSessions); setActiveSessionId(initialSession.id); setMessages(initialSession.messages); ——为什么三连同步？",
    options: [
      sc("A", "三个 state 反映同一初始化事件——React 18 自动 batch 三个 setter，单次重渲染；如果分散到不同 effect 会出现中间不一致状态"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "同事件多 setter → 同一 effect 内调，React 18 batch 单渲染。" },
    abilityTags: ["frontend.state.local", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 hasLoadedSessions ref 顺序",
    prompt: "useEffect 末尾 hasLoadedSessions.current = true; ——为什么放最后？",
    options: [
      sc("A", "确保 sessions 已设值后再标记「已 loaded」；如果先标 ref 再 set，第二个 useEffect 可能在初始 sessions=[] 时就触发写入空数组到 localStorage——把本地数据擦了"),
      sc("B", "随机"),
      sc("C", "无差"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ref 设置时机决定第二个 effect 何时生效——顺序错会擦数据。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 第二个 useEffect 写入",
    prompt: "useEffect(() => { if (hasLoadedSessions.current) { saveNemesisChatSessions(sessions); } }, [sessions]);——这是写 effect？",
    options: [
      sc("A", "对——sessions 任何变化（增删改）都触发；前置 hasLoadedSessions guard 跳过初始化阶段；典型「state ↔ persist storage」双向同步范式"),
      sc("B", "永远写"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "依赖 [sessions] + ref guard = 用户产生的任何变更都同步到 localStorage。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 不用 hasLoadedSessions 后果",
    prompt: "若删掉 hasLoadedSessions ref guard——后果？",
    options: [
      sc("A", "组件首次挂载 sessions 初值是 []（useState 默认）→ 第二个 effect 立刻触发写入 [] 到 localStorage→把用户已存的会话全部抹掉；下个第一个 effect 读到空就再建空会话；数据丢失"),
      sc("B", "无影响"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "缺 ref guard = 初始 [] 被立刻持久化覆盖本地——经典 race。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 ref 而不是 useState 标志位",
    prompt: "为什么用 useRef 而不是 useState 存 hasLoadedSessions？",
    options: [
      sc("A", "ref 修改不引发渲染——这个标志位只供 effect 内查询，不需要触发 UI 更新；用 state 会让设 true 再触发不必要的重渲；ref 是无渲染副作用的开关首选"),
      sc("B", "TypeScript"),
      sc("C", "性能差"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "「不需要触发渲染的标志」= ref 用例。" },
    abilityTags: ["frontend.state.local", "frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 upsertActiveSession 内 slice",
    prompt: "[{ ... newSession }, ...current.filter(...)].slice(0, MAX_NEMESIS_CHAT_SESSIONS);——slice 在最后？",
    options: [
      sc("A", "新会话置顶后保留前 N 个——超出阈值的旧会话自动丢弃；列表呈现「新→旧」顺序 + 总数有上限保护 localStorage 体积"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "新置顶 + slice 上限 = 「LRU-like」会话列表 + 体积保护。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 startNewSession",
    prompt: "const startNewSession = useCallback(() => { if (isLoading) return; const nextSession = createNemesisChatSession(); setSessions(c => [nextSession, ...c].slice(0, MAX)); ... });——首行 isLoading guard 含义？",
    options: [
      sc("A", "请求中不允许新建会话——会话切换会让 sendMessage 拿到 stale activeSessionId / messages，导致状态错乱；guard 让用户必须等当前请求完才能新建"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loading 期间禁动会话 = 防止与 in-flight 请求竞态。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 selectSession",
    prompt: "selectSession(sessionId) 内 if (isLoading || sessionId === activeSessionId) return;——双 guard 含义？",
    options: [
      sc("A", "isLoading：禁切；sessionId 等于当前：无效操作（重复切到自己）；两 guard 一起避免不必要的状态变更和闭包问题"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "load 中禁切 + 重复操作短路——状态变更前置防御。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 deleteSession 边界",
    prompt: "deleteSession 内：删完后 if (sessionId === activeSessionId) { const fallbackSession = nextSessions[0] ?? createNemesisChatSession(); ... }——为什么 fallback？",
    options: [
      sc("A", "删的是当前活跃会话——必须切到下一个；nextSessions[0] 是剩余最新；如果空数组（删了唯一会话）就建新；保证 activeSessionId 始终有目标"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "删活跃会话 → 必有 fallback；空时新建——activeSessionId 不变 null。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 ensuredSessions 三元",
    prompt: "const ensuredSessions = nextSessions.length > 0 ? nextSessions : [fallbackSession]; return ensuredSessions;——为什么不只 return nextSessions？",
    options: [
      sc("A", "若 nextSessions 为空（删完最后一个），UI 会进入「无会话」中间态闪一帧；用 fallback 保证返回至少 1 个会话；与上一题 fallback 配套"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "保证 sessions 永远非空 = UI 不出现空态。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 commitMessages 排序",
    prompt: "commitMessages 内 .sort((a, b) => b.updatedAt - a.updatedAt);——意图？",
    options: [
      sc("A", "活跃会话被改后，把它按 updatedAt 重排到列表前——最近更新的在最上；多会话场景下符合用户期望的「最近聊在最上」"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "更新即重排——「最近活跃在最上」交互模式。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 双 effect vs 一个 effect",
    prompt: "为什么用「读 effect」+「写 effect」两个，不合一个？",
    options: [
      sc("A", "读只在 mount 跑一次（[] 依赖），写在 sessions 每次变都跑（[sessions] 依赖）——依赖不同必须分两个；硬合一会迫使写也只在 mount 跑或读跟着 sessions 变重读，两者都错"),
      sc("B", "性能"),
      sc("C", "习惯"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "依赖不同 = 两个 effect；强合是反模式。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q16 用户首次访问→新建→关页→重访 完整流",
    prompt: "用户首次访问 chat 页，发一句话，关闭浏览器，下次重访——sessions 状态变化？",
    options: [
      sc("s1", "1. 首次挂载：useEffect [] 跑 → readNemesisChatSessions() 返 []"),
      sc("s2", "2. fallback 创建一个空 session → setSessions([emptySession]) + setActiveSessionId + setMessages([])"),
      sc("s3", "3. hasLoadedSessions.current = true 标记完成"),
      sc("s4", "4. 用户发「你好」→ sendMessage 内 upsertActiveSession 更新 sessions"),
      sc("s5", "5. 第二个 useEffect [sessions] 触发 → ref 已 true → saveNemesisChatSessions(sessions) 写 localStorage"),
      sc("s6", "6. 用户关页——内存状态丢，但 localStorage 留有 sessions"),
      sc("s7", "7. 下次重访：useEffect [] → readNemesisChatSessions() 返之前数据"),
      sc("s8", "8. localSessions.length > 0 → 直接用本地数据 → setSessions/setActiveSessionId/setMessages"),
      sc("s9", "9. ref 标记 true；后续 sessions 变更继续写本地——闭环"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8", "s9"] },
    explanation: { short: "完整双向同步链：mount 读 + 变更写 + 关页留本地 + 重访恢复——9 步。" },
    abilityTags: ["frontend.effect.useEffect", "frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 隐私模式问题",
    prompt: "若用户在隐私模式（localStorage 抛 SecurityError）——hook 行为？",
    options: [
      sc("A", "依赖封装层 readNemesisChatSessions / saveNemesisChatSessions 内部 try/catch；读返 []，写静默失败；hook 自身不感知错误，能正常工作但每次访问都从 0 开始"),
      sc("B", "崩溃"),
      sc("C", "永远 OK"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "持久化层封装吸收异常 = hook 在隐私模式仍能跑（无持久化）。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/lib/nemesis-chat-sessions.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q18 单标签 vs 多标签",
    prompt: "用户在 A 标签发消息后立刻切到 B 标签（同站同 hook 实例不同 React 树）——B 看到 A 的会话吗？",
    options: [
      sc("A", "B 是后挂载——读 localStorage 时拿到 A 写过的最新值；但 A 后续更新不会 push 到 B；多标签同步需要 storage 事件监听（当前未实现）；新标签首次加载是新鲜的，但实时同步缺失"),
      sc("B", "实时同步"),
      sc("C", "完全隔离"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "localStorage 跨标签：新标签首次读看到最新；运行时同步需 storage event。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 改用 IndexedDB",
    prompt: "若想从 localStorage 迁到 IndexedDB（容量更大）——影响范围？",
    options: [
      sc("A", "只改封装层 nemesis-chat-sessions.client.ts 内的 read/save 实现 + 改成 async；hook 内调用要改 await；effect 内的 save 异步化（无大问题）；分层封装的好处"),
      sc("B", "重写 hook"),
      sc("C", "无法迁"),
      sc("D", "TypeScript 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "持久化层换实现 = 局部改造；hook 业务逻辑稳定。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/lib/nemesis-chat-sessions.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q20 加云端同步",
    prompt: "想加「登录后会话同步到云」——落点？",
    options: [
      sc("A", "封装层加 syncSessionsToServer(sessions, userId)；第二个 effect 内 if (user) syncToServer(sessions) else saveLocal(sessions)；按登录态分流；hook 仍不变"),
      sc("B", "改 hook 大改"),
      sc("C", "改 root"),
      sc("D", "新 hook"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "持久化层增能 = 双轨（本地 + 云）；hook 接口稳定。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/lib/nemesis-chat-sessions.client.ts"],
  }),
  q({
    type: "true_false", title: "Q21 sessions 写 effect 是否会无限循环",
    prompt: "判断：useEffect(() => { saveNemesisChatSessions(sessions); }, [sessions]) 会因为写 localStorage 引发自身循环。",
    correctAnswer: { value: false },
    explanation: { short: "错——saveNemesisChatSessions 不读 sessions 也不 setSessions，effect 跑完就结束；不构成循环。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 持久化整体哲学",
    prompt: "sessions ↔ localStorage 同步整体哲学？",
    options: [
      sc("A", "1) 双 effect 拆读写——依赖不同必须分 2) ref 标记防初始化阶段空数组覆盖本地 3) fallback 保证 sessions 永远非空 4) slice 上限保护体积 5) 持久化用封装层（错误吸收 + 协议演进）6) 多会话场景默认本地 + 云同步可加 7) 重排让最近活跃在前——综合：可靠 + 鲁棒 + 可演进的客户端持久化范式"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "持久化 7 原则——客户端会话存储的工程典范。" },
    abilityTags: ["frontend.effect.useEffect", "frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/lib/nemesis-chat-sessions.client.ts"],
  }),
];
