/**
 * Real questions for site-13-frontend-state / state-capstone.
 * Anchor: remix/app/hooks/useNemesisChat.client.ts —— 综合：状态范围 / hook vs 组件 state / 加新功能 / SSR 边界 / 测试 / 性能 / 整体哲学
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/hooks/useNemesisChat.client.ts";
const sc = (id: string, text: string) => ({ id, text });

export const stateCapstoneQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 文件总长",
    prompt: "useNemesisChat.client.ts 总行数约 ____ 行（写整数）。",
    options: [],
    blanks: [{ id: "v", placeholder: "数字", acceptedAnswers: ["419", "420"] }],
    correctAnswer: { type: "fill_blank", values: { v: "419" } },
    explanation: { short: "419 行——单 hook 包揽聊天前端所有状态逻辑；接近拆分阈值。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 hook 与 NemesisChatPage 的边界",
    prompt: "为什么状态全在 useNemesisChat 而不放 NemesisChatPage 组件内？",
    options: [
      sc("A", "1) 解耦 UI 与状态——组件可单独优化渲染（拆子组件、改样式）不动状态机 2) 状态可独立单元测试（mock 网络层调 sendMessage 校验状态过渡）3) hook 可被多个组件消费（虽当前只一个）；分层让两边各自演进"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "hook 是 ViewModel——UI 与状态机两层各自演进。" },
    abilityTags: ["frontend.state.scope", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/nemesis/chat/NemesisChatPage.client.tsx"],
  }),
  q({
    type: "single_choice", title: "Q3 hook vs Context 取舍",
    prompt: "若想让聊天状态被 Header / Footer / Sidebar 多组件共享——保 hook 还是上 Context？",
    options: [
      sc("A", "上 Context——hook 实例化在每个组件独立；多组件共享必须放 Provider 提升 + useContext 消费；hook 仍可作 inner（在 Provider 内调）；分层 + 共享"),
      sc("B", "保 hook"),
      sc("C", "改 root"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "多组件共享 = Context Provider；hook 仍是状态实现层。" },
    abilityTags: ["frontend.state.scope", "frontend.state.global", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 hook 是否该上 useReducer",
    prompt: "419 行 14 个 useState——是否应整体改 useReducer？",
    options: [
      sc("A", "可考虑——多动作（send/regenerate/select/delete）多状态字段联动改写为 reducer 时，能用一个 dispatch 表达「整个事件」语义；但代价是新增 action types/reducer/payload 体系；当前 14 个 useState 仍可读时可不必"),
      sc("B", "立刻改"),
      sc("C", "永不改"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useReducer = 多状态联动事件的好选择；当前可读 = 不必强迁。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 hook SSR 安全",
    prompt: "useNemesisChat 在 Cloudflare Worker SSR 时绝不会被调用——靠什么？",
    options: [
      sc("A", "1) 文件 .client 后缀让 Remix 不打进 SSR bundle 2) 使用方 NemesisChatPage.client 同样 .client 隔离 3) chat.tsx 路由文件 SSR 渲染时 .client 组件位置只放占位，不挂 hook；三层隔离防 SSR 触发"),
      sc("B", "useEffect 隔离"),
      sc("C", "随机"),
      sc("D", "Cloudflare 拦截"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三层 .client 隔离 = SSR 安全保证。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/nemesis/chat/NemesisChatPage.client.tsx", "app/routes/chat.tsx"],
  }),
  q({
    type: "single_choice", title: "Q6 加 attachments 字段",
    prompt: "想让消息支持 attachments（图片/文件附件）。改动？",
    options: [
      sc("A", "1) 类型 Message 加 attachments?: Attachment[]——~/types/chat 内 2) sendMessage 接收 attachments 参数 + 加入 userMessage 3) buildAssistantMessage 也支持 4) UI 渲染层显示附件 5) localStorage 持久化已自动包含；类型先行 + 各层透传"),
      sc("B", "改 root"),
      sc("C", "改 wrangler"),
      sc("D", "改 D1"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "新字段加 = 类型 + 入口 + 渲染 + 持久化四面同步；类型先行驱动。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/types/chat.ts"],
  }),
  q({
    type: "single_choice", title: "Q7 加加密会话",
    prompt: "想让会话内容在 localStorage 加密——落点？",
    options: [
      sc("A", "封装层 nemesis-chat-sessions.client.ts 内 read/save 加 crypto.subtle 加解密；密钥存内存或派生自用户登录信息；hook 完全无感；持久化层是好的扩展点"),
      sc("B", "hook 改"),
      sc("C", "组件加"),
      sc("D", "改 root"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "加密 = 持久化层职责；hook 业务不动；分层的好处。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/lib/nemesis-chat-sessions.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q8 hook 测试策略",
    prompt: "如何对 useNemesisChat 写单元测试？",
    options: [
      sc("A", "用 @testing-library/react 的 renderHook + act：mock requestNemesisReply / readNemesisChatSessions；调 sendMessage 后断言 messages / isLoading / error 状态过渡；副作用 effect 通过 act 内 await 触发；reducer 化后更易测"),
      sc("B", "无法测"),
      sc("C", "改 hook"),
      sc("D", "用 Cypress"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "renderHook + mock 网络/存储 + act 触发——hook 单测标准。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 hook 性能",
    prompt: "419 行 14 个 useState + 5 useEffect——性能瓶颈在哪？",
    options: [
      sc("A", "实际无瓶颈：每次 setState 触发一次重渲；useState 分散反而精确（合并对象会让所有消费 props 失效）；useCallback 让函数引用稳；profiler 才是判官，结构上没明显问题"),
      sc("B", "致命"),
      sc("C", "应改 useReducer"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "结构无瓶颈；优化看 profiler 实测——直觉不是依据。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 hook 易出错地方",
    prompt: "419 行最容易出错的是哪类？",
    options: [
      sc("A", "依赖数组写错——useCallback / useEffect 的依赖漏列会导致闭包陷阱（stale state）；exhaustive-deps lint 是必装防线；其次是「初始化 race」（session-storage 课讲过的 ref 防御）"),
      sc("B", "样式"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "hook 主要 bug 来源 = 依赖数组 + 初始化 race。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q11 复杂全流：登录 → 切会话 → 重发 → 反馈",
    prompt: "用户已登录，从会话 A 切到 B，对 B 中的助手消息点反馈，然后重发——状态变化序列？",
    options: [
      sc("s1", "1. selectSession(B) → guard 通过 → setActiveSessionId(B) + setMessages(B 的 messages) + setError(null) + setRequestStage(null) + setTypingMessageId(null)"),
      sc("s2", "2. useEffect [activeSessionId] 触发 → textareaRef.focus()"),
      sc("s3", "3. 用户点助手消息「反馈」按钮 → openFeedback(messageId) → setFeedbackMessageId(messageId) + reset 表单"),
      sc("s4", "4. 用户填类别和备注 → setFeedbackCategory + setFeedbackNote"),
      sc("s5", "5. 提交反馈 → submitFeedback → guard 通过 → setFeedbackSubmittingId(id) → 调 submitNemesisFeedback API"),
      sc("s6", "6. API 成功 → setSubmittedFeedbackIds 加入 + setFeedbackMessageId(null) 关闭弹层 + setFeedbackNote('')"),
      sc("s7", "7. 用户对最后助手消息点重发 → regenerateResponse(id)"),
      sc("s8", "8. 找前置 user 消息 → commitMessages 暂时移除旧助手消息 + setIsLoading(true) + setRequestStage(initial)"),
      sc("s9", "9. await requestNemesisReply 成功 → commitMessages 加入新助手消息 + setTypingMessageId(新id)"),
      sc("s10", "10. finally：setIsLoading(false) + setRequestStage(null)"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8", "s9", "s10"] },
    explanation: { short: "复杂多事件 10 步——切会话+反馈+重发的状态机协奏。" },
    abilityTags: ["frontend.state.local", "frontend.event.submit", "frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 hook 与 nemesis-chat-api.client 的边界",
    prompt: "网络层 nemesis-chat-api.client.ts 与 hook 各自管什么？",
    options: [
      sc("A", "网络层：HTTP/SSE 协议、JSON 解析、错误规范化、进度回调推送；hook：状态机、UI 时序、用户事件响应；网络变化（如换 SSE → WebSocket）只动网络层；hook 业务稳定"),
      sc("B", "全在 hook"),
      sc("C", "全在网络"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "分层契约：网络处理协议；hook 处理状态——演进面隔离。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/lib/nemesis-chat-api.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q13 hook 演进：拆 sub-hook",
    prompt: "若文件膨胀到 700 行——拆分策略？",
    options: [
      sc("A", "1) useNemesisSessions（多会话状态 + localStorage）2) useNemesisMessages（当前 messages + send/regenerate）3) useNemesisFeedback；3 个独立 hook，主 useNemesisChat 组合调用——保持对外 API 稳定"),
      sc("B", "强拆组件"),
      sc("C", "改 redux"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "拆 sub-hook + 主 hook 组合 = 文件膨胀的标准应对。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 hook 与 SSR 注水",
    prompt: "若想从 chat.tsx loader 里返回服务端读到的会话历史，让 hook 用作初值——怎么改？",
    options: [
      sc("A", "1) chat.tsx loader 改成 return json({ sessions }); 2) NemesisChatPage 用 useLoaderData 拿 sessions 3) 把 sessions 作为 useNemesisChat(initial?) 参数；hook 第一个 useEffect 读 localStorage 时优先用 initial（如果有）；服务端 + 本地双源合并"),
      sc("B", "改 wrangler"),
      sc("C", "改 root"),
      sc("D", "无法实现"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SSR 注水 = loader 返数据 + hook 接初值 + 优先级合并。" },
    abilityTags: ["bridge.reactRouter.loader", "project.modify.fullstack", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/chat.tsx"],
  }),
  q({
    type: "single_choice", title: "Q15 加「编辑用户消息后重发」",
    prompt: "想让用户点一条已发的消息进入编辑→改完→重新发。改动？",
    options: [
      sc("A", "新加 editMessageId state + 新 callback editMessage(messageId, newContent) 内：移除当前消息及之后 → sendMessage(newContent)；状态机扩展不破坏现有 send 逻辑"),
      sc("B", "改 root"),
      sc("C", "改 server"),
      sc("D", "无法实现"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "「编辑后重发」= 移除尾部消息后调 sendMessage——复用核心 API。" },
    abilityTags: ["project.modify.fullstack", "frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 hook 内不引 Remix",
    prompt: "useNemesisChat 不 import @remix-run/* 任何 API——为什么？",
    options: [
      sc("A", "保 hook 与框架解耦——若未来从 Remix 迁 Next.js / 纯 React，hook 业务可直接用；网络/存储/状态全是浏览器能力，不依赖框架；可移植性"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "hook 框架无关 = 可移植；Remix 接口在路由 / 组件层用就好。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 typeof messages.length",
    prompt: "useEffect(..., [isLoading, messages.length, scrollToBottom])——依赖用 messages.length 而不是 messages？",
    options: [
      sc("A", "messages 数组每次 setMessages 都是新引用——会让 effect 在每次细微改动都重跑；用 .length 仅当数量变化才触发滚——精确触发；当 commitMessages 替换助手消息但长度不变时不必滚"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "依赖 .length 而非数组本身 = 仅数量变才触发——精确 effect。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 hook 与全站状态管理",
    prompt: "若项目其他地方用 Zustand/Redux——chat 状态是否该融入？",
    options: [
      sc("A", "chat 状态高度局部（只 NemesisChatPage 用）+ 业务逻辑复杂，独立 hook 更清晰；非「全站共享」状态没必要塞 store；store 适合用户、主题、通知这种全局贯穿"),
      sc("B", "必须融入"),
      sc("C", "永不"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "局部状态用 hook；全站共享用 store——按作用域选工具。" },
    abilityTags: ["frontend.state.scope", "frontend.state.global", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 hook 内的命名约定",
    prompt: "命名：activeSession（对象）/ activeSessionId（id）/ initialSessions（参数）—风格一致？",
    options: [
      sc("A", "对——「形容词 + 名词」格式，区分 session 还是 id；initialSessions 名前缀 initial 表「构造期」；命名一致让 419 行可读性显著提升"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "命名约定一致 = 大文件可读性的关键。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 改写为 Server-driven state",
    prompt: "若要把所有会话存服务端（非 localStorage），由服务端 push 状态——hook 还需要吗？",
    options: [
      sc("A", "仍需要——hook 仍管「optimistic 更新」「打字机时序」「错误展示」「输入框」等纯 UI 状态；服务端只管「持久化的会话与消息」；分工不同；hook 不会消失只会瘦身"),
      sc("B", "可去掉"),
      sc("C", "全改 server"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "server-driven 也需 client UI 状态——hook 仍是 ViewModel 层。" },
    abilityTags: ["ai.review.architecture", "frontend.state.scope"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 hook 的导出接口稳定性",
    prompt: "export type NemesisChatController = ReturnType<typeof useNemesisChat>;——若 hook 内部加新字段——破坏性？",
    options: [
      sc("A", "新增字段是非破坏（消费者按需取）；删除/重命名才破坏；ReturnType 让类型自动跟实现走；新增是「向后兼容」演进"),
      sc("B", "永远破坏"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ReturnType 类型 + 新增字段 = 兼容演进；删/改才破坏。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 useNemesisChat 整体哲学",
    prompt: "useNemesisChat 419 行整体设计哲学（一站式总结）？",
    options: [
      sc("A", "1) 单一 hook 包揽聊天 ViewModel——状态 + 副作用 + 操作三件套打包给消费者 2) 状态分散 14 个 useState 精确更新 + 派生值不入 state 3) ref 区分 DOM 句柄与「不渲染标记」4) 网络/存储分层封装让 hook 业务稳定 5) 三处 catch 统一收窄 + 业务/网络错误区分文案 6) 5 effect 各管一事 + .length 依赖精确触发 7) 框架无关可移植 + ReturnType 类型自动 8) 缺口认知：AbortController / focus 还原 / 多标签同步——综合：「业务驱动 ViewModel hook + 分层网络存储 + 状态机精准 + 缺口透明」"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "419 行 8 原则 = 大型聊天前端状态机的工程范式。" },
    abilityTags: ["frontend.state.local", "frontend.state.scope", "frontend.effect.useEffect", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
];
