/**
 * Real questions for site-13-frontend-state / submit-chain.
 * Anchor: remix/app/hooks/useNemesisChat.client.ts —— sendMessage 链：trim → optimistic user msg → upsertActiveSession → setIsLoading → requestNemesisReply（SSE 进度回调） → buildAssistantMessage → typingMessageId
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/hooks/useNemesisChat.client.ts";
const sc = (id: string, text: string) => ({ id, text });

export const submitChainQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 sendMessage 第一行 guard",
    prompt: "const message = (messageToSend || inputMessage).____();",
    options: [],
    blanks: [{ id: "v", placeholder: "方法", acceptedAnswers: ["trim"] }],
    correctAnswer: { type: "fill_blank", values: { v: "trim" } },
    explanation: { short: "trim() 去首尾空白——空格-only 输入要被视为空。" },
    abilityTags: ["frontend.event.submit"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 if (!message || isLoading) return",
    prompt: "if (!message || isLoading) { return; }——双 guard 意图？",
    options: [
      sc("A", "空消息不该发；正在请求中再触发会发起并发请求 + UI 状态混乱；显式 early return = 单点拦截无效调用"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "input 边界 + 状态边界双 guard——发函数顶部规范。" },
    abilityTags: ["frontend.event.submit", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 messageToSend || inputMessage",
    prompt: "sendMessage(messageToSend?: string)——首参可选，默认用 inputMessage？",
    options: [
      sc("A", "支持两个调用模式：1) 普通发送：用户在输入框打字，sendMessage() 用 inputMessage 2) 重发/快捷：sendMessage('某固定文本') 直接传——一个函数同时服务两类入口"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "可选首参 = 一个函数支持「输入框」与「快捷按钮」双入口。" },
    abilityTags: ["frontend.event.submit", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 sessionId fallback",
    prompt: "const sessionId = activeSessionId ?? createNemesisChatId(); if (!activeSessionId) { setActiveSessionId(sessionId); }——为什么这样写？",
    options: [
      sc("A", "活跃会话不存在时即时创建——首次进入页面或刚删完所有会话；不依赖额外 effect 来保证 activeSessionId 总有值；发函数即建会话"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "lazy 创建会话 = 任何 send 触发都能成功建会话——避免空状态。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 history = messages",
    prompt: "const history = messages;——意图？",
    options: [
      sc("A", "把当前 messages 数组作为「历史上下文」快照——稍后传给 requestNemesisReply 让模型看到之前对话；快照避免后续闭包变化"),
      sc("B", "TypeScript"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "history = 当前 messages 的命名快照——传给 API 用作模型上下文。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 optimistic 用户消息",
    prompt: "const userMessage = { id: createNemesisChatId(), role: 'user', content: message, timestamp: Date.now() }; const nextMessages = [...history, userMessage]; setMessages(nextMessages);——这是 optimistic update？",
    options: [
      sc("A", "对——不等服务端确认，立刻把用户消息显示在 UI 上；如果请求失败 catch 不会回滚（但下面的代码确实没 rollback；改进点）；UX 优先：让用户即时看到自己说的话"),
      sc("B", "等服务端"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "optimistic update = 即时反馈；用户消息属于不易出错的写——不滚也合理。" },
    abilityTags: ["frontend.event.submit", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 createNemesisChatId",
    prompt: "id: createNemesisChatId()——为什么前端生成 id 不让服务端给？",
    options: [
      sc("A", "前端 id 让消息能立刻渲染（React key + 后续 update 定位）；服务端再返回相同 id 只需校验一致；客户端 id 是 optimistic 更新的关键基础"),
      sc("B", "TypeScript"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "前端生成 id = optimistic UI 必备——消息渲染先于网络确认。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/lib/nemesis-chat-sessions.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q8 upsertActiveSession 调用",
    prompt: "upsertActiveSession(sessionId, nextMessages);——为什么显式 upsert？",
    options: [
      sc("A", "新建会话时 sessions 数组里还没这个 id；upsert = 「有就更新，没有就插入」；同步把 messages 写入 sessions 里对应那一项；让 sessions 与 messages 始终一致"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "upsert = sessions 列表与 messages 同步——两个 state 一致性维护。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 setInputMessage('')",
    prompt: "setInputMessage('');——清空输入框时机？",
    options: [
      sc("A", "在 optimistic 加用户消息后立刻清——用户视觉上「说完话立刻准备下一条」；不等服务端响应；同时 textareaRef.current.style.height='auto' 重置高度"),
      sc("B", "在 finally"),
      sc("C", "在 catch"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "立刻清输入 + 重置高度 = 即时反馈 UX。" },
    abilityTags: ["frontend.event.submit", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 setIsLoading + setRequestStage",
    prompt: "setIsLoading(true); setRequestStage(createInitialNemesisProgress());——两个一起设？",
    options: [
      sc("A", "isLoading 是「请求进行中」二值开关；requestStage 是「具体阶段（鉴权 → 模型 → 完成）」详细数组；两个互补：isLoading 控按钮 disabled，requestStage 显示进度"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "两个 state 同步开始 = 不同视图层使用不同粒度。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 textareaRef.current.style.height = 'auto'",
    prompt: "if (textareaRef.current) { textareaRef.current.style.height = 'auto'; }——为什么直接操作 DOM？",
    options: [
      sc("A", "auto-resize textarea 是 DOM 测量场景：必须先 height='auto' 让浏览器算 scrollHeight 再设新高；这是 imperative 操作的合理位置——React 的声明式不擅长「测量后修改」"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "imperative DOM = 测量场景的逃生口；声明式做不到的事用 ref 做。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 scrollToBottom",
    prompt: "scrollToBottom();——内部用 requestAnimationFrame 包裹？",
    options: [
      sc("A", "rAF 让滚动发生在下一帧——上面 setMessages 还没真正反映到 DOM；rAF 在浏览器布局/绘制前的同步点滚动到 scrollHeight，能滚到刚加的消息"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "rAF = 等下一帧 DOM 更新完再滚动 → scrollHeight 反映新消息。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 try / await requestNemesisReply",
    prompt: "const answer = await requestNemesisReply(message, history, setRequestStage);——第三参数为什么是 setRequestStage？",
    options: [
      sc("A", "网络层在收到 SSE 进度事件时回调 setRequestStage(newStages)——逐步更新进度数组；hook 把 setter 注入网络层，把 SSE 进度桥接到 React state"),
      sc("B", "TypeScript"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "setter 当 callback 注入 = SSE 进度→React state 的桥。" },
    abilityTags: ["frontend.state.local", "frontend.event.submit", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/lib/nemesis-chat-api.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q14 buildAssistantMessage",
    prompt: "const assistantMessage = buildAssistantMessage(answer, message);——为什么需要 message 参数？",
    options: [
      sc("A", "助手消息可能要嵌入 sources/citations 时引用用户原问题做关联；或在 metadata 里存 user_query；封装函数把多字段组装一处；hook 不关心细节"),
      sc("B", "TypeScript"),
      sc("C", "随机"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "buildAssistantMessage 是消息构造工厂——附带用户问题可做关联字段。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/lib/nemesis-chat-api.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q15 setTypingMessageId",
    prompt: "setMessages(answeredMessages); upsertActiveSession(sessionId, answeredMessages); setTypingMessageId(assistantMessage.id);——三步顺序意图？",
    options: [
      sc("A", "1) messages 加入完整的回复消息 2) 同步到 sessions 持久化层 3) 标记本条「正在打字机播放」让 UI 启动逐字渲染；播完后 finishTypingMessage 清 typingMessageId；显示完整内容前先有打字机过渡"),
      sc("B", "随机顺序"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "插入完整消息 + 标记打字机——内容已就绪 UI 渐进展示。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 catch 块",
    prompt: "} catch (err) { setError(err instanceof Error ? err.message : DEFAULT_ERROR_MESSAGE); }——为什么写 instanceof？",
    options: [
      sc("A", "JS 任何东西都能 throw（字符串/对象/Error）；只有 Error 才有可读 message；用 instanceof Error 收窄后取 message 否则用 DEFAULT_ERROR_MESSAGE 兜底；防御编程"),
      sc("B", "TypeScript 强制"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "catch 入参 unknown → instanceof 收窄取 message；缺省兜底字符串。" },
    abilityTags: ["frontend.event.submit", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 finally 清理",
    prompt: "} finally { setIsLoading(false); setRequestStage(null); }——这两步为什么放 finally？",
    options: [
      sc("A", "无论成功（try 跑完）还是失败（catch 处理）都要清理 loading 状态——finally 是「必跑」语义；放 try 里失败不会跑、放 catch 里成功不会跑"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "finally = 必跑清理——loading state 不应留挂。" },
    abilityTags: ["frontend.event.submit", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q18 sendMessage 完整成功流",
    prompt: "用户在输入框打「你好」按 Enter 触发 handleEnter → sendMessage()，完整步骤？",
    options: [
      sc("s1", "1. trim 后 message='你好' 不空 + 不在 loading"),
      sc("s2", "2. activeSessionId 已有 → sessionId = 它"),
      sc("s3", "3. history = messages 快照；userMessage 创建 + nextMessages 拼接"),
      sc("s4", "4. setMessages(nextMessages) optimistic 渲染用户消息"),
      sc("s5", "5. upsertActiveSession 同步到 sessions"),
      sc("s6", "6. setInputMessage('') + textarea height='auto' + setIsLoading(true) + setRequestStage(initial)"),
      sc("s7", "7. scrollToBottom 用 rAF 滚动"),
      sc("s8", "8. await requestNemesisReply 触发 SSE 请求；onProgress 回调持续 setRequestStage"),
      sc("s9", "9. 服务端流完返 answer → buildAssistantMessage 拼成 assistantMessage"),
      sc("s10", "10. setMessages 加入助手消息 + upsertActiveSession 持久化"),
      sc("s11", "11. setTypingMessageId(id) 启动打字机；scrollToBottom"),
      sc("s12", "12. finally：setIsLoading(false) + setRequestStage(null)"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8", "s9", "s10", "s11", "s12"] },
    explanation: { short: "sendMessage 12 步全链——guard + optimistic + SSE 进度 + 打字机收尾。" },
    abilityTags: ["frontend.event.submit", "frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 网络失败时状态",
    prompt: "若 requestNemesisReply throw（网络断）——发送后 UI 状态？",
    options: [
      sc("A", "messages 仍含用户消息（optimistic 没回滚）+ error 显示错误文案 + isLoading=false（finally）+ requestStage=null；用户能看到自己的话还在但响应失败"),
      sc("B", "全部重置"),
      sc("C", "崩溃"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "失败时用户消息保留 + error 显错——可让用户看到上下文便于重试。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 没用 AbortController",
    prompt: "sendMessage 内没 AbortController——若用户切换会话怎么办？",
    options: [
      sc("A", "当前实现：请求继续跑，结果回来后写到旧 sessionId 对应 sessions 项；selectSession 已设新 messages，但旧请求结果可能更新了 sessions 中旧会话项；改进方向：AbortController + 在 selectSession 中 abort"),
      sc("B", "无问题"),
      sc("C", "崩溃"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "缺 AbortController = 切会话不取消旧请求；改进点。" },
    abilityTags: ["frontend.event.submit", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 加 retry 按钮",
    prompt: "想加「失败时点击重试」按钮。落点？",
    options: [
      sc("A", "暴露 sendMessage 给消费者已经够——错误时 NemesisChatPage 显示 error + button onClick={() => sendMessage(lastUserMessage.content)}；hook 不必新增 retry 函数；现有 API 复用"),
      sc("B", "新加 hook"),
      sc("C", "改 API"),
      sc("D", "改 root"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "已有 sendMessage 支持外部传内容 → 直接复用做 retry。" },
    abilityTags: ["project.modify.fullstack", "frontend.event.submit", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 sendMessage 哲学整体",
    prompt: "sendMessage 整体设计哲学？",
    options: [
      sc("A", "1) 顶部双 guard 拦无效 2) sessionId lazy fallback 让单步即建会话 3) optimistic 加用户消息 + 立刻清输入 4) loading + requestStage 双粒度状态 5) setter 注入网络层桥接 SSE 进度 6) catch 用 instanceof Error 收窄 + finally 必清 7) typingMessageId 标记打字机过渡——综合：状态机驱动 + 即时反馈 + 错误防御一体"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "sendMessage 7 原则——前端聊天「乐观更新」与「状态机收尾」典范。" },
    abilityTags: ["frontend.event.submit", "frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
];
