/**
 * Real questions for site-14-loader-read / cache-headers-read.
 * Anchor: remix/app/lib/cache-headers.server.ts —— 30 行常量与一个 forwardLoaderCacheControl HeadersFunction：NO_STORE / TOKEN_DATA / forwardLoaderCacheControl
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/lib/cache-headers.server.ts";
const sc = (id: string, text: string) => ({ id, text });

export const cacheHeadersReadQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 NO_STORE 三件套",
    prompt: "Cache-Control: 'no-cache, no-store, ____'——三个指令组合。",
    options: [],
    blanks: [{ id: "v", placeholder: "指令", acceptedAnswers: ["must-revalidate"] }],
    correctAnswer: { type: "fill_blank", values: { v: "must-revalidate" } },
    explanation: { short: "no-cache + no-store + must-revalidate = 强制每次回源，旧缓存无效化。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 NO_STORE 三个指令",
    prompt: "no-cache + no-store + must-revalidate 三者职责差异？",
    options: [
      sc("A", "no-cache: 缓存可存但用前必校验（304）；no-store: 完全不存（最强禁存）；must-revalidate: 旧资源到期后必校验不复用；三者叠加 = 最严格的「不缓存」语义"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三指令叠加 = 防 CDN/浏览器/中间代理任意层缓存——最严格。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 NO_STORE 用在哪",
    prompt: "什么样的响应该用 NO_STORE_HEADERS？",
    options: [
      sc("A", "私密/动态数据：1) 用户 session 相关（chat 页响应） 2) 错误响应（401/403/429） 3) Set-Cookie 响应 4) 实时数据（API 错误回包）；CDN 缓存这些会跨用户泄密 + 显示过期数据"),
      sc("B", "静态资源"),
      sc("C", "图片"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "私密/动态/Cookie 响应 → NO_STORE，防 CDN 跨用户共享。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 JSON_NO_STORE_HEADERS",
    prompt: "JSON_NO_STORE_HEADERS = { ...NO_STORE_HEADERS, 'Content-Type': 'application/json' }——为什么单独导出？",
    options: [
      sc("A", "API 响应必有 Content-Type:application/json + 缓存禁止；项目频繁组合 → 一次定义复用；调用点 return json(data, { headers: JSON_NO_STORE_HEADERS }) 一行清晰"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "JSON + NO_STORE 高频组合 → 命名常量复用——DRY。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/routes/api.nemesis.ts"],
  }),
  q({
    type: "single_choice", title: "Q5 TOKEN_DATA_CACHE_HEADERS",
    prompt: "'public, max-age=300'——300 秒 = 5 分钟为什么这样定？",
    options: [
      sc("A", "token data 是相对稳定但要可更新的资源；5 分钟够 CDN 缓存减负且变化能 5 分内生效；public 让 CDN 缓存（不限私有）；max-age=300 = 平衡新鲜度 vs 缓存命中"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "max-age=300 = 5 分钟过期；public 让 CDN 缓存——半静态资源平衡。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 public vs private",
    prompt: "Cache-Control 的 public 与 private 差异？",
    options: [
      sc("A", "public: CDN/中间代理可缓存（共享缓存层）；private: 仅终端浏览器可缓存（共享代理不能存）；含用户身份的响应必 private 防跨用户泄露；公开资源用 public 提高命中率"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "public = CDN 共享；private = 仅浏览器——隐私分级。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 forwardLoaderCacheControl",
    prompt: "export const forwardLoaderCacheControl: HeadersFunction = ({ loaderHeaders }) => { ... }——为什么 Remix 需要这个？",
    options: [
      sc("A", "Remix v3_singleFetch 模式下 loader 设的 Cache-Control 不会自动写到文档响应——必须在 export const headers 内显式从 loaderHeaders 读再返回；不导出 headers 函数则缓存头丢失；这是版本协议要求"),
      sc("B", "可选"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "v3_singleFetch = loader 头不自动转发，必须 headers 导出转发。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/routes/chat.tsx"],
  }),
  q({
    type: "single_choice", title: "Q8 HeadersFunction 类型",
    prompt: "HeadersFunction from @remix-run/cloudflare——签名 ({ loaderHeaders, parentHeaders, errorHeaders, actionHeaders }) => HeadersInit",
    options: [
      sc("A", "Remix 路由级 headers 钩子类型——Remix 调用并合并多层路由头；返回值会成为响应头；强类型保证不写错字段"),
      sc("B", "运行时验证"),
      sc("C", "随机"),
      sc("D", "ORM"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "HeadersFunction = 路由头钩子签名——Remix 协议。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 loaderHeaders.get",
    prompt: "const cacheControl = loaderHeaders.get('Cache-Control'); if (!cacheControl) return {};——空时返回？",
    options: [
      sc("A", "loader 没设 Cache-Control 就返 {} 不强行加；防止覆盖默认行为；调用方有责任设头则转发，无则放行"),
      sc("B", "throw"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "可选转发模式——loader 没设就放行，防默认行为被覆盖。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 Vary 也转发",
    prompt: "const vary = loaderHeaders.get('Vary'); if (vary) headers.Vary = vary;——为什么也要转发 Vary？",
    options: [
      sc("A", "Vary 告诉缓存层「按哪个请求头分桶」（如 Accept-Encoding 区分 gzip/br）；不转发 Vary 缓存层会跨编码错误共享内容；与 Cache-Control 配合使缓存正确分组"),
      sc("B", "无关"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Vary = 缓存分桶维度——必与 Cache-Control 配套转发。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 Vary 常见值",
    prompt: "Vary 常见取值的语义？",
    options: [
      sc("A", "Vary: Accept-Encoding 按 gzip/br 区分；Vary: Cookie 按 cookie 区分（私密资源必须）；Vary: Accept-Language 按多语言；多值用逗号分隔；告诉缓存层缓存键应包含哪些请求头"),
      sc("B", "随机"),
      sc("C", "无意义"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Vary = 缓存键的额外维度——多值逗号分隔。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 chat.tsx 实例",
    prompt: "chat.tsx loader 设 'Cache-Control': 'private, no-store' + Vary: 'Accept-Encoding'，再 export const headers = forwardLoaderCacheControl;——这样有效吗？",
    options: [
      sc("A", "有效——loader 设头 + headers 函数转发 = chat 文档响应带 private/no-store；private 因含登录态防 CDN 共享；Vary 让 gzip/br 分桶；登录态页的标准搭配"),
      sc("B", "无效"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader 设 + headers 转发 = 缓存头生效；登录态页标准搭配。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/routes/chat.tsx"],
  }),
  q({
    type: "single_choice", title: "Q13 max-age vs s-maxage",
    prompt: "max-age 与 s-maxage 差异？",
    options: [
      sc("A", "max-age 浏览器 + 共享代理都遵循；s-maxage 仅 CDN/共享代理遵循（覆盖 max-age）；常见 'public, max-age=60, s-maxage=3600' = 浏览器 1 分钟过期 CDN 1 小时缓存；细分两层缓存策略"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "max-age = 全层；s-maxage = 仅 CDN——细化两层缓存。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 stale-while-revalidate",
    prompt: "Cache-Control: 'public, max-age=60, stale-while-revalidate=600' 的含义？",
    options: [
      sc("A", "60 秒内直接返缓存；60 秒-660 秒内返旧缓存 + 后台异步刷新（用户秒回 + 数据自动更新）；超 660 秒回源；现代缓存策略：性能 + 新鲜度兼顾"),
      sc("B", "无意义"),
      sc("C", "性能差"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SWR = max-age 后旧值秒回 + 后台刷新——现代缓存模式。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 immutable",
    prompt: "Cache-Control: 'public, max-age=31536000, immutable' 用于？",
    options: [
      sc("A", "内容哈希文件名的静态资源（image-manifest 的 cdn 文件 / build 输出 JS）——文件名变 = 内容必变；immutable 告诉浏览器永不重验；max-age 一年极限缓存；CDN 静态站标配"),
      sc("B", "动态"),
      sc("C", "API"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "immutable + 长 max-age = 哈希命名静态资源极限缓存策略。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 错误：动态接口设了 max-age",
    prompt: "如果 api.nemesis.ts 误用 'public, max-age=600' —— 后果？",
    options: [
      sc("A", "1) CDN 缓存这个 POST 响应（其实 POST 通常不缓但错配可能命中） 2) 即使是 GET 也跨用户共享聊天结果——跨用户泄密 + 永远旧响应；私密 API 必 NO_STORE"),
      sc("B", "性能更好"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "私密 API 误用 public/max-age = 跨用户泄密——安全事故。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 错误：忘了导出 headers",
    prompt: "loader 设了 'public, max-age=3600' 但路由文件没 export const headers——结果？",
    options: [
      sc("A", "v3_singleFetch 模式下文档响应不带 Cache-Control（loader 头被丢弃）→ 浏览器走默认（通常无缓存）→ 缓存策略失效；必须导出 headers 转发；常见疏忽"),
      sc("B", "自动转发"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "v3_singleFetch 必导 headers——不导 loader 头丢失。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 ETag",
    prompt: "Cache-Control 之外，ETag 的作用？",
    options: [
      sc("A", "ETag = 资源指纹（hash 或 mtime）；浏览器附带 If-None-Match: 'xxx' 请求 → 服务器对比若不变返 304 Not Modified（无 body）→ 节省传输；与 Cache-Control 配合做条件请求"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ETag = 资源指纹 + 304 协议——节省传输的条件请求。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 调试缓存",
    prompt: "怎么验证某个响应缓存头生效？",
    options: [
      sc("A", "1) DevTools Network 看 Response Headers 的 Cache-Control 2) 第二次刷新看是否 from disk cache / from memory cache 3) curl -I URL 看头 4) 大型站用 Cloudflare cf-cache-status 头看 HIT/MISS；多手段验证"),
      sc("B", "无法验"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "DevTools + curl + cf-cache-status = 缓存调试三件套。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 缓存策略决策树",
    prompt: "根据资源类型选缓存策略——常见决策？",
    options: [
      sc("A", "1) 哈希命名静态：immutable + 1 年 2) 静态文档：max-age=300/SWR 3) 半静态 API（图书列表）：public + max-age=60-300 4) 私密 API：NO_STORE 5) 错误响应：NO_STORE 6) Set-Cookie 响应：private + no-store；按敏感度 + 变化频率分级"),
      sc("B", "全 NO_STORE"),
      sc("C", "全长 max-age"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "敏感度 + 变化频率 = 缓存策略决策两轴。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 加新缓存常量",
    prompt: "要给图书列表 API 加 SHORT_PUBLIC_CACHE_HEADERS = { 'Cache-Control': 'public, max-age=60, stale-while-revalidate=300' }——加哪？",
    options: [
      sc("A", "cache-headers.server.ts 内统一定义；loader 内 headers: SHORT_PUBLIC_CACHE_HEADERS；headers 导出 forwardLoaderCacheControl 转发；集中管理一致"),
      sc("B", "loader 内联"),
      sc("C", "组件内"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "新缓存常量 → cache-headers.server.ts 集中——一致性管理。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 cache-headers.server.ts 整体哲学",
    prompt: "cache-headers.server.ts 的整体哲学？",
    options: [
      sc("A", "1) 命名常量复用（NO_STORE / JSON_NO_STORE / TOKEN_DATA）减少散乱 2) JSON 版本附 Content-Type 是常组合的便利 3) forwardLoaderCacheControl 处理 v3_singleFetch 协议（loader 头不自动转发） 4) 也转发 Vary 保缓存分桶正确 5) 私密响应用 NO_STORE 三件套（no-cache/no-store/must-revalidate） 6) 半静态用 max-age + public 7) 集中管理便于策略调整 + grep 一目了然；综合：「常量复用 + 协议适配 + 分级策略」三件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "cache-headers 三原则——HTTP 缓存层纪律。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
];
