/**
 * Real questions for site-14-loader-read / db-read.
 * Anchor: remix/app/lib/db.server.ts —— D1Database 在 loader 内的封装：prepare/bind/all/get/run + getAuthDb (Kysely) 双层 + normalizeParam 类型转换
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/lib/db.server.ts";
const sc = (id: string, text: string) => ({ id, text });

export const dbReadQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 D1 入口",
    prompt: "db.server.ts 顶层不调 env.DB，而是 ____ ()——为什么走这个 getter？",
    options: [],
    blanks: [{ id: "v", placeholder: "函数名", acceptedAnswers: ["getDatabaseBinding"] }],
    correctAnswer: { type: "fill_blank", values: { v: "getDatabaseBinding" } },
    explanation: { short: "getDatabaseBinding 走 cloudflare-env.server.ts → 模块顶层 import 期 env 还未 ready，必须 lazy。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/utils/cloudflare-env.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q2 prepare/bind 包装层",
    prompt: "D1PreparedStatementWrapper 把 D1Database 原生 prepare 又包了一层——为什么不直接调 env.DB.prepare(...).bind(...)？",
    options: [
      sc("A", "包装层 1) lazy 解析 binding（每次 bind 时取） 2) normalizeParam 把 boolean/undefined 转 0/1/null（D1 不支持 boolean） 3) 统一接口 .all/.get/.run 4) 泛型 T 提供类型安全；hot path 不重复散落"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "包装 = lazy + 类型转换 + 接口统一三大职责。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 normalizeParam",
    prompt: "normalizeParam 把 boolean→0/1、undefined→null——为什么 D1 需要这层？",
    options: [
      sc("A", "D1 SQLite 协议只接受 string/number/null/blob——boolean 不是合法参数会抛错；undefined 会被序列化成 'undefined' 字符串而不是 NULL；不规范化必造成运行时错误"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "D1 协议有严格类型——boolean/undefined 必须规范化。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 .all vs .get vs .run",
    prompt: "wrapper 暴露三个方法的差异？",
    options: [
      sc("A", ".all 取多行（results 数组） .get 取首行（first 单条 → undefined） .run 写操作（拿 changes/lastInsertRowid 元数据）；语义对应 SELECT-多/SELECT-一/INSERT-UPDATE-DELETE 三场景"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三方法对应 多读/单读/写——语义化的 SQL 场景。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 prepare + bind 防 SQL 注入",
    prompt: "为什么必须用 prepare(query).bind(...params) 而不是字符串拼接？",
    options: [
      sc("A", "prepare/bind 是参数化查询——SQL 模板与值分离，引擎把值视为数据不是代码；拼接 'SELECT * FROM x WHERE id=' + userInput 经典 SQL 注入漏洞；这是 D1 内置防护机制"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "prepare/bind = 参数化查询防注入——不是性能而是安全。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 getAuthDb (Kysely) 双层",
    prompt: "项目同时有 db.prepare 与 getAuthDb (Kysely)——双层并存动机？",
    options: [
      sc("A", "db.prepare 偏底层 SQL 字符串（messages/rate_limits 自定义表）；Kysely 是类型安全 query builder（better-auth 内部用 + 复杂 join 用）；底层 raw + 高级 builder 各司其职"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "raw SQL + Kysely = 简单场景效率 + 复杂场景类型安全。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/auth.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q7 authDbCache 模式",
    prompt: "let authDbCache: Kysely | null + authDbBinding 检查——为什么要缓存？",
    options: [
      sc("A", "Kysely 实例创建有开销（dialect 初始化）+ 多次 loader/action 共享；但 binding 跨请求可能变（getPlatformProxy vs prod 切换）→ binding 变了重建；既复用又保正确"),
      sc("B", "性能 only"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "缓存 + binding 不变 = 复用；binding 变 = 重建——两全。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 AuthDatabase 类型",
    prompt: "type AuthDatabase = { user: {...}, session: {...}, account: {...}, ... }——这是？",
    options: [
      sc("A", "Kysely 的数据库 schema 类型——告诉编译器表名 + 列名 + 类型；selectFrom('user').select(['id','email']) 全程类型安全；表/列改了 TS 立即报错"),
      sc("B", "运行时校验"),
      sc("C", "随机"),
      sc("D", "ORM"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Kysely<DB> = 编译期 schema——类型安全的 query builder 核心。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 D1Dialect from kysely-d1",
    prompt: "new Kysely({ dialect: new D1Dialect({ database: binding }) })——D1Dialect 作用？",
    options: [
      sc("A", "Kysely 是数据库无关的 query builder——dialect 把它对接到具体引擎；D1Dialect 实现 query 协议（编 SQL + 调 binding.prepare/all）；换 PG 只换 dialect 不动业务"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "ORM"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Kysely + D1Dialect = 适配器模式——业务代码与具体 DB 解耦。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 loader 内 D1 调用模式",
    prompt: "loader 内 const row = await db.prepare('SELECT * FROM messages WHERE id = ?').get(id);——这段代码标准 loader 用法？",
    options: [
      sc("A", "标准——loader 是数据获取函数；prepare 字符串 + .get/.all 是项目协议；await 异步直返；不在 loader 内启 setInterval/订阅 等长生命周期；纯读操作"),
      sc("B", "应在客户端"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader = 服务端数据获取——D1 直查 + await 即可。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 D1 vs Kysely 何时选哪个",
    prompt: "新增「按用户分页查询消息 + 联动 user 表 join」用哪种？",
    options: [
      sc("A", "Kysely——join + where + orderBy + limit + offset 多条件，类型安全 builder 写起来清晰；db.prepare 字符串拼接 + 参数序列容易出错；复杂查询选 Kysely"),
      sc("B", "raw"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "复杂查询 → Kysely；简单 SELECT/INSERT → raw。决策树清晰。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 错误处理",
    prompt: "db.prepare('...').get(...) 失败抛错怎么办？loader 该 try/catch 吗？",
    options: [
      sc("A", "loader 抛错 React Router 自动捕获 → 走 ErrorBoundary；通常不必 try/catch（让框架处理）；除非要返回特定状态码（如 404 → throw new Response(null, {status:404}); 显式控制响应）"),
      sc("B", "必 try/catch"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader 抛错 = 框架自动处理；显式 try/catch 仅在要 craft 响应。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 cleanupExpiredRateLimits",
    prompt: "cleanupExpiredRateLimits 用 db.prepare DELETE WHERE expires_at < ?——为什么这个函数？",
    options: [
      sc("A", "rate_limits 表会累积过期记录；定期清理避免表无限增长（D1 表大查询慢）；可在 cron 触发或限流写入时偶尔触发；运维卫生"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "过期数据清理 = 表大小控制——D1 性能维护必备。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 initializeDatabase 空函数",
    prompt: "export async function initializeDatabase() { return; }——空函数为什么留着？",
    options: [
      sc("A", "注释明示「Database schema is managed via Wrangler D1 migrations.」——schema 由 migrations/ 文件管理（CI 时跑），运行时不需要建表；保留空函数是 API 兼容（旧代码可能调它）"),
      sc("B", "bug"),
      sc("C", "未实现"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "空函数 + 注释 = 历史 API 兼容 + schema 改由 migrations 管理。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "migrations/"],
  }),
  q({
    type: "single_choice", title: "Q15 D1 vs SQLite 区别",
    prompt: "Cloudflare D1 与本地 SQLite 文件的关键差异？",
    options: [
      sc("A", "D1 是 Cloudflare 托管的分布式 SQLite——通过 binding 调（无文件路径）；写有最终一致延迟（毫秒级跨节点同步）；查询走 HTTP；pricing 按 row read/write 计费；本地 SQLite 文件 IO 直接快"),
      sc("B", "完全等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "D1 = 托管 + 分布式；SQLite = 本地文件——架构差异。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 错误：在客户端调用 db",
    prompt: "MessageList.tsx 内 const rows = await db.prepare(...).all();——会怎样？",
    options: [
      sc("A", "构建期 Vite/Remix 检测到 .server 文件被客户端 import → 报错或剥离；运行时若漏检 getDatabaseBinding 在浏览器抛错（无 cloudflare context）；.server 后缀就是物理屏障"),
      sc("B", "正常"),
      sc("C", "性能差"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".server 文件不可被客户端 import——构建/运行时双重防御。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 batch 操作",
    prompt: "若要插入 100 条 messages 同时——选哪种？",
    options: [
      sc("A", "用 D1 batch API: env.DB.batch([prepare(sql).bind(...), ...])——单次 RPC 一起执行，比 100 个 prepare 串行快几十倍；事务性保证；本项目暂未用，复杂场景需要时引入"),
      sc("B", "for 循环 await"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "批量写 → batch；串行 await 是反模式（N 次 RPC 延迟）。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 索引",
    prompt: "messages 表查询用 WHERE user_id = ? 频繁——为什么需要索引？",
    options: [
      sc("A", "无索引时 D1 全表扫描（O(N)）；CREATE INDEX idx_messages_user_id ON messages(user_id) 后 O(log N)；高频查询字段必加索引；migrations/ 里加 INDEX 语句"),
      sc("B", "可选"),
      sc("C", "无意义"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "高频查询字段 → 必索引；migrations 文件里 CREATE INDEX。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "migrations/"],
  }),
  q({
    type: "single_choice", title: "Q19 N+1 查询陷阱",
    prompt: "loader 内 const messages = await getMessages(); for (const m of messages) { m.user = await getUser(m.user_id); }——什么问题？",
    options: [
      sc("A", "N+1 查询——1 次取消息列表 + N 次取每条用户；100 条消息 = 101 次 DB 调用；性能灾难；用 JOIN 单查或 IN (?,?,...) 批量取改成 1+1 模式"),
      sc("B", "正常"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "for + await 取关联数据 = N+1 反模式；JOIN 或批量 IN 修复。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 D1 schema 改动流程",
    prompt: "要给 messages 加 priority INTEGER 列——流程？",
    options: [
      sc("A", "1) migrations/ 加 NNNN_add_priority_to_messages.sql （ALTER TABLE messages ADD COLUMN priority INTEGER）2) wrangler d1 migrations apply 应用 3) 改 AuthDatabase 类型加列 4) 改 query 用新列；schema → 类型 → query 三步"),
      sc("B", "直接改"),
      sc("C", "无 migration"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "改 schema = migration + 类型 + query 三步走——纪律性。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "migrations/"],
  }),
  q({
    type: "single_choice", title: "Q21 db.server.ts 不导出 binding",
    prompt: "db.server.ts 不直接 export D1 binding 让 loader 用——为什么？",
    options: [
      sc("A", "封装层暴露 db.prepare/exec 接口——业务代码不直触 binding；将来换 DB（PG/Postgres）只动这一文件；接口稳定演进容易；遵循 单一访问点 + 抽象屏障 原则"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "封装 binding = 抽象屏障——演进时只动一处。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 db.server.ts 整体哲学",
    prompt: "db.server.ts 的整体哲学？",
    options: [
      sc("A", "1) 封装层（D1PreparedStatementWrapper 包 prepare/bind） 2) 类型规范化（normalizeParam 把 boolean/undefined 转 D1 兼容值） 3) 双层 API（raw db.prepare + Kysely query builder） 4) lazy binding 解析（getDatabaseBinding 调用时取） 5) 缓存（authDbCache 复用 Kysely 实例） 6) AuthDatabase 类型给 Kysely 编译期 schema 7) schema 由 migrations/ 管理（运行时不建表） 8) 物理隔离（.server 后缀阻止客户端 import）；综合：「封装 + 类型规范 + 双 API + lazy + 缓存」五件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "db.server 五原则——D1 数据访问层纪律。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
];
