/**
 * Real questions for site-15-action-write / action-capstone.
 * Anchor: remix/app/routes/api.nemesis.ts —— action 全链路: requireNemesisUser → validateNemesisRequest → checkNemesisRateLimit → guardNemesisMessage → callNemesisModel → SSE emit + audit waitUntil
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/api.nemesis.ts";
const sc = (id: string, text: string) => ({ id, text });

export const actionCapstoneQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 action 前置守门四步",
    prompt: "api.nemesis.ts action 顺序 = 鉴权 → 验证 → ____ → 守卫 → 调模型。",
    options: [],
    blanks: [{ id: "v", placeholder: "限流", acceptedAnswers: ["限流", "rate-limit", "checkRateLimit", "checkNemesisRateLimit"] }],
    correctAnswer: { type: "fill_blank", values: { v: "限流" } },
    explanation: { short: "auth → validation → rate-limit → guard → model = 五步链。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 action 五步流水线",
    prompt: "action 完整链路与每步职责？",
    options: [
      sc("A", "1) requireNemesisUser: 鉴权（无登录抛 401） 2) validateNemesisRequest: 解析 body + 校验字段 3) checkNemesisRateLimit: IP/用户配额 4) guardNemesisMessage: 内容守卫（Gemini 分类） 5) callNemesisModel + SSE emit + waitUntil 审计；五步流水线职责单一"),
      sc("B", "纯写"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "五步流水线 = 鉴权/验证/限流/守卫/业务——职责清晰。" },
    abilityTags: ["bridge.reactRouter.action", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 method 检查",
    prompt: "if (request.method !== 'POST') return json({ error: 'Method not allowed' }, { status: 405, headers: NO_STORE_HEADERS });——为什么显式检查？",
    options: [
      sc("A", "Remix action 默认接所有非 GET 方法（POST/PUT/PATCH/DELETE）；本接口只允 POST 必显式拒绝其他；405 是 HTTP 标准（Method Not Allowed）；防客户端误调"),
      sc("B", "Remix 自动"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix action 多方法接收 → 必显式 method check + 405。" },
    abilityTags: ["bridge.reactRouter.action", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 try/catch Response 抛物",
    prompt: "try { user = await requireNemesisUser(request); } catch (error) { if (error instanceof Response) { return json(...); } throw error; }——这种模式？",
    options: [
      sc("A", "requireNemesisUser 内部 throw new Response(...) 是 Remix 守门标准模式；这里把 Response 转 JSON + NO_STORE 头返回（客户端 JSON 友好）；非 Response 错误（unexpected）继续抛让框架处理"),
      sc("B", "反模式"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Response 抛物 + JSON 包装 = 守门错误转 API 友好响应。" },
    abilityTags: ["ai.review.architecture", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/services/nemesis-auth.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q5 validateNemesisRequest 返回",
    prompt: "if (!validation.ok) { return json(validation.payload, { status: validation.status, headers: JSON_NO_STORE_HEADERS }); }——返回模式？",
    options: [
      sc("A", "validation 返回 discriminated union { ok: true, message, recentMessages } | { ok: false, status, payload }；调用方一行 if 处理失败 + 解构成功——TypeScript 友好的双状态返回；不抛错降低控制流复杂度"),
      sc("B", "应抛错"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "discriminated union 返回 = 不抛错的双状态——TS 友好控制流。" },
    abilityTags: ["ai.review.architecture", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/services/nemesis-guard.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q6 限流响应",
    prompt: "if (!limitResult.allowed) { return json({ error: ... }, { status: 429, headers: NO_STORE_HEADERS }); }——为什么 429？",
    options: [
      sc("A", "HTTP 429 Too Many Requests = 限流标准状态码；客户端可针对该状态码 backoff 重试；项目区分 'minute' 与 daily 给不同文案；NO_STORE 防 CDN 缓 429"),
      sc("B", "404"),
      sc("C", "503"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "429 = 限流；NO_STORE 防错缓——HTTP 标准。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 cloudflare context 类型",
    prompt: "type CloudflareLoadContext = { cloudflare?: { env?, ctx? } } + const cloudflare = (context as CloudflareLoadContext).cloudflare;——为什么这样？",
    options: [
      sc("A", "Remix LoadContext 是 unknown 由项目自定义 shape；项目把它定义为可选嵌套（cloudflare 可能不存在测试 mock 时）；逐层 ?. 取避免任意层 undefined 抛错；显式类型 cast 让 TS 知道结构"),
      sc("B", "无类型"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "context 自定义 shape + 可选层 + cast = 类型安全 + 测试 mock 友好。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 createNemesisSseResponse",
    prompt: "return createNemesisSseResponse(async (emit) => { ... });——这种模式？",
    options: [
      sc("A", "工厂函数封装 SSE Response 创建——内部 ReadableStream + emit 接口；action 只关心「调函数 + 写 emit」；流式响应封装让业务代码看起来像同步逐步 emit，底层细节隐藏"),
      sc("B", "纯 fetch"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "createNemesisSseResponse = SSE 流式响应工厂——业务侧 emit 即可。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/nemesis-sse.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q9 emit('status', ...) 用途",
    prompt: "emit('status', { step: 'guard', state: 'running', label: '正在做安全判断…' });——SSE status 事件作用？",
    options: [
      sc("A", "客户端实时显示「Nemesis 当前在做什么」（守卫中/路由中/调模型中），UX 不再黑盒；step 字段让客户端按 step 渲染不同 UI；进度感强"),
      sc("B", "调试"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "status 事件 = 客户端进度感——AI 长流程必备 UX。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 guard.shouldAudit",
    prompt: "if (!guard.shouldAudit) { return; } 在 recordAudit 内——什么场景？",
    options: [
      sc("A", "守卫决策内置 shouldAudit 标志——某些场景（如规则守卫的「正常对话」直通）不必落审计；只在「有风险/拦截/重要分类」事件审计；减日志噪音 + 节省 D1 写入"),
      sc("B", "总审计"),
      sc("C", "永不审计"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "shouldAudit = 选择性审计——日志噪音 vs 完整性平衡。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 cloudflare?.ctx?.waitUntil",
    prompt: "cloudflare?.ctx?.waitUntil(auditPromise);——这是什么 API？",
    options: [
      sc("A", "Cloudflare Workers ExecutionContext.waitUntil(promise)——告诉 runtime 「这个 promise 完成前别 kill worker」但不阻塞响应返回；用户已收到 SSE 答案，审计写入在后台继续；性能与可观测兼顾"),
      sc("B", "阻塞响应"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "waitUntil = 后台任务保活——响应已返但任务不死。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 modeReply 短路",
    prompt: "if (modeReply) { recordAudit({ assistantMessage: modeReply }); emit('done', ...); return; }——什么时候触发？",
    options: [
      sc("A", "守卫决策 mode 为「BLOCK / ROBOT_REJECT 等」内置回复时——直接返回固定文案不调模型（省 token + 立即响应）；先审计再 emit done 终止流；快速路径优化"),
      sc("B", "永远"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "modeReply 短路 = 守卫已定结果直接回不调模型——快速路径。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 callNemesisModel + onProgress",
    prompt: "onProgress: (event) => { emit('status', event); } 透传给 callNemesisModel——什么作用？",
    options: [
      sc("A", "下层 service 内部进度（路由分类完成 / 模型调用中 / 流式 token 等）通过回调上抛；action 一行 emit 透传给 SSE 客户端；分层而保进度链不断"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "onProgress 回调 = 跨层进度透传——分层但不阻碍流。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 NemesisModelError",
    prompt: "} catch (error) { recordAudit(); if (error instanceof NemesisModelError) { emit('error', { message: error.message }); return; } console.error(...); emit('error', { message: 'Nemesis 暂时无法响应' }); }——分支差异？",
    options: [
      sc("A", "已知错误（NemesisModelError）：内置可读 message 直回客户端；未知错误：console.error + 通用文案（不暴露内部错误细节）；安全 + 用户体验 + 可观测三平衡"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "已知 vs 未知错误分流 = 友好文案 + 内部细节隐藏 + log 完整。" },
    abilityTags: ["ai.review.architecture", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 process.env.NODE_ENV !== 'production'",
    prompt: "if (process.env.NODE_ENV !== 'production') { console.log('[NemesisGuard]', ...); }——为什么仅 dev log？",
    options: [
      sc("A", "守卫决策含敏感信息（用户消息长度 + 分类原因）——prod 滥写 console 1) 性能 2) Cloudflare 日志成本 3) 可能误暴露用户输入；dev 验证逻辑用 + prod 静默；条件 log 是平衡"),
      sc("B", "永远 log"),
      sc("C", "永不 log"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "NODE_ENV 条件 log = dev 验证 + prod 静默——日志卫生。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 错误：审计阻塞响应",
    prompt: "如果改 await recordNemesisGuardEvent(...) 而非 waitUntil(...)——后果？",
    options: [
      sc("A", "用户收 SSE 响应必须等审计写完 D1（一次额外 RPC，10-50ms）→ 累积每请求加延迟；waitUntil 让审计后台跑响应秒回；性能差异在高并发明显"),
      sc("B", "等价"),
      sc("C", "更安全"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "await 审计 = 阻塞响应；waitUntil = 后台并行——性能选 waitUntil。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 错误：审计失败影响主流程",
    prompt: "如果 recordNemesisGuardEvent 抛错没 catch——后果？",
    options: [
      sc("A", "waitUntil 内部 promise reject 可能让 worker run 标记失败但响应已发；项目 .catch 内 console.error 吞错保主流程不影响；非关键路径错误不打断业务"),
      sc("B", "中断响应"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".catch 内 log 吞错 = 副作用任务不影响主流程——边缘错误处理。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 加新前置守门",
    prompt: "新增「IP 黑名单检查」——在哪步加？",
    options: [
      sc("A", "鉴权前（需登录前先封 IP）或鉴权后（黑名单查 user.id 关联）按业务定；前置守门链顺序很重要：失败短路省后续工作；位置反映优先级"),
      sc("B", "在调模型后"),
      sc("C", "在审计后"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "守门链顺序 = 优先级 + 短路省工作；前面拦截更早。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 加新 SSE 事件",
    prompt: "需在客户端显示「模型 token 实时」——加什么？",
    options: [
      sc("A", "callNemesisModel 内 streaming 已存在则在 onProgress 多发 event:'token' 类型事件；客户端 nemesis-sse.client 加事件 case 处理增量 token；前后端协议同步加新事件类型"),
      sc("B", "无需改"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "新 SSE 事件 = 后端 emit + 客户端 case 双面同步。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 action 内联 vs service 抽离",
    prompt: "为什么 guard / model 等都抽到 services 而 action 只是编排？",
    options: [
      sc("A", "1) 业务逻辑可独立测试 2) action 只 36-180 行才看清楚整链路 3) service 可被其他路由复用（如 admin 测试守卫接口） 4) 隔离 Remix 框架细节让 service 纯逻辑；分层 + 单一职责"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "service 抽离 = 测试 + 复用 + 框架解耦——分层基础。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 action vs API route",
    prompt: "Remix 的 action 与传统 Express POST 路由差异？",
    options: [
      sc("A", "Remix action 自动与 form / fetcher 集成（fetcher.submit → action → revalidate loader），是 RR 数据流的一部分；Express POST 是裸 handler 客户端要自己管 fetch + 状态；action = 集成模式"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix action = 数据流一等公民；Express POST = 裸 handler。" },
    abilityTags: ["bridge.reactRouter.action", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 action capstone 哲学",
    prompt: "api.nemesis.ts action 整体哲学？",
    options: [
      sc("A", "1) 五步流水线（鉴权/验证/限流/守卫/业务）每步职责单一 2) 失败短路 + 错误响应 NO_STORE 3) Response 抛物 + JSON 包装的双层错误协议 4) discriminated union 返回不抛错降低控制流复杂 5) waitUntil 后台审计不阻塞响应 6) NemesisModelError 已知错误友好文案 + 未知错误隐藏内部 7) NODE_ENV 条件 log 8) SSE emit + onProgress 透传分层进度 9) service 抽离 + action 编排 10) HTTP 状态码精确（401/403/405/429）；综合：「五步流水线 + 错误协议 + 异步审计 + SSE 流式 + 分层」五件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "action 10 原则——Remix action 写链顶层纪律。" },
    abilityTags: ["bridge.reactRouter.action", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
];
