/**
 * Real questions for site-15-action-write / cache-invalidate.
 * Anchor: remix/app/lib/cache-headers.server.ts —— action 后用 NO_STORE 让响应不缓 + Remix 自动重 fetch loader 实现 mutation 后客户端数据刷新；区分 HTTP 缓存 vs 客户端 loader 缓存
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/lib/cache-headers.server.ts";
const sc = (id: string, text: string) => ({ id, text });

export const cacheInvalidateQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 action 响应",
    prompt: "action 写后返回时用 ____ _NO_STORE_HEADERS——防 CDN 缓存写响应。",
    options: [],
    blanks: [{ id: "v", placeholder: "前缀", acceptedAnswers: ["JSON"] }],
    correctAnswer: { type: "fill_blank", values: { v: "JSON" } },
    explanation: { short: "JSON_NO_STORE_HEADERS = NO_STORE + Content-Type:application/json。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/routes/api.nemesis.ts"],
  }),
  q({
    type: "single_choice", title: "Q2 写后缓存失效核心矛盾",
    prompt: "POST 后 GET 同 URL 返旧数据——发生了什么？",
    options: [
      sc("A", "GET 响应被 CDN/浏览器缓存（max-age 未过）→ POST 写完数据 → 用户刷新立即 GET 命中旧缓存看不到新数据；写后必须让相关 GET 缓存失效或不缓存写响应"),
      sc("B", "正常"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "写后旧 GET 命中 = 缓存失效核心矛盾。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 Remix loader 自动重 fetch",
    prompt: "Remix action 完成后——loader 怎样？",
    options: [
      sc("A", "Remix 自动重 fetch 当前路由 + 父级 loader（revalidate 机制）；client-side 数据立即刷新；不必手动 invalidate；这是 Remix data flow 内置流程"),
      sc("B", "需手动 fetcher.load"),
      sc("C", "页面刷新"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix action 后自动 revalidate loader——内置流程。" },
    abilityTags: ["bridge.reactRouter.action", "bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 三层缓存",
    prompt: "Web 应用三层缓存？",
    options: [
      sc("A", "1) 浏览器缓存（按 Cache-Control 缓本地） 2) CDN/反向代理缓存（按头分桶共享缓存） 3) 客户端 SPA 数据缓存（Remix loader / RTK / Apollo 等内存缓存）；写后三层都要考虑失效"),
      sc("B", "只浏览器"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三层缓存 = 浏览器 + CDN + 客户端 SPA——写后都要考虑。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 action 响应必 NO_STORE",
    prompt: "为什么 api.nemesis.ts action 错误响应都用 NO_STORE_HEADERS？",
    options: [
      sc("A", "1) 写响应是 POST 通常不缓但中间代理可能错误缓存 2) 错误响应（401/429）是临时状态——不能让 CDN 缓 401 给已登录用户 3) Set-Cookie 响应必 NO_STORE 防共享缓存中的 cookie 漏给别人；安全 + 正确性"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "action 响应 NO_STORE = 写响应安全 + 临时状态防错缓。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/routes/api.nemesis.ts"],
  }),
  q({
    type: "single_choice", title: "Q6 CDN purge",
    prompt: "如果有 CDN 缓存过期 GET 列表——怎么主动 invalidate？",
    options: [
      sc("A", "1) Cloudflare API 调 purge（按 URL 或 tag） 2) 设短 max-age（自然过期） 3) cache-tag 头标记资源后批量 purge by tag 4) URL 加版本号 ?v=2 强制新 URL；CDN 主动失效有 4 种方式"),
      sc("B", "无法主动"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "CDN 主动 purge: API + cache-tag + 版本号 + 短 max-age 四种。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 stale-while-revalidate 妙用",
    prompt: "GET 列表设 'public, max-age=10, stale-while-revalidate=600'——写后？",
    options: [
      sc("A", "10 秒新鲜窗口 + 后台 600 秒慢失效；用户写后最多 10 秒看到新数据；权衡：CDN 命中率高 + 数据延迟可接受场景；非强一致路径常用"),
      sc("B", "永不失效"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "短 max-age + 长 SWR = CDN 命中 + 写后秒级新鲜——非强一致路径。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 useFetcher submit 触发",
    prompt: "useFetcher().submit(formData, { method:'POST' })——之后 loader 怎样？",
    options: [
      sc("A", "fetcher 完成后 Remix 自动 revalidate 所有活跃 loader → useLoaderData 自动收新数据；客户端缓存立即失效；不必手动 fetcher.load"),
      sc("B", "页面刷新"),
      sc("C", "需手动"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useFetcher.submit → 自动 revalidate loader——零手动。" },
    abilityTags: ["bridge.reactRouter.action", "bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 跳过 revalidate",
    prompt: "若 action 后不希望某个无关 loader 重 fetch——怎么做？",
    options: [
      sc("A", "loader 导出 shouldRevalidate 函数 + 返 false（按条件控制）；如「只在 form action 路径相关时重 fetch」「params 不变就跳过」；细粒度优化"),
      sc("B", "无法控制"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "shouldRevalidate 钩子 = 跳过特定 loader 重 fetch——细粒度。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 action 跨路由失效",
    prompt: "在 /chat 调 fetcher.submit 写到 api.nemesis——/messages 路由 loader 也会重 fetch？",
    options: [
      sc("A", "默认所有当前活跃路由 loader 都重 fetch（不论是否相关）；想限制需 shouldRevalidate；广泛失效保证一致但有性能代价"),
      sc("B", "不会"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "默认全活跃 loader 都 revalidate——一致优先。" },
    abilityTags: ["bridge.reactRouter.action", "bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 KV 缓存 invalidate",
    prompt: "若 GET 走 KV 公共缓存（参考 Code Coach 的 LEARN_CACHE）——写后？",
    options: [
      sc("A", "1) action 写完调 deleteCacheKey(单 key) 立即失效 2) 或者 LEARN_CACHE_VERSION 版本号 +1 全局失效 3) 写后顺手 set 新值（避免重读 DB）；策略按粒度选"),
      sc("B", "自动"),
      sc("C", "无法"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "KV 缓存写后必显式失效——deleteKey + 版本号 + 写新值。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 错误：写响应用 max-age",
    prompt: "如果 action 错误响应误用 'public, max-age=600'——后果？",
    options: [
      sc("A", "CDN 可能缓存这个错误响应 → 同 URL 后续请求一直返这个错误（即使后端已修好）；POST 通常不缓但 GET 错配会发生；错误响应必 NO_STORE 防错被永久化"),
      sc("B", "无影响"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "错误响应缓存 = 错误永久化——NO_STORE 必备。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 调试：action 后旧数据",
    prompt: "用户写后还看到旧数据——排查路径？",
    options: [
      sc("A", "1) DevTools Network 看 fetcher 是否触发 → 看 loader 重 fetch 请求 → 看响应数据 2) 看响应 Cache-Control 是否被 CDN 命中（cf-cache-status:HIT） 3) 看 KV 是否被 invalidate 4) 看 shouldRevalidate 是否返 false 跳过；逐层排查"),
      sc("B", "刷新页面"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "action 后旧数据 = 三层缓存逐层排查——网络 + CDN + KV + shouldRevalidate。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 错误：手动 setState 而非 revalidate",
    prompt: "在 fetcher.submit 后手动 setMessages([...newMsg]) 不依赖 revalidate——什么问题？",
    options: [
      sc("A", "手动 setState 是 optimistic 模式可叠加到 revalidate 上；但若不调 revalidate（替换数据源）—— 多标签同步会失效（其他标签 loader 不刷新看不到新消息）；让 revalidate 走"),
      sc("B", "正确"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "手动 setState 仅是 optimistic 增强；不能替代 revalidate。" },
    abilityTags: ["bridge.reactRouter.action", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 optimistic + revalidate",
    prompt: "理想 UX 流程？",
    options: [
      sc("A", "1) 用户点提交 2) 立即 setOptimistic(newMsg) UI 假装成功 3) fetcher.submit 实际写 4) revalidate 完成后 useLoaderData 收真实数据替换 optimistic；UX 即时 + 数据最终一致"),
      sc("B", "等 revalidate 才更新 UI"),
      sc("C", "永远 optimistic"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "optimistic + revalidate = 即时 UI + 最终一致——理想模式。" },
    abilityTags: ["bridge.reactRouter.action", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 缓存 vs DB 一致性",
    prompt: "缓存层数据和 DB 不一致——根因可能？",
    options: [
      sc("A", "1) 写 DB 但忘 invalidate 缓存 2) 缓存 invalidate 后但用户立即 GET 命中并发 set 写回旧值（race） 3) CDN 边缘节点未及时 purge 4) 客户端旧 fetcher 还在飞 race；缓存一致问题多原因"),
      sc("B", "DB bug"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "缓存与 DB 不一致 = 多种 race + 漏失效——分布式难题。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 写穿 vs 写绕",
    prompt: "缓存 + DB 写策略——常见三种？",
    options: [
      sc("A", "1) write-through: 同步写 DB + 写 cache 2) write-around: 只写 DB 让 cache 自然过期/读时再填 3) write-back: 先写 cache 异步刷 DB；项目按场景选；NemesisGuard 类用 write-through 立即可见"),
      sc("B", "唯一一种"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "write-through/around/back = 缓存写策略三经典。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 ETag 协助",
    prompt: "ETag 在写后失效中怎么帮忙？",
    options: [
      sc("A", "GET 响应带 ETag，浏览器/CDN 缓后下次发 If-None-Match：服务端对比若变了返 200+新内容若不变返 304；与 max-age 配合：max-age 过期后用 ETag 条件请求节省传输"),
      sc("B", "无关"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ETag = 条件请求节省传输——max-age 过期后的优化。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 一致性级别",
    prompt: "数据一致性级别从严到松？",
    options: [
      sc("A", "1) 强一致：每次读看到最新写（DB 直查无缓存） 2) 读写一致：读到自己写的（带 user 头跳过缓存） 3) 最终一致：缓存延迟一段后一致（max-age） 4) 弱一致：可能任意延迟；按业务选"),
      sc("B", "无差异"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "强 → 读写 → 最终 → 弱 = 一致性谱系。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 加新 mutation 路由",
    prompt: "加 PATCH /api/messages/:id 编辑消息——缓存层流程？",
    options: [
      sc("A", "1) action 内 update DB 2) deleteCacheKey('messages:list') 失效列表 3) deleteCacheKey('messages:'+id) 失效详情 4) 返 NO_STORE 响应 5) 客户端 fetcher 完成后自动 revalidate /messages loader；KV + HTTP 三层都处理"),
      sc("B", "只 update DB"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "新 mutation = DB + KV invalidate + NO_STORE + revalidate 四步。" },
    abilityTags: ["bridge.reactRouter.action", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 LEARN_CACHE_VERSION 模式",
    prompt: "Code Coach 项目用 LEARN_CACHE_VERSION = 'v10' 拼接 key——为什么？",
    options: [
      sc("A", "全局版本号——shape 改了 +1 一次性废所有相关 key（不需 wildcard delete KV）；旧 key 自然过期；shape 不破坏的小改可重用版本；版本化失效经典模式"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "版本号前缀 = 全局失效不依赖 wildcard——KV 友好。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 cache-invalidate 整体哲学",
    prompt: "写后缓存失效整体哲学？",
    options: [
      sc("A", "1) 写响应必 NO_STORE 防错缓 2) Remix 自动 revalidate 活跃 loader 3) 客户端缓存（loader）零手动 4) KV 缓存写后显式 invalidate（deleteKey 或版本号 +1） 5) CDN 缓存按 max-age + SWR 自然失效或 purge API 6) 一致性等级按业务选 7) optimistic + revalidate 兼顾 UX + 一致 8) shouldRevalidate 细粒度跳过；综合：「三层缓存 + 自动失效 + 写响应 NO_STORE + 按业务选一致性」四件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "缓存失效 8 原则——写后数据一致纪律。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
];
