/**
 * Real questions for site-15-action-write / set-cookie.
 * Anchor: remix/app/utils/theme.server.ts —— setTheme 用 createCookie + serialize 生成 Set-Cookie 字符串；action 内 headers.append('Set-Cookie', ...) 写入响应
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/utils/theme.server.ts";
const sc = (id: string, text: string) => ({ id, text });

export const setCookieQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 setTheme 返回",
    prompt: "setTheme 内 return themeCookie.____ (theme);——Cookie API 把值序列化成 Set-Cookie 字符串。",
    options: [],
    blanks: [{ id: "v", placeholder: "方法名", acceptedAnswers: ["serialize"] }],
    correctAnswer: { type: "fill_blank", values: { v: "serialize" } },
    explanation: { short: "serialize 把值 + cookie 选项编码成 'theme=dark; Max-Age=...; SameSite=Lax' 字符串。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 Set-Cookie 头",
    prompt: "action 内 const setCookie = await setTheme('dark', request); return new Response(null, { headers: { 'Set-Cookie': setCookie } });——浏览器收到怎么处理？",
    options: [
      sc("A", "浏览器解析 Set-Cookie 头：写入对应域名 cookie 存储，按 Max-Age/SameSite/Secure 等约束生效；下次请求自动附带；服务端写 cookie 的标准协议"),
      sc("B", "JSON"),
      sc("C", "丢弃"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Set-Cookie 头 = 服务端写 cookie 的协议；下次请求浏览器自动附带。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q3 createCookie 抽象",
    prompt: "为什么 Remix createCookie 而不直接拼字符串 'theme=dark; Path=/; Max-Age=...'？",
    options: [
      sc("A", "createCookie 1) 类型安全（选项编辑器补全） 2) 自动转义值（特殊字符 URL 编码） 3) 序列化/解析对称（parse + serialize）；4) 配合签名/加密（secrets 选项）；手拼字符串易错 + 不安全"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "createCookie = 类型安全 + 转义 + 对称序列化——防手拼陷阱。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 httpOnly:false",
    prompt: "theme cookie 设 httpOnly: false 而不像 session cookie 设 true——为什么？",
    options: [
      sc("A", "FOUC 防闪需要：HTML 顶部 inline 脚本要读 document.cookie 取主题应用 className；httpOnly:true 时 JS 拿不到该 cookie；session 因不要 JS 访问设 true 防 XSS 偷；按用途分级"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "theme 要 JS 读防 FOUC → httpOnly:false；session 防 XSS → httpOnly:true。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 sameSite:lax",
    prompt: "sameSite: 'lax'——三个值的差异？",
    options: [
      sc("A", "strict: 仅同源请求带 cookie（连点链接也不带）；lax: 同源 + 顶层导航（点链接带，跨站 form POST 不带）；none: 全部带（必配 secure）；lax 是平衡防 CSRF + 体验良好的默认"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "strict/lax/none 防 CSRF 强度递减——lax 是默认平衡点。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 secure 动态",
    prompt: "secure: request ? new URL(request.url).protocol === 'https:' : false——为什么动态？",
    options: [
      sc("A", "secure:true 时 cookie 只在 HTTPS 传——dev 模式 http://localhost 写 cookie 但浏览器不发回（cookie 'lost'）；动态判断让 dev http 时 secure:false，prod https 时 true；同代码两环境兼容"),
      sc("B", "总 true"),
      sc("C", "总 false"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "secure 动态 = dev http + prod https 同代码兼容。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 Max-Age vs Expires",
    prompt: "maxAge: 31_536_000——为什么用 Max-Age 而不 Expires？",
    options: [
      sc("A", "Max-Age 是相对秒数（立即从现在算）；Expires 是绝对日期（如 'Wed, 01 Jan 2030 ...'）易因时钟差错；现代浏览器优先 Max-Age；31536000 = 365 天"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Max-Age 相对秒数 = 时钟无关——优于绝对 Expires。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 Path 默认",
    prompt: "未显式设 path——cookie 会绑哪个路径？",
    options: [
      sc("A", "Remix createCookie 默认 path: '/'——全站可见；若要限子路径可显式设 path: '/admin'；但全站设是常态"),
      sc("B", "当前路径"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix 默认 path:'/'——全站可见；显式收窄需特殊场景。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 Domain 默认",
    prompt: "未设 domain——cookie 绑哪个域？",
    options: [
      sc("A", "默认绑当前请求域名（精确匹配）；显式设 domain: 'example.com' 后子域共享（如 a.example.com 和 b.example.com 共用）；开放共享要小心 XSS 跨子域"),
      sc("B", "全网"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "默认绑当前域 = 最严；显式设 domain 才能子域共享。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 多 cookie 同时写",
    prompt: "action 同时写 theme cookie + session cookie——怎样？",
    options: [
      sc("A", "Set-Cookie 头可重复（headers.append('Set-Cookie', a); headers.append('Set-Cookie', b)）—— 浏览器分别处理两个 cookie；不能用 'Set-Cookie': 'a; b' 单字符串拼接（会被解析成单 cookie 错误）"),
      sc("B", "只能一个"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "多 cookie = 多 append；单字符串拼会被解析错。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 redirect + Set-Cookie",
    prompt: "action 内 return redirect('/', { headers: { 'Set-Cookie': cookie } });——这种模式？",
    options: [
      sc("A", "PRG 模式（Post-Redirect-Get）—— action 写 cookie 后 redirect 让浏览器重导航；新 GET 请求带新 cookie；防表单重复提交 + 状态可见性；Remix 推荐路径"),
      sc("B", "反模式"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "redirect + Set-Cookie = PRG 模式——Remix 写状态推荐。" },
    abilityTags: ["bridge.reactRouter.action", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q12 删 cookie",
    prompt: "怎么让浏览器删除 cookie？",
    options: [
      sc("A", "Set-Cookie 同名 + maxAge:0（或过去日期 expires）；浏览器收到立即清除；createCookie('theme', { maxAge: 0 }).serialize('') 实现登出/重置"),
      sc("B", "无法删"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "删 cookie = 同名 + maxAge:0——浏览器立即清。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 cookie 大小限制",
    prompt: "Cookie 大小限制？",
    options: [
      sc("A", "每个 cookie ≤ 4KB（约 4096 字节）；单域 cookie 总数 ≤ 50 个；超限会被丢弃；大数据应放服务端 session 用 cookie 只存 session id；不要把 JSON 整体塞 cookie"),
      sc("B", "无限"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "cookie 4KB 限制——大数据走服务端 session。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 加密 cookie",
    prompt: "createCookie('id', { secrets: ['s1', 's2'] })——secrets 作用？",
    options: [
      sc("A", "签名 cookie——值用 HMAC-SHA256 + secret 签 → 浏览器篡改后 parse 返 null；多 secret 支持密钥轮转（s1 验旧 s2 验新）；session id 类敏感值常用"),
      sc("B", "加密"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "secrets = HMAC 签名防篡改；多 secret 支持轮转——非加密。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 错误：忘了写 Set-Cookie 头",
    prompt: "action 调 setTheme 但忘了把返回值放进响应 headers——结果？",
    options: [
      sc("A", "cookie 没写——浏览器不知道 + 下次请求仍带旧值；用户切换主题表面上 Did Nothing；调试常见疏忽：serialize 后必须 attach 到响应"),
      sc("B", "自动写"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "serialize 不等于 attach——必须显式放入 headers。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 错误：dev http 设 secure:true",
    prompt: "若硬编码 secure: true 在 dev 模式 http://localhost——结果？",
    options: [
      sc("A", "Set-Cookie 头浏览器忽略（http 不发 secure cookie）→ cookie 没写 → 切主题不生效；dev 调试很久才发现是协议不一致；动态 secure 解决这个陷阱"),
      sc("B", "正常"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "secure:true + http = cookie 丢——动态 secure 必要。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 错误：sameSite:none 缺 secure",
    prompt: "如果设 sameSite: 'none' 但忘加 secure: true——结果？",
    options: [
      sc("A", "现代浏览器拒绝该 cookie——'SameSite=None must be Secure' 错误（Chrome 80+）→ cookie 完全不写；none 必须 secure 防中间人攻击 + 跨站隐私"),
      sc("B", "正常"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "sameSite:none 必配 secure——浏览器硬性规则。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 cookie 命名规范",
    prompt: "cookie 名 'theme'——为什么用裸名而不带前缀？",
    options: [
      sc("A", "项目特定，简单清晰；大型项目可加 __Secure- 前缀（强制 secure 前缀，浏览器额外校验）或 __Host- 前缀（强制 secure + path:/ + 无 domain）；本项目主题 cookie 简单需求用裸名"),
      sc("B", "必加前缀"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "裸名简单；__Secure-/__Host- 前缀提供额外浏览器约束——按需选。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 不同 cookie 不同策略",
    prompt: "项目 theme + better-auth session 两类 cookie 配置应该差异？",
    options: [
      sc("A", "theme: httpOnly:false（JS 要读防 FOUC） + lax + 1 年；session: httpOnly:true（防 XSS） + lax + 7 天 + 签名/加密；按敏感度分两套配置"),
      sc("B", "完全相同"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "敏感度分级 = 不同 cookie 不同配置——纪律。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/auth.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q20 加新 cookie 流程",
    prompt: "新增 'lang' cookie 存语言偏好——流程？",
    options: [
      sc("A", "1) lang.server.ts: createCookie('lang', { httpOnly:false, sameSite:'lax', maxAge:31536000, secure:动态 }) 2) getLang/setLang 函数 3) action 调 setLang + redirect 4) loader 读 + 注入 useLoaderData；模仿 theme.server 模式即可"),
      sc("B", "全局变量"),
      sc("C", "localStorage"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "新 cookie = 模仿 theme.server 模板五步走。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 cookie vs localStorage",
    prompt: "存语言偏好——选 cookie 还是 localStorage？",
    options: [
      sc("A", "cookie：服务端 SSR 时已知 lang 可直接渲染对应语言（无 FOUC）；localStorage 仅客户端能读 SSR 时拿不到必显示默认 → 闪到正确语言；要 SSR 一致选 cookie"),
      sc("B", "localStorage 总是好"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SSR 要无闪 = cookie；纯客户端状态 = localStorage——决策依据。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 set-cookie 整体哲学",
    prompt: "Set-Cookie 流程整体哲学？",
    options: [
      sc("A", "1) 服务端 createCookie 定义 schema（选项一次定义） 2) action 调 serialize 拿字符串 3) 显式 attach 到响应 headers（不自动） 4) httpOnly 按是否需 JS 读分级 5) sameSite:lax 防 CSRF 默认 6) secure 动态适配 dev/prod 7) Max-Age 优于 Expires 8) PRG 模式 redirect + Set-Cookie 9) 多 cookie append 不拼字符串 10) 删 cookie = 同名 + maxAge:0；综合：「服务端写状态的标准协议 + 安全分级 + 跨环境兼容」三件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Set-Cookie 10 原则——服务端写状态纪律。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
];
