/**
 * Real questions for site-06-file-routing / auth-splat.
 * Anchor: remix/app/routes/api.auth.$.ts —— 219 行：splat 捕获 /api/auth/* 全部请求；GET loader + POST action 都转 Better Auth handler；含 Microsoft OAuth callback relay + sanitize 调试日志
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/api.auth.$.ts";
const sc = (id: string, text: string) => ({ id, text });

export const authSplatQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 splat 文件名约定",
    prompt: "api.auth.____.ts —— 末段符号让此路由捕获 /api/auth/* 任意子路径。",
    options: [],
    blanks: [{ id: "v", placeholder: "符号", acceptedAnswers: ["$"] }],
    correctAnswer: { type: "fill_blank", values: { v: "$" } },
    explanation: { short: "$ 单字符在末段 = splat（catch-all）；匹配 /api/auth/ 之下任意深度。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 splat vs $param",
    prompt: "$.ts（splat）vs $platform.tsx（动态参数）的区别？",
    options: [
      sc("A", "$.ts 末段单 $ = catch-all 匹配剩余任意深度；$platform.tsx 是单段动态参数（仅匹配一段）；splat 用于「我不知道有多少层」如 OAuth 多种回调子路径"),
      sc("B", "完全等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "$ 单字符 = splat 多段；$name = 单段参数——两种深度。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 为什么 auth 路由用 splat",
    prompt: "Better Auth 库需要捕获 /api/auth/sign-in、/api/auth/sign-out、/api/auth/callback/google、/api/auth/callback/microsoft、/api/auth/session 等数十种 endpoint——所以？",
    options: [
      sc("A", "对——Better Auth 内部维护这些 endpoint 路由表；用 splat 把所有 /api/auth/* 都接给 Better Auth handler；不需要为每个 endpoint 建文件"),
      sc("B", "建 N 个文件"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "splat = 「转发所有」——库内部决定具体逻辑；外层只是路由汇聚点。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 同时 export loader + action",
    prompt: "export async function loader(...) + export async function action(...) 都调 handleAuthRequest——为什么两者都要？",
    options: [
      sc("A", "loader 处理 GET（如 /api/auth/callback/google?code=...）；action 处理 POST（如 /api/auth/sign-in/social）；两个 HTTP 方法都用，所以两个 export 都要导出"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader=GET, action=POST/其他动词——OAuth 流两者都需要。" },
    abilityTags: ["bridge.reactRouter.loader", "bridge.reactRouter.action", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 handleAuthRequest 同款逻辑",
    prompt: "loader 和 action 都调 handleAuthRequest(request)——为什么共用？",
    options: [
      sc("A", "Better Auth handler 自己分发 GET/POST；不必在 Remix 层区分；handleAuthRequest 是「桥接」适配 Remix 路由 → Better Auth handler；DRY"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "桥接函数 = 一处写两处用——loader/action 都调。" },
    abilityTags: ["bridge.reactRouter.loader", "bridge.reactRouter.action", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 Microsoft callback relay 拦截",
    prompt: "loader 内 const relay = getMicrosoftCallbackRelay(request); if (relay) throw redirect(relay);——意图？",
    options: [
      sc("A", "Microsoft OAuth 注册的 redirect_uri 必须固定，但项目可能有多域名（如 www.gregor.com vs gregor.com）；某域收到回调时若不是注册的主域，relay 转给主域处理；多域名 OAuth 兼容"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Microsoft OAuth 严格 redirect_uri → 多域名场景下用 relay 转发。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 throw redirect",
    prompt: "if (relay) throw redirect(relay);——为什么 throw 而不 return？",
    options: [
      sc("A", "Remix 约定：throw 一个 Response（包括 redirect 返的 Response）让框架短路返响应；省去后续代码继续跑；与 return redirect 效果等价但更明确「拦截」语义"),
      sc("B", "随机"),
      sc("C", "永远 return"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "throw Response = Remix 拦截短路；语义比 return 更明显。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 try/catch 捕日志再 throw",
    prompt: "handleAuthRequest 内 try { ... } catch (error) { console.error(...); throw error; }——为什么 catch 后再 throw？",
    options: [
      sc("A", "捕获只为日志（生产环境定位 OAuth 失败原因）；不能 swallow（用户必须看到错误页）；throw error 让 ErrorBoundary 接管；可观测 + 行为不变"),
      sc("B", "应该 swallow"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "catch-log-throw = 加日志不改行为——可观测的标准模式。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 sanitizeSearchParams",
    prompt: "console.error 内 search: sanitizeSearchParams(url) ——sanitize 函数把 code/state/id_token/access_token/refresh_token 替换为 [redacted]；意图？",
    options: [
      sc("A", "OAuth 的 code/state/token 是敏感凭据——日志里若直接打印会被日志收集系统持久化、泄露风险；sanitize 让日志可观测但不泄密；安全 + 调试双兼顾"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "敏感凭据从日志脱敏 = 安全工程基本纪律。" },
    abilityTags: ["ai.review.architecture", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 getAuthDebugContext",
    prompt: "context.callback = { provider, hasCode, hasState, hasStateCookie }——为什么只记 has* 而不记 token 本身？",
    options: [
      sc("A", "OAuth 调试关键是「这些字段是否齐全」；具体值可能含敏感信息（state token 等）；hasCode/hasState 只表存在性 + 不泄密；定位故障够用"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "调试日志记「存在性」而非具体值——典型 OAuth 调试纪律。" },
    abilityTags: ["ai.review.architecture", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 sanitizeOAuthURL clientIdSuffix",
    prompt: "sanitizeOAuthURL 内 clientIdSuffix: url.searchParams.get('client_id')?.slice(-12)——只取后 12 位？",
    options: [
      sc("A", "client_id 是公开信息但完整泄露在日志仍不优；取后缀 12 位足够人眼区分但不暴露完整值；调试可读 + 安全冗余"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "client_id 后缀 = 调试时区分 + 不全暴露；安全冗余设计。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 getOAuthCallbackProvider 正则",
    prompt: "function getOAuthCallbackProvider(pathname) { const match = pathname.match(/^\\/api\\/auth\\/callback\\/([^/]+)$/); return match?.[1] ?? null; }——做什么？",
    options: [
      sc("A", "从 /api/auth/callback/google 提取 'google' / /api/auth/callback/microsoft 提取 'microsoft'——动态识别 callback provider 名；用于按 provider 分类调试日志"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "正则提 provider 名 = 多 provider OAuth 的统一处理。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 hasOAuthStateCookie 检测",
    prompt: "function hasOAuthStateCookie(request) { ... return cookie.split(';').some(part => name.toLowerCase().includes('state')); }——意图？",
    options: [
      sc("A", "OAuth state 防 CSRF——发起 sign-in 时设 state cookie，回调时校验；检测「callback 时是否有 state cookie」让调试时知道是否丢失（user 删 cookie 或浏览器隐私模式等）"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "OAuth state cookie 检测 = 调试 sign-in 失败的关键线索。" },
    abilityTags: ["backend.session.cookie", "ai.review.architecture", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 getSetCookieNames",
    prompt: "logAuthDebugResult 内 setCookieNames: getSetCookieNames(response.headers)——只记 cookie 名？",
    options: [
      sc("A", "对——OAuth 成功后 Better Auth 会 Set-Cookie 多个（session/auth/...）；记录名字让调试知道哪些 cookie 被设；不记 value（敏感）；可观测 + 安全"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "记 cookie 名 = 调试可见性；不记 value = 安全。" },
    abilityTags: ["backend.session.cookie", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 readSocialSignInBody 用 request.clone()",
    prompt: "async function readSocialSignInBody(request) { try { const body = await request.clone().json() ... } catch { return undefined; } }——为什么 clone？",
    options: [
      sc("A", "request body 是 stream 只能读一次——读了之后 Better Auth handler 又要读会失败；clone() 复制一份让两边各读各的；读流的标准守则"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "request body 是 stream → clone 后才能多次消费。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 getOAuthRedirectDebug",
    prompt: "async function getOAuthRedirectDebug(response) { const location = response.headers.get('location'); if (location) return sanitizeOAuthURL(location); ... try { const body = await response.clone().json() ... } }——为什么 try 两个来源？",
    options: [
      sc("A", "Better Auth 返响应：sign-in 时可能 302 redirect 到 OAuth 提供商（Location 头有）；或 200 + JSON body 含 url/redirect 字段（前端 fetch 自己跳）；两种模式都要支持"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Better Auth 双重返回模式（302 vs 200+json）→ 调试时两边都查。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q17 用户 Google 登录全流",
    prompt: "用户点 Google 登录按钮，完整 OAuth 步骤？",
    options: [
      sc("s1", "1. 前端 fetch POST /api/auth/sign-in/social { provider:'google' }"),
      sc("s2", "2. Worker 路由匹配 api.auth.$.ts → action(request)"),
      sc("s3", "3. handleAuthRequest 调 getAuth(request).handler(request) Better Auth 处理"),
      sc("s4", "4. Better Auth 设 state cookie + 返 200 JSON { url: 'https://accounts.google.com/oauth/authorize?...' }"),
      sc("s5", "5. logAuthDebugResult 记日志 + sanitizeOAuthURL"),
      sc("s6", "6. 前端拿到 url 跳转到 Google"),
      sc("s7", "7. 用户授权后 Google 回调 /api/auth/callback/google?code=xxx&state=yyy"),
      sc("s8", "8. Worker 路由匹配 api.auth.$.ts → loader(request)"),
      sc("s9", "9. loader 调 handleAuthRequest → Better Auth 校验 state cookie + 用 code 换 access_token + 取用户信息 + 写 D1 + 设 session cookie"),
      sc("s10", "10. Better Auth 返 302 redirect 到 callbackURL（如 /chat）"),
      sc("s11", "11. logAuthDebugResult 记 setCookieNames + sanitizeOAuthURL"),
      sc("s12", "12. 用户最终落 /chat 已登录态"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8", "s9", "s10", "s11", "s12"] },
    explanation: { short: "OAuth 完整 12 步——sign-in 与 callback 双流穿插。" },
    abilityTags: ["bridge.reactRouter.action", "bridge.reactRouter.loader", "backend.auth.required", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/auth.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q18 加新 OAuth provider",
    prompt: "想加 GitHub OAuth——改 api.auth.$.ts？",
    options: [
      sc("A", "几乎不改——这文件只是桥；改 app/lib/auth.server.ts 内 Better Auth 配置加 github provider；splat 自动处理 /api/auth/callback/github；splat 的好处"),
      sc("B", "新建文件"),
      sc("C", "改 wrangler"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "splat 让加 provider = 改库配置；路由文件无需改。" },
    abilityTags: ["project.modify.fullstack", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/auth.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q19 splat 顺序优先级",
    prompt: "若同时有 api.auth.$.ts + api.auth.session.ts —— 后者优先吗？",
    options: [
      sc("A", "对——具体路径优先 splat；Remix 路由匹配按特异性顺序：先精确再 splat；可用此机制覆写某 endpoint 的处理逻辑"),
      sc("B", "splat 优先"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix 路由匹配按特异性——精确优先 splat，可用于 override。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 文件后缀 .ts 不是 .tsx",
    prompt: "api.auth.$.ts 用 .ts ——为什么不 .tsx？",
    options: [
      sc("A", "纯 resource route——只导出 loader/action 返 Response，无 JSX；.ts 表明意图；vs UI route 带 default 组件用 .tsx"),
      sc("B", "应该 .tsx"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "resource route = .ts；UI route = .tsx——文件后缀暗示意图。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 改造调试日志级别",
    prompt: "线上 OAuth 失败率突增想加 metric——落点？",
    options: [
      sc("A", "logAuthDebugResult 内 catch 块 + status >= 400 时上报 metric（OAuth provider + status code）；现有日志结构已含 sanitize；扩展线性"),
      sc("B", "新加 service"),
      sc("C", "改 root"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "可观测扩展 = 现有日志点加 metric——单点拦截。" },
    abilityTags: ["ai.review.architecture", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 splat 路由整体哲学",
    prompt: "api.auth.$.ts 219 行整体设计哲学？",
    options: [
      sc("A", "1) splat 文件名捕获所有 /api/auth/* —— 不为每 endpoint 建文件 2) loader + action 共调 handleAuthRequest 桥接 Better Auth 3) 多域名 OAuth 用 relay 兼容 4) 完整调试日志：path/status/Set-Cookie names/OAuth redirect debug 5) sanitize 把 code/state/token 全脱敏防泄密 6) hasCode/hasState 等存在性记录足够调试 7) request.clone 多次消费 stream 8) try-catch-log-throw 保留行为只加可观测——综合：「单 splat 桥 + 安全调试 + 框架适配」三件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "splat 8 原则——OAuth 路由桥的工程范式。" },
    abilityTags: ["code.position.handler", "bridge.reactRouter.loader", "bridge.reactRouter.action", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/auth.server.ts"],
  }),
];
