/**
 * Real questions for site-06-file-routing / flat-routes.
 * Anchor: remix/app/routes/gallery.tsx + 整体 routes/ 目录约定 —— 「一个 .tsx 文件 = 一个 URL」的扁平化路由
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/gallery.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const flatRoutesQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 gallery.tsx URL 映射",
    prompt: "app/routes/gallery.tsx 自动映射到 URL 路径 /____。",
    options: [],
    blanks: [{ id: "v", placeholder: "路径", acceptedAnswers: ["gallery"] }],
    correctAnswer: { type: "fill_blank", values: { v: "gallery" } },
    explanation: { short: "扁平路由：文件名 = URL 段；gallery.tsx → /gallery。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 扁平 vs 嵌套",
    prompt: "为什么 gallery 是扁平 (gallery.tsx) 而 game 是嵌套 (game.tsx + game._index.tsx + game.$platform.tsx)？",
    options: [
      sc("A", "gallery 是单页面无子路径——一个 .tsx 文件够；game 有 layout（共享 shell）+ 默认页 + 动态平台 → 拆 3 个文件用文件名 . 表层级；按页面结构选扁平 vs 嵌套"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "单页扁平、多页嵌套——按 URL 树选文件结构。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game.tsx"],
  }),
  q({
    type: "single_choice", title: "Q3 路由文件五个标准导出",
    prompt: "gallery.tsx 顶部 export const links / meta / loader + 默认 export Gallery 组件——为什么这种五件套？",
    options: [
      sc("A", "Remix 路由模块协议：links（注入 <link>）、meta（注入 <meta>）、loader（服务端数据）、headers（响应头）、default（UI）；每个文件按需导出对应的；约定即接口"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix 路由模块协议 = 命名导出即生命周期挂钩。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 routes/ 目录文件清单",
    prompt: "routes/ 内有 _index, anime, api.auth.$, api.claim-token, api.nemesis-feedback, api.nemesis, auth.sign-out, auth, chat, cv, gallery, game.$platform, game._index, game, messages, music, rapid-layers-preview, sitemap[.]xml, updates, xiao 等 .tsx/.ts —— 文件名 → URL 的映射？",
    options: [
      sc("A", ". 分隔 = URL 段；$ = 动态参数；_ 前缀 = pathless（不参与 URL）；[.] = 转义点字面量；扁平命名 + 5 种约定符号 → 完整路由树"),
      sc("B", "随机"),
      sc("C", "嵌套目录"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix v2 扁平路由 5 符号：. $ _ [] —— URL 树扁平化表达。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 sitemap[.]xml.tsx",
    prompt: "sitemap[.]xml.tsx 映射 URL？",
    options: [
      sc("A", "/sitemap.xml —— [.] 转义让 . 作为字面量而非分隔符；否则 sitemap.xml.tsx 会被当作两层路由 sitemap → xml；常见用于 .xml/.json 等含点 URL"),
      sc("B", "/sitemap/xml"),
      sc("C", "/sitemap[.]xml"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "[.] 转义 = 让 . 不被当分隔符——sitemap.xml/manifest.json 等场景必备。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/sitemap[.]xml.tsx"],
  }),
  q({
    type: "single_choice", title: "Q6 api.nemesis-feedback.ts",
    prompt: "api.nemesis-feedback.ts 文件名约定？",
    options: [
      sc("A", "api 第一段 + nemesis-feedback 第二段（连字符在段内合法）→ /api/nemesis-feedback；后缀 .ts 表 resource route（仅 loader/action 无 UI）"),
      sc("B", "/api.nemesis-feedback"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ". 分段 + - 连字符段内合法 → /api/nemesis-feedback；.ts 后缀 resource route。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/api.nemesis-feedback.ts"],
  }),
  q({
    type: "single_choice", title: "Q7 .ts vs .tsx",
    prompt: "为什么 api.* 路由用 .ts 而其他用 .tsx？",
    options: [
      sc("A", ".tsx 含 JSX——UI 路由；.ts 纯 TS——resource route 仅 loader/action 处理 JSON/XML 等响应；明示意图区分两类"),
      sc("B", "随机"),
      sc("C", "TypeScript 限制"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".ts = 资源路由（API）；.tsx = UI 路由——文件名暗示意图。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 资源路由（resource route）特征",
    prompt: "resource route（如 api.nemesis.ts）与 UI route（如 chat.tsx）的差异？",
    options: [
      sc("A", "resource：仅 export loader/action，返 Response（如 json/redirect/Stream）；无 default 组件；UI route：有 default 组件渲 JSX；两者都被 Remix 路由表收录"),
      sc("B", "完全等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "resource route 无 UI 只返 Response；UI route 渲组件——两类文件名通常区分。" },
    abilityTags: ["code.position.handler", "bridge.reactRouter.loader", "bridge.reactRouter.action", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/routes/api.nemesis.ts"],
  }),
  q({
    type: "single_choice", title: "Q9 auth.sign-out.tsx",
    prompt: "auth.sign-out.tsx 映射？",
    options: [
      sc("A", "/auth/sign-out —— . 第一段 auth + 第二段 sign-out（- 段内合法）；Header 退出按钮的 fetcher action 目标就是这个；命名表达层级"),
      sc("B", "/auth.sign-out"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "auth.sign-out.tsx → /auth/sign-out；扁平表层级。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/auth.sign-out.tsx"],
  }),
  q({
    type: "single_choice", title: "Q10 单个文件没 layout 嵌套",
    prompt: "gallery.tsx 是扁平 → 它有父 layout 吗？",
    options: [
      sc("A", "有 root.tsx 的 Layout 作为隐式父——所有路由都套 root；gallery 自己不再叠 layout（无 gallery.tsx + gallery._index.tsx 拆分）；扁平路由的简洁性"),
      sc("B", "完全无父"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "扁平路由仍套 root layout；不再加自定义中层。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q11 加新页 /blog",
    prompt: "想新增 /blog 页——文件名？",
    options: [
      sc("A", "app/routes/blog.tsx —— 单文件直映射；无子路由情况下扁平最简单；导出 default + 可选 loader/meta 即可"),
      sc("B", "blog/index.tsx"),
      sc("C", "_blog.tsx"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "新单页 = 加 .tsx 文件 + URL 段对应名字；零配置。" },
    abilityTags: ["project.modify.fullstack", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/blog.tsx"],
  }),
  q({
    type: "single_choice", title: "Q12 加 /blog/$slug",
    prompt: "若 /blog 也想要详情页 /blog/abc-post——文件结构？",
    options: [
      sc("A", "blog.tsx（layout 含 Outlet）+ blog._index.tsx（默认列表页）+ blog.$slug.tsx（动态详情）；嵌套结构 3 文件；与 game.tsx 模式一致"),
      sc("B", "blog/$slug.tsx"),
      sc("C", "blog-$slug.tsx"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "需要列表+详情 = 嵌套 3 文件；扁平命名表层级。" },
    abilityTags: ["project.modify.fullstack", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game.tsx"],
  }),
  q({
    type: "single_choice", title: "Q13 routes.ts 显式声明",
    prompt: "Code Coach 项目用 app/routes.ts 显式声明所有路由——Remix v2 不一样？",
    options: [
      sc("A", "Remix v2 用 file-based routing（自动扫描 app/routes/）；React Router 7 framework mode 提供两种：file-based（扁平/嵌套）或 routes.ts 显式声明；选哪种是项目偏好"),
      sc("B", "完全一样"),
      sc("C", "随机"),
      sc("D", "TypeScript 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix v2 = file-based；RR7 二选一——本课关注 Remix v2 的扁平。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 文件名重命名",
    prompt: "若把 gallery.tsx 重命名 photos.tsx——影响？",
    options: [
      sc("A", "URL 自动变 /photos；老 /gallery 链接全失效（404）；外链/SEO 受冲击；建议加 /gallery 重定向到 /photos 过渡——文件名 = URL 强耦合"),
      sc("B", "无影响"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "文件名 = URL；改名 = 改 URL；要做 redirect 过渡。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 链接进 gallery",
    prompt: "Header 内 <Link to=\"/gallery\"> 跳转到 gallery.tsx——为什么 to 写绝对路径？",
    options: [
      sc("A", "绝对路径 / 开头不依赖当前 URL——任何页都跳到 /gallery；相对路径会按当前 URL 拼接；导航类 Link 通常用绝对路径明确目标"),
      sc("B", "TypeScript"),
      sc("C", "随机"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "导航 Link 用绝对路径——位置无关；相对路径用于嵌套子路由内部。" },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/ui/Header.tsx"],
  }),
  q({
    type: "branch_trace", title: "Q16 用户访问 /gallery 路由匹配",
    prompt: "用户在 Header 点 /gallery 链接，路由匹配步骤？",
    options: [
      sc("s1", "1. Link 触发 client navigation 到 /gallery"),
      sc("s2", "2. Remix 路由表匹配 routes/gallery.tsx"),
      sc("s3", "3. 调 gallery.tsx 的 loader（若有）"),
      sc("s4", "4. 等 loader 完成 → 数据传给 useLoaderData"),
      sc("s5", "5. 渲染 Outlet 内 root.tsx Layout 套 gallery.tsx 默认组件"),
      sc("s6", "6. 调 gallery 的 meta 函数 → 注入 <meta> 标签"),
      sc("s7", "7. 调 links → 注入 stylesheet 等"),
      sc("s8", "8. 用户看到 /gallery 完整页面"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8"] },
    explanation: { short: "路由匹配 + loader/meta/links 协奏 + Outlet 嵌套——8 步完成切页。" },
    abilityTags: ["code.position.handler", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q17 url 参数处理（搜索）",
    prompt: "若 /gallery?tag=portrait 想读 query——怎么做？",
    options: [
      sc("A", "loader 内 const url = new URL(request.url); const tag = url.searchParams.get('tag');——request 包含完整 URL，URL 实例解析 query；不必加文件后缀路由"),
      sc("B", "新文件"),
      sc("C", "随机"),
      sc("D", "$tag"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "query 参数在 loader 内 URL.searchParams 读——不需要新建路由文件。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 _index 与 _ 前缀其他用法",
    prompt: "除了 _index，还能用 _ 前缀做什么？",
    options: [
      sc("A", "_pathless layout——文件名 _foo.tsx 让该层级不参与 URL 但提供 layout；如 _auth.login.tsx + _auth.signup.tsx 共享 auth 母 layout 但 URL 是 /login /signup（不是 /auth/login）；分组而不影响 URL"),
      sc("B", "无其他"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "_前缀 = pathless（不影响 URL 但提供 layout）；分组工具。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 routes 目录的 _ 与 .",
    prompt: "Remix 扁平路由的 _ 与 . 字符具体作用？",
    options: [
      sc("A", "_ 前缀 = 文件不参与 URL（pathless / 父 layout 默认）；. = URL 段分隔符；两者结合：_app.dashboard._index.tsx 表示 /dashboard 默认页 + _app pathless layout 提供 shell；细粒度组合"),
      sc("B", "完全相同"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "_ 跳过 URL；. 分段；组合表达「URL 不变但 layout 包」。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 file routing vs config-based",
    prompt: "Remix v2 file routing 与 React Router 7 routes.ts 配置——哪种更优？",
    options: [
      sc("A", "各有适用：file routing 上手快、新手友好、URL 与目录直观对应；config-based（routes.ts）显式可见所有路由、支持复杂逻辑（动态生成、类型推导更强）；大型项目偏 config，中小型偏 file"),
      sc("B", "永远 config 更好"),
      sc("C", "永远 file 更好"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "两种风格按项目规模与偏好选——本项目 Remix v2 用 file routing。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 路由命名一致性",
    prompt: "项目内 cv.tsx / gallery.tsx / chat.tsx / anime.tsx / music.tsx 都是单段名——为什么不嵌套？",
    options: [
      sc("A", "这些都是「独立单页」无子路径——单文件就够；如果某天 /music 要加 /music/playlist 子页才需嵌套；按需扩展是最佳实践"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "单页 → 单文件；按需扩展 → 嵌套——避免过度设计。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 扁平路由整体哲学",
    prompt: "Remix v2 扁平路由整体哲学？",
    options: [
      sc("A", "1) 文件名 = URL 强约定 2) . 段分隔 / $ 动态 / _ pathless / [] 转义 5 符号表完整路由树 3) 资源路由 .ts vs UI 路由 .tsx 区分意图 4) 单页扁平 + 多页嵌套按需选 5) routes/ 目录一目了然 6) 改名 = 改 URL 高耦合提醒做 redirect 过渡——综合：约定优于配置 + 文件结构即路由表"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "扁平路由 6 原则——Remix v2 路由约定的总览。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
];
