/**
 * Real questions for site-06-file-routing / index-route.
 * Anchor: remix/app/routes/_index.tsx —— 195 行：links/loader/headers/meta/Index 主页路由全套；lazy-load + Promise.all + JSON-LD
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/_index.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const indexRouteQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 _index 文件名约定",
    prompt: "首页路由文件名是 ____（不写 .tsx）。",
    options: [],
    blanks: [{ id: "v", placeholder: "文件名", acceptedAnswers: ["_index"] }],
    correctAnswer: { type: "fill_blank", values: { v: "_index" } },
    explanation: { short: "_index.tsx 映射根路径 /；下划线前缀让 Remix 识别为「父路由的默认 index」。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 _index 与 index 的区别",
    prompt: "为什么是 _index 不是 index？",
    options: [
      sc("A", "Remix v2 file-routing 约定：下划线 _ 前缀让文件被视为「pathless / index 路由」而非 /index 子路径；index.tsx 会映射成 /index 而非 / —— 完全不同语义"),
      sc("B", "随机"),
      sc("C", "TypeScript 限制"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "_index = 父路由默认页（映射 /）；index = 子路径 /index——一字之差。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 多导出 links/loader/headers/meta",
    prompt: "_index.tsx 同时 export links / loader / headers / meta / 默认组件——为什么这种结构？",
    options: [
      sc("A", "Remix 路由文件按命名规范导出：links（注入 <link> 标签）、loader（服务端数据）、headers（响应头）、meta（<meta> 标签）、default（UI）；五者由框架在不同时机调用；约定 > 配置"),
      sc("B", "随机"),
      sc("C", "TypeScript 限制"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix 路由模块协议——5 个导出 = 5 种生命周期挂钩。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 lazy(() => import(...)) ",
    prompt: "const TabShowcase = lazy(() => import('~/components/home/tab-showcase'));——同一文件 5 个 lazy 调用？",
    options: [
      sc("A", "对——首屏只渲 Hero，TabShowcase / VideoShowcase / DonghuaSection / CyberTerminal / BubbleMessageBoard 都拆 chunk 按需懒加载；首屏 JS 体积大幅压缩"),
      sc("B", "性能更差"),
      sc("C", "TypeScript 限制"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "lazy + Suspense = 路由级代码分割——首屏体积优化的标配。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 ViewportLazySection",
    prompt: "<ViewportLazySection fallback={...}><Suspense><TabShowcase /></Suspense></ViewportLazySection>——双层包裹的意义？",
    options: [
      sc("A", "ViewportLazySection 用 IntersectionObserver 直到组件接近视口才挂载；Suspense 处理懒加载组件的 chunk 加载中状态；两层串：可视才加载 + 加载中显 fallback；带宽友好 + 体验流畅"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Viewport 懒挂 + Suspense 懒加载 = 双重延迟体系。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/components/common/ViewportLazySection.tsx"],
  }),
  q({
    type: "single_choice", title: "Q6 loader Promise.all",
    prompt: "loader 内 const [session, messages] = await Promise.all([sessionPromise, messagesPromise]);——Promise.all 而非串行 await？",
    options: [
      sc("A", "并发执行——session 查与 messages 查相互独立；并发让响应时间 = max(两者) 而非 sum；SSR 关键路径必须并发优化"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "性能更差"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "独立 IO → Promise.all 并发；串行是反模式。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 sessionPromise 条件",
    prompt: "const sessionPromise = requestHasAuthSessionCookie(request) ? getSessionCached(request) : Promise.resolve(null);——意图？",
    options: [
      sc("A", "无 auth cookie 的访客直接 short-circuit 返 null —— 跳过 D1 查询；优化访客流量大的首页（多数访客是访客非用户）"),
      sc("B", "性能更差"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "lazy auth：cookie 存在性预过滤 → 不必要的 D1 查询不发；首页性能关键。" },
    abilityTags: ["bridge.reactRouter.loader", "backend.session.cookie", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/auth.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q8 用户额外查询",
    prompt: "if (session?.user) { [limitStatus, userPendingMessages] = await Promise.all([...]); }——为什么用户登录后才查这两个？",
    options: [
      sc("A", "limitStatus（消息提交配额）+ pendingMessages（未审核消息）只对登录用户有意义；访客无 user.id 也查不出；按状态条件查询省掉无用 D1 调用"),
      sc("B", "TypeScript"),
      sc("C", "随机"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "条件查询 = 按用户态分支——访客省钱、用户拿全。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/messages.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q9 Cache-Control 三态",
    prompt: "headers Cache-Control: session?.user ? 'private, no-store' : 'public, max-age=60, s-maxage=300, stale-while-revalidate=600';——三方策略？",
    options: [
      sc("A", "登录用户：private no-store——CDN 不缓存（含个人化 UI）；访客：public 60s 浏览器 + 300s CDN + stale 600s——访客流量大可激进 CDN 缓存；按身份分级"),
      sc("B", "永远 no-store"),
      sc("C", "永远 public"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "缓存策略按用户态分——个人化页 no-store；公共页 public+stale。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 stale-while-revalidate",
    prompt: "stale-while-revalidate=600 含义？",
    options: [
      sc("A", "缓存过期（max-age=60 后）但仍 ≤600s 内的请求：CDN 立刻返过期内容 + 后台异步 revalidate；用户感知延迟为 0；后续请求拿到新内容；CDN 性能优化金标准"),
      sc("B", "永远新"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "stale-while-revalidate = 过期立刻返 + 后台刷新；零延迟体验。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 forwardLoaderCacheControl",
    prompt: "export const headers: HeadersFunction = forwardLoaderCacheControl;——必要？",
    options: [
      sc("A", "v3_singleFetch 模式下 loader 的 headers 默认不进 document Response；显式 forward 才把 Cache-Control 透传到外层；不加则缓存策略失效"),
      sc("B", "可省"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "v3_singleFetch + headers = 必加 forwardLoaderCacheControl。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q12 JSON-LD 结构化数据",
    prompt: "<script type=\"application/ld+json\" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />——目的？",
    options: [
      sc("A", "Schema.org 结构化数据让搜索引擎理解页面是「Person 类」+ name/jobTitle/worksFor 等；提升 SERP 富片段展示概率；SEO 高阶项"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "JSON-LD = Schema.org 结构化数据 → SEO 富片段。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 dangerouslySetInnerHTML",
    prompt: "为什么用 dangerouslySetInnerHTML？",
    options: [
      sc("A", "JSON-LD 必须是原始 JSON 字符串作 script 内容；React 默认会 escape <>& 让 JSON 损坏；dangerouslySetInnerHTML 跳过 escape 注入原文；jsonLd 是自构对象不含用户输入——安全可控"),
      sc("B", "永远不安全"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "dangerouslySetInnerHTML 用于注入「自己控制的纯文本」如 JSON-LD；用户输入绝不能这么用。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 ClientOnly 包 BubbleMessageBoard",
    prompt: "<ClientOnly fallback={...}>{() => <ViewportLazySection><Suspense><BubbleMessageBoard ... /></Suspense></ViewportLazySection>}</ClientOnly>——为什么 ClientOnly 包外层？",
    options: [
      sc("A", "BubbleMessageBoard.client 含浏览器 API（动画/交互），不能 SSR；ClientOnly 让首屏只显 fallback，hydrate 后才挂载真实组件；三层（ClientOnly + ViewportLazy + Suspense）= 三重保护"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ClientOnly 在最外 = 杜绝 SSR 触发；后续两层处理 chunk 与可视。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/messages/BubbleMessageBoard.client.tsx"],
  }),
  q({
    type: "single_choice", title: "Q15 links 内 fontPreloadHrefs",
    prompt: "links 内 ...fontPreloadHrefs(HOME_HERO_PRELOAD_TEXT, 8).map(href => ({ rel: 'preload', as: 'font', ... }))——为什么 preload 字体？",
    options: [
      sc("A", "Hero 区域用了特定字体，preload 让浏览器在解析 HTML 早期开始下载字体——避免 FOIT（Flash of Invisible Text）；首屏 LCP 关键；为 8 个字符预加载够 Hero 用就行"),
      sc("B", "性能更差"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "字体 preload = 防 FOIT + 改善 LCP——首屏关键路径。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/lib/font-preloads.ts"],
  }),
  q({
    type: "branch_trace", title: "Q16 访客访问首页全流",
    prompt: "访客（无 cookie）访问 / —— 全流程？",
    options: [
      sc("s1", "1. Worker 收 GET /"),
      sc("s2", "2. Remix 路由匹配 _index.tsx → loader 启动"),
      sc("s3", "3. requestHasAuthSessionCookie(request) 返 false → sessionPromise = Promise.resolve(null)"),
      sc("s4", "4. messagesPromise = getApprovedMessages(...)"),
      sc("s5", "5. Promise.all 并发等两 promise"),
      sc("s6", "6. session=null → 跳过 limitStatus/pendingMessages 查询"),
      sc("s7", "7. return json({ userId:null, currentUser:null, songs, messages, ... }, { headers: 'public,max-age=60,s-maxage=300,...' })"),
      sc("s8", "8. headers 函数 forwardLoaderCacheControl 透传 Cache-Control"),
      sc("s9", "9. SSR 渲染 Index 组件 → Header / Hero 直接渲；后续区块用 Suspense fallback 占位"),
      sc("s10", "10. HTML + 缓存头返浏览器 → CDN 缓存 60s 浏览器、300s CDN"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8", "s9", "s10"] },
    explanation: { short: "访客首页 SSR 全 10 步——lazy auth + Promise.all + lazy 区块 + Cache-Control。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 useLoaderData<typeof loader>",
    prompt: "const { currentUser, songs, messages, userPendingMessages, messageLimitStatus } = useLoaderData<typeof loader>();——typeof loader 含义？",
    options: [
      sc("A", "TypeScript 用 typeof loader 推导 loader 函数返回类型 → 让 useLoaderData 静态类型对应；改 loader 字段时 useLoaderData 编译期错；类型与实现一处真源"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "typeof loader = 类型自动跟随 loader 实现；类型安全的 loader 数据消费。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 pulseFallback helper",
    prompt: "const pulseFallback = (className) => <div className={className + ' bg-gradient-to-r ... animate-pulse'} />;——为什么本地函数？",
    options: [
      sc("A", "多个 ViewportLazySection 都需要 fallback 占位 + 高度类不同；闭包参数化高度类；vs 五处复制 className 字符串易错；本地工具函数减重复"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "本地工厂 = 减重复 + 参数化差异——比 5 次复制好。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 Faq 不在 lazy 里",
    prompt: "Faq 在 main 之后直接渲（非 lazy）——为什么不延迟？",
    options: [
      sc("A", "Faq 体积小且常用、用户经常滚到——不必延迟；lazy 适合「重 + 低概率被看」的下方组件；选择性应用懒加载"),
      sc("B", "应该 lazy"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "lazy 不是越多越好——按「重 + 概率低」选；轻组件直接 import。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 加新区块到首页",
    prompt: "想在首页加一个「项目展示」区块。改动？",
    options: [
      sc("A", "1) 写组件 app/components/home/projects-showcase.tsx 2) _index.tsx 内加 const ProjectsShowcase = lazy(() => import(...)) 3) 在 main 内加 ViewportLazySection + Suspense + ProjectsShowcase；零改 loader"),
      sc("B", "改 root"),
      sc("C", "改 wrangler"),
      sc("D", "改 loader"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "加纯展示区块 = 加 lazy 引用 + 加 JSX——loader 不需要动。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 加新 loader 数据",
    prompt: "若新区块需要服务端数据（如 D1 查 projects 表）。改 loader？",
    options: [
      sc("A", "1) 加 const projectsPromise = getProjects() 2) 加进 Promise.all 并发 3) return json 里加 projects 字段；TypeScript 自动让 useLoaderData 拿到新字段；扩展线性"),
      sc("B", "新 API"),
      sc("C", "改 root"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader 加并发查 + json 字段——一处扩展全栈联通。" },
    abilityTags: ["project.modify.fullstack", "bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 _index.tsx 整体哲学",
    prompt: "_index.tsx 195 行整体设计哲学？",
    options: [
      sc("A", "1) 5 个 export 协议（links/loader/headers/meta/default）各管一事 2) lazy + Suspense + ViewportLazy 三重延迟首屏体积控制 3) Promise.all 并发 IO 4) 条件查询访客省 D1 5) Cache-Control 按用户态分级（public + stale-while-revalidate vs no-store）6) JSON-LD 结构化数据 SEO 7) ClientOnly 包浏览器 API 组件 8) 字体 preload 改善 LCP——综合：「首页是 SSR + SEO + 性能 + 个人化全方位演练场」"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "_index 8 原则——首页是 Remix 工程能力的最强综合体现。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
];
