/**
 * Real questions for site-06-file-routing / layout-route.
 * Anchor: remix/app/routes/game.tsx —— 仅 5 行：纯 Outlet layout 容器；与 game._index.tsx + game.$platform.tsx 协作展示嵌套路由
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/game.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const layoutRouteQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 game.tsx 行数",
    prompt: "game.tsx 仅 ____ 行（写整数），整个文件就 import + Outlet 组件。",
    options: [],
    blanks: [{ id: "v", placeholder: "数字", acceptedAnswers: ["5", "五"] }],
    correctAnswer: { type: "fill_blank", values: { v: "5" } },
    explanation: { short: "5 行——import Outlet + 默认导出函数返 <Outlet/>；最薄的 layout route。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 layout route 的作用",
    prompt: "为什么 game.tsx 只返 <Outlet/>？",
    options: [
      sc("A", "layout route 是「父壳」——内含 Outlet 占位让子路由（game._index, game.$platform）渲在这里；当前未加共享导航/侧栏所以仅 Outlet；将来可在 Outlet 外加 <GameSidebar /> 等共享 UI"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "layout 父路由 = Outlet 占位 + 可加共享 UI；当前仅占位。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game._index.tsx", "app/routes/game.$platform.tsx"],
  }),
  q({
    type: "single_choice", title: "Q3 不写 game.tsx 后果",
    prompt: "若删掉 game.tsx 仅留 game._index + game.$platform —— 还能访问吗？",
    options: [
      sc("A", "Remix v2 file routing 要求父 layout 文件存在才让 . 分段路由生效；删 game.tsx 会导致 game._index 与 game.$platform 找不到父——路由表错误；layout 文件必须存在"),
      sc("B", "无影响"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "嵌套路由的父 layout 文件强制存在——即便只是空 Outlet。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 import 自 @remix-run/react",
    prompt: "import { Outlet } from \"@remix-run/react\"; ——Outlet 是什么？",
    options: [
      sc("A", "Remix 的「子路由占位」组件——父 layout 在这渲染当前匹配的子路由；与 React Router 同名概念；嵌套路由的核心"),
      sc("B", "普通 div"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Outlet = 嵌套路由占位；子路由组件在这挂。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 game.tsx vs game._index.tsx",
    prompt: "区别？",
    options: [
      sc("A", "game.tsx：父 layout 容器，包含 Outlet；任何 /game/* 都套这个 shell。game._index.tsx：/game 默认页（不是 /game/index）；仅在 URL 精确为 /game 时挂在 Outlet 内"),
      sc("B", "完全等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "layout = 容器；_index = 默认子页；两者协作让 / 与 /xxx 共 layout。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game._index.tsx"],
  }),
  q({
    type: "single_choice", title: "Q6 加共享导航到 layout",
    prompt: "若想让所有 /game/* 页面都显「返回 /game 列表」按钮——落点？",
    options: [
      sc("A", "改 game.tsx —— 在 <Outlet/> 上方加 <Link to=\"/game\">返回</Link>；共享 UI 一次写多处生效；这就是 layout route 的核心价值"),
      sc("B", "改子路由"),
      sc("C", "改 root"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "共享 UI = layout route 内；零重复。" },
    abilityTags: ["project.modify.fullstack", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 父 loader 共享数据",
    prompt: "若想让所有 /game/* 共享一个 loader 数据（如平台列表）——落点？",
    options: [
      sc("A", "game.tsx 加 loader 返平台列表；子路由用 useRouteLoaderData('routes/game') 拿；layout loader = 共享数据；vs 每个子路由各查一次浪费"),
      sc("B", "重复查"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "layout loader = 共享数据；子路由 useRouteLoaderData 消费。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 useRouteLoaderData",
    prompt: "useRouteLoaderData('routes/game') —— 字符串参数含义？",
    options: [
      sc("A", "路由模块路径 ID —— Remix 用文件路径作 ID（'routes/game' = app/routes/game.tsx）；子路由用此查父 loader 数据；vs useLoaderData 只拿当前路由数据"),
      sc("B", "URL"),
      sc("C", "随机"),
      sc("D", "组件名"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useRouteLoaderData(routeId) = 跨层级拿数据；ID 是路由模块路径。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 Outlet vs children",
    prompt: "为什么用 <Outlet/> 而不是 React 的 children prop？",
    options: [
      sc("A", "嵌套路由是 Remix 的运行时机制——根据 URL 决定挂哪个组件；children 是 React 的编译期机制，固定父子；Outlet 是给路由系统的「插槽」，不是普通组件树"),
      sc("B", "完全等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Outlet = 路由系统的运行时插槽；children = React 编译期；两者本质不同。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 layout 嵌套深度",
    prompt: "若 /game/$platform/$mode 三层 URL —— 文件结构？",
    options: [
      sc("A", "game.tsx + game.$platform.tsx + game.$platform.$mode.tsx；每层都是潜在 layout（如有 Outlet 才是）；最深叶子文件是 leaf 路由；扁平命名表树"),
      sc("B", "目录嵌套"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix v2 嵌套深度任意——. 段加深 + 各层可作 layout。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q11 用户访问 /game/genshin 路由匹配",
    prompt: "用户从 /game 跳到 /game/genshin —— 步骤？",
    options: [
      sc("s1", "1. Link 触发 client 路由切到 /game/genshin"),
      sc("s2", "2. Remix 路由匹配树：root.tsx → game.tsx → game.$platform.tsx（params.platform='genshin'）"),
      sc("s3", "3. 调三层各自的 loader（root/game/game.$platform）并发执行"),
      sc("s4", "4. root.tsx Layout 渲染 → 内 <Outlet/> 是 game.tsx 的渲染目标"),
      sc("s5", "5. game.tsx 渲染 → 仅 <Outlet/> —— 把控制让给 game.$platform.tsx"),
      sc("s6", "6. game.$platform.tsx 用 useLoaderData 渲染具体平台 UI"),
      sc("s7", "7. 用户看到三层套娃：root shell → game shell（薄）→ platform 详情"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7"] },
    explanation: { short: "嵌套路由 7 步——Outlet 链式套娃；各层 layout 包裹叶子。" },
    abilityTags: ["code.position.handler", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/root.tsx", "app/routes/game.$platform.tsx"],
  }),
  q({
    type: "single_choice", title: "Q12 默认导出函数命名",
    prompt: "export default function GameLayout() { return <Outlet />; } ——函数名 GameLayout 重要吗？",
    options: [
      sc("A", "对 Remix 不重要——Remix 只看 default export；但对 React DevTools 有用：组件名出现在树中便于调试；命名与文件功能匹配是工程惯例"),
      sc("B", "强制"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "default 函数名仅为 DevTools 与可读性；Remix 不用名字识别。" },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 父 layout 没 Outlet 后果",
    prompt: "若 game.tsx 内不写 <Outlet/> 只写 <div>game</div> —— 子路由会渲吗？",
    options: [
      sc("A", "不会——子路由必须有 Outlet 才能挂；用户访问 /game/genshin 会看到「game」字样而无平台 UI；Outlet 是嵌套必需"),
      sc("B", "自动渲"),
      sc("C", "报错"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "缺 Outlet = 子路由无处挂——空 layout bug 的常见原因。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 parent ErrorBoundary",
    prompt: "若 game.$platform 抛错——错误在哪渲？",
    options: [
      sc("A", "向上找 ErrorBoundary：先 game.$platform 自身（无）→ game.tsx 的 ErrorBoundary（无）→ root.tsx 的 ErrorBoundary——错误页一直向上冒；ErrorBoundary 在哪定义影响错误隔离粒度"),
      sc("B", "永远 root"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ErrorBoundary 向上查找 = 子路由错可被父层隔离捕获。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q15 game.tsx 加 ErrorBoundary",
    prompt: "想让 /game/* 错误显「游戏区出错了」专属错误页（不冒到全局）——落点？",
    options: [
      sc("A", "game.tsx 加 export function ErrorBoundary() { return <GameErrorPage /> }；子路由错先被这层捕；不冒到 root；错误隔离粒度"),
      sc("B", "改 root"),
      sc("C", "新文件"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "layout ErrorBoundary = 模块化错误隔离；按域设错误页。" },
    abilityTags: ["project.modify.fullstack", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 layout 与 _index 配合",
    prompt: "若 game.tsx 加共享导航后，/game 默认页（game._index.tsx）会怎么显示？",
    options: [
      sc("A", "URL=/game 时：game.tsx 渲共享导航 + Outlet 中渲 game._index 的内容；用户看到「导航 + 默认列表」；URL=/game/xxx 时：game._index 不挂，Outlet 改渲 platform 详情"),
      sc("B", "永远只 _index"),
      sc("C", "永远只 platform"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "_index 在 URL 精确为父路径时挂；其他子路径接管。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game._index.tsx"],
  }),
  q({
    type: "single_choice", title: "Q17 loader 不写也合法",
    prompt: "game.tsx 没 loader——合法吗？",
    options: [
      sc("A", "合法——loader 是可选；layout 仅渲染时也不必查数据；保持最薄；按需扩展"),
      sc("B", "强制"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader 可选——纯渲染 layout 不需要。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 _ pathless layout 应用",
    prompt: "若想让 /login 与 /signup 共享 auth shell 但 URL 不带 /auth 前缀——文件结构？",
    options: [
      sc("A", "_auth.tsx（pathless layout，Outlet）+ _auth.login.tsx（URL=/login）+ _auth.signup.tsx（URL=/signup）；_前缀让 _auth 不参与 URL；分组+共享 layout"),
      sc("B", "auth.login.tsx"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "_前缀 pathless = URL 不变但提供 layout——Remix 强大的分组工具。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 layout route 性能",
    prompt: "嵌套 4 层 layout（root → A → B → C → leaf）—— 性能开销？",
    options: [
      sc("A", "实测开销极小——每层仅 React 渲染开销 + 各自 loader（如有）并发；Remix 用 v3_singleFetch 一次请求拿所有 loader 数据；嵌套深度不引性能问题"),
      sc("B", "致命"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "嵌套 layout 性能开销小——Remix singleFetch 优化数据并发。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 layout 文件何时该加 vs 不加",
    prompt: "什么场景需要 layout route？",
    options: [
      sc("A", "1) 多子路由共享 UI/侧栏/导航 2) 共享 loader 数据 3) 共享 ErrorBoundary 隔离子路由错误；这三种场景值得；纯单页（如 cv.tsx）不必"),
      sc("B", "永远要"),
      sc("C", "永远不要"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "layout route 三大用途：UI 共享、数据共享、错误隔离——按需选。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 当前 game.tsx 的薄选择",
    prompt: "本项目 game.tsx 仅 5 行 Outlet 占位——为什么不去掉？",
    options: [
      sc("A", "Remix 嵌套路由要求父文件存在（即便空 Outlet）；删除会让 game._index + game.$platform 失父；保留是必要的；将来加共享 UI/loader 时不必新建"),
      sc("B", "可去掉"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "嵌套子路由的父 layout 文件必须存在——即便空 Outlet。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 layout route 整体哲学",
    prompt: "Remix layout route 整体设计哲学？",
    options: [
      sc("A", "1) 父文件 + Outlet = 嵌套子路由必备 2) 共享 UI/loader/ErrorBoundary 三大用途 3) 嵌套深度任意（. 段递归）4) _前缀 pathless 让 layout 不影响 URL 5) Outlet 是路由运行时插槽不是 React children 6) 子路由错误向上冒到最近 ErrorBoundary 7) layout loader 数据用 useRouteLoaderData(routeId) 跨层取——综合：「Remix 嵌套路由通过文件结构表 UI 树 + 数据树 + 错误树」"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "layout route 7 原则——Remix 嵌套路由的核心模式。" },
    abilityTags: ["code.position.handler", "bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game._index.tsx", "app/routes/game.$platform.tsx"],
  }),
];
