/**
 * Real questions for site-06-file-routing / routing-capstone.
 * Anchor: 综合 remix/app/routes/ 全目录的 file-based routing 规则、resource vs UI、扁平 vs 嵌套、splat、动态参数、_index、_pathless 等
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/";
const sc = (id: string, text: string) => ({ id, text });

export const routingCapstoneQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 routes/ 文件总数",
    prompt: "remix/app/routes/ 内大约有 ____ 个路由文件（写整数）。",
    options: [],
    blanks: [{ id: "v", placeholder: "数字", acceptedAnswers: ["20", "21"] }],
    correctAnswer: { type: "fill_blank", values: { v: "20" } },
    explanation: { short: "约 20 个——_index/anime/api.auth.$/api.claim-token/api.nemesis-feedback/api.nemesis/auth.sign-out/auth/chat/cv/gallery/game.$platform/game._index/game/messages/music/rapid-layers-preview/sitemap[.]xml/updates/xiao 等。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 五种约定符号",
    prompt: "Remix v2 扁平路由的五种特殊符号？",
    options: [
      sc("A", ". 段分隔（auth.sign-out）/ $ 动态参数（game.$platform）/ $ 单字符 splat（api.auth.$）/ _ 前缀 pathless（_index, _auth）/ [] 转义（sitemap[.]xml）—— 五种符号表完整路由树"),
      sc("B", "三种"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "五约定符号 = . / $ / $单字符 / _ / [] —— 扁平命名表 URL 树。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 路由分类",
    prompt: "按职能分，本项目 routes/ 的文件可分几类？",
    options: [
      sc("A", "三类：1) UI 路由 .tsx（_index/chat/cv/gallery/...）2) 资源路由 .ts（api.*）3) layout 路由（game.tsx 仅 Outlet）；按职能选文件类型"),
      sc("B", "随机"),
      sc("C", "全 UI"),
      sc("D", "全 API"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三类：UI / 资源 / layout——文件名 + 后缀暗示职能。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 加新页：决策树",
    prompt: "「需要加一个 /docs 文档页（含 /docs 列表 + /docs/$slug 详情）」——文件结构？",
    options: [
      sc("A", "docs.tsx（layout，Outlet）+ docs._index.tsx（列表）+ docs.$slug.tsx（详情）；嵌套结构 + 共享 layout 显示侧栏导航；将来加 /docs/categories 也用 docs.categories.tsx"),
      sc("B", "单文件"),
      sc("C", "目录嵌套"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "列表 + 详情 = 嵌套 3 文件——layout 共享侧栏的标准模式。" },
    abilityTags: ["project.modify.fullstack", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 加新 API：决策树",
    prompt: "「需要加一个 GET /api/version 返当前部署版本」——文件结构？",
    options: [
      sc("A", "api.version.ts（resource route）—— 仅 export loader 返 json({ version: ... })；.ts 后缀明示意图；不必拆 layout"),
      sc("B", ".tsx"),
      sc("C", "嵌套"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "简单 API = 资源路由 .ts 单文件——loader 返 JSON。" },
    abilityTags: ["project.modify.fullstack", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 加 catch-all：决策树",
    prompt: "「需要捕获所有 /docs/proxy/* 转发到外部文档站」——文件结构？",
    options: [
      sc("A", "docs.proxy.$.ts —— splat 捕获 /docs/proxy/任意深度；loader 内提取 splat 参数（params['*']）+ fetch 外站；典型代理模式"),
      sc("B", "$slug"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "深度未知 → splat $；params['*'] 拿剩余路径。" },
    abilityTags: ["project.modify.fullstack", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 加 sitemap.xml 类含点 URL",
    prompt: "想加 /robots.txt——文件名？",
    options: [
      sc("A", "robots[.]txt.tsx 或 .ts —— [.] 转义让 . 字面化；否则 robots.txt 会变成两段；与 sitemap[.]xml.tsx 同款约定"),
      sc("B", "robots.txt.tsx"),
      sc("C", "robots-txt"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "URL 含 . 字面 → [] 转义；与 sitemap[.]xml 同款。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 routes 命名一致性",
    prompt: "本项目 api.* 都用连字符（api.nemesis-feedback / api.claim-token）—— 一致性？",
    options: [
      sc("A", "对——同类资源（API）用同套命名风格（点分段 + 连字符复合词）；扁平路由文件名直接是 URL 段，命名一致 = URL 一致 = 用户/客户端心智一致；工程纪律"),
      sc("B", "随机"),
      sc("C", "无所谓"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "路由文件命名一致 = URL 一致 = API 体验一致。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 路由文件中常见的反模式",
    prompt: "下列哪个是路由文件中常见反模式？",
    options: [
      sc("A", "在 routes/ 内塞业务工具函数——routes/ 应只放路由模块；工具函数应去 lib/ 或 utils/；混杂会让模块边界模糊"),
      sc("B", "loader/action"),
      sc("C", "meta"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "routes/ = 路由模块专属；工具函数另开目录——边界清晰。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 路由文件「薄」原则",
    prompt: "为什么本项目 routes/ 内文件普遍很「薄」（chat.tsx 35 行，game.tsx 5 行）？",
    options: [
      sc("A", "路由文件聚焦「服务端 loader/action + 渲染入口」——UI 复杂度推到 components/，业务逻辑推到 lib/services/；路由文件 = 串联各层的薄一层；分层"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "薄路由 + 厚 lib/components = Remix 项目分层范式。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 路由 ID",
    prompt: "Remix 内部用什么作路由 ID？",
    options: [
      sc("A", "文件路径相对 app/ 去掉后缀——routes/game 或 routes/api.nemesis；useRouteLoaderData('routes/game') 等用此 ID 跨层级取数据"),
      sc("B", "URL"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "路由 ID = 文件路径；跨层级 API 都用此 ID。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 缺 _index 后果",
    prompt: "若有 game.tsx + game.$platform.tsx 但删 game._index.tsx —— 访问 /game 显示什么？",
    options: [
      sc("A", "game.tsx 渲 layout（Outlet 空）；Outlet 内无组件——用户只见 game layout 框架但中间空白；建议加 _index 让 /game 有默认内容"),
      sc("B", "404"),
      sc("C", "崩溃"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "缺 _index = 父路径访问时 Outlet 无内容；UI 空白。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game._index.tsx"],
  }),
  q({
    type: "single_choice", title: "Q13 多动态参数",
    prompt: "若想 /docs/$category/$slug —— 文件结构？",
    options: [
      sc("A", "docs.tsx + docs.$category.tsx + docs.$category.$slug.tsx；params 内有 { category, slug }；嵌套同模式"),
      sc("B", "$category-$slug"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "多段动态参数 = 多 $name；按嵌套层级建文件。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 splat 与 $param 混用",
    prompt: "若 /api/$service/$.ts —— 含义？",
    options: [
      sc("A", "$service 单段动态 + 末段 $ splat 多段——/api/users/foo/bar/baz 匹配为 service='users', * = 'foo/bar/baz'；混用支持灵活路径"),
      sc("B", "无效"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "$param + $ splat 混用 = 灵活捕获模式。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 命名冲突",
    prompt: "若同时有 docs.tsx + docs.ts —— 后果？",
    options: [
      sc("A", "Remix 编译报冲突——同 URL 不能两个路由模块；选其中一个删；命名按职能选 .tsx（含 UI） 或 .ts（仅 API）"),
      sc("B", "都生效"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "同 URL 双路由 = 编译冲突；选一个。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 动态 vs 静态优先级",
    prompt: "若同时有 game.special.tsx 与 game.$platform.tsx —— 用户访问 /game/special 命中哪个？",
    options: [
      sc("A", "game.special.tsx —— Remix 路由匹配按特异性：静态段 > 动态段 > splat；同段同位置时静态优先"),
      sc("B", "$platform"),
      sc("C", "随机"),
      sc("D", "都"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "静态优先动态优先 splat——可用于覆盖动态路由的特例。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 file-based vs config-based 取舍",
    prompt: "Remix v2 file routing vs RR7 routes.ts config——哪种更适合本项目？",
    options: [
      sc("A", "本项目（中小型个人站，~20 路由）file routing 已够——直观、零配置；若加大量动态生成路由（CMS/i18n 多语言）才考虑 config-based；规模决定选择"),
      sc("B", "永远 config"),
      sc("C", "永远 file"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "中小型 file routing 即可；大型/动态 config 更优——规模驱动选择。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 路由树可视化",
    prompt: "怎么快速看本项目的完整路由树？",
    options: [
      sc("A", "ls app/routes/ + 按文件名规则脑补；或用 npx remix routes 命令打印路由表；或在 dev 工具看 Remix 路由 manifest；多手段验证"),
      sc("B", "猜"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ls + remix routes 命令 + manifest 三种方式查路由树。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 路由文件不导出 default",
    prompt: "resource route（.ts）不导出 default 组件——访问会怎样？",
    options: [
      sc("A", "loader 返 Response 直接响应；浏览器访问 /api/version 会下载/显 JSON 而非渲页面；resource route 的本质——返数据不渲 UI"),
      sc("B", "404"),
      sc("C", "崩溃"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "resource route 无 UI，直接返 Response——这就是它和 UI route 的本质区别。" },
    abilityTags: ["code.position.handler", "bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 测试路由",
    prompt: "怎么测试一个路由？",
    options: [
      sc("A", "1) 单测 loader/action 函数（mock request）2) integration 测路由 fetch 整页响应（用 createRemixStub 或部署到 dev）3) e2e 测用户跳转（Playwright）；分层测各层"),
      sc("B", "无法测"),
      sc("C", "只 e2e"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "路由测试三层：单测函数 + integration 测响应 + e2e 测交互。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 重命名路由的迁移成本",
    prompt: "若想把 /chat 重命名 /ai 影响范围？",
    options: [
      sc("A", "1) 文件 chat.tsx → ai.tsx 2) Header navigation 数组改 href 3) 任何指向 /chat 的硬编码 link 改（grep 全 codebase）4) /chat 加 redirect 到 /ai 兼容老链接 5) sitemap 等改；URL 是公共契约改名成本不小"),
      sc("B", "改一处"),
      sc("C", "无影响"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "URL 是公共契约——改名要做迁移 + redirect；规划 URL 命名要长远。" },
    abilityTags: ["project.modify.fullstack", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 site-06 路由整体哲学",
    prompt: "Remix v2 file routing 综合设计哲学（毕业级）？",
    options: [
      sc("A", "1) 文件名 = URL 强约定 → 目录即路由表 2) 五约定符号（. $ $-单 _ []）表 URL 树各种语义 3) 资源路由 .ts vs UI 路由 .tsx 区分意图 4) layout route 提供共享 UI/loader/ErrorBoundary 5) splat 让单文件捕一族 endpoint 6) _index 与 _ pathless 处理「父路径默认」与「URL 无关分组」7) 静态 > 动态 > splat 优先级 8) URL 是公共契约改名要做 redirect——综合：「约定优于配置 + 文件结构表语义 + 路由薄 + 工具组合表达力」"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix v2 路由 8 原则——文件路由约定的全景。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
];
