/**
 * Real questions for site-05-shell-errors / error-boundary-comp.
 * Anchor: remix/app/components/error/RouteErrorBoundary.tsx
 *   - useRouteError + isRouteErrorResponse(error)
 *   - errorMessage = isRouteErrorResponse(error) ? `${error.status} ${error.statusText}` : error instanceof Error ? error.message : "未知错误"
 *   - displayText 打字机 fullText = "页面游走了"
 *   - canvas 鱼动画 (3 条鱼随波)
 *   - GsapFillLink to="/" 文案 "游回首页"
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/error/RouteErrorBoundary.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const errorBoundaryCompQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 fullText",
    prompt: "const fullText = \"____ \"; (RouteErrorBoundary 的)",
    options: [], blanks: [{ id: "v", placeholder: "中文", acceptedAnswers: ["页面游走了"] }],
    correctAnswer: { type: "fill_blank", values: { v: "页面游走了" } },
    explanation: { short: "「游走了」——配鱼的视觉。404 用「无人之境」+ 龙；500 这套用「页面游走」+ 鱼。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 三个 hook",
    prompt: "顶部 import { useRouteError, isRouteErrorResponse } from \"@remix-run/react\"——这两个是？",
    options: [
      sc("A", "useRouteError 拿到 ErrorBoundary 捕获的 error；isRouteErrorResponse 判定 error 是不是 React Router 抛出的 Response（throw new Response(...)）"),
      sc("B", "useState/useEffect 别名"),
      sc("C", "Tailwind 提供"),
      sc("D", "isbot 库"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ErrorBoundary 专用 API。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 errorMessage 三段三元",
    prompt: "const errorMessage = isRouteErrorResponse(error) ? `${error.status} ${error.statusText}` : error instanceof Error ? error.message : \"未知错误\"; ——三个分支的来源？",
    options: [
      sc("A", "1) loader/action throw new Response (走 isRouteErrorResponse) 2) loader 抛 Error 实例 3) 抛任意 throw \"foo\"/throw 1 的兜底"),
      sc("B", "三个都是 React Router 自己的"),
      sc("C", "三个都是浏览器的"),
      sc("D", "三个都是 TypeScript 的"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "错误来源三种类型——三段保护让 boundary 永远能显示「点什么」。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q4 ErrorResponse 含 status",
    prompt: "判断：error.status 和 error.statusText 是 isRouteErrorResponse 收窄后才能安全访问的属性。",
    correctAnswer: { value: true },
    explanation: { short: "对——TypeScript discriminated union；isRouteErrorResponse 收窄到 ErrorResponse 类型才有 status/statusText。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 三条鱼初始位置",
    prompt: "const fish1 = { x: -100, ... }; fish2 = { x: canvas.width + 50, ... }——为什么 fish1 在屏幕外左侧、fish2 在屏幕外右侧？",
    options: [
      sc("A", "鱼往各自方向游进屏幕——左鱼向右游、右鱼向左游、第三鱼在中间——形成多向游动错落"),
      sc("B", "随机位置"),
      sc("C", "TypeScript 要求"),
      sc("D", "性能优化"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三鱼协同节奏让画面不单调。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 fish.direction = -1",
    prompt: "fish2 的 direction: -1，fish.x += fish.speed * fish.direction 让它向左移动。direction 用 -1/+1 而不是布尔？",
    options: [
      sc("A", "数学运算更简洁——单乘法搞定方向；如果用布尔要分支 if (right) x += speed; else x -= speed;"),
      sc("B", "TypeScript 不支持布尔"),
      sc("C", "性能"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "方向作为 ±1 标量是经典数值技巧。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 鱼出屏幕循环",
    prompt: "if (fish.direction > 0 && fish.x > canvas.width + 100) fish.x = -100; ——鱼出右边界后？",
    options: [
      sc("A", "瞬移回左边界外，再次游进——形成循环"),
      sc("B", "停止"),
      sc("C", "反向"),
      sc("D", "消失"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "无限循环游动——经典动画技巧。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 sin 浪",
    prompt: "const waveY = Math.sin(time * 2 + fish.x * 0.01) * 15; ——sin 函数让鱼？",
    options: [
      sc("A", "上下浪起伏 ±15px——time 控全局节奏，fish.x 让不同鱼出错相位（不齐步上下）"),
      sc("B", "鱼的速度"),
      sc("C", "鱼的颜色"),
      sc("D", "无意义"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "sin 配置让鱼游得有水的感觉。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 rotation 镜像",
    prompt: "const rotation = fish.direction > 0 ? 0 : Math.PI; ——为什么用 PI？",
    options: [
      sc("A", "向左游的鱼绕中心旋转 180°——视觉上鱼头朝左；ctx.rotate(Math.PI) = 180°"),
      sc("B", "性能优化"),
      sc("C", "TypeScript 要求"),
      sc("D", "随机抖动"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Canvas 角度单位是弧度，PI = 180°。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 displayText 与 errorMessage 共存",
    prompt: "JSX 里 <h1>{displayText}<span>|</span></h1> + <p>{errorMessage}</p>——两层文字？",
    options: [
      sc("A", "上层 displayText 是装饰文案（打字机），下层 errorMessage 是真实错误内容（404 Not Found / Error message 等）"),
      sc("B", "两层都是装饰"),
      sc("C", "两层都是错误内容"),
      sc("D", "其中一层是冗余"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "装饰 + 实质——两层并存让用户先感受氛围再获取信息。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 GsapFillLink 文案",
    prompt: "<GsapFillLink to=\"/\">游回首页 →</GsapFillLink>——文案设计？",
    options: [
      sc("A", "「游回」呼应鱼的主题——错误页文案与视觉协同"),
      sc("B", "随机"),
      sc("C", "Tailwind 默认"),
      sc("D", "TypeScript 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "文案与视觉锚定让品牌一致。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 ErrorBoundary 在哪",
    prompt: "RouteErrorBoundary 这个组件本身要被消费才生效。怎么用？",
    options: [
      sc("A", "在 root.tsx export function ErrorBoundary() { return <RouteErrorBoundary />; }——React Router 7 的约定"),
      sc("B", "在 _index.tsx import"),
      sc("C", "在 entry.client 里"),
      sc("D", "在 wrangler.toml 配置"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "framework 约定 export 一个 ErrorBoundary 顶层函数；React Router 自动消费。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q13 errorMessage 兜底",
    prompt: "throw 1（抛了一个数字）触发 ErrorBoundary，errorMessage 显示什么？",
    options: [
      sc("A", "「未知错误」——isRouteErrorResponse(1) false，1 instanceof Error false，落到第三个分支"),
      sc("B", "1"),
      sc("C", "TypeError"),
      sc("D", "空"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三段三元的兜底——抛任何非 Error 类型都能优雅处理。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q14 status 决定显示",
    prompt: "判断：error.status === 404 时 errorMessage 会显示「404 Not Found」（statusText 是默认的）。",
    correctAnswer: { value: true },
    explanation: { short: "对——React Router 抛 Response 时如果 statusText 没显式给，框架会用 HTTP 默认值（Not Found / Internal Server Error 等）。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 RouteErrorBoundary 与 NotFound404 区别",
    prompt: "项目里同时有 RouteErrorBoundary（这个文件）和 NotFound404（另一个）。功能划分？",
    options: [
      sc("A", "RouteErrorBoundary 是「全错误兜底」，按 status 决定 UI；NotFound404 是 RouteErrorBoundary 在 404 分支调用的子组件——更专门的视觉"),
      sc("B", "完全等价"),
      sc("C", "NotFound404 是 RouteErrorBoundary 的子类"),
      sc("D", "两者无关"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "实际项目中通常 RouteErrorBoundary 内部会判断 status === 404 渲染 <NotFound404 />，其他状态渲染本组件的鱼版本。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/error/NotFound404.tsx"],
  }),
  q({
    type: "single_choice", title: "Q16 不要把堆栈给用户看",
    prompt: "errorMessage 显示「Error: db down」（loader 抛 new Error('db down')）。生产环境是否合适？",
    options: [
      sc("A", "不合适——内部错误信息可能泄露 schema/路径/技术细节给攻击者；生产应展示通用 \"出错了，请重试\" + log 上报"),
      sc("B", "合适，能让用户报错更准"),
      sc("C", "TypeScript 要求"),
      sc("D", "Cloudflare 自动屏蔽"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "用户不该看到内部 error.message——dev 模式可以，生产要脱敏。" },
    abilityTags: ["ai.review.architecture", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 dev vs prod 的 ErrorBoundary",
    prompt: "想让 dev 模式显示完整堆栈、prod 显示通用文案。改 RouteErrorBoundary 怎么做？",
    options: [
      sc("A", "import.meta.env.DEV 区分——dev 显示 error.stack，prod 显示「页面游走了」+ \"出错了\"占位"),
      sc("B", "用 process.env"),
      sc("C", "loader 注入"),
      sc("D", "无法实现"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Vite 的 import.meta.env.DEV 是构建时常量，prod bundle 会消除 dev 分支。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 SSR 渲染",
    prompt: "loader 抛 throw new Response('boom', {status: 500})，SSR 时这一页 HTML 是什么？",
    options: [
      sc("A", "RouteErrorBoundary 的初始 JSX——displayText=空、errorMessage=\"500 \"，hydration 后打字机+鱼+完整状态码动起来"),
      sc("B", "白屏"),
      sc("C", "loader 抛错不能 SSR"),
      sc("D", "完整动画"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ErrorBoundary 是普通 React 组件，SSR + hydration 流程一致。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 .client 后缀考虑",
    prompt: "组件文件名是 RouteErrorBoundary.tsx——SSR 时是不是会因为 canvas/window 报错？",
    options: [
      sc("A", "不会——所有 window/canvas 都在 useEffect 里（仅客户端跑）；初始 render 只用 React state（displayText=\"\"），canvas 元素本身有 ref 但 SSR 渲染不需要 getContext"),
      sc("B", "会"),
      sc("C", "需要 .client 后缀"),
      sc("D", "Cloudflare 拒绝"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "只要 window/document 调用都在 effect 里，组件就能 SSR。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q20 同时多 Suspense 错",
    prompt: "判断：一个页面如果多个 Suspense 边界都抛错，RouteErrorBoundary 会渲染多次（每个错一次）。",
    correctAnswer: { value: false },
    explanation: { short: "错——一个 ErrorBoundary 实例只渲染一次（最近的错）。多个 Suspense 错会被各自最近的 boundary 捕获，root boundary 只看到最外层那个。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "position_judgement", title: "Q21 加错误上报",
    prompt: "想给所有错误加上 Sentry 上报。落点？",
    options: [
      sc("A", "RouteErrorBoundary 内 useEffect(() => { reportError(error) }, [error])——hydration 后客户端上报；同时 entry.server 的 onError 写服务端上报"),
      sc("B", "只在 entry.server"),
      sc("C", "在 root loader"),
      sc("D", "在每个组件"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "client + server 双端上报覆盖完整。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/entry.server.tsx"],
  }),
  q({
    type: "single_choice", title: "Q22 整体设计哲学",
    prompt: "RouteErrorBoundary 既显示错误又渲染装饰动画——是否反模式？",
    options: [
      sc("A", "不反模式——错误页本身是「最不希望用户停留」的页面；好的设计让错误页温和、可读、有出口（回家按钮）；动画消化挫败感比纯文本「Error 500」更人性化"),
      sc("B", "反模式，永远要纯文本"),
      sc("C", "反模式，永远要重定向到首页"),
      sc("D", "无意义"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "错误体验也是产品体验。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
];
