/**
 * Real questions for site-05-shell-errors / errors-capstone.
 * Anchor: 整合 root.tsx ErrorBoundary + RouteErrorBoundary.tsx + NotFound404.tsx + RouteTransition.tsx
 * 主题：错误体系的整体决策
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/error/RouteErrorBoundary.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const errorsCapstoneQuestions: RealQ[] = [
  q({
    type: "position_judgement", title: "Q1 加 503 maintenance 页",
    prompt: "新增「503 维护中」页面。落点？",
    options: [
      sc("A", "新建 components/error/Maintenance503.tsx + root ErrorBoundary 内 if (status === 503) 返回 Maintenance503"),
      sc("B", "改 RouteErrorBoundary 加分支"),
      sc("C", "改 entry.server"),
      sc("D", "wrangler.toml redirect"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "新错误状态 = 新组件 + root 分发——保持现有组件单一职责。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: "app/root.tsx", layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "position_judgement", title: "Q2 加全局错误上报",
    prompt: "想给所有错误上报到 Sentry。落点？",
    options: [
      sc("A", "ErrorBoundary 客户端 useEffect + entry.server onError 服务端——双端覆盖"),
      sc("B", "只在 ErrorBoundary"),
      sc("C", "只在 entry.server"),
      sc("D", "在每个 loader try/catch"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "client + server 双端，覆盖 SSR error 和客户端 boundary 触发。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: "app/entry.server.tsx", layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: ["app/entry.server.tsx", "app/root.tsx"],
  }),
  q({
    type: "branch_trace", title: "Q3 用户访问不存在的 URL",
    prompt: "用户访问 /nope 触发的步骤？",
    options: [
      sc("s1", "1. React Router 找不到匹配路由"),
      sc("s2", "2. 自动抛 throw new Response(null, { status: 404 })"),
      sc("s3", "3. 冒泡到 root export ErrorBoundary"),
      sc("s4", "4. useRouteError() 拿到 ErrorResponse 实例"),
      sc("s5", "5. isRouteErrorResponse(error) && error.status === 404 → 渲染 NotFound404"),
      sc("s6", "6. 浏览器收到 200 + NotFound404 HTML（Worker 已经把 404 status 透传）"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6"] },
    explanation: { short: "无匹配 → 框架抛 404 → boundary 接 → NotFound404。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: "app/root.tsx", layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/components/error/NotFound404.tsx", "app/root.tsx"],
  }),
  q({
    type: "branch_trace", title: "Q4 loader 抛 500",
    prompt: "/messages loader 抛 throw new Error('db down') 步骤？",
    options: [
      sc("s1", "1. React Router 调 messages loader"),
      sc("s2", "2. loader 抛普通 Error"),
      sc("s3", "3. 冒泡到 root ErrorBoundary"),
      sc("s4", "4. isRouteErrorResponse(error) === false（是普通 Error）"),
      sc("s5", "5. 走 RouteErrorBoundary 分支（鱼版本）"),
      sc("s6", "6. errorMessage = error.message = \"db down\""),
      sc("s7", "7. entry.server: didError = true → status 500"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7"] },
    explanation: { short: "普通 Error → RouteErrorBoundary（非 404 兜底）。" },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: "app/root.tsx", layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/entry.server.tsx"],
  }),
  q({
    type: "single_choice", title: "Q5 错误页与导航",
    prompt: "用户在 /messages 看到错误页，点击「游回首页」跳到 /。期间 RouteTransition 工作吗？",
    options: [
      sc("A", "工作——GsapFillLink 是 React Router Link，触发 useNavigation 状态变化，RouteTransition 监听后启动幕布过渡"),
      sc("B", "不工作"),
      sc("C", "只在错误页内"),
      sc("D", "需要手动调"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "错误页只是子树渲染，RouteTransition 在 root 层不受影响。" },
    abilityTags: ["bridge.reactRouter.loader", "frontend.event.click"],
    sourceFilePath: "app/components/transitions/RouteTransition.tsx", layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/transitions/RouteTransition.tsx"],
  }),
  q({
    type: "true_false", title: "Q6 子路由覆盖 ErrorBoundary",
    prompt: "判断：/chat 路由可以 export 自己的 ErrorBoundary 来定制聊天错误 UI，root 的不会接管这部分。",
    correctAnswer: { value: true },
    explanation: { short: "对——React Router 7 ErrorBoundary 可在每个路由级别 export，最近一层先接。" },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: "app/root.tsx", layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/chat.tsx"],
  }),
  q({
    type: "single_choice", title: "Q7 status 与 entry.server 协调",
    prompt: "loader throw new Response('forbidden', {status: 403})，最终 HTTP status 是？",
    options: [
      sc("A", "403——错误透传到 entry.server 的 responseStatusCode；didError 不会翻 true（boundary 处理了）；最终 status: didError ? 500 : responseStatusCode = 403"),
      sc("B", "200"),
      sc("C", "500"),
      sc("D", "302"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader Response.status → 框架透传 → entry.server 输出 403。" },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: "app/entry.server.tsx", layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/entry.server.tsx"],
  }),
  q({
    type: "single_choice", title: "Q8 RouteTransition 与 ErrorBoundary 顺序",
    prompt: "Layout 里 RouteTransition 应该放在 Outlet 之前还是之后？",
    options: [
      sc("A", "之后——RouteTransition 用 fixed 定位，DOM 顺序无关；但放后避免误以为是布局元素"),
      sc("B", "之前"),
      sc("C", "无所谓"),
      sc("D", "在 ErrorBoundary 内"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "fixed 定位下顺序不影响视觉，但「全局工具」放最后是清晰约定。" },
    abilityTags: ["code.position.handler"], sourceFilePath: "app/root.tsx", layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q9 dev vs prod 错误显示",
    prompt: "想让 dev 显示完整 stack，prod 显示通用文案。最佳改造？",
    options: [
      sc("A", "RouteErrorBoundary 内 import.meta.env.DEV ? error.stack : '出错了'——构建时 dead code elimination 让 prod bundle 不带 stack 字串"),
      sc("B", "在 root 改"),
      sc("C", "在 entry.server 改"),
      sc("D", "无法实现"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Vite import.meta.env.DEV 是构建时常量，prod build 自动消除分支。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 错误页 SEO",
    prompt: "404 页面要不要给 robots.txt 屏蔽爬虫？",
    options: [
      sc("A", "不需要——HTTP 404 是约定信号，搜索引擎自然不会索引；ErrorBoundary 渲染的 HTML 加 <meta name=\"robots\" content=\"noindex\"> 是双保险"),
      sc("B", "必须 robots.txt 屏蔽"),
      sc("C", "返回 200"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "404 status 已经够，meta noindex 双保险更稳。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 错误页与 theme",
    prompt: "用户开 dark theme 时看到 404，文字 + canvas 颜色应该怎样？",
    options: [
      sc("A", "Tailwind 类 (text-primary-950 dark:text-primary-50) 自动随 html 上的 dark class 切换；canvas 颜色硬编码 hsl(28, 70%, 42%) 在 dark 下不变（暖色对两 theme 都和谐）"),
      sc("B", "永远 light"),
      sc("C", "永远 dark"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "文字靠 Tailwind dark: 自动；canvas 选了 theme 不敏感的颜色。" },
    abilityTags: ["ai.review.architecture", "frontend.state.global"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 错误页的「回家」按钮",
    prompt: "「让龙带你回家」「游回首页」按钮 to=\"/\"。如果想给登录用户回 /dashboard，怎么改？",
    options: [
      sc("A", "用 useRouteLoaderData('root') 拿 root loader 的 session，登录用户 to={user ? '/dashboard' : '/'} ——动态目的地"),
      sc("B", "硬编码 /dashboard"),
      sc("C", "useEffect 跳转"),
      sc("D", "无法实现"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useRouteLoaderData('root') 让 ErrorBoundary 也能消费 root 数据（如果 root loader 没失败）。" },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 错误页内的 hook 限制",
    prompt: "ErrorBoundary 内能用 useLoaderData() 吗？",
    options: [
      sc("A", "不能——loader 失败才进 ErrorBoundary，没数据；用 useRouteLoaderData('root') 拿可能成功的父级 loader 数据"),
      sc("B", "能"),
      sc("C", "永远 undefined"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ErrorBoundary 不在 loader 成功的上下文，hook 行为差。" },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q14 错误页打字机能 SSR",
    prompt: "判断：NotFound404 的打字机效果会在 SSR HTML 里出现完整文字。",
    correctAnswer: { value: false },
    explanation: { short: "错——displayText 初始 useState(\"\")，SSR 渲染输出空字符串；hydration 后 useEffect 启动 setInterval 才开始打字。" },
    abilityTags: ["frontend.effect.useEffect", "bridge.reactRouter.loader"],
    sourceFilePath: "app/components/error/NotFound404.tsx", layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/components/error/NotFound404.tsx"],
  }),
  q({
    type: "single_choice", title: "Q15 重试按钮设计",
    prompt: "想给错误页加「重试」按钮（重新调 loader）。怎么实现？",
    options: [
      sc("A", "用 useRevalidator()，<button onClick={() => revalidator.revalidate()}>——React Router 提供的 hook 重跑当前路由所有 loader"),
      sc("B", "navigate(window.location.href)"),
      sc("C", "window.location.reload()"),
      sc("D", "无法实现"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useRevalidator 是优雅方式——不刷新页面，只重跑 loader。" },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 errorMessage 信息泄露",
    prompt: "errorMessage 显示「Database error: schema 'users' missing column 'role'」——生产泄露什么？",
    options: [
      sc("A", "DB schema 信息（表名 users、列名 role）泄露给攻击者，便于 SQL injection 探测；应该展示通用「服务出错」并把详细 error 上报到内部日志"),
      sc("B", "不泄露"),
      sc("C", "只泄露给登录用户"),
      sc("D", "Cloudflare 自动屏蔽"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "用户看到的错误信息是攻击面——必须脱敏。" },
    abilityTags: ["ai.review.architecture", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 错误页的导航限制",
    prompt: "用户在错误页时，能用 NavLink 导航到其他页吗？",
    options: [
      sc("A", "能——错误页只是替换了路由的渲染输出，Layout 里的 Header/NavLink 还在，导航正常工作"),
      sc("B", "不能"),
      sc("C", "只能用 reload"),
      sc("D", "需要重新登录"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ErrorBoundary 是「在 Layout 内的子树替换」，全局导航不受影响。" },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q18 错误页本身错误",
    prompt: "如果 RouteErrorBoundary 自己渲染时也 throw 错（极端 case），怎么处理？",
    options: [
      sc("A", "React Router 框架内置最简单 fallback（白屏 + Error 字符串）；这是「兜底的兜底」，几乎不可能触发，但确保不死循环"),
      sc("B", "无限循环"),
      sc("C", "白屏"),
      sc("D", "Cloudflare 重定向"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "框架兜底防死循环——这就是为什么 ErrorBoundary 应该写得很「轻」。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "multi_choice", title: "Q19 错误页应该具备",
    prompt: "好的错误页应该包含哪些元素？(多选)",
    options: [
      sc("A", "明确的状态信息（status code 或友好文案）"),
      sc("B", "出口（回家按钮、重试按钮）"),
      sc("C", "保留全站导航（Header）"),
      sc("D", "完整的 stack trace（dev mode）"),
      sc("E", "用户输入的表单数据完整保留"),
    ],
    correctAnswer: { choiceIds: ["A", "B", "C", "D"] },
    explanation: { short: "A/B/C/D 是基本盘；E 不属于错误页职责（属于 Form 库的状态管理）。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 错误页测试",
    prompt: "怎么本地测 RouteErrorBoundary 渲染？",
    options: [
      sc("A", "在某个路由 loader 里临时 throw new Response('test', {status: 500}); 然后访问该路由——boundary 自动接管"),
      sc("B", "改 entry.server"),
      sc("C", "改 root"),
      sc("D", "vitest"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader 临时抛错是最快的本地验证方法。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 错误页与 RouteTransition",
    prompt: "用户在 /messages 触发错误，路径 / → /messages 的幕布会怎样？",
    options: [
      sc("A", "正常完成——RouteTransition 不知道也不关心目标路由是否成功；幕布盖上 → 等 useNavigation idle → 揭开（这时已经渲染错误页）"),
      sc("B", "卡住"),
      sc("C", "永远 leaving"),
      sc("D", "白屏"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "RouteTransition 与 ErrorBoundary 解耦——前者只看导航状态。" },
    abilityTags: ["bridge.reactRouter.loader", "frontend.event.click"],
    sourceFilePath: "app/components/transitions/RouteTransition.tsx", layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/transitions/RouteTransition.tsx"],
  }),
  q({
    type: "single_choice", title: "Q22 整体架构",
    prompt: "项目错误体系的整体架构是？",
    options: [
      sc("A", "1) loader 抛 Response/Error 2) 冒泡到最近 ErrorBoundary（默认 root） 3) root 按 status 分发到 NotFound404 / RouteErrorBoundary 4) 渲染装饰 + 出口 + 错误信息 5) RouteTransition 不感知错误，按导航状态工作 6) entry.server didError 决定 status"),
      sc("B", "全部在 entry.server"),
      sc("C", "全部在 ErrorBoundary"),
      sc("D", "Cloudflare 自动"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "六步分布式 = 各组件各司其职，扩展点清晰。" },
    abilityTags: ["ai.review.architecture", "code.position.handler", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/root.tsx", "app/components/error/NotFound404.tsx", "app/entry.server.tsx", "app/components/transitions/RouteTransition.tsx"],
  }),
];
