/**
 * Real questions for site-05-shell-errors / not-found.
 * Anchor: remix/app/components/error/NotFound404.tsx
 *   - displayText state + 打字机 setInterval(150ms)
 *   - fullText = "你来到了无人之境"
 *   - canvas 像素龙: segmentCount = 35, segmentDistance = 18
 *   - GsapFillLink to="/" 文案 "让龙带你回家"
 *   - rAF animate 循环（无 cancelAnimationFrame cleanup）
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/error/NotFound404.tsx";

const sc = (id: string, text: string) => ({ id, text });

export const notFoundQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 fullText",
    prompt: "组件里 const fullText = \"____ \";",
    options: [], blanks: [{ id: "v", placeholder: "中文", acceptedAnswers: ["你来到了无人之境"] }],
    correctAnswer: { type: "fill_blank", values: { v: "你来到了无人之境" } },
    explanation: { short: "404 文案——故意带「无人」感降低用户挫败感。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank", title: "Q2 打字机间隔",
    prompt: "setInterval(() => { ... }, ____ ) 间隔毫秒？",
    options: [], blanks: [{ id: "v", placeholder: "数字", acceptedAnswers: ["150"] }],
    correctAnswer: { type: "fill_blank", values: { v: "150" } },
    explanation: { short: "150ms 一字——慢到能感受打字、快到不让用户烦。" },
    abilityTags: ["frontend.effect.useEffect"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank", title: "Q3 龙身段数",
    prompt: "const segmentCount = ____, segmentDistance = ____ ;",
    options: [], blanks: [
      { id: "a", placeholder: "数字", acceptedAnswers: ["35"] },
      { id: "b", placeholder: "数字", acceptedAnswers: ["18"] },
    ],
    correctAnswer: { type: "fill_blank", values: { a: "35", b: "18" } },
    explanation: { short: "35 段身、每段间隔 18px——既不卡又有龙的体感。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 GsapFillLink",
    prompt: "组件返回页面用 <GsapFillLink to=\"/\">让龙带你回家</GsapFillLink>。这个 Link 干嘛？",
    options: [
      sc("A", "项目自定义的「悬停时背景渐变填充」按钮 Link，包了 React Router Link"),
      sc("B", "Tailwind 自带组件"),
      sc("C", "GSAP 库自带"),
      sc("D", "原生 a 标签"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "自定义 UI 组件，路径在 ~/components/ui/GsapFillLink。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/ui/GsapFillLink.tsx"],
  }),
  q({
    type: "true_false", title: "Q5 cleanup rAF",
    prompt: "判断：组件 useEffect 注册了 requestAnimationFrame 但没有 cancelAnimationFrame cleanup——存在泄漏风险。",
    correctAnswer: { value: true },
    explanation: { short: "对——真有 leak。卸载后 rAF 还在跑、还在 setState（没 setState 就只是空跑）。代码可改：保存 raf id，cleanup cancelAnimationFrame(id)。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 resize 监听",
    prompt: "useEffect 注册 window.addEventListener(\"resize\", resizeCanvas)。cleanup 是？",
    options: [
      sc("A", "return () => window.removeEventListener(\"resize\", resizeCanvas);"),
      sc("B", "无 cleanup"),
      sc("C", "用 AbortSignal.timeout"),
      sc("D", "useState"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "标准 effect cleanup 模式——removeEventListener。" },
    abilityTags: ["frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 canvasRef 取 ctx",
    prompt: "const ctx = canvas.getContext(\"2d\"); if (!ctx) return; ——为什么 if 守门？",
    options: [
      sc("A", "getContext 在某些场景返回 null（同 canvas 已被取过 webgl 上下文等），TypeScript 类型也是 CanvasRenderingContext2D | null"),
      sc("B", "TypeScript 误报"),
      sc("C", "防止内存泄漏"),
      sc("D", "性能优化"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "类型 + 运行时双层防御。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 dragonSegments 初始化",
    prompt: "for (let i = 0; i < segmentCount; i++) dragonSegments.push({ x, y, angle: 0 });——初始位置？",
    options: [
      sc("A", "让段从画布中心开始向左排列（x = canvas.width/2 - i * segmentDistance），y 都在中线"),
      sc("B", "随机位置"),
      sc("C", "屏幕外"),
      sc("D", "原点"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "整条龙起步在中线水平排列，animate 启动后随路径游动。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 时间变量",
    prompt: "let angle = 0; let time = 0; 在 animate 里 time += 0.01; angle += 0.01; ——它们的角色？",
    options: [
      sc("A", "angle 控龙头绕中心旋转的相位；time 给龙身正弦摆动用——两个 0.01 增量是「每帧极小步进」"),
      sc("B", "都是定时器"),
      sc("C", "都是 React state"),
      sc("D", "都是 prop"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "两个累加变量驱动 sin/cos 让画面动起来。" },
    abilityTags: ["frontend.effect.useEffect"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 龙头 vs 龙尾绘制顺序",
    prompt: "for (let i = segmentCount - 1; i >= 0; i--) 倒序绘制——为什么？",
    options: [
      sc("A", "Canvas 后画的覆盖前画的——倒序保证龙头（i=0）最后画在最上层"),
      sc("B", "性能优化"),
      sc("C", "TypeScript 要求"),
      sc("D", "随机顺序"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "z-order 由绘制顺序决定，头要在最上。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 displayText 显示",
    prompt: "JSX 里 {displayText}<span className=\"animate-pulse\">|</span>——竖杠的作用？",
    options: [
      sc("A", "光标——用 Tailwind 的 animate-pulse 让它闪烁，模拟终端打字"),
      sc("B", "分隔符"),
      sc("C", "进度条"),
      sc("D", "占位符"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "经典打字机效果。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q12 .client 后缀",
    prompt: "判断：组件文件名是 NotFound404.tsx（无 .client 后缀），但用了 canvas/window——SSR 时会报错。",
    correctAnswer: { value: false },
    explanation: { short: "错——所有 window/canvas 调用都在 useEffect 里（仅客户端运行）；SSR 阶段只渲染初始 JSX，不进 effect，安全。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 设 displayText 初始为空",
    prompt: "useState(\"\") 初始空串，第一帧不显示文字——好处？",
    options: [
      sc("A", "等打字机第一次 setInterval tick 才开始显字——SSR 输出 empty + cursor，hydration 后才动起来；如果初始就给完整字符串，打字效果就破了"),
      sc("B", "性能优化"),
      sc("C", "TypeScript 要求"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "初始 empty + 客户端动起来 = 打字效果完整。" },
    abilityTags: ["frontend.state.local"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 displayText 何时停止",
    prompt: "setInterval 在 if (index <= fullText.length) ... else clearInterval(timer)——什么时候 clear？",
    options: [
      sc("A", "index 超过 fullText.length（字符全打完）后下一个 tick clear"),
      sc("B", "组件卸载"),
      sc("C", "永不 clear"),
      sc("D", "用户点击"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "打完即停——再不浪费 setInterval。" },
    abilityTags: ["frontend.effect.useEffect"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q15 setInterval cleanup",
    prompt: "判断：第一个 useEffect 在 cleanup 里 return () => clearInterval(timer)——保证组件卸载时 interval 不会泄漏。",
    correctAnswer: { value: true },
    explanation: { short: "对——这是标准 effect cleanup。" },
    abilityTags: ["frontend.effect.useEffect"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "position_judgement", title: "Q16 NotFound404 该挂哪",
    prompt: "404 组件应该挂在哪？",
    options: [
      sc("A", "root.tsx ErrorBoundary 内 isRouteErrorResponse(error) && error.status === 404 时渲染——React Router 7 没匹配路由会自动抛 404 ErrorResponse"),
      sc("B", "每个路由的 ErrorBoundary"),
      sc("C", "_index.tsx"),
      sc("D", "entry.client.tsx"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "全局兜底——root ErrorBoundary 是单点，按 status 分支显示 404 vs 500 vs 其它。" },
    abilityTags: ["code.position.handler", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q17 视觉风格",
    prompt: "404 用「龙 + 打字机」而不是简单的纯文本「404 Not Found」——为什么？",
    options: [
      sc("A", "个人站差异化——404 是品牌触点；过度悲伤不友好，过度严肃不个性化；龙 + 中文文案是有趣的折中"),
      sc("B", "性能优化"),
      sc("C", "SEO"),
      sc("D", "防爬虫"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "404 体验是个人站的彩蛋点。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 hsl(28, 70%, ...)",
    prompt: "ctx.fillStyle = `hsl(28, 70%, ${42 + index * 0.5}%)`——颜色按段递变，原因？",
    options: [
      sc("A", "尾段比头段亮——给龙身渐变效果，视觉上有动感"),
      sc("B", "性能优化"),
      sc("C", "Tailwind 限制"),
      sc("D", "随机色"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "动态计算颜色，省 CSS 字符串数组。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 龙爪绘制位置",
    prompt: "if (i === 6 || i === 12 || i === 18 || i === 24) drawDragonClaw——四组爪子？",
    options: [
      sc("A", "每隔 6 段画一对爪子，模拟「龙身上有四对爪」——硬编码索引足够"),
      sc("B", "随机"),
      sc("C", "性能优化"),
      sc("D", "TypeScript 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "魔法数字硬编码——这种纯视觉代码不需要抽常量。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 canvas 大小",
    prompt: "resizeCanvas: canvas.width = window.innerWidth; canvas.height = window.innerHeight。为什么不用 CSS 100vw/vh？",
    options: [
      sc("A", "Canvas 的 width/height 属性决定的是画布像素分辨率（drawing buffer），CSS width/height 决定的是显示大小；只 set CSS 会拉伸模糊。两者都要 set 才正确"),
      sc("B", "Tailwind 不支持 vw"),
      sc("C", "性能优化"),
      sc("D", "无差别"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Canvas 的双 size 概念：drawing buffer + CSS。一不一致就糊。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 z-10 与 absolute",
    prompt: "<canvas className=\"absolute inset-0\" /> 和 <div className=\"relative z-10 ...\"> 文字——绝对定位 + z-10？",
    options: [
      sc("A", "canvas 铺满背景（absolute inset-0 + opacity 0.4），文字层 relative + z-10 保证文字在 canvas 之上"),
      sc("B", "性能优化"),
      sc("C", "TypeScript 限制"),
      sc("D", "Tailwind 默认"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "绝对定位画布作背景 + 相对定位文字层在前。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 整体设计哲学",
    prompt: "404 页面用「重 canvas 动画 + 打字机」综合花哨实现，工程上 OK 吗？",
    options: [
      sc("A", "对个人站 OK——404 流量很少，性能浪费可接受；它是品牌触点（被分享时给人留印象）；但商业站应优先「快速 + 朴素」，因为 404 通常意味着用户已经困惑"),
      sc("B", "永远不 OK"),
      sc("C", "永远 OK"),
      sc("D", "取决于浏览器"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "场景决定：个性站 OK，商业站要克制。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
];
