/**
 * Real questions for site-05-shell-errors / root-error-export.
 * Anchor: remix/app/root.tsx 中 export function ErrorBoundary 的部分 (consume RouteErrorBoundary 与 NotFound404)
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/root.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const rootErrorExportQuestions: RealQ[] = [
  q({
    type: "single_choice", title: "Q1 React Router 7 约定",
    prompt: "root.tsx 怎么注册全局 ErrorBoundary？",
    options: [
      sc("A", "export function ErrorBoundary() { ... }——React Router 7 自动消费这个 export"),
      sc("B", "import { ErrorBoundary } from React"),
      sc("C", "把它包成 Provider"),
      sc("D", "在 entry.client 里 register"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "命名约定 export = 框架契约。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 ErrorBoundary 内分支",
    prompt: "ErrorBoundary 内部怎么决定渲染 NotFound404 还是 RouteErrorBoundary？",
    options: [
      sc("A", "isRouteErrorResponse(error) && error.status === 404 → NotFound404；其他 → RouteErrorBoundary"),
      sc("B", "永远 NotFound404"),
      sc("C", "永远 RouteErrorBoundary"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "按 status 分支，404 单独走专用组件。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/components/error/NotFound404.tsx"],
  }),
  q({
    type: "single_choice", title: "Q3 ErrorBoundary 与 Layout",
    prompt: "ErrorBoundary 应该被 Layout（含 html/body）包裹吗？",
    options: [
      sc("A", "应该——错误页要复用全站 html shell（lang/theme/meta/links），错误时 html 结构不能塌；React Router 7 framework 会自动让 ErrorBoundary 走 Layout 渲染"),
      sc("B", "不应该，独立 html"),
      sc("C", "无所谓"),
      sc("D", "Cloudflare 自动处理"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "html 结构必须完整——错误页也是页面。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 useRouteError 在 ErrorBoundary 内",
    prompt: "ErrorBoundary 函数体里用 const error = useRouteError(); 这能拿到？",
    options: [
      sc("A", "本次请求触发 boundary 的错误对象（loader/action 抛的 Response 或组件渲染抛的 Error 等）"),
      sc("B", "全部历史错误"),
      sc("C", "全局 error log"),
      sc("D", "永远 null"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useRouteError 是 ErrorBoundary 专用 hook。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q5 ErrorBoundary 在外层",
    prompt: "判断：root.tsx 的 export ErrorBoundary 是「最外层」错误兜底——任何子路由没自己 export ErrorBoundary 就用它。",
    correctAnswer: { value: true },
    explanation: { short: "对——React Router 7 错误冒泡到最近一层 ErrorBoundary，root 是最后一站。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 isRouteErrorResponse 判定",
    prompt: "isRouteErrorResponse(error) === true 意味着？",
    options: [
      sc("A", "error 是 React Router 抛 Response 时构造的 ErrorResponse 实例（有 status/statusText/data）；区别于业务自己抛的 new Error/throw 1"),
      sc("B", "error 是 Promise"),
      sc("C", "error 是 string"),
      sc("D", "error 是 number"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ErrorResponse 是 React Router 内部类型，throw new Response(...) 抛到 boundary 时被包成它。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 子路由各自 ErrorBoundary",
    prompt: "如果某个 /chat 路由 export 自己的 ErrorBoundary，root 的 ErrorBoundary 还会被调用吗？",
    options: [
      sc("A", "/chat 路由内的错误会先被 chat 自己的 ErrorBoundary 捕获，不冒泡到 root；root 只在 chat boundary 也抛错时才接管"),
      sc("B", "永远 root 接管"),
      sc("C", "永远不冒泡"),
      sc("D", "用户决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ErrorBoundary 嵌套——最近一层先接错。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 返回 5xx vs 200",
    prompt: "ErrorBoundary 渲染时 HTTP status 是？",
    options: [
      sc("A", "由抛错原因决定——loader throw new Response(...)的 status 透回；业务 throw new Error 一般是 500；React Router 框架自动协调"),
      sc("B", "永远 200"),
      sc("C", "永远 500"),
      sc("D", "200 + 后续 setState 改"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "status 由错误对象决定，框架透传。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q9 SSR 错误页",
    prompt: "判断：ErrorBoundary 渲染的错误页支持 SSR。",
    correctAnswer: { value: true },
    explanation: { short: "对——boundary 是 React 组件，SSR + hydration 路径一致。entry.server 的 didError 在 boundary 内 throw 才会翻 true。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/entry.server.tsx"],
  }),
  q({
    type: "single_choice", title: "Q10 渲染 RouteErrorBoundary 还是 NotFound404",
    prompt: "代码可能写法：return isRouteErrorResponse(error) && error.status === 404 ? <NotFound404 /> : <RouteErrorBoundary />。这样写的好处？",
    options: [
      sc("A", "把「错误分发」从 RouteErrorBoundary 抽离到 root——让 NotFound404 和 RouteErrorBoundary 各自专注自己 UI；新增 503/maintenance 页只需在 root 加分支"),
      sc("B", "性能优化"),
      sc("C", "TypeScript 限制"),
      sc("D", "Cloudflare 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "分发逻辑放 root；展示组件保持单一职责。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 ErrorBoundary 与 useLoaderData",
    prompt: "ErrorBoundary 能用 useLoaderData() 拿到 root loader 数据吗？",
    options: [
      sc("A", "不能——loader 都还没成功，没有数据；只能用 useRouteLoaderData('root') 拿可能成功的父级 loader 数据"),
      sc("B", "可以"),
      sc("C", "Cloudflare 自动注入"),
      sc("D", "返回 undefined 但不报错"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ErrorBoundary 在 loader 失败上下文，useLoaderData 不可靠。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 ErrorBoundary 与 theme",
    prompt: "ErrorBoundary 应该尊重当前 theme 吗？",
    options: [
      sc("A", "应该——Layout 已经把 theme class 挂在 html，ErrorBoundary 渲染的 UI 用 Tailwind dark: 自动跟随；不需要 ErrorBoundary 自己读 theme"),
      sc("B", "永远 light theme"),
      sc("C", "随机"),
      sc("D", "TypeScript 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Layout 已处理 theme class，子组件继承样式。" },
    abilityTags: ["frontend.state.global", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 ErrorBoundary 与 Outlet",
    prompt: "ErrorBoundary 内部渲染时还包 <Outlet /> 吗？",
    options: [
      sc("A", "不——Outlet 渲染子路由，错误已经抛了不该再尝试渲染子树；ErrorBoundary 是「替代 Outlet」的渲染分支"),
      sc("B", "包，让用户能看子树"),
      sc("C", "看 status 决定"),
      sc("D", "TypeScript 要求包"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ErrorBoundary 是「分支替代」，Outlet 不该出现。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 子路由不 export ErrorBoundary",
    prompt: "如果 /chat 路由的 loader throw new Error('db down')，没 export 自己 ErrorBoundary。最终展示？",
    options: [
      sc("A", "root 的 ErrorBoundary 接管——非 404，渲染 RouteErrorBoundary（鱼版本），errorMessage = \"db down\"（dev 模式）"),
      sc("B", "白屏"),
      sc("C", "重定向"),
      sc("D", "404"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "默认冒泡到 root；dev 看到具体 message，prod 应改成通用文案。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 throw redirect 不算错误",
    prompt: "loader 用 throw redirect('/login') 不会触发 ErrorBoundary 的原因？",
    options: [
      sc("A", "redirect 是 React Router 用来「中断 loader 链」的特殊抛出，框架内部识别为「跳转指令」而不是错误，直接 302 不进 boundary"),
      sc("B", "redirect 是普通函数调用"),
      sc("C", "redirect 在 ErrorBoundary 内"),
      sc("D", "Cloudflare 拦截"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "redirect 是约定的非错误抛出，框架特殊处理。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 throw json 进 boundary",
    prompt: "loader 用 throw json({ code: 'AUTH_REQUIRED' }, { status: 401 }) 触发 boundary 时？",
    options: [
      sc("A", "走 isRouteErrorResponse 分支——errorMessage 显示「401 Unauthorized」；要拿 data 用 useRouteError() 后 (error as any).data"),
      sc("B", "走 instanceof Error 分支"),
      sc("C", "boundary 不接住"),
      sc("D", "客户端忽略"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "throw json 等价 throw new Response(JSON.stringify(...), { status, headers: ... })，是 ErrorResponse。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 ErrorBoundary 上报",
    prompt: "想给 ErrorBoundary 内的 error 都做 Sentry 上报。最佳位置？",
    options: [
      sc("A", "ErrorBoundary 内 useEffect(() => { reportError(error) }, [error])——hydration 后客户端上报"),
      sc("B", "渲染时直接 reportError"),
      sc("C", "在每个组件里"),
      sc("D", "无法实现"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useEffect 保证只在客户端跑一次（同步上报会让 SSR 报错）。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q18 删 root ErrorBoundary 后果",
    prompt: "判断：删除 root.tsx 的 export ErrorBoundary，整站没错误兜底。",
    correctAnswer: { value: false },
    explanation: { short: "错——React Router 7 在没有 user-defined ErrorBoundary 时用框架内置默认（最简单的「<h1>Error</h1>」级别）；不会白屏，但 UX 难看。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 SSR 错误页 status code",
    prompt: "ErrorBoundary 渲染时 HTTP status 由谁决定？",
    options: [
      sc("A", "loader throw 的 Response 的 status 透传到 entry.server 的 responseStatusCode；entry.server 用 didError ? 500 : responseStatusCode 决策——通常等于错误的 status"),
      sc("B", "永远 200"),
      sc("C", "永远 500"),
      sc("D", "Cloudflare 自定义"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "framework + entry.server 协同决定 status。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/entry.server.tsx"],
  }),
  q({
    type: "single_choice", title: "Q20 ErrorBoundary vs componentDidCatch",
    prompt: "React Router 7 的 ErrorBoundary 和 React 自带的 class componentDidCatch 关系？",
    options: [
      sc("A", "完全独立——React class boundary 只接组件渲染错；React Router boundary 接 loader/action error + 渲染错。两者可共存"),
      sc("B", "等价"),
      sc("C", "React Router boundary 替代 componentDidCatch"),
      sc("D", "React 已废弃 componentDidCatch"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "React boundary 与 React Router boundary 各自工作。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "position_judgement", title: "Q21 加 maintenance 页",
    prompt: "新需求：当 D1 故障时显示 \"系统维护中\" 页面。落点？",
    options: [
      sc("A", "ErrorBoundary 内增加 status === 503 分支渲染 Maintenance 组件——所有 loader 抛 throw new Response('maintenance', {status: 503}) 都进这分支"),
      sc("B", "重写 entry.server"),
      sc("C", "wrangler.toml redirect"),
      sc("D", "客户端 useEffect 跳转"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ErrorBoundary 是「按 status 分发 UI」的中央点。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 整体设计哲学",
    prompt: "「root export ErrorBoundary + 子组件 NotFound404 / RouteErrorBoundary 分离」的设计哲学？",
    options: [
      sc("A", "root 做「分发」（按 status 决定渲染谁），子组件做「展示」（只关心一种状态的 UI）——分发与展示解耦，新加 503/maintenance/etc. 只改 root 不动子组件"),
      sc("B", "纯历史原因"),
      sc("C", "Cloudflare 强制"),
      sc("D", "TypeScript 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "分发 + 展示分离 = 易扩展。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
];
