/**
 * Real questions for site-05-shell-errors / route-transition.
 * Anchor: remix/app/components/transitions/RouteTransition.tsx
 *   - NAVIGATE_EVENT = "route-transition:navigate"
 *   - NAVIGATE_AFTER_MS = 260, MIN_COVER_MS = 430, FADE_OUT_MS = 360
 *   - useLocation, useNavigate, useNavigation
 *   - 导出 default + named navigateWithRouteTransition(to)
 *   - dispatchEvent(new CustomEvent(NAVIGATE_EVENT, { detail: { to } }))
 *   - prefers-reduced-motion: reduce 关闭 transform
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/transitions/RouteTransition.tsx";

export const routeTransitionQuestions: RealQ[] = [
  q({
    type: "fill_blank",
    title: "Q1 自定义事件名",
    prompt: "文件顶部 const NAVIGATE_EVENT = \"____ \";",
    options: [],
    blanks: [{ id: "v", placeholder: "事件名字符串", acceptedAnswers: ["route-transition:navigate"] }],
    correctAnswer: { type: "fill_blank", values: { v: "route-transition:navigate" } },
    explanation: { short: "命名空间前缀 route-transition: 防与其他 CustomEvent 冲突。" },
    abilityTags: ["frontend.event.click"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank",
    title: "Q2 三个时间常量",
    prompt: "三个常量值（毫秒）：NAVIGATE_AFTER_MS = ____, MIN_COVER_MS = ____, FADE_OUT_MS = ____ ",
    options: [],
    blanks: [
      { id: "a", placeholder: "数字", acceptedAnswers: ["260"] },
      { id: "b", placeholder: "数字", acceptedAnswers: ["430"] },
      { id: "c", placeholder: "数字", acceptedAnswers: ["360"] },
    ],
    correctAnswer: { type: "fill_blank", values: { a: "260", b: "430", c: "360" } },
    explanation: { short: "260 = 拉幕后多久才真正 navigate；430 = 幕至少盖多久；360 = 幕淡出多久。" },
    abilityTags: ["frontend.state.local"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q3 三个 router hook",
    prompt: "组件用了 useLocation、useNavigate、useNavigation 三个 hook，分别干什么？",
    options: [
      { id: "A", text: "useLocation 读当前 URL；useNavigate 触发跳转；useNavigation 读「正在跳转」的瞬态状态" },
      { id: "B", text: "useLocation 写 URL；useNavigate 读 URL；useNavigation 是路由表" },
      { id: "C", text: "三者都是 React 自带 hook" },
      { id: "D", text: "三者都从 history 读" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useNavigation 是 React Router 7 提供的瞬态导航状态 hook。" },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q4 三个 timer ref",
    prompt: "navigateTimerRef、revealTimerRef、fadeTimerRef 都用 useRef<number>()，存的是？",
    options: [
      { id: "A", text: "window.setTimeout 返回的 numeric handle，组件卸载或事件触发时 clearTimeout 清掉" },
      { id: "B", text: "存动画时长" },
      { id: "C", text: "存 location.key" },
      { id: "D", text: "存 React 内部 fiber" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三个 setTimeout 的句柄，统一在 clearTimers 里清。" },
    abilityTags: ["frontend.state.local"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q5 三个布尔 state",
    prompt: "useState 维护 visible、active、leaving 三个布尔，分别表示？",
    options: [
      { id: "A", text: "visible=节点是否挂载渲染；active=transform translateY 是否到 0（盖住屏幕）；leaving=是否处于淡出阶段" },
      { id: "B", text: "visible=是否登录；active=路由是否激活；leaving=用户是否离开" },
      { id: "C", text: "三者都是动画进度" },
      { id: "D", text: "都是 Redux state" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三态机驱动 CSS 类名 .active / .leaving 切换。" },
    abilityTags: ["frontend.state.local"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q6 startCover 用 RAF",
    prompt: "startCover 里 setVisible(true) 之后用 window.requestAnimationFrame(() => setActive(true))。为什么不直接 setActive(true)？",
    options: [
      { id: "A", text: "保证 visible=true 那一帧先把节点挂上 transform: translateY(100%)（CSS 起点），下一帧再 .active translateY(0%) 触发 transition——避免无 transition 的瞬移" },
      { id: "B", text: "RAF 性能更好" },
      { id: "C", text: "React 要求" },
      { id: "D", text: "Cloudflare 限制" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "「先挂节点-再切类」是 CSS transition 触发的标准技巧。" },
    abilityTags: ["frontend.effect.useEffect"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q7 finishCover 的延迟计算",
    prompt: "finishCover 里 const revealDelay = Math.max(80, MIN_COVER_MS - elapsed)。为什么要 max(80, ...)？",
    options: [
      { id: "A", text: "保证至少 80ms 让用户看到「盖上」状态——即使 SSR 路由切换很快，也不会让幕一闪而过" },
      { id: "B", text: "性能优化" },
      { id: "C", text: "浏览器最小 setTimeout 间隔" },
      { id: "D", text: "随机抖动" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "下限 80ms 防视觉抖动；上限自动收敛到 MIN_COVER_MS（430）。" },
    abilityTags: ["frontend.effect.useEffect"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q8 命名导出 navigateWithRouteTransition",
    prompt: "文件末尾 export function navigateWithRouteTransition(to)：dispatch CustomEvent 而不是直接 navigate。为什么？",
    options: [
      { id: "A", text: "调用方不需要拿到组件内部 navigate 引用——通过事件桥让任何组件都能「请求一次过渡跳转」，组件再用 addEventListener 接收并触发覆盖动画再 navigate" },
      { id: "B", text: "性能更好" },
      { id: "C", text: "TypeScript 限制" },
      { id: "D", text: "Cloudflare 要求" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "事件总线模式让 RouteTransition 既是「监听者」又是「触发器」。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false",
    title: "Q9 自动监听 useNavigation",
    prompt: "判断：除了 CustomEvent 触发的导航，组件还会监听 useNavigation().state，在框架自身导航（比如 NavLink 点击）时也启动覆盖动画。",
    correctAnswer: { value: true },
    explanation: { short: "对——第二个 useEffect 监听 navigation.state；不是 idle 就 startCover，覆盖框架原生跳转。" },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q10 location.key 防重",
    prompt: "previousKeyRef.current === location.key 判断在做什么？",
    options: [
      { id: "A", text: "去重——React StrictMode 双调 effect 时，两次渲染 key 一样不动；只有 key 真变了才 finishCover" },
      { id: "B", text: "防止 SSR" },
      { id: "C", text: "性能优化" },
      { id: "D", text: "防止内存泄漏" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useEffect 在 StrictMode 双调，要靠 ref 防重做。" },
    abilityTags: ["frontend.state.local"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q11 inline <style>",
    prompt: "组件直接 return `<style>{...CSS...}</style>` 把 CSS 写在 JSX 里。为什么不用 .css 文件？",
    options: [
      { id: "A", text: "组件高度自包含——容易复用、单独删除；少量样式不值得增加 css import 与 build chain；实测有效" },
      { id: "B", text: "Cloudflare 不支持 CSS 文件" },
      { id: "C", text: "TypeScript 限制" },
      { id: "D", text: "性能更好" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "工程权衡：组件级别的 inline style 是合理的封装。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q12 prefers-reduced-motion",
    prompt: "@media (prefers-reduced-motion: reduce) { .route-transition-panel { transform: none; transition: opacity 140ms ease; } } 的意图？",
    options: [
      { id: "A", text: "尊重用户系统设置——开「减少动效」时去掉 transform 滑动，只保留快速 opacity 淡入淡出" },
      { id: "B", text: "性能优化" },
      { id: "C", text: "TypeScript 报错处理" },
      { id: "D", text: "Cloudflare 强制" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "可访问性——前庭功能障碍用户对滑动动画敏感。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank",
    title: "Q13 z-index",
    prompt: ".route-transition-panel { position: fixed; inset: 0; z-index: ____; }——空格里的数字是？",
    options: [],
    blanks: [{ id: "z", placeholder: "数字", acceptedAnswers: ["60"] }],
    correctAnswer: { type: "fill_blank", values: { z: "60" } },
    explanation: { short: "60 — 高于 navbar/常规 modal，低于 toast/Auth modal 这些极重要 UI。" },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q14 pointer-events: none",
    prompt: ".route-transition-panel 设了 pointer-events: none，原因？",
    options: [
      { id: "A", text: "幕布盖在屏幕上时也不能挡住鼠标事件——用户依然能点底层 UI；只用幕布做视觉过渡不应该锁交互" },
      { id: "B", text: "性能优化" },
      { id: "C", text: "TypeScript 要求" },
      { id: "D", text: "防止 CSS 冲突" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "视觉幕布不能阻塞交互——这是一种 progressive enhancement。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q15 aria-hidden",
    prompt: "<div className=... aria-hidden=\"true\">——为什么？",
    options: [
      { id: "A", text: "幕布对屏幕阅读器无意义（纯视觉装饰），明确 aria-hidden 告知 AT 跳过" },
      { id: "B", text: "性能优化" },
      { id: "C", text: "防 SEO 抓取" },
      { id: "D", text: "样式继承需要" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "可访问性约定：装饰元素显式 aria-hidden。" },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false",
    title: "Q16 RouteTransition 是 .client 后缀吗",
    prompt: "判断：组件文件名是 RouteTransition.tsx（无 .client 后缀），但内部使用了 window 全局——能 SSR 吗？",
    correctAnswer: { value: true },
    explanation: { short: "对——window 调用都在 useEffect 里（仅客户端跑）；export default function 自己 return JSX，SSR 时不进入 effect，安全。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q17 卸载时清 timer",
    prompt: "useEffect(() => clearTimers, [clearTimers]) 这一行的作用？",
    options: [
      { id: "A", text: "组件卸载时把所有未触发的 timeout 清掉，避免「卸载后 setState」内存泄漏 + React 警告" },
      { id: "B", text: "性能监控" },
      { id: "C", text: "强制重渲染" },
      { id: "D", text: "TypeScript 必需" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useEffect 返回函数 = 清理函数。这里返回 clearTimers 直接当 cleanup。" },
    abilityTags: ["frontend.effect.useEffect"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q18 navigateTimerRef 的延迟",
    prompt: "navigateTimerRef = setTimeout(() => navigate(to), NAVIGATE_AFTER_MS=260)——为什么不立即 navigate？",
    options: [
      { id: "A", text: "260ms 让幕布动画有时间「盖上」屏幕，再开始真正切换路由——视觉上「先盖再换页」比「换页同时盖」干净" },
      { id: "B", text: "等 React 完成 reconcile" },
      { id: "C", text: "等浏览器空闲" },
      { id: "D", text: "Cloudflare 要求" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "260ms 是动画与跳转的时序协调。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "position_judgement",
    title: "Q19 把 RouteTransition 挂哪",
    prompt: "RouteTransition 应该挂在哪一层？",
    options: [
      { id: "A", text: "root.tsx 的 Layout 内、Outlet 旁——全站只一个实例，所有路由共享" },
      { id: "B", text: "每个页面组件顶部" },
      { id: "C", text: "_index.tsx 内" },
      { id: "D", text: "entry.client.tsx" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "全局单点——Layout 是合适位置。" },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice",
    title: "Q20 if (!visible) return null",
    prompt: "组件 if (!visible) return null。为什么不一直挂 + display: none 切换？",
    options: [
      { id: "A", text: "未发生跳转时完全不挂幕布——节省 DOM 节点 + 不让 .route-transition-panel 的 ::before/::after 一直占内存" },
      { id: "B", text: "TypeScript 报错" },
      { id: "C", text: "React 要求" },
      { id: "D", text: "性能没区别" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "按需挂载减少 DOM 节点，更经济。" },
    abilityTags: ["frontend.state.local"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q21 location.search 与 hash",
    prompt: "handleNavigate 里比较 `${location.pathname}${location.search}${location.hash}` === to——三件套拼接的意图？",
    options: [
      { id: "A", text: "避免重复跳转——如果用户点的链接就是当前页（含 query 和 hash），跳转无意义，省一次幕布动画" },
      { id: "B", text: "性能优化" },
      { id: "C", text: "TypeScript 需要" },
      { id: "D", text: "Cloudflare 要求" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "完整 URL 比对去重。" },
    abilityTags: ["frontend.event.click"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q22 整体设计意图",
    prompt: "整个 RouteTransition 解决的问题是？",
    options: [
      { id: "A", text: "React Router 的客户端跳转默认是「瞬时切换」——视觉上 jarring；幕布过渡让 UX 更顺滑，且统一所有跳转入口（CustomEvent + useNavigation 监听）" },
      { id: "B", text: "防止用户跳转" },
      { id: "C", text: "缓存路由数据" },
      { id: "D", text: "处理鉴权" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "纯 UX 优化——可见的「换页过程」比瞬时切换感觉更稳。" },
    abilityTags: ["ai.review.architecture", "frontend.event.click"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY],
  }),
];
