/**
 * Real questions for site-05-shell-errors / transition-access.
 * Anchor: remix/app/components/transitions/RouteTransition.tsx 中的 prefers-reduced-motion 处理 + canvas/useEffect 内的客户端检测
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/transitions/RouteTransition.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const transitionAccessQuestions: RealQ[] = [
  q({
    type: "single_choice", title: "Q1 prefers-reduced-motion",
    prompt: "@media (prefers-reduced-motion: reduce) 是？",
    options: [
      sc("A", "用户在系统设置开了「减少动效」时浏览器会让这个 CSS @media 命中——网站可据此关掉滑动/缩放等可能引发不适的动画"),
      sc("B", "Tailwind 自定义 query"),
      sc("C", "Cloudflare 提供"),
      sc("D", "TypeScript 类型"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Web 标准 CSS Media Query；Apple/Windows/Linux 系统设置都暴露这一信号。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 reduce 时的 transform",
    prompt: ".route-transition-panel { transform: none; transition: opacity 140ms ease; } @media reduce 时——意图？",
    options: [
      sc("A", "去掉 translateY 滑动，只保留快速 opacity 淡入淡出——尊重用户偏好但保留视觉过渡"),
      sc("B", "完全去掉过渡"),
      sc("C", "性能优化"),
      sc("D", "Tailwind 默认"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "替换为低强度过渡而不是「全无」——可访问性 vs 视觉一致性的折中。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 reduce 与 ::before 的伪元素",
    prompt: ".route-transition-panel::before { transition: none; } 在 reduce 下的意图？",
    options: [
      sc("A", "把伪元素的内部光线/渐变 transition 也关掉——光线移动是视觉「噪音」之一，reduce 时彻底安静"),
      sc("B", "性能优化"),
      sc("C", "Cloudflare 限制"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "细节也要尊重 reduce——::before 的 transition 也要 none。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 leaving 状态在 reduce",
    prompt: ".route-transition-panel.leaving { transform: none; } 在 reduce 下——意图？",
    options: [
      sc("A", "覆盖正常的 translateY(-8%) 上移退场，让幕布原地淡出，不上移"),
      sc("B", "性能优化"),
      sc("C", "TypeScript 要求"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "退场也要不动——彻底无 transform 才算 reduce 友好。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 浏览器 API 检测",
    prompt: "如果想 JS 也判断 reduce，怎么做？",
    options: [
      sc("A", "window.matchMedia('(prefers-reduced-motion: reduce)').matches——同步返回 boolean"),
      sc("B", "navigator.prefersReducedMotion"),
      sc("C", "Cloudflare API"),
      sc("D", "user agent 字符串"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "matchMedia API 让 JS 与 CSS 同步——HomeHero.tsx 里就这样用。" },
    abilityTags: ["ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/home/HomeHero.tsx"],
  }),
  q({
    type: "single_choice", title: "Q6 RouteTransition 应该 JS 检测 reduce 吗",
    prompt: "RouteTransition 组件本身没用 matchMedia 检测 reduce——为什么？",
    options: [
      sc("A", "CSS @media 已经处理了视觉部分（transform/transition）；JS 跟动画进度无关，无需提前知 reduce 偏好；少一处副作用就少一处 bug 源"),
      sc("B", "matchMedia 不可用"),
      sc("C", "TypeScript 不允许"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "CSS 能解的就 CSS 解，避免 JS 重复关心。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q7 reduce 不影响 timer",
    prompt: "判断：reduce 模式下，setTimeout(navigate, NAVIGATE_AFTER_MS=260) 仍会等 260ms。",
    correctAnswer: { value: true },
    explanation: { short: "对——CSS @media 不影响 JS。reduce 下幕布淡入淡出更短（140ms），但 NAVIGATE_AFTER_MS 是 JS 常量，不动。" },
    abilityTags: ["frontend.effect.useEffect"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 reduce 优化建议",
    prompt: "如果想让 reduce 模式下 NAVIGATE_AFTER_MS 也变 0（立即跳转），怎么改？",
    options: [
      sc("A", "useEffect 内 const reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches; 然后 timer = setTimeout(navigate, reduce ? 0 : NAVIGATE_AFTER_MS)"),
      sc("B", "改 NAVIGATE_AFTER_MS 常量"),
      sc("C", "重写 useNavigate"),
      sc("D", "无法改"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "JS 检测 reduce 后给 timer 赋 0——但要权衡：跳转太快用户来不及看「过渡」反而像 bug。" },
    abilityTags: ["ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 aria-hidden 与可访问性",
    prompt: "<div className=... aria-hidden=\"true\"> 的意图？",
    options: [
      sc("A", "屏幕阅读器跳过这个节点——幕布是装饰，不该被 NVDA/VoiceOver 念出来"),
      sc("B", "隐藏节点 in DOM"),
      sc("C", "性能优化"),
      sc("D", "Tailwind 默认"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "aria-hidden 让 AT 跳过——视觉显示但 a11y 树跳过。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 pointer-events: none",
    prompt: ".route-transition-panel { pointer-events: none; }——为什么不用 visibility: hidden？",
    options: [
      sc("A", "幕布在视觉上「在场」（有透明度变化）但不该挡鼠标——pointer-events: none 让点击穿透；visibility: hidden 会让节点视觉消失"),
      sc("B", "性能优化"),
      sc("C", "TypeScript 要求"),
      sc("D", "无差别"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "区别：pointer-events 不影响视觉，visibility 影响。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q11 z-index 影响焦点",
    prompt: "判断：幕布 z-index: 60 + pointer-events: none，能保证用户的焦点（input 等）不被打断。",
    correctAnswer: { value: true },
    explanation: { short: "对——pointer-events: none 让焦点穿透；如果没 set，input 焦点会因为幕布盖在上面失去。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 触摸设备",
    prompt: "幕布在触摸设备上行为？",
    options: [
      sc("A", "和桌面一样——pointer-events: none 不区分鼠标和触摸；幕布不挡触摸"),
      sc("B", "只对触摸有效"),
      sc("C", "只对鼠标有效"),
      sc("D", "TypeScript 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Pointer Events 模型统一鼠标/触摸/笔。" },
    abilityTags: ["frontend.event.click"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 grain 装饰",
    prompt: ".route-transition-panel__grain 用 background-image: linear-gradient(rgba(...) 1px, transparent 1px) ——意图？",
    options: [
      sc("A", "用线性渐变模拟「网格颗粒」纹理——视觉上让幕布不是纯色而有纸张/墨水质感"),
      sc("B", "性能优化"),
      sc("C", "TypeScript 限制"),
      sc("D", "随机抖动"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "CSS-only 颗粒效果——避免引入图像资源。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 grain reduce 表现",
    prompt: "reduce 模式下 grain 是否还显示？",
    options: [
      sc("A", "显示——CSS 没把 grain 在 @media reduce 下隐藏；它是静态视觉，不构成动效不适"),
      sc("B", "永远不显示"),
      sc("C", "动态隐藏"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "静态装饰可以保留——reduce 关心动效，不关心视觉密度。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 transition 时长 reduce vs 默认",
    prompt: "默认 transform 520ms cubic-bezier，reduce 时只 opacity 140ms。区别？",
    options: [
      sc("A", "默认 520ms 给细腻 cubic-bezier 缓动，reduce 用最简 ease 140ms——总时长缩短到 1/4，缓动函数也降级"),
      sc("B", "无区别"),
      sc("C", "reduce 反而更慢"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "时长 + 缓动同时简化；reduce 整体更安静。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 NotFound404 与 reduce",
    prompt: "NotFound404 的 canvas 龙动画在 reduce 下应该停吗？",
    options: [
      sc("A", "应该——目前代码没处理 reduce，是个 a11y 漏洞；改进：useEffect 检测 prefers-reduced-motion 决定要不要启动 animate"),
      sc("B", "已经处理"),
      sc("C", "不需要处理"),
      sc("D", "Cloudflare 自动"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "现状漏掉了——这是改进点。" },
    abilityTags: ["ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: "app/components/error/NotFound404.tsx", layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/error/NotFound404.tsx"],
  }),
  q({
    type: "single_choice", title: "Q17 Hero 的 reduce",
    prompt: "对比 HomeHero.tsx 里 const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches; if (reduceMotion) return; ——它的策略？",
    options: [
      sc("A", "完全跳过 GSAP 动画——reduce 模式下连「字符上飞」都不做；比 RouteTransition 的「降级到淡入」更彻底"),
      sc("B", "速度减半"),
      sc("C", "保留但加 delay"),
      sc("D", "无区别"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Hero 选择「全跳过」，RouteTransition 选择「降级 opacity」——两种合理策略。" },
    abilityTags: ["ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: "app/components/home/HomeHero.tsx", layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/home/HomeHero.tsx"],
  }),
  q({
    type: "single_choice", title: "Q18 a11y 测试方法",
    prompt: "怎么本地测 reduce 模式表现？",
    options: [
      sc("A", "Chrome DevTools → Rendering 面板 → Emulate CSS media feature prefers-reduced-motion: reduce"),
      sc("B", "改系统设置"),
      sc("C", "命令行参数"),
      sc("D", "无法测试"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "DevTools 内置 emulator，比改系统设置方便。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 contrast 也是可访问性",
    prompt: "@media (prefers-contrast: more) 类似 reduce-motion 但是？",
    options: [
      sc("A", "「请提高对比度」——视障用户偏好；可在 CSS 里换更深色背景/文字。当前代码没处理，是潜在改进点"),
      sc("B", "无意义"),
      sc("C", "只对高 dpr 显示器"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "可访问性 query 一族——reduce 是其中之一。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 SSR + reduce",
    prompt: "服务器端 SSR 时能知道用户偏好 reduce 吗？",
    options: [
      sc("A", "不能——CSS @media 是浏览器解析时决定，SSR 渲染同一份 HTML 给所有客户；浏览器自己根据 @media 应用样式"),
      sc("B", "可以读 Sec-CH-Prefers-Reduced-Motion 头"),
      sc("C", "可以读 user-agent"),
      sc("D", "Cloudflare 自动注入"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "理论上 Client Hint Sec-CH-Prefers-Reduced-Motion 存在但浏览器支持有限——主要靠 CSS @media 解决。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q21 prefers-color-scheme 同样模式",
    prompt: "判断：theme 系统也用类似 @media (prefers-color-scheme: dark) 处理深色模式。",
    correctAnswer: { value: true },
    explanation: { short: "对——@media 系列 a11y query 是 Web 标准家族，prefers-color-scheme 是其中之一。" },
    abilityTags: ["ai.review.architecture", "frontend.state.global"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/utils/theme.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q22 整体 a11y 清单",
    prompt: "检查项目动画/UI 的 a11y 覆盖度，应该看什么？",
    options: [
      sc("A", "1) 所有动画在 reduce 下降级或停 2) 装饰元素 aria-hidden 3) 焦点不被遮挡（pointer-events 或 z-index 正确） 4) 错误页能键盘导航 5) 颜色对比度足够（prefers-contrast）"),
      sc("B", "只看 reduce-motion"),
      sc("C", "只看 dark mode"),
      sc("D", "Cloudflare 自动"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "可访问性是清单不是单点。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
];
