/**
 * Real questions for site-10-chat-page / chat-capstone.
 * Anchor: chat.tsx + NemesisChatPage.client.tsx + useNemesisChat.client.ts 综合 —— 改 chat 入口、加新功能落点
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/chat.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const chatCapstoneQuestions: RealQ[] = [
  q({
    type: "single_choice", title: "Q1 chat 全栈分层",
    prompt: "chat 整个功能可以分为几层？",
    options: [
      sc("A", "1) chat.tsx 路由（鉴权 + meta + 渲染入口） 2) NemesisChatPage.client（layout + 解构 hook） 3) useNemesisChat hook（状态 + handler） 4) 4 个子组件（UI 细节） 5) services/nemesis-auth.server（鉴权辅助）——五层"),
      sc("B", "一层"),
      sc("C", "两层"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "五层分工：路由/外壳/状态/UI/服务——分而治之的清晰示范。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/components/nemesis/chat/NemesisChatPage.client.tsx", "app/hooks/useNemesisChat.client.ts", "app/services/nemesis-auth.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q2 加文件上传",
    prompt: "想给 chat 加「上传图片到对话」功能。落点？",
    options: [
      sc("A", "1) Composer 加 <input type=file>+UI 2) hook 加 attachedFile state 3) sendMessage 时 FormData 提交 + 加 attachment 字段 4) 服务端 /api/nemesis 处理 multipart 5) 消息类型加 type:'image' 渲染——5 处一气改通"),
      sc("B", "改 root"),
      sc("C", "改 Header"),
      sc("D", "改 wrangler"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "新功能 = 多层协调：UI + 状态 + 网络 + 后端 + 渲染。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/hooks/useNemesisChat.client.ts", "app/components/nemesis/chat/NemesisChatComposer.tsx", "app/routes/api.nemesis.ts"],
  }),
  q({
    type: "single_choice", title: "Q3 改鉴权方式",
    prompt: "想从「跳 /auth 登录」改成「弹窗内联登录」。落点？",
    options: [
      sc("A", "loader 内 catch 不再 throw redirect，改 return json({ requiresAuth: true })；前端 ChatRoute 判 data.requiresAuth → 渲染 <NemesisChatPage /> 时套 LoginGate；fetcher.submit 内联登录；revalidate 后状态切；UX 更顺"),
      sc("B", "改 wrangler"),
      sc("C", "改 root"),
      sc("D", "改 nemesis-auth"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "auth 策略切换 = loader 返多状态 + 前端按状态分支渲染。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/services/nemesis-auth.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q4 加聊天历史云同步",
    prompt: "把聊天历史从 localStorage 改到 D1 同步。改动？",
    options: [
      sc("A", "1) 加 chat_sessions 表 + migration 2) loader 拉用户 sessions 3) hook 改 saveNemesisChatSessions 调 fetcher.submit /api/chat-sessions 持久化 4) 跨设备打开自动同步——4 处协调改"),
      sc("B", "永远本地"),
      sc("C", "改 wrangler"),
      sc("D", "改 root"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "存储升级 = D1 + loader 拉 + action 写——典型迁移模式。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/hooks/useNemesisChat.client.ts", "migrations/"],
  }),
  q({
    type: "single_choice", title: "Q5 加 SSE 流式回复",
    prompt: "想从「整段返回」改成「字符流 SSE」。落点？",
    options: [
      sc("A", "1) /api/nemesis 后端用 ReadableStream 输出 SSE chunks 2) hook 内用 EventSource 或 fetch + reader.read() 读流 3) 边读边 setMessages 拼 4) UI 自动重渲染显示「打字效果」——服务端 + 客户端协同"),
      sc("B", "改 root"),
      sc("C", "改 wrangler"),
      sc("D", "改 Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SSE 流式 = 服务端流 + 客户端读流 + 拼 state——经典异步 UX 升级。" },
    abilityTags: ["ai.review.architecture", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/hooks/useNemesisChat.client.ts", "app/routes/api.nemesis.ts"],
  }),
  q({
    type: "single_choice", title: "Q6 速率限制接入",
    prompt: "防止用户狂发垃圾消息——速率限制落点？",
    options: [
      sc("A", "1) /api/nemesis 服务端用 Durable Object 速率限制（如「每用户每分钟 5 条」） 2) 超限返 429 + retry-after 3) 前端 hook 接 429 后 setError 显示 4) UI 显示倒计时—— 前后端协同"),
      sc("B", "改 wrangler"),
      sc("C", "改 root"),
      sc("D", "改 chat.tsx"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "速率限制 = 服务端 DO + 客户端友好显示——前后端配合。" },
    abilityTags: ["backend.rateLimit", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/lib/rate-limit.server.ts", "app/lib/rate-limiter-do.ts"],
  }),
  q({
    type: "single_choice", title: "Q7 改聊天数据形态",
    prompt: "Message 类型从 { id, role, content } 改为 { id, role, content, attachments[] }——影响范围？",
    options: [
      sc("A", "1) types/ 内 Message 接口改 2) hook 内 setMessages 处理 attachments 3) MessageList 渲染遍历 attachments 4) Composer 提交时构造 attachments 5) 服务端持久化字段——五处协调改"),
      sc("B", "一处"),
      sc("C", "TypeScript 强制"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "数据形态变更 = 全栈协调；类型先行确保不漏。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/hooks/useNemesisChat.client.ts", "app/types/"],
  }),
  q({
    type: "single_choice", title: "Q8 拆 hook 减少重渲染",
    prompt: "用户反馈「输入时整个 chat 都卡」——优化方向？",
    options: [
      sc("A", "1) inputMessage 单独 hook（useState + setInputMessage）让父不持有 → 不影响 messages list 2) 子组件 React.memo 隔离 3) MessageList 与 Composer 分别拿不同 hook——细化状态拥有权"),
      sc("B", "永远集中"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "重渲染优化 = 拆细 state 拥有权 + memo 隔离——React 性能基本功。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY, "app/hooks/useNemesisChat.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q9 错误监控加 Sentry",
    prompt: "想让 chat 发送失败自动上报 Sentry。落点？",
    options: [
      sc("A", "1) sendMessage 内 try/catch + sentryCapture 2) loader catch 也加 capture 3) ErrorBoundary 加 onError 上报；三层兜底——客户端 + 服务端 + 边界"),
      sc("B", "永远 client"),
      sc("C", "永远 server"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三层错误捕获 = 全方位可观测——监控覆盖率高。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 SEO 升级",
    prompt: "想让 chat 页 og:image 动态显示用户当前对话标题。落点？",
    options: [
      sc("A", "MetaFunction({ data }) 内基于 loader 返的 user.activeSessionTitle 拼接 og:image URL（指向动态生成卡片图的服务）；vs 静态预生成卡片图"),
      sc("B", "永远静态"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "动态 og:image = 接 loader 数据；分享卡片个性化。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/utils/seo.ts"],
  }),
  q({
    type: "single_choice", title: "Q11 多模型切换",
    prompt: "想让用户切「GPT-4 / Claude / Gemini」三个模型。落点？",
    options: [
      sc("A", "1) hook 加 selectedModel state 2) Composer 加下拉选择器 3) sendMessage 带 model 字段提交 4) 服务端 /api/nemesis 按 model 路由到不同 AI 服务 5) 持久化 selectedModel 到 localStorage——5 处改"),
      sc("B", "改 wrangler"),
      sc("C", "改 Cloudflare"),
      sc("D", "改 chat.tsx"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "多模型切换 = 状态 + UI + 网络 + 后端路由 + 持久化协同。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/hooks/useNemesisChat.client.ts", "app/routes/api.nemesis.ts"],
  }),
  q({
    type: "single_choice", title: "Q12 测试策略",
    prompt: "想给 chat 加单测。优先级？",
    options: [
      sc("A", "1) hook（useNemesisChat）单测：状态机逻辑、错误处理、reducer 类（react-hooks 库） 2) 子组件快照测试 3) e2e 完整流（playwright）——金字塔层次"),
      sc("B", "永远 e2e"),
      sc("C", "永远单测"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "测试金字塔：hook（多）→ 组件（中）→ e2e（少）——平衡覆盖与速度。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 TypeScript 严格化",
    prompt: "想让 hook 返的 controller 类型自动推回外层组件。落点？",
    options: [
      sc("A", "useNemesisChat 文件已有 export type NemesisChatController = ReturnType<typeof useNemesisChat>；改 hook 字段时 NemesisChatController 自动更新；外层 destructure 类型受 protected"),
      sc("B", "手写 interface"),
      sc("C", "any"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ReturnType<typeof fn> = 类型从 hook 推；改一处类型自动同步。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: "app/hooks/useNemesisChat.client.ts", layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/hooks/useNemesisChat.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q14 国际化 i18n",
    prompt: "想让 chat 支持英文界面。落点？",
    options: [
      sc("A", "1) 子组件文案抽出到 i18n key 2) loader 按 cookie 取 locale 3) MetaFunction 按 locale 切 title/description 4) 子组件接 t(key) 工具—— 多处协调；从「文案外置」开始"),
      sc("B", "永远中文"),
      sc("C", "改 root"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "i18n = 文案外置 + locale 路由 + meta 切换；多文件协调改造。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 离线模式",
    prompt: "想让网络断时显示「离线 - 请重新连接」。落点？",
    options: [
      sc("A", "1) hook 加 useEffect 监听 navigator.onLine + window 'online'/'offline' 事件 → setIsOffline 2) UI 渲染 banner 3) Composer 在 offline 时禁用 send——客户端检测 + UI 反馈"),
      sc("B", "Cloudflare 检测"),
      sc("C", "服务端"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "navigator.onLine + 事件监听 = 离线检测的标准做法。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY, "app/hooks/useNemesisChat.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q16 数据隐私防泄漏",
    prompt: "「Chat 页 SSR 不能让任何用户消息泄露给搜索引擎」——技术实现？",
    options: [
      sc("A", "loader return json(null) 不返用户数据；.client 子组件 SSR 不渲染消息内容；搜索引擎抓取 chat HTML 只看到空 layout；隐私自然保护"),
      sc("B", "永远 noindex"),
      sc("C", "Cloudflare 拦截"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "本架构天然隔离 SSR 与用户数据 = 隐私优先设计。" },
    abilityTags: ["ai.review.architecture", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 减少首屏 JS 体积",
    prompt: "用户首次进 chat 页加载慢——优化方向？",
    options: [
      sc("A", "1) lazy import 4 个子组件（Suspense + skeleton） 2) 主 NemesisChatPage 也包 lazy 3) 字体子集 / 不必要 polyfill 减包 4) bundle 分析找体积大头 5) Cloudflare 自动 br 压缩——多管齐下"),
      sc("B", "Cloudflare 决定"),
      sc("C", "永远慢"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "首屏优化 = lazy 拆 chunk + 包体分析 + 压缩——综合手段。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q18 完整新功能落地",
    prompt: "加「点赞消息」功能 7 步？",
    options: [
      sc("s1", "1. types/ Message 加 likes: number 字段"),
      sc("s2", "2. migration 加 message_likes 表"),
      sc("s3", "3. hook 加 likeMessage handler 调 fetcher.submit /api/messages/:id/like"),
      sc("s4", "4. /api/messages.like 路由 action 写库 + 返新计数"),
      sc("s5", "5. MessageList 渲染 likes 数 + onLikeClick"),
      sc("s6", "6. typecheck 全过"),
      sc("s7", "7. 部署 + 远程 D1 migrate"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7"] },
    explanation: { short: "新功能落地 7 步：类型 + 表 + 状态 + API + UI + 验证 + 部署。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/hooks/useNemesisChat.client.ts", "app/types/", "migrations/"],
  }),
  q({
    type: "single_choice", title: "Q19 chat 与 Nemesis API 边界",
    prompt: "chat.tsx 与 /api/nemesis.ts 的关系？",
    options: [
      sc("A", "chat.tsx 仅鉴权 + 渲染入口；不调 AI 服务；hook 内 sendMessage 才 fetcher.submit /api/nemesis；AI 调用集中到 /api/nemesis 服务端 action——前后端职责分明"),
      sc("B", "chat 调 AI"),
      sc("C", "客户端调 AI"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "chat 仅入口；AI 调用收敛到 /api/nemesis——分层清晰。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/api.nemesis.ts"],
  }),
  q({
    type: "single_choice", title: "Q20 Cloudflare AI Gateway 接入",
    prompt: "想用 Cloudflare AI Gateway 监控 chat AI 调用。落点？",
    options: [
      sc("A", "/api/nemesis.ts action 内把 fetch URL 从直接 OpenAI 改为 https://gateway.ai.cloudflare.com/.../openai/...；header 加 cf-aig-* 字段；其他不变；改一处全部 chat AI 流量过 Gateway"),
      sc("B", "改前端"),
      sc("C", "改 wrangler"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "AI Gateway 接入 = URL 替换 + 几个 header；架构清晰则改动小。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: "app/routes/api.nemesis.ts", layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/routes/api.nemesis.ts"],
  }),
  q({
    type: "single_choice", title: "Q21 容错重试",
    prompt: "AI 服务返 503 偶发——前端表现？",
    options: [
      sc("A", "hook 内 sendMessage catch 503 → setError + 不立即提示用户重试；可加自动重试 1-2 次（exponential backoff）；UI 显示「上游模型暂忙」（项目已有 DEFAULT_ERROR_MESSAGE）"),
      sc("B", "永远报错"),
      sc("C", "永远重试"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "容错策略 = 友好提示 + 自动重试——平衡 UX 与不打扰。" },
    abilityTags: ["ai.review.architecture", "frontend.state.local"],
    sourceFilePath: "app/hooks/useNemesisChat.client.ts", layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/hooks/useNemesisChat.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q22 整体演进路线图",
    prompt: "chat 功能从 v1 到 v3 的演进顺序？",
    options: [
      sc("A", "v1: 基础 chat（本架构 ✓） → v2: SSE 流式 + D1 历史 → v3: 多模型 + 文件上传 + 团队协作；每步保持「分层不破」前提下增量；架构稳则迭代快"),
      sc("B", "随机重写"),
      sc("C", "永远 v1"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "好架构支持迭代——分层 + 类型推导 + hook 解耦让升级稳定。" },
    abilityTags: ["ai.review.architecture", "code.position.handler", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/hooks/useNemesisChat.client.ts", "app/components/nemesis/chat/NemesisChatPage.client.tsx", "app/routes/api.nemesis.ts"],
  }),
];
