/**
 * Real questions for site-10-chat-page / chat-layout.
 * Anchor: remix/app/components/nemesis/chat/NemesisChatPage.client.tsx 的 layout 结构 —— sidebar + main + composer 响应式
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/nemesis/chat/NemesisChatPage.client.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const chatLayoutQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 容器视口高",
    prompt: '<div className="flex ____ flex-col ...">',
    options: [],
    blanks: [{ id: "v", placeholder: "高度类", acceptedAnswers: ["h-screen"] }],
    correctAnswer: { type: "fill_blank", values: { v: "h-screen" } },
    explanation: { short: "h-screen = height: 100vh = 占满整个视口；chat 全屏布局必备。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 flex-col vs md:flex-row",
    prompt: "flex-col + md:flex-row 的响应式策略？",
    options: [
      sc("A", "移动端竖排（sidebar 上方占顶部 + main 下方占主体）；md（≥768px）切横排（sidebar 左 + main 右）；适配触屏 + 桌面两种交互"),
      sc("B", "永远横排"),
      sc("C", "永远竖排"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Tailwind 响应式 = 按断点切布局；移动竖、桌面横。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 overflow-hidden 容器",
    prompt: "<div className='flex h-screen flex-col overflow-hidden'>——overflow-hidden 用途？",
    options: [
      sc("A", "防止整个容器（含 sidebar + main）超出 100vh 后整页滚动；只让内部子项（消息列表）独立滚动；典型 app shell 布局"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "外层 overflow-hidden + 内层独立 overflow-y-auto = 经典 app shell 滚动模型。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 main flex-1 min-h-0",
    prompt: "<main className='flex min-h-0 flex-1 flex-col'>——min-h-0 解决什么？",
    options: [
      sc("A", "flex 子项默认 min-height: auto，不允许收缩到比内容小；min-h-0 允许收缩；这样内部消息列表才能正确 overflow-y: auto；不加则消息列表撑大父容器导致整页滚动"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "flex 滚动陷阱：嵌套滚动容器的子项要加 min-h-0——常见坑。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 flex-1 含义",
    prompt: "main 上的 flex-1（main 占用剩余空间）——精确含义？",
    options: [
      sc("A", "flex: 1 1 0% = 在 flex 容器内占用所有剩余空间；vs flex-auto（1 1 auto）保留内容尺寸最小宽；flex-1 适合「sidebar 固定 + main 撑满」"),
      sc("B", "永远 100%"),
      sc("C", "1px"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "flex-1 = 1 1 0% = 完全占据剩余空间；常用于主内容区。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 内层 max-w-5xl",
    prompt: "<div className='mx-auto flex min-h-0 w-full max-w-5xl flex-1 flex-col px-3 py-4 md:px-6 md:py-6'>——为什么再嵌套 max-w-5xl？",
    options: [
      sc("A", "main 占满后内容仍然居中限宽 1024px——超大屏幕上消息不横铺过宽；mx-auto 居中；px/py 移动 vs 桌面留边——多层嵌套是为了「填充背景但内容居中」"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "外满背景 + 内居中限宽 = chat 布局的双层模式。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 px-3 vs md:px-6",
    prompt: "px-3 py-4 md:px-6 md:py-6——两套 padding？",
    options: [
      sc("A", "移动端紧凑（12px / 16px）省空间；md 桌面松弛（24px）增加视觉留白；按设备不同密度切换；细节体验"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "响应式 padding = 设备密度自适应——细节优雅。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 NemesisChatHeader 位置",
    prompt: "main 内 Header 在最顶部——为什么不在最外层？",
    options: [
      sc("A", "全站 layout Header 在 root 已经有；这里 NemesisChatHeader 是 chat 专属（如显示当前对话标题、隐私按钮）；嵌套在 main 内只覆盖 chat 区域；功能不同"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "全站 Header vs 页内 Header 是两层；嵌套位置看作用域。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/nemesis/chat/NemesisChatHeader.tsx"],
  }),
  q({
    type: "single_choice", title: "Q9 Sidebar 在 main 之外",
    prompt: "<NemesisChatSidebar /> 在 main 同级而非内嵌——为什么？",
    options: [
      sc("A", "Sidebar 是 chat 全屏布局的「左/上栏」与 main 同级；嵌入 main 会让 sidebar 跟随 main 的限宽 mx-auto，但 sidebar 应该贴边；同级 = 横向独立"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Sidebar 与 main 同级 = 各自独立 layout；DOM 嵌套对应布局意图。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 MessageList 与 Composer 同级",
    prompt: "MessageList + Composer 在 max-w-5xl 内同级 div——layout 含义？",
    options: [
      sc("A", "MessageList flex-1（占主体可滚动） + Composer 固定底部（auto 自然高）；vs Composer 用 absolute 容易被 flex 影响；同级 + flex-col 自然实现「上消息流 + 下输入栏」"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "flex-col + flex-1 在 list = 占主体；Composer 自然底——无需 absolute。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 移动端 sidebar 体验",
    prompt: "移动端 flex-col 时 sidebar 在 main 上方；如果 sidebar 大量会议被压缩到上方很矮——怎么办？",
    options: [
      sc("A", "实际 NemesisChatSidebar 内部应有「移动端折叠/抽屉」逻辑（hamburger 按钮 + overlay）；本组件 layout 只决定栅格大方向；细化交互在 sub component 内"),
      sc("B", "永远横排"),
      sc("C", "永远紧凑"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "外层粗布局 + 内层精交互——分层职责。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/nemesis/chat/NemesisChatSidebar.tsx"],
  }),
  q({
    type: "single_choice", title: "Q12 bg-primary-50 双层",
    prompt: "外层 + main 都 bg-primary-50——重复？",
    options: [
      sc("A", "外层 bg 给整屏背景兜底；main bg 是为了 sidebar 收起时 main 区仍纯净（防止透明出现外层 bg 拼接缝）；双层都设 = 视觉一致兜底"),
      sc("B", "完全重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "嵌套 bg = 防止透明出现底层不一致——视觉细节。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 text-primary-950",
    prompt: "外层 className 含 text-primary-950——含义？",
    options: [
      sc("A", "Tailwind 自定义色：primary-950 是项目色板的最深色（用于深色文本）；继承到子组件不必每个再写；text 颜色一处统一"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Tailwind 色板 + 顶层 text-color 继承 = 全屏统一文本色。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 chat 全屏 vs Header 全站",
    prompt: "chat 页用 h-screen 让整屏被 chat 占；Header（全站）会显示吗？",
    options: [
      sc("A", "若 root 在 Outlet 外渲染 Header；那么 chat 页 h-screen 占整屏会让 Header 在外面或被 chat 顶头；通常 chat/全屏页会在 root 设条件渲染 Header（hide on /chat）；layout 与全站 Header 的协调"),
      sc("B", "永远显示"),
      sc("C", "永远不显"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "全屏页 vs 全站 Header 协调 = layout 设计的常见决策。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q15 加底部状态栏",
    prompt: "想在 Composer 下加一行「状态栏」（如 token 用量）。落点？",
    options: [
      sc("A", "max-w-5xl 容器内 Composer 之后追加 <NemesisStatusBar />；同级 flex-col 自然顶到底；vs 套到 Composer 内职责混乱"),
      sc("B", "改 root"),
      sc("C", "改 layout 外层"),
      sc("D", "新建路由"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "新模块在合适层级追加 + flex 自然布局——增量迭代。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 max-w 调整",
    prompt: "想让消息区更宽——max-w-5xl 改 max-w-7xl？",
    options: [
      sc("A", "可以——5xl ≈ 1024px → 7xl ≈ 1280px；视觉变宽、行长变多；小心阅读舒适宽度（45-75 字符）；vs 直接去掉限宽撑满 = 大屏阅读痛苦"),
      sc("B", "随便"),
      sc("C", "永远不改"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "max-w 调整 = 阅读宽度权衡；不能完全撑满。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 SSR 输出 layout",
    prompt: "SSR 时 NemesisChatPage 不渲染（.client）——layout HTML 在哪？",
    options: [
      sc("A", "在 chat.tsx route 默认导出函数内；Remix SSR 渲染 <ChatRoute /> = <NemesisChatPage />；但 .client 跳过 → 这层 layout 也不在 SSR；client 端 hydrate 后才出现整套布局"),
      sc("B", "永远 SSR"),
      sc("C", "永远 client"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".client 文件层级布局也跳 SSR——取决于该组件是否拆出非 .client 部分。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/chat.tsx"],
  }),
  q({
    type: "single_choice", title: "Q18 a11y 跳过链接",
    prompt: "想给 chat 页加键盘 a11y「跳到主内容」。落点？",
    options: [
      sc("A", "外层最顶加 <a href='#chat-main' className='sr-only focus:not-sr-only'>跳到主内容</a>；main 加 id='chat-main'；标准 a11y 模式"),
      sc("B", "改 root"),
      sc("C", "改 Header"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "skip link = 键盘 a11y 标配——sr-only + focus:not-sr-only 模式。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q19 用户输入消息全流",
    prompt: "用户输入消息按 Enter 发送的 layout 影响？",
    options: [
      sc("s1", "1. Composer textarea 接收输入"),
      sc("s2", "2. Enter 触发 onEnter（hook 内 handleEnter）"),
      sc("s3", "3. void chat.sendMessage() 异步开始"),
      sc("s4", "4. messages 数组追加用户消息 → MessageList 重渲染"),
      sc("s5", "5. useEffect[messages.length] 触发 scrollToBottom 滚到最新"),
      sc("s6", "6. AI 回复进入 typing 状态 → 字符流逐步写入"),
      sc("s7", "7. min-h-0 + flex-1 确保 MessageList 滚动而非整页滚"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7"] },
    explanation: { short: "layout 配合 hook 状态 = 消息流自然滚动；min-h-0 是关键。" },
    abilityTags: ["frontend.event.click", "frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/hooks/useNemesisChat.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q20 视频/图片消息布局",
    prompt: "若消息内嵌视频/大图——layout 影响？",
    options: [
      sc("A", "MessageList 内子项需 max-w-full + height: auto；超长内容靠垂直滚动；max-w-5xl 父级保证不横溢；img loading='lazy' 防顶部大图阻塞首屏"),
      sc("B", "破坏布局"),
      sc("C", "永远报错"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "媒体消息布局 = max-w 限宽 + 自适应高度 + lazy 加载——三件套。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 设计 token 与色板",
    prompt: "为什么用 bg-primary-50 而非 bg-white？",
    options: [
      sc("A", "项目色板：primary-50 是「品牌主色的极浅版本」（带轻微暖色调）；vs 纯 bg-white 太冷；通过色板让全站视觉一致；改色板一处全更新"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "色板 = 设计 token；改一处全站统一。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "tailwind.config.ts"],
  }),
  q({
    type: "single_choice", title: "Q22 整体 layout 哲学",
    prompt: "NemesisChatPage layout 整体哲学？",
    options: [
      sc("A", "1) h-screen 占满视口 2) flex-col + md:flex-row 响应式切方向 3) overflow-hidden 防整页滚 4) min-h-0 解 flex 滚动陷阱 5) max-w-5xl 居中限宽阅读舒适 6) px/py 响应式留边 7) 双层 bg 防视觉拼缝 8) sub-component 同级避嵌套耦合——综合：全屏 chat layout 的范式"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "八条原则——全屏 chat 应用的 layout 标准模式。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY, "tailwind.config.ts"],
  }),
];
