/**
 * Real questions for site-10-chat-page / chat-route.
 * Anchor: remix/app/routes/chat.tsx —— 5 import + loader try/catch redirect 模式 + 默认导出 NemesisChatPage
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/chat.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const chatRouteQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 文件路径",
    prompt: "聊天页路由文件路径：app/____/chat.tsx",
    options: [],
    blanks: [{ id: "v", placeholder: "目录", acceptedAnswers: ["routes"] }],
    correctAnswer: { type: "fill_blank", values: { v: "routes" } },
    explanation: { short: "Remix 路由约定 = app/routes/<name>.tsx 自动映射 /name 路径。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 .client 后缀 import",
    prompt: "import NemesisChatPage from '~/components/nemesis/chat/NemesisChatPage.client';——.client 后缀的作用？",
    options: [
      sc("A", "Remix 编译时识别 .client 后缀文件——只打包到客户端 bundle，不进 Worker SSR；这样组件内的浏览器 API（localStorage/SSE）不会让 SSR 报错"),
      sc("B", "TypeScript 类型"),
      sc("C", "随机"),
      sc("D", "Cloudflare 强制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".client 后缀 = 强制客户端打包；浏览器 API 隔离 SSR。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/nemesis/chat/NemesisChatPage.client.tsx"],
  }),
  q({
    type: "single_choice", title: "Q3 默认导出函数",
    prompt: "export default function ChatRoute() { return <NemesisChatPage />; }——为什么这么薄？",
    options: [
      sc("A", "路由文件只负责 loader/meta/headers + 渲染入口；UI 全在 NemesisChatPage.client 内；分层让路由文件聚焦「服务端逻辑 + SSR 渲染入口」"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "路由薄层 = 关注点分离；UI 复杂度推到 component。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 requireNemesisUser",
    prompt: "loader 内 await requireNemesisUser(request);——这个 helper 做什么？",
    options: [
      sc("A", "服务端检查 session：有效 user → 返回 user 对象继续；无效 → throw new Response(null, { status: 401 })；强制登录守门"),
      sc("B", "只查 cookie"),
      sc("C", "TypeScript 类型"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "throw Response 是 Remix 守门的标准模式——让外层 catch 处理。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/services/nemesis-auth.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q5 try/catch 拦截 401",
    prompt: "try { await requireNemesisUser(request); } catch (error) { if (error instanceof Response && error.status === 401) { throw redirect(...) } throw error; }——意图？",
    options: [
      sc("A", "401 → 转 redirect 去登录页（带 returnTo 参数）；其他错（如 500） throw error 让 ErrorBoundary 处理；区分「未登录 vs 系统故障」"),
      sc("B", "永远 redirect"),
      sc("C", "永远 throw"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "401 = 用户问题（要登录）；500 = 系统问题（要错误页）——区分对待。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/services/nemesis-auth.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q6 returnTo 参数",
    prompt: "throw redirect(`/auth?returnTo=${encodeURIComponent(url.pathname + url.search)}`);——returnTo 的作用？",
    options: [
      sc("A", "登录后回到原页面（如用户访问 /chat 被踢到 /auth，登录成功后从 returnTo 拿到 /chat 重定向回去）；保持用户路径不丢失"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "returnTo 是登录流标配——避免登录后被甩到首页。" },
    abilityTags: ["bridge.reactRouter.loader", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/routes/auth.tsx"],
  }),
  q({
    type: "single_choice", title: "Q7 encodeURIComponent",
    prompt: "encodeURIComponent(url.pathname + url.search)——encode 必要？",
    options: [
      sc("A", "必要——pathname + search 可能含 `?`、`&`、中文等特殊字符；不 encode 会破坏 redirect URL 的 query 解析；encode 是 URL 拼接铁律"),
      sc("B", "可省"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "URL 嵌套 query 必须 encode——否则解析错乱。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 throw error 第二条",
    prompt: "} else { throw error; }——为什么不 swallow 错误？",
    options: [
      sc("A", "不能吞掉非预期错误——swallow 后用户看到空白页且无错误线索；throw 让 ErrorBoundary 捕获显示友好错误页 + 监控可上报；可观测性铁律"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "无意义的 swallow 是反模式——throw 让上层处理。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 return json(null)",
    prompt: "return json(null, { headers: ... });——loader 不返回数据？",
    options: [
      sc("A", "确实——chat 页所有数据都在 client 端 hook（useNemesisChat）从 localStorage 拉；loader 只做「鉴权 + 设置缓存头」；返 null 也合法"),
      sc("B", "永远要返 data"),
      sc("C", "TypeScript 限制"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader 可以只做副作用（鉴权 + headers）；返 null 完全合法。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank", title: "Q10 Cache-Control",
    prompt: 'Cache-Control: "____ , no-store"',
    options: [],
    blanks: [{ id: "v", placeholder: "scope", acceptedAnswers: ["private"] }],
    correctAnswer: { type: "fill_blank", values: { v: "private" } },
    explanation: { short: "私聊页 = private no-store；CDN 不缓存 + 浏览器不缓存；用户隔离。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 Vary: Accept-Encoding",
    prompt: "headers: { 'Vary': 'Accept-Encoding' }——意图？",
    options: [
      sc("A", "缓存 key 也要按 Accept-Encoding 区分——不同浏览器接受的压缩算法（gzip/br）不同；不 Vary 会发错压缩格式；CDN 行为正确性"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Vary: Accept-Encoding 是缓存正确性铁律——压缩与缓存共存的关键。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 forwardLoaderCacheControl",
    prompt: "export const headers: HeadersFunction = forwardLoaderCacheControl;——必要？",
    options: [
      sc("A", "必要——v3_singleFetch 模式下 loader headers 默认不进 document Response；显式 forward 才让 Cache-Control + Vary 生效"),
      sc("B", "可省"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "v3_singleFetch + headers = 必加 forwardLoaderCacheControl。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q13 meta 函数",
    prompt: "export const meta: MetaFunction = () => pageMeta.chat();——pageMeta.chat() 返什么？",
    options: [
      sc("A", "返 Meta[] 数组——title/description/og:title/og:description 等；utils/seo.ts 集中管理；vs 硬编码不一致"),
      sc("B", "字符串"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "meta 函数返结构化 Meta[]——Remix 自动生成 head 标签。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/utils/seo.ts"],
  }),
  q({
    type: "branch_trace", title: "Q14 未登录用户访问 /chat 完整流",
    prompt: "未登录用户访问 /chat 步骤？",
    options: [
      sc("s1", "1. 浏览器 GET /chat"),
      sc("s2", "2. Worker 路由 chat.tsx loader 启动"),
      sc("s3", "3. await requireNemesisUser(request) 内查 session 失败"),
      sc("s4", "4. throw new Response(null, { status: 401 })"),
      sc("s5", "5. catch 捕获——error instanceof Response && status===401 真"),
      sc("s6", "6. throw redirect('/auth?returnTo=' + encodeURIComponent('/chat'))"),
      sc("s7", "7. 浏览器收到 302 → 跳到 /auth?returnTo=/chat"),
      sc("s8", "8. 用户登录成功后 /auth 处理 returnTo redirect 回 /chat"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8"] },
    explanation: { short: "未登录守门完整 8 步——auth 流的标准链。" },
    abilityTags: ["bridge.reactRouter.loader", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/services/nemesis-auth.server.ts", "app/routes/auth.tsx"],
  }),
  q({
    type: "branch_trace", title: "Q15 已登录用户访问 /chat 完整流",
    prompt: "已登录用户访问 /chat 步骤？",
    options: [
      sc("s1", "1. 浏览器 GET /chat"),
      sc("s2", "2. loader 启动"),
      sc("s3", "3. await requireNemesisUser(request) 通过——返 user"),
      sc("s4", "4. return json(null, { headers: 'private no-store' })"),
      sc("s5", "5. forwardLoaderCacheControl 把 headers 转写到 document"),
      sc("s6", "6. SSR 渲染 ChatRoute → <NemesisChatPage /> 的 fallback（client 才挂）"),
      sc("s7", "7. HTML + Cache-Control: private no-store 发给浏览器"),
      sc("s8", "8. client 端 NemesisChatPage hydrate → useNemesisChat 从 localStorage 拉历史"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8"] },
    explanation: { short: "已登录流：鉴权 + headers + SSR 入口 + client hydrate 拉本地数据。" },
    abilityTags: ["bridge.reactRouter.loader", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 SSR 时 .client 组件",
    prompt: "SSR 时 NemesisChatPage（.client.tsx）被怎么处理？",
    options: [
      sc("A", "Remix .client 后缀文件不进 SSR bundle——SSR 时该位置渲染空 placeholder（或 React 跳过整个组件树）；client 端 hydrate 才挂载真实组件"),
      sc("B", "渲染完整"),
      sc("C", "报错"),
      sc("D", "Cloudflare 拦截"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".client 文件 SSR 跳过——浏览器 API 安全的根本。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q17 chat 页可以裸 deploy",
    prompt: "判断：chat.tsx 不需要 .client 后缀的子组件配合也能正常工作。",
    correctAnswer: { value: false },
    explanation: { short: "错——NemesisChatPage 用了 localStorage/SSE/window 等浏览器 API；不加 .client 后缀 SSR 会报 ReferenceError。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 改鉴权策略",
    prompt: "想从「未登录跳转 /auth」改为「未登录显示游客 UI」。改动？",
    options: [
      sc("A", "loader 内不再 throw redirect——改为 catch 后 return json({ guest: true })；前端按 data.guest 切换 UI；多状态返 loader 是常规扩展"),
      sc("B", "改 wrangler"),
      sc("C", "改 root"),
      sc("D", "改 Header"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "auth 策略切换 = loader 返多状态；前端按状态分支。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 加载历史聊天放哪",
    prompt: "用户希望服务端加载聊天历史（替代 localStorage）。落点？",
    options: [
      sc("A", "loader 内 await requireNemesisUser → user.id；查 D1 chat_sessions 表 → return json({ user, sessions })；前端 useNemesisChat 从 useLoaderData 拿初始数据；client 状态接管后续"),
      sc("B", "改 root"),
      sc("C", "新建 API"),
      sc("D", "改 Header"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader 拉初始 server data + 前端接管状态——SSR + client 增强双轨。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 chat 路由长度",
    prompt: "chat.tsx 仅 35 行——为什么这么少？",
    options: [
      sc("A", "复杂度全在 NemesisChatPage.client + useNemesisChat hook + 4 个 sub component；路由文件保持「服务端 + 入口」最薄；分层让每个文件做单一事情"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "薄路由 + 厚组件 = 关注点分离的清晰体现。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/components/nemesis/chat/NemesisChatPage.client.tsx"],
  }),
  q({
    type: "single_choice", title: "Q21 改登录守门到 root.tsx",
    prompt: "想让所有需登录的页都自动跳 /auth——逻辑应放哪？",
    options: [
      sc("A", "可放 root.tsx loader 检查 session 但不全局守门——因为 / 公开页也走 root；更好的做法：每个需鉴权的路由各自调 requireXxxUser；显式 + 灵活"),
      sc("B", "永远 root"),
      sc("C", "Header"),
      sc("D", "Worker middleware"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix 鉴权按路由级，不靠全局 middleware——更灵活。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q22 整体设计哲学",
    prompt: "chat.tsx 整体哲学？",
    options: [
      sc("A", "1) 薄路由（35 行）—UI 推到 .client 组件 2) loader 鉴权用 try/catch 区分 401 vs 其他 3) returnTo 保持登录前路径 4) private no-store + Vary 头精准缓存控制 5) forwardLoaderCacheControl 透传 6) .client 后缀隔离浏览器 API 7) 默认导出 ChatRoute 渲染入口——综合：精准的服务端 + 客户端边界划分"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "七条原则——薄路由 + 厚客户端组件的范式。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/components/nemesis/chat/NemesisChatPage.client.tsx", "app/services/nemesis-auth.server.ts", "app/lib/cache-headers.server.ts"],
  }),
];
