/**
 * Real questions for site-10-chat-page / chat-loader.
 * Anchor: remix/app/routes/chat.tsx loader —— 守门 + 缓存头精细控制
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/chat.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const chatLoaderQuestions: RealQ[] = [
  q({
    type: "single_choice", title: "Q1 LoaderFunctionArgs 解构",
    prompt: "export async function loader({ request }: LoaderFunctionArgs)——为什么解构 request？",
    options: [
      sc("A", "loader 可拿 request/context/params 三参；这里只用 request（取 cookie / URL）；解构得到所需即可"),
      sc("B", "TypeScript 强制"),
      sc("C", "随机"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader 三参 = request/context/params；按需解构。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 try/catch 唯一目标",
    prompt: "try { await requireNemesisUser(request); } catch (error) { ... }——为什么只 try 这一行？",
    options: [
      sc("A", "只这一行可能 throw Response 401；其他代码（json + headers）不会异常；精准 try 范围不掩盖其他 bug"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "try 范围 = 仅可能抛错的语句；过宽易吞别 bug。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 instanceof Response 守卫",
    prompt: "if (error instanceof Response && error.status === 401)——双条件？",
    options: [
      sc("A", "守卫顺序：先确认 error 是 Response（不是 Error/object/string）→ 再访问 .status；类型守卫让 TS 知道 error.status 安全；vs 直接 error.status 不安全"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "instanceof + 字段判断 = TS 类型守卫的标准两步。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 throw redirect 与 throw error",
    prompt: "throw redirect('/auth?...')；末尾 throw error;——为什么都用 throw？",
    options: [
      sc("A", "Remix 约定 loader 中「响应」与「错误」都通过 throw 抛出——redirect 是特殊 Response，被 RR 拦截转 302；普通 error 被 ErrorBoundary 捕获；throw 是统一通信机制"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader throw = Remix 标准通信渠道——redirect / error 都靠它。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 returnTo URL 安全",
    prompt: "throw redirect(`/auth?returnTo=${encodeURIComponent(url.pathname + url.search)}`);——returnTo 是否有 open redirect 风险？",
    options: [
      sc("A", "有——若 /auth 登录后无校验直接 redirect(returnTo) 会被攻击者注入 //evil.com 跳到外部站；正确做法 /auth 端检查 returnTo 是否本站相对路径"),
      sc("B", "无风险"),
      sc("C", "Cloudflare 拦截"),
      sc("D", "TypeScript 强制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "open redirect 是常见 web 漏洞——目标端必须验证 returnTo。" },
    abilityTags: ["backend.auth.required", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/routes/auth.tsx"],
  }),
  q({
    type: "fill_blank", title: "Q6 Cache-Control 主指令",
    prompt: 'Cache-Control: "____ "',
    options: [],
    blanks: [{ id: "v", placeholder: "完整值", acceptedAnswers: ["private, no-store"] }],
    correctAnswer: { type: "fill_blank", values: { v: "private, no-store" } },
    explanation: { short: "private = 仅浏览器；no-store = 完全不存。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 private vs public",
    prompt: "private vs public——区别？",
    options: [
      sc("A", "public CDN 可缓存共享给多用户；private 只浏览器自己缓存；CDN 必须跳过；登录页/个人页用 private 防数据串户"),
      sc("B", "无区别"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "private = 浏览器单用户；public = CDN 多用户共享。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 no-store vs no-cache",
    prompt: "no-store vs no-cache——区别？",
    options: [
      sc("A", "no-store 完全不存（连临时缓存都不存）；no-cache 可存但每次必须 revalidate；no-store 更严格 = 真正「不缓存」"),
      sc("B", "无区别"),
      sc("C", "随机"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "no-store > no-cache 严格度——chat 私密性选最严。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 Vary: Accept-Encoding",
    prompt: "headers: { 'Vary': 'Accept-Encoding' }——这个 chat 页加 Vary 的意义？",
    options: [
      sc("A", "即使 private no-store 也写 Vary 是为「兼容 CDN 中间层逻辑」——某些 CDN/proxy 会缓存 private 标记之外的副本（如开发模式）；Vary 防错配；保险措施"),
      sc("B", "TypeScript"),
      sc("C", "随机"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Vary 是缓存行为正确性的双保险——即使 no-store 也加。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 forwardLoaderCacheControl 必加",
    prompt: "若忘记 export const headers——用户表现？",
    options: [
      sc("A", "loader 设的 Cache-Control 不会传到 document Response；浏览器和 CDN 可能默认缓存 chat 页 HTML；后续访问看到旧用户的渲染——严重数据隔离问题"),
      sc("B", "无影响"),
      sc("C", "页面挂"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "私聊页忘 forwardLoaderCacheControl = 隐私泄漏风险——必须加。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q11 redirect 状态码",
    prompt: "throw redirect('/auth?...');——redirect 默认状态码？",
    options: [
      sc("A", "302 (Found) ——临时重定向；浏览器/CDN 不缓存；适合「未登录跳转」这种条件性跳转；vs 301 永久（搜索引擎会替换索引）"),
      sc("B", "200"),
      sc("C", "301"),
      sc("D", "403"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix redirect 默认 302 临时——SEO 安全。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 url 构造",
    prompt: "const url = new URL(request.url);——url.pathname + url.search 拿到？",
    options: [
      sc("A", "完整路径 + query：'/chat?xxx=yyy'；不含协议/域；用于 returnTo 嵌入；URL 解析的标准做法"),
      sc("B", "只 pathname"),
      sc("C", "完整 URL"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "URL 解析 = 协议无关的路径 + query 拼接。" },
    abilityTags: ["code.position.handler", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 为什么 chat loader 不返用户数据",
    prompt: "loader return json(null)——不返用户给前端用？",
    options: [
      sc("A", "前端 useNemesisChat 不需用户数据（聊天历史在 localStorage）；如果需要可改 return json({ user })；当前设计极简"),
      sc("B", "永远 null"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader 返什么取决于前端需要——目前 null 即可。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 多平台 redirect URL 规范",
    prompt: "returnTo 应该是绝对还是相对路径？",
    options: [
      sc("A", "相对（'/chat'）——避免域名硬编码（dev/prod 不同）；登录后 redirect 时浏览器自动加当前 origin；移植性最好"),
      sc("B", "永远绝对"),
      sc("C", "永远相对"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "相对路径 = 环境无关——绝对路径硬编码域名是反模式。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 改 D1 加载历史",
    prompt: "想从 D1 加载用户聊天历史替代 localStorage——loader 改什么？",
    options: [
      sc("A", "1) 把 await requireNemesisUser 拿到 user 2) 加 await db.selectFrom('chat_sessions').where('user_id','=',user.id) 3) return json({ sessions, user })；前端 useLoaderData 拿初始数据；hook 用 useState 接管后续 mutation"),
      sc("B", "改 localStorage"),
      sc("C", "改 root"),
      sc("D", "新建 API"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader 拉初始 data + hook 接管交互——SSR + 客户端协作模式。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 错误监控",
    prompt: "throw error 末尾——生产想加 Sentry。落点？",
    options: [
      sc("A", "catch 内 throw error 之前调 sentryCapture(error) 上报；不阻塞 throw 让 ErrorBoundary 处理；vs 后台静默吞错丢失可观测性"),
      sc("B", "改 ErrorBoundary"),
      sc("C", "改 root"),
      sc("D", "改 Worker middleware"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "catch + 上报 + throw = 监控不影响错误处理流。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 SSR 时 loader 抛 401",
    prompt: "用户在浏览器导航到 /chat 触发 SSR loader 抛 401——浏览器看到？",
    options: [
      sc("A", "不会看到 401 —— catch 转成 throw redirect('/auth?...')；浏览器收到 302 直接跳走；用户感觉「点了 chat 链接被自动带到登录页」"),
      sc("B", "401 错误页"),
      sc("C", "白屏"),
      sc("D", "Cloudflare 拦截"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "401 → redirect → 302 跳转——用户无感切换。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 client 端导航 fetch loader",
    prompt: "已登录用户从 /messages 点击 Header 「Nemesis」链接——client 行为？",
    options: [
      sc("A", "RR 客户端 navigate → fetch /chat 触发 loader（仅 server 跑，不全页刷新）；loader return json(null) → 切到 chat 路由组件 → NemesisChatPage 挂载；丝滑切换"),
      sc("B", "全页刷新"),
      sc("C", "永远跳 /auth"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "client 导航 = fetch loader + 局部组件切换；丝滑 SPA 体验。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q19 client 导航未登录流",
    prompt: "未登录用户从首页点 「Nemesis」链接——client 步骤？",
    options: [
      sc("s1", "1. RR Link onClick → 拦截原生导航"),
      sc("s2", "2. fetch /chat?_data=... loader-only 请求"),
      sc("s3", "3. 服务端 loader → requireNemesisUser 失败"),
      sc("s4", "4. catch → throw redirect 302 /auth?returnTo=/chat"),
      sc("s5", "5. RR 客户端识别 redirect，先 fetch /auth 的 loader"),
      sc("s6", "6. 切换到 /auth 路由组件"),
      sc("s7", "7. URL 浏览器栏更新为 /auth?returnTo=/chat"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7"] },
    explanation: { short: "RR 客户端识别 redirect + 自动跟随——SPA 体验下的自动跳转。" },
    abilityTags: ["bridge.reactRouter.loader", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/auth.tsx"],
  }),
  q({
    type: "single_choice", title: "Q20 redirect 是否会让 client navigation 看起来卡顿",
    prompt: "未登录点 chat → redirect → /auth 全过程中间 fetch 几次 loader？",
    options: [
      sc("A", "最少 2 次：第一次 /chat 的 loader（拿到 redirect）+ 第二次 /auth 的 loader（拿初始数据）；可能再 + revalidation；用户感觉一次「短暂闪屏」"),
      sc("B", "1 次"),
      sc("C", "永远 0"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "redirect = 多 fetch 链——可优化但本质成本就在那。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 直接显示「请登录」UI 替代 redirect",
    prompt: "替代 redirect，loader 改返 json({ requiresAuth: true })——前端做什么？",
    options: [
      sc("A", "前端组件 if (data.requiresAuth) return <LoginPrompt onLogin={() => ...} />；用户在原页内登录后 revalidate 自动重渲染；UX 更顺滑（少一跳）"),
      sc("B", "永远报错"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "数据状态驱动 UI = 内联登录 UX；trade-off：模态登录 vs 跳转登录页。" },
    abilityTags: ["bridge.reactRouter.loader", "frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 整体 loader 设计哲学",
    prompt: "chat loader 整体设计？",
    options: [
      sc("A", "1) 仅做鉴权 + 缓存头（不返业务数据） 2) try 范围最窄 3) instanceof Response 类型守卫 4) 401 转 redirect + returnTo encode 5) 其他错 throw 给 ErrorBoundary 6) private + no-store + Vary 三件套头 7) forwardLoaderCacheControl 透传 8) 默认 302 redirect 不影响 SEO——综合：精准、安全、可观测的鉴权 loader 范式"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "八条原则——鉴权守门 loader 的范式。" },
    abilityTags: ["bridge.reactRouter.loader", "backend.auth.required", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/services/nemesis-auth.server.ts", "app/lib/cache-headers.server.ts"],
  }),
];
