/**
 * Real questions for site-10-chat-page / chat-meta.
 * Anchor: remix/app/routes/chat.tsx meta + remix/app/utils/seo.ts pageMeta.chat()
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/chat.tsx";
const SEO = "app/utils/seo.ts";
const sc = (id: string, text: string) => ({ id, text });

export const chatMetaQuestions: RealQ[] = [
  q({
    type: "single_choice", title: "Q1 meta 函数签名",
    prompt: "export const meta: MetaFunction = () => pageMeta.chat();——MetaFunction 类型？",
    options: [
      sc("A", "Remix 提供的类型 = 函数返 Meta[]（数组中是 title/description/og:* 等结构化项）；HTML head 标签由 Remix 自动渲染"),
      sc("B", "字符串"),
      sc("C", "JSX"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "MetaFunction 返 Meta[]——结构化的 head 元数据。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank", title: "Q2 chat 页 title",
    prompt: 'pageMeta.chat() 内 title: "AI聊天室 - 与____对话"',
    options: [],
    blanks: [{ id: "v", placeholder: "名字", acceptedAnswers: ["Nemesis"] }],
    correctAnswer: { type: "fill_blank", values: { v: "Nemesis" } },
    explanation: { short: "Nemesis 是项目特色 AI 命名——作为品牌植入 SEO。" },
    abilityTags: ["code.position.handler"], sourceFilePath: SEO, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, SEO],
  }),
  q({
    type: "single_choice", title: "Q3 url 字段含义",
    prompt: 'url: "https://xn--cckl9nsb.com/chat"——这个 url 用途？',
    options: [
      sc("A", "og:url（Open Graph 元数据）——分享到微信/Twitter 时的目标 URL；让分享卡片指向 canonical 链接，避免 SEO 链接被分散"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "og:url = 分享卡片的规范链接；SEO 友好。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: SEO, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, SEO],
  }),
  q({
    type: "fill_blank", title: "Q4 域名 punycode",
    prompt: 'url: "https://____.com/chat"',
    options: [],
    blanks: [{ id: "v", placeholder: "punycode 域名", acceptedAnswers: ["xn--cckl9nsb"] }],
    correctAnswer: { type: "fill_blank", values: { v: "xn--cckl9nsb" } },
    explanation: { short: "xn--cckl9nsb.com 是中文域名「汪家俊.com」的 IDN/punycode 表示——url 必须用 ASCII。" },
    abilityTags: ["code.position.handler"], sourceFilePath: SEO, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, SEO],
  }),
  q({
    type: "single_choice", title: "Q5 image og 卡片",
    prompt: "image: cdnUrl('og/chat.jpg')——og:image 用途？",
    options: [
      sc("A", "微信/Twitter 分享时显示的卡片预览图（通常 1200×630）；不设的话分享卡很丑；走 cdnUrl 拿 CDN URL；专门的 og/ 目录管理"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "og:image = 分享卡的脸面；专图 1200×630 最佳。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: SEO, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, SEO, "app/lib/media-cdn.ts"],
  }),
  q({
    type: "single_choice", title: "Q6 keywords 数组",
    prompt: "keywords: ['AI聊天', '人工智能', '对话机器人', 'Nemesis']——keywords meta 还有用吗？",
    options: [
      sc("A", "Google 已经不看 keywords 多年；但百度等中文搜索引擎仍可能参考；保留是低成本兜底；4 个关键词覆盖技术 + 业务"),
      sc("B", "永远关键"),
      sc("C", "永远废"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "keywords meta 边际效用低但成本也低——保留兜底。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: SEO, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, SEO],
  }),
  q({
    type: "single_choice", title: "Q7 集中 vs 分散 meta",
    prompt: "为什么 meta 集中到 utils/seo.ts？",
    options: [
      sc("A", "1) 多页可能 share 部分字段（site_name、author 等）2) 一处改全局生效 3) generateMeta 公共函数标准化输出 4) 防止某页漏字段——集中管理 SEO 是惯例"),
      sc("B", "性能"),
      sc("C", "TypeScript 强制"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SEO 集中 = 一处管理多页一致性。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: SEO, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, SEO],
  }),
  q({
    type: "single_choice", title: "Q8 generateMeta 函数",
    prompt: "pageMeta.chat() 内调 generateMeta({...})——这是什么？",
    options: [
      sc("A", "公共工厂函数：接 { title, description, url, image, keywords } → 返完整 Meta[]（包含 og:title/og:description/og:url/og:image/twitter:card/keywords 等所有标准字段）；省掉每页重复"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "generateMeta 工厂 = 标准 SEO 字段一站补齐。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: SEO, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [SEO],
  }),
  q({
    type: "single_choice", title: "Q9 Twitter card 也覆盖",
    prompt: "generateMeta 内部应该输出 twitter:card / twitter:image / twitter:title 等——为什么？",
    options: [
      sc("A", "Twitter 不读 og:* 而读 twitter:*；为兼容多平台分享需要双输出；4 个字段足够；微信读 og 即可"),
      sc("B", "永远等价 og"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Twitter 与 OG 不同 namespace——双套字段保兼容。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: SEO, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [SEO],
  }),
  q({
    type: "single_choice", title: "Q10 og:type",
    prompt: "cv 页设 type: 'profile' 而 chat 不设——'profile' 与默认 type？",
    options: [
      sc("A", "Open Graph 默认 type=website；profile 适用人物页（让 FB/LinkedIn 渲染人物卡片）；chat 是产品页继续用默认 website 即可；按内容选 type"),
      sc("B", "永远 website"),
      sc("C", "永远 profile"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "og:type 按内容语义选——人物 / 文章 / 产品 不同卡片样式。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: SEO, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, SEO],
  }),
  q({
    type: "single_choice", title: "Q11 SSR 输出 head 顺序",
    prompt: "Remix 渲染 head 时 meta 标签来自哪？",
    options: [
      sc("A", "三层合并：root.tsx meta（站点级 default） + 父 layout meta（如 site-09 没层）+ 子路由 meta（如 chat.tsx 自定义）；后者覆盖前者；title/description 等单值"),
      sc("B", "只有 root"),
      sc("C", "只有页"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix meta = 路由树合并 + 子覆盖父——精细化 SEO 的基础。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q12 加新页 SEO 落点",
    prompt: "新加 /timeline 页要 SEO meta。落点？",
    options: [
      sc("A", "1) utils/seo.ts pageMeta 加 timeline 方法 2) routes/timeline.tsx export const meta = () => pageMeta.timeline()；两步即可；新页不必新建 seo 工具"),
      sc("B", "新建 seo.ts"),
      sc("C", "改 root"),
      sc("D", "硬编码"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SEO 添加 = 集中加 + 路由文件单行——单一来源原则。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: SEO, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, SEO],
  }),
  q({
    type: "single_choice", title: "Q13 dev mode 看 og 卡片",
    prompt: "本地开发想测试微信分享卡片显示。怎么做？",
    options: [
      sc("A", "需公网可访问 URL（微信/Twitter 抓取）；本地用 cloudflared tunnel 或 ngrok 暴露 localhost；把 og:url 临时改 ngrok URL；调好再换回 prod；vs 直接 deploy 测试"),
      sc("B", "本地直接看"),
      sc("C", "永远不能测"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "外部抓取需要公网——隧道工具是 dev 测试 OG 的标准做法。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, SEO],
  }),
  q({
    type: "single_choice", title: "Q14 og:image 缓存",
    prompt: "改 og/chat.jpg 后微信分享仍看到旧图——原因？",
    options: [
      sc("A", "微信/Facebook 等会缓存抓取的 OG 数据（通常 24h-7天）；改图后需用「分享调试器」（fb sharing-debugger / weibo 调试）主动刷新；或加 ?v=2 query 强制不同 URL"),
      sc("B", "无办法"),
      sc("C", "永远旧"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "OG 缓存 = 改图后需主动 invalidate；调试器 + query 是常用招数。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: SEO, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [SEO],
  }),
  q({
    type: "single_choice", title: "Q15 描述长度",
    prompt: "description: '与AI助手 Nemesis 进行智能对话，探讨技术、创意和生活...'——字数有上限吗？",
    options: [
      sc("A", "Google 搜索结果摘要约 150-160 字符；超过截断；中文字符按 2 字节算更宽限；描述前 100 字最关键；超出无害但被截"),
      sc("B", "随便长"),
      sc("C", "永远 50"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "description 黄金长度 150 字内——关键信息前置。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: SEO, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [SEO],
  }),
  q({
    type: "single_choice", title: "Q16 title 模式",
    prompt: "'AI聊天室 - 与Nemesis对话'——「主功能 - 子描述」格式？",
    options: [
      sc("A", "title 黄金格式：「主关键词 - 副描述 | 站名」；本页省略站名（由 root 默认 site_name 拼接）；vs 「Nemesis | 站名」太抽象"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "title = 关键词 + 副描述——SEO + 用户扫描双友好。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: SEO, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [SEO],
  }),
  q({
    type: "single_choice", title: "Q17 本页 meta 不含 robots",
    prompt: "chat 页是否 noindex？",
    options: [
      sc("A", "默认 index——SEO 抓取；但因 chat 页 SSR 出空白（.client 组件不渲染）抓取价值低；可考虑加 noindex 跟 og 双策略"),
      sc("B", "永远 noindex"),
      sc("C", "永远 index"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "noindex/index 决策看抓取价值——SSR 空内容页可考虑 noindex。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: SEO, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [SEO],
  }),
  q({
    type: "single_choice", title: "Q18 sitemap.xml 联动",
    prompt: "chat 页应不应进 sitemap.xml？",
    options: [
      sc("A", "看抓取价值——本页 SSR 空白对搜索引擎价值低；可不进；进了也不大影响排名；项目已有 sitemap[.]xml.tsx 路由控制"),
      sc("B", "永远进"),
      sc("C", "永远不进"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "sitemap 选择 = 高价值内容页优先；交互页可省。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: SEO, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [SEO, "app/routes/sitemap[.]xml.tsx"],
  }),
  q({
    type: "single_choice", title: "Q19 dynamic meta",
    prompt: "若 chat 页要动态 title（如「与 Nemesis 对话 - 用户名」）——怎么改？",
    options: [
      sc("A", "meta: MetaFunction = ({ data }) => [...]；从 loader 返的 data 拿 user 信息组合 title；vs 静态 pageMeta.chat() 不能用 loader 数据"),
      sc("B", "永远静态"),
      sc("C", "永远 D1"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "MetaFunction 接 { data } = loader 返值——动态 title 的钥匙。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 i18n meta 准备",
    prompt: "未来想英文页用英文 title。落点？",
    options: [
      sc("A", "MetaFunction 内 ({ data, params }) => 按 params.locale 选语言；pageMeta.chat({ locale }) 重载；i18n 工具按 key 取多语言文案；提前留 locale 参数即可"),
      sc("B", "永远中文"),
      sc("C", "硬编码"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "MetaFunction 接 params = i18n 的入口；提前留 locale 接口。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: SEO, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [SEO],
  }),
  q({
    type: "true_false", title: "Q21 SSR 时 meta 已渲染",
    prompt: "判断：Remix SSR 时 chat 页的 <title> 已经在 HTML 内。",
    correctAnswer: { value: true },
    explanation: { short: "对——meta 函数纯函数 SSR 阶段执行；title/description/og 都在 head 内；vs 客户端 React Helmet 等需 mount 后注入。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 整体 meta 设计哲学",
    prompt: "chat 页 meta 设计？",
    options: [
      sc("A", "1) MetaFunction 类型化函数 2) pageMeta 集中所有页 3) generateMeta 工厂统一字段 4) og + twitter 双套兼容多平台 5) keywords 兜底中文搜索 6) cdnUrl 走 CDN 缓存图 7) url 用 punycode IDN 8) 静态当前 + 动态扩展（{ data }）保留——综合：可扩展、跨平台、可维护的 SEO 范式"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "八条原则——SEO meta 的范式。" },
    abilityTags: ["ai.review.architecture", "code.position.handler", "bridge.reactRouter.loader"],
    sourceFilePath: SEO, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, SEO, "app/lib/media-cdn.ts", "app/root.tsx"],
  }),
];
