/**
 * Real questions for site-10-chat-page / nemesis-page-client.
 * Anchor: remix/app/components/nemesis/chat/NemesisChatPage.client.tsx —— 4 sub-component + useNemesisChat hook 解构
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/nemesis/chat/NemesisChatPage.client.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const nemesisPageClientQuestions: RealQ[] = [
  q({
    type: "single_choice", title: "Q1 .client.tsx 后缀",
    prompt: "文件名 NemesisChatPage.client.tsx 的 .client 后缀含义？",
    options: [
      sc("A", "Remix 编译指示——只打包到客户端 bundle，不进 SSR；组件内部使用浏览器 API 安全；vs 普通 .tsx 文件双端可用"),
      sc("B", "TypeScript"),
      sc("C", "性能"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".client 后缀 = 强制 client-only 打包；浏览器 API 隔离的关键。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank", title: "Q2 hook import",
    prompt: 'import { useNemesisChat } from "~/hooks/____.client";',
    options: [],
    blanks: [{ id: "v", placeholder: "文件名（不含扩展名）", acceptedAnswers: ["useNemesisChat"] }],
    correctAnswer: { type: "fill_blank", values: { v: "useNemesisChat" } },
    explanation: { short: "useNemesisChat.client.ts 同样 .client 后缀——主 hook 也只在客户端用。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/hooks/useNemesisChat.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q3 4 个 sub-component",
    prompt: "NemesisChatHeader / NemesisChatSidebar / NemesisChatMessageList / NemesisChatComposer 4 个 sub——为什么拆？",
    options: [
      sc("A", "分而治之——header 顶栏、sidebar 历史会话、messageList 消息流、composer 输入区；各自约 100-300 行；vs 一个 800 行巨型组件难维护"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "分组件 = 各自职责清晰；维护成本下降。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 const chat = useNemesisChat()",
    prompt: "function NemesisChatPage() { const chat = useNemesisChat(); ... }——chat 是？",
    options: [
      sc("A", "controller object——hook 返大对象（state + setter + handler 30+ 字段）；外层组件作为「状态拥有者」把片段 prop 传给各 sub；vs 让 sub 各自调 hook 状态会分散"),
      sc("B", "context"),
      sc("C", "ref"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Hook 集中状态 + 父组件传 props 给子 = 简化版「自定义 reducer」。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/hooks/useNemesisChat.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q5 chat.activeSession?.id ?? null",
    prompt: "activeSessionId={chat.activeSession?.id ?? null}——双兜底？",
    options: [
      sc("A", "?. 安全访问可能 null 的 activeSession；?? null 把 undefined 也归一为 null；NemesisChatSidebar 期待 string|null prop——类型一致性"),
      sc("B", "随机"),
      sc("C", "TypeScript 强制"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "?. + ?? = null/undefined 归一化——TS prop 类型严格时常用。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank", title: "Q6 默认 title",
    prompt: 'title={chat.activeSession?.title ?? "____"}',
    options: [],
    blanks: [{ id: "v", placeholder: "默认", acceptedAnswers: ["新的对话"] }],
    correctAnswer: { type: "fill_blank", values: { v: "新的对话" } },
    explanation: { short: "新会话还没问问题前用默认标题——避免 UI 显示 undefined。" },
    abilityTags: ["frontend.state.local"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 setIsPrivacyPopoverOpen 函数式",
    prompt: "onTogglePrivacyPopover={() => chat.setIsPrivacyPopoverOpen((value) => !value)}——为什么 prev=>!prev？",
    options: [
      sc("A", "函数式更新避免闭包过期——多次连点 toggle 不会用到陈旧值；vs 直接 set(!isOpen) 在异步场景可能错；React 推荐做法"),
      sc("B", "TypeScript"),
      sc("C", "性能"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "setX(prev => ...) = 永远拿最新值；闭包陷阱的标准防御。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 onSubmitFeedback void wrap",
    prompt: "onSubmitFeedback={(message) => void chat.submitFeedback(message)}——void 的作用？",
    options: [
      sc("A", "submitFeedback 返 Promise；onSubmitFeedback 期待返 void/undefined 的 handler；用 void operator 显式弃用 Promise；不 await 让 UI 响应不阻塞"),
      sc("B", "TypeScript 限制"),
      sc("C", "随机"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "void Promise = fire-and-forget 显式标记——TS no-misused-promises 规则要求。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 onSend 同款 void",
    prompt: "onSend={() => void chat.sendMessage()}——同样模式？",
    options: [
      sc("A", "对——sendMessage 返 Promise；UI 不阻塞；error 通过 hook 内部 setError 暴露而非 throw；fire-and-forget 标准模式"),
      sc("B", "永远 await"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "异步 handler 用 void 包 = UI 不阻塞，error 通过 state 通知。" },
    abilityTags: ["frontend.event.click", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 ref props 传递",
    prompt: "chatWindowRef={chat.chatWindowRef} textareaRef={chat.textareaRef}——为什么父持 ref 传子？",
    options: [
      sc("A", "ref 在父定义（hook 内）让 hook 能 useEffect 内 textareaRef.current?.focus() 等命令式操作；子组件只是把 ref attach 到具体 DOM；状态拥有权保持在父"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ref 在父定义 + 子 attach = hook 控制 DOM 的标准模式。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/hooks/useNemesisChat.client.ts"],
  }),
  q({
    type: "single_choice", title: "Q11 className flex h-screen flex-col",
    prompt: "<div className='flex h-screen flex-col overflow-hidden bg-primary-50 ... md:flex-row'>——layout 关键 class 含义？",
    options: [
      sc("A", "h-screen 占满视口高 + flex-col 移动端竖排（sidebar 上、main 下）+ md:flex-row 桌面横排（sidebar 左、main 右）+ overflow-hidden 防整屏滚动；响应式 chat layout 的标准"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "全屏 chat 布局 = 视口高 + 弹性方向 + 防溢出——铁三角。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 min-h-0 必要",
    prompt: "<main className='flex min-h-0 flex-1 flex-col'>——min-h-0 用途？",
    options: [
      sc("A", "解决 flexbox 子项 overflow——默认 min-height: auto 让子项不收缩到比内容小；min-h-0 允许收缩 + flex-1 占剩余；这样内部消息列表才能 overflow-y: auto 滚动"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "性能"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "flex 容器内滚动陷阱：子项加 min-h-0 才允许收缩——常见坑。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 max-w-5xl 容器",
    prompt: "<div className='mx-auto flex min-h-0 w-full max-w-5xl flex-1 flex-col px-3 py-4 md:px-6 md:py-6'>——max-w-5xl 用途？",
    options: [
      sc("A", "聊天内容区最大宽 1024px 居中——超大屏幕不让消息横铺过宽（影响阅读）；px-3/6 移动 vs 桌面留边；mx-auto 居中"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "max-w + mx-auto = 长内容居中限宽——阅读体验。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 大量 props 传递的性能",
    prompt: "MessageList 接 17 个 props，Composer 7 个——性能担心？",
    options: [
      sc("A", "props 多但不重渲染——只要父 chat 字段不变 React.memo 子组件可保持；hook 内 useCallback 稳定 handler；前提是 hook 内做了优化（这里做了）"),
      sc("B", "永远性能差"),
      sc("C", "TypeScript 限制"),
      sc("D", "Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "多 props 本身不慢——配 useCallback + React.memo 即可。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 Composer 与 MessageList 顺序",
    prompt: "<MessageList ... /> <Composer ... /> 顺序为什么 list 在前？",
    options: [
      sc("A", "DOM 顺序 = MessageList 占主体（flex-1 ）+ Composer 底部固定；视觉上消息列表上、输入框下；屏幕阅读器也按顺序读，符合用户心智"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "DOM 顺序 = 视觉 + a11y 双对齐——简单聊天 UI 标准。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 hook 状态拥有权",
    prompt: "若用户希望 sidebar 独立刷新（如长轮询查别人的会话）——重构方向？",
    options: [
      sc("A", "Sidebar 独立 hook（如 useChatSessions） + ChatPage 不持有 sessions；vs 当前所有状态集中 useNemesisChat；trade-off：集中更易用但拆得越细越独立"),
      sc("B", "永远集中"),
      sc("C", "永远拆开"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "状态拥有权按更新独立性划分——独立刷新需求拆 hook。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/hooks/useNemesisChat.client.ts"],
  }),
  q({
    type: "true_false", title: "Q17 NemesisChatPage 里没 useState",
    prompt: "判断：NemesisChatPage.client.tsx 内部直接没有任何 useState 调用。",
    correctAnswer: { value: true },
    explanation: { short: "对——所有 state 都在 useNemesisChat hook 里；本组件只解构 + 传 props；这就是「pure presentational shell」。" },
    abilityTags: ["frontend.state.local", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 hook 解耦组件",
    prompt: "useNemesisChat 与 NemesisChatPage 解耦带来的优势？",
    options: [
      sc("A", "1) hook 可单测（不依赖 DOM）2) 组件可单测（mock hook）3) 可换布局复用同 hook 4) 状态变更不引起 view 不必要的副作用——分层福利"),
      sc("B", "性能差"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Hook + Component 分层 = 测试性 + 复用性双赢。" },
    abilityTags: ["ai.review.architecture", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 SSR 不渲染本组件",
    prompt: "SSR 阶段 NemesisChatPage 不渲染——那 chat 页 HTML 看起来是？",
    options: [
      sc("A", "Remix 输出包含 root layout（Header）但 Outlet 内是空 placeholder（或 loading 状态）；client hydrate 后 NemesisChatPage 才挂出整界面；首屏 LCP 取决于 client JS 加载速度"),
      sc("B", "白屏"),
      sc("C", "完整 chat"),
      sc("D", "Cloudflare 拦截"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".client 组件 SSR 跳过 + hydrate 挂——首屏与 client 加载速度强绑。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/chat.tsx"],
  }),
  q({
    type: "single_choice", title: "Q20 动画/loader 加 SSR",
    prompt: "想给 chat 页加 SSR loading skeleton——哪里加？",
    options: [
      sc("A", "chat.tsx route 默认导出函数加一段 SSR HTML（如 <ChatSkeleton />），client hydrate 时被 NemesisChatPage 替换；保留 SSR 视觉占位"),
      sc("B", "改 root"),
      sc("C", "改 Header"),
      sc("D", "改 Cloudflare"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SSR skeleton + client 挂载 = 首屏不空白；UX 提升关键。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: "app/routes/chat.tsx", layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/chat.tsx"],
  }),
  q({
    type: "single_choice", title: "Q21 拆组件颗粒度",
    prompt: "为什么不把 Sidebar 内每个 session 项也拆成独立组件？",
    options: [
      sc("A", "权衡：再拆颗粒太细维护反难（参 props drilling）；当前 4 大块已平衡复杂度；细节列表项内联 .map 即可——不必教条拆"),
      sc("B", "永远拆到最细"),
      sc("C", "TypeScript 强制"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "拆组件粒度看复杂度边界——不教条，按需。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 整体设计哲学",
    prompt: "NemesisChatPage 整体哲学？",
    options: [
      sc("A", "1) .client 后缀强制客户端打包 2) 单 hook 集中所有状态 + handler 3) 主组件作为 prop drilling 的中转 4) 4 大子组件分而治之 5) ?? null + ?. 安全访问 6) 函数式 setter 防闭包陷阱 7) void Promise 标记 fire-and-forget 8) ref 父持子 attach + min-h-0 解 flex 滚动陷阱——综合：复杂客户端 UI 的解耦范式"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "八条原则——复杂 chat UI 的拆分与状态范式。" },
    abilityTags: ["ai.review.architecture", "frontend.state.local", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY, "app/hooks/useNemesisChat.client.ts", "app/components/nemesis/chat/NemesisChatHeader.tsx"],
  }),
];
