import type { CourseSpec, LessonSpec } from "./factory";

function L(
  slug: string,
  title: string,
  path: string,
  summary: string,
  focus: string,
  remixModules: LessonSpec["remixModules"],
  abilityTags: LessonSpec["abilityTags"],
  primaryFile?: string,
): LessonSpec {
  return { slug, title, path, summary, focus, remixModules, abilityTags, primaryFile };
}

const loaderTags = ["bridge.reactRouter.loader"] as LessonSpec["abilityTags"];
const actionTags = ["bridge.reactRouter.action"] as LessonSpec["abilityTags"];
const globalTags = ["frontend.state.global"] as LessonSpec["abilityTags"];
const localTags = ["frontend.state.local"] as LessonSpec["abilityTags"];
const sessionTags = ["backend.session.cookie", "backend.auth.required"] as LessonSpec["abilityTags"];
const guardTags = ["backend.rateLimit", "backend.auth.required"] as LessonSpec["abilityTags"];
const handlerTags = ["code.position.handler"] as LessonSpec["abilityTags"];
const fullstackTags = ["project.modify.fullstack", "ai.review.architecture"] as LessonSpec["abilityTags"];

export const UNIT_01_SPECS: CourseSpec[] = [
  {
    slug: "site-01-repo-map",
    title: "仓库地图与运行环境",
    description: "从 remix/ 根目录认识 app、utils、migrations 与 Cloudflare Worker 运行方式。",
    projectContext: "读懂个人网站 monorepo 中 remix 子项目如何独立部署到 Workers。",
    difficulty: "beginner",
    abilityTags: ["code.position.handler", "bridge.reactRouter.loader"],
    orderIndex: 0,
    unitIndex: 0,
    remixModules: ["repo-map"],
    lessons: [
      L("app-tree", "app/ 目录鸟瞰", "app/", "React Router 应用根目录", "routes、components、lib、services 按职责分包", ["repo-map"], handlerTags, "app/root.tsx"),
      L("entry-server-intro", "entry.server 入口", "app/entry.server.tsx", "SSR 文档响应入口", "handleRequest 渲染 Remix 树并设置响应头", ["shell-entry", "repo-map"], loaderTags),
      L("cloudflare-env", "Cloudflare 环境", "app/utils/cloudflare-env.server.ts", "从 context 读取 env", "统一访问 DB、AI、OAuth 等 binding", ["repo-map"], loaderTags),
      L("routes-folder", "routes 与 URL", "app/routes/", "文件系统路由目录", "文件名决定 URL 与 layout 嵌套", ["routes-core", "repo-map"], handlerTags, "app/routes/_index.tsx"),
      L("components-folder", "components 分区", "app/components/", "可复用 UI 与页面区块", "home、nemesis、ui 等子目录按功能划分", ["repo-map"], handlerTags, "app/components/ui/Header.tsx"),
      L("repo-capstone", "仓库 capstone", "app/", "跨目录协作", "新功能应落在 routes 还是 components 的判断", ["repo-map"], fullstackTags, "app/root.tsx"),
    ],
  },
  {
    slug: "site-02-root-shell",
    title: "Root 与 App Shell",
    description: "root.tsx 的 loader、Layout、Outlet 构成全站壳层。",
    projectContext: "所有页面共享 root loader 注入的 theme 与 session。",
    difficulty: "intermediate",
    abilityTags: ["frontend.state.global", "bridge.reactRouter.loader"],
    orderIndex: 1,
    unitIndex: 0,
    remixModules: ["shell-root"],
    lessons: [
      L("root-loader", "root loader 数据", "app/root.tsx", "返回 theme/session", "匿名访客跳过 D1 session 读取", ["shell-root"], loaderTags),
      L("layout-html", "Layout 与 html 壳", "app/root.tsx", "theme class 挂 html", "防闪烁内联脚本读取 theme cookie", ["shell-root", "shell-theme"], globalTags),
      L("outlet-shell", "Outlet 路由出口", "app/root.tsx", "子路由渲染点", "App 组件内 Outlet 承载页面", ["shell-root"], handlerTags),
      L("error-boundary", "ErrorBoundary", "app/root.tsx", "路由级错误捕获", "export ErrorBoundary 包裹子树", ["shell-errors", "shell-root"], handlerTags),
      L("lazy-login", "懒加载登录 UI", "app/root.tsx", "LoginModal 动态 import", "客户端边界减少首包", ["shell-root", "ui-client"], localTags),
      L("shell-capstone", "Shell capstone", "app/root.tsx", "改全站布局", "动 root Layout 还是子路由", ["shell-root"], fullstackTags),
    ],
  },
];

export const UNIT_02_SPECS: CourseSpec[] = [
  {
    slug: "site-03-entry-server",
    title: "Entry Server 深入",
    description: "entry.server.tsx 如何生成 HTML 与流式响应。",
    projectContext: "Worker 上 SSR 的第一站是 entry.server。",
    difficulty: "intermediate",
    abilityTags: ["bridge.reactRouter.loader"],
    orderIndex: 2,
    unitIndex: 1,
    remixModules: ["shell-entry"],
    lessons: [
      L("handle-request", "handleRequest", "app/entry.server.tsx", "请求入口", "调用 renderToReadableStream 或等价 API", ["shell-entry"], loaderTags),
      L("response-headers", "响应头", "app/entry.server.tsx", "Content-Type 与缓存", "HTML 文档响应头设置", ["shell-entry"], loaderTags),
      L("bot-detection", "爬虫与 SPA", "app/entry.server.tsx", "bot 分支", "搜索引擎与用户请求差异化", ["shell-entry"], handlerTags),
      L("stream-fallback", "流式与降级", "app/entry.server.tsx", "onShellReady", "shell 就绪后刷新缓冲", ["shell-entry"], handlerTags),
      L("entry-env", "entry 与 env", "app/entry.server.tsx", "loadContext", "把 Cloudflare env 传入 Remix", ["shell-entry", "repo-map"], loaderTags),
      L("entry-capstone", "entry capstone", "app/entry.server.tsx", "改 SSR 行为", "entry 与 root 的分工边界", ["shell-entry"], fullstackTags),
    ],
  },
  {
    slug: "site-04-theme-system",
    title: "全局主题系统",
    description: "theme cookie、root action 与黑夜模式同步。",
    projectContext: "主题在服务端 cookie 与客户端 class 双写保持一致。",
    difficulty: "intermediate",
    abilityTags: ["frontend.state.global", "bridge.reactRouter.action"],
    orderIndex: 3,
    unitIndex: 1,
    remixModules: ["shell-theme"],
    lessons: [
      L("theme-server", "theme.server", "app/utils/theme.server.ts", "读写在服务端", "getTheme / setThemeCookie 助手", ["shell-theme"], sessionTags),
      L("root-theme-loader", "loader 读 theme", "app/root.tsx", "loader 返回 theme", "Layout 消费 useLoaderData", ["shell-theme", "shell-root"], loaderTags),
      L("root-theme-action", "action 写 theme", "app/root.tsx", "POST 切换主题", "action 设置 Set-Cookie", ["shell-theme"], actionTags),
      L("theme-toggle-ui", "切换控件", "app/components/ui/Header.tsx", "触发 theme 提交", "Form 或 fetcher 调 root action", ["shell-theme", "ui-header"], actionTags),
      L("theme-fouc", "防闪烁", "app/root.tsx", "head 内联脚本", "水合前同步 documentElement class", ["shell-theme"], globalTags),
      L("theme-capstone", "主题 capstone", "app/utils/theme.server.ts", "新增主题选项", "server cookie + root + Header 联动", ["shell-theme"], fullstackTags),
    ],
  },
  {
    slug: "site-05-shell-errors",
    title: "过渡与错误边界",
    description: "RouteTransition、404 与 RouteErrorBoundary。",
    projectContext: "路由切换动画与友好错误页提升体验。",
    difficulty: "intermediate",
    abilityTags: ["frontend.effect.useEffect", "code.position.handler"],
    orderIndex: 4,
    unitIndex: 1,
    remixModules: ["shell-errors"],
    lessons: [
      L("route-transition", "RouteTransition", "app/components/transitions/RouteTransition.tsx", "路由过渡动画", "location 变化触发过渡", ["shell-errors"], localTags),
      L("not-found", "NotFound404", "app/components/error/NotFound404.tsx", "404 展示", "catch-all 或 throw 404 时使用", ["shell-errors"], handlerTags),
      L("error-boundary-comp", "RouteErrorBoundary", "app/components/error/RouteErrorBoundary.tsx", "错误 UI", "展示 status 与 message", ["shell-errors"], handlerTags),
      L("root-error-export", "root 导出 ErrorBoundary", "app/root.tsx", "全局错误兜底", "与路由级 boundary 配合", ["shell-errors", "shell-root"], handlerTags),
      L("transition-access", "减少动效干扰", "app/components/transitions/RouteTransition.tsx", "prefers-reduced-motion", "尊重系统动效偏好", ["shell-errors"], localTags),
      L("errors-capstone", "错误 capstone", "app/components/error/", "统一错误体验", "404 与 500 组件分工", ["shell-errors"], fullstackTags, "app/components/error/RouteErrorBoundary.tsx"),
    ],
  },
];

export const UNIT_03_SPECS: CourseSpec[] = [
  {
    slug: "site-06-file-routing",
    title: "文件路由基础",
    description: "routes 目录命名与 URL 映射规则。",
    projectContext: "React Router v7 文件路由是个人网站 URL 的真相来源。",
    difficulty: "beginner",
    abilityTags: ["code.position.handler", "bridge.reactRouter.loader"],
    orderIndex: 5,
    unitIndex: 2,
    remixModules: ["routes-core"],
    lessons: [
      L("index-route", "_index 首页", "app/routes/_index.tsx", "站点根路径", "/ 映射到 _index", ["routes-core", "routes-home"], handlerTags),
      L("flat-routes", "扁平路由文件", "app/routes/gallery.tsx", "/gallery 单文件路由", "无 $ 参数的简单页面", ["routes-core", "routes-content"], handlerTags),
      L("api-routes", "api.* 路由", "app/routes/api.nemesis.ts", "资源路由", "仅 export loader/action 无 UI", ["routes-core", "nemesis-api"], handlerTags),
      L("auth-splat", "api.auth.$", "app/routes/api.auth.$.ts", "Better Auth 捕获", "splat 匹配 OAuth 回调", ["routes-core", "auth-session"], handlerTags),
      L("layout-route", "layout 路由", "app/routes/game.tsx", "父 layout 无 index", "子路由共享 shell", ["routes-core", "routes-nested"], handlerTags),
      L("routing-capstone", "路由 capstone", "app/routes/", "新增页面放哪", "新 URL 应对应哪个文件名", ["routes-core"], fullstackTags, "app/routes/api.nemesis.ts"),
    ],
  },
  {
    slug: "site-07-nested-layouts",
    title: "嵌套路由 game",
    description: "game.tsx 布局与 platform 动态段。",
    projectContext: "游戏区展示嵌套 layout + 动态参数用法。",
    difficulty: "intermediate",
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    orderIndex: 6,
    unitIndex: 2,
    remixModules: ["routes-nested"],
    lessons: [
      L("game-layout", "game layout", "app/routes/game.tsx", "游戏区父路由", "Outlet 渲染子平台页", ["routes-nested"], handlerTags),
      L("game-index", "game._index", "app/routes/game._index.tsx", "默认子页", "/game 列表或入口", ["routes-nested"], handlerTags),
      L("game-platform", "game.$platform", "app/routes/game.$platform.tsx", "动态平台", "params.platform 区分游戏", ["routes-nested"], loaderTags),
      L("game-loader", "平台 loader", "app/routes/game.$platform.tsx", "服务端数据", "按 platform 读配置或分数", ["routes-nested"], loaderTags),
      L("game-components", "游戏组件", "app/components/game/", "展示与交互", "路由薄、组件厚", ["routes-nested"], handlerTags, "app/components/game/GamePlatformPicker.tsx"),
      L("nested-capstone", "嵌套 capstone", "app/routes/game.tsx", "加新平台路由", "layout 与子文件如何增改", ["routes-nested"], fullstackTags),
    ],
  },
];

export const UNIT_04_SPECS: CourseSpec[] = [
  {
    slug: "site-08-home-landing",
    title: "首页落地页",
    description: "_index 与 components/home 区块。",
    projectContext: "首页聚合 GSAP、视频、歌词等多媒体区块。",
    difficulty: "intermediate",
    abilityTags: ["frontend.effect.useEffect", "frontend.state.local"],
    orderIndex: 7,
    unitIndex: 3,
    remixModules: ["routes-home"],
    lessons: [
      L("index-route-home", "首页路由", "app/routes/_index.tsx", "组装 home 组件", "路由文件保持精简", ["routes-home"], handlerTags),
      L("home-hero", "Hero 区块", "app/components/home/", "首屏视觉", "GSAP 或 motion 驱动动画", ["routes-home"], localTags, "app/components/home/HomeHero.tsx"),
      L("home-video", "视频区块", "app/components/home/", "懒加载媒体", "ClientOnly 包裹播放器", ["routes-home", "ui-client"], localTags, "app/components/home/video-showcase.tsx"),
      L("home-lyrics", "歌词/文字", "app/components/home/", "滚动或打字效果", "副作用清理防泄漏", ["routes-home"], localTags, "app/components/home/cyber-terminal.tsx"),
      L("home-data", "首页 loader 可选", "app/routes/_index.tsx", "静态 vs 动态", "多数内容可静态，少打 DB", ["routes-home"], loaderTags),
      L("home-capstone", "首页 capstone", "app/components/home/", "加新区块", "组件目录与 _index 导入关系", ["routes-home"], fullstackTags, "app/routes/_index.tsx"),
    ],
  },
  {
    slug: "site-09-gallery-updates",
    title: "内容展示页",
    description: "gallery、updates、cv、anime 等内容型路由。",
    projectContext: "内容页以展示为主，loader 提供列表或 Markdown 源。",
    difficulty: "intermediate",
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    orderIndex: 8,
    unitIndex: 3,
    remixModules: ["routes-content"],
    lessons: [
      L("gallery-route", "gallery 页", "app/routes/gallery.tsx", "作品集展示", "图片网格与灯箱", ["routes-content"], handlerTags),
      L("updates-route", "updates 页", "app/routes/updates.tsx", "动态/博客", "时间线或列表", ["routes-content"], loaderTags),
      L("cv-route", "cv 页", "app/routes/cv.tsx", "简历", "结构化段落", ["routes-content"], handlerTags),
      L("anime-route", "anime 页", "app/routes/anime.tsx", "番剧清单", "个人兴趣展示", ["routes-content"], handlerTags),
      L("shared-layout", "共享 Header", "app/components/ui/Header.tsx", "内容页导航", "各路由复用全站壳", ["routes-content", "ui-header"], handlerTags),
      L("content-capstone", "内容 capstone", "app/routes/gallery.tsx", "新内容栏目", "复制 gallery 模式建新路由", ["routes-content"], fullstackTags),
    ],
  },
  {
    slug: "site-10-chat-page",
    title: "聊天页面",
    description: "chat 路由与 Nemesis 客户端页。",
    projectContext: "chat 页挂载重量级客户端聊天 UI。",
    difficulty: "intermediate",
    abilityTags: ["frontend.state.local", "frontend.event.submit"],
    orderIndex: 9,
    unitIndex: 3,
    remixModules: ["routes-chat"],
    lessons: [
      L("chat-route", "chat.tsx", "app/routes/chat.tsx", "聊天路由壳", "导出默认页组件", ["routes-chat"], handlerTags),
      L("nemesis-page-client", "NemesisChatPage", "app/components/nemesis/chat/NemesisChatPage.client.tsx", "客户端主界面", ".client 后缀仅浏览器执行", ["routes-chat", "ui-client"], localTags),
      L("chat-loader", "chat loader 守门", "app/routes/chat.tsx", "可选登录检查", "未登录重定向或提示", ["routes-chat", "auth-session"], sessionTags),
      L("chat-meta", "页面 meta", "app/routes/chat.tsx", "title/description", "SEO 与分享卡片", ["routes-chat"], handlerTags),
      L("chat-layout", "聊天布局", "app/components/nemesis/chat/", "输入区与消息列表", "状态在 hook 内", ["routes-chat", "ui-state"], localTags, "app/components/nemesis/chat/NemesisChatPage.client.tsx"),
      L("chat-capstone", "聊天 capstone", "app/routes/chat.tsx", "改聊天入口", "route 与 client 组件边界", ["routes-chat"], fullstackTags),
    ],
  },
];

export const UNIT_05_SPECS: CourseSpec[] = [
  {
    slug: "site-11-ui-header",
    title: "全站 Header UI",
    description: "导航、主题切换与登录入口。",
    projectContext: "Header 连接主题 action、路由 Link 与 auth 状态。",
    difficulty: "beginner",
    abilityTags: ["frontend.event.click", "frontend.state.global"],
    orderIndex: 10,
    unitIndex: 4,
    remixModules: ["ui-header"],
    lessons: [
      L("header-nav", "导航链接", "app/components/ui/Header.tsx", "NavLink 列表", "高亮当前路由", ["ui-header"], handlerTags),
      L("header-theme", "主题按钮", "app/components/ui/Header.tsx", "提交 theme", "Form/fetcher 调 root", ["ui-header", "shell-theme"], actionTags),
      L("header-auth", "登录态展示", "app/components/ui/Header.tsx", "session 来自 root", "useRouteLoaderData root", ["ui-header", "auth-session"], sessionTags),
      L("header-mobile", "移动端菜单", "app/components/ui/Header.tsx", "局部 open 状态", "useState 控制抽屉", ["ui-header"], localTags),
      L("header-a11y", "可访问性", "app/components/ui/Header.tsx", "键盘与 aria", "按钮与导航语义", ["ui-header"], handlerTags),
      L("header-capstone", "Header capstone", "app/components/ui/Header.tsx", "加导航项", "改 Header 还是 root", ["ui-header"], fullstackTags),
    ],
  },
  {
    slug: "site-12-client-boundary",
    title: "客户端边界",
    description: "ClientOnly、lazy 与 .client.tsx 模式。",
    projectContext: "Worker SSR 不能把浏览器 API 打进服务端 bundle。",
    difficulty: "intermediate",
    abilityTags: ["frontend.effect.useEffect", "code.position.handler"],
    orderIndex: 11,
    unitIndex: 4,
    remixModules: ["ui-client"],
    lessons: [
      L("client-only", "ClientOnly", "app/components/common/ClientOnly.tsx", "挂载后再渲染", "避免 SSR 访问 window", ["ui-client"], localTags),
      L("dot-client", ".client 后缀", "app/components/nemesis/chat/NemesisChatPage.client.tsx", "构建时分离", "仅客户端打包路径", ["ui-client", "routes-chat"], handlerTags),
      L("lazy-import", "React.lazy", "app/root.tsx", "懒加载 Modal", "Suspense fallback", ["ui-client"], localTags),
      L("hydration-mismatch", "水合一致", "app/components/common/ClientOnly.tsx", "首屏占位", "服务端与客户端 DOM 对齐", ["ui-client"], localTags),
      L("browser-api", "浏览器 API", "app/hooks/useNemesisChat.client.ts", "localStorage/SSE", "放 client hook", ["ui-client", "ui-state"], localTags),
      L("client-capstone", "客户端 capstone", "app/components/common/ClientOnly.tsx", "新浏览器功能", "选 ClientOnly 还是 .client", ["ui-client"], fullstackTags),
    ],
  },
  {
    slug: "site-13-frontend-state",
    title: "前端状态与事件",
    description: "useNemesisChat 与表单提交链。",
    projectContext: "聊天状态、loading、error 派生自 hook。",
    difficulty: "intermediate",
    abilityTags: ["frontend.state.local", "frontend.event.submit"],
    orderIndex: 12,
    unitIndex: 4,
    remixModules: ["ui-state"],
    lessons: [
      L("nemesis-hook", "useNemesisChat", "app/hooks/useNemesisChat.client.ts", "聊天状态机", "messages、input、streaming", ["ui-state"], localTags),
      L("submit-chain", "发送消息", "app/hooks/useNemesisChat.client.ts", "POST api.nemesis", "fetch 与 SSE 解析", ["ui-state", "nemesis-api"], actionTags),
      L("session-storage", "会话列表", "app/hooks/useNemesisChat.client.ts", "localStorage", "多会话 id 持久化", ["ui-state"], localTags),
      L("loading-ui", "loading 派生", "app/components/nemesis/chat/", "禁用输入", "isLoading 控制按钮", ["ui-state"], localTags, "app/components/nemesis/chat/NemesisChatComposer.tsx"),
      L("error-state", "error 展示", "app/hooks/useNemesisChat.client.ts", "API 错误码", "映射用户可读文案", ["ui-state", "data-errors"], localTags),
      L("state-capstone", "状态 capstone", "app/hooks/useNemesisChat.client.ts", "加新 UI 状态", "hook vs 组件 state", ["ui-state"], fullstackTags),
    ],
  },
];

export const UNIT_06_SPECS: CourseSpec[] = [
  {
    slug: "site-14-loader-read",
    title: "Loader 读链",
    description: "root 与各路由 loader 如何读 cookie/DB。",
    projectContext: "读操作集中在 loader，避免客户端重复请求。",
    difficulty: "intermediate",
    abilityTags: ["bridge.reactRouter.loader", "backend.session.cookie"],
    orderIndex: 13,
    unitIndex: 5,
    remixModules: ["bridge-loader"],
    lessons: [
      L("loader-contract", "loader 约定", "app/root.tsx", "只读副作用", "不在 loader 写 cookie", ["bridge-loader"], loaderTags),
      L("cookie-read", "读 auth cookie", "app/root.tsx", "requestHasAuthSessionCookie", "条件读 session", ["bridge-loader", "auth-session"], sessionTags),
      L("db-read", "D1 读", "app/lib/db.server.ts", "prepare/bind", "getSessionCached 等", ["bridge-loader", "data-d1"], loaderTags),
      L("cache-headers-read", "缓存头", "app/lib/cache-headers.server.ts", "loader 返回 Cache-Control", "静态内容可 CDN", ["bridge-loader"], loaderTags),
      L("typed-loader", "useLoaderData", "app/root.tsx", "typeof loader", "类型安全消费", ["bridge-loader"], loaderTags),
      L("loader-capstone", "loader capstone", "app/root.tsx", "新全局数据", "加 root loader 字段影响面", ["bridge-loader"], fullstackTags),
    ],
  },
  {
    slug: "site-15-action-write",
    title: "Action 写链",
    description: "root action、api.nemesis POST 与 Set-Cookie。",
    projectContext: "写操作走 action 或 API route action。",
    difficulty: "intermediate",
    abilityTags: ["bridge.reactRouter.action", "backend.validation.field"],
    orderIndex: 14,
    unitIndex: 5,
    remixModules: ["bridge-action"],
    lessons: [
      L("root-action", "root action", "app/root.tsx", "theme 写入", "返回 redirect 或 json", ["bridge-action", "shell-theme"], actionTags),
      L("api-nemesis-post", "api.nemesis POST", "app/routes/api.nemesis.ts", "聊天请求体", "JSON 校验后转 Nemesis", ["bridge-action", "nemesis-api"], actionTags),
      L("request-body", "请求体解析", "app/routes/api.nemesis.ts", "request.json + unknown 收窄", "校验 message 与 recentMessages", ["bridge-action", "nemesis-api"], ["backend.validation.field"], "app/services/nemesis-guard.server.ts"),
      L("set-cookie", "Set-Cookie", "app/utils/theme.server.ts", "服务端写 cookie", "HttpOnly/SameSite 策略", ["bridge-action"], sessionTags),
      L("validation", "字段校验", "app/routes/api.nemesis.ts", "zod/手动检查", "缺字段 400", ["bridge-action"], ["backend.validation.field"]),
      L("cache-invalidate", "写后缓存", "app/lib/cache-headers.server.ts", "mutation 后", "避免 CDN 旧数据", ["bridge-action"], actionTags),
      L("action-capstone", "action capstone", "app/routes/api.nemesis.ts", "新 POST 字段", "action 与 service 分层", ["bridge-action"], fullstackTags),
    ],
  },
];

export const UNIT_07_SPECS: CourseSpec[] = [
  {
    slug: "site-16-auth-session",
    title: "认证与 Session",
    description: "Better Auth、session cookie 与 api.auth。",
    projectContext: "登录态由 Better Auth + D1 持久化。",
    difficulty: "advanced",
    abilityTags: ["backend.auth.required", "backend.session.cookie"],
    orderIndex: 15,
    unitIndex: 6,
    remixModules: ["auth-session"],
    lessons: [
      L("auth-server", "auth.server", "app/lib/auth.server.ts", "Better Auth 实例", "adapter 指向 D1", ["auth-session"], sessionTags),
      L("auth-route", "api.auth.$", "app/routes/api.auth.$.ts", "OAuth 回调", "catch-all 转发", ["auth-session"], sessionTags),
      L("session-cached", "getSessionCached", "app/lib/auth.server.ts", "缓存 session", "减少重复 DB", ["auth-session"], loaderTags),
      L("google-oauth", "Google 登录", "app/root.tsx", "googleClientId", "loader 注入客户端", ["auth-session"], sessionTags),
      L("protected-routes", "受保护页", "app/routes/chat.tsx", "登录守门", "loader 检查 session", ["auth-session"], sessionTags),
      L("auth-capstone", "认证 capstone", "app/lib/auth.server.ts", "加 OAuth 提供商", "auth 配置与路由", ["auth-session"], fullstackTags),
    ],
  },
  {
    slug: "site-17-guards-rate-limit",
    title: "守卫与限流",
    description: "nemesis-guard、rate-limit 与权限顺序。",
    projectContext: "API 链先认证再限流再业务。",
    difficulty: "advanced",
    abilityTags: ["backend.rateLimit", "backend.auth.required"],
    orderIndex: 16,
    unitIndex: 6,
    remixModules: ["auth-guards"],
    lessons: [
      L("guard-module", "nemesis-guard", "app/services/nemesis-guard.server.ts", "统一守门", "抽离鉴权逻辑", ["auth-guards"], guardTags),
      L("rate-limit", "限流", "app/services/nemesis-guard.server.ts", "IP/用户配额", "超限 429", ["auth-guards"], guardTags),
      L("guard-order", "守门顺序", "app/routes/api.nemesis.ts", "auth→limit→handler", "顺序错误会泄密", ["auth-guards", "nemesis-api"], guardTags),
      L("classifier-reason", "分类器理由", "app/services/nemesis-guard.server.ts", "Gemini 分类理由", "classifierReason 只进审计不回前端", ["auth-guards", "nemesis-api"], guardTags),
      L("audit-ctx-waitUntil", "审计与 waitUntil", "app/routes/api.nemesis.ts", "后台审计", "ctx.waitUntil 不阻塞主响应", ["auth-guards", "nemesis-api"], guardTags),
      L("error-responses", "守卫错误码", "app/routes/api.nemesis.ts", "401/403/429", "客户端可区分", ["auth-guards", "data-errors"], guardTags),
      L("admin-bypass", "特权分支", "app/services/nemesis-guard.server.ts", "可选管理员", "环境变量控制", ["auth-guards"], guardTags),
      L("guards-capstone", "守卫 capstone", "app/routes/api.nemesis.ts", "加新守卫", "guard 文件 vs 路由内联", ["auth-guards"], fullstackTags),
    ],
  },
];

export const UNIT_08_SPECS: CourseSpec[] = [
  {
    slug: "site-18-nemesis-api-chain",
    title: "Nemesis API 链",
    description: "api.nemesis 从请求到服务的完整链路。",
    projectContext: "个人网站 AI 聊天核心 HTTP 入口。",
    difficulty: "advanced",
    abilityTags: ["backend.auth.required", "bridge.reactRouter.action"],
    orderIndex: 17,
    unitIndex: 7,
    remixModules: ["nemesis-api"],
    lessons: [
      L("api-entry", "api.nemesis 入口", "app/routes/api.nemesis.ts", "export action", "仅 POST 处理", ["nemesis-api"], actionTags),
      L("parse-body", "解析 body", "app/routes/api.nemesis.ts", "messages 数组", "校验结构", ["nemesis-api"], ["backend.validation.field"]),
      L("call-guard", "调用 guard", "app/routes/api.nemesis.ts", "鉴权限流", "失败早返回", ["nemesis-api", "auth-guards"], guardTags),
      L("nemesis-service", "nemesis.server", "app/services/nemesis.server.ts", "业务编排", "prompt 与模型选择", ["nemesis-api", "nemesis-gateway"], handlerTags),
      L("feedback-route", "feedback API", "app/routes/api.nemesis-feedback.ts", "用户反馈", "旁路写 D1", ["nemesis-api", "data-d1"], actionTags),
      L("api-capstone", "API capstone", "app/routes/api.nemesis.ts", "加新 Nemesis 能力", "route vs service 切分", ["nemesis-api"], fullstackTags),
    ],
  },
  {
    slug: "site-19-nemesis-sse-gateway",
    title: "SSE 与 AI Gateway",
    description: "流式响应、网关代理与密钥隔离。",
    projectContext: "SSE 把模型 token 流推到浏览器。",
    difficulty: "advanced",
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.action"],
    orderIndex: 18,
    unitIndex: 7,
    remixModules: ["nemesis-sse", "nemesis-gateway"],
    lessons: [
      L("sse-server", "nemesis-sse.server", "app/lib/nemesis-sse.server.ts", "SSE 格式化", "text/event-stream", ["nemesis-sse"], handlerTags),
      L("stream-response", "流式 Response", "app/routes/api.nemesis.ts", "ReadableStream", "Worker 上流式转发", ["nemesis-sse", "nemesis-api"], actionTags),
      L("ai-gateway", "AI Gateway", "app/lib/nemesis-ai-gateway.server.ts", "模型代理", "API key 不暴露客户端", ["nemesis-gateway"], handlerTags),
      L("client-parse-sse", "客户端解析", "app/hooks/useNemesisChat.client.ts", "逐 chunk 追加", "onmessage 或 fetch reader", ["nemesis-sse", "ui-state"], localTags),
      L("prompts-catalog", "prompts/catalog", "app/nemesis/", "系统提示与分类", "改人格先找 catalog", ["nemesis-gateway"], handlerTags, "app/nemesis/system-prompt.server.ts"),
      L("sse-capstone", "SSE capstone", "app/lib/nemesis-ai-gateway.server.ts", "换模型提供商", "gateway 与环境变量", ["nemesis-gateway", "nemesis-sse"], fullstackTags),
    ],
  },
  {
    slug: "site-20-d1-errors-capstone",
    title: "D1 与错误 capstone",
    description: "migrations、db.server 与全站错误映射。",
    projectContext: "持久化与可观测性收尾，串联前 19 课。",
    difficulty: "advanced",
    abilityTags: ["project.modify.fullstack", "ai.review.architecture"],
    orderIndex: 19,
    unitIndex: 7,
    remixModules: ["data-d1", "data-errors"],
    lessons: [
      L("db-server", "db.server", "app/lib/db.server.ts", "D1 访问层", "统一 prepare 助手", ["data-d1"], loaderTags),
      L("migrations", "migrations", "migrations/", "表结构演进", "auth 与 learn 表", ["data-d1"], handlerTags, "migrations/0001_init.sql"),
      L("messages-route", "messages 页", "app/routes/messages.tsx", "历史消息 UI", "读 D1 会话", ["data-d1"], loaderTags),
      L("error-mapping", "错误映射", "app/hooks/useNemesisChat.client.ts", "用户文案", "技术错误→提示", ["data-errors"], localTags),
      L("cross-module", "跨模块改造", "app/routes/api.nemesis.ts", "端到端", "route→service→gateway→D1", ["data-d1", "nemesis-api", "data-errors"], fullstackTags),
      L("final-capstone", "毕业 capstone", "app/", "读懂 remix", "列举改聊天+主题+登录涉及的文件", ["data-d1", "data-errors", "nemesis-api"], fullstackTags, "app/routes/api.nemesis.ts"),
    ],
  },
];

export const ALL_COURSE_SPECS: CourseSpec[] = [
  ...UNIT_01_SPECS,
  ...UNIT_02_SPECS,
  ...UNIT_03_SPECS,
  ...UNIT_04_SPECS,
  ...UNIT_05_SPECS,
  ...UNIT_06_SPECS,
  ...UNIT_07_SPECS,
  ...UNIT_08_SPECS,
];
