/**
 * Real questions for site-18-nemesis / nemesis-service.
 *
 * Anchor: remix/app/services/nemesis.server.ts L741-900 (callNemesisModel +
 *          fallbackRoutes / shouldTryFallback / selectNemesisModel / routeDecisionFromQuery).
 * 学习目标: 多模型路由 + fallback 链 + 模型调用层, 跨 provider 设计.
 *
 * 题目数: 22.
 *
 * 引用 recipe: nemesisGrokFallbackBreak (§11.3-8).
 */

import { q } from "../../types";
import type { RealQ } from "../index";
import { nemesisGrokFallbackBreak } from "../recipes";

const PRIMARY = "app/services/nemesis.server.ts";
const TOUCHED = [PRIMARY, "app/routes/api.nemesis.ts", "app/lib/nemesis-ai-gateway.server.ts"];

export const nemesisServiceQuestions: RealQ[] = [
  q({
    type: "single_choice",
    title: "Q1 callNemesisModel 角色",
    prompt: "callNemesisModel 是 nemesis.server 的什么?",
    options: [
      { id: "A", text: "多 provider (Gemini / DeepSeek / Grok) 主入口, 内部路由 + fallback 链 + onProgress 回调" },
      { id: "B", text: "守门" },
      { id: "C", text: "D1" },
      { id: "D", text: "无" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "callNemesisModel 是 nemesis.server 主入口, 多 provider 路由 + fallback + onProgress.",
      detail: "callNemesisModel 接受 env / message / recentMessages / responseMode / onProgress, 内部 selectNemesisModel 选 primary, fallbackRoutes 拼 fallback 链, 循环尝试, onProgress emit status / fallback / generate / done 事件给前端.",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q2 NemesisModelRoute 含义",
    prompt: "NemesisModelRoute 字面量值?",
    options: [
      { id: "A", text: "'gemini_lite' | 'gemini_flash' | 'grok_roast' | 'grok_complex' | 'deepseek' 等" },
      { id: "B", text: "string" },
      { id: "C", text: "boolean" },
      { id: "D", text: "无" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "NemesisModelRoute 是字面量联合, 多个 provider × 多个用途的路由组合.",
      detail: "字面量联合让 TS 编译期强制 exhaustive switch, 涵盖主分类 (gemini_lite / gemini_flash) + Grok 特殊 (grok_roast / grok_complex) + DeepSeek 兜底 (deepseek). 受控 union 防止任意 string 注入.",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q3 selectNemesisModel 作用",
    prompt: "selectNemesisModel 作用?",
    options: [
      { id: "A", text: "根据 message + recentMessages + queryType 选择最合适的 primary 模型 (Gemini lite / flash / Grok / DeepSeek)" },
      { id: "B", text: "无" },
      { id: "C", text: "TS" },
      { id: "D", text: "装饰" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "selectNemesisModel 选最合适 primary 模型, 基于 query 类型 / 上下文 / 路由策略.",
      detail: "selectNemesisModel 内部用 routeDecisionFromQuery + forceRouteFromEnv + 各类规则, 决定主模型是 gemini_lite / flash / Grok. 返回 RouteDecision 含 provider / model / route / reason / queryType / quoteTags / quoteIntensity.",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank",
    title: "Q4 fallbackRoutes(gemini_flash) 返回",
    prompt: "fallbackRoutes('gemini_flash') 返回? (数组, 顺序)",
    options: [],
    correctAnswer: { values: { v: "['gemini_lite', 'deepseek']" } },
    blanks: [{ id: "v", placeholder: "数组", acceptedAnswers: ["['gemini_lite', 'deepseek']", "gemini_lite, deepseek", "gemini_lite 然后 deepseek"] }],
    explanation: {
      short: "fallbackRoutes('gemini_flash') = ['gemini_lite', 'deepseek'], flash 失败先 lite, lite 失败再 deepseek.",
      detail: "fallbackRoutes 链式 fallback: gemini_flash 失败 → gemini_lite (降级但同 provider) → deepseek (跨 provider). 顺序是工程权衡, 同 provider 优先 (保留 Gemini 风格), 跨 provider 兜底 (避开 Gemini quota).",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "multi_choice",
    title: "Q5 fallbackRoutes 行为",
    prompt: "fallbackRoutes 的设计? (多选)",
    options: [
      { id: "A", text: "Grok 路由 (roast / complex) 没有 fallback, 因为 persona 必须保持, fallback 会破坏体验" },
      { id: "B", text: "gemini_lite 失败 → deepseek (跨 provider)" },
      { id: "C", text: "gemini_flash 失败 → gemini_lite → deepseek (链式)" },
      { id: "D", text: "deepseek 失败 → ? (无 fallback)" },
    ],
    correctAnswer: { choiceIds: ["A", "B", "C"] },
    explanation: {
      short: "Grok 无 fallback (persona), gemini_lite → deepseek, gemini_flash → lite → deepseek 链式.",
      detail: "Grok 路由返回 [], 是设计选择: persona 体验必须保持, fallback 到 Gemini / DeepSeek 会让用户感觉是另一个人. gemini_lite 跨 provider fallback 到 deepseek, gemini_flash 同 provider 降级再跨 provider. 是'用户体验优先'与'成本 / 可用性'的工程权衡.",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q6 shouldTryFallback 状态码",
    prompt: "shouldTryFallback 检查的状态码?",
    options: [
      { id: "A", text: "400 / 404 / 429 / 500 / 502 / 503 / 504, 临时的或 client error 触发 fallback" },
      { id: "B", text: "always" },
      { id: "C", text: "TS" },
      { id: "D", text: "无" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "shouldTryFallback 检查 400/404/429/500/502/503/504, 临时或 client error 触发 fallback, 永久错误 (401/403) 不 fallback.",
      detail: "状态码选择: 400 (bad request 模型 input) / 404 (model not found) / 429 (rate limit) / 5xx (server) 都 fallback. 401/403 (auth 错误) 不 fallback, 失败重试不会改变结果. 是'临时性错误 vs 永久性错误'的工程判断.",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "line_pick",
    title: "Q7 关键行: attempts 链",
    prompt: "const attempts = [primary, ...fallbackRoutes(primary.route).map(route => routeToDecision(route, 'Fallback route'))] 出现在 callNemesisModel 哪一行?",
    code: `1 export async function callNemesisModel(input: {...}) {
2   const primary = await selectNemesisModel(input);
3   input.onProgress?.({...});
9
10  const attempts = [primary, ...fallbackRoutes(primary.route).map((route) => routeToDecision(route, "Fallback route"))];`,
    options: [],
    linePickLines: [
      { id: "L2", lineNumber: 2, text: "const primary = await selectNemesisModel(input);" },
      { id: "L10", lineNumber: 10, text: "const attempts = [primary, ...fallbackRoutes(primary.route).map((route) => routeToDecision(route, 'Fallback route'))];" },
    ],
    correctAnswer: { lineId: "L10" },
    explanation: {
      short: "第 10 行 attempts 数组 = [primary, ...fallbackRoutes], 拼成主 + fallback 调用链.",
      detail: "attempts 把 primary 放在第一位, 后面拼接 fallback 链. 循环 try each, 第一个成功的 break, 全部失败抛错. routeToDecision 给每个 fallback route 加 'Fallback route' reason 标记.",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q8 onProgress 事件类型",
    prompt: "onProgress 回调 emit 的 step 字段?",
    options: [
      { id: "A", text: "'route' / 'fallback' / 'generate' / 'done' (4 种进度状态)" },
      { id: "B", text: "无" },
      { id: "C", text: "TS" },
      { id: "D", text: "无" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "onProgress step 4 种: 'route' (选模型) / 'fallback' (尝试 fallback) / 'generate' (主模型生成) / 'done' (完成).",
      detail: "4 步进度让前端能展示'正在路由 → 正在 fallback → 正在生成 → 完成', 用户感知到 AI 在做什么. 是流式 UX 的标准设计.",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q9 responseMode 决定 quote",
    prompt: "responseMode === 'normal' 时 selectNemesisQuoteCandidates, 'roast' 时?",
    options: [
      { id: "A", text: "quoteCandidates = [] (Grok roast 不用 quote, 用 roast persona)" },
      { id: "B", text: "无" },
      { id: "C", text: "TS" },
      { id: "D", text: "无" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "responseMode='roast' (Grok) 时 quoteCandidates = [], roast 模式不用 quote, 用 roast persona.",
      detail: "Grok roast 是 persona 风格 (辛辣 / 吐槽), 引用歌词破坏 persona 一致性. quoteCandidates 留空, 主模型走纯 persona. 同样是 Grok 的 grok_complex 也不 quote.",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "multi_choice",
    title: "Q10 fallback 重试链循环",
    prompt: "for (let attemptIndex = 0; attemptIndex < attempts.length; attemptIndex += 1) 循环行为? (多选)",
    options: [
      { id: "A", text: "每个 attempt 是 primary 或 fallback, 顺序尝试" },
      { id: "B", text: "成功 break, 失败继续, 全部失败抛错" },
      { id: "C", text: "attemptIndex > 0 时 emit fallback 状态" },
      { id: "D", text: "无" },
    ],
    correctAnswer: { choiceIds: ["A", "B", "C"] },
    explanation: {
      short: "循环尝试每个 attempt, 成功 break, 失败继续, 全部失败抛错, attemptIndex>0 时 emit fallback 状态.",
      detail: "循环: 第一次 try primary, 失败记录 errors, 第二次 try fallback (emit fallback running 状态), 直到成功或全部失败. shouldTryFallback 决定哪些错误触发 fallback. 全部失败抛 AggregateError 或最后一次错误.",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q11 modelResult 含字段",
    prompt: "callNemesisModel 返回的 result 不含?",
    options: [
      { id: "A", text: "secret (模型 secret)" },
      { id: "B", text: "text (回复)" },
      { id: "C", text: "provider (Gemini / DeepSeek / Grok)" },
      { id: "D", text: "model (具体模型)" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "result 不含 secret, secret 留在 server 端, 客户端 / D1 审计永远拿不到.",
      detail: "result 是公开字段: text / provider / model / route / queryType / fallbackUsed / fallbackChain / finishReason / incomplete. secret (API key / token) 是 server-only, 永远不进 result, 防止 secret 泄露到客户端 / audit / SSE 事件.",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace",
    title: "Q12 gemini_flash 失败 fallback 完整路径",
    prompt: "gemini_flash 失败 → fallback gemini_lite → 也失败 → fallback deepseek → 成功, 完整路径?",
    options: [
      { id: "primary", text: "selectNemesisModel 选 gemini_flash (attempt 0)" },
      { id: "try-flash", text: "callGemini flash 失败 (429 quota), 记录 errors" },
      { id: "fallback-1", text: "emit fallback running, attempt 1 = gemini_lite" },
      { id: "try-lite", text: "callGemini lite 失败 (500), 记录 errors" },
      { id: "fallback-2", text: "emit fallback running, attempt 2 = deepseek" },
      { id: "try-deep", text: "callDeepSeek 成功, 返回 result" },
    ],
    correctAnswer: { pathIds: ["primary", "try-flash", "fallback-1", "try-lite", "fallback-2", "try-deep"] },
    explanation: {
      short: "primary flash → fail 429 → fallback 1 lite → fail 500 → fallback 2 deepseek → success.",
      detail: "完整 fallback 链: 3 次尝试, 1-2 都失败, 第 3 个成功. errors 记录前两次失败, 管理员 audit 看到完整 fallback 链. 用户感受到'系统有点慢, 但能正常工作'.",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace",
    title: "Q13 roast persona 路径",
    prompt: "用户问'吐槽我', grok_roast 路径?",
    options: [
      { id: "select", text: "selectNemesisModel 选 grok_roast" },
      { id: "no-quote", text: "quoteCandidates = [], friendVisitHint = null" },
      { id: "roast-mode", text: "responseMode = 'roast'" },
      { id: "no-fallback", text: "fallbackRoutes('grok_roast') = [], 只有 1 个 attempt" },
    ],
    correctAnswer: { pathIds: ["select", "no-quote", "roast-mode", "no-fallback"] },
    explanation: {
      short: "select grok_ast → no quote → roast mode → no fallback.",
      detail: "Grok roast 路径: selectNemesisModel 选 grok_roast → 不用 quote (persona 一致) → responseMode='roast' → fallbackRoutes 返回 [] (persona 必须保持), attempts 数组只有 1 个, 失败就直接抛错, 不 fallback.",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q14 全部 fallback 失败时",
    prompt: "primary + 全部 fallback 都失败, 行为?",
    options: [
      { id: "A", text: "抛最后一次错误, api.nemesis.ts catch 处理, emit error 友好提示" },
      { id: "B", text: "no-op" },
      { id: "C", text: "整站 500" },
      { id: "D", text: "无" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "全部失败抛错, api.nemesis.ts catch 处理, emit error 友好提示, 用户看到 'AI 暂时无法响应'.",
      detail: "callNemesisModel 抛最后一次错误, api.nemesis.ts catch 收到, NemesisModelError emit error + error.message, 其他错误 console.error + emit 'Nemesis 暂时无法响应, 请稍后再试'. 记录 audit, 用户感知到失败但不是整站 500.",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/routes/api.nemesis.ts"],
  }),
  q({
    type: "single_choice",
    title: "Q15 模型选择被 env 强制时",
    prompt: "forceRouteFromEnv() 强强制 route, 行为?",
    options: [
      { id: "A", text: "env 配置 NEMESIS_FORCE_ROUTE 时 selectNemesisModel 跳过自动选择, 强制走该 route" },
      { id: "B", text: "无" },
      { id: "C", text: "TS" },
      { id: "D", text: "无" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "env NEMESIS_FORCE_ROUTE 配置时跳过 selectNemesisModel 自动选择, 强制走该 route.",
      detail: "forceRouteFromEnv 读 env NEMESIS_FORCE_ROUTE, 配置时跳过 query 分析, 直接返回该 route. 用于 (1) 调试某模型 (2) 紧急回滚 (3) 性能压测. 是 ops 友好的设计.",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "ai_review",
    title: "Q16 AI 给 Grok 也加 deepseek fallback",
    prompt: "AI 改坏: AI 觉得 'Grok 也需要兜底' 给 grok_roast / grok_complex 也加 ['deepseek'] fallback. 后果是? (timu.MD §11.3-8)",
    options: [
      { id: "A", text: "roast / complex 失败 fallback 到 DeepSeek, 失去 persona 一致性, 用户看到吐槽风格被 Gemini / DeepSeek 替换" },
      { id: "B", text: "更稳定" },
      { id: "C", text: "更兼容" },
      { id: "D", text: "无影响" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "roast / complex 失败 fallback 到 DeepSeek, persona 漂移, 用户看到吐槽风格被替换.",
      detail: "timu.MD §11.3-8 经典反例: Grok roast 有专门 persona (辛辣 / 吐槽), fallback 到 Gemini / DeepSeek 让用户感觉是另一个人. fallback 改变 route contract, 体验与审计双崩. 应该让 Grok 路由没有 fallback, 失败抛错让 ops 介入.",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
    realWorldImpact: "用户选 'roast 风格' 拿到的是 DeepSeek 输出, 风格与承诺不一致, 安全 prompt 不生效.",
    aiReviewRisk: "把'便宜'当默认 fallback 依据, 忽略 route / persona 设计契约.",
    wrongAnswerFeedback: {
      B: "更稳定是反话, persona 漂移.",
      C: "更兼容是反话, route contract 改变.",
      D: "有严重体验影响.",
    },
  }),
  q({
    type: "ai_review",
    title: "Q17 AI 删 shouldTryFallback 全部 fallback",
    prompt: "AI 改坏: AI 觉得 'fallback 复杂' 删 shouldTryFallback, 任何错误都 fallback. 后果是?",
    options: [
      { id: "A", text: "401/403 auth 错误也 fallback, 浪费 quota, 用户看到 401 错误信息被 fallback 屏蔽" },
      { id: "B", text: "TS 报错" },
      { id: "C", text: "更稳定" },
      { id: "D", text: "无影响" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "401/403 auth 错误也 fallback, 浪费 quota, 401 错误被 fallback 屏蔽.",
      detail: "shouldTryFallback 设计'临时性错误 fallback, 永久性错误不 fallback'. 401 (auth) / 403 (forbidden) 永久错误 fallback 不会改变结果, 只是浪费 quota + 延迟. AI 删了守卫后, 用户 auth 失败也会触发 fallback, 体验糟 + 成本涨.",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
    realWorldImpact: "用户 auth 错误触发 1-N 次 fallback 浪费 quota, 401 信息被屏蔽, 体验糟.",
    aiReviewRisk: "为'稳定'全部 fallback, 失去临时性 vs 永久性错误区分.",
    wrongAnswerFeedback: {
      B: "TS 不会报错.",
      C: "全部 fallback 不更稳定.",
      D: "有性能与体验影响.",
    },
  }),
  q({
    type: "ai_review",
    title: "Q18 AI 把 result 里的 secret 字段加上",
    prompt: "AI 改坏: AI 觉得 '调试需要' 把 result 加 secret: apiKey 字段. 后果是?",
    options: [
      { id: "A", text: "secret 暴露到客户端 + D1 audit, 任何人能读到, 严重安全事件" },
      { id: "B", text: "TS 报错" },
      { id: "C", text: "更可调试" },
      { id: "D", text: "无影响" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "secret 暴露到客户端 + D1 audit, 任何人能读到 API key, 严重安全事件.",
      detail: "result 是公开字段, 客户端 SSE 事件 + D1 audit 都会拿到. 加 secret 字段等于把 API key 暴露到 (1) 客户端 window.__remixContext (2) 任何浏览器的 dev tools (3) D1 audit 表 (4) Cloudflare logs. 攻击者拿到 API key 立刻可以调 Gemini / DeepSeek / Grok 浪费你的 quota.",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
    realWorldImpact: "API key 暴露, 攻击者刷 Gemini / DeepSeek / Grok 配额, 你的账单暴涨 + 攻击者免费用.",
    aiReviewRisk: "为'调试'把 secret 暴露, 严重泄露.",
    wrongAnswerFeedback: {
      B: "TS 不会报错.",
      C: "调试方便不是暴露 secret 的理由.",
      D: "有灾难性安全影响.",
    },
  }),
  q({
    type: "ai_review",
    title: "Q19 引用 §11.3-8 Grok 默认 fallback 漂移",
    prompt: nemesisGrokFallbackBreak({
      lessonSlug: "nemesis-service",
      courseSlug: "site-18-nemesis-api-chain",
      orderIndex: 18,
    }).prompt,
    options: nemesisGrokFallbackBreak({
      lessonSlug: "nemesis-service",
      courseSlug: "site-18-nemesis-api-chain",
      orderIndex: 18,
    }).options,
    correctAnswer: nemesisGrokFallbackBreak({
      lessonSlug: "nemesis-service",
      courseSlug: "site-18-nemesis-api-chain",
      orderIndex: 18,
    }).correctAnswer as { choiceId: "string" },
    explanation: nemesisGrokFallbackBreak({
      lessonSlug: "nemesis-service",
      courseSlug: "site-18-nemesis-api-chain",
      orderIndex: 18,
    }).explanation,
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
    realWorldImpact: "roast / complex 失败 fallback 到 DeepSeek, 失去 persona 一致性, route contract 改变.",
    aiReviewRisk: "把'便宜'当默认 fallback 依据, 忽略 route / persona 设计契约.",
    wrongAnswerFeedback: nemesisGrokFallbackBreak({
      lessonSlug: "nemesis-service",
      courseSlug: "site-18-nemesis-api-chain",
      orderIndex: 18,
    }).wrongAnswerFeedback ?? {},
  }),
  q({
    type: "ai_review",
    title: "Q20 AI 删 onProgress 回调",
    prompt: "AI 改坏: AI 觉得 '前端不需要进度' 删 onProgress 调用. 后果是?",
    options: [
      { id: "A", text: "前端拿不到 status / fallback / generate 进度, 用户看到空白直到 done, 体验退步" },
      { id: "B", text: "TS 报错" },
      { id: "C", text: "更简洁" },
      { id: "D", text: "无影响" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "前端拿不到 status / fallback 进度, 用户看到空白直到 done, 体验退步.",
      detail: "onProgress 是流式 UX 的核心, 删了用户看不到 '正在路由 → 正在生成 → 完成' 进度, 空白 1-3 秒才出结果, 体验糟. 长任务 (主模型 + fallback) 必须有进度反馈.",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
    realWorldImpact: "用户每次查询看到 1-3 秒空白, 体验退步, 不像 AI 在思考, 怀疑网站崩了.",
    aiReviewRisk: "为'简洁'删 onProgress, 失去流式 UX 的进度反馈.",
    wrongAnswerFeedback: {
      B: "TS 不会报错.",
      C: "删回调不是简洁.",
      D: "有体验影响.",
    },
  }),
  q({
    type: "free_explain",
    title: "Q21 解释多 provider 路由 + fallback 链设计",
    prompt: "用自己的话解释为什么 (1) 多 provider (Gemini / DeepSeek / Grok) (2) selectNemesisModel 自动路由 (3) fallbackRoutes 链式 (4) shouldTryFallback 区分状态码 (5) Grok 无 fallback, 这 5 个设计一起形成完整的可用性 + 成本 + 体验设计.",
    options: [],
    correctAnswer: {
      text: "5 个设计协作: (1) 多 provider: 避免单点故障, 跨 provider 模型能力差异. (2) selectNemesisModel: 根据 query 类型智能路由, 复杂任务用 Gemini Flash, 简单任务用 Gemini Lite, persona 走 Grok. (3) fallbackRoutes 链式: 主失败后同 provider 降级再跨 provider 兜底, 避免一失败就跳到不同 persona. (4) shouldTryFallback: 区分临时 (429/5xx) vs 永久 (401/403) 错误, 临时触发 fallback, 永久直接抛错节省 quota. (5) Grok 无 fallback: persona 必须保持一致, fallback 改变 route contract 破坏体验. 5 个设计合在一起形成 '智能路由 + 链式兜底 + persona 一致' 的完整体系.",
    },
    explanation: {
      short: "5 个设计协作: 多 provider + 智能路由 + 链式兜底 + 状态码区分 + persona 一致.",
      detail: "5 个设计互相依赖, 任何一项被破坏都破坏整体: 删智能路由 = 所有查询都走 Gemini 浪费成本; 删 fallback = 单点故障; 删状态码区分 = 永久错误浪费 quota; 给 Grok 加 fallback = persona 漂移.",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "free-response",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "review_comment",
    title: "Q22 一句 PR review",
    prompt: "PR 把 fallbackRoutes('grok_roast') 改成 ['deepseek'], 写一条 review comment (1-2 句).",
    options: [],
    correctAnswer: {
      comment: "Grok roast / complex 路由设计为无 fallback, 因为 persona (辛辣 / 吐槽) 必须保持一致, fallback 到 DeepSeek 让用户感觉是另一个人, route contract 也改变 (timu.MD §11.3-8 经典反例). 必须保留 Grok 无 fallback, 失败抛错让 ops 介入, 而不是 fallback 隐藏问题.",
    },
    explanation: {
      short: "审查点: Grok persona 必须保持, 不可以 fallback.",
      detail: "好的 review 指出 (1) timu.MD §11.3-8 反例 (2) persona 一致性 (3) route contract 不变 (4) 给出明确保留.",
    },
    abilityTags: ["ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "free-response",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
];
