/**
 * Real questions for site-03-entry-server / bot-detection.
 * Anchor: remix/app/entry.server.tsx
 *   - import { isbot } from "isbot"
 *   - if (isbot(request.headers.get("user-agent") || "")) { await body.allReady; }
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/entry.server.tsx";

export const botDetectionQuestions: RealQ[] = [
  q({
    type: "single_choice",
    title: "Q1 isbot 包名",
    prompt: "顶部 import 写 `import { isbot } from \"____ \"`——这是哪种 import？",
    options: [
      { id: "A", text: "命名导入（named import）从 npm 包 isbot——package.json 里 \"isbot\": \"^5.1.28\"" },
      { id: "B", text: "默认导入" },
      { id: "C", text: "动态 import" },
      { id: "D", text: "TypeScript-only 类型导入" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "isbot v5 改成命名导出，v3 是默认导出。注意版本不同写法不同。",
      detail: "如果你升级到 v5+ 还写 `import isbot from 'isbot'`，运行时会拿到 undefined，调用就 TypeError。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank",
    title: "Q2 完整调用",
    prompt: "请补全代码：if (isbot(request.headers.get(\"____ \") || \"\")) { await body.____ ; }",
    options: [],
    blanks: [
      { id: "h", placeholder: "header 名", acceptedAnswers: ["user-agent", "User-Agent", "USER-AGENT"] },
      { id: "p", placeholder: "属性名", acceptedAnswers: ["allReady"] },
    ],
    correctAnswer: { type: "fill_blank", values: { h: "user-agent", p: "allReady" } },
    explanation: {
      short: "user-agent 头 → isbot 判定 → 等 body.allReady。",
      detail: "Headers.get 是 case-insensitive 的，写 user-agent 或 User-Agent 都行。allReady 是 ReadableStream 在 react-dom/server.browser 上扩展的属性。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q3 || \"\" 的作用",
    prompt: "代码 isbot(request.headers.get(\"user-agent\") || \"\")——`|| \"\"` 是为了？",
    options: [
      { id: "A", text: "headers.get 找不到时返回 null，isbot 不接受 null（TS 类型 + 运行时都不友好），用空串兜底" },
      { id: "B", text: "强制转为字符串" },
      { id: "C", text: "防止 user-agent 含 undefined 字面量" },
      { id: "D", text: "ESLint 规则要求" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "Headers.get 找不到键返回 null；isbot 期望 string，给 null 会抛或行为未定义。",
      detail: "现代浏览器都会发 User-Agent，但 fetch from server-side 或某些隐私扩展会移除——这一行是健壮性兜底。",
    },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q4 为什么 bot 要等 allReady",
    prompt: "isbot 为 true 时为什么必须 await body.allReady？",
    options: [
      { id: "A", text: "搜索引擎爬虫拿到流式 HTML 通常只读「Shell」就走（Suspense 边界还没填好），导致索引到的是空 fallback；阻塞等所有 boundary 完成 → 拿到完整 HTML → 索引正确" },
      { id: "B", text: "isbot 库要求" },
      { id: "C", text: "Cloudflare 限制" },
      { id: "D", text: "为了反爬虫，故意拖慢" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "爬虫不会等动态填充，allReady 让 HTML 全 ready 再返回。",
      detail: "用户路径下我们不等是为 TTFB（First Byte 越快越好），但爬虫不在乎 TTFB，在乎能不能拿到完整可索引内容。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false",
    title: "Q5 普通用户也 await allReady",
    prompt: "判断：把 isbot 检查删掉、所有请求都 await body.allReady，对用户体验影响很小（CF Worker 反正在 SSR）。",
    correctAnswer: { value: false },
    explanation: {
      short: "错——会显著恶化 TTFB（First Byte 时间），用户感知首屏变慢。",
      detail: "流式 SSR 的核心收益就是「shell 一就绪立即开始往浏览器吐字节」，浏览器边接边解析。allReady 阻塞会把这个收益吃掉。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace",
    title: "Q6 Googlebot 完整路径",
    prompt: "Googlebot UA = \"Mozilla/5.0 (compatible; Googlebot/2.1; ...)\" 访问 / 时，handleRequest 路径？",
    options: [
      { id: "s1", text: "1. setRuntimeEnv" },
      { id: "s2", text: "2. .well-known 检查 → false 继续" },
      { id: "s3", text: "3. let didError = false" },
      { id: "s4", text: "4. const body = await renderToReadableStream(...) → 拿到 ReadableStream" },
      { id: "s5", text: "5. isbot(UA) === true → await body.allReady（阻塞直到所有 Suspense 完成）" },
      { id: "s6", text: "6. responseHeaders.set Content-Type" },
      { id: "s7", text: "7. return new Response(body, ...)" },
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7"] },
    explanation: {
      short: "用户 vs bot 唯一差别就是 step 5——bot 多一个 await。",
      detail: "实测 bot 路径比用户路径慢 100-1000ms 不等，取决于页面有多少 Suspense 边界。",
    },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q7 没 UA 的请求",
    prompt: "如果 user-agent 头被删（UA = null），isbot('') 返回什么、走哪条路径？",
    options: [
      { id: "A", text: "isbot('') === false → 走用户路径（不 await allReady）" },
      { id: "B", text: "isbot('') === true → 当 bot 处理" },
      { id: "C", text: "抛 TypeError" },
      { id: "D", text: "返回 undefined" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "空串走用户路径——isbot 对空串返 false。",
      detail: "策略是「保守地把没特征的当用户」，避免误把内部健康检查（无 UA）当 bot 阻塞 5 秒。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q8 自定义爬虫识别",
    prompt: "团队内部脚本想抓 SSR 完整 HTML（不是流式），UA 设为 \"Mozilla/5.0\"。当前代码会怎么处理？",
    options: [
      { id: "A", text: "走用户路径（流式）——脚本拿到的是渐进 HTML，可能 Suspense fallback 还在原位；解决：脚本带特定 UA 如 \"FullPageSnapshotBot/1.0\"，触发 isbot 走 allReady 分支" },
      { id: "B", text: "自动识别为 bot" },
      { id: "C", text: "抛错拒绝" },
      { id: "D", text: "Cloudflare 拦截" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "想要完整 HTML 抓取就把自己声明成 bot UA。",
      detail: "isbot 库识别一长串爬虫 UA 模式（包括 Bot、Crawler、Spider、Snapshot 等关键字）；自定义命名时带这些就行。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q9 isbot 性能",
    prompt: "isbot 在每个请求都被调一次。性能开销？",
    options: [
      { id: "A", text: "极低——内部主要是几次正则 match，复杂度 O(UA 长度)，对 Worker 来说几乎 0 成本" },
      { id: "B", text: "高，需要联网查询" },
      { id: "C", text: "高，需要查 D1" },
      { id: "D", text: "中，需要解析 JSON" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "纯字符串匹配，无 IO，可忽略。",
      detail: "v5 库代码 ~5KB，匹配规则在 module load 时编译好。Worker 上每请求成本 < 0.1ms。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "code_fix",
    title: "Q10 反向逻辑",
    prompt: "代码被改成：if (!isbot(...)) await body.allReady; 这等于让用户阻塞、bot 流式。修正建议？",
    code: `if (!isbot(request.headers.get("user-agent") || "")) {\n  await body.allReady;\n}`,
codeFixBaseline: `if (!isbot(request.headers.get("user-agent") || "")) {\n  await body.allReady;\n}`,
correctAnswer: { patchedCode: "去掉感叹号：if (isbot(...))。当前写法把策略反了——用户 TTFB 大涨，bot 反而拿到流式（爬虫不读流，索引会破）。修复：恢复 if (isbot(...)) await body.allReady;。" },
explanation: { short: "见下方解释。", detail: "去掉感叹号：if (isbot(...))。当前写法把策略反了——用户 TTFB 大涨，bot 反而拿到流式（爬虫不读流，索引会破）。修复：恢复 if (isbot(...)) await body.allReady;。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q11 Headers.get 大小写",
    prompt: "request.headers.get(\"User-Agent\") 和 request.headers.get(\"user-agent\")——结果有差吗？",
    options: [
      { id: "A", text: "无差——Fetch API 的 Headers.get 是 case-insensitive，规范定义如此" },
      { id: "B", text: "User-Agent 才能拿到" },
      { id: "C", text: "user-agent 才能拿到" },
      { id: "D", text: "看浏览器实现" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "Headers 是 case-insensitive，规范行为。",
      detail: "底层都标准化为小写存。代码写 \"user-agent\" 是常见约定，但写 \"User-Agent\" 也对。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "position_judgement",
    title: "Q12 决策：把 isbot 移到 worker.ts",
    prompt: "提案：在 worker.ts 入口就检查 isbot，bot 直接转给一个专门的 prerender Worker。当前代码移除 isbot。是否合理？",
    options: [
      { id: "A", text: "合理但成本高——需要部署第二个 Worker、维护两份代码；当前把 bot 处理收在 entry.server 单点是「省事 + 收益足够」的工程权衡" },
      { id: "B", text: "完全没必要" },
      { id: "C", text: "Cloudflare 不允许 Worker 间转发" },
      { id: "D", text: "isbot 必须在 entry.server" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "技术上可行但工程开销大，目前规模不值。",
      detail: "等到流量到几百万 SSR/日且 SEO/抓取流量占比高，才需要单独 prerender。小到中型站 entry.server 处理就好。",
    },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false",
    title: "Q13 isbot 也能识别社交分享卡",
    prompt: "判断：Twitter/Facebook/Slack 抓 OG meta 时的 UA（Twitterbot, facebookexternalhit, Slackbot 等）isbot 能识别。",
    correctAnswer: { value: true },
    explanation: {
      short: "对——这些主流平台 UA 都在 isbot 规则里。",
      detail: "意味着分享链接拿到的 OG 卡片是「allReady 后的完整 HTML」，预览能正确读到 <meta property=\"og:title\"> 等。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q14 isbot 误判用户",
    prompt: "极端情况：用户的浏览器扩展把 UA 改成包含 \"bot\" 关键字。当前代码后果？",
    options: [
      { id: "A", text: "用户被识别为 bot，TTFB 慢一些（多等 SSR allReady），其他无影响——内容渲染正常" },
      { id: "B", text: "用户看到错误页" },
      { id: "C", text: "服务器拒绝服务" },
      { id: "D", text: "客户端 JS 不执行" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "误判代价 = 几百毫秒 TTFB；功能没坏。",
      detail: "客户端 hydration 还是会执行（HTML 完整 + 客户端 bundle 加载）；用户感知只是首屏稍慢。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "multi_choice",
    title: "Q15 改用 isbot，要做什么",
    prompt: "你想换掉 isbot 库为自己的简单实现 const isBot = (ua) => /bot|crawler/i.test(ua)。要承受哪些代价？(多选)",
    options: [
      { id: "A", text: "漏掉 isbot v5 维护的几百个常见 bot UA 模式（特别是 Slack、LinkedIn、Discord 这类社交分享）" },
      { id: "B", text: "误判用户里 UA 含 \"crawler\" 字符的（比如名为 \"DataCrawler/1.0\" 的合法工具）" },
      { id: "C", text: "维护负担：每出现新 bot UA 都得自己更新规则" },
      { id: "D", text: "性能反而显著下降（自写正则比 isbot 慢）" },
      { id: "E", text: "Cloudflare 拒绝部署" },
    ],
    correctAnswer: { choiceIds: ["A", "B", "C"] },
    explanation: {
      short: "三选——库维护的规则集是核心价值，自写补不齐。",
      detail: "性能其实自写更快（少匹配几百模式），Cloudflare 也不管你怎么写。真正代价是「漏识别 + 维护成本」。",
    },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q16 isbot + AbortSignal",
    prompt: "如果 bot 路径下 await body.allReady 因为某个 Suspense 永远 pending 卡住，会怎样？",
    options: [
      { id: "A", text: "5 秒后 AbortSignal.timeout(ABORT_DELAY) 触发，stream 被 abort，allReady 抛错→onError 触发→didError = true→最终返回 500 + 部分 body" },
      { id: "B", text: "永远卡住" },
      { id: "C", text: "Cloudflare 强制断连" },
      { id: "D", text: "ReadableStream 自动恢复" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "AbortSignal.timeout 兜底——任何 await 在 5 秒后都会失败。",
      detail: "这是为什么 entry.server 必须挂 AbortSignal——Worker 有 CPU/wall time 限制，没有 timeout 一旦 Suspense 死锁整个 isolate 都会被回收。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q17 isbot 与 noindex",
    prompt: "对于敏感页（比如 /admin），你不希望被 bot 索引。是否应该在 entry.server 给 isbot=true 的请求返 403？",
    options: [
      { id: "A", text: "不——isbot 只是 UA 检测，可以伪造；正确做法是页面加 <meta name=\"robots\" content=\"noindex\">、robots.txt 屏蔽路径、loader 校验 session" },
      { id: "B", text: "是，最简洁" },
      { id: "C", text: "返回 404 给 bot" },
      { id: "D", text: "动态生成 robots.txt" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "防爬靠 robots.txt + meta + 真实鉴权，不靠 isbot。",
      detail: "isbot 设计目的是「优化用户体验」（决定流式还是 allReady），不是「鉴权」。鉴权要走 loader/session。",
    },
    abilityTags: ["ai.review.architecture", "backend.auth.required"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q18 stream + bot 兼容性",
    prompt: "为什么不直接「全员 allReady」让代码更简单？",
    options: [
      { id: "A", text: "TTFB 是 SSR 的核心收益——allReady 把它干掉就退化成「加 SPA」，跟纯 CSR 比 SSR 没意义；isbot 双轨制保住「用户快 + bot 完整」两端" },
      { id: "B", text: "Cloudflare 限制 allReady" },
      { id: "C", text: "React 19 不支持" },
      { id: "D", text: "ReadableStream 不能 allReady" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "TTFB = SSR 的命，全员 allReady 等于阉割 SSR。",
      detail: "对长内容页（如 changelog、博客）TTFB 差异可达 1-3 秒。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "code_fix",
    title: "Q19 await 漏写",
    prompt: "代码被改成：if (isbot(...)) body.allReady; （漏写 await）。后果？",
    code: `if (isbot(request.headers.get("user-agent") || "")) {\n  body.allReady; // 漏 await\n}`,
codeFixBaseline: `if (isbot(request.headers.get("user-agent") || "")) {\n  body.allReady; // 漏 await\n}`,
correctAnswer: { patchedCode: "body.allReady 是 Promise，单独求值不会等待——bot 路径退化成跟用户路径一样的流式输出。修复：补 await——await body.allReady;。还要看 ESLint @typescript-eslint/no-floating-promises 规则有没有开，没开就不会报。" },
explanation: { short: "见下方解释。", detail: "body.allReady 是 Promise，单独求值不会等待——bot 路径退化成跟用户路径一样的流式输出。修复：补 await——await body.allReady;。还要看 ESLint @typescript-eslint/no-floating-promises 规则有没有开，没开就不会报。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q20 老版本 isbot",
    prompt: "如果 package.json 锁的 isbot 是 v3.x，代码 import { isbot } from \"isbot\" 会怎样？",
    options: [
      { id: "A", text: "TypeScript 报错（v3 是 default export）；bundle 出来 isbot 是 undefined，运行时调 isbot(...) 直接 TypeError" },
      { id: "B", text: "正常运行" },
      { id: "C", text: "降级为 false 永远走用户路径" },
      { id: "D", text: "Cloudflare 帮你兜底" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "v3 → v5 是 breaking change（default → named）；锁旧版用新写法会爆。",
      detail: "升级路径：把 v3 的 `import isbot from 'isbot'` 改成 v5 的 `import { isbot } from 'isbot'`，反向也一样。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "remix/package.json"],
  }),
  q({
    type: "review_comment",
    title: "Q21 Review：缓存 isbot 结果",
    prompt: "Reviewer 留言：「每个请求都调 isbot 太浪费，建议在 module 层用 Map 缓存 UA → bool。」请评价。",
    correctAnswer: { comment: "评审错——isbot 内部已经是 O(N) 字符串匹配且 N 小（< 1ms），无需缓存。Map 缓存反而引入新问题：UA 长尾极多（百万种），Map 无界增长会让 isolate 内存泄漏；且 isolate 重启会清，命中率有限。结论：保持原样，不要 over-engineer。" },
explanation: { short: "见 review comment。", detail: "评审错——isbot 内部已经是 O(N) 字符串匹配且 N 小（< 1ms），无需缓存。Map 缓存反而引入新问题：UA 长尾极多（百万种），Map 无界增长会让 isolate 内存泄漏；且 isolate 重启会清，命中率有限。结论：保持原样，不要 over-engineer。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "free_explain",
    title: "Q22 自由说明：bot vs 用户的两套策略",
    prompt: "用一段话说明：handleRequest 里为什么对 bot 和用户走两条路径？两条路径分别承担什么 trade-off？",
    correctAnswer: { text: "(1) 用户路径：流式 SSR——shell 一就绪就开始往浏览器吐字节，TTFB 优先 (2) bot 路径：等 allReady——爬虫读完一次 Response 不会回来等 Suspense，必须给完整 HTML (3) trade-off：用户牺牲 SEO（Suspense 的内容初次没有），bot 牺牲 TTFB（多等百毫秒） (4) isbot 是「策略选择器」——根据 UA 决定走哪条 (5) 本质：单 entry.server 同时优化两类 client，避免维护两套部署" },
explanation: { short: "见详细要点。", detail: "(1) 用户路径：流式 SSR——shell 一就绪就开始往浏览器吐字节，TTFB 优先 (2) bot 路径：等 allReady——爬虫读完一次 Response 不会回来等 Suspense，必须给完整 HTML (3) trade-off：用户牺牲 SEO（Suspense 的内容初次没有），bot 牺牲 TTFB（多等百毫秒） (4) isbot 是「策略选择器」——根据 UA 决定走哪条 (5) 本质：单 entry.server 同时优化两类 client，避免维护两套部署" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "free-response",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
];
