/**
 * Real questions for site-03-entry-server / entry-env.
 * Anchor: remix/app/entry.server.tsx + remix/app/utils/cloudflare-env.server.ts
 *   - import { setRuntimeEnv, type RuntimeEnv } from "./utils/cloudflare-env.server";
 *   - CloudflareLoadContext = AppLoadContext & { cloudflare?: { env?: RuntimeEnv } }
 *   - if (cloudflareEnv) setRuntimeEnv(cloudflareEnv)
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/entry.server.tsx";
const ENV = "app/utils/cloudflare-env.server.ts";

export const entryEnvQuestions: RealQ[] = [
  q({
    type: "single_choice",
    title: "Q1 setRuntimeEnv 来源",
    prompt: "setRuntimeEnv 函数是从哪里 import 的？",
    options: [
      { id: "A", text: "./utils/cloudflare-env.server——同 remix 项目的工具模块" },
      { id: "B", text: "@remix-run/cloudflare" },
      { id: "C", text: "wrangler" },
      { id: "D", text: "@cloudflare/workers-types" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "项目自己写的工具，文件路径 app/utils/cloudflare-env.server.ts。",
      detail: "导出还包括 RuntimeEnv 类型、getEnvVar、getRequiredEnv 等。entry.server 这里只用 setRuntimeEnv + RuntimeEnv 类型。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, ENV],
  }),
  q({
    type: "single_choice",
    title: "Q2 RuntimeEnv 类型",
    prompt: "type RuntimeEnv 描述了什么？",
    options: [
      { id: "A", text: "Cloudflare Worker 的 env 对象——含所有 binding（DB、AUTH_KEY_SECRET、APP_URL 等）的 TypeScript 类型" },
      { id: "B", text: "Node.js process.env 类型" },
      { id: "C", text: "import.meta.env 类型" },
      { id: "D", text: "运行时 globalThis 类型" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "Worker env 的强类型版——getEnvVar 返回值靠它收窄。",
      detail: "wrangler.toml 里写的每个 binding 都应在 RuntimeEnv 里有对应字段。新增 binding 不更新类型 = TypeScript 看不到。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: ENV,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, ENV],
  }),
  q({
    type: "fill_blank",
    title: "Q3 CloudflareLoadContext 类型",
    prompt: "type CloudflareLoadContext = AppLoadContext & { cloudflare?: { env?: ____ } };",
    options: [],
    blanks: [{ id: "t", placeholder: "类型名", acceptedAnswers: ["RuntimeEnv"] }],
    correctAnswer: { type: "fill_blank", values: { t: "RuntimeEnv" } },
    explanation: {
      short: "type 名字是 RuntimeEnv——和 setRuntimeEnv 接受的参数类型一致。",
      detail: "整个 cloudflare 字段是可选的（?）——dev 不跑 worker 模式时不存在。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, ENV],
  }),
  q({
    type: "single_choice",
    title: "Q4 cloudflareEnv 取值",
    prompt: "const cloudflareEnv = (loadContext as CloudflareLoadContext).cloudflare?.env;——cloudflareEnv 的可能取值？",
    options: [
      { id: "A", text: "RuntimeEnv 实例 或 undefined（如果没有 cloudflare 字段或 env 字段）" },
      { id: "B", text: "永远 RuntimeEnv 实例" },
      { id: "C", text: "永远 undefined" },
      { id: "D", text: "Promise<RuntimeEnv>" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "可选链让两端都可能 undefined——TypeScript 收窄为 RuntimeEnv | undefined。",
      detail: "下面的 if (cloudflareEnv) 守门正是消费这个收窄。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q5 setRuntimeEnv 的内部",
    prompt: "setRuntimeEnv(cloudflareEnv) 在 cloudflare-env.server.ts 内部做了什么（参考之前的 site-01 课）？",
    options: [
      { id: "A", text: "把 env 同时写进 module 局部变量 runtimeEnv 和 globalThis.__REMIX_RUNTIME_ENV__——双写是为应对 Worker module 缓存与 isolate 重建之间的边界场景" },
      { id: "B", text: "把 env 写进 D1" },
      { id: "C", text: "把 env 写进 KV" },
      { id: "D", text: "把 env 写进 cookie" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "双写 module + globalThis——后续 getEnvVar 三层 fallback 之一。",
      detail: "三层 fallback：globalThis.__REMIX_RUNTIME_ENV__ → runtimeEnv → process.env。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: ENV,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, ENV],
  }),
  q({
    type: "true_false",
    title: "Q6 多请求共享 module",
    prompt: "判断：Cloudflare Worker 的同一个 isolate 内，多次 SSR 请求共享同一个 module（runtimeEnv 变量）。",
    correctAnswer: { value: true },
    explanation: {
      short: "对——同 isolate 内 module 状态共享。所以一次 setRuntimeEnv 后，后续请求都能读到。",
      detail: "isolate 重建后 module 重置——这就是为什么每次 handleRequest 都重新 setRuntimeEnv，防止丢失。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, ENV],
  }),
  q({
    type: "single_choice",
    title: "Q7 if 守门的必要性",
    prompt: "去掉 if (cloudflareEnv)，直接 setRuntimeEnv(cloudflareEnv) 会怎样？",
    options: [
      { id: "A", text: "TypeScript 报错（cloudflareEnv 类型是 RuntimeEnv | undefined，setRuntimeEnv 期望 RuntimeEnv）；运行时如果 undefined 进去，setRuntimeEnv 实现里大概率覆写为 undefined，后续 getEnvVar 全部走 fallback——除非 process.env 也有值，否则全部失败" },
      { id: "B", text: "正常工作" },
      { id: "C", text: "Worker 立即崩溃" },
      { id: "D", text: "Cloudflare 自动注入兜底" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "类型层会拦；但实际危害是「写入 undefined 把可能存在的旧值清掉」。",
      detail: "守门的另一价值：保留上次 setRuntimeEnv 写入的值（万一新 isolate 第一次请求恰好没带 cloudflare 字段，旧 module 状态尚存可用）。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, ENV],
  }),
  q({
    type: "branch_trace",
    title: "Q8 dev 模式下 cloudflareEnv 路径",
    prompt: "本地 npm run dev（vite + 不模拟 worker）时，请求进 handleRequest 的 cloudflareEnv 是什么？",
    options: [
      { id: "s1", text: "1. loadContext 不含 cloudflare 字段（vite dev 不注入）" },
      { id: "s2", text: "2. const cloudflareEnv = (loadContext as ...).cloudflare?.env;" },
      { id: "s3", text: "3. cloudflareEnv === undefined" },
      { id: "s4", text: "4. if (cloudflareEnv) 守门——跳过 setRuntimeEnv" },
      { id: "s5", text: "5. 后续 getEnvVar 走 process.env fallback——读 .env 配置" },
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5"] },
    explanation: {
      short: "dev 模式 → undefined → 跳 setRuntimeEnv → process.env fallback。",
      detail: "这是为什么 .env / .dev.vars 在本地有效——getEnvVar 实际读了 process.env。",
    },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, ENV],
  }),
  q({
    type: "single_choice",
    title: "Q9 worker.ts 怎么塞 env",
    prompt: "remix/worker.ts 里怎么把 env 塞进 loadContext？",
    options: [
      { id: "A", text: "调 createRequestHandler(handler) 时第二个参数（getLoadContext 函数）返回 { cloudflare: { env, ctx } }" },
      { id: "B", text: "塞进 request.cf 字段" },
      { id: "C", text: "通过 globalThis 全局变量" },
      { id: "D", text: "通过 wrangler.toml 自动注入" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "createRequestHandler 第二个参数是 getLoadContext，签名 (request, env, ctx) => loadContext。",
      detail: "Cloudflare 适配器的约定：你在 worker.ts 决定 loadContext 形状，handleRequest 在 entry.server 里读出来。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "remix/worker.ts"],
  }),
  q({
    type: "single_choice",
    title: "Q10 ctx.waitUntil 在哪",
    prompt: "你想在 handleRequest 里用 ctx.waitUntil 做异步埋点（比如 Logpush）。能拿到 ctx 吗？",
    options: [
      { id: "A", text: "代码里没读 ctx——但 worker.ts 把 ctx 塞进 loadContext 了，你需要把类型扩展为 { cloudflare?: { env?, ctx? } }，然后在 handleRequest 里 (loadContext as CloudflareLoadContext).cloudflare?.ctx 读出来" },
      { id: "B", text: "ctx 不能在 handleRequest 拿到" },
      { id: "C", text: "需要 import 全局 ctx" },
      { id: "D", text: "Cloudflare 不支持 waitUntil" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "loadContext 里有 ctx，只是当前类型没暴露，要扩展。",
      detail: "实际现状：项目主要在 loader/action 里通过 context.cloudflare.ctx.waitUntil 调用，不在 entry.server 调。",
    },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "remix/worker.ts"],
  }),
  q({
    type: "code_fix",
    title: "Q11 把 setRuntimeEnv 漏掉",
    prompt: "把 if (cloudflareEnv) setRuntimeEnv(cloudflareEnv) 整段删了。生产症状？",
    code: `// ❌ 删了 setRuntimeEnv 调用\nconst url = new URL(request.url);\nif (url.pathname.startsWith("/.well-known/")) { ... }`,
codeFixBaseline: `// ❌ 删了 setRuntimeEnv 调用\nconst url = new URL(request.url);\nif (url.pathname.startsWith("/.well-known/")) { ... }`,
correctAnswer: { patchedCode: "症状：getRequiredEnv 在 isolate 第一次请求时拿不到 env，抛 'Missing env: ...'；后续请求如果碰巧 globalThis.__REMIX_RUNTIME_ENV__ 还在能用，否则继续抛。dev 模式不受影响（process.env fallback）。修复：恢复那一行。" },
explanation: { short: "见下方解释。", detail: "症状：getRequiredEnv 在 isolate 第一次请求时拿不到 env，抛 'Missing env: ...'；后续请求如果碰巧 globalThis.__REMIX_RUNTIME_ENV__ 还在能用，否则继续抛。dev 模式不受影响（process.env fallback）。修复：恢复那一行。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, ENV],
  }),
  q({
    type: "single_choice",
    title: "Q12 setRuntimeEnv 在 worker.ts 调",
    prompt: "提案：把 setRuntimeEnv 移到 worker.ts 的 fetch handler 里调，handleRequest 里就不用调了。是否合理？",
    options: [
      { id: "A", text: "合理且更早期——fetch handler 是请求最先经过的位置，越早 setRuntimeEnv 越保险；不过 entry.server 里也调一次也行（双保险），不冲突" },
      { id: "B", text: "不合理，必须在 handleRequest" },
      { id: "C", text: "TypeScript 不允许" },
      { id: "D", text: "Cloudflare 拒绝" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "更早调更安全——worker.ts 是 SSR 链路最早的钩子。",
      detail: "实践上很多团队就在 worker.ts 调，entry.server 不重复。当前项目两处都没用，只在 entry.server 调一次也够了。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "remix/worker.ts", ENV],
  }),
  q({
    type: "true_false",
    title: "Q13 import type",
    prompt: "判断：`import { setRuntimeEnv, type RuntimeEnv } from \"./utils/cloudflare-env.server\";`——type 关键字写在花括号内是合法语法。",
    correctAnswer: { value: true },
    explanation: {
      short: "对——TypeScript 4.5+ 的 type modifier on import names 语法。",
      detail: "好处：编译时把 RuntimeEnv 完全擦掉（不进 bundle），同时还能从同一句 import 拿运行时值 setRuntimeEnv。比写两条 import 简洁。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q14 RuntimeEnv 升级",
    prompt: "你给 wrangler.toml 加了一个新 KV binding LEARN_CACHE。要让 entry.server 也能间接拿到，最少改哪里？",
    options: [
      { id: "A", text: "只需在 RuntimeEnv 类型里加 LEARN_CACHE: KVNamespace 字段——entry.server 不需要改（它只调 setRuntimeEnv 写整体 env，后续 loader 用 getEnvVar('LEARN_CACHE') 取）" },
      { id: "B", text: "改 entry.server 加 import" },
      { id: "C", text: "改 worker.ts" },
      { id: "D", text: "重写 setRuntimeEnv" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "RuntimeEnv 是单点契约，加字段就生效。",
      detail: "entry.server 写法很通用——它把整个 env 都塞进 module，具体读哪个字段是 loader 决定。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: ENV,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, ENV, "remix/wrangler.toml"],
  }),
  q({
    type: "position_judgement",
    title: "Q15 决策：直接 import env",
    prompt: "你想在某个 server util 里直接读 env，能不能在文件顶部 import { env } from \"./entry.server\";？",
    options: [
      { id: "A", text: "不能——entry.server 不导出 env；正确做法是 import { getEnvVar } from \"~/utils/cloudflare-env.server\"，让 module 缓存帮你拿到 setRuntimeEnv 写入的值" },
      { id: "B", text: "可以直接 import" },
      { id: "C", text: "用 globalThis.env" },
      { id: "D", text: "用 process.env" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "环境变量统一走 getEnvVar 助手——三层 fallback + 命名约束。",
      detail: "直 import entry.server 的本地变量在 ESM 里不可行（且 entry.server 不导出）；project 风格是中央化的 getEnvVar/getRequiredEnv。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: ENV,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, ENV],
  }),
  q({
    type: "single_choice",
    title: "Q16 entry.client 与 env",
    prompt: "为什么 entry.client.tsx 不调 setRuntimeEnv？",
    options: [
      { id: "A", text: "client 端没有 worker env——浏览器 globalThis 不存在 binding；client 要的「环境变量」走 root loader 注入到 useLoaderData，或者打包时通过 import.meta.env 注入（不带敏感值）" },
      { id: "B", text: "client 也调，只是 vite 自动隐藏了" },
      { id: "C", text: "Cloudflare 自动同步" },
      { id: "D", text: "client 不需要 env" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "env 是 server 概念；client 要值要靠 loader 注入。",
      detail: "比如 GOOGLE_CLIENT_ID（公开值）通过 root loader 暴露给 client；AUTH_KEY_SECRET（敏感值）只在 server 使用，绝不进 bundle。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/entry.client.tsx", "app/root.tsx"],
  }),
  q({
    type: "single_choice",
    title: "Q17 RuntimeEnv 与 secret",
    prompt: "AUTH_KEY_SECRET 在 wrangler 里被声明为 secret（不是 var）。RuntimeEnv 类型里它的字段类型是？",
    options: [
      { id: "A", text: "string——wrangler secret 在 Worker 运行时和 var 一样表现为 env.AUTH_KEY_SECRET 字符串；区别只是部署时怎么注入（secret 加密、var 明文）" },
      { id: "B", text: "Promise<string>" },
      { id: "C", text: "{ value: string }" },
      { id: "D", text: "不能在 TypeScript 里声明" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "运行时无差，类型层面就是 string。",
      detail: "secret 与 var 的差只在「部署阶段如何注入」——secret 用 wrangler secret put 加密存，var 直接写 wrangler.toml 明文。代码里读法完全一样。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: ENV,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, ENV, "remix/wrangler.toml"],
  }),
  q({
    type: "code_fix",
    title: "Q18 在 entry.server 直接读 env",
    prompt: "新代码：import { getEnvVar } from \"~/utils/cloudflare-env.server\"; const SECRET = getEnvVar('AUTH_KEY_SECRET'); 在文件顶部（module 顶层）。会出什么问题？",
    code: `// 文件顶层\nimport { getEnvVar } from "~/utils/cloudflare-env.server";\nconst SECRET = getEnvVar("AUTH_KEY_SECRET");`,
codeFixBaseline: `// 文件顶层\nimport { getEnvVar } from "~/utils/cloudflare-env.server";\nconst SECRET = getEnvVar("AUTH_KEY_SECRET");`,
correctAnswer: { patchedCode: "module 顶层执行时间是「first import 时」——比 setRuntimeEnv 还早，runtimeEnv 还是 undefined，getEnvVar 拿到 undefined（或抛）。修复：把 getEnvVar 调用放到 handleRequest 函数体内，那时 setRuntimeEnv 已经跑过；或者把 SECRET 改成 lazy: const getSecret = () => getEnvVar('AUTH_KEY_SECRET')。" },
explanation: { short: "见下方解释。", detail: "module 顶层执行时间是「first import 时」——比 setRuntimeEnv 还早，runtimeEnv 还是 undefined，getEnvVar 拿到 undefined（或抛）。修复：把 getEnvVar 调用放到 handleRequest 函数体内，那时 setRuntimeEnv 已经跑过；或者把 SECRET 改成 lazy: const getSecret = () => getEnvVar('AUTH_KEY_SECRET')。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, ENV],
  }),
  q({
    type: "single_choice",
    title: "Q19 entry.server 与 worker.ts 的分工",
    prompt: "worker.ts 和 entry.server.tsx 的分工是？",
    options: [
      { id: "A", text: "worker.ts: Cloudflare 平台入口，定义 fetch handler、组装 loadContext、调 createRequestHandler。entry.server.tsx: React Router 给的 SSR hook，决定怎么把树渲染成 Response" },
      { id: "B", text: "完全等价，可以合并" },
      { id: "C", text: "worker.ts 跑 client，entry.server 跑 server" },
      { id: "D", text: "worker.ts 是 dev only" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "worker.ts = 平台层，entry.server = 框架层。",
      detail: "worker.ts 改 binding 注入方式；entry.server 改 SSR 渲染策略。两个都改风险叠加。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "remix/worker.ts"],
  }),
  q({
    type: "true_false",
    title: "Q20 setRuntimeEnv 是否必须在 await render 之前",
    prompt: "判断：setRuntimeEnv(cloudflareEnv) 必须在 const body = await renderToReadableStream(...) 之前调用，否则 loader 拿不到 env。",
    correctAnswer: { value: true },
    explanation: {
      short: "对——loader 在 renderToReadableStream 内部跑，跑前必须 setRuntimeEnv。",
      detail: "如果晚调，loader 通过 getEnvVar 取值会读到 undefined（除非 globalThis 还残留旧值）。",
    },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, ENV],
  }),
  q({
    type: "review_comment",
    title: "Q21 Review：env 写 globalThis",
    prompt: "Reviewer 留言：「setRuntimeEnv 把 env 双写 module + globalThis 太重，单写 module 就够了。」请评价。",
    correctAnswer: { comment: "评审错。双写不是冗余而是兼容多种 Worker 加载策略：1) 同 isolate 多次请求 → module 缓存命中即可；2) Worker 依赖 esbuild 重打包后 module 实例可能跨边界出现新副本——globalThis 是真单例；3) 个别 lib（数据库 client）会缓存到 globalThis，没有这一层就拿不到。代价：写 globalThis 是 O(1)，可以忽略。建议保持双写。" },
explanation: { short: "见 review comment。", detail: "评审错。双写不是冗余而是兼容多种 Worker 加载策略：1) 同 isolate 多次请求 → module 缓存命中即可；2) Worker 依赖 esbuild 重打包后 module 实例可能跨边界出现新副本——globalThis 是真单例；3) 个别 lib（数据库 client）会缓存到 globalThis，没有这一层就拿不到。代价：写 globalThis 是 O(1)，可以忽略。建议保持双写。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: ENV,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, ENV],
  }),
  q({
    type: "free_explain",
    title: "Q22 自由说明：env 在 Worker 上的传递链",
    prompt: "用一段话说明：环境变量从 wrangler.toml 一路到 loader 内 getEnvVar 调用，经过哪些「站点」？",
    correctAnswer: { text: "(1) 起点：wrangler.toml 声明 binding（D1, KV, secret, var） (2) 部署时：wrangler 把 binding 注入 Cloudflare，运行时通过 fetch(req, env, ctx) 第二个参数传给 Worker (3) worker.ts: 接住 env 并通过 createRequestHandler 第二个参数 getLoadContext 塞进 loadContext.cloudflare.env (4) entry.server: handleRequest 收到 loadContext，提取 cloudflareEnv，调 setRuntimeEnv 写入 module/globalThis 缓存 (5) loader/util: getEnvVar('XXX') 从 globalThis → runtimeEnv → process.env 三层 fallback 取值 (6) 整条链上 entry.server 是「平台 → 框架」的桥" },
explanation: { short: "见详细要点。", detail: "(1) 起点：wrangler.toml 声明 binding（D1, KV, secret, var） (2) 部署时：wrangler 把 binding 注入 Cloudflare，运行时通过 fetch(req, env, ctx) 第二个参数传给 Worker (3) worker.ts: 接住 env 并通过 createRequestHandler 第二个参数 getLoadContext 塞进 loadContext.cloudflare.env (4) entry.server: handleRequest 收到 loadContext，提取 cloudflareEnv，调 setRuntimeEnv 写入 module/globalThis 缓存 (5) loader/util: getEnvVar('XXX') 从 globalThis → runtimeEnv → process.env 三层 fallback 取值 (6) 整条链上 entry.server 是「平台 → 框架」的桥" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "free-response",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, ENV, "remix/worker.ts", "remix/wrangler.toml"],
  }),
];
