/**
 * Real questions for site-03-entry-server / entry-capstone.
 * Anchor: 整合 entry.server.tsx 全文件的修改决策——什么时候改 entry.server，什么时候改 root，什么时候改 worker.ts。
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/entry.server.tsx";

export const entryCapstoneQuestions: RealQ[] = [
  q({
    type: "position_judgement",
    title: "Q1 加全站 CSP 头",
    prompt: "全站 SSR HTML 都要加 Content-Security-Policy 头。落点？",
    options: [
      { id: "A", text: "entry.server 的 responseHeaders.set——平台级安全头，单点写所有 SSR 都生效" },
      { id: "B", text: "root.tsx 的 loader headers" },
      { id: "C", text: "每个路由 headers()" },
      { id: "D", text: "wrangler.toml routes" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "CSP 是平台层，entry.server 是单点。",
      detail: "如果还要 nonce 每请求随机，更必须 entry.server——只有这里能同时写 CSP 头和把 nonce 注入 loadContext 给 root 用。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "position_judgement",
    title: "Q2 给登录用户首页缓存设私",
    prompt: "首页对登录用户返回个性化内容，要 Cache-Control: private, no-store。落点？",
    options: [
      { id: "A", text: "_index.tsx 的 loader 里根据 session 设 headers——业务策略，按是否登录走不同 Cache-Control" },
      { id: "B", text: "entry.server 全局 set" },
      { id: "C", text: "wrangler.toml routes" },
      { id: "D", text: "Cloudflare Cache Rule UI" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "「登录与否」是业务变量，应在 loader 里决定。",
      detail: "entry.server 全局 set 会把所有页面都搞成 private，CDN 命中率掉到 0。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture", "backend.session.cookie"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/routes/_index.tsx"],
  }),
  q({
    type: "position_judgement",
    title: "Q3 加 GeoIP 路由分流",
    prompt: "需求：根据 request.cf.country 把中国用户路由到 /cn 子站。落点？",
    options: [
      { id: "A", text: "worker.ts 的 fetch handler——最早期、最容易做 redirect 而不进 React Router" },
      { id: "B", text: "entry.server" },
      { id: "C", text: "root loader" },
      { id: "D", text: "客户端 useEffect" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "redirect 在 fetch handler 最早期，省掉 SSR 整轮成本。",
      detail: "entry.server 也行（早期做 return new Response(null, {status: 302, headers: {Location: '/cn'}})），但比 worker.ts 晚一站。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "remix/worker.ts"],
  }),
  q({
    type: "position_judgement",
    title: "Q4 加全局错误埋点",
    prompt: "想给所有 SSR 错误自动上报到 Sentry。落点？",
    options: [
      { id: "A", text: "entry.server 的 onError 回调里 ctx.waitUntil(reportError(error))——这里能拿到原始 error 对象，且 ctx 通过 loadContext 取出" },
      { id: "B", text: "root.tsx ErrorBoundary" },
      { id: "C", text: "worker.ts 的 fetch handler 外层 try/catch" },
      { id: "D", text: "每个 loader try/catch" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "onError 是 React 渲染错误的唯一通知点——唯一一个 SSR 渲染失败的「全捕」位置。",
      detail: "B 只能拿到 RouteErrorBoundary 已经处理过的；C 拿到 throw 出 entry.server 的错（很少）；D 漏 RemixServer 自身错误。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "position_judgement",
    title: "Q5 改 ABORT_DELAY",
    prompt: "团队反馈个别 loader 慢到 6 秒经常超时，决定调到 8 秒。改哪？",
    options: [
      { id: "A", text: "entry.server.tsx 文件顶部的 const ABORT_DELAY = 5_000——单点，一个值同时给 RemixServer 和 AbortSignal" },
      { id: "B", text: "wrangler.toml" },
      { id: "C", text: "package.json" },
      { id: "D", text: "每个慢 loader 自己加 timeout" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "ABORT_DELAY 是命名常量，单点修改。",
      detail: "建议同时优化慢 loader 而不是只调常量——8 秒只是延后炸点，loader 慢的根因要在 D1 查询/外部 API 那解决。",
    },
    abilityTags: ["code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q6 entry.server 改动风险评估",
    prompt: "改 entry.server.tsx 一行代码，最坏可能影响范围？",
    options: [
      { id: "A", text: "全站所有 SSR 路径——任何 user/bot 请求都经过它，bug 立即影响 100% 流量" },
      { id: "B", text: "只影响首页" },
      { id: "C", text: "只影响 dev 模式" },
      { id: "D", text: "只影响管理员" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "entry.server 是单点 + 全站必经，错一行整站挂。",
      detail: "改 entry.server 之前的「最低成本」自查：1) typecheck 2) 本地 vite dev 测一遍 3) wrangler dev 测一遍 4) 灰度部署。",
    },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace",
    title: "Q7 一个完整请求生命周期",
    prompt: "用户访问 /messages（已登录），handleRequest 内步骤？",
    options: [
      { id: "s1", text: "1. setRuntimeEnv 把 env 写 module/globalThis" },
      { id: "s2", text: "2. /.well-known 检查 false" },
      { id: "s3", text: "3. didError = false" },
      { id: "s4", text: "4. await renderToReadableStream（内部跑 root loader + messages loader）" },
      { id: "s5", text: "5. isbot 普通用户 false → 跳过 allReady" },
      { id: "s6", text: "6. responseHeaders.set Content-Type: text/html" },
      { id: "s7", text: "7. return new Response(body, status: 200)" },
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7"] },
    explanation: {
      short: "标准用户路径——7 步走完。",
      detail: "loader 在 step 4 内执行：root loader 读 session，messages loader 读 D1 拿消息列表。",
    },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/root.tsx", "app/routes/messages.tsx"],
  }),
  q({
    type: "code_fix",
    title: "Q8 全员阻塞的 bug",
    prompt: "新代码删了 isbot 守门，所有请求都 await body.allReady：",
    code: `// ❌ 移除了 isbot 检查\nawait body.allReady;\nresponseHeaders.set("Content-Type", "text/html");\nreturn new Response(body, ...);`,
codeFixBaseline: `// ❌ 移除了 isbot 检查\nawait body.allReady;\nresponseHeaders.set("Content-Type", "text/html");\nreturn new Response(body, ...);`,
correctAnswer: { patchedCode: "症状：所有用户 TTFB 退化为「等整个 SSR 完成」，慢页面（含 Suspense lazy）首屏白屏 5 秒；监控指标 P50 / P95 都飙升。修复：恢复 if (isbot(request.headers.get('user-agent') || '')) { await body.allReady; } 守门，只让 bot 走 allReady。" },
explanation: { short: "见下方解释。", detail: "症状：所有用户 TTFB 退化为「等整个 SSR 完成」，慢页面（含 Suspense lazy）首屏白屏 5 秒；监控指标 P50 / P95 都飙升。修复：恢复 if (isbot(request.headers.get('user-agent') || '')) { await body.allReady; } 守门，只让 bot 走 allReady。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q9 多 isolate 多 request 并发",
    prompt: "高峰期 Cloudflare 创建多个 isolate 同时跑同一份 Worker。每个 isolate 都会调 setRuntimeEnv 吗？",
    options: [
      { id: "A", text: "对——每个 isolate 进的第一个请求都会 setRuntimeEnv 一次（写自己 isolate 的 module 缓存）；后续请求复用同 isolate 的 module" },
      { id: "B", text: "全局共享，只调一次" },
      { id: "C", text: "isolate 间 share globalThis" },
      { id: "D", text: "Cloudflare 自动同步" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "isolate 间不共享 module/globalThis；每个 isolate 独立调一次。",
      detail: "代码每请求都调 setRuntimeEnv 是对这种「每 isolate 第一次」的保险。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q10 entry.server 与 entry.client 关系",
    prompt: "entry.server.tsx 与 entry.client.tsx 是什么关系？",
    options: [
      { id: "A", text: "前者 SSR 时跑（Worker 上），后者 hydration 时跑（浏览器）；两边的 default export 函数名分别是 handleRequest 和 hydrate（实际是 hydrateRoot 调用包装）；它们组成「同构 SSR」的两端" },
      { id: "B", text: "完全等价，可以二合一" },
      { id: "C", text: "entry.server 包含 entry.client" },
      { id: "D", text: "entry.client 是 fallback" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "server / client 两端 entry，两个文件分担 SSR 与 hydration。",
      detail: "改 SSR 行为找 server，改 hydration 行为（startTransition、ErrorRecovery 等）找 client。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/entry.client.tsx"],
  }),
  q({
    type: "true_false",
    title: "Q11 删 entry.server 的后果",
    prompt: "判断：删除 entry.server.tsx 文件，React Router 会用框架默认 SSR 实现，项目仍能跑。",
    correctAnswer: { value: true },
    explanation: {
      short: "对——React Router 在没有 entry.server 时用框架内置默认实现。",
      detail: "代价：失去 .well-known 短路、setRuntimeEnv 调用、自定义 isbot 路径、ABORT_DELAY 设置。生产上别这么干。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q12 entry.server vs root.tsx",
    prompt: "「设全局 favicon link」最佳落点？",
    options: [
      { id: "A", text: "root.tsx 的 Layout 组件 <Links />（或 export const links）——它是 React 树的一部分，热刷新友好；entry.server 是平台层不该管 link" },
      { id: "B", text: "entry.server" },
      { id: "C", text: "wrangler.toml" },
      { id: "D", text: "client.entry" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "<link> 标签属于 HTML 树，归 root.tsx。",
      detail: "entry.server 是字节流处理，不该写「内容」。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "multi_choice",
    title: "Q13 哪些一定不该放 entry.server",
    prompt: "下列哪些放进 entry.server 是反模式？(多选)",
    options: [
      { id: "A", text: "业务鉴权（每请求 await session check）" },
      { id: "B", text: "数据库查询（DB.prepare(...).first()）" },
      { id: "C", text: "调外部 API（fetch openai.com）" },
      { id: "D", text: "字符串操作（设置 Content-Type）" },
      { id: "E", text: "数组求和、JSON.stringify 等纯函数" },
    ],
    correctAnswer: { choiceIds: ["A", "B", "C"] },
    explanation: {
      short: "鉴权/DB/外部 API 都属业务应在 loader；entry.server 只做平台层。",
      detail: "D/E 是纯计算/平台契约，可以放——它们的成本可控、影响域明确。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q14 整合后的清单",
    prompt: "回顾整个 entry.server.tsx 65 行代码做的「五件大事」是？",
    options: [
      { id: "A", text: "1) setRuntimeEnv 注入 env 2) /.well-known 短路 3) renderToReadableStream + AbortSignal 4) isbot 双轨 5) responseHeaders.set + 三元 status" },
      { id: "B", text: "登录/鉴权/限流/日志/缓存" },
      { id: "C", text: "数据库连接管理" },
      { id: "D", text: "URL 路由匹配" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "五件事都是「平台契约级」决定，不涉业务。",
      detail: "想加新事项前先问「这是平台契约还是业务策略」——业务的去 loader/action。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "code_fix",
    title: "Q15 直接在 entry.server 加业务",
    prompt: "新代码：在 setRuntimeEnv 后加了 const session = await getSessionCached(request); 想统一鉴权。",
    code: `if (cloudflareEnv) setRuntimeEnv(cloudflareEnv);\n\nconst session = await getSessionCached(request); // ❌ 业务\nif (!session && url.pathname.startsWith("/admin")) {\n  return new Response(null, { status: 302, headers: { Location: "/auth" } });\n}`,
codeFixBaseline: `if (cloudflareEnv) setRuntimeEnv(cloudflareEnv);\n\nconst session = await getSessionCached(request); // ❌ 业务\nif (!session && url.pathname.startsWith("/admin")) {\n  return new Response(null, { status: 302, headers: { Location: "/auth" } });\n}`,
correctAnswer: { patchedCode: "把鉴权抽到 loader——/admin/* 路由（或父 layout）的 loader 里 await requireAdmin(request)，未登录抛 redirect。entry.server 加鉴权：1) 每请求都跑（含 _index 等公开页），浪费；2) entry.server 改一行影响 100% 流量风险大；3) 鉴权策略变化（白名单调整、登录方式增加）需要改 entry.server，违反「平台 vs 业务」分层。修复：删掉这段，移到具体路由 loader。" },
explanation: { short: "见下方解释。", detail: "把鉴权抽到 loader——/admin/* 路由（或父 layout）的 loader 里 await requireAdmin(request)，未登录抛 redirect。entry.server 加鉴权：1) 每请求都跑（含 _index 等公开页），浪费；2) entry.server 改一行影响 100% 流量风险大；3) 鉴权策略变化（白名单调整、登录方式增加）需要改 entry.server，违反「平台 vs 业务」分层。修复：删掉这段，移到具体路由 loader。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "backend.auth.required"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/lib/auth.server.ts"],
  }),
  q({
    type: "single_choice",
    title: "Q16 entry.server 与 worker.ts 同时改",
    prompt: "重构：把 setRuntimeEnv 调用移到 worker.ts，并删除 entry.server 里的相应代码。验证步骤？",
    options: [
      { id: "A", text: "1) typecheck 2) npm run dev 测 vite dev 路径（不进 worker.ts），确认 process.env fallback 还能用 3) npm start 测 wrangler dev 路径，确认新 setRuntimeEnv 位置生效 4) deploy 后用真实流量小规模灰度" },
      { id: "B", text: "改完直接部署" },
      { id: "C", text: "Cloudflare 自动验证" },
      { id: "D", text: "TypeScript 通过就行" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "两路径要分别测——vite dev 和 wrangler dev 走不同入口。",
      detail: "vite dev 不调 worker.ts，靠 process.env fallback；wrangler dev 走完整 Worker 链路。两路径都通才稳。",
    },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "remix/worker.ts"],
  }),
  q({
    type: "single_choice",
    title: "Q17 monkey patch global fetch",
    prompt: "提案：在 entry.server 顶部 monkey patch globalThis.fetch 加上自动重试和上报。是否合理？",
    options: [
      { id: "A", text: "不合理——entry.server 顶部代码在 module load 时执行（不是每请求），patch 一次后所有 isolate 全局生效；fetch 是 Worker 整个生态的根基（包括框架内部调用），随便 patch 会牵动你不知道的链路" },
      { id: "B", text: "合理且简洁" },
      { id: "C", text: "Cloudflare 鼓励这么做" },
      { id: "D", text: "TypeScript 会自动恢复" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "全局 patch 影响面失控；要重试/上报，做 wrapper 函数，业务方按需调用。",
      detail: "原则：「不要在 entry.server 影响别人」——它的爆炸半径是全站。",
    },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false",
    title: "Q18 entry.server 与 hydration mismatch",
    prompt: "判断：如果 entry.server 输出的 HTML 和 entry.client hydration 期望的不一致，浏览器会报 hydration mismatch 警告。",
    correctAnswer: { value: true },
    explanation: {
      short: "对——SSR HTML 与 client React 树差异是 hydration mismatch 经典原因。",
      detail: "常见触发：在组件里直接读 window/document、用 Date.now()/Math.random() 之类非确定值。entry.server 自己一般不引入 mismatch，但它包的 RemixServer 渲染出的内容如果有问题，会经它输出。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/entry.client.tsx"],
  }),
  q({
    type: "review_comment",
    title: "Q19 Review：合并三 timeout",
    prompt: "Reviewer 留言：「ABORT_DELAY 用了两次（abortDelay + signal），还有 console.error，能不能合并成一个 timeout 处理？」请评价。",
    correctAnswer: { comment: "评审混淆了概念。abortDelay 是 React 控制 Suspense fallback 时机的参数，AbortSignal.timeout 是网络层中断 stream 的方法——两者位于不同层（React 渲染 vs Web Stream），不能合并。同值 5_000 是「契约」而非冗余。console.error 是日志工具，跟 timeout 无关。建议保持现状。" },
explanation: { short: "见 review comment。", detail: "评审混淆了概念。abortDelay 是 React 控制 Suspense fallback 时机的参数，AbortSignal.timeout 是网络层中断 stream 的方法——两者位于不同层（React 渲染 vs Web Stream），不能合并。同值 5_000 是「契约」而非冗余。console.error 是日志工具，跟 timeout 无关。建议保持现状。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q20 单文件 65 行的「克制」",
    prompt: "回顾整个 entry.server，文件的「克制」体现在？",
    options: [
      { id: "A", text: "1) 没有业务（鉴权、限流、DB） 2) 没有日志（除 onError console.error） 3) 没有 monkey patch 4) 没有副作用（纯函数式 + module-level setRuntimeEnv）——五件事各自单点不超 5 行" },
      { id: "B", text: "代码风格一致" },
      { id: "C", text: "ESLint 规则严格" },
      { id: "D", text: "TypeScript 类型完整" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "克制 = 知道什么不该放——文件读起来「无聊」是好事。",
      detail: "未来如果文件涨到 500 行，绝大概率有业务在里面，应该重构。",
    },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "code_fix",
    title: "Q21 entry.server 同时被 vite dev 和 wrangler dev 跑",
    prompt: "vite dev 跑得通，wrangler dev 报错 setRuntimeEnv is not a function。最可能原因？",
    code: `import { setRuntimeEnv } from "./utils/cloudflare-env.server";`,
codeFixBaseline: `import { setRuntimeEnv } from "./utils/cloudflare-env.server";`,
correctAnswer: { patchedCode: "vite dev 的 module 解析（vite 自带）和 wrangler dev 的 esbuild module 解析略有不同——可能 .server.ts 后缀被一边正确识别为 server-only 一边没识别（特别是路径用了 ~ alias）。修复方向：1) 保证 tsconfig.json 的 paths 同步给 wrangler vite 插件；2) 检查 import 是否相对路径正确（./utils/... 应该没问题）；3) 看看 utils/cloudflare-env.server.ts 是否真的导出了 setRuntimeEnv（命名 vs 默认）。" },
explanation: { short: "见下方解释。", detail: "vite dev 的 module 解析（vite 自带）和 wrangler dev 的 esbuild module 解析略有不同——可能 .server.ts 后缀被一边正确识别为 server-only 一边没识别（特别是路径用了 ~ alias）。修复方向：1) 保证 tsconfig.json 的 paths 同步给 wrangler vite 插件；2) 检查 import 是否相对路径正确（./utils/... 应该没问题）；3) 看看 utils/cloudflare-env.server.ts 是否真的导出了 setRuntimeEnv（命名 vs 默认）。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/utils/cloudflare-env.server.ts"],
  }),
  q({
    type: "free_explain",
    title: "Q22 自由说明：什么时候改 entry.server",
    prompt: "用一段话总结：你接到一个新需求时，怎么判断要不要改 entry.server？",
    correctAnswer: { text: "(1) 判断 1：是否平台级（CSP、Server-Timing、安全头、env 注入）→ 改 entry.server (2) 判断 2：是否业务策略（鉴权、缓存策略、Set-Cookie、分流）→ 改 loader/action 或 worker.ts (3) 判断 3：是否影响 SSR 流式行为（abort、bot 处理、status 决策）→ 改 entry.server (4) 判断 4：是否影响内容（meta、link、script、HTML 结构）→ 改 root.tsx 或具体路由 (5) 默认：能不动 entry.server 就不动——它是单点 + 全站必经，错一行即灾" },
explanation: { short: "见详细要点。", detail: "(1) 判断 1：是否平台级（CSP、Server-Timing、安全头、env 注入）→ 改 entry.server (2) 判断 2：是否业务策略（鉴权、缓存策略、Set-Cookie、分流）→ 改 loader/action 或 worker.ts (3) 判断 3：是否影响 SSR 流式行为（abort、bot 处理、status 决策）→ 改 entry.server (4) 判断 4：是否影响内容（meta、link、script、HTML 结构）→ 改 root.tsx 或具体路由 (5) 默认：能不动 entry.server 就不动——它是单点 + 全站必经，错一行即灾" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "free-response",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
];
