/**
 * Real questions for site-03-entry-server / handle-request.
 * Anchor: remix/app/entry.server.tsx
 *   - default export handleRequest(request, status, headers, remixContext, loadContext)
 *   - 五个参数：Request、responseStatusCode、responseHeaders、remixContext、loadContext
 *   - eslint-disable-next-line 标了 loadContext 不直接读，而是 cast 后取 cloudflare.env
 *   - CloudflareLoadContext = AppLoadContext & { cloudflare?: { env?: RuntimeEnv } }
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/entry.server.tsx";

export const handleRequestQuestions: RealQ[] = [
  q({
    type: "single_choice",
    title: "Q1 五参数顺序",
    prompt: "handleRequest 的参数顺序是？",
    options: [
      { id: "A", text: "(request, responseStatusCode, responseHeaders, remixContext, loadContext)" },
      { id: "B", text: "(request, response, context, status, headers)" },
      { id: "C", text: "(request, loadContext, remixContext, headers, status)" },
      { id: "D", text: "(env, request, response, context)" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "Remix/RR7 约定的固定签名，顺序不能改。",
      detail: "顺序是 React Router server runtime 调用约定：你只能从这五个参数中拿到本次 SSR 全部上下文。把它们换序框架根本不会传新参数过来。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "multi_choice",
    title: "Q2 哪些参数是「Remix 框架自己造好递给你的」",
    prompt: "下列五个参数里，哪些是 React Router 框架在调 handleRequest 时已经把内容填好的？(多选)",
    options: [
      { id: "A", text: "request——浏览器/CDN 发来的原始 Request 对象" },
      { id: "B", text: "responseStatusCode——默认 200，路由 loader/action 抛 Response 时改写" },
      { id: "C", text: "responseHeaders——Headers 实例，框架放了 link rel=preload 之类" },
      { id: "D", text: "remixContext——本次匹配的路由树 + loader 数据" },
      { id: "E", text: "loadContext——Worker fetch handler 在调 createRequestHandler 时手动塞的（这里塞了 cloudflare.env）" },
    ],
    correctAnswer: { choiceIds: ["A", "B", "C", "D", "E"] },
    explanation: {
      short: "全是框架/Worker 入口塞好的，handleRequest 不创造它们，只消费 + 增删头。",
      detail: "前四个由 React Router 自己组装；第五个 loadContext 是「你」（worker.ts 里 createRequestHandler 第二个参数）传给框架的，框架原样回传。",
    },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "remix/worker.ts"],
  }),
  q({
    type: "single_choice",
    title: "Q3 loadContext 与 cloudflareEnv",
    prompt: "代码里这样取 env：const cloudflareEnv = (loadContext as CloudflareLoadContext).cloudflare?.env;。为什么要 cast + 可选链？",
    options: [
      { id: "A", text: "AppLoadContext 是开放接口，框架不知道你塞了什么；cast 收窄类型，可选链兜底未塞 cloudflare 的情况（比如 vite dev 跑非 worker 模式）" },
      { id: "B", text: "loadContext 总是 undefined，可选链是必需的" },
      { id: "C", text: "cloudflare 是异步属性，必须可选链" },
      { id: "D", text: "TypeScript bug，可选链是 workaround" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "AppLoadContext 是 module augmentation 友好接口，运行时形状由你决定。",
      detail: "你在 worker.ts 里给 createRequestHandler 第二个参数塞 { cloudflare: { env, ctx } }，所以这里能取到。但框架类型层面不强制——可选链是「这个 entry.server 能在不带 cloudflare 的运行时下也不崩」的防御。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false",
    title: "Q4 eslint-disable",
    prompt: "代码里 loadContext 上方有 // eslint-disable-next-line @typescript-eslint/no-unused-vars 的注释。判断：这是因为 loadContext 在函数体里压根没被读到。",
    correctAnswer: { value: false },
    explanation: {
      short: "错——loadContext 被读了，cast 之后取了 cloudflare.env。",
      detail: "实际原因是参数名叫 loadContext 但 ESLint 在某些版本把 cast 后的访问当做「类型层面操作」不算 use；为了保留参数位置又关 lint，留了这一行。安全的修法是把名字改成 _loadContext 或直接删掉这行 disable。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank",
    title: "Q5 setRuntimeEnv 时机",
    prompt: "代码：if (cloudflareEnv) { ____ (cloudflareEnv); }——空格里函数名是？",
    options: [],
    blanks: [{ id: "fn", placeholder: "函数名", acceptedAnswers: ["setRuntimeEnv"] }],
    correctAnswer: { type: "fill_blank", values: { fn: "setRuntimeEnv" } },
    explanation: {
      short: "setRuntimeEnv，从 utils/cloudflare-env.server 导入。",
      detail: "每个请求都重新写一次 module-level 缓存——Worker 多请求共享 module，但 env 实例可能因 isolate 重启等原因重建，所以每次都覆写一遍最稳。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/utils/cloudflare-env.server.ts"],
  }),
  q({
    type: "single_choice",
    title: "Q6 RemixServer 包装",
    prompt: "renderToReadableStream(<RemixServer ... />, ...)——RemixServer 这个组件做什么？",
    options: [
      { id: "A", text: "把路由树 + loader 数据注入 React 上下文，让 useLoaderData 等 hook 能在 SSR 时读到当前请求的数据" },
      { id: "B", text: "渲染整个 HTML 文档（包括 doctype）" },
      { id: "C", text: "处理 Cookie 和 Session" },
      { id: "D", text: "执行 loader 函数" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "RemixServer = 上下文 provider，loader 已经在更早阶段跑完，结果通过 remixContext 传给它。",
      detail: "loader 跑在 React Router 的「数据阶段」，结果序列化进 remixContext。RemixServer 只负责把这些数据注入 Provider，让组件 SSR 时通过 useLoaderData() 读出来。HTML doctype 是 root.tsx 自己写的。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "multi_choice",
    title: "Q7 RemixServer 三个 prop",
    prompt: "<RemixServer context={remixContext} url={request.url} abortDelay={ABORT_DELAY} />——这三个 prop 的作用分别是？(选所有正确的)",
    options: [
      { id: "A", text: "context: 携带本次匹配的路由 + loader 数据，让组件树读" },
      { id: "B", text: "url: 让服务端 useLocation 等 hook 知道当前 URL" },
      { id: "C", text: "abortDelay: Suspense fallback 等多久还没就绪就放弃，触发 onError" },
      { id: "D", text: "url: 让 fetch 知道目标地址" },
      { id: "E", text: "context: 是 React Context API 的实例" },
    ],
    correctAnswer: { choiceIds: ["A", "B", "C"] },
    explanation: {
      short: "context 是 Remix 自定义对象（不是 React Context），url 给 router hook 用，abortDelay 是 Suspense 上限。",
      detail: "三者都是 RemixServer 私有 prop，跟 fetch、React Context API 都没关系。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace",
    title: "Q8 第一次请求 / 路径",
    prompt: "用户首次访问 / 时（非 bot），handleRequest 内执行的关键步骤顺序？",
    options: [
      { id: "step-1", text: "1. setRuntimeEnv(env) 写入模块缓存" },
      { id: "step-2", text: "2. 检查 url.pathname 是否 .well-known——否，继续" },
      { id: "step-3", text: "3. 进入 renderToReadableStream，挂上 AbortSignal.timeout" },
      { id: "step-4", text: "4. isbot 检查 → 用户非 bot，跳过 await body.allReady" },
      { id: "step-5", text: "5. 设 Content-Type: text/html，return new Response(body)" },
    ],
    correctAnswer: { pathIds: ["step-1", "step-2", "step-3", "step-4", "step-5"] },
    explanation: {
      short: "env 写 → well-known 短路检查 → 渲染流 → bot 分支 → 出 Response。",
      detail: "用户路径 = 流式：renderToReadableStream 一返回 ReadableStream 就回去构造 Response，浏览器边接收边渲染 shell。",
    },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace",
    title: "Q9 bot 请求路径",
    prompt: "Googlebot UA 请求 / 时，关键步骤顺序？",
    options: [
      { id: "s1", text: "1. setRuntimeEnv" },
      { id: "s2", text: "2. 不是 .well-known，继续" },
      { id: "s3", text: "3. renderToReadableStream，得到 body (ReadableStream)" },
      { id: "s4", text: "4. isbot(UA) === true → await body.allReady" },
      { id: "s5", text: "5. 流的 onShellReady + onAllReady 都跑完后，构造 Response" },
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5"] },
    explanation: {
      short: "bot 分支 = 等到所有 Suspense 边界完成再返回完整 HTML，让爬虫能拿到全文。",
      detail: "搜索引擎爬不了流式渲染（它读完一次 Response 就走），所以阻塞等 allReady。代价是 TTFB 变慢但全文可索引。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q10 onError 闭包变量",
    prompt: "renderToReadableStream(..., { onError(error) { didError = true; console.error(error); } })——为什么用闭包变量 didError 而不是直接 throw？",
    options: [
      { id: "A", text: "Suspense 边界抛错会被 React 捕获并降级（fallback），onError 只是「报告」回调；要把抛错事实带到外层（写进 status 500）就靠闭包变量回收一次" },
      { id: "B", text: "throw 会被 await 吞掉" },
      { id: "C", text: "onError 不能 throw，TypeScript 会报错" },
      { id: "D", text: "因为 React 19 不允许 onError 抛" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "Suspense 已经容错了，onError 只通知；外层用 didError 把这一事实带回 status。",
      detail: "React 流式渲染允许某个子树抛错时降级到 fallback 继续渲染父树。这种情况下 body 还是能产出（带 fallback UI），但服务器应该回 500 让运维知道。didError 闭包就是干这个的。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank",
    title: "Q11 didError 默认值",
    prompt: "let didError = ____ ;（声明时的初始值）",
    options: [],
    blanks: [{ id: "v", placeholder: "字面量", acceptedAnswers: ["false"] }],
    correctAnswer: { type: "fill_blank", values: { v: "false" } },
    explanation: {
      short: "false——onError 触发时翻成 true，最后用三元决定 status。",
      detail: "如果初始 true，永远 500——任何顺利请求也变错误。这是必然的初始值。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "basic",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q12 status 三元",
    prompt: "return new Response(body, { headers: responseHeaders, status: didError ? 500 : responseStatusCode });——这个三元为什么不是 didError ? 500 : 200？",
    options: [
      { id: "A", text: "因为 responseStatusCode 可能是 404、302 等——loader 抛 Response 时 React Router 会把 status 传过来；只有真正发生渲染错误时才覆写成 500" },
      { id: "B", text: "200 已经隐含在 responseStatusCode 默认值里" },
      { id: "C", text: "Cloudflare 不允许写死 200" },
      { id: "D", text: "性能优化" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "保留 loader/action 想要的 status，只在 SSR 出错时强制 500。",
      detail: "throw new Response('Not Found', {status: 404}) 在 loader 里抛 → React Router 把 404 透到 responseStatusCode → 这里要保留它。如果硬写 200，就把所有 4xx 都吞掉了。",
    },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false",
    title: "Q13 responseHeaders 是否可改",
    prompt: "responseHeaders.set('Content-Type', 'text/html')——判断：handleRequest 里只能 set，不能 delete 或 append。",
    correctAnswer: { value: false },
    explanation: {
      short: "错——responseHeaders 是 Headers 实例，set/append/delete 全都能用。",
      detail: "实践上一般只 set Content-Type 和加自定义头（Server-Timing 等），但你想 delete 框架塞的 link preload 也是合法的。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q14 Content-Type 默认值",
    prompt: "如果删掉 responseHeaders.set('Content-Type', 'text/html')，浏览器拿到的 Response 是什么 MIME？",
    options: [
      { id: "A", text: "由框架/平台决定——Cloudflare Workers 通常会给一个默认 text/plain 或不设，浏览器可能按 sniff 启动渲染但不可靠（部分浏览器拒绝执行 inline script）" },
      { id: "B", text: "永远 text/html" },
      { id: "C", text: "永远 application/json" },
      { id: "D", text: "永远 text/plain" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "不可靠——这一行是「显式声明」，删了出问题难调。",
      detail: "依赖 sniffing 是反模式：CSP nosniff 启用后浏览器拒绝执行 inline JS，整个 SSR 失效。这一行是契约，不是装饰。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q15 loadContext 拿不到 env",
    prompt: "假设你部署到一个不传 cloudflare 字段的环境，cloudflareEnv 是 undefined。当前代码会怎样？",
    options: [
      { id: "A", text: "if (cloudflareEnv) 守门跳过 setRuntimeEnv，照常 SSR；后续 getEnvVar 会走 process.env / globalThis fallback；如果都没有就拿到 undefined（getRequiredEnv 会抛）" },
      { id: "B", text: "立即抛 TypeError" },
      { id: "C", text: "renderToReadableStream 会拒绝" },
      { id: "D", text: "Cloudflare 拒绝部署" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "if 守门 → 跳过；后续看代码用 getRequiredEnv 还是 getEnvVar 决定结果。",
      detail: "这是「优雅降级」——dev 跑非 Worker 模式（vite dev 默认）时也要能 SSR，cloudflareEnv 自然 undefined。生产 Worker 一定有，所以这里不强制。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "code_fix",
    title: "Q16 移走 setRuntimeEnv",
    prompt: "有人把 setRuntimeEnv 调用挪到了 renderToReadableStream 之后才执行。这会出什么问题？请给出最小修复。",
    code: `const body = await renderToReadableStream(<RemixServer .../>, {...});\nif (cloudflareEnv) setRuntimeEnv(cloudflareEnv); // 挪到了这里`,
codeFixBaseline: `const body = await renderToReadableStream(<RemixServer .../>, {...});\nif (cloudflareEnv) setRuntimeEnv(cloudflareEnv); // 挪到了这里`,
correctAnswer: { patchedCode: "把 setRuntimeEnv 调用挪回 renderToReadableStream 之前。loader 是在 renderToReadableStream 内部执行的，loader 用 getEnvVar('AUTH_KEY_SECRET') 等会读不到，全部走 fallback；最坏拿到 undefined 直接抛。" },
explanation: { short: "见下方解释。", detail: "把 setRuntimeEnv 调用挪回 renderToReadableStream 之前。loader 是在 renderToReadableStream 内部执行的，loader 用 getEnvVar('AUTH_KEY_SECRET') 等会读不到，全部走 fallback；最坏拿到 undefined 直接抛。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "position_judgement",
    title: "Q17 决策：要在 handleRequest 里加日志",
    prompt: "你想给所有 SSR 请求加一条「请求 URL + 是否 bot + 耗时」日志。落点选？",
    options: [
      { id: "A", text: "entry.server.tsx 里 handleRequest 函数体——所有 SSR 请求必经，且能拿到 didError、isbot 判定" },
      { id: "B", text: "root.tsx 的 loader 里——更靠业务" },
      { id: "C", text: "每个路由 loader 里都加" },
      { id: "D", text: "worker.ts 入口" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "entry.server 是 SSR 链路上「单点 + 拿得到全部信号」的位置。",
      detail: "B 漏掉只渲染不跑 loader 的页面（理论极少但有），C 是 N×重复，D 拿不到 didError 和 isbot 判定。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q18 单文件 65 行的克制",
    prompt: "整个 entry.server.tsx 才 65 行。这个「短」本身传达了什么设计意图？",
    options: [
      { id: "A", text: "entry.server 是「SSR 框架接缝」，不放业务——业务在 loader/action/组件里。这里多写一行都是大决定" },
      { id: "B", text: "团队没空写完" },
      { id: "C", text: "故意混淆，保护商业秘密" },
      { id: "D", text: "Remix 限制 100 行" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "短 = 边界明确。entry.server 的职责是把 React 树渲成 Response，不是放业务。",
      detail: "你想加日志、加监控、加埋点，都先想想能不能放到 loader 或者 worker.ts。entry.server 越克制越不容易把整站 SSR 搞挂。",
    },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank",
    title: "Q19 import 三件套",
    prompt: "entry.server.tsx 顶部三个关键 import：\n  import { isbot } from \"____ \";\n  import { renderToReadableStream } from \"react-dom/____ \";\n  import { setRuntimeEnv, type RuntimeEnv } from \"./utils/____ \";\n请填三处。",
    options: [],
    blanks: [
      { id: "p1", placeholder: "包名", acceptedAnswers: ["isbot"] },
      { id: "p2", placeholder: "subpath", acceptedAnswers: ["server.browser"] },
      { id: "p3", placeholder: "文件名（不含扩展）", acceptedAnswers: ["cloudflare-env.server"] },
    ],
    correctAnswer: { type: "fill_blank", values: { p1: "isbot", p2: "server.browser", p3: "cloudflare-env.server" } },
    explanation: {
      short: "isbot / react-dom/server.browser / ./utils/cloudflare-env.server",
      detail: "三个 import 决定了文件能不能跑：isbot 决定 bot 分支，server.browser 决定流式 API，cloudflare-env.server 让 setRuntimeEnv 写进缓存。",
    },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q20 跨 isolate 的 setRuntimeEnv",
    prompt: "Cloudflare Worker 的 module-level 变量在 isolate 重启后会丢。这里每次请求都调 setRuntimeEnv 的设计弥补了什么？",
    options: [
      { id: "A", text: "新 isolate 的第一次请求自然进 handleRequest，立刻把 env 写进缓存——之后这个 isolate 内所有请求都能 getEnvVar，无需每次重新读 binding" },
      { id: "B", text: "Cloudflare 限制每分钟只能读 env 一次" },
      { id: "C", text: "loader 不能直接接收 env" },
      { id: "D", text: "防止 env 被篡改" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "isolate 重启 + module 缓存的 race，靠每次请求都 set 来解。",
      detail: "另一个常见误解是「每次都 set 是浪费」——实际上覆写 module 变量是 O(1)，几乎零成本，但能保证「无论 isolate 多新，第一个请求结束后都能让 module 拿到 env」。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/utils/cloudflare-env.server.ts"],
  }),
  q({
    type: "review_comment",
    title: "Q21 Review：error 不报到外部",
    prompt: "Reviewer 在 onError 处留言：「这里只 console.error，没有把错误上报到 Sentry/Logpush，生产看不到具体堆栈，建议加上报。」请用一句话评价这条评审。",
    correctAnswer: { comment: "评审合理。entry.server 是「最后一关」，这里捕获到的是 SSR 树渲染错；不上报就只能看 worker tail——堆栈被截断的概率很高。生产想可观测，确实该把 onError 接到 Logpush 或 Sentry，但要小心：onError 是同步回调，里面发请求会阻塞流；推荐只 enqueue 到 ctx.waitUntil(reportError(error)) 异步上报。" },
explanation: { short: "见 review comment。", detail: "评审合理。entry.server 是「最后一关」，这里捕获到的是 SSR 树渲染错；不上报就只能看 worker tail——堆栈被截断的概率很高。生产想可观测，确实该把 onError 接到 Logpush 或 Sentry，但要小心：onError 是同步回调，里面发请求会阻塞流；推荐只 enqueue 到 ctx.waitUntil(reportError(error)) 异步上报。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "free_explain",
    title: "Q22 自由说明：handleRequest 在 SSR 链路里的位置",
    prompt: "用一段话说明：浏览器从输入 URL 到看到首屏 HTML，handleRequest 在这条链上排第几站、上一站和下一站分别是什么、它能做和不能做什么。",
    correctAnswer: { text: "(1) 上一站：worker.ts 的 fetch handler，调 createRequestHandler(handler) 把请求交给 React Router runtime (2) 再上一站：React Router runtime 解析路由 + 跑所有 matched loader (3) handleRequest 是这一站：拿到 remixContext（含 loader 数据）+ 框架塞好的 status/headers，决定怎么把树渲染成 Response (4) 下一站：return Response 回到 worker.ts，由 fetch handler 返还给 Cloudflare 网络 (5) 能做：set 响应头、决定流式还是 allReady、捕获 SSR 错误改 status (6) 不能做：跑 loader（已经跑过了）、做权限校验（应该在 loader 里早返）、连数据库（这里只是把树渲染成字节流）" },
explanation: { short: "见详细要点。", detail: "(1) 上一站：worker.ts 的 fetch handler，调 createRequestHandler(handler) 把请求交给 React Router runtime (2) 再上一站：React Router runtime 解析路由 + 跑所有 matched loader (3) handleRequest 是这一站：拿到 remixContext（含 loader 数据）+ 框架塞好的 status/headers，决定怎么把树渲染成 Response (4) 下一站：return Response 回到 worker.ts，由 fetch handler 返还给 Cloudflare 网络 (5) 能做：set 响应头、决定流式还是 allReady、捕获 SSR 错误改 status (6) 不能做：跑 loader（已经跑过了）、做权限校验（应该在 loader 里早返）、连数据库（这里只是把树渲染成字节流）" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "free-response",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "remix/worker.ts"],
  }),
];
