/**
 * Real questions for site-03-entry-server / response-headers.
 * Anchor: remix/app/entry.server.tsx
 *   - responseHeaders.set("Content-Type", "text/html")
 *   - status: didError ? 500 : responseStatusCode
 *   - /.well-known/* 短路 Response { 200, "Content-Type": "application/json", "Cache-Control": "public, max-age=3600" }
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/entry.server.tsx";

export const responseHeadersQuestions: RealQ[] = [
  q({
    type: "single_choice",
    title: "Q1 唯一被 set 的头",
    prompt: "handleRequest 主路径里 responseHeaders.set 只调用了一次，set 的头是？",
    options: [
      { id: "A", text: "Content-Type: text/html" },
      { id: "B", text: "Cache-Control: no-store" },
      { id: "C", text: "Set-Cookie" },
      { id: "D", text: "X-Powered-By: Remix" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "Content-Type: text/html，告诉浏览器接下来的字节流是 HTML。",
      detail: "其他响应头由 React Router 框架在 responseHeaders 里预填（比如 Link rel=preload），handleRequest 只补这一个最关键的。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q2 Cache-Control 在哪",
    prompt: "/.well-known/ 短路 Response 的 Cache-Control 值是？",
    options: [
      { id: "A", text: "public, max-age=3600" },
      { id: "B", text: "no-store" },
      { id: "C", text: "private, max-age=60" },
      { id: "D", text: "no-cache, must-revalidate" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "公开缓存 1 小时——.well-known 是浏览器/扩展定期探测的，缓 1 小时省 Worker 调用费。",
      detail: "max-age=3600 = 3600 秒 = 1 小时；public 表示 CDN 也能缓。这条路径上没有用户特定数据，缓存安全。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank",
    title: "Q3 .well-known 短路完整 status",
    prompt: ".well-known 短路返回的 Response 是 status: ____, body 是空对象 JSON 字符串。",
    options: [],
    blanks: [{ id: "v", placeholder: "数字", acceptedAnswers: ["200"] }],
    correctAnswer: { type: "fill_blank", values: { v: "200" } },
    explanation: {
      short: "200——告诉探测者「这是合法响应，但内容空」。",
      detail: "返回 404 也行，但 200 + {} 让一些较为严格的探测客户端不会重试。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q4 short-circuit 顺序",
    prompt: "if (url.pathname.startsWith('/.well-known/')) { return ... } 这个判断放在 setRuntimeEnv 之后、renderToReadableStream 之前。如果挪到 setRuntimeEnv 之前会怎样？",
    options: [
      { id: "A", text: "对功能无影响——.well-known 路径不会触发 SSR，set 与不 set runtime env 都行；但每次请求绕过 setRuntimeEnv 会让正常路径下「冷启动后第一个 .well-known 探测」之后接的第一个真请求拿不到 env" },
      { id: "B", text: "立即崩溃" },
      { id: "C", text: "Cloudflare 拒绝部署" },
      { id: "D", text: "完全等价" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "顺序 = 防御性。先 setRuntimeEnv 再短路，保证就算只有 .well-known 进来也建好缓存。",
      detail: "实际差异极小（getRequiredEnv 第一次会兜底从 process.env 取），但「先建缓存再决定要不要短路」是更稳的写法。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false",
    title: "Q5 didError 与 status 的耦合",
    prompt: "判断：如果 onError 触发但 SSR 仍然产出了完整 body，最终 Response 的 status 还是 500。",
    correctAnswer: { value: true },
    explanation: {
      short: "对——didError 一旦翻 true，status: didError ? 500 : responseStatusCode 就走 500 分支。",
      detail: "这是一个保守策略：宁可 500 让运维察觉，也不让看起来正常的 200 掩盖渲染异常。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q6 status 与 SEO",
    prompt: "假设你想让 SSR 错误也返 200，让爬虫不丢页面。建议的修改方式？",
    options: [
      { id: "A", text: "不要这么干——爬虫看到 200 + 空白/降级 HTML 会以为这是真实内容索引；坚持 500，让爬虫等下次重抓" },
      { id: "B", text: "把 didError ? 500 改成 didError ? 200" },
      { id: "C", text: "把 didError 改成 false" },
      { id: "D", text: "在 fetch 层强制 status = 200" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "SEO 角度，500 比错误的 200 安全得多。",
      detail: "Google/Bing 看到 5xx 会把这次结果丢弃；看到 200 + 错误页则会把错误页当作内容索引，正常版本被排到错误版本之下。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "multi_choice",
    title: "Q7 Headers 来源四条",
    prompt: "返回的 Response headers 由谁贡献？(多选)",
    options: [
      { id: "A", text: "React Router 框架——matched 路由的 headers() 函数返回的内容" },
      { id: "B", text: "loader/action 返回 json() 时的 headers" },
      { id: "C", text: "entry.server.tsx 自己加的 Content-Type" },
      { id: "D", text: "Cloudflare 网络层（CF-Ray、Server 等）" },
      { id: "E", text: "ServiceWorker 缓存层（不存在，混淆项）" },
    ],
    correctAnswer: { choiceIds: ["A", "B", "C", "D"] },
    explanation: {
      short: "框架 + loader/action + entry.server + Cloudflare 网络层——五条之外没有别人。",
      detail: "排除 E：Cloudflare 没有 Service Worker 中间层，CF Workers 自己就是请求处理。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts"],
  }),
  q({
    type: "single_choice",
    title: "Q8 加全站 Server-Timing 落点",
    prompt: "你想给所有 SSR 响应加一个 Server-Timing: ssr;dur={ms} 头。最合适的位置？",
    options: [
      { id: "A", text: "entry.server.tsx 在 renderToReadableStream 前后取 performance.now()，差值后 responseHeaders.set('Server-Timing', `ssr;dur=${dur}`)" },
      { id: "B", text: "每个 loader 里加" },
      { id: "C", text: "root.tsx 的 Layout 里加" },
      { id: "D", text: "worker.ts 入口的 fetch handler 里" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "entry.server 是唯一能拿到「SSR 渲染时长」单点。",
      detail: "B/C 拿不到 SSR 总时长，D 能拿到但需要两次反 React 才能塞进 Response headers——entry.server 是最自然的位置。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "code_fix",
    title: "Q9 重复 set Content-Type",
    prompt: "新代码里有人写了两行 set：responseHeaders.set('Content-Type', 'text/html'); responseHeaders.set('Content-Type', 'text/html; charset=utf-8'); 哪一行胜出？",
    code: `responseHeaders.set("Content-Type", "text/html");\nresponseHeaders.set("Content-Type", "text/html; charset=utf-8");`,
codeFixBaseline: `responseHeaders.set("Content-Type", "text/html");\nresponseHeaders.set("Content-Type", "text/html; charset=utf-8");`,
correctAnswer: { patchedCode: "Headers.set 的语义是「替换」，第二行覆盖第一行——最终 Content-Type 是 text/html; charset=utf-8。如果想保留两个值（不该这么做），用 append；想要 utf-8，直接写第二行那行就够。" },
explanation: { short: "见下方解释。", detail: "Headers.set 的语义是「替换」，第二行覆盖第一行——最终 Content-Type 是 text/html; charset=utf-8。如果想保留两个值（不该这么做），用 append；想要 utf-8，直接写第二行那行就够。" },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q10 charset 是否需要",
    prompt: "Content-Type 写 text/html 没带 charset=utf-8 是否安全？",
    options: [
      { id: "A", text: "现代浏览器 + UTF-8 文件实际能正常渲染——HTML5 默认 UTF-8；但显式 charset 是更稳的工程实践（特别是有用户输入注入时防止 UTF-7 攻击）" },
      { id: "B", text: "完全不安全，会立即乱码" },
      { id: "C", text: "永远不需要 charset" },
      { id: "D", text: "Cloudflare 会自动加" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "实际能跑，但工程上建议显式 charset=utf-8。",
      detail: "Remix/RR7 模板里没带是因为 root.tsx 的 <meta charSet=\"utf-8\" /> 提供了 in-document declaration——双保险。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "branch_trace",
    title: "Q11 .well-known 短路完整路径",
    prompt: "Chrome DevTools Network 里访问 /.well-known/appspecific/chrome.foo，handleRequest 内步骤？",
    options: [
      { id: "s1", text: "1. 进入 handleRequest" },
      { id: "s2", text: "2. setRuntimeEnv（如果 cloudflareEnv 存在）" },
      { id: "s3", text: "3. const url = new URL(request.url)" },
      { id: "s4", text: "4. url.pathname.startsWith('/.well-known/') === true → 短路返回 {} JSON 200" },
      { id: "s5", text: "5. 不再进入 renderToReadableStream，直接出 handleRequest" },
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5"] },
    explanation: {
      short: "短路在 setRuntimeEnv 之后、render 之前——提前出函数。",
      detail: "短路的核心收益：Worker 不进 React 树渲染，省 CPU + 内存（CF Workers 按 ms + 内存计费）。",
    },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false",
    title: "Q12 .well-known body",
    prompt: "判断：短路返回的 body 是 JSON.stringify({}) 即字符串 '{}', 不是空字符串。",
    correctAnswer: { value: true },
    explanation: {
      short: "对——代码就是 new Response(JSON.stringify({}), ...)。",
      detail: "空字符串 + Content-Type: application/json 在 strict JSON parser 上会抛 SyntaxError；'{}' 是合法 JSON。这里防御了部分严苛的探测客户端。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "position_judgement",
    title: "Q13 决策：所有 /api 也短路",
    prompt: "新需求：所有 /api/* 路径要绕过 SSR React 树渲染，直接走 loader 输出 JSON。在 entry.server 加 if (url.pathname.startsWith('/api/')) 短路是否合适？",
    options: [
      { id: "A", text: "不合适——/api/* 已经是 React Router 的 resource route（仅 export loader/action 无 default），框架自己就不会渲染 React 树。再短路一遍是重复" },
      { id: "B", text: "合适，提速明显" },
      { id: "C", text: "合适，但要在 .well-known 之前加" },
      { id: "D", text: "用 worker.ts 入口短路" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "Resource route 自动跳过 SSR——不需要在 entry.server 重复。",
      detail: "react-router 文件路由约定：api.nemesis.ts 这类只 export loader/action 不 export default 的，框架自动认为是 resource route，loader 返回的 Response 直接出去，不进 RemixServer 渲染。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/routes/api.nemesis.ts"],
  }),
  q({
    type: "single_choice",
    title: "Q14 Set-Cookie 落点",
    prompt: "你想 SSR 时给所有响应都加 Set-Cookie: theme=light（如果客户端没传）。最合适的位置？",
    options: [
      { id: "A", text: "root.tsx 的 loader 里 return json(..., { headers: { 'Set-Cookie': cookieStr } })——loader 已经能读 cookie 决定要不要发新值，且 React Router 会把 loader headers 合进最终 Response" },
      { id: "B", text: "entry.server.tsx 的 responseHeaders.set" },
      { id: "C", text: "worker.ts" },
      { id: "D", text: "浏览器 fetch 拦截" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "Set-Cookie 是「业务决策」（要不要 set、值是什么），属于 root loader/action。",
      detail: "entry.server 是平台层，加 Set-Cookie 等于把业务上提一层，未来 Multi-tenant 主题就难拆。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture", "backend.session.cookie"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice",
    title: "Q15 didError 输出 status 但 body 内容",
    prompt: "didError = true 时，浏览器看到的 body 是什么？",
    options: [
      { id: "A", text: "renderToReadableStream 返回的 stream——里面是部分 SSR HTML（出错子树降级到 Suspense fallback、其他子树正常渲染）" },
      { id: "B", text: "空 body" },
      { id: "C", text: "JSON 错误对象" },
      { id: "D", text: "RouteErrorBoundary 渲染的内容（永远）" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "Body 还是 React 流的产物——状态码是 500 但 HTML 不为空。",
      detail: "如果错的子树有 RouteErrorBoundary 包裹，会渲染 boundary；没包则降到框架兜底（一般是空白）。整体响应是「500 + 部分 HTML」。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/components/error/RouteErrorBoundary.tsx"],
  }),
  q({
    type: "single_choice",
    title: "Q16 短路与 SEO",
    prompt: "/.well-known/security.txt 这种规范路径，短路返回 {} JSON 200 会有什么副作用？",
    options: [
      { id: "A", text: "扫描器拿到 JSON 而不是预期的 plaintext 安全声明，可能误判「站点没有 security.txt」——如果你确实想发布，应该在短路前先 if (pathname === '/.well-known/security.txt') 单独处理" },
      { id: "B", text: "Cloudflare 拒绝部署" },
      { id: "C", text: "Browser 报错" },
      { id: "D", text: "无任何副作用" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "短路是粗粒度策略——你想发布特定 .well-known 资源，要在短路前显式 case。",
      detail: "实际个人站常见 .well-known 流量都是 Chrome / 扩展 / 监控的探测，业务上没意义；短路是合理优化。",
    },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "code_fix",
    title: "Q17 status 漏 didError",
    prompt: "有人重写为 status: responseStatusCode（去掉 didError 三元）。生产症状会是？",
    code: `return new Response(body, {\n  headers: responseHeaders,\n  status: responseStatusCode,\n});`,
codeFixBaseline: `return new Response(body, {\n  headers: responseHeaders,\n  status: responseStatusCode,\n});`,
correctAnswer: { patchedCode: "症状：SSR 出错时返回 200 + 不完整/降级 HTML——爬虫和监控都不会发现「这个页面渲染坏了」。修复：恢复三元 status: didError ? 500 : responseStatusCode。如果担心 500 太激进，至少改成 504/503，但绝不能 200。" },
explanation: { short: "见下方解释。", detail: "症状：SSR 出错时返回 200 + 不完整/降级 HTML——爬虫和监控都不会发现「这个页面渲染坏了」。修复：恢复三元 status: didError ? 500 : responseStatusCode。如果担心 500 太激进，至少改成 504/503，但绝不能 200。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false",
    title: "Q18 Cache-Control on text/html",
    prompt: "判断：entry.server 没在 SSR HTML Response 上 set Cache-Control，所以 HTML 默认不缓存。",
    correctAnswer: { value: false },
    explanation: {
      short: "错——「没 set」不等于「不缓存」；浏览器有启发式缓存（heuristic caching），CDN 可能也有默认 TTL。",
      detail: "想 100% 不缓存要显式 Cache-Control: no-store。Remix 模板里 HTML 默认让 loader 决定（root loader 设 private,no-store 或 public,max-age）。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice",
    title: "Q19 加自定义 X-Frame-Options",
    prompt: "想给所有 SSR HTML 加 X-Frame-Options: DENY 防 iframe 嵌入。落点选？",
    options: [
      { id: "A", text: "entry.server 的 responseHeaders.set——平台级安全头，所有 HTML 必须有，放这里最保险" },
      { id: "B", text: "root.tsx 的 loader headers" },
      { id: "C", text: "每个路由 headers()" },
      { id: "D", text: "wrangler.toml 的 routes" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "安全头要「全局生效不可漏」，entry.server 是单点。",
      detail: "B 在 SPA 跳转时不一定每次跑（虽然 SSR 一定跑），保险还是 entry.server。CSP、X-Content-Type-Options 同理。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q20 添加 nonce 头",
    prompt: "你启用了 CSP nonce 防 XSS，每次 SSR 要给 inline script/style 同一个随机 nonce。最佳落点？",
    options: [
      { id: "A", text: "entry.server 早期 const nonce = crypto.randomUUID(); 写进 loadContext 让 root.tsx 能读，同时 responseHeaders.set('Content-Security-Policy', `script-src 'nonce-${nonce}'`)" },
      { id: "B", text: "root.tsx 的 loader 生成 nonce 并写 headers" },
      { id: "C", text: "每个组件自己生成 nonce" },
      { id: "D", text: "client 端生成 nonce" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "nonce 必须 SSR 生成 + 同时进 CSP 头和 inline tag，entry.server 是唯一能两端写的位置。",
      detail: "B 在 root loader 里生成可以，但要把 nonce 注入 entry.server 的 responseHeaders 比较绕；entry.server 是干净路径。client 生成不行——client 的 nonce 浏览器不接受。",
    },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "review_comment",
    title: "Q21 Review：cache 短路",
    prompt: "Reviewer 留言：「.well-known 短路用 Cache-Control max-age=3600 太短了，建议改 86400 一天。」请评价。",
    correctAnswer: { comment: "评审基本合理但要小心。1 小时改 1 天对 .well-known 探测流量降本 24x，业务无影响；但有少数 .well-known 子路径（如 acme-challenge for Let's Encrypt）必须实时——如果以后开启证书续期，这种路径会被旧缓存挡住。建议：保留 1 小时，或者 if (pathname.startsWith('/.well-known/acme-challenge/')) 不短路，其他可以延长。" },
explanation: { short: "见 review comment。", detail: "评审基本合理但要小心。1 小时改 1 天对 .well-known 探测流量降本 24x，业务无影响；但有少数 .well-known 子路径（如 acme-challenge for Let's Encrypt）必须实时——如果以后开启证书续期，这种路径会被旧缓存挡住。建议：保留 1 小时，或者 if (pathname.startsWith('/.well-known/acme-challenge/')) 不短路，其他可以延长。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "free_explain",
    title: "Q22 自由说明：响应头三层来源",
    prompt: "用一段话说明：一个最终的 SSR 响应中，Cache-Control、Content-Type、Set-Cookie、CSP 这四个头分别由哪一层（entry.server / root loader / 路由 loader / 框架）合理负责。",
    correctAnswer: { text: "(1) Cache-Control：业务策略，应在 root loader / 路由 loader 里 set——根据是否登录、内容是否私有决定 (2) Content-Type：平台契约，entry.server 兜底 text/html (3) Set-Cookie：业务决策（theme/session），属 root action 或路由 loader/action (4) CSP：平台安全策略（特别是 nonce 类需要每请求随机），放 entry.server 最合理 (5) 总原则：业务变量交给 loader/action（能 per-route override），平台不变交给 entry.server" },
explanation: { short: "见详细要点。", detail: "(1) Cache-Control：业务策略，应在 root loader / 路由 loader 里 set——根据是否登录、内容是否私有决定 (2) Content-Type：平台契约，entry.server 兜底 text/html (3) Set-Cookie：业务决策（theme/session），属 root action 或路由 loader/action (4) CSP：平台安全策略（特别是 nonce 类需要每请求随机），放 entry.server 最合理 (5) 总原则：业务变量交给 loader/action（能 per-route override），平台不变交给 entry.server" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "free-response",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/root.tsx", "app/lib/cache-headers.server.ts"],
  }),
];
