/**
 * Real questions for site-03-entry-server / stream-fallback.
 * Anchor: remix/app/entry.server.tsx
 *   - renderToReadableStream 返回 ReadableStream（Web Streams API）
 *   - signal: AbortSignal.timeout(ABORT_DELAY) — 5 秒超时
 *   - body.allReady 仅 bot 路径
 *   - onError 闭包变量 didError
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/entry.server.tsx";

export const streamFallbackQuestions: RealQ[] = [
  q({
    type: "single_choice",
    title: "Q1 流式 API",
    prompt: "renderToReadableStream(...) 返回的对象类型是？",
    options: [
      { id: "A", text: "ReadableStream（Web Streams API），同时挂了 react-dom 扩展属性 allReady" },
      { id: "B", text: "Node.js Readable" },
      { id: "C", text: "Promise<string>" },
      { id: "D", text: "Buffer" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "Web Streams 的 ReadableStream，可以直接传给 new Response。",
      detail: "Cloudflare Workers 用 Web Streams 而非 Node Streams。React 18+ 的 server.browser 出口正是为这种环境设计。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank",
    title: "Q2 timeout API",
    prompt: "signal: AbortSignal.____ (ABORT_DELAY)——空格里方法名是？",
    options: [],
    blanks: [{ id: "fn", placeholder: "静态方法名", acceptedAnswers: ["timeout"] }],
    correctAnswer: { type: "fill_blank", values: { fn: "timeout" } },
    explanation: {
      short: "AbortSignal.timeout——比手写 setTimeout + AbortController 简洁。",
      detail: "返回值是 AbortSignal 实例，N ms 后自动 abort。Worker 运行时支持，需 Node 18+。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q3 timeout 触发后的级联",
    prompt: "5 秒到时 AbortSignal 触发，会发生什么？",
    options: [
      { id: "A", text: "renderToReadableStream 内部接到 abort 信号，已开始的渲染会停止；onError 收到一个 AbortError；body 还能 read 但部分子树没填完" },
      { id: "B", text: "Worker 立即崩溃" },
      { id: "C", text: "用户看到永久 loading" },
      { id: "D", text: "ReadableStream 自动重试" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "abort → onError → didError = true → 最终返回 500 + 部分 body。",
      detail: "兜底机制确保「再慢的页面」也能在 5 秒内出 Response，不挂死整个 isolate。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q4 ReadableStream 与 Response",
    prompt: "为什么能直接 new Response(body, { ... })，body 是 ReadableStream？",
    options: [
      { id: "A", text: "Fetch API 标准定义 Response 构造器接受 ReadableStream 作为 body——浏览器/Worker/Deno 都遵循" },
      { id: "B", text: "Cloudflare 自定义扩展" },
      { id: "C", text: "Remix 框架包了一层" },
      { id: "D", text: "需要先 new TextEncoder().encode(...)" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "Web 标准 Response body 类型支持 ReadableStream。",
      detail: "其他合法 body 类型：string、Uint8Array、Blob、FormData、URLSearchParams、ArrayBuffer。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false",
    title: "Q5 流的多次消费",
    prompt: "判断：return new Response(body) 之后，handleRequest 内部还能再 await body.allReady（在另一个分支里）。",
    correctAnswer: { value: false },
    explanation: {
      short: "错——ReadableStream 只能消费一次，被 Response 拿走后再读会拿到 already locked 错误。",
      detail: "代码里 await body.allReady 在 return 之前——这个时间点 body 还没 lock 给 Response。顺序很重要。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q6 ABORT_DELAY 用三处",
    prompt: "ABORT_DELAY = 5_000 在文件里出现几次？",
    options: [
      { id: "A", text: "两次：abortDelay={ABORT_DELAY} 给 RemixServer + AbortSignal.timeout(ABORT_DELAY) 给 stream signal" },
      { id: "B", text: "一次" },
      { id: "C", text: "三次" },
      { id: "D", text: "0 次（被静态分析消除）" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "两处共用同一常量——RemixServer 内部 Suspense 超时 + stream 整体超时。",
      detail: "两个 timeout 协同：Suspense 超时 → fallback；stream 超时 → 整个 abort。同值就是「不给 stream 比 Suspense 更宽松的窗口」。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "code-reading",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q7 调长 ABORT_DELAY 的代价",
    prompt: "把 ABORT_DELAY 调到 30_000（30 秒），代价是？",
    options: [
      { id: "A", text: "loader 慢的页面能完成 SSR 不出 500，但 Worker 占用 CPU/wall time 30 秒（CF Workers 计费按 ms），且用户体验上等久会主动关页面——一般不调超过 10 秒" },
      { id: "B", text: "立即拒绝部署" },
      { id: "C", text: "Cloudflare 强制 30 秒上限" },
      { id: "D", text: "ReadableStream 不支持超过 5 秒" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "技术允许；权衡是 Worker 计费 + 用户体验。",
      detail: "CF Workers Free 计划 CPU 时间 10ms/请求，Paid 50ms（特殊场景到 5min）。30 秒 wall time 没 CPU 限制（IO 等待）但也很贵。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace",
    title: "Q8 Suspense 边界 fallback 触发",
    prompt: "页面 A 含一个 Suspense 包着的慢组件 SlowList，loader 4 秒返回。bot 请求时步骤？",
    options: [
      { id: "s1", text: "1. renderToReadableStream 开始，shell（非 Suspense 部分）秒级输出" },
      { id: "s2", text: "2. SlowList 在 4 秒后准备好" },
      { id: "s3", text: "3. ABORT_DELAY=5 秒 > 4 秒，所有 Suspense 边界都填好" },
      { id: "s4", text: "4. await body.allReady 解决（resolve）" },
      { id: "s5", text: "5. 返回完整 HTML，bot 拿到全文" },
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5"] },
    explanation: {
      short: "5 秒窗口足以覆盖 4 秒的慢 loader——bot 拿到完整内容。",
      detail: "如果 SlowList 慢到 6 秒，会在 step 3 处被 abort，bot 拿到的 HTML 里 SlowList 还是 fallback。",
    },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q9 stream 与 SSR 重启",
    prompt: "Cloudflare isolate 突然回收。当前流式响应会怎样？",
    options: [
      { id: "A", text: "正在传输的 body stream 被中断，浏览器看到不完整 HTML——通常浏览器自己重试或显示「连接被重置」" },
      { id: "B", text: "Cloudflare 自动续传" },
      { id: "C", text: "isolate 不会被回收" },
      { id: "D", text: "用户重连后继续接收" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "中断 → 浏览器重试是正常 web 行为。",
      detail: "Cloudflare 不保证 isolate 生命周期；流式响应天然要面对中断。这也是为什么 SSR 内不该做副作用：isolate 半路死掉，副作用执行了一半。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "code_fix",
    title: "Q10 误用 await 在 stream 上",
    prompt: "有人改成 const html = await body.text();——把流转字符串再 return。后果？",
    code: `const html = await body.text();\nreturn new Response(html, { headers: responseHeaders, status: ... });`,
codeFixBaseline: `const html = await body.text();\nreturn new Response(html, { headers: responseHeaders, status: ... });`,
correctAnswer: { patchedCode: "症状：所有用户都退化成 allReady 行为（等整个 SSR 完成才发字节），TTFB 变慢；额外内存代价（整个 HTML 在 Worker 内存里组装）；body.text 不存在/不可靠（Web ReadableStream 没有 .text 方法，要 new Response(body).text() 才能转）。修复：恢复 return new Response(body, ...) 直接传流。" },
explanation: { short: "见下方解释。", detail: "症状：所有用户都退化成 allReady 行为（等整个 SSR 完成才发字节），TTFB 变慢；额外内存代价（整个 HTML 在 Worker 内存里组装）；body.text 不存在/不可靠（Web ReadableStream 没有 .text 方法，要 new Response(body).text() 才能转）。修复：恢复 return new Response(body, ...) 直接传流。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q11 onError 触发频次",
    prompt: "页面有 3 个 Suspense 边界都抛错。onError 被调几次？",
    options: [
      { id: "A", text: "3 次——每个边界的错都通知一次；didError 在第一次就翻 true，后续不变" },
      { id: "B", text: "1 次（第一个错就停）" },
      { id: "C", text: "0 次（流被 abort）" },
      { id: "D", text: "随机次数" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "每错一次报一次；didError 只翻一次。",
      detail: "console.error 会打印 3 次堆栈——dev 时 3 次能帮诊断，但生产可以考虑去重。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q12 onShellReady vs onAllReady",
    prompt: "renderToReadableStream 的回调里只用 onError，没用 onShellReady、onAllReady。原因？",
    options: [
      { id: "A", text: "Web 版（react-dom/server.browser）的 renderToReadableStream 与 Node 版的 renderToPipeableStream 接口不同——Web 版直接返回 ReadableStream 对象，allReady/onShellReady 是 stream 自身的属性/事件，不需要再传回调" },
      { id: "B", text: "代码漏写了" },
      { id: "C", text: "v17 React 才需要" },
      { id: "D", text: "Cloudflare 不支持回调" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "Web 版用属性 body.allReady，Node 版用回调 onShellReady/onAllReady。",
      detail: "类似 ReadableStream 的设计——你拿到对象后用属性/事件订阅生命周期，不是构造时传回调。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false",
    title: "Q13 单页 5 秒 abort 是否影响 client 跳转",
    prompt: "判断：SSR abort 后浏览器渲染失败，但用户在浏览器内点 NavLink 跳转到下一页（client-side navigation），这一页的 client-side fetch 不会受影响。",
    correctAnswer: { value: true },
    explanation: {
      short: "对——SSR abort 只影响首屏 HTML；hydration 完成后客户端跳转走的是 fetch，独立于 entry.server。",
      detail: "如果首屏 SSR 失败到完全无法 hydrate，那就影响了；但 React 18+ 流式 + RouteErrorBoundary 一般还能 hydrate 到部分 UI 让用户跳转。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q14 stream 与 cf cache",
    prompt: "Cloudflare CDN 缓存 SSR 流式响应吗？",
    options: [
      { id: "A", text: "可以缓存——CDN 等到完整 body 收齐才缓；缓存条件取决于 Cache-Control 头（loader 决定），跟它是不是流无关" },
      { id: "B", text: "流式响应永远不缓存" },
      { id: "C", text: "只有 Cache-Control: public 的才缓" },
      { id: "D", text: "依靠 ETag 决定" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "流式只是「源到边缘」的传输形式，缓存策略跟 Cache-Control 头走。",
      detail: "用户首次访问触发 Worker SSR 流式产出 → CDN 边收边转给用户，同时把 body 攒齐缓到 edge → 后续命中直接吐缓存（不再 SSR）。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts"],
  }),
  q({
    type: "position_judgement",
    title: "Q15 决策：renderToString 替换 stream",
    prompt: "提案：改用 renderToString(<RemixServer .../>)（同步），代码更简单。是否合理？",
    options: [
      { id: "A", text: "不合理——同步 renderToString 不支持 Suspense（遇到会 throw 而不是 fallback），项目里凡是用 Suspense lazy load 的组件都会爆；且 TTFB 退化为「等整个树渲染完」" },
      { id: "B", text: "合理，省一次 await" },
      { id: "C", text: "Cloudflare 不支持 renderToString" },
      { id: "D", text: "renderToString 性能更好" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "renderToString 不支持 Suspense；项目里 lazy import 全部会爆。",
      detail: "remix 项目用了 React.lazy + Suspense（root.tsx 的 LoginModal 等），切到 renderToString 就 boom。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice",
    title: "Q16 stream 与 hydration",
    prompt: "客户端 hydration 跟 stream 的关系？",
    options: [
      { id: "A", text: "无直接耦合——stream 把 HTML 吐到浏览器，浏览器解析 HTML 同时下载 client.js bundle，bundle 加载完后调 hydrateRoot 把 React 接管 DOM；React 18+ 支持「渐进 hydration」即流到一半就可以局部 hydrate" },
      { id: "B", text: "必须 stream 完才 hydrate" },
      { id: "C", text: "不能流式时 hydrate" },
      { id: "D", text: "hydration 不需要 stream" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "stream + 渐进 hydration 是 React 18+ 一起设计的两个能力。",
      detail: "用户感知：HTML 流式出现 + bundle 加载完后局部交互可点击——比传统 SSR 「整页等齐再交互」体验好。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/entry.client.tsx"],
  }),
  q({
    type: "code_fix",
    title: "Q17 漏 await",
    prompt: "改写为 const body = renderToReadableStream(...);（漏 await）。后果？",
    code: `const body = renderToReadableStream(\n  <RemixServer .../>,\n  { signal: AbortSignal.timeout(ABORT_DELAY), onError: ... }\n);`,
codeFixBaseline: `const body = renderToReadableStream(\n  <RemixServer .../>,\n  { signal: AbortSignal.timeout(ABORT_DELAY), onError: ... }\n);`,
correctAnswer: { patchedCode: "renderToReadableStream 在 Web 环境返回 Promise<ReadableStream>，漏 await 会让 body 变成 Promise 对象。new Response(body) 会把 Promise 当 body——浏览器拿到 [object Promise] 字符串。修复：补 const body = await renderToReadableStream(...);" },
explanation: { short: "见下方解释。", detail: "renderToReadableStream 在 Web 环境返回 Promise<ReadableStream>，漏 await 会让 body 变成 Promise 对象。new Response(body) 会把 Promise 当 body——浏览器拿到 [object Promise] 字符串。修复：补 const body = await renderToReadableStream(...);" },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "production-debugging",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q18 ABORT_DELAY 的级联",
    prompt: "ABORT_DELAY 同时给 RemixServer 的 abortDelay 和 AbortSignal.timeout，意图？",
    options: [
      { id: "A", text: "RemixServer abortDelay 控制「单个 Suspense 边界等多久 fallback」，AbortSignal.timeout 控制「整个 stream 多久 abort」；同值意味着「最多再等 5 秒就强制结束」，没有 stream 比 Suspense 宽松的可能" },
      { id: "B", text: "随便写，无关联" },
      { id: "C", text: "RemixServer 不支持 abortDelay" },
      { id: "D", text: "为了配 React 19" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "两层 timeout 协同工作，同值 = 不留缝隙。",
      detail: "如果 stream timeout > Suspense abortDelay，那么 Suspense 边界已经 fallback 了 stream 还在转，无意义但无害；反过来 stream timeout < Suspense abortDelay，Suspense 还没来得及 fallback 就被 abort。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice",
    title: "Q19 流式响应 Worker 时长",
    prompt: "用户路径下，Worker 在多久后能「释放」（处理下一个请求）？",
    options: [
      { id: "A", text: "Worker 在 return new Response(body, ...) 后立即可以接下一个请求；body 的实际数据传输由 Cloudflare 网络层接管，不占 Worker CPU" },
      { id: "B", text: "等 body 全部传完才释放" },
      { id: "C", text: "等 5 秒 ABORT_DELAY" },
      { id: "D", text: "下次冷启动" },
    ],
    correctAnswer: { choiceId: "A" },
    explanation: {
      short: "return Response 后 Worker 释放——这是 stream 的核心收益。",
      detail: "对比：renderToString 必须等整个 HTML 串出来 Worker 才能 return，期间一直占用 isolate；stream 让 Worker 早释放，处理更多请求。",
    },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false",
    title: "Q20 abort 后的 onError",
    prompt: "判断：AbortSignal 触发 abort，onError 一定会被调一次（带 AbortError）。",
    correctAnswer: { value: true },
    explanation: {
      short: "对——React 18+ 把 abort 当作渲染失败的一种，会通知 onError。",
      detail: "didError 会被翻 true，最终 status = 500——这是「超时即错误」的策略。",
    },
    abilityTags: ["bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
  q({
    type: "review_comment",
    title: "Q21 Review：分流 SSR 失败",
    prompt: "Reviewer 留言：「SSR 失败时返 500 太粗暴，建议返 200 + RouteErrorBoundary 内容，至少用户能看到错误页。」请评价。",
    correctAnswer: { comment: "评审混淆了两层。RouteErrorBoundary 是 React Router 提供的「子树渲染错被父级捕获」的机制——loader/render error 会被 boundary 包裹的子树捕获并渲染 fallback——这种情况下 didError 不会触发（boundary 已经处理完），最终 status 还是 200 + boundary HTML。didError 翻 true 的是「boundary 都救不回来」的根错误（比如 RemixServer 本身渲染崩了）；这种返 500 + 部分 HTML 是合理且必要的——不要用 200 掩盖。所以 reviewer 的建议针对的不是这层，他真正想要的应该是「再加一层全局 catch + 渲染 ErrorPage」，但这要重写 RemixServer，超出本文件职责。" },
explanation: { short: "见 review comment。", detail: "评审混淆了两层。RouteErrorBoundary 是 React Router 提供的「子树渲染错被父级捕获」的机制——loader/render error 会被 boundary 包裹的子树捕获并渲染 fallback——这种情况下 didError 不会触发（boundary 已经处理完），最终 status 还是 200 + boundary HTML。didError 翻 true 的是「boundary 都救不回来」的根错误（比如 RemixServer 本身渲染崩了）；这种返 500 + 部分 HTML 是合理且必要的——不要用 200 掩盖。所以 reviewer 的建议针对的不是这层，他真正想要的应该是「再加一层全局 catch + 渲染 ErrorPage」，但这要重写 RemixServer，超出本文件职责。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY,
    layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/components/error/RouteErrorBoundary.tsx"],
  }),
  q({
    type: "free_explain",
    title: "Q22 自由说明：流式 SSR 的两道护栏",
    prompt: "用一段话说明：handleRequest 给流式 SSR 加了「abortDelay + AbortSignal.timeout」两道护栏，分别防什么、为什么不能只留一个。",
    correctAnswer: { text: "(1) abortDelay（RemixServer prop）：单个 Suspense 边界等多久就 fallback——保证「慢的子树不阻塞父树渲染」 (2) AbortSignal.timeout（stream signal）：整个 renderToReadableStream 多久强制结束——保证「Worker 不会被某个无限等的子树拖死」 (3) 缺 abortDelay 后果：慢的 Suspense 没有 fallback 时机，父级也不能继续渲染，整个 SSR 卡死直到 stream timeout 强制 abort (4) 缺 AbortSignal.timeout 后果：所有 Suspense 都 fallback 了但 stream 内部某个状态还在等，Worker 占用 CPU/wall time 直到平台杀进程 (5) 结论：两道护栏分别防「子树死锁」和「整体死锁」，缺一不可" },
explanation: { short: "见详细要点。", detail: "(1) abortDelay（RemixServer prop）：单个 Suspense 边界等多久就 fallback——保证「慢的子树不阻塞父树渲染」 (2) AbortSignal.timeout（stream signal）：整个 renderToReadableStream 多久强制结束——保证「Worker 不会被某个无限等的子树拖死」 (3) 缺 abortDelay 后果：慢的 Suspense 没有 fallback 时机，父级也不能继续渲染，整个 SSR 卡死直到 stream timeout 强制 abort (4) 缺 AbortSignal.timeout 后果：所有 Suspense 都 fallback 了但 stream 内部某个状态还在等，Worker 占用 CPU/wall time 直到平台杀进程 (5) 结论：两道护栏分别防「子树死锁」和「整体死锁」，缺一不可" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY,
    layer: "free-response",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY],
  }),
];
