/**
 * Real questions for site-08-home-landing / home-capstone.
 * Anchor: 整合 _index.tsx + HomeHero + video-showcase + cyber-terminal + ClientOnly + ViewportLazySection 整体决策
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/_index.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const homeCapstoneQuestions: RealQ[] = [
  q({
    type: "position_judgement", title: "Q1 加「博客摘要」区段",
    prompt: "新增首页一个「最新博客 5 篇」区段。落点？",
    options: [
      sc("A", "1) 新建 components/home/blog-snippet.tsx 2) _index.tsx 顶部 lazy import 3) main 内插 ViewportLazySection + Suspense 包装 4) loader 内并发 await getBlogList(5) 加进 return 对象 5) 组件 props 拿 useLoaderData 给的数据"),
      sc("B", "改 root"),
      sc("C", "新路由"),
      sc("D", "wrangler 配置"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "首页扩区段 = 新组件 + lazy + viewport + loader 并发——五处统一改。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/components/home/blog-snippet.tsx"],
  }),
  q({
    type: "position_judgement", title: "Q2 加首屏全屏视频",
    prompt: "想把 HomeHero 改成全屏视频背景。落点？",
    options: [
      sc("A", "改 HomeHero.tsx 内 JSX 加 <video autoPlay muted playsInline poster={POSTER} src={ossUrl('hero.mp4')} />；reduce motion 用户用静态 poster；preload 配合"),
      sc("B", "新建组件 HomeVideoHero"),
      sc("C", "改 _index.tsx"),
      sc("D", "改 root"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Hero 区改 video = 改 HomeHero 内部，不动其他文件；保持外层 lazy + viewport 范式。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: "app/components/home/HomeHero.tsx", layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: ["app/components/home/HomeHero.tsx"],
  }),
  q({
    type: "single_choice", title: "Q3 ClientOnly vs ViewportLazySection",
    prompt: "BubbleMessageBoard 用 ClientOnly + ViewportLazySection 双层包；CyberTerminal 用 ViewportLazySection 单层——区别？",
    options: [
      sc("A", "BubbleMessageBoard.client.tsx 是 .client 后缀（不能 SSR），ClientOnly 必要；CyberTerminal 是 shared 文件能 SSR，只需 viewport 控制挂载时机；按文件性质选包装"),
      sc("B", "随机"),
      sc("C", "纯习惯"),
      sc("D", "TypeScript 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ClientOnly 用于 .client 文件；ViewportLazySection 用于按需挂载——按文件类型选。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY, "app/components/messages/BubbleMessageBoard.client.tsx", "app/components/home/cyber-terminal.tsx"],
  }),
  q({
    type: "single_choice", title: "Q4 SSR 输出与 hydrate",
    prompt: "首页 SSR HTML 包含哪些区段的真实内容？",
    options: [
      sc("A", "Header / HomeHero（默认 zh 文字、无动画）/ Faq / footer（CreativeFooter）/ JSON-LD —— 这些都是非 lazy 组件；5 个 lazy 区段（TabShowcase 等）SSR 时输出 fallback skeleton；hydrate + 视口触发后才下 chunk 真渲染"),
      sc("B", "全部"),
      sc("C", "全空"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "lazy 区段 SSR 出 skeleton + CSR 渲真——双阶段渐进式。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 首屏性能指标",
    prompt: "首页主要影响哪些 Core Web Vitals 指标？",
    options: [
      sc("A", "LCP（最大内容绘制，HomeHero 大字 + 字体 preload 优化）；CLS（累积布局偏移，pulseFallback skeleton 尺寸接近真组件）；INP（交互响应，scroll listener rAF 节流）"),
      sc("B", "都不影响"),
      sc("C", "永远满分"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "首页是 SEO/Web Vitals 主要衡量页——多处优化对应不同指标。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 ChangelogSection",
    prompt: "<ChangelogSection /> 直接在 _index.tsx 渲染（不 lazy）——意图？",
    options: [
      sc("A", "ChangelogSection 体积小（只是展示 updates 数组前 4 项），不值得拆 chunk；与 Faq、CreativeFooter 一起在首屏 main bundle，立即可见"),
      sc("B", "TypeScript 限制"),
      sc("C", "随机"),
      sc("D", "Cloudflare 强制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "lazy 不是越多越好——小组件直接 import 反而省 chunk 切分开销。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/home/changelog-section.tsx"],
  }),
  q({
    type: "single_choice", title: "Q7 共享 loader 数据",
    prompt: "currentUser 在 _index 路由 loader 拿到，传给 BubbleMessageBoard 给登录用户显示「我的待审核留言」——这种？",
    options: [
      sc("A", "loader → useLoaderData → props 单向数据流；登录态信息在路由层判断，业务组件只渲染；干净的「数据从顶部下流」模式"),
      sc("B", "全局 store"),
      sc("C", "Cloudflare 决定"),
      sc("D", "TypeScript 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader → props 单向流——React 数据流首选；避免无关组件订阅 store。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 footer-curtain 揭示效果",
    prompt: "<div className='ui-footer-curtain'> 外层 + ui-footer-curtain-stage / ui-footer-reveal 双子层——意图？",
    options: [
      sc("A", "「幕布揭示 footer」效果——stage 主内容浮在前，sticky position；reveal 在 stage 后，滚到底时 stage 滑出 reveal（footer）显现；纯 CSS sticky/transform 实现"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "幕布揭示 footer 是项目特色 UI——纯 CSS 完成不需要 JS 副作用。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/components/home/creative-footer.tsx"],
  }),
  q({
    type: "branch_trace", title: "Q9 首次访问完整流",
    prompt: "首次匿名用户访问 https://wangjiajun.asia/ 完整渲染步骤？",
    options: [
      sc("s1", "1. CDN 看 cache hit/miss；miss 转给 Worker"),
      sc("s2", "2. Worker 跑 _index.tsx loader，cookie 早判断 → 跳过 session，只查 messages"),
      sc("s3", "3. loader return json + Cache-Control: public 60s s-maxage 300 SWR 600"),
      sc("s4", "4. SSR 渲染：Header + HomeHero（默认 zh 静态字）+ main 5 个 fallback skeleton + Faq + footer + JSON-LD"),
      sc("s5", "5. 流式输出 HTML，CDN 边缘缓存 5 分钟"),
      sc("s6", "6. 浏览器收到，<link rel='preload' as='font'> 立即下字体；<link rel='stylesheet'> 下 CSS"),
      sc("s7", "7. JS bundle 下完，hydrate 接管；GSAP 异步下完后 HomeHero 字飞入"),
      sc("s8", "8. 用户滚到 below-the-fold，IntersectionObserver 触发 ViewportLazySection 挂；Suspense 等 lazy chunk 下完渲染真组件"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8"] },
    explanation: { short: "CDN → Worker → SSR → 流式 → hydrate → 视口惰性——首页完整渲染链。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 第二次访问加速",
    prompt: "用户在 5 分钟内第二次访问 / —— Worker 是否被触发？",
    options: [
      sc("A", "不触发——CDN 边缘缓存命中，直接返之前的 HTML；除非用户带 auth cookie 触发 Vary 重查；省 Worker invocation"),
      sc("B", "永远触发"),
      sc("C", "随机"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "CDN 命中 = Worker 0 调用——免费层流量大头省钱。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 移除 lazy 后果",
    prompt: "如果把 5 个 lazy import 改成顶部直接 import——首页表现？",
    options: [
      sc("A", "首屏 main bundle 体积大幅增加（GSAP 间接被 HomeHero 链拉、video 库、syntax-highlight 等都进来）；首屏 LCP/INP 恶化；用户没进 below-the-fold 就下了所有"),
      sc("B", "无影响"),
      sc("C", "更快"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "lazy 是首屏关键——拆 chunk 让首屏只下必要 JS。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q12 lazy import 必须 default export",
    prompt: "判断：lazy(() => import('~/components/home/x')) 要求 x.tsx 必须 export default。",
    correctAnswer: { value: true },
    explanation: { short: "对——React.lazy 默认拿 module.default；如要拿命名 export 用 .then(m => ({ default: m.X }))。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 错误隔离",
    prompt: "如果 CyberTerminal lazy chunk 加载失败——整个首页崩吗？",
    options: [
      sc("A", "不崩——Suspense 内部错误冒泡到最近 ErrorBoundary（root），但只影响 Suspense 内的子树；其他区段（HomeHero / 其他 lazy）正常显示。可加路由级 ErrorBoundary 捕住更精细"),
      sc("B", "全崩"),
      sc("C", "白屏"),
      sc("D", "Cloudflare 接管"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Suspense + ErrorBoundary 隔离区段错误——单点失败不影响全局。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 main vs Suspense 包装层级",
    prompt: "<main><ViewportLazySection><Suspense><X /></Suspense></ViewportLazySection></main>——三层包装重复吗？",
    options: [
      sc("A", "不重复——main 是 ARIA landmark；ViewportLazySection 控视口挂载；Suspense 等 chunk；各自独立职责，叠加才完整"),
      sc("B", "重复 + 性能差"),
      sc("C", "TypeScript 要求"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三层各司其职——可访问性 + 视口 + chunk。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 改字体 preload",
    prompt: "想给首页加一种新字体（如 Noto Sans CJK），落点？",
    options: [
      sc("A", "1) 加字体文件到 public/fonts/ 2) lib/font-preloads.ts 加 helper 返回 hrefs 3) _index.tsx 的 links 函数 spread 这些 href 进 preload 数组 4) CSS 写 @font-face 用同 URL——构建时已被预加载"),
      sc("B", "改 root"),
      sc("C", "改 entry.server"),
      sc("D", "wrangler 配置"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "字体 preload 跨四步——文件 + helper + links + @font-face。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/lib/font-preloads.ts"],
  }),
  q({
    type: "single_choice", title: "Q16 SEO 评估",
    prompt: "首页 SEO 关键元素？",
    options: [
      sc("A", "1) <title> 来自 meta 函数（pageMeta.home()） 2) JSON-LD Person 给搜索引擎理解人物身份 3) <main>/<section>/<h1>语义结构 4) HomeHero 的真实文字（SSR 输出 SEO 可见） 5) <link rel='preload'> 字体加快渲染减少 CLS——综合提升搜索排名"),
      sc("B", "只 title"),
      sc("C", "只 JSON-LD"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SEO 是综合工程——title + 结构化数据 + 语义 HTML + 性能。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 reduce motion 全站统一",
    prompt: "HomeHero / RouteTransition 都做了 reduce-motion 处理；其他动画组件呢？",
    options: [
      sc("A", "应该统一——目前 NotFound404 龙动画没处理是漏点；项目可建一个 useReducedMotion() hook 集中检测并所有组件接入"),
      sc("B", "已统一"),
      sc("C", "不需要"),
      sc("D", "Cloudflare 自动"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "可访问性应统一——目前是渐进改进点。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/error/NotFound404.tsx"],
  }),
  q({
    type: "single_choice", title: "Q18 测首页性能",
    prompt: "怎么本地测首页性能？",
    options: [
      sc("A", "1) Chrome DevTools Lighthouse 跑 mobile + slow 4G 2) Network 看 main bundle 体积 3) Coverage 看未用 JS / CSS 4) Performance 录制看 LCP/CLS/INP；线上后用 Cloudflare Analytics + Web Vitals"),
      sc("B", "只看错误"),
      sc("C", "用户反馈"),
      sc("D", "Cloudflare 自动"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Lighthouse + DevTools 全套——首页性能调优工具链。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 加 i18n",
    prompt: "想给首页加完整 i18n（按 URL /en/、/ja/）。落点？",
    options: [
      sc("A", "新建动态段 $lang.tsx 作 layout，loader 读 params.lang 决定语言；现有 / 改成默认 zh；HomeHero 现有 activeKey 仍局部切，但 server 端从 lang 读初值；触动 root + _index + 新 layout 三层"),
      sc("B", "改一行"),
      sc("C", "wrangler 配置"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "完整 i18n 是大工程——URL 段 + loader + 组件多层级改造。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 measure & monitor",
    prompt: "线上首页性能怎么持续监控？",
    options: [
      sc("A", "1) Cloudflare Analytics（pageviews + 错误） 2) Web Vitals（LCP/CLS/INP 真实用户数据） 3) Real User Monitoring（如 Sentry Performance）；定期对比 deploy 前后；性能下降时 git bisect"),
      sc("B", "只看 logs"),
      sc("C", "用户反馈"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "RUM + Vitals + 错误监控——线上持续可见性。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 数据流总览",
    prompt: "首页数据流总览？",
    options: [
      sc("A", "request → cookie 早判断 → loader 并发查 D1 → return json + Cache-Control → entry.server SSR → React 渲染（lazy 出 skeleton）→ 流式 HTML → CDN 缓存 → hydrate → useEffect 启 GSAP / scroll listener → IntersectionObserver 触发 lazy chunk 下载 → Suspense 渲真组件"),
      sc("B", "纯客户端"),
      sc("C", "纯 SSR"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "数据流贯穿 server + CDN + client——全栈协作。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 整体设计",
    prompt: "首页整体设计哲学？",
    options: [
      sc("A", "1) 路由薄、组件厚 2) lazy 拆 below-the-fold chunk 3) ViewportLazySection + Suspense 双层惰性 4) ClientOnly 隔离 .client 文件 5) loader 并发 + 按身份切缓存 6) Cache-Control 透回 document（forwardLoaderCacheControl） 7) HomeHero 用 reduce motion + GSAP context 优雅动画 8) JSON-LD + 字体 preload + sticky footer——综合：性能 + SEO + 可访问性 + UX 多维平衡"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare 强制"),
      sc("D", "TypeScript 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "八条原则——首页是项目工程实践的集大成。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/components/home/HomeHero.tsx", "app/components/common/ClientOnly.tsx", "app/lib/cache-headers.server.ts"],
  }),
];
