/**
 * Real questions for site-08-home-landing / home-video.
 * Anchor: remix/app/components/home/video-showcase.tsx —— 4 useState + 2 useRef + drag + isMobile resize
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/home/video-showcase.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const homeVideoQuestions: RealQ[] = [
  q({
    type: "single_choice", title: "Q1 4 个 useState",
    prompt: "isDragging / position / dragStart / isMobile 4 个 state——分工？",
    options: [
      sc("A", "isDragging：是否拖拽中；position：当前视频窗位置 {x,y}；dragStart：拖拽起点（mouse 与 window 的偏移）；isMobile：屏 < 1024px 时禁用拖拽——4 个 state 分别管不同维度"),
      sc("B", "全等"),
      sc("C", "无意义"),
      sc("D", "TypeScript 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "拖拽组件标准 state 拆分——一个动作多个独立维度。" },
    abilityTags: ["frontend.state.local"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 isMobile resize 监听",
    prompt: "useEffect 内 const checkMobile = () => setIsMobile(window.innerWidth < 1024); window.addEventListener('resize', checkMobile); 这个 effect 设计？",
    options: [
      sc("A", "初始 + 每次窗口 resize 时重新判断「是否手机宽度」；移动端禁用拖拽（手机直接看视频，不模拟桌面交互）；cleanup remove listener 防泄漏"),
      sc("B", "性能"),
      sc("C", "纯样式"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "resize listener + cleanup——响应式判断的标准 React 模式。" },
    abilityTags: ["frontend.effect.useEffect", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank", title: "Q3 mobile 阈值",
    prompt: "setIsMobile(window.innerWidth < ____ );",
    options: [],
    blanks: [{ id: "v", placeholder: "数字", acceptedAnswers: ["1024"] }],
    correctAnswer: { type: "fill_blank", values: { v: "1024" } },
    explanation: { short: "1024px 是 lg breakpoint；与 Tailwind lg: 一致。" },
    abilityTags: ["frontend.event.click"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 dragStart 计算",
    prompt: "setDragStart({ x: e.clientX - position.x, y: e.clientY - position.y }); 减 position 的意图？",
    options: [
      sc("A", "记录「鼠标与窗体左上角的偏移」——后续 mousemove 时 position = e.clientX - dragStart.x 还原成窗体新位置；保证拖拽中鼠标始终对准最初按下的位置而非窗体角"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "dragStart 是「相对偏移」，不是「绝对起点」——拖拽体验关键。" },
    abilityTags: ["frontend.event.click", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 isMobile 拒拖",
    prompt: "handleMouseDown 内 if (isMobile) return; ——意图？",
    options: [
      sc("A", "手机端跳过拖拽逻辑——手机用户用 touch 滚动，不需要桌面拖窗体效果；省 setState + 防止 layout 错位"),
      sc("B", "性能"),
      sc("C", "Cloudflare 限制"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "设备能力差异化——手机不模拟桌面交互。" },
    abilityTags: ["frontend.event.click"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 video poster",
    prompt: "const VIDEO_POSTER = resolveImage('asset_cc24ca'); 这个 poster 用途？",
    options: [
      sc("A", "<video poster={VIDEO_POSTER} /> 视频未播放时显示的封面图——视频 src 加载慢时给用户视觉占位；resolveImage 把 hash key 解析成 CDN 完整 URL"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "video poster = 加载占位封面——首屏视觉关键。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/lib/resolve-image.ts"],
  }),
  q({
    type: "single_choice", title: "Q7 ossUrl",
    prompt: "const YOTEI_VIDEO_SRC = ossUrl('yotei.mp4'); ossUrl 是？",
    options: [
      sc("A", "返回阿里云 OSS 上的 yotei.mp4 完整 URL（通过 IMAGE_BASE_URL 或类似 env 拼）；视频文件大不放 R2 而走 OSS 是项目的存储分层选择"),
      sc("B", "本地文件"),
      sc("C", "Cloudflare R2"),
      sc("D", "硬编码"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "媒体分层存储——大视频走 OSS，小图标走 R2 + CDN。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/lib/media-cdn.ts"],
  }),
  q({
    type: "single_choice", title: "Q8 lazy 在 _index.tsx",
    prompt: "VideoShowcase 在 _index.tsx 里被 lazy(() => import('~/components/home/video-showcase')) 引用——意图？",
    options: [
      sc("A", "代码分割——VideoShowcase 是 below-the-fold 区段，首屏不需要；用 lazy 让它单独成 chunk，滚到时再下；同时降低首屏 main bundle 体积"),
      sc("B", "TypeScript"),
      sc("C", "Cloudflare 限制"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "lazy import = chunk 分割——首页性能关键。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: "app/routes/_index.tsx", layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/routes/_index.tsx"],
  }),
  q({
    type: "single_choice", title: "Q9 视频自带 .client 吗",
    prompt: "video-showcase.tsx 文件名没 .client 后缀——为什么仍能用 useState/useRef？",
    options: [
      sc("A", "组件可以双端跑：SSR 时 useState 给初始值（isDragging=false 等），不调 window 就不会出错；resize listener 在 useEffect 内只 client 跑——文件本身是「shared」"),
      sc("B", "Remix 自动处理"),
      sc("C", "TypeScript"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "文件 shared = SSR 友好；浏览器 API 在 useEffect 内 client-only 执行。" },
    abilityTags: ["bridge.reactRouter.loader", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q10 SSR 输出 video 标签",
    prompt: "判断：SSR 时 VideoShowcase 输出 <video src={YOTEI_VIDEO_SRC} poster={VIDEO_POSTER} /> 的 HTML。",
    correctAnswer: { value: true },
    explanation: { short: "对——video 标签是 React 输出的标准 HTML 节点；浏览器收到立即开始预加载封面图，提升首屏。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 拖拽事件三件套",
    prompt: "handleMouseDown / handleMouseMove / handleMouseUp 三件套——挂在哪里？",
    options: [
      sc("A", "都挂在 windowRef 元素上：onMouseDown / onMouseMove / onMouseUp——只有窗口区域触发拖拽，不影响外部点击；缺点：鼠标快移出窗口时 mouseup 可能丢失（卡在 dragging 状态）"),
      sc("B", "全局 document"),
      sc("C", "随机"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "组件级 listener——简单但有边界丢失风险；进阶可改用 pointercapture。" },
    abilityTags: ["frontend.event.click"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 position 应用",
    prompt: "<div style={{ transform: `translate(${position.x}px, ${position.y}px)` }}>—— transform translate 而非 left/top 的好处？",
    options: [
      sc("A", "transform 走 GPU 合成层，不触发 layout/paint；left/top 触发 layout，性能差；高频拖拽用 transform 是性能基本功"),
      sc("B", "纯习惯"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "transform 是 GPU 加速属性——拖拽/动画首选。" },
    abilityTags: ["ai.review.architecture", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 onMouseLeave",
    prompt: "拖拽过程中鼠标移出窗口——是否应该停止拖拽？",
    options: [
      sc("A", "应该 onMouseLeave={handleMouseUp}——避免鼠标在窗外松开后回来仍处 dragging 状态；当前代码没做这处理是潜在改进点"),
      sc("B", "永远不停"),
      sc("C", "无关"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "onMouseLeave 兜底——边界丢失防护。" },
    abilityTags: ["frontend.event.click", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q14 用户拖动视频窗",
    prompt: "用户在桌面端拖拽视频窗步骤？",
    options: [
      sc("s1", "1. mouseDown 触发 → if (isMobile) return（false 跳过）"),
      sc("s2", "2. setIsDragging(true)、setDragStart 记偏移"),
      sc("s3", "3. mouseMove 触发 → if (!isDragging) return；else setPosition"),
      sc("s4", "4. setPosition 引发组件重渲染，transform translate 生效"),
      sc("s5", "5. 用户松开 mouseUp → setIsDragging(false)"),
      sc("s6", "6. 后续 mouseMove 因 isDragging=false 不再 setState"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6"] },
    explanation: { short: "拖拽状态机：down 开始 → move 跟随 → up 结束。" },
    abilityTags: ["frontend.state.local", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 setState 频繁拖拽性能",
    prompt: "mouseMove 每帧 setPosition 引发 React 重渲染——性能担心？",
    options: [
      sc("A", "可接受——React 18+ 自动 batch + 浏览器 60fps 限制；transform translate 走 GPU 不阻塞主线程；拖拽流畅；如果出问题可用 useRef 直接改 DOM 不走 state"),
      sc("B", "永远卡顿"),
      sc("C", "性能极差"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "现代 React + GPU transform 拖拽够流畅；高级优化用 ref 直接改 DOM 跳过 React。" },
    abilityTags: ["ai.review.architecture", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 移动端怎么交互",
    prompt: "移动端 (isMobile=true) 用户怎么看视频？",
    options: [
      sc("A", "禁用拖拽，窗体居中固定显示视频；用户用浏览器原生触摸滚动页面浏览；视频本身可点击播放"),
      sc("B", "不能看"),
      sc("C", "弹出 modal"),
      sc("D", "重定向"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "移动端简化交互——拖拽是桌面专属增强。" },
    abilityTags: ["frontend.event.click"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q17 Suspense 包它",
    prompt: "判断：_index.tsx 内 <Suspense fallback={pulseFallback(...)}><VideoShowcase /></Suspense>——必要。",
    correctAnswer: { value: true },
    explanation: { short: "对——VideoShowcase 是 lazy 组件，下载 chunk 时没渲染；Suspense 给 fallback skeleton；缺了 React 报错。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: "app/routes/_index.tsx", layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/routes/_index.tsx"],
  }),
  q({
    type: "single_choice", title: "Q18 视频懒加载",
    prompt: "<video preload='metadata' />——意图？",
    options: [
      sc("A", "preload='metadata' 让浏览器只下视频元数据（时长 / 尺寸）不下完整 buffer；用户点播放才真下；首屏带宽友好"),
      sc("B", "全下"),
      sc("C", "永不下"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "preload metadata 平衡 UX 和带宽——视频组件标准做法。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 ViewportLazySection 与 lazy 区别",
    prompt: "_index.tsx 中 <ViewportLazySection><Suspense><VideoShowcase /></Suspense></ViewportLazySection>——viewport 比 lazy 多做什么？",
    options: [
      sc("A", "lazy 是「JS chunk 按需下」；ViewportLazySection 是「DOM 节点按需挂载」——元素进视口才创建组件实例；先 viewport gate 再 lazy chunk，双层惰性"),
      sc("B", "重复"),
      sc("C", "无差别"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "viewport 控时机 + lazy 控代码体积——两层独立优化。" },
    abilityTags: ["ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: "app/routes/_index.tsx", layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/routes/_index.tsx"],
  }),
  q({
    type: "single_choice", title: "Q20 cleanup remove listener",
    prompt: "useEffect return () => window.removeEventListener('resize', checkMobile); 必要吗？",
    options: [
      sc("A", "必要——组件卸载时不 remove，window 仍持引用，组件无法被 GC（内存泄漏）；React 严格模式下可重复 mount/unmount，不 cleanup 会重复绑定多个 listener"),
      sc("B", "无所谓"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "addEventListener 必须配 removeEventListener——React 副作用清理铁律。" },
    abilityTags: ["frontend.effect.useEffect"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 GsapFillLink 在视频区",
    prompt: "VideoShowcase 内 <GsapFillLink to=...>——为什么用项目封装而非原生 Link？",
    options: [
      sc("A", "GsapFillLink 包了 Link + GSAP hover 填充动画——保留 React Router 客户端导航 + 加视觉细节；项目里大量 Link 都用它，统一交互"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "封装组件统一交互——可视风格全站一致。" },
    abilityTags: ["frontend.event.click", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/ui/GsapFillLink.tsx"],
  }),
  q({
    type: "single_choice", title: "Q22 整体视频区设计",
    prompt: "VideoShowcase 整体设计哲学？",
    options: [
      sc("A", "1) 大视频走 OSS（成本/体积考虑） 2) preload metadata + poster 平衡 UX/带宽 3) lazy + Suspense 减首屏 chunk 4) ViewportLazySection 进视口才挂 5) isMobile resize 监听差异化交互 6) 拖拽用 transform/GPU 7) cleanup 防泄漏——综合：性能 + 设备适配 + 健壮"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare 强制"),
      sc("D", "TypeScript 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "七条原则——视频组件的工程实践集合。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY, "app/routes/_index.tsx", "app/lib/media-cdn.ts"],
  }),
];
