/**
 * Real questions for site-08-home-landing / home-hero.
 * Anchor: remix/app/components/home/HomeHero.tsx —— useRef×3 + useState×2 + 3 个 useEffect + 动态 GSAP import + reduce motion + raf
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/home/HomeHero.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const homeHeroQuestions: RealQ[] = [
  q({
    type: "single_choice", title: "Q1 三个 useRef",
    prompt: "useRef<HTMLElement>(null) 三个：rootRef / textRef / mountedRef——分别作用？",
    options: [
      sc("A", "rootRef 拿外层 DOM 给 GSAP context；textRef 拿语言切换的文本块；mountedRef 是「初始动画是否跑过」的旗标，避免语言切换时重跑入场动画"),
      sc("B", "都一样"),
      sc("C", "只有 rootRef 有用"),
      sc("D", "TypeScript 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三 ref 各司其职——DOM 引用 + 状态旗标的常见模式。" },
    abilityTags: ["frontend.state.local", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 useState activeKey",
    prompt: "const [activeKey, setActiveKey] = useState<HeroLocaleKey>('zh'); 作用？",
    options: [
      sc("A", "当前语言（zh/en/ja 等）的 state——切换时 useMemo 重新算 activeLocale，第二个 useEffect 监听它重跑文字动画"),
      sc("B", "纯样式"),
      sc("C", "loader 数据"),
      sc("D", "全局"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "activeKey 是「当前选中语言」——驱动 UI 和动画双重切换。" },
    abilityTags: ["frontend.state.local"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 useMemo 派生 activeLocale",
    prompt: "const activeLocale = useMemo(() => homeHeroLocales.find(l => l.key === activeKey) ?? homeHeroLocales[0], [activeKey]); 这步意图？",
    options: [
      sc("A", "派生值缓存——只有 activeKey 变了才重新 find；?? 兜底防 find 返 undefined；典型「state → 派生数据」模式"),
      sc("B", "性能要求"),
      sc("C", "TypeScript 限制"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useMemo 缓存 find 结果——dep 变才重算。" },
    abilityTags: ["frontend.state.local", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 prefers-reduced-motion 检测",
    prompt: "const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches; if (reduceMotion) { mountedRef.current = true; return; } 这段做什么？",
    options: [
      sc("A", "用户开了系统「减少动效」时直接跳过 GSAP 入场动画——但仍把 mountedRef 标记 true 让后续语言切换知道「已就绪不需要重跑入场」；可访问性优先"),
      sc("B", "性能优化"),
      sc("C", "TypeScript 强制"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "尊重 reduce 偏好 + 维持状态机一致性——可访问性 + 健壮性双重考虑。" },
    abilityTags: ["ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 动态 import('gsap')",
    prompt: "void import('gsap').then(({ gsap }) => { ... }); 动态 import 而非顶部 import——意图？",
    options: [
      sc("A", "GSAP 体积大（~70KB），动态 import 让它单独拆 chunk，不混进首屏 main bundle；reduce motion 用户根本不下；副作用：必须在 useEffect 内（确保 client）"),
      sc("B", "TypeScript 要求"),
      sc("C", "纯习惯"),
      sc("D", "Cloudflare 强制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "动态 import 拆 chunk + 按需下——首屏 JS 优化关键。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 void 前缀",
    prompt: "void import('gsap').then(...) 中 void 前缀作用？",
    options: [
      sc("A", "显式丢弃 Promise 返回值——告诉 ESLint「我不打算 await/catch 这个」；不影响运行时；本身有 .catch 链兜底，所以不要 await"),
      sc("B", "性能优化"),
      sc("C", "TypeScript 要求"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "void Promise = 「故意 fire-and-forget」——绕开 ESLint no-floating-promises。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 cancelled 闭包变量",
    prompt: "let cancelled = false; ... if (cancelled) return; ... return () => { cancelled = true; ctx?.revert(); }; 这种模式？",
    options: [
      sc("A", "「effect 取消」模式——卸载时 cancelled = true 让正在等的 import().then() 知道组件已卸载，不要再操作 DOM；与 ctx?.revert() 配合双保险"),
      sc("B", "性能优化"),
      sc("C", "纯写法"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "异步 effect 卸载防回调——闭包变量 + cleanup 是 React 标准。" },
    abilityTags: ["frontend.effect.useEffect"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 gsap.context",
    prompt: "ctx = gsap.context(() => { ... }, root); 用 gsap.context 包裹的好处？",
    options: [
      sc("A", "GSAP context API——把 selector 作用域绑到 root 元素（context-aware selector），动画自动用 root.querySelectorAll；ctx.revert() 一键回滚所有动画副作用"),
      sc("B", "纯样式"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "gsap.context = 作用域 + 一键 revert——React 用 GSAP 推荐范式。" },
    abilityTags: ["frontend.effect.useEffect"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank", title: "Q9 入场动画第一步",
    prompt: 'gsap.fromTo(".hero-gsap-char", { yPercent: ____, rotateX: 58, rotateZ: 2, opacity: 0, filter: "blur(10px)" }, ...)',
    options: [],
    blanks: [{ id: "v", placeholder: "数字", acceptedAnswers: ["80"] }],
    correctAnswer: { type: "fill_blank", values: { v: "80" } },
    explanation: { short: "yPercent: 80 = 起点位置在最终位置下方 80%；模拟「字符从下飞起」的效果。" },
    abilityTags: ["frontend.effect.useEffect"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 stagger",
    prompt: "stagger: 0.045 含义？",
    options: [
      sc("A", "每个 .hero-gsap-char 间隔 45ms 启动——视觉上看到字符一个个飞起而非整体；stagger 是 GSAP 实现「错峰动画」的关键参数"),
      sc("B", "总时长"),
      sc("C", "随机"),
      sc("D", "TypeScript 类型"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "stagger 让多元素动画呈波浪推进——节奏感关键。" },
    abilityTags: ["frontend.effect.useEffect"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 第二个 useEffect 依赖 [activeKey]",
    prompt: "useEffect(() => { ... }, [activeKey]); 第二个 effect 在什么时候跑？",
    options: [
      sc("A", "activeKey 变化时（用户切语言）——重新跑一次更短更轻的入场动画给新语言文字；初次 mount 也跑一次（activeKey 默认 'zh'，但 mountedRef 检查阻止），避免和第一个 effect 重复"),
      sc("B", "永远跑"),
      sc("C", "永不跑"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "第二个 effect 是「语言切换动画」——通过 mountedRef 守卫避免初次重复。" },
    abilityTags: ["frontend.effect.useEffect"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 mountedRef 守卫",
    prompt: "if (!root || !mountedRef.current) return; 这个守卫意图？",
    options: [
      sc("A", "如果初始 GSAP 还没载完（mountedRef 还是 false），不要跑这个语言切换动画——避免和初始入场动画打架；等初始完成后才允许语言切换动画"),
      sc("B", "性能优化"),
      sc("C", "随机"),
      sc("D", "TypeScript 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "mountedRef 是「入场动画完成」的握手——保证语言切换不抢资源。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 第三个 useEffect 滚动监听",
    prompt: "useEffect(() => { let rafId = 0; const updateNoticeTone = () => {...}; const scheduleUpdate = () => {...} }, []) 这个 effect 做什么？",
    options: [
      sc("A", "监听滚动，根据 hero 的 rect.top 判断「是否滚出视口足够远」决定 noticeEmphasized；用 requestAnimationFrame 节流避免每帧调用 setState 引发性能问题"),
      sc("B", "纯样式"),
      sc("C", "随机"),
      sc("D", "TypeScript 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "rAF 节流的 scroll 监听——经典性能优化模式。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank", title: "Q14 noticeEmphasized 阈值",
    prompt: "const threshold = Math.min(220, window.innerHeight * ____ );",
    options: [],
    blanks: [{ id: "v", placeholder: "小数", acceptedAnswers: ["0.24"] }],
    correctAnswer: { type: "fill_blank", values: { v: "0.24" } },
    explanation: { short: "0.24 = 视口高度 24%——大屏 PC 用 220 上限，小屏手机用动态值，自适应阈值。" },
    abilityTags: ["frontend.effect.useEffect"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q15 用户切英文",
    prompt: "用户从 zh 点切到 en 步骤？",
    options: [
      sc("s1", "1. 用户点击语言按钮 → setActiveKey('en')"),
      sc("s2", "2. activeKey state 变 'en'"),
      sc("s3", "3. useMemo 重算 activeLocale = homeHeroLocales.find(l => l.key === 'en')"),
      sc("s4", "4. 第二个 useEffect dep 变化触发"),
      sc("s5", "5. mountedRef.current === true（初始入场已完），不被守卫挡"),
      sc("s6", "6. 检查 reduce motion，不命中 → 跑短版 GSAP 入场动画"),
      sc("s7", "7. 卸载 cleanup ctx?.revert() 回滚"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7"] },
    explanation: { short: "state → memo → effect → 动画——React 数据流标准链。" },
    abilityTags: ["frontend.state.local", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q16 SSR 渲染 HomeHero",
    prompt: "判断：HomeHero 在 SSR 阶段会跑 useEffect。",
    correctAnswer: { value: false },
    explanation: { short: "错——useEffect 只在客户端 hydrate 后跑；SSR 只跑组件函数 + JSX，输出初始 HTML（静态文字）。" },
    abilityTags: ["frontend.effect.useEffect", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 SSR 输出 hero",
    prompt: "SSR 时 HomeHero 输出 HTML 是？",
    options: [
      sc("A", "默认 zh 语言版的静态 JSX——所有 .hero-gsap-char 已渲染但没有动画样式（GSAP 是 client-only）；hydrate 后 useEffect 启动 GSAP 把它们「飞」入场"),
      sc("B", "空白"),
      sc("C", "skeleton"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SSR 给静态结构 + CSR 加入场动画——SEO 友好。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 import.meta.env.SSR",
    prompt: "如果 useEffect 内调 window.matchMedia 没守卫——SSR 会怎样？",
    options: [
      sc("A", "不会出错——useEffect 不在 SSR 跑；如果直接在组件函数体内调 window.matchMedia 才会 SSR 报 ReferenceError；这是 React 的天然 client/server 隔离"),
      sc("B", "永远报错"),
      sc("C", "随机"),
      sc("D", "Cloudflare 拦截"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useEffect 是「只在 client」的护城河——所以 GSAP / matchMedia 都安全用。" },
    abilityTags: ["frontend.effect.useEffect", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 GSAP catch 兜底",
    prompt: ".catch((error) => { console.error('[HomeHero] Failed to load GSAP', error); mountedRef.current = true; }); 这步意图？",
    options: [
      sc("A", "GSAP 模块下载失败时也把 mountedRef 标 true——让后续语言切换不会因为 mountedRef 永远 false 卡死；优雅降级：动画没了，但功能仍可用"),
      sc("B", "性能"),
      sc("C", "TypeScript 强制"),
      sc("D", "纯日志"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "失败也维持状态机一致性——「降级不破坏」原则。" },
    abilityTags: ["ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 noticeEmphasized 用途",
    prompt: "noticeEmphasized state 通常用于？",
    options: [
      sc("A", "JSX 内根据它切换某个「通知/提示」的样式（更显眼/更淡）；滚动时 hero 滚出视口越多 → noticeEmphasized=true → 提示更醒目"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "scroll-driven UI——根据滚动位置切换视觉强调。" },
    abilityTags: ["frontend.state.local"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 cleanup 双层 ctx?.revert()",
    prompt: "三个 useEffect 都 return cleanup 调 ctx?.revert()——对比手动 gsap.killTweensOf？",
    options: [
      sc("A", "ctx.revert() 是 gsap.context API 提供的「一键回滚」——回滚动画 + 移除 selector 内所有副作用；vs 手动 killTweensOf 每个 selector 单独 kill 易遗漏"),
      sc("B", "性能差"),
      sc("C", "无差别"),
      sc("D", "TypeScript 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "context.revert 是 GSAP 推荐 React 集成方式——一键回滚，无遗漏。" },
    abilityTags: ["ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 整体 hero 设计",
    prompt: "HomeHero 整体设计哲学？",
    options: [
      sc("A", "1) GSAP 动态 import 拆 chunk 2) reduce motion 完全跳过动画 3) gsap.context 作用域 + 一键 revert 4) cancelled + cleanup 双重保护异步副作用 5) mountedRef 状态机协调初始 + 切语言两个动画 6) raf 节流 scroll 监听——综合：性能 + 可访问性 + 健壮性"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare 强制"),
      sc("D", "TypeScript 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "六条原则——React + 第三方动画库的最佳实践集合。" },
    abilityTags: ["ai.review.architecture", "frontend.effect.useEffect", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/lib/home-hero-locales.ts"],
  }),
];
