/**
 * Real questions for site-08-home-landing / home-data.
 * Anchor: remix/app/routes/_index.tsx loader —— Promise.all 并发 + getApprovedMessages + 按 session 切 Cache-Control
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/_index.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const homeDataQuestions: RealQ[] = [
  q({
    type: "single_choice", title: "Q1 loader 第一步并发",
    prompt: "loader 内 const sessionPromise = ...; const messagesPromise = getApprovedMessages(null, MESSAGE_BOARD_LIMIT); 不 await——意图？",
    options: [
      sc("A", "构造 Promise 还不等结果——后面 Promise.all 一起 await 才并发；如果先 await session 再调 messages 就串行（耗时翻倍）"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "构造 Promise + Promise.all = 并发；先构造再统一 await——loader 性能基本功。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 requestHasAuthSessionCookie 守卫",
    prompt: "requestHasAuthSessionCookie(request) ? getSessionCached(request) : Promise.resolve(null) 双分支——意图？",
    options: [
      sc("A", "无 auth cookie 直接给 null Promise——绕过 D1 session 表查询；首页大部分匿名流量直接零 IO 拿到 session=null"),
      sc("B", "TypeScript"),
      sc("C", "Cloudflare 限制"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "cookie 早判断 + 短路——首页匿名多时显著省成本。" },
    abilityTags: ["ai.review.architecture", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/auth.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q3 getApprovedMessages 第一参",
    prompt: "getApprovedMessages(null, MESSAGE_BOARD_LIMIT) 第一参 null——意图？",
    options: [
      sc("A", "「不限定用户 id」——拉所有审核通过的留言；登录用户和匿名用户看到一样的公开列表；第二参是数量上限"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "公开列表全用户共享——首页留言区是公开内容。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/messages.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q4 双 await 阶段",
    prompt: "loader 第一阶段 Promise.all([sessionPromise, messagesPromise]) 后；第二阶段 if (session?.user) { Promise.all([getMessageLimitStatus, getPendingMessagesForUser]) }——为什么二阶段？",
    options: [
      sc("A", "第二阶段查询依赖 user.id（session 解开后才有）；只有登录用户才查 limitStatus + pendingMessages；匿名用户跳过——按需查询"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "依赖前置数据的查询要分阶段——依赖关系决定并发边界。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 limitStatus 类型",
    prompt: "let limitStatus: Awaited<ReturnType<typeof getMessageLimitStatus>> | null = null; 这种 TS 类型？",
    options: [
      sc("A", "Awaited<ReturnType<...>> 是「函数返回 Promise 解开后的类型」——避免硬编码 MessageLimitStatus 接口；类型变更只需改 getMessageLimitStatus 一处"),
      sc("B", "随机"),
      sc("C", "Cloudflare 强制"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "类型从函数推——单一来源。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 return json 结构",
    prompt: "return json({ userId, currentUser, songs, messages, userPendingMessages, messageLimitStatus }, { headers })——为什么把这么多字段放一个对象？",
    options: [
      sc("A", "Remix loader 返一个对象 = 一次性给前端所有需要的数据；前端 useLoaderData 一次解构拿全；vs 多次发请求"),
      sc("B", "TypeScript 强制"),
      sc("C", "Cloudflare 限制"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader 一次给齐 = 前端无需多请求——SSR + hydrate 一次到位。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 Cache-Control 双值",
    prompt: "Cache-Control: session?.user ? 'private, no-store' : 'public, max-age=60, s-maxage=300, stale-while-revalidate=600' 两分支？",
    options: [
      sc("A", "登录用户 = 个人化数据，private + no-store（不缓存）；匿名 = 公共数据，CDN 可缓存（s-maxage=300 5分钟）+ 浏览器 60s + SWR 600s——同路由按身份切策略"),
      sc("B", "永远 no-store"),
      sc("C", "永远 public"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "按身份切缓存——CDN 复用率 + 个人化的精细平衡。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank", title: "Q8 SWR 时长",
    prompt: "stale-while-revalidate=____ ",
    options: [],
    blanks: [{ id: "v", placeholder: "数字（秒）", acceptedAnswers: ["600"] }],
    correctAnswer: { type: "fill_blank", values: { v: "600" } },
    explanation: { short: "600 秒（10 分钟）——max-age 过期后用户仍看旧值，后台 fetch 新值；不阻塞用户。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 forwardLoaderCacheControl",
    prompt: "export const headers: HeadersFunction = forwardLoaderCacheControl;——必要？",
    options: [
      sc("A", "必要——v3_singleFetch 模式下 loader Cache-Control 默认不 forward 到 document Response；必须显式 export headers 把它转写出去；不写则 CDN/浏览器不缓存 HTML 页"),
      sc("B", "可选"),
      sc("C", "TypeScript 要求"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "v3_singleFetch + 缓存 = 必须 forward；常被忘记的坑。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q10 HOME_SONGS",
    prompt: "songs: HOME_SONGS——HOME_SONGS 来自 ~/data/home-songs，是？",
    options: [
      sc("A", "构建时 import 的歌曲列表静态数组；不查 D1，loader 直接喂给前端 TabShowcase；改歌单需重新部署"),
      sc("B", "API 拉"),
      sc("C", "用户上传"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "静态歌单 = 模块导入；个人站点的常见简化。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/data/home-songs.ts"],
  }),
  q({
    type: "single_choice", title: "Q11 MESSAGE_BOARD_LIMIT",
    prompt: "getApprovedMessages(null, MESSAGE_BOARD_LIMIT)——MESSAGE_BOARD_LIMIT 是？",
    options: [
      sc("A", "messages.server.ts 内的常量上限（如 30）——首页只展示最近 N 条留言，避免拉满 D1；UI 上有「查看更多」跳到完整 /messages 页"),
      sc("B", "随机"),
      sc("C", "Cloudflare 限制"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "首页摘要 limit——只拉够展示的；详情页才拉全。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: "app/lib/messages.server.ts", layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/messages.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q12 userId 与 currentUser",
    prompt: "userId: session?.user?.id || null, currentUser: session?.user || null——两个字段重复？",
    options: [
      sc("A", "不重复——userId 给「需要 id 但不要全 user 对象」的子组件（轻量传递）；currentUser 给需要 email/name 等完整字段的（如展示用户名）；分两 props 减无关重渲染"),
      sc("B", "纯重复"),
      sc("C", "TypeScript 限制"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "粒度分离的 props——优化精细化场景。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q13 完整 loader 流",
    prompt: "匿名用户访问 / loader 步骤？",
    options: [
      sc("s1", "1. ({ request }) 入参"),
      sc("s2", "2. requestHasAuthSessionCookie(request) → false"),
      sc("s3", "3. sessionPromise = Promise.resolve(null)"),
      sc("s4", "4. messagesPromise = getApprovedMessages(null, 30)"),
      sc("s5", "5. await Promise.all → [null, messages]"),
      sc("s6", "6. session?.user 是 undefined，跳过 if 块；limitStatus 保持 null，userPendingMessages 保持 []"),
      sc("s7", "7. return json with Cache-Control public 60s 300s SWR 600s"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7"] },
    explanation: { short: "匿名最少 IO 流：cookie 早判断 → messages 一次查 → 公共缓存。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/messages.server.ts", "app/lib/auth.server.ts"],
  }),
  q({
    type: "branch_trace", title: "Q14 登录用户 loader 流",
    prompt: "登录用户访问 / loader 步骤？",
    options: [
      sc("s1", "1. requestHasAuthSessionCookie → true"),
      sc("s2", "2. sessionPromise = getSessionCached(request)（D1 解 session）"),
      sc("s3", "3. messagesPromise = getApprovedMessages(null, 30)"),
      sc("s4", "4. Promise.all 并发 → [session, messages]"),
      sc("s5", "5. session?.user 真，进 if 块"),
      sc("s6", "6. 第二阶段并发 await Promise.all([getMessageLimitStatus(user.id), getPendingMessagesForUser(user.id)])"),
      sc("s7", "7. return json with Cache-Control private no-store"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7"] },
    explanation: { short: "登录态最长流：cookie + session + messages 一阶段并发，limit + pending 二阶段并发，缓存私有。" },
    abilityTags: ["bridge.reactRouter.loader", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/messages.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q15 缓存穿透到 CDN",
    prompt: "Cloudflare CDN 命中 5min 缓存的请求——Worker 是否被调用？",
    options: [
      sc("A", "不调用——CDN 边缘节点直接返缓存的 HTML，Worker invocation 数 = 0；这就是 public + s-maxage 的省成本核心机制"),
      sc("B", "永远调用"),
      sc("C", "随机"),
      sc("D", "Cloudflare 决定但通常调"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "CDN 边缘缓存命中 = 不打 Worker——免费层流量大头省钱关键。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 CDN cache key",
    prompt: "Cloudflare CDN 用什么字段作 cache key 来区分不同响应？",
    options: [
      sc("A", "默认是 URL（不含 query 之外的 hash）+ 部分 header（如 Vary: Cookie 时把 Cookie 加入 key）；配合 Vary 让登录态和匿名各自独立缓存"),
      sc("B", "永远 URL"),
      sc("C", "永远 IP"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "cache key = URL + Vary 字段——精准缓存不同上下文。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q17 Vary: Cookie 必要",
    prompt: "判断：当前 loader 不 set Vary: Cookie——CDN 可能把登录用户的 private 响应错误缓存给匿名用户？",
    correctAnswer: { value: false },
    explanation: { short: "错——登录用户走的是 Cache-Control: private no-store，CDN 不缓存它；不存在「错误共享」风险。匿名走 public 才进缓存，互不污染。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 D1 查询性能",
    prompt: "getApprovedMessages 实现常见 SELECT * FROM messages WHERE status='approved' ORDER BY created_at DESC LIMIT 30；性能担心？",
    options: [
      sc("A", "需要 (status, created_at) 复合索引——否则全表扫；D1 是 SQLite 单文件，索引设计好才能快；首页 hot path 必须秒回"),
      sc("B", "永远快"),
      sc("C", "永远慢"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "高频路径必须索引——D1 性能基本功。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: "app/lib/messages.server.ts", layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/messages.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q19 错误抛 vs 返默认",
    prompt: "如果 getApprovedMessages 失败 throw——loader 表现？",
    options: [
      sc("A", "Error 冒泡到 ErrorBoundary（root），整个首页不渲染只显示错误页；过激；进阶可改 try/catch 给 messages = [] 兜底，让首页其他区段仍可看"),
      sc("B", "白屏"),
      sc("C", "永远 200"),
      sc("D", "Cloudflare 拦截"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader throw = 整页错；try/catch + 部分降级是更好的 UX。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 加 R2 数据",
    prompt: "想给首页加「最新照片」一区从 R2 列表拉。落点？",
    options: [
      sc("A", "loader 内 await env.MEDIA_BUCKET.list({ prefix: 'gallery/', limit: 6 })；并发 Promise.all 加进现有数组；前端组件接 props 渲染"),
      sc("B", "客户端 fetch"),
      sc("C", "新路由"),
      sc("D", "wrangler 配置"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "首页扩数据 = loader 加并发查询；保持「一次给齐」原则。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 messageLimitStatus 用途",
    prompt: "messageLimitStatus 拿到后传给 BubbleMessageBoard——用途？",
    options: [
      sc("A", "前端展示用户「今日还能发 X 条」/「下次发言冷却 N 秒」等限流信息——避免用户不知道结果就提交被拒；实时同步「离上限多远」"),
      sc("B", "纯展示"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "限流状态前置 = 用户体验更好，减少错误提交。" },
    abilityTags: ["ai.review.architecture", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/lib/rate-limit.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q22 整体 loader 设计",
    prompt: "_index.tsx loader 整体设计哲学？",
    options: [
      sc("A", "1) cookie 早判断短路省 D1 查询 2) Promise.all 一阶段并发独立 IO 3) 二阶段按需查依赖 user 的数据 4) 一次性 return 所有前端需要的字段 5) 按身份切 Cache-Control（public CDN vs private） 6) forwardLoaderCacheControl 透回 document——综合：性能 + 个人化 + CDN 友好"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare 决定"),
      sc("D", "TypeScript 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "六条原则——首页 loader 性能 + 缓存范式。" },
    abilityTags: ["ai.review.architecture", "bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/lib/auth.server.ts", "app/lib/messages.server.ts", "app/lib/cache-headers.server.ts"],
  }),
];
