/**
 * Real questions for site-08-home-landing / home-lyrics.
 * Anchor: remix/app/components/home/cyber-terminal.tsx —— AI_REDIRECT_HINT_KEY localStorage + AgentStep / TimelineItem 类型 + claim-token 调用
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/home/cyber-terminal.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const homeLyricsQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 localStorage key",
    prompt: 'const AI_REDIRECT_HINT_KEY = "____ ";',
    options: [],
    blanks: [{ id: "v", placeholder: "key", acceptedAnswers: ["cyberTerminalAiHintDismissed"] }],
    correctAnswer: { type: "fill_blank", values: { v: "cyberTerminalAiHintDismissed" } },
    explanation: { short: "驼峰式 key 命名——「赛博终端 AI 提示已关闭」标记，避免重复显示给同一用户。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank", title: "Q2 演示 placeholder",
    prompt: 'const DEMO_INPUT_PLACEHOLDER = "____";',
    options: [],
    blanks: [{ id: "v", placeholder: "提示语", acceptedAnswers: ["演示终端（试试输入 1111）"] }],
    correctAnswer: { type: "fill_blank", values: { v: "演示终端（试试输入 1111）" } },
    explanation: { short: "硬编码提示——彩蛋式引导用户输入「1111」触发 claim-token 流程。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 接口 AgentStep",
    prompt: "interface AgentStep { type: 'read' | 'think' | 'modify'; text: string; meta?: string; } 这个 union type 三个值用途？",
    options: [
      sc("A", "模拟 AI agent 的「读取代码 → 思考 → 修改文件」三步骤——前端用不同 icon 显示；这是项目特色：让用户看到「假 AI agent」工作流，给用户使用 Code Coach 主项目的预期"),
      sc("B", "随机"),
      sc("C", "TypeScript 强制"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "AI agent 工作步骤类型——可视化引导用户理解 agent 概念。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 OutputFile 类型",
    prompt: "interface OutputFile { fileName: string; language: string; content: string; }——用途？",
    options: [
      sc("A", "假装 AI 生成的代码文件——前端用 syntax-highlight（按 language 着色）展示 content；这是「AI 生成代码」的视觉模拟"),
      sc("B", "实际文件系统"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "代码块展示数据结构——syntax 高亮所需。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 TimelineItem status",
    prompt: "interface TimelineItem { status: 'completed' | 'running' | 'pending'; ... } 三态用途？",
    options: [
      sc("A", "前端时间线项的状态——completed（绿色 ✓）、running（蓝色加载）、pending（灰色等待）；视觉化「AI 任务进度」"),
      sc("B", "服务端"),
      sc("C", "随机"),
      sc("D", "TypeScript 强制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "状态机三态——时间线 UI 标准建模。" },
    abilityTags: ["frontend.state.local"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 category enum",
    prompt: "category: 'ACG' | 'Dev' | 'Life'——三类用途？",
    options: [
      sc("A", "时间线项分类——ACG（动漫游戏）/ Dev（开发）/ Life（生活）；不同分类用不同颜色 chip 区分；项目个人站三大兴趣"),
      sc("B", "随机"),
      sc("C", "Cloudflare 决定"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "业务分类 enum——视觉分组的数据基础。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 ClaimTokenResponse status",
    prompt: "ClaimTokenResponse status: 'ok' | 'unauthorized' | 'not_eligible' | 'claimed' | 'empty_but_echo_available' | 'echo_created' 六态——意图？",
    options: [
      sc("A", "claim-token API 的「精细化结果」——前端按状态分支显示不同 toast/提示；vs 简单 success/fail 不能区分「未登录」「不符合条件」「已领过」「无库存但有回声」等场景"),
      sc("B", "纯枚举"),
      sc("C", "TypeScript 限制"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "API 返回精细 status——前端可针对每种情况优化 UX。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/api.claim-token.ts"],
  }),
  q({
    type: "single_choice", title: "Q8 BRAND_BG_SRC",
    prompt: "const BRAND_BG_SRC = resolveImage('internal_brand_023'); 用途？",
    options: [
      sc("A", "终端面板的品牌背景图——resolveImage 把 hash key 解析成 CDN 完整 URL；模块顶层调用，构建时已绑定 URL"),
      sc("B", "随机"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "顶层 resolveImage——构建时确定的静态资源 URL。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/lib/resolve-image.ts"],
  }),
  q({
    type: "single_choice", title: "Q9 5 个 hooks import",
    prompt: "import { useState, useEffect, useCallback, useRef, useMemo } from 'react';——为什么这么多 hooks？",
    options: [
      sc("A", "复杂交互组件：useState 多个 UI 状态、useEffect 副作用、useCallback 稳定 handler 引用、useRef DOM 操作和计时器、useMemo 派生计算——典型「重组件」使用全套 React hooks"),
      sc("B", "随便 import"),
      sc("C", "TypeScript 强制"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "复杂组件 = hooks 五件套——React 主流模式。" },
    abilityTags: ["frontend.state.local", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 lazy 在首页",
    prompt: "_index.tsx 内 const CyberTerminal = lazy(() => import('~/components/home/cyber-terminal'));——chunk 大小考虑？",
    options: [
      sc("A", "组件复杂（多类型 + 大量 mock 数据 + 多 hooks），单独 chunk 减首屏；ViewportLazySection 包它进视口才挂——双层 lazy"),
      sc("B", "纯习惯"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "复杂组件 lazy 单独 chunk——首屏体积优化。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: "app/routes/_index.tsx", layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/routes/_index.tsx"],
  }),
  q({
    type: "single_choice", title: "Q11 localStorage SSR 安全",
    prompt: "组件内访问 localStorage.getItem(AI_REDIRECT_HINT_KEY) 必须放哪里？",
    options: [
      sc("A", "useEffect 内——SSR 时 localStorage 不存在，直接调 ReferenceError；useEffect 只 client 跑，安全访问"),
      sc("B", "组件函数体顶部"),
      sc("C", "全局 IIFE"),
      sc("D", "loader"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "浏览器 API 必须在 useEffect 内——SSR 隔离的标准做法。" },
    abilityTags: ["frontend.effect.useEffect", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 claim-token API 调用",
    prompt: "用户输入 1111 → 触发 fetch('/api/claim-token', { method: 'POST', ... })——这是？",
    options: [
      sc("A", "向后端 api.claim-token.ts 路由发 POST，服务端检查 session + 库存，返 ClaimTokenResponse；前端用 status 字段分支处理"),
      sc("B", "纯前端"),
      sc("C", "Cloudflare KV"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "前后端分离——前端 fetch + 服务端 action。" },
    abilityTags: ["bridge.reactRouter.loader", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/routes/api.claim-token.ts"],
  }),
  q({
    type: "single_choice", title: "Q13 EchoToken",
    prompt: "ClaimTokenResponse 内 echoToken?: EchoToken | null——'echo' 概念？",
    options: [
      sc("A", "「回声」机制——库存空时给用户一个虚拟 echo（回声）作为安慰奖；既不算正式 token 又能给反馈；项目特色 UX"),
      sc("B", "echo 是 ping/pong 测试"),
      sc("C", "TypeScript 类型"),
      sc("D", "Cloudflare 默认"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "「无库存但给回声」是 UX 巧思——降低用户失望。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 useCallback 优化点",
    prompt: "useCallback 包 handleSubmit / handleDismiss 等 handler——意图？",
    options: [
      sc("A", "稳定 handler 引用——传给子组件 props 时不会因父重渲染就触发子重渲染（React.memo 配合时）；纯优化，逻辑不变"),
      sc("B", "性能差"),
      sc("C", "TypeScript 要求"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useCallback = 稳定引用——传 props 给 memo 子时关键。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 useMemo 派生时间线",
    prompt: "useMemo 通常用于派生 timelineItems / filteredCategories——意图？",
    options: [
      sc("A", "缓存大数组的 filter/map 结果——dep 不变就不重算；避免每次重渲染都跑一遍 timelineItems.filter()"),
      sc("B", "TypeScript 要求"),
      sc("C", "Cloudflare 限制"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useMemo 派生数据 = 重算开销大才用；小计算直接写就好。" },
    abilityTags: ["frontend.state.local", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q16 SSR 模拟 AI 输出",
    prompt: "判断：SSR 时 timelineItems 默认数据已经渲染到 HTML。",
    correctAnswer: { value: true },
    explanation: { short: "对——TimelineItem[] 是组件内静态数据；SSR 输出完整时间线 HTML（虽然交互/动画 client 才接管）；SEO 友好。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 演示模式 vs 真模式",
    prompt: "用户输入「1111」触发真 claim-token；输入其他文字呢？",
    options: [
      sc("A", "走演示模式——模拟 AI 步骤动画（read/think/modify）但不调真 API；让用户感受「AI agent」工作流；保护后端不被乱测"),
      sc("B", "永远调 API"),
      sc("C", "拒绝"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "演示 vs 真实双模式——给用户体验同时保护后端。" },
    abilityTags: ["ai.review.architecture", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 Link 而非 anchor",
    prompt: "import { Link } from '@remix-run/react'——为什么不用 <a>？",
    options: [
      sc("A", "Link 触发 React Router 客户端导航不刷新页面；<a> 全页刷新；项目内导航统一用 Link"),
      sc("B", "TypeScript"),
      sc("C", "纯习惯"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SPA 内部跳转用 Link；外部跳转才用 <a>。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 输入框 onKeyDown",
    prompt: "通常 <input onKeyDown={(e) => { if (e.key === 'Enter') handleSubmit(); }} />——为什么不用 onChange + 检测？",
    options: [
      sc("A", "onKeyDown 直接听 Enter 键——惯例 + 简洁；onChange 每次输入触发不该处理 submit；终端类组件首选 onKeyDown"),
      sc("B", "性能"),
      sc("C", "TypeScript"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Enter 提交用 onKeyDown——交互语义清晰。" },
    abilityTags: ["frontend.event.click"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 大量 mock 数据位置",
    prompt: "TimelineItem[] 数据写在哪里？",
    options: [
      sc("A", "组件文件内 const TIMELINE_DATA: TimelineItem[] = [...] —— 数据 + UI 在一个文件，不需要单独 data/ 文件；适合「展示型 mock 数据」（不会从 API 拉）"),
      sc("B", "data/ 目录"),
      sc("C", "D1"),
      sc("D", "API 拉"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "本文件 const + JSX——简单展示型数据就近放。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 加新分类",
    prompt: "想加 'Music' 分类。落点？",
    options: [
      sc("A", "1) interface TimelineItem 的 category union 加 | 'Music' 2) 数据数组里某条改 category: 'Music' 3) UI 渲染时按 'Music' 加 chip 颜色——三处统一改"),
      sc("B", "改 wrangler"),
      sc("C", "改 root"),
      sc("D", "新建文件"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "类型 + 数据 + UI 三处同步——封闭 enum 扩展的标准动作。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 整体设计",
    prompt: "CyberTerminal 整体哲学？",
    options: [
      sc("A", "1) lazy 拆 chunk 2) ViewportLazySection 进视口挂 3) 复杂状态用 5 个 hooks 综合 4) localStorage 在 useEffect 内访问 5) 演示模式 + 真 API 模式双轨 6) 时间线 status/category 用封闭 enum 7) ClaimTokenResponse 精细 status 让前端分支——综合：性能 + 模拟 AI + 真实 API + 健壮性"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare 强制"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "七条原则——「假装是 AI agent」的视觉化展示组件。" },
    abilityTags: ["ai.review.architecture", "code.position.handler", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY, "app/routes/api.claim-token.ts", "app/routes/_index.tsx"],
  }),
];
