/**
 * Real questions for site-08-home-landing / index-route-home.
 * Anchor: remix/app/routes/_index.tsx —— 首页 lazy + ViewportLazySection + ClientOnly + JSON-LD
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/_index.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const indexRouteHomeQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 文件名约定",
    prompt: "Remix v2 flat-routes：根 URL / 对应的路由文件名是 ____ 。",
    options: [],
    blanks: [{ id: "v", placeholder: "文件名", acceptedAnswers: ["_index.tsx"] }],
    correctAnswer: { type: "fill_blank", values: { v: "_index.tsx" } },
    explanation: { short: "_index.tsx 是「root 默认子页」的约定——URL / 时渲染。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 顶部 5 个 lazy import",
    prompt: "const TabShowcase = lazy(() => import('~/components/home/tab-showcase')); 5 个 lazy ——意图？",
    options: [
      sc("A", "below-the-fold 区段拆 chunk——首屏只下 Header + HomeHero + Faq + JSON-LD 这些必要 JS；TabShowcase / VideoShowcase / DonghuaSection / CyberTerminal / BubbleMessageBoard 滚到时才下"),
      sc("B", "代码组织"),
      sc("C", "TypeScript 强制"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "lazy import = 代码分割 = 首屏 JS 体积小——首页性能优化的核心手段。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 ViewportLazySection 与 Suspense 嵌套",
    prompt: "<ViewportLazySection><Suspense><TabShowcase /></Suspense></ViewportLazySection> 双层包裹的意图？",
    options: [
      sc("A", "ViewportLazySection 用 IntersectionObserver 等元素进视口才渲染子（懒挂载）；Suspense 等 lazy 的 chunk 真下完才渲染——双层互补：viewport 控制时机，Suspense 控制 chunk 等待"),
      sc("B", "重复"),
      sc("C", "TypeScript 要求"),
      sc("D", "性能下降"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "viewport gate + suspense gate 双层惰性——首屏 JS / 渲染都最小。" },
    abilityTags: ["ai.review.architecture", "frontend.effect.useEffect"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY, "app/components/common/ViewportLazySection.tsx"],
  }),
  q({
    type: "single_choice", title: "Q4 pulseFallback 函数",
    prompt: "const pulseFallback = (className: string) => (<div className={`${className} bg-gradient-to-r from-primary-50 via-primary-100 to-primary-50 bg-[length:200%_100%] animate-pulse`} />); 这是？",
    options: [
      sc("A", "lazy/Suspense fallback 占位条工厂——传入 className 控制大小，统一渐变 + animate-pulse 视觉；避免到处复制相同 skeleton"),
      sc("B", "纯样式"),
      sc("C", "loader 数据"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "工厂函数复用 skeleton 样式——首页大量区段共用一套占位风格。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 ClientOnly 包 BubbleMessageBoard",
    prompt: "<ClientOnly fallback={...}>{() => (...)}</ClientOnly> 包 BubbleMessageBoard——为什么？",
    options: [
      sc("A", "BubbleMessageBoard.client.tsx 是 .client 文件（用 framer-motion / canvas 等浏览器 API），不能 SSR；ClientOnly 让 SSR 出 fallback skeleton，hydrate 后再挂真组件——避免 hydration mismatch"),
      sc("B", "性能优化"),
      sc("C", "TypeScript 要求"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ClientOnly = SSR 占位 + CSR 渲真组件——是 .client 文件的标准包装。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY, "app/components/messages/BubbleMessageBoard.client.tsx", "app/components/common/ClientOnly.tsx"],
  }),
  q({
    type: "single_choice", title: "Q6 ClientOnly children 是函数",
    prompt: "<ClientOnly>{() => <BubbleMessageBoard ... />}</ClientOnly> children 写成 ()=>JSX 函数——意图？",
    options: [
      sc("A", "延迟实例化——SSR 阶段 ClientOnly 不调用这函数，BubbleMessageBoard.client 模块的 import 副作用（如顶层 framer-motion 调浏览器 API）也不触发；hydrate 后才调用渲真"),
      sc("B", "纯写法"),
      sc("C", "TypeScript 要求"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "function-as-children 模式 = 推迟到 client 才创建元素——避免 SSR 触发模块副作用。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: [PRIMARY, "app/components/common/ClientOnly.tsx"],
  }),
  q({
    type: "single_choice", title: "Q7 JSON-LD 用 dangerouslySetInnerHTML",
    prompt: "<script type='application/ld+json' dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />——为什么用 dangerouslySetInnerHTML？",
    options: [
      sc("A", "React 默认会转义 JSX 文本中的 < / > 等字符；JSON-LD 必须是合法 JSON 文本不能被转义；用 dangerouslySetInnerHTML 直接注入；JSON.stringify 内容是受控的不会被 XSS"),
      sc("B", "性能"),
      sc("C", "Cloudflare 强制"),
      sc("D", "TypeScript 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "JSON-LD 注入是 dangerouslySetInnerHTML 的安全用例——内容是程序生成 + 可控。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 JSON-LD 内容",
    prompt: "jsonLd 对象 @type: 'Person' 包含 name/jobTitle/worksFor/knowsAbout/sameAs 等——是？",
    options: [
      sc("A", "Schema.org Person 结构——给搜索引擎（Google/Bing）告诉「这个网站是谁的个人简历」；提升 SEO 知识图谱命中率"),
      sc("B", "随机数据"),
      sc("C", "Cloudflare 默认"),
      sc("D", "TypeScript 类型"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Schema.org Person 是搜索引擎理解「人物身份」的标准结构——SEO 加分项。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 结构 ui-footer-curtain",
    prompt: "<div className='ui-footer-curtain'><div className='ui-footer-curtain-stage'>{所有内容}</div><div className='ui-footer-reveal'><CreativeFooter /></div></div>——意图？",
    options: [
      sc("A", "「幕布揭示」效果——主内容（stage）滚动时挡住底部 footer（reveal），滚到底部时 footer 像被「揭开」露出；纯 CSS sticky/transform 实现"),
      sc("B", "性能优化"),
      sc("C", "Cloudflare 要求"),
      sc("D", "TypeScript 强制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "幕布揭示 footer 是项目特色 UI——CSS sticky 实现，无 JS 副作用。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/home/creative-footer.tsx"],
  }),
  q({
    type: "single_choice", title: "Q10 fontPreloadHrefs",
    prompt: "links 函数返回的 fontPreloadHrefs(HOME_HERO_PRELOAD_TEXT, 8).map(href => ({ rel: 'preload', as: 'font', type: 'font/woff2', crossOrigin: 'anonymous' })) 意图？",
    options: [
      sc("A", "首屏 HomeHero 大字使用的字体提前 preload——HTML 解析时就开始下字体，不等 CSS 解析完才发请求；HOME_HERO_PRELOAD_TEXT 决定哪些字符；max 8 个文件防过多 preload"),
      sc("B", "纯样式"),
      sc("C", "Cloudflare 要求"),
      sc("D", "无意义"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "字体 preload 减少 FOUT（unstyled flash）——首屏视觉关键优化。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/lib/font-preloads.ts"],
  }),
  q({
    type: "single_choice", title: "Q11 stylesheet links",
    prompt: "{ rel: 'stylesheet', href: styles } 中 styles 来自 import styles from '~/styles/index-route.css?url'——?url 后缀作用？",
    options: [
      sc("A", "Vite 约定——?url 让 import 拿到 CSS 文件的「打包后 URL 路径」而非内容；用于 <link rel='stylesheet'> href，路由级 CSS 关联"),
      sc("B", "纯习惯"),
      sc("C", "TypeScript 限制"),
      sc("D", "Cloudflare 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "?url 是 Vite 显式取 URL 的写法——区别于默认 import CSS 自动注入。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q12 用户首次访问 / 步骤",
    prompt: "首次访问 https://wangjiajun.asia/ 步骤？",
    options: [
      sc("s1", "1. Worker 收 GET /"),
      sc("s2", "2. Remix 匹配 root + _index.tsx"),
      sc("s3", "3. _index.tsx loader 跑：getApprovedMessages + 可能的 getSession 并发"),
      sc("s4", "4. links() 返回 stylesheet + favicon + 字体 preload 列表"),
      sc("s5", "5. SSR 渲染：JSON-LD script + Header + HomeHero + main 内 5 个 lazy 区段（输出 fallback skeleton）+ Faq + footer"),
      sc("s6", "6. 流式输出 HTML，Cache-Control 受 forwardLoaderCacheControl 决策（公共 60s）"),
      sc("s7", "7. JS bundle hydrate，IntersectionObserver 等区段进视口才下 chunk 并渲染"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7"] },
    explanation: { short: "首页 SSR + 流式 + 视口懒加载——三层渐进渲染策略。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/components/home/HomeHero.tsx"],
  }),
  q({
    type: "single_choice", title: "Q13 useLoaderData 解构",
    prompt: "const { currentUser, songs, messages, userPendingMessages, messageLimitStatus } = useLoaderData<typeof loader>(); 拿到的字段？",
    options: [
      sc("A", "loader return 的 json body 字段——TypeScript 用 typeof loader 自动推每个字段类型；songs 是 HOME_SONGS 静态数组，messages 是 D1 查询结果"),
      sc("B", "全局 store"),
      sc("C", "url query"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useLoaderData 拿 loader 给的 server data——TS 类型联动。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q14 _index.tsx 也能 export action",
    prompt: "判断：_index.tsx 也能 export action 接 / 路径的 POST。",
    correctAnswer: { value: true },
    explanation: { short: "对——_index 是普通路由 + 默认匹配属性；export action 接 POST / PUT / DELETE 全支持。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 添加新区段",
    prompt: "想在首页加一个「最近文章」区段。落点？",
    options: [
      sc("A", "1) 新建 components/home/recent-articles.tsx 2) _index.tsx 顶部 const RecentArticles = lazy(() => import('~/components/home/recent-articles')); 3) main 内插一个 ViewportLazySection + Suspense 包它——保持懒加载范式"),
      sc("B", "改 root.tsx"),
      sc("C", "新路由"),
      sc("D", "wrangler 配置"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "首页新区段 = 新组件文件 + lazy + ViewportLazySection 范式——三步不动其他。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/home/recent-articles.tsx"],
  }),
  q({
    type: "single_choice", title: "Q16 Cache-Control 双值",
    prompt: "loader 内 Cache-Control: session?.user ? 'private, no-store' : 'public, max-age=60, s-maxage=300, stale-while-revalidate=600' 双分支？",
    options: [
      sc("A", "登录用户 = private no-store（个人化数据，不共享缓存）；匿名用户 = public 60s 浏览器 + 300s CDN + SWR 600s（公共首页 CDN 复用）；同一路由按身份切换缓存策略"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare 强制"),
      sc("D", "TypeScript 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "按 session 切换缓存策略——精细化平衡个人化 vs CDN 命中率。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 stale-while-revalidate=600",
    prompt: "Cache-Control 中 stale-while-revalidate=600 含义？",
    options: [
      sc("A", "max-age 过期后 600s 内仍可用旧值，同时后台 fetch 新值——用户看到的是旧值（不阻塞），下次访问拿到新；首页这种「准静态」内容的最佳缓存策略"),
      sc("B", "永远新鲜"),
      sc("C", "永远旧"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SWR 模式 = 用户体验优先（不阻塞）+ 数据最终新鲜（后台刷新）。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 Promise.all 并发查询",
    prompt: "loader 内 const [session, messages] = await Promise.all([sessionPromise, messagesPromise]); 用 Promise.all——意图？",
    options: [
      sc("A", "session 查询和 messages 查询互不依赖，并发跑省时间——总耗时 = max(session, messages) 而非 sum；这是「N 次独立 IO」的标准并发模式"),
      sc("B", "Cloudflare 强制"),
      sc("C", "TypeScript 要求"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Promise.all 并发独立 IO——loader 性能基本功。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 requestHasAuthSessionCookie 优化",
    prompt: "const sessionPromise = requestHasAuthSessionCookie(request) ? getSessionCached(request) : Promise.resolve(null); 这优化点？",
    options: [
      sc("A", "请求没 auth cookie 时不调 getSessionCached（绕开 D1 查询 + 解密）；匿名用户直接拿 null——首页大部分流量是匿名的，省掉无效查询"),
      sc("B", "TypeScript 优化"),
      sc("C", "Cloudflare 限制"),
      sc("D", "纯写法"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "「先看 cookie 再查」是 short-circuit 优化——首页匿名流量大头时显著省成本。" },
    abilityTags: ["ai.review.architecture", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/auth.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q20 main vs section",
    prompt: "<main> 包大部分区段而 <Header />、<Faq />、footer 在 main 外——HTML 语义？",
    options: [
      sc("A", "<main> 表「页面主要内容」，每页只能有一个；Header/Footer/Faq 是周边导航/辅助元素，放 main 外更符合 ARIA landmark；屏幕阅读器可用「跳到 main」快捷键"),
      sc("B", "纯样式"),
      sc("C", "随机"),
      sc("D", "TypeScript 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "main 是 ARIA landmark——可访问性 + SEO 都加分。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 5 个 Suspense 共享 fallback",
    prompt: "TabShowcase / DonghuaSection / CyberTerminal / VideoShowcase 各有不同 min-h（36rem/34rem/780px/screen）——为什么各自传 className？",
    options: [
      sc("A", "fallback skeleton 大小尽量贴近真组件渲染后的尺寸——避免「占位 vs 真内容尺寸跳变」造成 CLS（累积布局偏移）；CLS 是 Core Web Vitals 关键指标"),
      sc("B", "纯样式"),
      sc("C", "随机"),
      sc("D", "性能要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "fallback 尺寸贴近真组件 = 防 CLS——影响 SEO 排名和用户体验。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 整体首页设计",
    prompt: "首页 _index.tsx 整体设计哲学？",
    options: [
      sc("A", "1) loader 并发查必要数据 + 按身份切缓存 2) lazy 拆 5 个 below-the-fold chunk 3) ViewportLazySection 控制视口惰性挂载 4) Suspense 等 chunk 5) ClientOnly 包 .client 文件防 hydration mismatch 6) JSON-LD + 字体 preload + sticky footer——综合：首屏 JS 最小、SEO 完整、惰性加载到位"),
      sc("B", "纯习惯"),
      sc("C", "Remix 强制"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "六条原则贯穿——首页性能 + SEO + 体验三方面平衡。" },
    abilityTags: ["ai.review.architecture", "code.position.handler", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/components/home/HomeHero.tsx", "app/components/common/ClientOnly.tsx"],
  }),
];
