import type { SeedCourseData } from "./types";
import { q } from "./types";

export const aiChatRequestChainCourse: SeedCourseData = {
  slug: "ai-chat-request-chain",
  title: "AI Chat 请求链",
  subtitle: "从前端输入到 AI Gateway 的完整守门顺序",
  description:
    "围绕个人网站 AI 聊天功能，训练输入状态、提交事件、请求构造、session 校验、字段验证、限流、AI 调用与响应渲染的完整因果链。",
  projectContext:
    "个人网站的 RAG-Nemesis 聊天需要先过登录、字段校验、限流，再调用 AI Gateway，最后把结果渲染到消息列表。",
  difficulty: "intermediate",
  abilityTags: [
    "frontend.state.local",
    "frontend.event.submit",
    "backend.session.cookie",
    "backend.auth.required",
    "backend.validation.field",
    "backend.rateLimit",
    "bridge.reactRouter.action",
  ],
  orderIndex: 1,
  lessons: [
    {
      slug: "input-and-submit",
      title: "输入状态与提交事件",
      description: "理解聊天输入框状态与发送按钮的因果关系。",
      learningGoal: "能追踪从输入到提交的完整前端事件链。",
      sourceFilePath: "app/routes/chat.tsx",
      orderIndex: 0,
      questions: [
        q({
          type: "single_choice",
          title: "输入框状态类型",
          prompt: "聊天输入框中正在输入的文字应该用什么状态？",
          options: [
            { id: "a", text: "局部 useState" },
            { id: "b", text: "全局 theme 状态" },
            { id: "c", text: "D1 表字段" },
            { id: "d", text: "Cookie" },
          ],
          correctAnswer: { choiceId: "a" },
          explanation: {
            short: "输入草稿是典型局部状态。",
            detail: "只有发送后才需要把消息提升到消息列表或提交到后端。",
          },
          abilityTags: ["frontend.state.local"],
          orderIndex: 0,
        }),
        q({
          type: "sort",
          title: "点击发送后的前端顺序",
          prompt: "用户点击发送按钮后，前端的正确执行顺序：",
          sortItems: [
            { id: "1", text: "读取输入框当前值" },
            { id: "2", text: "校验非空" },
            { id: "3", text: "构造请求体" },
            { id: "4", text: "调用 action/fetcher 提交" },
            { id: "5", text: "清空或保留输入框" },
          ],
          correctAnswer: { itemIds: ["1", "2", "3", "4", "5"] },
          explanation: {
            short: "读值 → 校验 → 构造 → 提交 → 更新 UI。",
            detail: "这是前端事件链的基本模式。",
          },
          abilityTags: ["frontend.event.submit", "frontend.event.click"],
          orderIndex: 1,
        }),
        q({
          type: "fill_blank",
          title: "提交方式",
          prompt: "在 React Router 中，表单写操作通常通过 _____ 处理。",
          blanks: [
            { id: "action", placeholder: "API", acceptedAnswers: ["action", "Action"] },
          ],
          correctAnswer: { values: { action: "action" } },
          explanation: {
            short: "action 负责处理 POST 写操作。",
            detail: "loader 负责读，action 负责写，这是 RR 数据模式的基本分工。",
          },
          abilityTags: ["bridge.reactRouter.action"],
          orderIndex: 2,
        }),
        q({
          type: "debug",
          title: "提交空消息",
          prompt: "以下代码允许提交空消息，问题是什么？\nif (message) { submit(message); } // 但 message 可能是空格",
          options: [
            { id: "trim", text: "缺少 trim() 校验，空格可通过" },
            { id: "syntax", text: "if 语法错误" },
            { id: "api", text: "API 地址错误" },
            { id: "none", text: "没有问题" },
          ],
          correctAnswer: { issueId: "trim" },
          explanation: {
            short: "前端应先 trim 再校验非空。",
            detail: "纯空格消息不应发送到后端浪费资源。",
          },
          abilityTags: ["backend.validation.field", "frontend.event.submit"],
          orderIndex: 3,
        }),
        q({
          type: "position_judgement",
          title: "handleSubmit 位置",
          prompt: "handleSubmit 函数应该写在哪里？",
          options: [
            { id: "before", text: "组件 return 之前" },
            { id: "jsx", text: "嵌套在 JSX onClick 内联 50 行逻辑" },
            { id: "loader", text: "loader 函数内" },
            { id: "css", text: "CSS 文件" },
          ],
          correctAnswer: { positionId: "before" },
          explanation: {
            short: "事件处理函数放在 return 前。",
            detail: "保持 JSX 可读，逻辑与视图分离。",
          },
          abilityTags: ["code.position.handler"],
          orderIndex: 4,
        }),
      ],
    },
    {
      slug: "request-and-session",
      title: "请求构造与 Session 读取",
      description: "后端如何读取 Cookie/Session 并判断登录。",
      learningGoal: "理解 action 中 session 守门的位置。",
      sourceFilePath: "app/lib/auth.server.ts",
      orderIndex: 1,
      questions: [
        q({
          type: "sort",
          title: "后端请求守门顺序（前半段）",
          prompt: "AI Chat action 收到请求后的前半段正确顺序：",
          sortItems: [
            { id: "1", text: "检查 request method" },
            { id: "2", text: "读取 Cookie / Session" },
            { id: "3", text: "判断用户是否登录" },
            { id: "4", text: "解析并校验 message 字段" },
          ],
          correctAnswer: { itemIds: ["1", "2", "3", "4"] },
          explanation: {
            short: "method → session → 登录 → 字段校验。",
            detail: "未登录应在字段校验前直接返回 401。",
          },
          abilityTags: ["backend.session.cookie", "backend.auth.required", "bridge.reactRouter.action"],
          mistakeTypes: ["backend_guard_order_error"],
          orderIndex: 0,
        }),
        q({
          type: "single_choice",
          title: "未登录应返回什么？",
          prompt: "未登录用户调用 AI Chat API 应返回？",
          options: [
            { id: "401", text: "401 Unauthorized" },
            { id: "200", text: "200 空响应" },
            { id: "500", text: "500 服务器错误" },
            { id: "301", text: "301 重定向" },
          ],
          correctAnswer: { choiceId: "401" },
          explanation: {
            short: "401 表示需要登录。",
            detail: "这与 403（无权限）、400（参数错）含义不同。",
          },
          abilityTags: ["backend.auth.required"],
          mistakeTypes: ["session_error", "error_code_error"],
          orderIndex: 1,
        }),
        q({
          type: "branch_trace",
          title: "未登录用户发消息",
          prompt: "未登录用户提交聊天消息时的正确分支：",
          options: [
            { id: "session", text: "读取 session，user 为空" },
            { id: "401", text: "返回 401，不调用 AI" },
            { id: "skip", text: "跳过限流和资格检查" },
          ],
          correctAnswer: { pathIds: ["session", "401", "skip"] },
          explanation: {
            short: "未登录直接 401，不进入后续业务。",
            detail: "不应在未登录时调用昂贵的 AI API。",
          },
          abilityTags: ["backend.auth.required", "backend.session.cookie"],
          orderIndex: 2,
        }),
        q({
          type: "multi_choice",
          title: "AI Chat 调用前必须检查",
          prompt: "调用 AI 模型前必须检查哪些？（多选）",
          options: [
            { id: "login", text: "是否登录" },
            { id: "message", text: "message 是否合法" },
            { id: "rate", text: "是否触发限流" },
            { id: "css", text: "CSS 是否加载完成" },
          ],
          correctAnswer: { choiceIds: ["login", "message", "rate"] },
          explanation: {
            short: "登录、字段、限流是三道关键守门。",
            detail: "CSS 加载与 API 守门无关。",
          },
          abilityTags: ["backend.auth.required", "backend.validation.field", "backend.rateLimit"],
          orderIndex: 3,
        }),
        q({
          type: "fill_blank",
          title: "Session 存储位置",
          prompt: "Web 应用中 session 标识通常存在 _____ 里。",
          blanks: [
            { id: "cookie", placeholder: "存储", acceptedAnswers: ["cookie", "Cookie", "cookies"] },
          ],
          correctAnswer: { values: { cookie: "cookie" } },
          explanation: {
            short: "Cookie 是 session 传递的标准载体。",
            detail: "后端从 request headers 读取 Cookie 解析 session。",
          },
          abilityTags: ["backend.session.cookie"],
          orderIndex: 4,
        }),
      ],
    },
    {
      slug: "validation-and-ratelimit",
      title: "字段校验与限流",
      description: "理解校验和限流在 AI 调用前的位置。",
      learningGoal: "知道限流应在昂贵 AI 调用之前执行。",
      sourceFilePath: "app/lib/rate-limit.server.ts",
      orderIndex: 2,
      questions: [
        q({
          type: "single_choice",
          title: "限流应在何时检查？",
          prompt: "限流检查应该放在 AI API 调用的？",
          options: [
            { id: "before", text: "之前" },
            { id: "after", text: "之后" },
            { id: "never", text: "不需要限流" },
            { id: "db", text: "数据库写入时" },
          ],
          correctAnswer: { choiceId: "before" },
          explanation: {
            short: "先限流，再调用昂贵 API。",
            detail: "先调 AI 再限流会浪费资源和费用。",
            commonMistake: "AI 先调用再限流是常见架构错误。",
          },
          abilityTags: ["backend.rateLimit", "ai.review.architecture"],
          orderIndex: 0,
        }),
        q({
          type: "sort",
          title: "完整后端守门顺序",
          prompt: "AI Chat action 的完整后端守门顺序：",
          sortItems: [
            { id: "1", text: "读取 session" },
            { id: "2", text: "检查登录" },
            { id: "3", text: "校验 message 字段" },
            { id: "4", text: "检查限流" },
            { id: "5", text: "调用 AI Gateway" },
            { id: "6", text: "返回结果" },
          ],
          correctAnswer: { itemIds: ["1", "2", "3", "4", "5", "6"] },
          explanation: {
            short: "session → 登录 → 校验 → 限流 → AI → 返回。",
            detail: "这是后端请求链训练的核心顺序。",
          },
          abilityTags: ["backend.rateLimit", "bridge.reactRouter.action"],
          mistakeTypes: ["backend_guard_order_error"],
          orderIndex: 1,
        }),
        q({
          type: "debug",
          title: "限流顺序错误",
          prompt: "代码先 await callAiGateway() 再 checkRateLimit()，问题是什么？",
          options: [
            { id: "order", text: "限流应在 AI 调用之前" },
            { id: "none", text: "顺序无所谓" },
            { id: "css", text: "CSS 问题" },
            { id: "db", text: "D1 锁表" },
          ],
          correctAnswer: { issueId: "order" },
          explanation: {
            short: "昂贵操作前应完成所有守门检查。",
            detail: "包括登录、校验、限流、权限。",
          },
          abilityTags: ["backend.rateLimit", "ai.review.architecture"],
          orderIndex: 2,
        }),
        q({
          type: "single_choice",
          title: "触发限流返回码",
          prompt: "用户请求过于频繁应返回？",
          options: [
            { id: "429", text: "429 Too Many Requests" },
            { id: "401", text: "401" },
            { id: "403", text: "403" },
            { id: "200", text: "200" },
          ],
          correctAnswer: { choiceId: "429" },
          explanation: {
            short: "429 专用于限流场景。",
            detail: "与 401（未登录）、403（无权限）区分。",
          },
          abilityTags: ["backend.rateLimit"],
          mistakeTypes: ["rate_limit_error", "error_code_error"],
          orderIndex: 3,
        }),
        q({
          type: "ai_review",
          title: "评审 AI 生成的 action",
          prompt: "AI 生成的 action 直接调用 AI Gateway，没有任何登录和限流检查。最大问题是？",
          options: [
            { id: "a", text: "缺少后端守门，存在安全和成本风险" },
            { id: "b", text: "应该用 GET 而不是 POST" },
            { id: "c", text: "缺少 CSS" },
            { id: "d", text: "变量名太长" },
          ],
          correctAnswer: { choiceId: "a" },
          explanation: {
            short: "AI 调用前必须有完整守门链。",
            detail: "未登录可调用、无限流保护会导致滥用和费用失控。",
          },
          abilityTags: ["ai.review.architecture", "backend.auth.required", "backend.rateLimit"],
          orderIndex: 4,
        }),
      ],
    },
    {
      slug: "response-render",
      title: "AI 响应与前端渲染",
      description: "AI 返回后如何更新消息列表 UI。",
      learningGoal: "理解从 action 返回到 UI 更新的完整链路。",
      sourceFilePath: "app/routes/chat.tsx",
      orderIndex: 3,
      questions: [
        q({
          type: "sort",
          title: "从 AI 响应到 UI 更新",
          prompt: "AI Gateway 返回后的前端处理顺序：",
          sortItems: [
            { id: "1", text: "action 返回 JSON 响应" },
            { id: "2", text: "fetcher/action 接收结果" },
            { id: "3", text: "更新 messages 状态" },
            { id: "4", text: "UI 重新渲染显示新消息" },
          ],
          correctAnswer: { itemIds: ["1", "2", "3", "4"] },
          explanation: {
            short: "响应 → 接收 → 更新状态 → 渲染。",
            detail: "这是前后端连接的最后一段链路。",
          },
          abilityTags: ["bridge.reactRouter.action", "frontend.state.local"],
          orderIndex: 0,
        }),
        q({
          type: "single_choice",
          title: "消息列表状态",
          prompt: "聊天消息列表通常用什么管理？",
          options: [
            { id: "a", text: "组件 state 或 loader 数据 + 乐观更新" },
            { id: "b", text: "CSS 变量" },
            { id: "c", text: "wrangler.toml" },
            { id: "d", text: "不需要状态" },
          ],
          correctAnswer: { choiceId: "a" },
          explanation: {
            short: "消息列表需要可变的 UI 状态。",
            detail: "新消息到达后需要触发重新渲染。",
          },
          abilityTags: ["frontend.state.local"],
          orderIndex: 1,
        }),
        q({
          type: "multi_choice",
          title: "action 返回应包含",
          prompt: "AI Chat action 成功时通常应返回？（多选）",
          options: [
            { id: "text", text: "AI 回复文本" },
            { id: "id", text: "消息 ID（可选）" },
            { id: "html", text: "整个 HTML 页面" },
            { id: "error", text: "错误时应返回错误信息" },
          ],
          correctAnswer: { choiceIds: ["text", "id", "error"] },
          explanation: {
            short: "返回结构化 JSON，不是整页 HTML。",
            detail: "RR action 模式返回数据，由组件负责渲染。",
          },
          abilityTags: ["bridge.reactRouter.action"],
          orderIndex: 2,
        }),
        q({
          type: "branch_trace",
          title: "AI 调用失败分支",
          prompt: "AI Gateway 调用失败时的正确处理：",
          options: [
            { id: "catch", text: "catch 错误" },
            { id: "log", text: "记录日志" },
            { id: "friendly", text: "返回友好错误给前端" },
            { id: "crash", text: "让 Worker 崩溃不处理" },
          ],
          correctAnswer: { pathIds: ["catch", "log", "friendly"] },
          explanation: {
            short: "捕获 → 记录 → 友好提示。",
            detail: "AI 失败不应导致整个页面不可用。",
          },
          abilityTags: ["bridge.reactRouter.action", "project.modify.fullstack"],
          orderIndex: 3,
        }),
        q({
          type: "fill_blank",
          title: "数据读取入口",
          prompt: "React Router 中页面初始数据通常由 _____ 加载。",
          blanks: [
            { id: "loader", placeholder: "函数", acceptedAnswers: ["loader", "Loader"] },
          ],
          correctAnswer: { values: { loader: "loader" } },
          explanation: {
            short: "loader 负责读，action 负责写。",
            detail: "聊天历史可在 loader 中预加载。",
          },
          abilityTags: ["bridge.reactRouter.loader"],
          orderIndex: 4,
        }),
      ],
    },
  ],
};
