import type { SeedCourseData } from "./types";
import { q } from "./types";

export const authProtectedTokenFlowCourse: SeedCourseData = {
  slug: "auth-protected-token-flow",
  title: "登录保护与领取 Token",
  subtitle: "Cookie/Session、资格校验与错误码反馈",
  description:
    "围绕受保护 API 领取 token 的真实场景，训练 cookie/session、登录守门、字段校验、重复领取检查、D1 写入与 401/403/429/400 错误处理。",
  projectContext:
    "个人网站有领取补给 token 的受保护 API：未登录返回 401，字段不合法返回 400，重复领取返回 403，触发限流返回 429。",
  difficulty: "advanced",
  abilityTags: [
    "backend.session.cookie",
    "backend.auth.required",
    "backend.validation.field",
    "backend.rateLimit",
    "bridge.reactRouter.action",
    "bridge.reactRouter.loader",
    "project.modify.fullstack",
  ],
  orderIndex: 2,
  lessons: [
    {
      slug: "cookie-session-guard",
      title: "Cookie / Session 守门",
      description: "理解受保护 API 如何读取 session 判断登录。",
      learningGoal: "知道未登录时不能进入业务逻辑。",
      sourceFilePath: "app/lib/auth.server.ts",
      orderIndex: 0,
      questions: [
        q({
          type: "single_choice",
          title: "受保护 API 第一步",
          prompt: "领取 token 的 action 收到请求后，第一步应该？",
          options: [
            { id: "a", text: "读取 Cookie 解析 session" },
            { id: "b", text: "直接写 D1" },
            { id: "c", text: "调用 AI" },
            { id: "d", text: "返回 HTML 页面" },
          ],
          correctAnswer: { choiceId: "a" },
          explanation: {
            short: "先确认身份，再执行业务。",
            detail: "session 是后续所有守门的前提。",
          },
          abilityTags: ["backend.session.cookie", "backend.auth.required"],
          orderIndex: 0,
        }),
        q({
          type: "branch_trace",
          title: "未登录领取 token",
          prompt: "未登录用户请求领取 token 的正确路径：",
          options: [
            { id: "read", text: "读取 session" },
            { id: "empty", text: "user 不存在" },
            { id: "401", text: "返回 401" },
            { id: "skip", text: "不检查资格、不写数据库" },
          ],
          correctAnswer: { pathIds: ["read", "empty", "401", "skip"] },
          explanation: {
            short: "未登录 → 401 → 不进入后续逻辑。",
            detail: "这是文档中的经典后端分支推演案例。",
          },
          abilityTags: ["backend.auth.required", "backend.session.cookie"],
          mistakeTypes: ["session_error", "backend_guard_order_error"],
          orderIndex: 1,
        }),
        q({
          type: "sort",
          title: "领取 token 完整守门链",
          prompt: "已登录用户领取 token 的后端完整顺序：",
          sortItems: [
            { id: "1", text: "读取 session 确认登录" },
            { id: "2", text: "校验请求字段" },
            { id: "3", text: "检查限流" },
            { id: "4", text: "检查是否已领取（资格）" },
            { id: "5", text: "写入 D1" },
            { id: "6", text: "返回 token" },
          ],
          correctAnswer: { itemIds: ["1", "2", "3", "4", "5", "6"] },
          explanation: {
            short: "登录 → 校验 → 限流 → 资格 → 写入 → 返回。",
            detail: "守门顺序错误是后端训练的核心。",
          },
          abilityTags: ["bridge.reactRouter.action", "backend.rateLimit"],
          mistakeTypes: ["backend_guard_order_error"],
          orderIndex: 2,
        }),
        q({
          type: "multi_choice",
          title: "401 vs 403",
          prompt: "以下说法正确的是？（多选）",
          options: [
            { id: "401", text: "401 = 未登录" },
            { id: "403", text: "403 = 已登录但无权限/不符合资格" },
            { id: "same", text: "401 和 403 含义相同" },
            { id: "400", text: "400 = 请求参数不合法" },
          ],
          correctAnswer: { choiceIds: ["401", "403", "400"] },
          explanation: {
            short: "三种错误码含义不同，不能混用。",
            detail: "重复领取 token 通常是 403，不是 401。",
          },
          abilityTags: ["backend.auth.required"],
          mistakeTypes: ["error_code_error", "permission_error"],
          orderIndex: 3,
        }),
        q({
          type: "debug",
          title: "跳过登录检查",
          prompt: "action 直接 await writeTokenToD1() 没有检查 session，问题是什么？",
          options: [
            { id: "auth", text: "任何人都可以领取 token" },
            { id: "css", text: "CSS 不生效" },
            { id: "none", text: "没有问题" },
            { id: "slow", text: "只是慢一点" },
          ],
          correctAnswer: { issueId: "auth" },
          explanation: {
            short: "缺少登录守门是严重安全漏洞。",
            detail: "受保护 API 必须先验证身份。",
          },
          abilityTags: ["backend.auth.required", "ai.review.architecture"],
          orderIndex: 4,
        }),
      ],
    },
    {
      slug: "field-validation",
      title: "字段校验",
      description: "请求参数校验的位置和方式。",
      learningGoal: "知道非法字段应返回 400。",
      sourceFilePath: "app/routes/api.claim-token.tsx",
      orderIndex: 1,
      questions: [
        q({
          type: "single_choice",
          title: "非法字段返回码",
          prompt: "请求 body 缺少必填字段应返回？",
          options: [
            { id: "400", text: "400 Bad Request" },
            { id: "401", text: "401" },
            { id: "500", text: "500" },
            { id: "200", text: "200" },
          ],
          correctAnswer: { choiceId: "400" },
          explanation: {
            short: "400 表示客户端请求有问题。",
            detail: "与未登录（401）、无权限（403）区分。",
          },
          abilityTags: ["backend.validation.field"],
          mistakeTypes: ["validation_error", "error_code_error"],
          orderIndex: 0,
        }),
        q({
          type: "fill_blank",
          title: "校验时机",
          prompt: "字段校验应在 _____ 检查之后、业务逻辑之前执行。",
          blanks: [
            { id: "auth", placeholder: "检查", acceptedAnswers: ["登录", "login", "auth", "身份", "session"] },
          ],
          correctAnswer: { values: { auth: "登录" } },
          explanation: {
            short: "先确认身份，再校验参数。",
            detail: "但 400 和 401 的返回时机不同——未登录优先 401。",
          },
          abilityTags: ["backend.validation.field", "backend.auth.required"],
          orderIndex: 1,
        }),
        q({
          type: "multi_choice",
          title: "领取 token 可能需要的校验",
          prompt: "领取 token API 可能需要校验哪些？（多选）",
          options: [
            { id: "type", text: "token 类型是否合法" },
            { id: "amount", text: "数量是否在允许范围" },
            { id: "theme", text: "用户主题偏好" },
            { id: "format", text: "字段格式是否正确" },
          ],
          correctAnswer: { choiceIds: ["type", "amount", "format"] },
          explanation: {
            short: "业务字段校验，不是 UI 偏好。",
            detail: "主题与 token 领取无关。",
          },
          abilityTags: ["backend.validation.field"],
          orderIndex: 2,
        }),
        q({
          type: "debug",
          title: "信任客户端数据",
          prompt: "后端直接使用 body.userId 而不从 session 读取，问题是什么？",
          options: [
            { id: "spoof", text: "客户端可伪造 userId" },
            { id: "slow", text: "性能慢" },
            { id: "css", text: "样式错误" },
            { id: "none", text: "没有问题" },
          ],
          correctAnswer: { issueId: "spoof" },
          explanation: {
            short: "用户身份必须来自服务端 session，不能信任客户端。",
            detail: "这是基本的安全原则。",
          },
          abilityTags: ["backend.session.cookie", "backend.auth.required"],
          orderIndex: 3,
        }),
        q({
          type: "position_judgement",
          title: "校验函数位置",
          prompt: "validateClaimTokenBody() 最适合放在？",
          options: [
            { id: "server", text: "server 层独立函数，action 调用" },
            { id: "jsx", text: "React 组件 JSX 内" },
            { id: "css", text: "CSS 文件" },
            { id: "client", text: "仅客户端校验，后端不校验" },
          ],
          correctAnswer: { positionId: "server" },
          explanation: {
            short: "后端必须独立校验，不能仅靠前端。",
            detail: "校验逻辑放 server 层便于复用和测试。",
          },
          abilityTags: ["backend.validation.field", "code.position.handler"],
          orderIndex: 4,
        }),
      ],
    },
    {
      slug: "rate-limit-eligibility",
      title: "限流与资格检查",
      description: "限流和重复领取检查的执行顺序。",
      learningGoal: "理解 429 和 403 的触发场景。",
      orderIndex: 2,
      questions: [
        q({
          type: "single_choice",
          title: "重复领取返回码",
          prompt: "用户已经领取过 token，再次领取应返回？",
          options: [
            { id: "403", text: "403 Forbidden" },
            { id: "401", text: "401" },
            { id: "200", text: "200 再发一个" },
            { id: "500", text: "500" },
          ],
          correctAnswer: { choiceId: "403" },
          explanation: {
            short: "已登录但不符合资格 → 403。",
            detail: "不是未登录（401），而是业务规则不允许。",
          },
          abilityTags: ["backend.auth.required"],
          mistakeTypes: ["permission_error", "error_code_error"],
          orderIndex: 0,
        }),
        q({
          type: "sort",
          title: "限流 vs 资格检查顺序",
          prompt: "限流和资格检查的正确相对位置（都已登录、字段合法）：",
          sortItems: [
            { id: "1", text: "检查限流（429）" },
            { id: "2", text: "检查是否已领取（403）" },
            { id: "3", text: "写入 D1" },
          ],
          correctAnswer: { itemIds: ["1", "2", "3"] },
          explanation: {
            short: "先挡高频请求，再检查业务资格。",
            detail: "两者都在 D1 写入之前。",
          },
          abilityTags: ["backend.rateLimit", "backend.auth.required"],
          orderIndex: 1,
        }),
        q({
          type: "ai_review",
          title: "评审 AI 的 token action",
          prompt: "AI 生成：先写 D1 再检查是否重复领取。最大问题是？",
          options: [
            { id: "a", text: "可能导致重复写入，守门顺序错误" },
            { id: "b", text: "变量命名不规范" },
            { id: "c", text: "缺少注释" },
            { id: "d", text: "应使用 GET" },
          ],
          correctAnswer: { choiceId: "a" },
          explanation: {
            short: "资格检查必须在写入之前。",
            detail: "先写后查会造成数据不一致。",
          },
          abilityTags: ["ai.review.architecture", "backend.auth.required"],
          orderIndex: 2,
        }),
        q({
          type: "branch_trace",
          title: "触发限流时的路径",
          prompt: "用户短时间内多次请求触发限流：",
          options: [
            { id: "count", text: "KV/计数器检测超限" },
            { id: "429", text: "返回 429" },
            { id: "skip", text: "不写入 D1" },
          ],
          correctAnswer: { pathIds: ["count", "429", "skip"] },
          explanation: {
            short: "超限 → 429 → 不写库。",
            detail: "限流是保护后端和数据库的关键机制。",
          },
          abilityTags: ["backend.rateLimit"],
          mistakeTypes: ["rate_limit_error"],
          orderIndex: 3,
        }),
        q({
          type: "multi_choice",
          title: "D1 写入前应完成",
          prompt: "向 D1 写入 token 记录前必须完成？（多选）",
          options: [
            { id: "login", text: "登录确认" },
            { id: "validate", text: "字段校验" },
            { id: "rate", text: "限流检查" },
            { id: "dup", text: "重复领取检查" },
          ],
          correctAnswer: { choiceIds: ["login", "validate", "rate", "dup"] },
          explanation: {
            short: "全部守门通过后才能写库。",
            detail: "这是后端请求链的最终关卡。",
          },
          abilityTags: ["backend.rateLimit", "backend.validation.field", "project.modify.fullstack"],
          orderIndex: 4,
        }),
      ],
    },
    {
      slug: "frontend-error-feedback",
      title: "前端错误反馈",
      description: "前端如何根据 401/403/429/400 给用户正确反馈。",
      learningGoal: "能把后端错误码映射为用户可理解的提示。",
      sourceFilePath: "app/routes/api.claim-token.tsx",
      orderIndex: 3,
      questions: [
        q({
          type: "single_choice",
          title: "401 的前端提示",
          prompt: "收到 401 时，前端应该？",
          options: [
            { id: "a", text: "提示用户登录" },
            { id: "b", text: "显示「领取成功」" },
            { id: "c", text: "忽略错误" },
            { id: "d", text: "刷新整个网站" },
          ],
          correctAnswer: { choiceId: "a" },
          explanation: {
            short: "401 → 引导登录。",
            detail: "用户需要知道为什么没有领取成功。",
          },
          abilityTags: ["bridge.reactRouter.action", "backend.auth.required"],
          orderIndex: 0,
        }),
        q({
          type: "multi_choice",
          title: "错误码与用户提示映射",
          prompt: "正确的错误码映射？（多选）",
          options: [
            { id: "400", text: "400 → 检查输入是否正确" },
            { id: "401", text: "401 → 请先登录" },
            { id: "403", text: "403 → 已领取或无权操作" },
            { id: "429", text: "429 → 操作太频繁，请稍后再试" },
          ],
          correctAnswer: { choiceIds: ["400", "401", "403", "429"] },
          explanation: {
            short: "每种错误码对应不同用户提示。",
            detail: "不要把所有错误都显示成「代码炸了」。",
          },
          abilityTags: ["project.modify.fullstack"],
          mistakeTypes: ["error_code_error"],
          orderIndex: 1,
        }),
        q({
          type: "sort",
          title: "前端领取 token 完整链路",
          prompt: "用户点击「领取 token」的完整前后端链路：",
          sortItems: [
            { id: "1", text: "用户点击按钮" },
            { id: "2", text: "前端 submit action" },
            { id: "3", text: "后端 session/校验/限流/资格" },
            { id: "4", text: "D1 写入 token" },
            { id: "5", text: "返回结果给前端" },
            { id: "6", text: "前端显示成功或错误提示" },
          ],
          correctAnswer: { itemIds: ["1", "2", "3", "4", "5", "6"] },
          explanation: {
            short: "点击 → 提交 → 守门 → 写库 → 返回 → 反馈。",
            detail: "这是前后端完整业务链。",
          },
          abilityTags: ["project.modify.fullstack", "frontend.event.click"],
          orderIndex: 2,
        }),
        q({
          type: "fill_blank",
          title: "成功反馈",
          prompt: "领取成功后，前端通常把 token 复制到剪贴板并显示 _____ 提示。",
          blanks: [
            { id: "ok", placeholder: "提示", acceptedAnswers: ["成功", "success", "已复制", "完成"] },
          ],
          correctAnswer: { values: { ok: "成功" } },
          explanation: {
            short: "成功反馈让用户确认操作完成。",
            detail: "个人网站中领取 token 后会显示复制成功提示。",
          },
          abilityTags: ["frontend.event.click"],
          orderIndex: 3,
        }),
        q({
          type: "debug",
          title: "错误提示不准确",
          prompt: "所有 API 错误都显示「服务器炸了」，问题是什么？",
          options: [
            { id: "mapping", text: "没有按错误码区分提示" },
            { id: "none", text: "没有问题" },
            { id: "css", text: "CSS 问题" },
            { id: "db", text: "D1 未创建" },
          ],
          correctAnswer: { issueId: "mapping" },
          explanation: {
            short: "用户无法知道是未登录、太频繁还是已领取。",
            detail: "错误码应映射为具体可操作的提示。",
          },
          abilityTags: ["project.modify.fullstack"],
          mistakeTypes: ["error_code_error", "bridge_error"],
          orderIndex: 4,
        }),
      ],
    },
  ],
};
