/**
 * Real questions for site-07-nested-layouts / game-components.
 * Anchor: remix/app/components/game/{GamePlatformPicker, GamePlatformPage, GamePlatformIcons, GamePageBackground, GamePageClient.client}.tsx
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/components/game/GamePlatformPicker.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const gameComponentsQuestions: RealQ[] = [
  q({
    type: "single_choice", title: "Q1 game/ 组件目录意图",
    prompt: "components/game/ 下放 GamePlatformPicker / GamePlatformPage / GamePlatformIcons / GamePageBackground / GamePageClient.client 五个文件——分组的好处？",
    options: [
      sc("A", "按业务域分目录——game 域下所有组件聚拢；新增「成就墙」组件就放 components/game/AchievementWall.tsx 不用动其他目录；vs 按类型（buttons/, cards/）分组的横切方式更利于快速定位"),
      sc("B", "Remix 强制"),
      sc("C", "TypeScript 限制"),
      sc("D", "Cloudflare 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "按域分组 = 业务相关的代码就近——增删改影响面收敛。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: "app/components/game/", layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/components/game/GamePlatformPage.tsx"],
  }),
  q({
    type: "fill_blank", title: "Q2 .client 后缀",
    prompt: "GamePageClient.client.tsx 后缀 ____ 表示什么？",
    options: [],
    blanks: [{ id: "v", placeholder: "后缀语义", acceptedAnswers: [".client", "client", ".client.tsx"] }],
    correctAnswer: { type: "fill_blank", values: { v: ".client" } },
    explanation: { short: ".client 是 Remix 约定——「永不在 server 跑」；构建时验证 server bundle 不会 import 它。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: "app/components/game/GamePageClient.client.tsx", layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: ["app/components/game/GamePageClient.client.tsx"],
  }),
  q({
    type: "single_choice", title: "Q3 GamePlatformIcons 内联 SVG",
    prompt: "GamePlatformIcons.tsx export PlayStationIcon / SwitchIcon / PCIcon——为什么选内联 SVG 而不是外部图片？",
    options: [
      sc("A", "SVG 内联进 React 组件 = 渲染时直接出现在 HTML 流；省一次图片 HTTP 请求；可用 currentColor 跟随 theme；体积小（图标几 KB）适合内联"),
      sc("B", "Cloudflare 限制"),
      sc("C", "性能更差但 React 习惯"),
      sc("D", "TypeScript 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "图标内联是常见优化——单文件 ≤ 5KB 时省一次请求 + 支持 currentColor。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: "app/components/game/GamePlatformIcons.tsx", layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/components/game/GamePlatformIcons.tsx"],
  }),
  q({
    type: "single_choice", title: "Q4 platformIcons 查表",
    prompt: "const platformIcons = { playstation: PlayStationIcon, switch: SwitchIcon, pc: PCIcon } as const; 这种字典查表？",
    options: [
      sc("A", "把 PlatformId → Icon 的映射表表化；map 内 const Icon = platformIcons[platform.id]; 后 <Icon /> 渲染——比 if/else 链短"),
      sc("B", "性能优化"),
      sc("C", "TypeScript 要求"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "字典代替 switch——查表是数据驱动渲染的常见手法。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/components/game/GamePlatformIcons.tsx"],
  }),
  q({
    type: "fill_blank", title: "Q5 as const 断言",
    prompt: "const platformIcons = { ... } as const; 中 as ____ 把对象类型从 { [key: string]: ComponentType } 收窄成 readonly { playstation: ..., switch: ..., pc: ... }",
    options: [],
    blanks: [{ id: "v", placeholder: "TS 关键字", acceptedAnswers: ["const"] }],
    correctAnswer: { type: "fill_blank", values: { v: "const" } },
    explanation: { short: "as const 让 TS 把字面量类型保留——值不可变 + 字段不可加，类型推导更精确。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 GamePageBackground 是装饰",
    prompt: "GamePageBackground.tsx 大概率渲染什么？",
    options: [
      sc("A", "fixed 定位的背景层（渐变/粒子/网格）——给 game 子页提供一致视觉氛围；与业务数据无关，纯展示组件"),
      sc("B", "数据列表"),
      sc("C", "loader"),
      sc("D", "router"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "*Background 是项目里的「氛围层」组件——纯视觉，无逻辑。" },
    abilityTags: ["code.position.handler"], sourceFilePath: "app/components/game/GamePageBackground.tsx", layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 GamePlatformPage 是包装",
    prompt: "game.$platform.tsx 内 <GamePlatformPage data={data} platformLabel={platformLabel} />——GamePlatformPage 的角色？",
    options: [
      sc("A", "页面级展示组件——接 loader 数据 + 派生的 platformLabel，组装成完整页面 UI；路由文件保持薄（只 loader + 一行 JSX），UI 复杂度封在组件"),
      sc("B", "loader 处理"),
      sc("C", "全局状态"),
      sc("D", "路由配置"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "「路由薄、组件厚」——业务复杂度沉到组件，路由专注数据流转。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: "app/components/game/GamePlatformPage.tsx", layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: ["app/routes/game.$platform.tsx", "app/components/game/GamePlatformPage.tsx"],
  }),
  q({
    type: "single_choice", title: "Q8 platformLabel 派生在路由层",
    prompt: "data.platforms.find(...).name 计算放在 game.$platform.tsx 路由文件而非组件——为什么？",
    options: [
      sc("A", "派生数据小逻辑（一行 find）放路由文件让组件 props 更精确（直接拿到字符串而非自己计算）；测试组件时不用造 platforms 数组只造 string 即可"),
      sc("B", "性能"),
      sc("C", "TypeScript 强制"),
      sc("D", "无差别"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "派生数据「就近 loader」——组件接收已经处理好的 props。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: "app/routes/game.$platform.tsx", layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: ["app/routes/game.$platform.tsx", "app/components/game/GamePlatformPage.tsx"],
  }),
  q({
    type: "single_choice", title: "Q9 路由文件薄的好处",
    prompt: "「路由文件薄、组件文件厚」原则的好处？",
    options: [
      sc("A", "1) 组件可独立测试（不需要 mock loader） 2) 组件可复用到其他路由 3) 路由文件可读性好（一眼看到 loader / meta / links / default export 四块） 4) 组件层不跟 Remix 路由 API 耦合"),
      sc("B", "纯习惯"),
      sc("C", "Remix 强制"),
      sc("D", "TypeScript 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "四点都成立——路由薄是 Remix 项目的常见好实践。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: "app/routes/game.$platform.tsx", layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: ["app/routes/game.$platform.tsx", "app/components/game/GamePlatformPage.tsx"],
  }),
  q({
    type: "single_choice", title: "Q10 GamePageClient.client.tsx 用途",
    prompt: "GamePageClient.client.tsx——什么时候会被 import？",
    options: [
      sc("A", "需要客户端独有 API 的子区段（如 IntersectionObserver / window.scrollY / GSAP timeline / canvas）；用 .client 后缀防止意外打到 server bundle 引发 ReferenceError: window is not defined"),
      sc("B", "Cloudflare 强制"),
      sc("C", "随机"),
      sc("D", "永远不 import"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".client 是「这段代码触碰浏览器 API，server 别跑」的强约束。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: "app/components/game/GamePageClient.client.tsx", layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: ["app/components/game/GamePageClient.client.tsx"],
  }),
  q({
    type: "single_choice", title: "Q11 .client 配合 ClientOnly",
    prompt: "导入 .client 文件时通常配合 <ClientOnly fallback={<Skeleton />}><GamePageClient /></ClientOnly>——为什么？",
    options: [
      sc("A", "ClientOnly 让组件 SSR 阶段渲染 fallback skeleton，hydrate 后才渲染真组件——避免 hydration mismatch（server 和 client 输出不一致触发警告）"),
      sc("B", "性能要求"),
      sc("C", "TypeScript 要求"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ClientOnly = SSR 给占位，CSR 渲真组件——是 .client 文件的标准包装。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: "app/components/game/GamePageClient.client.tsx", layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: ["app/components/game/GamePageClient.client.tsx"],
  }),
  q({
    type: "single_choice", title: "Q12 共享与不共享",
    prompt: "GamePlatformIcons.tsx 不带 .client 后缀——意味着？",
    options: [
      sc("A", "可以在 server 和 client 都安全运行——纯 React JSX，不碰浏览器 API；SSR 输出 SVG HTML，hydrate 后接管交互（虽然图标无交互）"),
      sc("B", "只在 server"),
      sc("C", "只在 client"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "无后缀 = 双端通用——纯 JSX/逻辑组件的常态。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: "app/components/game/GamePlatformIcons.tsx", layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: ["app/components/game/GamePlatformIcons.tsx"],
  }),
  q({
    type: "single_choice", title: "Q13 platformPickerStats 同步函数",
    prompt: "function platformPickerStats(platformId) { ... return { total, completed }; } 同步——能在 server 跑吗？",
    options: [
      sc("A", "能——纯计算，不碰 IO/DOM；SSR 时在 Worker 里跑出 stats 直接渲染 HTML；客户端 hydrate 时再算一次（结果一致）"),
      sc("B", "只 client"),
      sc("C", "只 server"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "纯函数双端通用——SSR + CSR 各算一次结果一致。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 加新组件位置",
    prompt: "新增「游戏成就墙」组件，叫什么名字、放哪？",
    options: [
      sc("A", "components/game/GameAchievementWall.tsx —— 业务前缀 Game + 功能描述 AchievementWall；放 game/ 目录跟同域组件一起"),
      sc("B", "components/AchievementWall.tsx"),
      sc("C", "components/game/wall.tsx"),
      sc("D", "随便放"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "命名 + 位置遵循域分组规则——一致性 = 可维护性。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: "app/components/game/", layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: ["app/components/game/"],
  }),
  q({
    type: "single_choice", title: "Q15 共享 ui 组件来源",
    prompt: "GamePlatformPicker import { GsapFillLink } from '~/components/ui/GsapFillLink'——为什么不放 components/game/？",
    options: [
      sc("A", "GsapFillLink 是跨域通用的「按钮带 GSAP 填充动画」UI 组件——home/cv/messages 等页都用；放 components/ui/ 表「全站通用」；按域分组的边界划在「业务相关 vs UI 通用」"),
      sc("B", "随机"),
      sc("C", "Remix 强制"),
      sc("D", "无差别"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "components/ui/ = 全站通用 UI；components/<domain>/ = 域内业务组件。划线清晰。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/components/ui/GsapFillLink.tsx"],
  }),
  q({
    type: "single_choice", title: "Q16 prefetch=\"intent\" 触发条件",
    prompt: "<Link prefetch=\"intent\" /> 什么事件触发预加载？",
    options: [
      sc("A", "mousedown / focus / touchstart——「用户即将点」的早期信号；vs prefetch=\"render\"（页面渲染时立即预加载，更激进）"),
      sc("B", "mouseover"),
      sc("C", "click"),
      sc("D", "load"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "「intent」= 「打算点」——比 hover 略晚一步，省没真打算点的请求。" },
    abilityTags: ["frontend.event.click", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q17 platforms 是 const",
    prompt: "判断：platforms 数组在 ~/data/game.ts 是 const 字面量，构建时绑定。",
    correctAnswer: { value: true },
    explanation: { short: "对——纯静态数据 import，编译时进 bundle；改了要重新 deploy 才生效。" },
    abilityTags: ["code.position.handler"], sourceFilePath: "app/data/game.ts", layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: ["app/data/game.ts"],
  }),
  q({
    type: "single_choice", title: "Q18 加新平台触及文件清单",
    prompt: "加「Xbox」需要改的文件清单？",
    options: [
      sc("A", "1) types/game.ts 加 PlatformId 'xbox' 2) data/game.ts platforms 加项 + allGamesData['xbox'] 3) GamePlatformIcons.tsx 加 XboxIcon 4) GamePlatformPicker.tsx platformIcons 字典加 xbox: XboxIcon ——4 个文件，全在「数据 + 图标」层，路由 + service 不动"),
      sc("B", "只改 routes"),
      sc("C", "只改 wrangler"),
      sc("D", "改 root"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "动态段路由 + 字典查表 = 加新值改动最小集中。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: "app/components/game/", layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: ["app/types/game.ts", "app/data/game.ts", "app/components/game/GamePlatformIcons.tsx", PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 组件无 client state",
    prompt: "GamePlatformPicker 组件没有 useState/useEffect——为什么？",
    options: [
      sc("A", "纯展示组件，不需要交互状态——所有数据从 import 来，渲染一次就定型；交互（点击 Link）由 React Router 接管，不需要本地 state"),
      sc("B", "性能优化"),
      sc("C", "TypeScript 限制"),
      sc("D", "Cloudflare 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "无状态组件 = 简单组件——React Router 接管交互，业务无 state 需求。" },
    abilityTags: ["frontend.state.local", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q20 用户点 PS 卡片跳转",
    prompt: "用户在 /game 点击 PlayStation 卡片步骤？",
    options: [
      sc("s1", "1. mousedown 触发 prefetch=\"intent\"，浏览器后台加载 /game/playstation 的 loader 数据 + JS chunk"),
      sc("s2", "2. click 事件触发 React Router 拦截"),
      sc("s3", "3. RouteTransition 监听 useNavigation 状态变 \"loading\"，启动幕布盖上"),
      sc("s4", "4. URL pushState 到 /game/playstation"),
      sc("s5", "5. 客户端 loader fetch 已 prefetched 命中缓存，立刻得数据"),
      sc("s6", "6. 渲染 GamePlatformPage，幕布揭开"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6"] },
    explanation: { short: "prefetch + Link 客户端导航 + RouteTransition 幕布——三者协同的丝滑体验。" },
    abilityTags: ["bridge.reactRouter.loader", "frontend.event.click"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/transitions/RouteTransition.tsx"],
  }),
  q({
    type: "single_choice", title: "Q21 SSR 渲染体积",
    prompt: "/game 页 SSR 输出 HTML 主要体积来自？",
    options: [
      sc("A", "1) 内联 SVG 图标（PlayStationIcon/SwitchIcon/PCIcon 各几 KB） 2) Tailwind 类名拼接产生的长 className 3) 3 个平台卡片重复结构——总计几十 KB；可优化：图标提取到外部文件 + className 复用"),
      sc("B", "数据拉取"),
      sc("C", "图片"),
      sc("D", "JS bundle"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SSR HTML 体积 = 内联 SVG + className + DOM 结构——Tailwind 项目的常见瓶颈。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 整体组件设计",
    prompt: "site-07 的「组件目录设计」整体哲学？",
    options: [
      sc("A", "1) 按业务域分目录（game/） 2) UI 通用组件分到 components/ui/ 3) 浏览器独占代码用 .client 后缀显式隔离 4) 路由文件薄、组件文件厚 5) 派生数据在路由层算好后传 props 6) 字典查表代替条件链——综合起来易扩展、易测试、SSR 安全"),
      sc("B", "纯习惯"),
      sc("C", "Remix 强制"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "六条规则全是工程实践——组件层的可维护性来自这些划分。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: "app/components/game/", layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/components/game/GamePlatformPage.tsx", "app/components/game/GamePlatformIcons.tsx", "app/components/game/GamePageClient.client.tsx", "app/components/ui/GsapFillLink.tsx"],
  }),
];
