/**
 * Real questions for site-07-nested-layouts / game-platform.
 * Anchor: remix/app/routes/game.$platform.tsx —— params.platform + isPlatformId 守卫 + JSON_TOKEN_DATA_CACHE_HEADERS
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/game.$platform.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const gamePlatformQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 文件名约定",
    prompt: "Remix v2 flat-routes：让 /game/playstation /game/switch /game/pc 都进同一个文件，文件名是 ____ 。",
    options: [],
    blanks: [{ id: "v", placeholder: "文件名", acceptedAnswers: ["game.$platform.tsx"] }],
    correctAnswer: { type: "fill_blank", values: { v: "game.$platform.tsx" } },
    explanation: { short: "$ 前缀 = 动态参数段；$platform 对应 params.platform。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 params 在哪",
    prompt: "loader 里怎么拿到 URL 段 platform？",
    options: [
      sc("A", "({ params }) => { const platformId = params.platform || \"playstation\"; } —— params 是 LoaderFunctionArgs 第一参的字段"),
      sc("B", "request.url.split('/')"),
      sc("C", "useParams()"),
      sc("D", "context.platform"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "params 由路由系统自动解析；$platform 文件名对应 params.platform。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 默认 fallback",
    prompt: "params.platform || \"playstation\" 这个 || 的意图？",
    options: [
      sc("A", "动态段缺省时给默认值——但这场景下 params.platform 永远存在（路由匹配了才会进来），实际是防御性写法"),
      sc("B", "URL 没匹配时跑这里"),
      sc("C", "TypeScript 强制"),
      sc("D", "Cloudflare 默认"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "防御性 fallback——TS 类型上 params.platform 是 string | undefined，但实际只要路由匹配就有值。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 isPlatformId 守卫",
    prompt: "if (!isPlatformId(platformId)) { throw new Response('Platform not found', { status: 404 }); } 这个守卫意图？",
    options: [
      sc("A", "动态段是 string，但只有 \"playstation\"/\"switch\"/\"pc\" 是合法平台；其它字符串（攻击者乱填）一律 404，避免后续 allGamesData[platformId] 拿到 undefined 崩溃"),
      sc("B", "性能优化"),
      sc("C", "TypeScript 限制"),
      sc("D", "Cloudflare 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "类型守卫 + 早抛 404——loader 入口处验证是 Remix 的标准防御模式。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/game-platform.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q5 isPlatformId 实现",
    prompt: "isPlatformId(s): s is PlatformId 怎么实现的？",
    options: [
      sc("A", "return getValidPlatformId(s) === s; —— getValidPlatformId 把不合法的转成 \"playstation\" 回退；自比对就能判断「原值是否合法」"),
      sc("B", "硬编码 if/else"),
      sc("C", "正则"),
      sc("D", "TypeScript 自动"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "复用既有 getValidPlatformId（用于回退）做类型守卫——一函数两用。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: "app/lib/game-platform.server.ts", layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/game-platform.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q6 throw new Response 与 ErrorBoundary",
    prompt: "loader 里 throw new Response('Platform not found', { status: 404, statusText: 'Platform not found' })——之后的流？",
    options: [
      sc("A", "Remix 框架接住，作为 ErrorResponse 抛到最近的 ErrorBoundary（root 的）；isRouteErrorResponse(error) === true 且 error.status === 404 → 渲染 NotFound404"),
      sc("B", "白屏"),
      sc("C", "重定向到 /"),
      sc("D", "Cloudflare 拦截"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader throw Response = 错误冒泡到 ErrorBoundary；status 决定走哪个分支。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/root.tsx", "app/components/error/NotFound404.tsx"],
  }),
  q({
    type: "fill_blank", title: "Q7 page 参数解析",
    prompt: "const currentPage = parseInt(url.searchParams.get('page') || '1', ____ );",
    options: [],
    blanks: [{ id: "v", placeholder: "数字", acceptedAnswers: ["10"] }],
    correctAnswer: { type: "fill_blank", values: { v: "10" } },
    explanation: { short: "parseInt(value, 10) 显式十进制——避免老旧字符串「08」被当 8 进制解析为 NaN/0。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 URL 拿 query",
    prompt: "loader 里 const url = new URL(request.url); url.searchParams.get('page') 是？",
    options: [
      sc("A", "Web 标准 URL/URLSearchParams API——request 是 Fetch Request；无第三方依赖"),
      sc("B", "Remix 专属"),
      sc("C", "Cloudflare 专属"),
      sc("D", "Node.js 专属"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Web 平台标准 API——Worker 原生支持，所以代码可移植到任何 Web 运行时。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 默认 page=1",
    prompt: "url.searchParams.get('page') || '1' 中的 '1' 是？",
    options: [
      sc("A", "URL 没 ?page=N 时默认第 1 页——保证 parseInt 拿到合法字符串而不是 null"),
      sc("B", "数字 1"),
      sc("C", "boolean"),
      sc("D", "Cloudflare 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "字符串 '1' 喂给 parseInt 得 1；保持类型链一致。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 loader 返回",
    prompt: "loader 最后 return json(await buildGamePlatformData(platformId, currentPage), { headers: JSON_TOKEN_DATA_CACHE_HEADERS }); 返回什么？",
    options: [
      sc("A", "Response 对象（JSON body + Cache-Control: public, max-age=300 + Content-Type: application/json）；React Router 自动 deserialize 给 useLoaderData"),
      sc("B", "纯 JS 对象"),
      sc("C", "Promise"),
      sc("D", "string"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "json() 是 Remix 工具，包成 Response + JSON header；loader 返 Response 是约定。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q11 JSON_TOKEN_DATA_CACHE_HEADERS",
    prompt: "JSON_TOKEN_DATA_CACHE_HEADERS 实际值？",
    options: [
      sc("A", "{ 'Cache-Control': 'public, max-age=300', 'Content-Type': 'application/json' } —— 5 分钟公共缓存"),
      sc("B", "no-store"),
      sc("C", "no-cache"),
      sc("D", "max-age=0"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "5 分钟 CDN 缓存——游戏数据近静态，公共可缓存。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: "app/lib/cache-headers.server.ts", layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q12 forwardLoaderCacheControl",
    prompt: "export const headers: HeadersFunction = forwardLoaderCacheControl; 这行作用？",
    options: [
      sc("A", "Remix v3_singleFetch 模式下 loader 的 Cache-Control 默认不会 forward 到 document 响应；这个 helper 把 loaderHeaders 的 Cache-Control（和 Vary）转写到外层 document Response，让 CDN 真的缓存 HTML"),
      sc("B", "纯样式"),
      sc("C", "Cloudflare 要求"),
      sc("D", "无意义"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "v3_singleFetch 把 loader header 隔离了；要 forward 必须显式 export headers。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: "app/lib/cache-headers.server.ts", layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts"],
  }),
  q({
    type: "true_false", title: "Q13 缺 export headers 后果",
    prompt: "判断：删除 export const headers = forwardLoaderCacheControl; 后，document 响应仍带 Cache-Control。",
    correctAnswer: { value: false },
    explanation: { short: "错——v3_singleFetch 下 document Response 默认不继承 loader header；删了 → 浏览器 + CDN 不缓存 HTML（每次回源）。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q14 meta 函数读 loader data",
    prompt: "meta: MetaFunction<typeof loader> = ({ data }) => { ... } 中的 data 是？",
    options: [
      sc("A", "loader return 的 JSON 反序列化结果（包含 platforms / platformId / paginatedGames 等）；TypeScript 自动从 typeof loader 推出类型"),
      sc("B", "随机"),
      sc("C", "null"),
      sc("D", "undefined"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "MetaFunction<typeof loader> 是 Remix 的类型联动——meta 自动拿到 loader 数据类型。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 meta data 为 null 兜底",
    prompt: "if (!data) { return [{ title: '游戏中心 - 未找到' }, ...]; } 什么时候触发？",
    options: [
      sc("A", "loader 抛错时，meta 拿到的 data 是 undefined；这分支提供错误页 fallback title，避免 SEO 看到空白"),
      sc("B", "永不触发"),
      sc("C", "loader 成功也触发"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader fail → ErrorBoundary 渲染时，meta 仍跑但 data=undefined；fallback 必要。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "fill_blank", title: "Q16 platformLabel 计算",
    prompt: 'data.platforms.find((platform) => platform.____  === data.platformId)?.name',
    options: [],
    blanks: [{ id: "v", placeholder: "字段", acceptedAnswers: ["id"] }],
    correctAnswer: { type: "fill_blank", values: { v: "id" } },
    explanation: { short: "platforms 数组按 id 查找当前平台元数据，?.name 安全取 name；fallback 是 platformId 本身。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 links: 注入 stylesheet",
    prompt: "export const links: LinksFunction = () => [{ rel: 'stylesheet', href: gameStyles }]; 作用？",
    options: [
      sc("A", "声明本路由依赖的 CSS（gameStyles 是 ?url import 的 CSS 路径）；Remix 根据匹配的路由树在 root 的 <Links /> 里插对应 <link rel=\"stylesheet\">"),
      sc("B", "懒加载图片"),
      sc("C", "preload JS"),
      sc("D", "Cloudflare 缓存"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "路由级 CSS 关联——只在该路由生效，避免全站包大。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q18 访问 /game/playstation?page=2",
    prompt: "用户访问 /game/playstation?page=2 步骤？",
    options: [
      sc("s1", "1. Worker 接到 GET /game/playstation?page=2"),
      sc("s2", "2. 路由匹配 game.tsx + game.$platform.tsx，params.platform=\"playstation\""),
      sc("s3", "3. loader 跑：url.searchParams.get('page')='2' → currentPage=2"),
      sc("s4", "4. isPlatformId('playstation') → true，不抛 404"),
      sc("s5", "5. await buildGamePlatformData('playstation', 2) 取第 2 页 8 个游戏"),
      sc("s6", "6. return json(...) with Cache-Control max-age=300"),
      sc("s7", "7. 渲染 GameLayout → Outlet → GamePlatformRoute → GamePlatformPage"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7"] },
    explanation: { short: "动态段 + query + loader + 渲染——经典 Remix 数据路由流程。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/lib/game-platform.server.ts"],
  }),
  q({
    type: "branch_trace", title: "Q19 访问 /game/xbox（不存在）",
    prompt: "用户访问 /game/xbox 步骤？",
    options: [
      sc("s1", "1. 路由匹配 game.$platform.tsx，params.platform=\"xbox\""),
      sc("s2", "2. loader 跑 isPlatformId(\"xbox\") → false"),
      sc("s3", "3. throw new Response('Platform not found', { status: 404 })"),
      sc("s4", "4. 框架捕获 ErrorResponse，冒泡到 root ErrorBoundary"),
      sc("s5", "5. isRouteErrorResponse(error) && error.status === 404 → 渲染 NotFound404"),
      sc("s6", "6. didError 不翻 true（boundary 处理了），entry.server 输出 status 404"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6"] },
    explanation: { short: "loader 守卫 throw 404 → ErrorBoundary 接 → NotFound404 渲染。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/root.tsx", "app/components/error/NotFound404.tsx", "app/entry.server.tsx"],
  }),
  q({
    type: "single_choice", title: "Q20 path traversal 防护",
    prompt: "如果 isPlatformId 守卫被删，攻击者访问 /game/../../etc/passwd 会怎样？",
    options: [
      sc("A", "URL 路由系统已经把段标准化（编码后是普通字符串「..」），不会真的访问文件系统；但 allGamesData[\"..\"] 返回 undefined → buildGamePlatformData 内崩溃 500——所以守卫还是必要的「行为正确性」防御"),
      sc("B", "Worker 自动屏蔽"),
      sc("C", "TypeScript 阻止"),
      sc("D", "重定向"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Worker 没有文件系统所以不存在 path traversal；守卫防的是「数据找不到导致崩溃」。" },
    abilityTags: ["ai.review.architecture", "backend.auth.required"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 useLoaderData 类型",
    prompt: "useLoaderData<typeof loader>() 返回类型？",
    options: [
      sc("A", "loader return 的 json(...) body 反序列化后的类型——Remix 把 typeof loader 推出来；这里有 platforms / paginatedGames / followedGames 等"),
      sc("B", "Response 对象"),
      sc("C", "any"),
      sc("D", "Promise"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "<typeof loader> 是 Remix 的类型联动——拿到精确反序列化类型。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "position_judgement", title: "Q22 加 ?sort=rating 参数",
    prompt: "新增 ?sort=rating 参数让用户按评分排序。落点？",
    options: [
      sc("A", "loader 内 const sort = url.searchParams.get('sort') ?? 'progress'; 把 sort 透传给 buildGamePlatformData(platformId, currentPage, sort)；service 层在 sortGamesByProgressAndRating 里按 sort 切换比较函数"),
      sc("B", "改前端组件"),
      sc("C", "改 wrangler"),
      sc("D", "新文件"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "URL 参数解析在 loader 入口，业务逻辑在 service——分层落位清晰。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/lib/game-platform.server.ts", "app/lib/utils/gameUtils.ts"],
  }),
];
