/**
 * Real questions for site-07-nested-layouts / game-index.
 * Anchor: remix/app/routes/game._index.tsx —— 9 行：MetaFunction + GamePlatformPicker
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/game._index.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const gameIndexQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 文件名约定",
    prompt: "Remix v2 flat-routes：访问 /game（无后缀）时渲染的文件名是 ____ 。",
    options: [],
    blanks: [{ id: "v", placeholder: "文件名", acceptedAnswers: ["game._index.tsx"] }],
    correctAnswer: { type: "fill_blank", values: { v: "game._index.tsx" } },
    explanation: { short: "_index 是「父路由的默认子」约定；URL /game = game.tsx 父 + game._index.tsx 子。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 GameIndexRoute body",
    prompt: "GameIndexRoute 函数体？",
    options: [
      sc("A", "return <GamePlatformPicker />;"),
      sc("B", "return <Outlet />;"),
      sc("C", "return <></>;"),
      sc("D", "return <iframe />;"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "_index 路由 = 一个完整页面组件，不需要 Outlet（_index 是叶子）。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 meta 函数返回",
    prompt: 'export const meta: MetaFunction = () => pageMeta.game(); 这种写法的好处？',
    options: [
      sc("A", "把所有页面的 meta 集中在 utils/seo.ts 的 pageMeta 对象，路由文件只引用——SEO 改动一处生效；命名空间避免重复 title 冲突"),
      sc("B", "纯历史"),
      sc("C", "Remix 强制"),
      sc("D", "TypeScript 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "集中式 SEO 配置——单点修改，规模化维护。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/utils/seo.ts"],
  }),
  q({
    type: "single_choice", title: "Q4 没有 loader",
    prompt: "GameIndexRoute 没 export loader——为什么？",
    options: [
      sc("A", "GamePlatformPicker 用的数据（platforms / allGamesData）都来自 ~/data/game 静态导入，构建时已绑定，运行时不需要 loader 拉数据"),
      sc("B", "忘了写"),
      sc("C", "Cloudflare 不允许"),
      sc("D", "TypeScript 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "静态数据 = 模块导入；动态数据 = loader。区分清楚是性能要点。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/components/game/GamePlatformPicker.tsx"],
  }),
  q({
    type: "true_false", title: "Q5 _index 与 layout 共存",
    prompt: "判断：访问 /game 时，game.tsx (layout) + game._index.tsx (子) 都会渲染。",
    correctAnswer: { value: true },
    explanation: { short: "对——layout + _index 都是嵌套层级的一部分；layout 渲染外壳，_index 通过 Outlet 渲染。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game.tsx"],
  }),
  q({
    type: "single_choice", title: "Q6 _index vs $platform 优先级",
    prompt: "访问 /game 时，Remix 是匹配 _index 还是 $platform？",
    options: [
      sc("A", "_index——动态段 $platform 需要至少一段 URL（/game/x），而 /game 后无段，所以匹配 _index"),
      sc("B", "$platform"),
      sc("C", "都匹配，渲染两次"),
      sc("D", "随机选"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "/game 没多余段 → _index；/game/pc 有 pc → $platform。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game.$platform.tsx"],
  }),
  q({
    type: "single_choice", title: "Q7 删除 _index 后果",
    prompt: "如果删除 game._index.tsx，访问 /game 会怎样？",
    options: [
      sc("A", "渲染 game.tsx 的 GameLayout（只有空 Outlet），用户看到空白——layout 没默认子可填，Outlet 啥也没插入"),
      sc("B", "404"),
      sc("C", "重定向"),
      sc("D", "随机选 $platform"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "_index 是「父 layout 的默认填充」；没了就 Outlet 空。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game.tsx"],
  }),
  q({
    type: "single_choice", title: "Q8 _index 与 default redirect",
    prompt: "想把 /game 默认跳到 /game/playstation。怎么做？",
    options: [
      sc("A", "game._index.tsx 加 export const loader = () => redirect('/game/playstation'); —— loader 抛 redirect = 框架直接 302，组件函数不会渲染"),
      sc("B", "改 game.tsx"),
      sc("C", "wrangler 重定向"),
      sc("D", "useEffect 跳"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "_index loader return redirect 是 Remix 标准重定向方式——SSR 阶段直接 302。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 GamePlatformPicker 数据来源",
    prompt: "GamePlatformPicker 内 import { userStats, platforms, allGamesData, followedGames } from '~/data/game'; 这是？",
    options: [
      sc("A", "构建时静态绑定的硬编码数据；游戏数量、成就等改动需要重新部署；优点：零运行时开销，CDN 全缓存"),
      sc("B", "运行时 fetch"),
      sc("C", "D1 查询"),
      sc("D", "用户私有数据"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "静态数据嵌入 bundle——适合「不常改、所有人看到一样」的内容。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: "app/components/game/GamePlatformPicker.tsx", layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/data/game.ts"],
  }),
  q({
    type: "single_choice", title: "Q10 Picker 内 GsapFillLink",
    prompt: "<GsapFillLink to=\"/\" /> 「返回首页」按钮——为什么不直接用 <Link>？",
    options: [
      sc("A", "GsapFillLink 是项目自定义，包了 React Router Link + GSAP hover 填充动画；保留 Link 的客户端导航优势同时加视觉细节"),
      sc("B", "Link 不支持"),
      sc("C", "Cloudflare 限制"),
      sc("D", "TypeScript 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "封装：标准 Link + 视觉装饰；项目里大量复用。" },
    abilityTags: ["frontend.event.click", "code.position.handler"],
    sourceFilePath: "app/components/game/GamePlatformPicker.tsx", layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/ui/GsapFillLink.tsx"],
  }),
  q({
    type: "true_false", title: "Q11 prefetch=\"intent\"",
    prompt: "判断：<Link to=`/game/${platform.id}` prefetch=\"intent\">——hover/touch 时预加载该路由资源。",
    correctAnswer: { value: true },
    explanation: { short: "对——prefetch=\"intent\" 是 React Router/Remix 性能优化：用户「打算点」时就开始拉资源。" },
    abilityTags: ["bridge.reactRouter.loader", "frontend.event.click"],
    sourceFilePath: "app/components/game/GamePlatformPicker.tsx", layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 platformPickerStats 计算时机",
    prompt: "function platformPickerStats(platformId) { return { total, completed }; } 这个函数什么时候执行？",
    options: [
      sc("A", "组件渲染时同步执行——SSR 时在 Worker 里跑算 total/completed，输出到 HTML；客户端 hydrate 时再算一次（结果相同）"),
      sc("B", "只在客户端"),
      sc("C", "构建时"),
      sc("D", "懒加载"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "渲染期同步函数；SSR + 客户端各一次但结果一致。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: "app/components/game/GamePlatformPicker.tsx", layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/components/game/GamePlatformPicker.tsx"],
  }),
  q({
    type: "single_choice", title: "Q13 platforms.map 渲染卡片",
    prompt: "{platforms.map((platform) => { const Icon = platformIcons[platform.id]; ... })} 渲染——key 用什么？",
    options: [
      sc("A", "key={platform.id} —— 唯一稳定 id，是 React 列表 key 的最佳实践"),
      sc("B", "key={index}"),
      sc("C", "不需要 key"),
      sc("D", "key={Math.random()}"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "稳定唯一 id 是 key 首选；index 在重排时会触发不必要重渲染。" },
    abilityTags: ["frontend.state.local"], sourceFilePath: "app/components/game/GamePlatformPicker.tsx", layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 SSR 输出体积",
    prompt: "/game 页 SSR 输出 HTML 体积主要由什么决定？",
    options: [
      sc("A", "platforms 数组长度（3 个：playstation/switch/pc）× 每个卡片的 DOM 节点数 + 头部 + 底部；图标 SVG 内联进 HTML（PlayStationIcon 等）"),
      sc("B", "用户多少"),
      sc("C", "图片体积"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "SSR HTML 体积 = 组件输出节点 × 数据量；图标内联是体积大头之一。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/components/game/GamePlatformPicker.tsx"],
  }),
  q({
    type: "single_choice", title: "Q15 _index 加 loader",
    prompt: "想给 /game 加「最近上线游戏」动态区，loader 落点？",
    options: [
      sc("A", "game._index.tsx 加 export const loader = async ({ context }) => { return json(...) }; 不影响 game.$platform.tsx 子路由的 loader"),
      sc("B", "改 game.tsx (layout)"),
      sc("C", "改 root.tsx"),
      sc("D", "改 entry.server"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "_index 是「/game 默认页」的专属位置；加 loader 不影响兄弟路由。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 命名约定 _index 而非 index",
    prompt: "Remix v2 flat-routes 文件名是 game._index.tsx 不是 game.index.tsx——下划线作用？",
    options: [
      sc("A", "下划线开头表示「特殊命名」不当作 URL 段；如果叫 game.index.tsx 框架会把它解析成 /game/index 路径"),
      sc("B", "纯命名习惯"),
      sc("C", "TypeScript 限制"),
      sc("D", "Cloudflare 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "_前缀 = flat-routes 的「不当作路径段」标记；用于 _index、_layout 等。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q17 用户访问 /game 完整流程",
    prompt: "用户首次访问 https://wangjiajun.asia/game 步骤？",
    options: [
      sc("s1", "1. 浏览器请求 GET /game"),
      sc("s2", "2. Cloudflare Worker 接收，调 entry.server handleRequest"),
      sc("s3", "3. Remix 路由匹配 root → game.tsx → game._index.tsx"),
      sc("s4", "4. 跑 game._index.tsx 的 meta() → pageMeta.game() 返回 title 数组"),
      sc("s5", "5. SSR 渲染 GameIndexRoute → GamePlatformPicker"),
      sc("s6", "6. 流式输出 HTML 给浏览器，浏览器开始展示"),
      sc("s7", "7. JS bundle 加载完，hydrate 接管交互（hover 触发 prefetch）"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7"] },
    explanation: { short: "完整 SSR + hydration 链——从 HTTP 请求到可交互。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/entry.server.tsx", "app/components/game/GamePlatformPicker.tsx"],
  }),
  q({
    type: "single_choice", title: "Q18 _index 也能 export action",
    prompt: "_index 路由能 export action 吗？",
    options: [
      sc("A", "能——_index 跟普通路由一样支持 loader/action/ErrorBoundary 全部约定；可以做 /game POST 提交"),
      sc("B", "只能 loader"),
      sc("C", "都不能"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "_index 是「正常路由」加上「URL 无后缀时匹配」属性；export 约定一致。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q19 Picker 不需要 useLoaderData",
    prompt: "判断：GamePlatformPicker 内不需要 useLoaderData——因为路由没 loader。",
    correctAnswer: { value: true },
    explanation: { short: "对——没 loader 时调 useLoaderData() 返回 undefined，硬调反而误导；当前文件用静态 import 拿数据。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/components/game/GamePlatformPicker.tsx"],
  }),
  q({
    type: "position_judgement", title: "Q20 加「我的统计」区到 /game 首页",
    prompt: "想给 /game 加「累计成就 X 个」统计卡片。落点？",
    options: [
      sc("A", "改 GamePlatformPicker.tsx——它就是 /game 的展示组件；统计逻辑用现成的 userStats 数据，加一个 stats card 区段"),
      sc("B", "新建 game._index.stats.tsx"),
      sc("C", "改 game.tsx layout"),
      sc("D", "改 root.tsx"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Picker 已经是 /game 的页面组件——加视觉区段就在它里面，路由结构不动。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client",
    touchedFiles: ["app/components/game/GamePlatformPicker.tsx"],
  }),
  q({
    type: "single_choice", title: "Q21 SSR 性能",
    prompt: "/game 页 SSR 时间贡献最大的是？",
    options: [
      sc("A", "GamePlatformPicker 内 platforms.map 的渲染计算（包括 platformPickerStats 调用 + Icon 组件查表 + 多层 className 拼接）；data 是静态导入，没 IO"),
      sc("B", "loader 数据库查询"),
      sc("C", "图片 fetch"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "无 IO 时 SSR 瓶颈是组件渲染计算——map 越多越慢。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/components/game/GamePlatformPicker.tsx"],
  }),
  q({
    type: "single_choice", title: "Q22 _index 整体定位",
    prompt: "site-07 中 game._index.tsx 的整体定位？",
    options: [
      sc("A", "嵌套路由的「默认子页」——URL /game 落地这里；纯展示路由（无 loader / action），数据从 ~/data/game 静态来；与 game.$platform.tsx 平级，共享 game.tsx layout"),
      sc("B", "只是占位"),
      sc("C", "随机"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "_index 在嵌套路由里是「第一个子页」——URL 无后缀时的归宿。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game.tsx", "app/routes/game.$platform.tsx"],
  }),
];
