/**
 * Real questions for site-07-nested-layouts / game-loader.
 * Anchor: remix/app/routes/game.$platform.tsx loader + remix/app/lib/game-platform.server.ts buildGamePlatformData
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/game.$platform.tsx";
const SERVICE = "app/lib/game-platform.server.ts";
const sc = (id: string, text: string) => ({ id, text });

export const gameLoaderQuestions: RealQ[] = [
  q({
    type: "single_choice", title: "Q1 loader 返回内容",
    prompt: "buildGamePlatformData 返回对象包含哪些字段？",
    options: [
      sc("A", "userStats / platforms / platformId / paginatedGames / totalGames / totalPages / currentPage / followedGames / avatarImageUrl"),
      sc("B", "只 paginatedGames"),
      sc("C", "随机"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader 一次性给齐前端要的所有数据——避免子组件再发请求；典型 Remix 思路。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: SERVICE, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, SERVICE],
  }),
  q({
    type: "single_choice", title: "Q2 sortGamesByProgressAndRating",
    prompt: "buildGamePlatformData 第一步：const sortedGames = sortGamesByProgressAndRating(allGamesData[platformId]); 排序意图？",
    options: [
      sc("A", "把游戏先按 progress（已完成度）后按 rating（评分）排序——展示「正在玩 + 高分」靠前，UX 优先级"),
      sc("B", "按字母"),
      sc("C", "按时间"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "复合排序——业务语义优先级嵌入 utility 函数。" },
    abilityTags: ["code.position.handler"], sourceFilePath: SERVICE, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, SERVICE, "app/lib/utils/gameUtils.ts"],
  }),
  q({
    type: "fill_blank", title: "Q3 分页大小",
    prompt: "const paginationResult = paginateGames(sortedGames, currentPage, ____ );",
    options: [],
    blanks: [{ id: "v", placeholder: "每页数量", acceptedAnswers: ["8"] }],
    correctAnswer: { type: "fill_blank", values: { v: "8" } },
    explanation: { short: "硬编码 8——可改成常量提取，但目前简单实用。" },
    abilityTags: ["code.position.handler"], sourceFilePath: SERVICE, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [SERVICE],
  }),
  q({
    type: "single_choice", title: "Q4 paginateGames 返回",
    prompt: "paginateGames 返回 { paginatedGames, totalGames, totalPages, currentPage } 这种 shape 的好处？",
    options: [
      sc("A", "前端展示分页器需要的元数据全在 loader 输出里——currentPage（用户在哪）、totalPages（总页）、totalGames（总数）；不需要前端再算"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare 要求"),
      sc("D", "TypeScript 强制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "把分页元数据下放到 server——前端只渲染，不算。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: SERVICE, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [SERVICE],
  }),
  q({
    type: "single_choice", title: "Q5 resolveR2Image 注入",
    prompt: "paginatedGames.map((game) => ({ ...game, cover: resolveR2Image(game.cover) })) 这步意图？",
    options: [
      sc("A", "把 game.cover 从相对路径（如 'game/zelda.jpg'）解析成 CDN 完整 URL（https://cdn.xn--cckl9nsb.com/game/zelda.jpg.{hash}）；前端拿到就能直接用"),
      sc("B", "懒加载"),
      sc("C", "图片压缩"),
      sc("D", "纯加密"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader 内做 URL 解析——前端拿到的是「可直接用」的完整 URL，无需再调用 helper。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: SERVICE, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [SERVICE, "app/lib/resolve-image.ts"],
  }),
  q({
    type: "single_choice", title: "Q6 followedGames 同样处理",
    prompt: "followedGames.map(...resolveR2Image(game.cover)...) 也做了一次。重复在哪？",
    options: [
      sc("A", "paginatedGames 和 followedGames 是两个独立数组（一个分页内，一个用户关注列表），各自需要独立 cover URL 解析；没法 dedup，因为它们是不同的「游戏组合」"),
      sc("B", "纯重复 bug"),
      sc("C", "性能浪费"),
      sc("D", "TypeScript 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "两个独立列表 → 各自映射——不算重复，是两个不同的视图数据源。" },
    abilityTags: ["code.position.handler"], sourceFilePath: SERVICE, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [SERVICE],
  }),
  q({
    type: "single_choice", title: "Q7 avatarImageUrl",
    prompt: "avatarImageUrl: resolveR2Image('game/jkl.jpg') 是？",
    options: [
      sc("A", "用户头像图片的 CDN URL——硬编码 jkl.jpg 表示固定头像；loader 一次给前端，避免前端再调 resolveR2Image"),
      sc("B", "随机头像"),
      sc("C", "用户上传"),
      sc("D", "Cloudflare 默认"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "硬编码个人头像——单用户站点的常见简化。" },
    abilityTags: ["code.position.handler"], sourceFilePath: SERVICE, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [SERVICE, "app/lib/resolve-image.ts"],
  }),
  q({
    type: "true_false", title: "Q8 .server.ts 后缀",
    prompt: "判断：游戏数据组装的 game-platform.server.ts 文件名加 .server 后缀是 Remix 约定。",
    correctAnswer: { value: true },
    explanation: { short: "对——.server.ts 标记「永不打到客户端 bundle」；构建时验证不让客户端代码 import 它。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: SERVICE, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [SERVICE],
  }),
  q({
    type: "single_choice", title: "Q9 buildGamePlatformData 是 async 但没 await",
    prompt: "为什么 buildGamePlatformData 写 async 但内部没 await？",
    options: [
      sc("A", "保留接口异步——以后可能加 await db.query / await fetch；现在所有数据来自静态 import 不需要 await，但保留 async 让 caller 可以一致使用 await"),
      sc("B", "TypeScript 强制"),
      sc("C", "性能要求"),
      sc("D", "Cloudflare 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "async 接口前瞻——为未来加异步留口子，现在零代价。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: SERVICE, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [SERVICE],
  }),
  q({
    type: "single_choice", title: "Q10 loader 内 await",
    prompt: "loader 写 return json(await buildGamePlatformData(...))——await 必要吗？",
    options: [
      sc("A", "必要——buildGamePlatformData 返回 Promise（async 函数即使没 await 也返 Promise）；不 await 则 json 把 Promise 当值序列化输出 {} 给客户端"),
      sc("B", "不必要"),
      sc("C", "TypeScript 强制"),
      sc("D", "纯习惯"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Promise.then = await——传给 json 必须先解开。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, SERVICE],
  }),
  q({
    type: "single_choice", title: "Q11 isPlatformId 是 type predicate",
    prompt: "function isPlatformId(s: string): s is PlatformId { ... } 中 's is PlatformId' 是？",
    options: [
      sc("A", "TypeScript 类型谓词——返回 true 时编译器把 s 的类型从 string 收窄到 PlatformId；后续访问 allGamesData[s] 不再类型错"),
      sc("B", "运行时检查"),
      sc("C", "instanceof"),
      sc("D", "纯注释"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "type predicate 是 TS 关键特性——把 runtime check 提升为 compile-time 类型收窄。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: SERVICE, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [SERVICE],
  }),
  q({
    type: "single_choice", title: "Q12 getValidPlatformId 双用",
    prompt: "getValidPlatformId 同时用于「fallback 到默认 playstation」和「isPlatformId 守卫」——这种「一函数两用」？",
    options: [
      sc("A", "巧妙——fallback: getValidPlatformId(any) 永远返合法；guard: getValidPlatformId(x) === x 表示 x 本身合法。一段判定逻辑两个语义"),
      sc("B", "代码气味"),
      sc("C", "强制重写"),
      sc("D", "Cloudflare 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "「值变换函数」自比对 = 「值合法性判定」——精巧的 utility 复用。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: SERVICE, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [SERVICE],
  }),
  q({
    type: "single_choice", title: "Q13 错误页 status",
    prompt: "throw new Response('Platform not found', { status: 404, statusText: 'Platform not found' })——statusText 显示在哪？",
    options: [
      sc("A", "HTTP 响应行（如 \"HTTP/1.1 404 Platform not found\"）；浏览器开发者工具 Network 面板能看到；ErrorBoundary 也能通过 error.statusText 拿到"),
      sc("B", "页面 body"),
      sc("C", "console"),
      sc("D", "TypeScript 类型"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "statusText 是 HTTP 协议字段——给程序看，不给用户看。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q14 完整 loader 流",
    prompt: "loader 跑 /game/playstation?page=1 完整步骤？",
    options: [
      sc("s1", "1. ({ params, request }) 解构入参"),
      sc("s2", "2. const url = new URL(request.url) 解析 URL"),
      sc("s3", "3. const platformId = params.platform || 'playstation' = 'playstation'"),
      sc("s4", "4. const currentPage = parseInt('1', 10) = 1"),
      sc("s5", "5. isPlatformId('playstation') === true，跳过 throw 404"),
      sc("s6", "6. await buildGamePlatformData('playstation', 1) 算分页 + 排序 + URL 解析"),
      sc("s7", "7. return json(data, { headers: JSON_TOKEN_DATA_CACHE_HEADERS })"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7"] },
    explanation: { short: "loader 标准流：解参 → 守卫 → 业务 → 包装 Response。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, SERVICE],
  }),
  q({
    type: "single_choice", title: "Q15 loader 错误处理",
    prompt: "如果 buildGamePlatformData 内崩了 throw new Error('boom')，loader 行为？",
    options: [
      sc("A", "Error 冒泡出 loader → React Router 包成 ErrorResponse → root ErrorBoundary 接住，渲染 RouteErrorBoundary（非 404 分支）；entry.server didError 翻 true → status 500"),
      sc("B", "白屏"),
      sc("C", "Worker 崩"),
      sc("D", "返回空"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader 抛 Error → boundary 接 → 500。这是 Remix 错误兜底链。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/root.tsx", "app/entry.server.tsx"],
  }),
  q({
    type: "single_choice", title: "Q16 loader 与 useLoaderData 数据流",
    prompt: "loader return json(data) → useLoaderData<typeof loader>() 拿到 data 的过程？",
    options: [
      sc("A", "SSR 时：loader 在 Worker 跑，返 Response 同时把 data 序列化到 HTML 内嵌 script；hydrate 后 useLoaderData() 直接读这块预填数据，不需要再请求；客户端导航时：loader 通过 .data fetch 拿，序列化反序列化一次"),
      sc("B", "始终客户端 fetch"),
      sc("C", "始终 SSR"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix 数据双轨：SSR 内嵌 + CSR fetch。useLoaderData 是「读内嵌数据」的入口。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 max-age=300 vs no-store",
    prompt: "JSON_TOKEN_DATA_CACHE_HEADERS 选 public, max-age=300 而非 no-store，权衡？",
    options: [
      sc("A", "游戏列表近静态——5 分钟内 CDN 复用同一份给多用户，省 Worker invocation；缺点：新增/修改游戏后要 5 分钟才看到（可接受，单用户站点）"),
      sc("B", "纯习惯"),
      sc("C", "性能要求强制"),
      sc("D", "Cloudflare 限制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "缓存粒度选择：业务容忍度 vs 成本。5 分钟是 sweet spot。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: "app/lib/cache-headers.server.ts", layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts"],
  }),
  q({
    type: "true_false", title: "Q18 loader 不能用 useState",
    prompt: "判断：loader 函数体内不能用 useState/useEffect。",
    correctAnswer: { value: true },
    explanation: { short: "对——loader 是 server function，跑在 Worker；React hooks 是组件运行时的概念，loader 里调直接报错。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 加 D1 查询",
    prompt: "如果 buildGamePlatformData 改成从 D1 拉游戏列表，怎么访问 D1？",
    options: [
      sc("A", "loader 里 ({ context }) 解构，context.cloudflare.env.DB.prepare(...) ；buildGamePlatformData 接受 db 作为新参数"),
      sc("B", "在组件里查"),
      sc("C", "wrangler.toml 配置"),
      sc("D", "context 全局"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Cloudflare bindings 通过 context.cloudflare.env 拿——loader 是入口。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, SERVICE],
  }),
  q({
    type: "single_choice", title: "Q20 loader 时序（多 loader 并发）",
    prompt: "Remix 在 SSR 时怎么调用嵌套路由的 loader？",
    options: [
      sc("A", "并发——root loader / game.tsx loader / game.$platform.tsx loader 同时跑（如果都有）；并发 settle 后再渲染组件树；这就是「不存在 N+1 瀑布」的由来"),
      sc("B", "串行"),
      sc("C", "随机"),
      sc("D", "只跑叶子"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix 关键性能特性——loader 并行启动。这是 vs 老 React 客户端瀑布的核心改进。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/routes/game.tsx"],
  }),
  q({
    type: "position_judgement", title: "Q21 加平台徽章",
    prompt: "想给每个 game 卡片加「白金奖杯数」徽章。loader 落点？",
    options: [
      sc("A", "改 buildGamePlatformData 内 paginatedGames.map 时多塞一个 platinumCount 字段；前端组件读 game.platinumCount 直接渲染——不动 loader 入口"),
      sc("B", "改前端组件"),
      sc("C", "新加 loader"),
      sc("D", "wrangler 改"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "数据装配在 service 层加字段——前端只渲染。这是「loader 给齐」的扩展。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: SERVICE, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [SERVICE, PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 整体 loader 设计",
    prompt: "「game.$platform.tsx loader 的整体设计哲学」？",
    options: [
      sc("A", "1) 入口验参（isPlatformId 守卫早抛 404） 2) 业务装配在 service .server.ts 层（buildGamePlatformData） 3) 资源 URL 在 server 端解析（resolveR2Image） 4) 缓存通过 forwardLoaderCacheControl 透回 document 5) loader 一次性给齐前端要的所有数据——前端零额外请求"),
      sc("B", "纯路由"),
      sc("C", "随机"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "守卫 + service + URL 解析 + 缓存 + 一次给齐——Remix loader 的标准范式。" },
    abilityTags: ["ai.review.architecture", "code.position.handler", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, SERVICE, "app/lib/cache-headers.server.ts", "app/lib/resolve-image.ts"],
  }),
];
