/**
 * Real questions for site-07-nested-layouts / game-layout.
 * Anchor: remix/app/routes/game.tsx —— 仅 5 行：import Outlet → export default function GameLayout { <Outlet /> }
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/game.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const gameLayoutQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 game.tsx 唯一 import",
    prompt: 'import { ____ } from "@remix-run/react";',
    options: [],
    blanks: [{ id: "v", placeholder: "组件名", acceptedAnswers: ["Outlet"] }],
    correctAnswer: { type: "fill_blank", values: { v: "Outlet" } },
    explanation: { short: "父 layout 路由唯一职责就是渲染 <Outlet /> 占位子路由。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 GameLayout 全部代码",
    prompt: "GameLayout 函数体完整代码是？",
    options: [
      sc("A", "return <Outlet />;"),
      sc("B", "return <div><Outlet /></div>;"),
      sc("C", "return null;"),
      sc("D", "return <header /><Outlet />;"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "极简 5 行——layout 没有视觉外壳，只是路由结构上的「父节点」。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 为什么需要 game.tsx 这个空 layout",
    prompt: "既然 GameLayout 啥也没干（只渲染 Outlet），为什么 Remix v2 还要这个文件？",
    options: [
      sc("A", "Remix v2 的 flat-routes 约定：要让 game._index.tsx + game.$platform.tsx 共享父路由分段，必须有 game.tsx 文件名作为父；删了它两个子路由就成了平级"),
      sc("B", "纯历史包袱"),
      sc("C", "TypeScript 要求"),
      sc("D", "Cloudflare 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "flat-routes 用文件名点分段表达嵌套——game.tsx 是结构上的「父」，即使 UI 是空的。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game._index.tsx", "app/routes/game.$platform.tsx"],
  }),
  q({
    type: "single_choice", title: "Q4 删了 game.tsx 后果",
    prompt: "如果删除 game.tsx，访问 /game/playstation 会怎样？",
    options: [
      sc("A", "依然工作——Remix flat-routes 在缺父 layout 时把 game.$platform.tsx 直接挂在 root 下；只是失去「未来在父层加共享 UI/loader」的扩展点"),
      sc("B", "404"),
      sc("C", "500"),
      sc("D", "重定向到 /"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix 容忍缺父；保留空 layout 是为「以后能加共享 UI」留口子。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q5 Outlet 接受 props",
    prompt: "判断：<Outlet /> 可以接受 context prop 给所有子路由共享数据。",
    correctAnswer: { value: true },
    explanation: { short: "对——<Outlet context={value} /> 让子路由 useOutletContext() 拿；这是「父 layout 给子」的标准方式。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 父 layout 加 loader",
    prompt: "想给 /game/* 所有子路由共享一个「我的成就总数」数据，怎么做？",
    options: [
      sc("A", "game.tsx 加 export const loader = async () => json({ totalAchievements: ... }); 子路由用 useRouteLoaderData('routes/game') 拿"),
      sc("B", "每个子路由各自 loader"),
      sc("C", "全局 store"),
      sc("D", "url query"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "父 layout 的 loader 是「子路由共享数据」的天然位置，避免重复请求。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "branch_trace", title: "Q7 访问 /game 渲染步骤",
    prompt: "用户访问 /game 触发的步骤？",
    options: [
      sc("s1", "1. Remix 路由匹配 routes/game.tsx (父) + routes/game._index.tsx (子)"),
      sc("s2", "2. 调用父 game.tsx 的 loader（无）"),
      sc("s3", "3. 调用 game._index.tsx 的 loader（无）"),
      sc("s4", "4. 渲染 root → Layout → GameLayout"),
      sc("s5", "5. GameLayout 内 <Outlet /> 占位"),
      sc("s6", "6. Outlet 处渲染 GameIndexRoute → GamePlatformPicker"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6"] },
    explanation: { short: "嵌套路由的 SSR 步骤：父 loader → 子 loader → 父组件 → Outlet → 子组件。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game._index.tsx"],
  }),
  q({
    type: "branch_trace", title: "Q8 访问 /game/pc 渲染步骤",
    prompt: "用户访问 /game/pc 步骤？",
    options: [
      sc("s1", "1. Remix 匹配 game.tsx + game.$platform.tsx，params.platform=\"pc\""),
      sc("s2", "2. 父 loader（无）→ 子 loader 跑 buildGamePlatformData(\"pc\", 1)"),
      sc("s3", "3. 渲染 GameLayout → <Outlet />"),
      sc("s4", "4. Outlet 渲染 GamePlatformRoute → useLoaderData() 拿数据"),
      sc("s5", "5. 渲染 GamePlatformPage 显示 PC 游戏列表"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5"] },
    explanation: { short: "动态段路由：params 解析 → 子 loader → Outlet → 子组件。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game.$platform.tsx"],
  }),
  q({
    type: "single_choice", title: "Q9 共享 header 怎么加",
    prompt: "想让 /game/* 所有页都有一个统一的「游戏中心」头部，落点？",
    options: [
      sc("A", "GameLayout 改成 return <><GameHeader /><Outlet /></>; 子路由不用各自重复"),
      sc("B", "每个子路由各自加"),
      sc("C", "改 root layout"),
      sc("D", "用 portal"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "父 layout 是「共享 UI」的天然位置——这是 layout 路由的核心价值。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q10 GameLayout 是 client 还是 server",
    prompt: "判断：GameLayout 函数本身在服务器和客户端都会执行。",
    correctAnswer: { value: true },
    explanation: { short: "对——React 组件 SSR 阶段在 Worker 里跑一次输出 HTML；hydrate 后客户端再跑一次接管交互。Layout 也是 React 组件，不例外。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 父 layout 抛错",
    prompt: "如果 GameLayout 渲染时 throw new Error('boom')，谁接？",
    options: [
      sc("A", "冒泡到 root.tsx 的 ErrorBoundary（因 game.tsx 没 export 自己的 ErrorBoundary）"),
      sc("B", "直接白屏"),
      sc("C", "子路由接住"),
      sc("D", "Cloudflare 兜底"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ErrorBoundary 沿父链冒泡，最近一层接——这里是 root。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q12 game.tsx 加 ErrorBoundary",
    prompt: "想让 /game/* 错误时显示「游戏中心暂时不可用」专属页，落点？",
    options: [
      sc("A", "game.tsx export function ErrorBoundary() { return <GameError />; } —— /game/* 子路由抛错时优先这里接，不冒到 root"),
      sc("B", "改 root.tsx"),
      sc("C", "改 entry.server"),
      sc("D", "改 worker.ts"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "嵌套 ErrorBoundary——父 layout 是为子路由群「定制错误 UI」的天然位置。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q13 GameLayout 是否需要 useLoaderData",
    prompt: "判断：现在的 GameLayout 内必须调用 useLoaderData() 才能正确工作。",
    correctAnswer: { value: false },
    explanation: { short: "错——当前 game.tsx 没 export loader，没数据要消费；硬调 useLoaderData 反而报错。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 增加共享 useState",
    prompt: "想在 GameLayout 内放一个跨子路由共享的「当前选中游戏 id」state，子路由用它打开 modal，怎么做？",
    options: [
      sc("A", "GameLayout 内 useState + <Outlet context={{ selectedId, setSelectedId }} />；子路由 useOutletContext() 拿"),
      sc("B", "全局 zustand"),
      sc("C", "url query 参数"),
      sc("D", "localStorage"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Outlet context 是 React Router 给嵌套路由共享 state 的官方方式，无需引入全局 store。" },
    abilityTags: ["bridge.reactRouter.loader", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 子路由切换时 GameLayout 重渲染吗",
    prompt: "用户从 /game/playstation 切到 /game/pc，GameLayout 会卸载重建吗？",
    options: [
      sc("A", "不——React Router 在路由切换时复用相同父 layout，只重渲染变化的 Outlet 部分；GameLayout 内的 useState 保留"),
      sc("B", "完全重建"),
      sc("C", "看情况"),
      sc("D", "TypeScript 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "相同父 layout = 复用 = state 保持——这是嵌套路由的关键性能特性。" },
    abilityTags: ["bridge.reactRouter.loader", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 与 Outlet 顺序",
    prompt: "如果想在 layout 里放「平台切换 tab」+ Outlet，tab 在前还是后？",
    options: [
      sc("A", "<><Tabs /><Outlet /></> ——tab 在前是惯例，因为视觉上「导航 → 内容」从上到下；DOM 顺序也影响 tab 索引"),
      sc("B", "Outlet 在前"),
      sc("C", "无所谓"),
      sc("D", "用 grid 不需要顺序"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "导航在前 + 内容在后是 a11y 友好；可视障用户先听到导航。" },
    abilityTags: ["ai.review.architecture"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 GameLayout 在 Worker 内的角色",
    prompt: "SSR 阶段，GameLayout 在 Cloudflare Worker 内做什么？",
    options: [
      sc("A", "renderToReadableStream 时执行 GameLayout 函数，输出 <div>...<!-- outlet --></div>，框架把子路由 SSR 输出嵌入 Outlet 位置；最终拼成完整 HTML 流"),
      sc("B", "只在客户端跑"),
      sc("C", "Worker 不跑组件"),
      sc("D", "Cloudflare 自动渲染"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "组件树 SSR 是嵌套展开的——父先渲染，Outlet 处插入子。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/entry.server.tsx"],
  }),
  q({
    type: "single_choice", title: "Q18 layout 与 _index 文件名分工",
    prompt: "为什么 /game 的「平台选择器」放 game._index.tsx 而不是 game.tsx？",
    options: [
      sc("A", "_index.tsx 是「父路由的默认子路由」——访问 /game（无后缀）时渲染；game.tsx 是父 layout 不该有具体内容；分工清晰：layout 管壳，_index 管首屏"),
      sc("B", "Remix 强制"),
      sc("C", "TypeScript 限制"),
      sc("D", "无差别"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "layout = 父结构；_index = 默认子。这是 Remix 嵌套路由的标准切分。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game._index.tsx"],
  }),
  q({
    type: "single_choice", title: "Q19 Outlet 与 children",
    prompt: "<Outlet /> 等价于 React 组件中的 props.children 吗？",
    options: [
      sc("A", "概念类似但不同——Outlet 是 React Router 提供的特殊组件，从路由匹配结果中挑出当前激活的子路由组件渲染；children 是普通 props 透传"),
      sc("B", "完全等价"),
      sc("C", "Outlet 只是 children 的别名"),
      sc("D", "无关"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Outlet 接的是「当前 URL 匹配到的子路由组件」，由 router 决定，不是父手动传。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "position_judgement", title: "Q20 加 Xbox 平台",
    prompt: "新增「Xbox」平台分类页。落点？",
    options: [
      sc("A", "1) 改 types/game.ts 给 PlatformId 加 \"xbox\" 2) 改 data/game.ts 加 platforms 项 + allGamesData[\"xbox\"] 3) 改 GamePlatformPicker.tsx 加 XboxIcon —— 不需要新文件"),
      sc("B", "新建 game.xbox.tsx"),
      sc("C", "改 wrangler.toml"),
      sc("D", "重写 GameLayout"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "动态段 game.$platform.tsx 已经能接所有平台 id；只需扩数据 + 类型。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: "app/routes/game.$platform.tsx", layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: ["app/types/game.ts", "app/data/game.ts", "app/components/game/GamePlatformPicker.tsx"],
  }),
  q({
    type: "single_choice", title: "Q21 加 /game/profile 子页",
    prompt: "想加 /game/profile（不属于平台），落点？",
    options: [
      sc("A", "新建 app/routes/game.profile.tsx ——文件名 game.profile = /game 父 + profile 子；与 game.$platform.tsx 平级；自动共享 game.tsx layout"),
      sc("B", "改 game.$platform.tsx 加 if profile 分支"),
      sc("C", "改 game.tsx"),
      sc("D", "改 game._index.tsx"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix flat-routes 加新子页 = 新文件 game.profile.tsx，自动嵌套在 game.tsx 下。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game.profile.tsx"],
  }),
  q({
    type: "single_choice", title: "Q22 整体设计",
    prompt: "「game.tsx 极简空 layout」的整体设计意图？",
    options: [
      sc("A", "占位父结构 = 路由树「形状」声明 + 共享 UI/loader/ErrorBoundary 的扩展点；现在空，是为以后能填——而不是「无用文件」"),
      sc("B", "纯历史包袱"),
      sc("C", "Remix 强制"),
      sc("D", "Cloudflare 要求"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "空 layout 是「保留扩展点」的结构性占位——结构先于功能。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game._index.tsx", "app/routes/game.$platform.tsx"],
  }),
];
