/**
 * Real questions for site-07-nested-layouts / nested-capstone.
 * Anchor: 整合 game.tsx + game._index.tsx + game.$platform.tsx + components/game/* 的整体决策
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/game.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const nestedCapstoneQuestions: RealQ[] = [
  q({
    type: "position_judgement", title: "Q1 加 /game/leaderboard",
    prompt: "新增 /game/leaderboard 排行榜页（不是平台特定）。落点？",
    options: [
      sc("A", "新建 app/routes/game.leaderboard.tsx——文件名 game.leaderboard = /game/leaderboard，自动嵌套在 game.tsx layout 下；与 $platform 平级"),
      sc("B", "改 game.$platform.tsx 加 if leaderboard 分支"),
      sc("C", "改 root 加路由"),
      sc("D", "wrangler 配置"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix flat-routes 加新子页 = 加新文件——零配置。" },
    abilityTags: ["code.position.handler", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game.leaderboard.tsx"],
  }),
  q({
    type: "position_judgement", title: "Q2 加深层嵌套 /game/playstation/zelda",
    prompt: "想给「具体游戏详情页」加 URL /game/playstation/zelda。落点？",
    options: [
      sc("A", "1) 把 game.$platform.tsx 改成 game.$platform.tsx layout（加 <Outlet />） 2) 新建 game.$platform._index.tsx 放原本的列表 3) 新建 game.$platform.$gameId.tsx 放详情——三层嵌套：game.tsx > game.$platform.tsx > 子（_index 或 $gameId）"),
      sc("B", "改 game.$platform.tsx 加 if 判断"),
      sc("C", "新建顶层 game-detail.tsx"),
      sc("D", "wrangler 重定向"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix flat-routes 多级嵌套 = 文件名多个点段 + 父加 Outlet——拓扑关系靠文件名表达。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/routes/game.$platform.tsx", "app/routes/game.$platform._index.tsx", "app/routes/game.$platform.$gameId.tsx"],
  }),
  q({
    type: "single_choice", title: "Q3 共享 game 头部 + 平台 tab",
    prompt: "想给所有 /game/* 页加「游戏中心」头部 + 「PS / Switch / PC」三 tab——header 放哪、tab 放哪？",
    options: [
      sc("A", "header 放 game.tsx layout（所有 /game/* 共享）；tab 也放 game.tsx——tab 切换走 NavLink 到 /game/<id>，自动 active 高亮当前路径"),
      sc("B", "都放 _index"),
      sc("C", "都放 $platform"),
      sc("D", "复制三份"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "共享 UI 在父 layout——一个文件改、所有子页生效。" },
    abilityTags: ["code.position.handler", "bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 共享 loader 跨子路由",
    prompt: "想让 /game/playstation 和 /game/switch 都能拿到「全站累计成就数」。loader 放哪？",
    options: [
      sc("A", "game.tsx layout 加 export const loader = async ({ context }) => json({ totalAchievements }); 子路由用 useRouteLoaderData('routes/game') 拿——loader 共享、避免重复 D1 查询"),
      sc("B", "每个子路由各算一遍"),
      sc("C", "全局 store"),
      sc("D", "url query"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "父 layout loader 是「子路由共享数据」的天然位置——并发跑、共享结果。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 子路由独立 ErrorBoundary",
    prompt: "想让 /game/* 错误时显示「游戏中心暂时不可用」专属错误页。落点？",
    options: [
      sc("A", "game.tsx export function ErrorBoundary() { return <GameUnavailable />; } —— /game/* 子路由抛错时优先这层接，不冒到 root；root 错误页保持「全站通用」"),
      sc("B", "改 root.tsx 加 if 分支"),
      sc("C", "每个子路由各 export"),
      sc("D", "wrangler 配置"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "嵌套 ErrorBoundary——父 layout 给子路由群定制错误 UI。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "branch_trace", title: "Q6 完整 SSR 嵌套渲染",
    prompt: "/game/playstation?page=2 SSR 在 Worker 内步骤？",
    options: [
      sc("s1", "1. Worker 收 GET /game/playstation?page=2"),
      sc("s2", "2. Remix matchRoutes → root + game.tsx + game.$platform.tsx"),
      sc("s3", "3. 并行跑所有 loader（root.loader、game.tsx 无 loader、game.$platform.tsx loader）"),
      sc("s4", "4. game.$platform.tsx loader 里 isPlatformId('playstation') = true → buildGamePlatformData"),
      sc("s5", "5. 全部 loader settle 后 React renderToReadableStream 开始"),
      sc("s6", "6. 渲染 root → Layout → GameLayout → <Outlet /> → GamePlatformRoute → useLoaderData → GamePlatformPage"),
      sc("s7", "7. 流式输出 HTML，Cache-Control 通过 forwardLoaderCacheControl 写到 document"),
    ],
    correctAnswer: { pathIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7"] },
    explanation: { short: "嵌套 SSR：路由匹配 → loader 并发 → 组件嵌套渲染 → 流输出。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "server",
    touchedFiles: [PRIMARY, "app/routes/game.$platform.tsx", "app/lib/cache-headers.server.ts", "app/entry.server.tsx"],
  }),
  q({
    type: "single_choice", title: "Q7 客户端导航复用 layout",
    prompt: "用户从 /game/playstation 切到 /game/pc——GameLayout 重渲染吗？",
    options: [
      sc("A", "不——React Router 在嵌套路由切换时复用相同父 layout 的实例；只有 Outlet 内的子路由组件重新渲染；GameLayout 内的 useState（如果有）保留"),
      sc("B", "完全重建"),
      sc("C", "随机"),
      sc("D", "TypeScript 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "嵌套路由的核心性能特性——共享父 = 复用 = state 保持。" },
    abilityTags: ["bridge.reactRouter.loader", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 嵌套 loader 并发 vs 串行",
    prompt: "Remix 怎么调嵌套路由的多个 loader？",
    options: [
      sc("A", "并发——root.loader / game.tsx.loader / game.$platform.tsx.loader 同时启动；全部 settle 后再渲染；这是 vs 老 React 客户端瀑布的核心改进，避免 N+1"),
      sc("B", "串行从父到子"),
      sc("C", "随机"),
      sc("D", "只跑叶子"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader 并发是 Remix 关键卖点——「fetch as you render」反过来，先全部取再一次渲染。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "true_false", title: "Q9 game.tsx 删了能否工作",
    prompt: "判断：删除 game.tsx 后，/game/playstation 仍能正常访问。",
    correctAnswer: { value: true },
    explanation: { short: "对——Remix 容忍缺父，game.$platform.tsx 直接挂在 root；只是失去未来加共享 UI/loader/ErrorBoundary 的扩展点。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 嵌套与 Outlet context",
    prompt: "GameLayout 想给所有子路由共享一个「当前用户偏好平台」state，怎么做？",
    options: [
      sc("A", "GameLayout 内 useState + <Outlet context={{ favoritePlatform, setFavoritePlatform }} />；子路由 useOutletContext() 拿和改——React Router 标准方式"),
      sc("B", "全局 zustand"),
      sc("C", "url query"),
      sc("D", "localStorage 同步"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Outlet context 是嵌套路由内共享 state 的官方方式，不需引入全局 store。" },
    abilityTags: ["bridge.reactRouter.loader", "frontend.state.local"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 路径参数传播",
    prompt: "GameLayout 想知道当前是哪个平台（params.platform），怎么拿？",
    options: [
      sc("A", "用 useParams() 拿——React Router 任何嵌套层级都能调用 useParams()，路径参数沿整个组件树都可访问"),
      sc("B", "通过 Outlet context"),
      sc("C", "props drill"),
      sc("D", "全局 store"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useParams 是 hook 形式，跨层级访问当前路径参数无需传递。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 子路由 export ErrorBoundary",
    prompt: "如果 game.$platform.tsx 也 export 自己 ErrorBoundary——root + game.tsx + $platform 三层都有 ErrorBoundary，错误冒泡顺序？",
    options: [
      sc("A", "$platform 自己抛 → 自己 ErrorBoundary 接（最近）；$platform ErrorBoundary 自己渲染时再抛 → 冒泡到 game.tsx ErrorBoundary；再抛 → root；最终是框架内置兜底"),
      sc("B", "永远到 root"),
      sc("C", "只在叶子接"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ErrorBoundary 链：最近一层接 → 它自己抛 → 上一层接——逐级回退。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "state-reasoning",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/root.tsx", "app/routes/game.$platform.tsx"],
  }),
  q({
    type: "single_choice", title: "Q13 React Router 与 Remix",
    prompt: "本项目用的 嵌套路由是？",
    options: [
      sc("A", "Remix v2（与 React Router 7 大体一致的概念，文件名约定 game.$platform.tsx 是 v2 flat-routes）；上层用 routes/ 目录扫描，loader / action / meta / links / ErrorBoundary 都是路由级 export"),
      sc("B", "Code Coach 自定义"),
      sc("C", "Cloudflare 自带"),
      sc("D", "Next.js"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "remix/ 子项目用 Remix v2；本课程项目（lea/）用 React Router 7。两者路由机制非常相似。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 共享样式",
    prompt: "想让 /game/* 全部页面用同一组 CSS 变量（accent 色）——落点？",
    options: [
      sc("A", "game.tsx layout 内 <div style={{ '--accent': '#xx' }}><Outlet /></div> ——CSS variable 沿子树继承；或者 export const links = () => [{ rel: 'stylesheet', href: gameVarsCSS }]"),
      sc("B", "改 root.tsx"),
      sc("C", "Tailwind config"),
      sc("D", "wrangler"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "父 layout 控制 CSS 变量 = 子树自动继承——React Router 嵌套路由的样式作用域特性。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 SSR 输出协调",
    prompt: "嵌套路由 SSR 时，谁决定最终 HTTP status code？",
    options: [
      sc("A", "framework + entry.server 协调——叶子 loader 抛 throw new Response({ status: 404 }) 透传到 entry.server 的 responseStatusCode；didError 决策：didError ? 500 : responseStatusCode；最终一份 HTTP 头"),
      sc("B", "永远 200"),
      sc("C", "永远 500"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "嵌套路由的 status 由「错误源」决定，entry.server 协调最终输出。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: "app/entry.server.tsx", layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/routes/game.$platform.tsx", "app/entry.server.tsx"],
  }),
  q({
    type: "true_false", title: "Q16 嵌套与 layout import",
    prompt: "判断：在 game.$platform.tsx 里能 import GameLayout 当组件用。",
    correctAnswer: { value: false },
    explanation: { short: "错——GameLayout 是「路由组件」由 router 在嵌套时自动包裹；当普通组件 import 是反模式（架构混乱），且 useOutlet 等 hook 行为会异常。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game.$platform.tsx"],
  }),
  q({
    type: "single_choice", title: "Q17 加 /game/$platform/$mode",
    prompt: "想给每个平台加「单人 / 多人」分类，URL /game/playstation/single——文件名？",
    options: [
      sc("A", "game.$platform.$mode.tsx + 把 game.$platform.tsx 改成 layout（加 Outlet）+ 新建 game.$platform._index.tsx 保留原列表——三层嵌套清晰"),
      sc("B", "game.$platform-$mode.tsx"),
      sc("C", "game.$platformAndMode.tsx"),
      sc("D", "无法实现"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix flat-routes 三层嵌套就是文件名三段——和 URL 段对应。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/routes/game.$platform.tsx", "app/routes/game.$platform.$mode.tsx", "app/routes/game.$platform._index.tsx"],
  }),
  q({
    type: "single_choice", title: "Q18 path matching 优先级",
    prompt: "如果同时有 game.$platform.tsx 和 game.special.tsx，访问 /game/special——匹配哪个？",
    options: [
      sc("A", "game.special.tsx——静态段优先级高于动态段；React Router 路由匹配规则"),
      sc("B", "$platform"),
      sc("C", "随机"),
      sc("D", "都匹配"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "路由匹配「具体优先」——static > dynamic ($) > splat (*)。" },
    abilityTags: ["bridge.reactRouter.loader"], sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game.$platform.tsx", "app/routes/game.special.tsx"],
  }),
  q({
    type: "single_choice", title: "Q19 路由分组目录化",
    prompt: "Remix v2 flat-routes 的扁平文件名（game.$platform.tsx）vs 文件夹路由（routes/game/$platform.tsx）选哪个？",
    options: [
      sc("A", "都支持——本项目选 flat（一目录扫所有路由），目录路由（folder routing）更适合大型项目；trade-off 是 flat 在路由多时文件名 explosion，folder 让结构层级更明显"),
      sc("B", "只支持 flat"),
      sc("C", "只支持 folder"),
      sc("D", "Cloudflare 强制"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix 同时支持 flat 和 folder；项目规模小用 flat 简单。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: "app/routes/", layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 嵌套与 type 推导",
    prompt: "如何在 GameLayout 里 type-safe 拿 game.$platform.tsx loader 的数据？",
    options: [
      sc("A", "useRouteLoaderData<typeof platformLoader>('routes/game.$platform') —— 显式 import platformLoader 类型 + 路由 id；TS 自动推 data 字段类型"),
      sc("B", "any 强转"),
      sc("C", "props 传"),
      sc("D", "全局 store"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "useRouteLoaderData<typeof loader> + 路由 id 是类型安全的 Remix 跨层数据访问。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY, "app/routes/game.$platform.tsx"],
  }),
  q({
    type: "single_choice", title: "Q21 SEO 嵌套 meta",
    prompt: "嵌套路由的 meta 函数怎么合并？",
    options: [
      sc("A", "Remix 默认按「最近一层 meta 覆盖父」合并；想精细控制可用 ({ matches }) => ... 拿父 meta 自己拼接；本项目 game.$platform.tsx 直接覆盖父，简单实用"),
      sc("B", "全部叠加"),
      sc("C", "永远父优先"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "嵌套 meta 合并默认子覆盖父；matches 给精细控制能力。" },
    abilityTags: ["bridge.reactRouter.loader", "ai.review.architecture"],
    sourceFilePath: "app/routes/game.$platform.tsx", layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/game.$platform.tsx"],
  }),
  q({
    type: "single_choice", title: "Q22 整体嵌套设计",
    prompt: "site-07 嵌套路由「game.tsx 空 layout + game._index.tsx 默认子 + game.$platform.tsx 动态子」整体哲学？",
    options: [
      sc("A", "1) 空 layout 占位 = 路由树形状声明 + 共享扩展点 2) _index 是 URL 无后缀时的默认子 3) $platform 是动态段，对所有平台共用一个文件 4) loader 守卫早抛 404 防止脏数据 5) 路由薄、组件厚 6) 派生数据在路由层算 + 组件层只渲染——结构清晰、易扩展、SSR 安全"),
      sc("B", "纯习惯"),
      sc("C", "Remix 强制"),
      sc("D", "Cloudflare 决定"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "六条原则贯穿 layout / _index / 动态段 / 守卫 / 分层 / 派生——构成完整嵌套路由范式。" },
    abilityTags: ["ai.review.architecture", "code.position.handler", "bridge.reactRouter.loader"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared",
    touchedFiles: [PRIMARY, "app/routes/game._index.tsx", "app/routes/game.$platform.tsx", "app/components/game/GamePlatformPicker.tsx"],
  }),
];
