/**
 * Real questions for site-16-auth-session / auth-capstone.
 * Anchor: remix/app/lib/auth.server.ts + api.auth.$.ts + chat.tsx —— 整套认证系统协奏：betterAuth 核心 + splat route + 受保护路由模板 + session 缓存 + admin 分级
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/lib/auth.server.ts";
const sc = (id: string, text: string) => ({ id, text });

export const authCapstoneQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 文件分工",
    prompt: "auth 三大文件：auth.server.ts（核心实例） + api.auth.$.ts（splat 路由） + ____（受保护页模板）。",
    options: [],
    blanks: [{ id: "v", placeholder: "文件", acceptedAnswers: ["chat.tsx", "chat", "routes/chat.tsx"] }],
    correctAnswer: { type: "fill_blank", values: { v: "chat.tsx" } },
    explanation: { short: "三文件分工：核心 + 路由 + 守门——三层架构。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 三层架构职责",
    prompt: "auth 三层职责？",
    options: [
      sc("A", "1) auth.server.ts: betterAuth 实例 + plugins (magicLink/google/microsoft/oneTap/admin) + sessionCache + requireAuth/Admin 工具函数 2) api.auth.$.ts: splat 接所有 /api/auth/* 转发 handler + Microsoft callback relay + sanitized debug log 3) 业务路由如 chat.tsx: loader 调 requireXX 守门 + redirect 模式 + Cache-Control private；分层职责清晰"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三层 = 核心 + 路由 + 守门——分工清晰。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/routes/api.auth.$.ts", "app/routes/chat.tsx"],
  }),
  q({
    type: "single_choice", title: "Q3 登录全流程（Google）",
    prompt: "用户点 Google 登录到拿到 session 全流程？",
    options: [
      sc("A", "1) 客户端 better-auth client.signIn.social({provider:'google'}) 2) 浏览器跳 /api/auth/sign-in/social → splat handler 处理 → redirect 到 google OAuth 3) 用户授权 4) Google 重定向 /api/auth/callback/google?code=... → 又进 splat handler 5) better-auth 用 code 换 token 6) 创建 user/session/account 三行 D1 写入 7) Set-Cookie session_token 8) redirect 回业务页 9) 后续请求带 cookie → getSessionCached 拿 user；9 步全 OAuth 流程"),
      sc("B", "纯客户端"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "OAuth 9 步全流程——客户端 + splat + better-auth + DB + cookie 协奏。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 magicLink 全流程",
    prompt: "用户在 /auth 输邮箱用 magic link 登录全流程？",
    options: [
      sc("A", "1) /api/auth/sign-in/magic-link POST email 2) splat handler → magicLink plugin sendMagicLink hook 3) 五重并发 rate-limit peek 4) 都通过则发邮件含一次性 link 5) consume 限流计数 6) 用户邮箱点 link 跳 /api/auth/verify-magic-link?token=... 7) splat 内 verify token + 创建 session 8) Set-Cookie + redirect 9) 拿 session；9 步含限流 + 邮件 + 验证"),
      sc("B", "纯邮件"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "magicLink 9 步全流程——限流 + 邮件 + 验证 + cookie。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 session 查询全流程",
    prompt: "受保护路由 chat.tsx 拿 session 全流程？",
    options: [
      sc("A", "1) loader 调 requireNemesisUser(request) 2) 内调 getSessionCached(request) 3) WeakMap 查缓存命中即返 4) 否则调 getAuth(request).api.getSession({headers}) 5) better-auth 解析 cookie 6) 查 D1 session 表 7) 关联 user 表 8) 校验 expiresAt 9) 返 AuthSession 10) cache.set Promise dedupe 11) 失败抛 401 Response → catch 转 redirect；多步链路 + 缓存优化"),
      sc("B", "单查"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "session 查询 11 步链路——含缓存 dedupe + 多次 DB + 错误协议。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 多 provider 共存设计",
    prompt: "项目同时支持 Google + Microsoft + magicLink + oneTap——为什么不选一个？",
    options: [
      sc("A", "1) Google 普及高 + Microsoft 企业用户 + magicLink 邮箱无密码 + oneTap 一键登录提升转化 2) 用户选自己习惯的减摩擦 3) provider 失败可降级（一个挂另一个仍可用） 4) better-auth plugin 模式让多 provider 共存代价低；用户体验 + 鲁棒性"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "多 provider = UX 多选 + 鲁棒性 + plugin 低成本——值得。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 admin 分级",
    prompt: "项目 ADMIN_EMAILS env + admin role 双层——为什么？",
    options: [
      sc("A", "1) ADMIN_EMAILS 是声明式（部署配置）—— 改变时不必改 DB 2) admin role 持久化在 DB 内 3) 登录时自动 promote（isAdmin email && role !== admin 时 update）4) 双层支持「快速增删管理员（env） + 历史 audit（DB role）」；安全 + 灵活"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ADMIN_EMAILS + role 双层 = 声明式增删 + DB audit 持久——分级。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 ban 系统",
    prompt: "isActiveBan(user) = banned && (无 banExpires || banExpires > now)——支持哪些场景？",
    options: [
      sc("A", "1) 永封 banned=true + banExpires=null 2) 临封 banned=true + banExpires=未来时间（自动解禁）3) 已解 banned=false 4) 解释 banReason；admin plugin 提供这些列；项目 requireAuth/requireAdmin 都查 isActiveBan 失败抛 403 / redirect 首页"),
      sc("B", "无 ban"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "banned + banExpires + banReason = 三态封禁系统——admin 可控。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 trustedOrigins + CSRF",
    prompt: "trustedOrigins 多源聚合的安全意图？",
    options: [
      sc("A", "防 CSRF—— better-auth 校验请求 origin 是否在白名单内；非白名单源的 cookie 提交（如 evil.com 的 form）被拒；多源是为兼容 dev/prod/worker.dev 等多个合法 origin；CSRF 保护边界"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "trustedOrigins = CSRF 防御边界——白名单合法 origin。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 sign-out",
    prompt: "用户登出全流程？",
    options: [
      sc("A", "1) 调 better-auth client signOut() 2) POST /api/auth/sign-out 3) splat → handler 4) 删 D1 session 行 5) 响应 Set-Cookie maxAge:0 清 cookie 6) 客户端 navigate 首页 7) 后续请求 cookie 已无 → getSessionCached 返 null；7 步含 DB 删除 + cookie 清除"),
      sc("B", "只清 cookie"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "登出 = DB 删 session + Set-Cookie maxAge:0——双清。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/routes/auth.sign-out.tsx"],
  }),
  q({
    type: "single_choice", title: "Q11 session 续期",
    prompt: "session.expiresIn:60*60*24*7 + updateAge:60*60*24——含义？",
    options: [
      sc("A", "expiresIn 7 天：session 总寿命；updateAge 1 天：每访问 1 次更新一次 expiresAt（向后延 7 天）；活跃用户 session 长期不掉；不活跃 7 天自动失效；UX + 安全平衡"),
      sc("B", "无续期"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "expiresIn + updateAge = 7 天总寿命 + 1 天滚动续期——平衡。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 D1 表 + better-auth schema",
    prompt: "AuthDatabase 类型定义 user/session/account/verification 四张表——为什么这些？",
    options: [
      sc("A", "user: 用户基本信息；session: 登录会话（token + expiresAt + ipAddress + userAgent）；account: OAuth 关联（providerId/accessToken/refreshToken）；verification: 邮件验证 token（magicLink 用）；better-auth 的标准 schema"),
      sc("B", "随机"),
      sc("C", "无意义"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "user/session/account/verification = better-auth 四表 schema——多 provider 设计。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 错误：忘配 GOOGLE_CLIENT_ID",
    prompt: "若忘配 GOOGLE_CLIENT_ID env—— 后果？",
    options: [
      sc("A", "1) auth.server fallback 到空字符串启动不崩 2) 用户点 Google 登录 → /api/auth/sign-in/social → handler 调 google OAuth 用空 client_id → google 返错 'invalid_client' 3) 用户看错误页；优雅降级（启动不崩）但功能不可用；env 检查必备"),
      sc("B", "启动崩"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "缺 env = 优雅降级启动 + 调用时报 invalid_client——env 检查必备。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 错误：trustedOrigins 漏配",
    prompt: "若 trustedOrigins 漏 worker.dev 域——后果？",
    options: [
      sc("A", "Microsoft callback 通过 worker.dev relay 时 better-auth 拒绝该 origin → CSRF 校验失败 → OAuth 流程崩；必须包括所有合法 origin；通过聚合多种 env vars 减漏"),
      sc("B", "无影响"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "trustedOrigins 漏 = OAuth callback 崩；多源聚合防漏。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 错误：session 缓存键漏 Request",
    prompt: "若 sessionCache 用 Map 而非 WeakMap——后果？",
    options: [
      sc("A", "Request 强引用累积 → 内存泄漏；Worker 长跑后被 Cloudflare 强 kill；prod 故障；WeakMap 是必需而非优化"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "sessionCache Map = 内存泄漏；WeakMap 必需。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 加新 OAuth provider",
    prompt: "加 GitHub 登录的端到端流程？",
    options: [
      sc("A", "1) auth.server.ts socialProviders 加 github 配置 2) 配 GITHUB_CLIENT_ID/SECRET env vars 3) GitHub Cloud 后台注册 callback URL = /api/auth/callback/github 4) trustedOrigins 包括 GitHub auth domain（如非必须）5) 客户端 sign-in 按钮调 signIn.social({provider:'github'}) 6) splat 路由不必改（已通配） 7) 测试 OAuth 流程；6 步插件式扩展"),
      sc("B", "需重写"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "新 provider = auth.server + env + 后台注册 + 客户端 4 处改动。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 调试 magicLink 失败",
    prompt: "用户反馈点邮件链接后 'Invalid or expired token'——可能原因？",
    options: [
      sc("A", "1) link 过期（>5min expiresIn） 2) link 已被使用（一次性 token）3) D1 verification 表行被清/不存在 4) 用户在多设备点了同一 link（首次消费后续失败）5) better-auth 版本不一致 token 格式变；多线索"),
      sc("B", "无法调"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "magicLink token 失效 = 过期/已用/丢/多设备/版本——多原因排查。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 安全审计要点",
    prompt: "auth 系统安全审计应检查？",
    options: [
      sc("A", "1) trustedOrigins 完整防 CSRF 2) sanitizeSearchParams 防 OAuth secret 进日志 3) returnTo 同源校验防 Open Redirect 4) cookie httpOnly + Secure + SameSite 防 XSS/CSRF 5) session expiresIn 适度 6) ban 系统检查 7) admin role 双层 8) sessionCache 不跨请求安全 9) magicLink 限流防滥用 10) error 不暴露内部细节；10 项审计"),
      sc("B", "无需审计"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "auth 安全审计 = 10 项清单——纪律性。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 better-auth vs Auth.js",
    prompt: "项目选 better-auth 而非 Auth.js（NextAuth）——理由？",
    options: [
      sc("A", "1) Auth.js 强绑 Next.js（虽有 Auth.js core 但 Cloudflare Workers 适配粗糙）2) better-auth 设计更现代化（plugin 系统更灵活）3) Edge runtime 一等公民 4) D1/SQLite adapter 友好 5) TypeScript 类型推导更好；选库基于运行时 + 类型 + 适配生态"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "better-auth = Edge + plugin + TS + D1 友好——选型理由。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 加 2FA 的影响面",
    prompt: "若给项目加 TOTP 2FA—— 影响哪些文件？",
    options: [
      sc("A", "1) auth.server.ts: 加 twoFactor plugin 2) D1 schema 加 user.twoFactorSecret 列 + migration 3) auth.tsx: 登录后第二步表单输 6 位 TOTP 4) sign-up 时引导扫 QR 5) requireAuth 内验证 2FA 完成；多文件协同 + DB schema 变更"),
      sc("B", "不影响"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "加 2FA = plugin + DB + 路由 + 守门 4 处协同。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 性能瓶颈",
    prompt: "auth 系统在高并发下可能瓶颈？",
    options: [
      sc("A", "1) D1 session 查询是 hot path——可加 KV 短缓存（5-30s 过期）减 DB 2) cookie 头解析 JS 字符串操作不是瓶颈 3) better-auth 内部 hash 校验有 CPU 成本 4) magicLink 邮件发送阻塞——已用 waitUntil 后台 5) ban 检查每次都查 user 表——可缓存；DB 是主瓶颈"),
      sc("B", "无瓶颈"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "auth 性能 = D1 hot path 主瓶颈——缓存 session 是关键优化。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 auth-capstone 整体哲学",
    prompt: "整套 auth 系统的设计哲学？",
    options: [
      sc("A", "1) 三层架构（核心 + splat 路由 + 业务守门）职责清晰 2) better-auth + plugin 模式让多 provider 共存 3) 所有 OAuth 流程通过 splat $.ts 一文件接 4) baseURL/redirectURI/trustedOrigins 全动态适配多环境 5) sessionCache WeakMap 单请求级 dedup 6) requireAuth 抛 401/requireAdmin redirect 首页 错误码精确 7) ADMIN_EMAILS env + admin role 双层 8) ban 三态系统支持永封/临封/解封 9) magicLink 五重并发 rate-limit + waitUntil 异步发邮件 10) 所有受保护页 Cache-Control private + Vary + headers 转发 11) sanitizeSearchParams 防 OAuth secret 进日志 12) returnTo 防 Open Redirect；综合：「分层 + 多 provider + 全动态 + 缓存 + 错误码 + 管理 + 安全日志 + 缓存私有」八件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "auth 系统 12 原则——认证授权全栈纪律。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
];
