/**
 * Real questions for site-16-auth-session / auth-route.
 * Anchor: remix/app/routes/api.auth.$.ts —— splat catch-all 接 /api/auth/*；loader + action 都转发给 getAuth(request).handler(request)；含 Microsoft callback 多域 relay + sanitized debug 日志
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/api.auth.$.ts";
const sc = (id: string, text: string) => ({ id, text });

export const authRouteQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 splat 文件名",
    prompt: "api.auth.$ 后缀 ____ —— 让该路由匹配 /api/auth/* 任意子路径。",
    options: [],
    blanks: [{ id: "v", placeholder: "扩展", acceptedAnswers: [".ts", "ts"] }],
    correctAnswer: { type: "fill_blank", values: { v: ".ts" } },
    explanation: { short: ".ts 表示纯 resource route 不渲染 UI；splat $ 是 Remix v2 通配。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 文件名结构",
    prompt: "api.auth.$.ts 文件名分解？",
    options: [
      sc("A", "api → /api 段；auth → /api/auth 段；$ → splat 通配匹配 /api/auth 后任意子路径（callback/microsoft、sign-in/social、verify-email 等）；.ts → 纯 resource route 无 UI；四段结构"),
      sc("B", "随机"),
      sc("C", "无意义"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "api.auth.$.ts = 路径 + 通配 + resource 三件事的 Remix v2 命名。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 splat 必要性",
    prompt: "为什么 better-auth 必须用 splat 而不是为每个 /api/auth 路径建独立文件？",
    options: [
      sc("A", "better-auth 内部多种路径（callback/sign-in/sign-up/verify-email/sign-out/...每 provider 又有变体）—— 数十条；splat 一文件全接 + 转发 handler；列举每条不仅冗余还会随 better-auth 版本变更落后"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "splat 转发 = 数十路径一次接住；版本演进无关。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 loader + action 都导出",
    prompt: "为什么同时 export loader 和 action？",
    options: [
      sc("A", "OAuth 流程含 GET（callback 重定向）+ POST（form 提交）；不同方法 better-auth 都要处理；loader 处理 GET，action 处理其他；都转给同一 getAuth().handler；HTTP 方法分流"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader=GET、action=非GET → 都转 better-auth handler；HTTP 方法分流。" },
    abilityTags: ["bridge.reactRouter.loader", "bridge.reactRouter.action", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 getAuth(request).handler(request)",
    prompt: "const response = await getAuth(request).handler(request);——handler 是？",
    options: [
      sc("A", "better-auth 暴露的标准 fetch-style handler——接 Request 返 Response；内部解析 URL → 路由到对应 provider/path → 执行业务（OAuth 交换、cookie 写、redirect）；handler 是协议层入口"),
      sc("B", "DB 查"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "handler = better-auth Fetch handler——Request → Response。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/auth.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q6 getMicrosoftCallbackRelay",
    prompt: "loader 内 const relay = getMicrosoftCallbackRelay(request); if (relay) throw redirect(relay);——什么场景？",
    options: [
      sc("A", "Microsoft OAuth 回调注册的是 worker.dev 域名；用户实际访问 xn--cckl9nsb.com；回调到 worker.dev 后此 relay 函数检测路径是 callback/microsoft 且 host ≠ primary → 重定向到 primary host 同路径让 better-auth 处理；workers 多域 OAuth 兼容"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Microsoft relay = 跨 worker.dev → primary host 的 OAuth 回调中转。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 relay 条件",
    prompt: "relay 函数返 null 的条件？",
    options: [
      sc("A", "1) 路径不是 /api/auth/callback/microsoft 2) 没配 MICROSOFT_REDIRECT_URI 或 BETTER_AUTH_URL/APP_URL 3) 当前 host 不是注册的 microsoft host 4) 当前 host = primary host（已正确）；多重保护避免误重定向"),
      sc("B", "随机"),
      sc("C", "无意义"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "relay null 的多重条件 = 防误触发；只在精确场景生效。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 throw redirect",
    prompt: "throw redirect(relay)——为什么 throw 而不 return？",
    options: [
      sc("A", "Remix loader 协议：throw Response 立即终止 loader 执行 + 转给 framework 处理；redirect() 返 302 Response；用 throw 形式让控制流明确「这里不再继续」（return 后还要 fall through）；惯用法"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "throw redirect = Remix 短路控制流惯用法。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 getAuthDebugContext",
    prompt: "handleAuthRequest 内 const authDebug = await getAuthDebugContext(request);——为什么先收集？",
    options: [
      sc("A", "OAuth 失败时排错需「请求来源」「provider」「callback 参数」「state cookie 是否存在」等上下文；handler 抛错前已经丢失这些信息（response 内可能不带）→ 提前提取 debug 上下文确保任何路径都可 log；可观测性优先"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "提前收集 debug 上下文 = 失败时仍可观测——可观测性优先。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 sanitizeSearchParams",
    prompt: "console.error 内 search: sanitizeSearchParams(url)——为什么要 sanitize？",
    options: [
      sc("A", "OAuth callback URL 含 code/state/token 等敏感参数；原样 log 会让 worker 日志/Cloudflare 日志暴露这些 secret 给运维；sanitize 把 code=xxx 替换成 [redacted]；调试可见结构但不泄密"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "log sanitize = OAuth secret 不进日志——隐私。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 catch + throw 模式",
    prompt: "try { ... } catch (error) { console.error(...); throw error; }——为什么 catch 后再 throw？",
    options: [
      sc("A", "中间人模式——只为加 log 不改变错误传播；console.error 落 debug 信息后让原 error 继续抛给 framework（最终走 ErrorBoundary 或 5xx）；中间人 logger 经典实现"),
      sc("B", "吞错"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "catch + log + throw = 中间人 logger——透明可观测。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 资源路由 vs UI 路由",
    prompt: "api.auth.$.ts 与 chat.tsx 文件命名区别？",
    options: [
      sc("A", ".ts vs .tsx —— Remix 用扩展名区分：.ts 是 resource route（仅 loader/action 无 default export 渲染） .tsx 是 UI route（含组件 default export）；api 类路由全是 .ts；前端页是 .tsx"),
      sc("B", "随机"),
      sc("C", "等价"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: ".ts = resource route；.tsx = UI route——扩展名分类。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 OAuth 流程",
    prompt: "用户点 'Google 登录' 全流程？",
    options: [
      sc("A", "1) 客户端调 better-auth client signIn.social({provider:'google'}) 2) 浏览器跳 /api/auth/sign-in/social → 这里 splat handler 处理 → 重定向到 google OAuth 3) 用户授权 4) Google 重定向回 /api/auth/callback/google?code=... 5) 又一次进 splat handler 6) better-auth 用 code 换 token + 创建 user/session + 写 cookie 7) 重定向回业务页；全程 splat 同一文件"),
      sc("B", "纯客户端"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "OAuth 全流程 = 多次进 splat handler——routing + better-auth 协作。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 Better Auth 处理 cookie 写",
    prompt: "OAuth 成功后谁负责写 session cookie 到响应？",
    options: [
      sc("A", "better-auth handler 内部完成——它构造 Response 含 Set-Cookie session；route 文件只是 await handler(request) 返回它；具体 cookie 名字/属性都由 better-auth 控；route 当透明转发"),
      sc("B", "route 自己写"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "better-auth handler 内部写 cookie；route 透明转发——分层。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 错误：忘了 splat",
    prompt: "若改文件名为 api.auth.ts（无 $）—— 后果？",
    options: [
      sc("A", "只匹配 /api/auth 不匹配 /api/auth/* 子路径；OAuth callback /api/auth/callback/google 路由不到此文件 → 404；OAuth 流程整体崩溃；splat 是必要的"),
      sc("B", "正常"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "无 $ = 不匹配子路径 → OAuth 404 崩。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 错误：把 sanitize 跳了",
    prompt: "若 console.error 直接 log url.search 而非 sanitizeSearchParams(url)——风险？",
    options: [
      sc("A", "OAuth code/state 进 worker 日志 → Cloudflare 日志面板可看 → 任何运维/被授权日志读者可见 → 可能用 code 提权（虽 code 短期失效但仍泄密）；安全审计漏洞"),
      sc("B", "无影响"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "OAuth secret 进日志 = 安全审计漏洞——sanitize 必备。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 错误：handler 未 await",
    prompt: "若忘了 await：return getAuth(request).handler(request);——会怎样？",
    options: [
      sc("A", "return Promise<Response>；Remix 通常会自动 await（resolveLoaderError 流程）但行为不可靠：错误捕获层缺失；最佳显式 await 后 try/catch 可控；惯例先 await 再处理"),
      sc("B", "完全等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "显式 await = 错误可捕获 + 行为可控；省略 await 失去 try/catch 能力。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 加新 OAuth provider",
    prompt: "要加 GitHub 登录——改哪些文件？",
    options: [
      sc("A", "1) auth.server.ts 内 socialProviders 加 github: { clientId, clientSecret } 2) 配 GITHUB_CLIENT_ID/SECRET env vars 3) 客户端 sign-in 调 better-auth signIn.social({provider:'github'}) 4) GitHub 后台注册 callback URL = /api/auth/callback/github 5) 不必改 splat 文件——它已通配；插件式扩展"),
      sc("B", "需新文件"),
      sc("C", "改路由"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "加 provider = 改 auth.server + env + 客户端 + GitHub 后台；splat 不动。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 splat 性能",
    prompt: "splat 把所有 /api/auth/* 都路由到一个 handler——性能担忧？",
    options: [
      sc("A", "无担忧——better-auth handler 内部按精确路径快速分发（O(1) hash 或 trie）；Remix 路由匹配本身是 trie 树同样快；splat 不增加运行时成本仅是约定不同；性能与拆分文件等价"),
      sc("B", "性能差"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "splat 性能与拆分文件等价——better-auth 内部高效分发。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 调试 OAuth 失败",
    prompt: "用户反馈「点 Google 登录后白屏」—— 怎么调试？",
    options: [
      sc("A", "1) 打开浏览器 Network → 看跳转链路 (300/302 状态码 + Location 头) 2) 看 worker 日志的 [BetterAuth] request failed log（含 sanitized search + headers + authBaseURL）3) 检查 Google Cloud Console 里 redirect URI 是否匹配 dev/prod 4) 检查 GOOGLE_CLIENT_ID/SECRET env 是否设；多线索定位"),
      sc("B", "无法调试"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "OAuth 调试 = Network + worker 日志 + provider 后台配置——多线索。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 splat vs $param",
    prompt: "Remix v2 中 $alone（splat）与 $param 差异？",
    options: [
      sc("A", "$alone = $.tsx：吃当前位置之后所有路径段（深度任意）；$param = users.$id.tsx：吃单段（如 /users/123 但不是 /users/123/edit）；本文件用 $.ts 因要吃任意深度路径"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "$ alone = 任意深度；$param = 单段——Remix v2 通配语法两类。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 api.auth.$.ts 整体哲学",
    prompt: "api.auth.$.ts 整体哲学？",
    options: [
      sc("A", "1) splat $ 通配让一文件接 better-auth 数十路径 2) loader + action 分别接 GET/非GET 3) 转发 getAuth(request).handler(request) 透明传递 4) Microsoft callback relay 多域 OAuth 兼容 5) 提前 getAuthDebugContext 保证失败可观测 6) sanitizeSearchParams 防 OAuth secret 进日志 7) catch + log + throw 中间人 logger 模式 8) .ts 后缀标识 resource route 9) 不含 UI 渲染纯协议层 10) 加 provider 不必改本文件——只改 auth.server；综合：「splat 通配 + 透明转发 + 多域兼容 + 安全日志」四件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "auth-route 10 原则——better-auth 接入路由层纪律。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
];
