/**
 * Real questions for site-16-auth-session / auth-server.
 * Anchor: remix/app/lib/auth.server.ts —— betterAuth 实例: D1 adapter + magicLink + oneTap (Google) + admin + microsoft + Microsoft callback workers 兼容 plugin
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/lib/auth.server.ts";
const sc = (id: string, text: string) => ({ id, text });

export const authServerQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 库",
    prompt: "import { betterAuth } from '____' —— 主认证库。",
    options: [],
    blanks: [{ id: "v", placeholder: "包名", acceptedAnswers: ["better-auth"] }],
    correctAnswer: { type: "fill_blank", values: { v: "better-auth" } },
    explanation: { short: "better-auth = 现代化 Node/Workers 认证库。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 better-auth 优势",
    prompt: "项目用 better-auth 而不 NextAuth/Auth.js——动机？",
    options: [
      sc("A", "1) Edge runtime 友好（Workers 兼容） 2) 数据库适配灵活（D1/SQLite/PG） 3) 插件机制（magicLink/oneTap/admin/microsoft 各自插件） 4) 类型安全 + 现代 API；适配 Cloudflare Workers 是关键"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "better-auth = Edge 友好 + 插件灵活——Workers 选型。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 D1 adapter",
    prompt: "database: { db: getAuthDb(), type: 'sqlite' }——getAuthDb 是？",
    options: [
      sc("A", "Kysely<AuthDatabase> 实例（包装 D1Dialect）；type:'sqlite' 告诉 better-auth 用 SQLite SQL 方言；用户/会话/账号表 schema 由 better-auth 管理但跑在 D1 上；adapter 模式让 better-auth 不知道具体后端"),
      sc("B", "原始 binding"),
      sc("C", "随机"),
      sc("D", "ORM"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Kysely + sqlite type = better-auth 适配 D1 的 adapter 配置。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/db.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q4 baseURL 动态",
    prompt: "baseURL: appUrl + 函数 getAuthBaseURL(request) 决定——为什么动态？",
    options: [
      sc("A", "dev 走 localhost:3000，prod 走 xn--cckl9nsb.com，测试可走 worker.dev——baseURL 影响 OAuth callback URL 必须正确反映当前请求来源；硬编码会让 OAuth 失败"),
      sc("B", "总硬编码"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "baseURL 动态 = OAuth callback 跟随请求来源——多环境兼容。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 secret 链",
    prompt: "secret: getEnvVar('BETTER_AUTH_SECRET') || getEnvVar('AUTH_KEY_SECRET') || 'dev-only-...'——三层 fallback 含义？",
    options: [
      sc("A", "新名字 BETTER_AUTH_SECRET 优先 → 兼容旧名 AUTH_KEY_SECRET → 都没就用 dev-only 警告字符串（避免崩但永不上线）；命名迁移期 + dev 友好"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "三层 fallback = 新名优先 + 兼容旧名 + dev 默认；迁移友好。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 trustedOrigins",
    prompt: "trustedOrigins = [...].filter((origin, index, origins) => Boolean(origin) && origins.indexOf(origin) === index);——什么逻辑？",
    options: [
      sc("A", "聚合多个可能源（appUrl/productionAppUrl/requestOrigin/各 env vars）+ filter 去重和 falsy；返唯一 origins 列表给 better-auth 校验请求来源；防 CSRF（拒绝非可信源）"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "trustedOrigins 多源聚合 + 去重 = 防 CSRF 边界。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 socialProviders.google",
    prompt: "socialProviders: { google: { clientId: getEnvVar('GOOGLE_CLIENT_ID') || '', clientSecret: ... } }——空字符串 fallback 什么意思？",
    options: [
      sc("A", "未配置时不抛错保程序启动；OAuth 调用时 better-auth 会拒绝（无效凭据）；让一个 provider 缺失不影响其他可用；优雅降级"),
      sc("B", "无效"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "空字符串 fallback = 启动不崩 + 调用时报错——优雅降级。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 microsoft redirectURI 动态",
    prompt: "microsoftRedirectURI = isLocalhost ? `${LOCAL_APP_URL}/api/auth/callback/microsoft` : microsoftWorkerRedirectURI;——为什么这样？",
    options: [
      sc("A", "Microsoft 注册时配的 redirect URI 必须精确匹配；dev localhost 与 prod worker 域名不同 → 各自有注册的 URI；isLocalhost 切换两套；硬编码 prod URI 在 dev 会触发 'redirect_uri_mismatch' 错误"),
      sc("B", "随机"),
      sc("C", "性能"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "redirect URI 必精确匹配 = 多环境双套 → isLocalhost 切换。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 Microsoft Workers callback plugin",
    prompt: "plugin id 'microsoft-workers-callback' 内 hooks.before 设 oauthConfig.skipStateCookieCheck:true——什么场景？",
    options: [
      sc("A", "Microsoft OAuth callback 跨域（用 worker.dev 注册）；state cookie 经多域跳转可能丢失（SameSite 策略）；本应用知该路径已用 state 参数防 CSRF 不必再校验 cookie；workers 多域兼容 hack"),
      sc("B", "安全降级"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "skipStateCookieCheck = workers 多域 OAuth callback 兼容 hack。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 oneTap 插件",
    prompt: "oneTap()——什么功能？",
    options: [
      sc("A", "Google One Tap 登录——用户访问站点时浮窗提示「使用 ... 账号继续」一键登录；提升注册转化（不必跳转 OAuth 全流程）；前端组件配后端 plugin 验证"),
      sc("B", "短信"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "oneTap = Google 一键登录浮窗——转化优化。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 admin 插件",
    prompt: "admin({ defaultRole: 'user', adminRoles: ['admin'] })——做什么？",
    options: [
      sc("A", "用户表加 role 列（默认 user）+ 提供 isAdmin 工具方法 + 后台 admin 操作（封禁、列表）；项目自定义 ADMIN_EMAILS env 还会自动 promote 到 admin role；分级权限基础"),
      sc("B", "只是标签"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "admin 插件 = role 列 + 工具方法 + 操作 API——权限基础。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 magicLink 配置",
    prompt: "magicLink({ disableSignUp: false, expiresIn: 300, rateLimit: { window: 60, max: 10 }, async sendMagicLink ... })——参数含义？",
    options: [
      sc("A", "disableSignUp:false 允许新用户通过链接注册；expiresIn:300 链接 5 分钟过期；rateLimit window:60/max:10 = 60s 内最多 10 次；sendMagicLink 自定义发邮件 + 速率检查；安全 + 体验"),
      sc("B", "默认"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "magicLink 配置 = 注册+过期+限流+发送钩子——四层控制。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/rate-limit.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q13 五重 rate-limit Promise.all",
    prompt: "sendMagicLink 内 Promise.all([global, ip, email, cooldown, status])——为什么并发 peek？",
    options: [
      sc("A", "五种检查彼此独立——并发查比串行 5 次 RPC 快近 5 倍；Durable Object 调用昂贵；任一不允立即抛 APIError 短路阻止后续邮件发送；性能 + 完整守门"),
      sc("B", "等价串行"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Promise.all = 5 次独立检查并发——性能优化。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 APIError TOO_MANY_REQUESTS",
    prompt: "throw new APIError('TOO_MANY_REQUESTS', { message: '请求过于频繁，请稍后再试' });——better-auth 怎么处理？",
    options: [
      sc("A", "APIError 是 better-auth 内置错误类型；自动转 HTTP 429 响应 + message 给客户端；项目业务里直接抛 better-auth 自动转换；类型安全的错误协议"),
      sc("B", "原生 throw"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "APIError = better-auth 错误协议 → 自动 HTTP 状态码。" },
    abilityTags: ["ai.review.architecture", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 双层错误",
    prompt: "sendMagicLink 内 try { peek 限流 } catch { throw or log } 然后另一 try { 发邮件 } catch { 抛 INTERNAL_SERVER_ERROR }——为什么这样分？",
    options: [
      sc("A", "限流 peek 失败（DO 异常）应「放行」（保业务可用）—— 业务限流不能因副作用基础设施失败拒服务；邮件发送失败应「拒绝」并 log（用户必须知道）；按业务影响分级处理"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "限流故障放行 + 邮件故障拒绝 = 按业务影响分级。" },
    abilityTags: ["ai.review.architecture", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 authInstances Map 缓存",
    prompt: "const authInstances = new Map<string, ReturnType<typeof betterAuth>>();——为什么按 origin 缓存？",
    options: [
      sc("A", "betterAuth 实例创建有开销（plugins 初始化 + DB adapter）；同 origin 多次 getAuth 共享一个实例；不同 origin（如 localhost vs prod）各持一个；按 key 缓存避免重建"),
      sc("B", "随机"),
      sc("C", "性能差"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "按 origin Map 缓存 = 实例复用 + 多环境隔离。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 Proxy 默认导出",
    prompt: "export const auth = new Proxy({}, { get(_, prop) { return (getAuth() as ...)[prop]; } });——为什么 Proxy？",
    options: [
      sc("A", "兼容旧代码 import { auth }——但每次 .api.xxx 时才调 getAuth() 拿当前实例；不传 request 走默认 origin；既保持简单 API 又不需调用方知道动态实例化；适配迁移"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Proxy = 旧 API 兼容 + lazy 实例化——迁移友好。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 sessionCache WeakMap",
    prompt: "const sessionCache = new WeakMap<Request, Promise<AuthSession>>();——为什么 WeakMap + 按 Request 键？",
    options: [
      sc("A", "同一 Request 单次生命周期可能多次 getSessionCached（loader + headers + 路由内复用） → 同 promise 复用减重复查 DB；WeakMap 键弱引用 Request gc 后自动清；按请求作用域的缓存"),
      sc("B", "全局 Map"),
      sc("C", "无缓存"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "WeakMap<Request, Promise> = 请求作用域缓存 + gc 友好。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 promoteConfiguredAdmin",
    prompt: "if (isAdmin(user.email) && user.role !== 'admin') { ... update role = 'admin' }——什么模式？",
    options: [
      sc("A", "ADMIN_EMAILS env var 配置的邮件登录后自动 promote 到 admin role；运维/部署时声明性配置 → 自动同步到 DB；无需手动 SQL；声明式管理员"),
      sc("B", "运行时风险"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ADMIN_EMAILS env → 自动 promote = 声明式管理员配置。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 isActiveBan 双因素",
    prompt: "isActiveBan(user) = user.banned && (无 banExpires || banExpires > now)——为什么两个条件？",
    options: [
      sc("A", "banned 标志位告诉「此号被封」；banExpires 控时长（无 = 永封，有 = 临时禁解）；解禁靠时间过期或人工改 banned；双字段支持永封 + 临时封 + 自动解禁三态"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "banned + banExpires = 永封 + 临封 + 自动解禁三状态。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 toPublicSession 收窄",
    prompt: "toPublicSession 把 session.user 收窄成 PublicSession 子集——为什么不直返 raw？",
    options: [
      sc("A", "raw session 含敏感字段（密码 hash、refresh token、accountId）—— 显式 pick 安全字段（id/email/name/image/role 等）防泄漏；类型签名也告诉调用方「这些是公开的」；数据脱敏 + 接口契约"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "PublicSession = 显式 pick 安全字段——脱敏 + 契约。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 auth.server.ts 整体哲学",
    prompt: "auth.server.ts 的整体哲学？",
    options: [
      sc("A", "1) 多 provider 并存（google/microsoft/magicLink/oneTap） 2) baseURL 动态适配多环境 3) trustedOrigins 多源聚合防 CSRF 4) plugins 模式拓展（admin/microsoft-workers-callback hack） 5) 五重并发限流 peek 6) 双层错误（限流故障放行 + 邮件失败拒绝） 7) authInstances Map + sessionCache WeakMap 双缓存 8) Proxy 默认导出兼容旧 API 9) ADMIN_EMAILS 自动 promote 声明式配置 10) toPublicSession 数据脱敏；综合：「多 provider + 多环境 + 多缓存 + 多守卫 + 数据脱敏」五件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "auth.server 10 原则——better-auth 集成层纪律。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
];
