/**
 * Real questions for site-16-auth-session / protected-routes.
 * Anchor: remix/app/routes/chat.tsx —— 受保护路由模式：loader 内 try { await requireNemesisUser(request) } catch (Response 401) { throw redirect('/auth?returnTo=...') } + Cache-Control: private, no-store
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/routes/chat.tsx";
const sc = (id: string, text: string) => ({ id, text });

export const protectedRoutesQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 守门函数",
    prompt: "loader 内 await ____ (request);——失败抛 401 Response。",
    options: [],
    blanks: [{ id: "v", placeholder: "函数名", acceptedAnswers: ["requireNemesisUser"] }],
    correctAnswer: { type: "fill_blank", values: { v: "requireNemesisUser" } },
    explanation: { short: "requireNemesisUser = 项目守门函数。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/services/nemesis-auth.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q2 守门 + 重定向流程",
    prompt: "try { await requireNemesisUser(request); } catch (error) { if (error instanceof Response && error.status === 401) throw redirect(`/auth?returnTo=${...}`); throw error; }——这个模式？",
    options: [
      sc("A", "守门函数抛 401 Response —— route 内 catch 把 401 转成「重定向到登录页 + returnTo 记当前 URL」；登录后回原页面；UX 完整；非 401 错误（500 等）继续抛框架处理"),
      sc("B", "纯 throw"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "401 → redirect to login + returnTo —— 受保护路由 UX 标准模式。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 returnTo 参数",
    prompt: "encodeURIComponent(url.pathname + url.search)——为什么编码？",
    options: [
      sc("A", "URL 参数值含特殊字符（&/?/#/=）必须编码——否则会破坏 URL 结构（提前结束/键值混淆）；登录页拿到后 decodeURIComponent 恢复原 URL；URL 编码标准"),
      sc("B", "可省略"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "URL 参数必编码 = 防特殊字符破坏结构——HTTP 标准。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 login 页 returnTo 处理",
    prompt: "/auth?returnTo=%2Fchat 收到后——登录页应该？",
    options: [
      sc("A", "1) decode 拿原 URL 2) 验证安全（必须以 / 开头防开放重定向） 3) 登录成功后 navigate(returnTo) 4) 缺省返首页；安全 + 体验"),
      sc("B", "永跳首页"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "returnTo 处理 = decode + 安全校验 + redirect——防开放重定向。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/routes/auth.tsx"],
  }),
  q({
    type: "single_choice", title: "Q5 开放重定向漏洞",
    prompt: "如果登录页直接 navigate(returnTo) 不校验—— 攻击场景？",
    options: [
      sc("A", "攻击者构造 /auth?returnTo=https://evil.com → 用户登录后跳钓鱼站；必须验证 returnTo 是相对路径（以 / 开头）或同源 URL；Open Redirect 是 OWASP 常见漏洞"),
      sc("B", "无害"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "无校验 returnTo = Open Redirect 漏洞——必须验证同源。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 throw redirect vs return redirect",
    prompt: "loader 用 throw redirect(...) 而不 return redirect(...)——差异？",
    options: [
      sc("A", "throw 立即终止 loader 执行 → 框架捕获 Response 直接发；return 也可（loader 协议两种都接）但 throw 表达「这是异常退出」语义更清晰；catch 块内必 throw 因 catch 已经在 try 内不能 return loader 数据"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "throw redirect = 短路 + 语义异常退出；catch 块内必 throw。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 Cache-Control: private, no-store",
    prompt: "loader 返 headers: { 'Cache-Control': 'private, no-store', 'Vary': 'Accept-Encoding' }——为什么这两条？",
    options: [
      sc("A", "private: CDN 共享缓存禁止存（chat 页含登录态）；no-store: 浏览器/中间代理也不存；Vary:Accept-Encoding 让 gzip/br 编码各自分桶；登录态页缓存安全标准搭配"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "private/no-store/Vary = 登录态页缓存安全标准三件。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q8 export const headers",
    prompt: "export const headers: HeadersFunction = forwardLoaderCacheControl;——作用？",
    options: [
      sc("A", "v3_singleFetch 模式下 loader 设的 Cache-Control 不会自动写到文档响应；headers 函数从 loaderHeaders 提取 Cache-Control + Vary 转发到响应头；不导出 headers 缓存策略失效"),
      sc("B", "可选"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "headers 转发 = v3_singleFetch 协议必备；不导出 = 头丢失。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/cache-headers.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q9 受保护路由位置",
    prompt: "守门为什么放 loader 而不是组件 useEffect？",
    options: [
      sc("A", "loader 服务端跑 SSR 阶段就守门 → 未登录用户连 HTML 都不会拿到 chat 页（直接 302 到 /auth）；放 useEffect 浏览器才检查 → 已经渲染敏感数据 + 闪烁；服务端守门是正确位置"),
      sc("B", "等价"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader 守门 = SSR 阶段就拒；useEffect 守门 = 已渲染敏感闪烁。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 多个受保护路由的复用",
    prompt: "/chat、/messages（写） 等都需要登录——怎么避免重复？",
    options: [
      sc("A", "1) 抽 requireNemesisUser 一个函数所有 loader 调 2) 父级 layout route 的 loader 守门（子路由都受保护）3) 共享守门函数 + try/catch 模式；本项目用方法 1 + 3"),
      sc("B", "复制粘贴"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "守门函数复用 + 父 layout 守门 = 受保护路由常见两套方案。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q11 401 vs 403",
    prompt: "守门返 401 而不是 403——差异？",
    options: [
      sc("A", "401 Unauthorized = 「你没登录或登录失效」（重新登录可解决）；403 Forbidden = 「你已登录但无权限」（没救要管理员开权）；本项目守门是「未登录」用 401 → redirect 到登录；语义精确"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "401 = 未登录可补救；403 = 无权限无解——HTTP 语义精确。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 chat 页内组件",
    prompt: "default function ChatRoute() { return <NemesisChatPage />; }——为什么页只一个组件？",
    options: [
      sc("A", "loader 已守门 + 缓存头设好；UI 单一职责调 client 组件；ChatRoute 只是 route 适配器（loader/headers/meta + 组件 mount）；分层使路由层薄业务层厚"),
      sc("B", "未实现"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "ChatRoute 薄 + NemesisChatPage 厚 = 路由适配 + 业务分层。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "shared", touchedFiles: [PRIMARY, "app/components/nemesis/chat/NemesisChatPage.client.tsx"],
  }),
  q({
    type: "single_choice", title: "Q13 meta 函数",
    prompt: "export const meta: MetaFunction = () => pageMeta.chat();——为什么集中？",
    options: [
      sc("A", "pageMeta 是 seo 工具集中 SEO 元数据（title/description/og/canonical）；多页路由都调避免散乱；改 SEO 策略一处修改全局生效；统一性"),
      sc("B", "直接 hardcode"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "pageMeta 集中 = SEO 一致性 + 改一处生效全局。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/utils/seo.ts"],
  }),
  q({
    type: "single_choice", title: "Q14 错误：守门后再 useEffect 检查",
    prompt: "客户端 NemesisChatPage 内还 useEffect 查 user—— 必要吗？",
    options: [
      sc("A", "不必——loader 已保证渲染时必登录；useEffect 重复检查多余 + 增加 hydration 复杂度；信任 loader 守门 + 子组件 props 接 user 即可；DRY"),
      sc("B", "必要"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "信任 loader 守门 = 客户端不重复检查——DRY。" },
    abilityTags: ["frontend.effect.useEffect", "ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 错误：未保护路由暴露",
    prompt: "如果忘了写 loader 守门——后果？",
    options: [
      sc("A", "未登录用户可访问 chat 页 → 看到 UI 但 API 调用 401 → 体验崩；更糟若 loader 内有 DB 查直接暴露用户私有数据；受保护路由必须守门——清单审计"),
      sc("B", "可接受"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "未守门 = 私有数据 + UI 暴露——必须清单审计。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 错误：returnTo 未编码",
    prompt: "若 returnTo 不 encodeURIComponent——后果？",
    options: [
      sc("A", "URL 含 & ? # 等会破坏 query 解析（被分成多个参数或被截断）；登录后 returnTo 解析错误 → 跳转到错误页或失败；URL 编码必备"),
      sc("B", "正常"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "未编码 returnTo = URL 结构破坏；编码必备。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 加新受保护页",
    prompt: "新增 /messages 编辑页——loader 该写什么？",
    options: [
      sc("A", "复用 chat.tsx 模板：try { user = await requireNemesisUser(request); } catch (e) { if (e instanceof Response && e.status === 401) throw redirect(`/auth?returnTo=...`); throw e; } + Cache-Control private/no-store + headers forwardLoaderCacheControl + meta；模板化"),
      sc("B", "纯组件"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "新受保护页 = chat.tsx 模板复制——一致性。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 layout 级守门",
    prompt: "若把 chat/messages/profile 都放 /app/* 下用一个 layout loader 守门——优势？",
    options: [
      sc("A", "1) 子路由 loader 不必各自写守门 → DRY 2) 加新受保护页只放 /app/* 即可 3) 改守门策略一处生效；缺点：所有 /app/* 路径强制守门即使个别页想公开；适合所有子页同需登录的场景"),
      sc("B", "无优势"),
      sc("C", "性能差"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "layout 级守门 = DRY 但缺乏例外灵活性——按场景选。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 admin 守门",
    prompt: "admin 路由用 requireAdmin 而非 requireAuth——做了什么额外？",
    options: [
      sc("A", "requireAdmin 内部除了 requireAuth 还查 user.role 或 user.email 是否在 ADMIN_EMAILS 内 + 检查 isActiveBan + 失败 throw redirect('/') 不显示登录页（普通用户也无意义看登录）；分级守门"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "requireAdmin = requireAuth + role 校验 + ban 检查 + 失败跳首页——分级。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/lib/auth.server.ts"],
  }),
  q({
    type: "single_choice", title: "Q20 调试 401",
    prompt: "用户反馈登录后访问 chat 页还是被踢回 /auth——怎么调？",
    options: [
      sc("A", "1) DevTools 看登录 Set-Cookie 是否成功 2) chat 页请求是否带 cookie（Headers Cookie：…）3) 服务端 console 看 [BetterAuth] log 看 session 查找结果 4) D1 表查 session 行 expiresAt 5) 检查 cookie 域名/路径配置；分层调试"),
      sc("B", "刷新"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "401 调试 = 5 层逐查（Set-Cookie + 请求 cookie + 服务日志 + DB session + 域路径）。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 客户端 fetch 受保护 API",
    prompt: "客户端 fetch('/api/some-protected') 收到 401——怎么处理？",
    options: [
      sc("A", "1) UI 显示「请先登录」+ 引导到 /auth?returnTo=当前页 2) 全局拦截器检测 401 自动跳登录 3) 失败 retry 一次（可能是 session 临时刷新中）；不要直接弹错误对话框（UX 差）；登录引导优先"),
      sc("B", "弹错"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "客户端 401 = 引导登录 + 记当前 URL——UX 优先。" },
    abilityTags: ["ai.review.architecture", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "client", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 protected-routes 整体哲学",
    prompt: "受保护路由整体哲学？",
    options: [
      sc("A", "1) loader 服务端守门（不放 useEffect） 2) requireNemesisUser 抛 401 Response 3) catch 转 redirect to /auth + returnTo 4) returnTo 必 encode + 登录页同源校验防 Open Redirect 5) Cache-Control: private, no-store + Vary 6) export headers forwardLoaderCacheControl 转发 7) throw redirect 短路控制流 8) 受保护页面薄路由层 + 厚业务组件 9) 401 vs 403 语义精确 10) admin 用 requireAdmin 含 role + ban 检查 11) layout 级守门可 DRY；综合：「服务端守门 + 安全 returnTo + 缓存私有 + 错误码精确 + 分级」五件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "受保护路由 11 原则——登录守门纪律。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
];
