/**
 * Real questions for site-16-auth-session / session-cached.
 * Anchor: remix/app/lib/auth.server.ts —— getSessionCached 用 WeakMap<Request, Promise<AuthSession>> 单请求生命周期内 dedupe；requestHasAuthSessionCookie 仅看 cookie 头存在，省 DB
 */

import { q } from "../../types";
import type { RealQ } from "../index";

const PRIMARY = "app/lib/auth.server.ts";
const sc = (id: string, text: string) => ({ id, text });

export const sessionCachedQuestions: RealQ[] = [
  q({
    type: "fill_blank", title: "Q1 缓存数据结构",
    prompt: "const sessionCache = new ____ <Request, Promise<AuthSession>>();——选什么 Map 类型？",
    options: [],
    blanks: [{ id: "v", placeholder: "类型", acceptedAnswers: ["WeakMap"] }],
    correctAnswer: { type: "fill_blank", values: { v: "WeakMap" } },
    explanation: { short: "WeakMap 弱引用键 → Request gc 时自动清。" },
    abilityTags: ["code.position.handler"], sourceFilePath: PRIMARY, layer: "code-reading",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q2 单次请求多次 getSession 场景",
    prompt: "为什么一次请求会多次需要 session？",
    options: [
      sc("A", "1) root loader 拿 user 信息渲染 Header 2) 子路由 loader 校验 user.id 3) headers 函数读 user 决定缓存策略 4) 子组件 useLoaderData 间接依赖 5) 中间件守门；多处都查 session DB 重复浪费 → 缓存 promise 共享一次"),
      sc("B", "只一次"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "loader 链多处查 session = 缓存必要——dedup。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q3 WeakMap vs Map",
    prompt: "用 WeakMap 不用 Map——动机？",
    options: [
      sc("A", "Map 强引用键 → 全局存活的 sessionCache 持有所有 Request 对象 → Request 永不 gc → 内存泄漏；WeakMap 弱引用键 → Request 没其他引用时键和值都被 gc；按请求生命周期自动清理"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "WeakMap = 自动 gc 友好；Map 会内存泄漏——必须 WeakMap。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q4 缓存 Promise 而非结果",
    prompt: "WeakMap<Request, Promise<AuthSession>>——为什么键 Promise 而不 AuthSession？",
    options: [
      sc("A", "并发场景：同一请求两个 loader 同时调 getSessionCached → 第一个 set Promise → 第二个直接 return 同 Promise 等同结果；如果存结果会有窗口期两次都查 DB；存 Promise 是 dedup 关键"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "缓存 Promise = 并发 dedup；缓存结果会重复查 DB。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q5 catch 内 sessionCache.delete",
    prompt: ".catch((error) => { sessionCache.delete(request); throw error; })——为什么删？",
    options: [
      sc("A", "失败的 promise 缓存住会让后续调用都返回 rejected promise（即使 DB 已恢复）；删除让下次重试；瞬时错误自动恢复"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "失败缓存清掉 = 瞬时错误可重试——可靠性。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q6 requestHasAuthSessionCookie",
    prompt: "AUTH_COOKIE_MARKERS 数组 + cookie 头 split + some 检查——这是什么优化？",
    options: [
      sc("A", "提前判断「请求有无登录态相关 cookie」；无 cookie 则 100% 未登录直接跳过 getSessionCached（省 DB 查 + better-auth 调用）；有 cookie 才走 getSession；省「公开请求」的 DB；常用大量游客访问场景"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "cookie 存在性预检 = 跳过未登录请求的 DB 查——大流量优化。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q7 AUTH_COOKIE_MARKERS 列表",
    prompt: "['better-auth', 'session_token', 'session-token', 'authjs', '__secure-better-auth']——为什么多个 marker？",
    options: [
      sc("A", "1) better-auth 多版本 cookie 名变迁 2) 历史遗留（authjs 是 NextAuth）3) Secure 前缀变体（__Secure-）4) 大小写变体；包含历史 + 现行所有可能名；any-match 即认为有 session"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "多 marker = 兼容历史 + 当前 + 变体——容错。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q8 toLowerCase()",
    prompt: ".trim().toLowerCase()——为什么？",
    options: [
      sc("A", "cookie 名理论上 case-sensitive 但有些代理/proxy 会改大小写；统一小写 + 用小写 marker 比较；防 'Better-Auth' vs 'better-auth' 不匹配；防御性"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "toLowerCase = 防代理大小写改造——防御性。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q9 includes 模糊匹配",
    prompt: "AUTH_COOKIE_MARKERS.some((marker) => name.includes(marker))——includes 而非 ===？",
    options: [
      sc("A", "cookie 名常带前缀如 __Secure-better-auth.session_token 或 __Host-session_token；includes 模糊匹配子串；如果只用 === 必列举所有完整名才中；includes 一处兼容多变体"),
      sc("B", "性能"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "includes 模糊匹配 = 一处兼容多前缀变体。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q10 root loader 用法",
    prompt: "root.tsx loader 内 if (requestHasAuthSessionCookie(request)) { session = await getSessionCached(request); } else { session = null; }——什么意图？",
    options: [
      sc("A", "公开页（首页/about）大多无登录 → 直接 session=null 不查 DB；登录用户访问才查；省「绝大多数请求」的 DB 调用；root loader 频次最高优化关键"),
      sc("B", "总查"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "root loader 高频访问 = 公开请求跳过 DB——大优化。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY, "app/root.tsx"],
  }),
  q({
    type: "single_choice", title: "Q11 better-auth getSession",
    prompt: "getAuth(request).api.getSession({ headers: request.headers })——内部做了什么？",
    options: [
      sc("A", "1) 解析 cookie 提取 session token 2) 查 DB session 表（按 token） 3) 校验 expiresAt 4) 关联 user 表取 user 信息 5) 返完整 AuthSession；通常 2-3 次 D1 RPC（session + user）"),
      sc("B", "纯计算"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "getSession = cookie 解析 + DB 查 + 校验 + 关联 user——多次 D1 调用。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q12 缓存范围",
    prompt: "sessionCache 范围是？",
    options: [
      sc("A", "全局 Module 级 WeakMap——单 worker 实例所有进程内共享；按 Request 键隔离请求；Worker 重启清空；适合「请求级 dedup」不适合跨请求长缓存"),
      sc("B", "跨 worker"),
      sc("C", "线程"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Module 级 WeakMap = 单 worker 共享 + 请求键隔离——请求级缓存。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q13 跨请求 session 缓存",
    prompt: "若想跨请求缓存 session（多请求复用）——可行吗？",
    options: [
      sc("A", "理论可行（按 token 缓存到 KV/DO）但风险大：1) session 撤销不立即 → 可能仍信任已 revoke session 2) 安全敏感数据缓存增加泄漏面 3) 5-30s 短缓存可考虑但需谨慎；项目选择只在单请求 dedup 安全保守"),
      sc("B", "总缓存"),
      sc("C", "无意义"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "跨请求 session 缓存可行但风险大；项目仅请求级 dedup——保守安全。" },
    abilityTags: ["ai.review.architecture", "code.position.handler"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q14 AuthSession 类型推导",
    prompt: "type AuthSession = Awaited<ReturnType<ReturnType<typeof getAuth>['api']['getSession']>>;——四层嵌套类型？",
    options: [
      sc("A", "typeof getAuth = (req?) => betterAuthInstance；ReturnType 拿到该实例；instance.api.getSession 是函数；ReturnType 拿其返回 Promise；Awaited 解 Promise 拿真值；类型派生避免手抄 better-auth 的 session shape"),
      sc("B", "无意义"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "类型派生 = better-auth 改 shape 时 TS 自动跟随——零手抄。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q15 错误：无缓存重复查",
    prompt: "若移除 sessionCache 直接每次 getAuth(req).api.getSession(...)——后果？",
    options: [
      sc("A", "单次请求可能 5+ 次 getSession 调用 → 5+ 次 DB 查（session + user）= 10-15 次 D1 RPC；累积 100-300ms 延迟；用户感知明显；缓存是必要优化"),
      sc("B", "等价"),
      sc("C", "性能"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "无缓存 = 单请求多次重复 DB 查——延迟累积。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q16 错误：用 Map 不 WeakMap",
    prompt: "若改 const sessionCache = new Map<...>()——后果？",
    options: [
      sc("A", "Request 对象永不 gc → 内存泄漏；Worker 长跑后 OOM 或被 Cloudflare kill；prod 故障；WeakMap 必须"),
      sc("B", "等价"),
      sc("C", "性能更好"),
      sc("D", "随机"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Map = 内存泄漏；WeakMap 必须——非可选。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q17 错误：未 catch promise",
    prompt: "若忘了 .catch 让失败 promise 留在缓存——后果？",
    options: [
      sc("A", "首次 DB 故障后所有 retry 都返同一 rejected promise（即使 DB 已恢复）→ 用户永久看到错误；catch + delete 让瞬时错误可恢复；缓存层稳定性"),
      sc("B", "正常"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "未 catch = 失败 promise 永久缓存 → 故障不能自愈。" },
    abilityTags: ["code.position.handler", "ai.review.architecture", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q18 测试 sessionCache",
    prompt: "怎么测 dedup 工作？",
    options: [
      sc("A", "1) mock getAuth(...).api.getSession 计调用次数 2) 同一 Request 调 2 次 getSessionCached 3) assert mock 只被调一次 4) 失败场景 + retry 验证 cache.delete 行为；spy + assert call count"),
      sc("B", "无法测"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "spy + 计调用次数 = dedup 测试核心。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q19 监控",
    prompt: "怎么监控 session 查询性能？",
    options: [
      sc("A", "1) console.log 调用频次（per request 几次）2) 用 console.time 测平均延迟 3) Cloudflare Analytics 看 D1 read row 数 4) 异常监控（rejected promise 比例）；多维度监控 session 链路；优化决策有据"),
      sc("B", "无监控"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "session 链路监控 = 频次 + 延迟 + DB 量 + 错误率——优化数据基础。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "production-debugging",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q20 SessionCache 替代品",
    prompt: "Remix loader API 已经有 deferred / cache 装饰——为什么还自建 sessionCache？",
    options: [
      sc("A", "Remix 内置缓存是 loader 级（同一 loader 不重复跑）；但 session 跨多个 loader 调用 + headers 函数 + service 内部都需要——loader 装饰器无法跨函数 dedup；自建 WeakMap 跨调用点共享；专项优化"),
      sc("B", "重复"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "Remix 内置 = loader 级；自建 WeakMap = 跨函数 dedup——专项优化。" },
    abilityTags: ["bridge.reactRouter.loader", "code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q21 cookie 预检 vs DB 查",
    prompt: "requestHasAuthSessionCookie 与 getSessionCached 关系？",
    options: [
      sc("A", "前者 O(1) 字符串扫描判断「可能有登录态」；后者 O(DB) 查实际 session；前者快速排除游客 + 后者校验登录用户；两层过滤：cookie 头存在性 → DB 真伪；分级降本"),
      sc("B", "等价"),
      sc("C", "随机"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "cookie 预检 + DB 查 = 两层过滤——分级降本。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
  q({
    type: "single_choice", title: "Q22 session-cached 整体哲学",
    prompt: "session 缓存层整体哲学？",
    options: [
      sc("A", "1) 单请求生命周期内 dedupe 多次调 session 2) WeakMap 防内存泄漏 3) 缓存 Promise 而非结果防并发 race 4) 失败 catch + delete 让瞬时错误可重试 5) cookie 头存在性预检跳过游客 DB 查 6) AUTH_COOKIE_MARKERS 多变体兼容历史 + 当前 7) Module 级缓存仅本 worker 8) 类型派生跟随 better-auth shape 9) 不跨请求缓存保安全 10) 与 root loader 频次最高一起优化；综合：「请求级 dedup + 内存安全 + 失败自愈 + cookie 预检 + 类型自动派生」五件事"),
      sc("B", "纯习惯"),
      sc("C", "Cloudflare"),
      sc("D", "TypeScript"),
    ],
    correctAnswer: { choiceId: "A" },
    explanation: { short: "session-cached 10 原则——session 查询缓存层纪律。" },
    abilityTags: ["code.position.handler", "ai.review.architecture"],
    sourceFilePath: PRIMARY, layer: "ai-review",
    serverClientBoundary: "server", touchedFiles: [PRIMARY],
  }),
];
